### DISCUSSION TITLE
index for standalone milvus server

### DISCUSSION THREAD

**Discussion by QunBB** [milvus-io/milvus#12166] [Q&A and General discussion] [answered]
I see the Q&A in https://milvus.io/docs/v1.1.1/performance_faq.md#Does-searching-while-inserting-affect-the-search-speed

_Does searching while inserting affect the search speed?_

- As of v0.9.0, if Milvus has started creating indexes for the newly inserted vectors, an incoming vector search interrupts the index creation process, causing a delay of about one second.

> So, my question is:

**If my milvus server is standalone(only cpu), and some programs keeps searching milvus on online, does it mean that the index of newly inserted vectors will never build successfully because it is always been interrupted by search jobs?**

**And my test likely proves it.**

**Comment by yhmo** [comment, marked as answer]
Yes, you are right. If a server continually/frequently receive search request, the index jobs will never finished.

Solution is: create one write node and 1 ~ n read-only nodes, the write node handle create/delete/insert/index, the read-only nodes handle search request.

**Reply by QunBB** [reply]
Thanks for your answer!
But, my write node always shut down when i insert 500K vectors and create index(ANNOY) in v1.1.1?
I am really confused, because there is nothing about error logs

**Reply by yhmo** [reply]
ANNOY index is seldom used, maybe it is a bug. Could you provide more information so that I can try reproduce it on my local:
- vector dimension
- the index_file_size value of the collection
- your write node hardware memory capacity
- the cache_size value in the server_config.yaml
- the index parameters of the ANNOY index
- your client operation steps

**Reply by QunBB** [reply]
I think it is a bug, because it will happen every time. And it disappears when i change other index type and don not change any operation steps
- vector dimension

  512

- the index_file_size value of the collection

  1024

- your write node hardware memory capacity

  16G

- the cache_size value in the server_config.yaml

  ```yaml
  version: 0.5
  
  cluster:
    enable: true
    role: rw
  
  general:
    timezone: UTC+8
    meta_uri: mysql://{username}:{password}@{hostname}:3306/milvus
  
  network: 
    bind.address: 0.0.0.0
    bind.port: 19531
    http.enable: true
    http.port: 19122
  
  storage:
    path: /var/lib/milvus
    auto_flush_interval: 1
  
  wal:
    enable: false
    recovery_error_ignore: false
    buffer_size: 256MB
    path: /var/lib/milvus/wal
  
  cache:
    cache_size: 4GB
    insert_buffer_size: 1GB
    preload_collection:
  
  gpu:
    enable: false
    cache_size: 1GB
    gpu_search_threshold: 1000
    search_devices:
      - gpu0
    build_index_devices:
      - gpu0
  
  fpga:
     enable: false
     search_devices:
       - fpga0
  
  logs:
    level: debug
    trace.enable: true
    path: /var/lib/milvus/logs
    max_log_file_size: 1024MB
    log_rotate_num: 0
    log_to_stdout: true
    log_to_file: true
  
  metric:
    enable: false
    address: 0.0.0.0
    port: 9091
  
  ```

  

- the index parameters of the ANNOY index

  ```
  {'n_trees': 10}
  ```

- your client operation steps

  ```python
  import time
  import random
  import numpy as np
  
  from milvus import Milvus, IndexType, MetricType, Status
  
  
  insert_num = 100000
  dim = 512
  partition_num = 5
  
  collection_name = "test13"
  
  milvus = Milvus(host=hostname, port='19531')
  
  param = {'collection_name': collection_name, 'dimension': dim,
           'index_file_size': 1024, 'metric_type': MetricType.IP}
  ret = milvus.create_collection(param)
  print(ret)
  print(ret.message)
  
  for i in range(partition_num):
      milvus.create_partition(collection_name, 'tag_' + str(i))
      ret = milvus.insert(collection_name=collection_name,
                          records=np.random.random([insert_num, dim]).tolist(),
                          ids=list(range(i * insert_num, (i + 1) * insert_num)),
                          partition_tag='tag_' + str(i)
                          )
  
      print(ret[0])
  
  
  status = milvus.flush([collection_name])
  print("flush: ", status)
  
  time.sleep(2)
  
  print("begin to create index")
  
  ivf_param = {'n_trees': 10}
  ret = milvus.create_index(collection_name, IndexType.ANNOY, ivf_param)
  print(ret)
  print(ret.message)
  
  milvus.close()
  ```
