### DISCUSSION TITLE
after drop collection, can auto clear relative storate in disk in local volumes dir

### DISCUSSION THREAD

**Discussion by rocke-dong** [milvus-io/milvus#16506] [Q&A and General discussion]
Dear ALL,

I use milvus 2.0.2, after drop collection, the local "volumes" dir storage size  is not change, that's the sub dir minio and milvus is not auto delete.
Could it auto del the storage file after drop collection?
thanks a lot in advance!!

https://milvus.io/docs/v1.1.0/storage_operation.md
The formal docs seems not work, that's the background cleanup does not work
The background cleanup task deletes the collection (including its partitions and segments) marked as deleted from the metadata and deletes the corresponding data files and folders from the disk. If there is an operation being performed on the collection before the delete operation is called, the segment is deleted after the previous operation is completed.

**Comment by yhmo** [comment]
In 2.0, after a collection was deleted, its segments still keep in minio, until internal garbage collection. The time interval of gc is defined in milvus.yml:
```
dataCoord:
  gc:
    interval: 3600 # gc interval in seconds
    missingTolerance: 86400 # file meta missing tolerance duration in seconds, 60*24
    dropTolerance: 86400 # file belongs to dropped entity tolerance duration in seconds, 60*24
```
