### DISCUSSION TITLE
How can i connect to milvus on other machine

### DISCUSSION THREAD

**Discussion by QunBB** [milvus-io/milvus#18563] [Q&A and General discussion]
### How can i connect to milvus on other machine
The document just includes `kubectl port-forward` for the local: https://milvus.io/docs/v2.0.x/install_cluster-helm.md

### What i tried
I install milvus cluster(2.0) with helm on minikube.

And i want to connect to milvus on other machine, so i forward milvus services by ingress.
This is my operation:
`helm install my-release milvus/milvus -f values.yaml`
The content of values.yaml is:
```
ingress:
  enabled: true
  annotations:
    # Annotation example: set nginx ingress type
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/listen-ports-ssl: '[19530]'
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels: {}
  hosts:
    - milvus.test.mama.cn
```
```
NAME                     CLASS    HOSTS                      ADDRESS        PORTS     AGE
my-release-milvus        nginx    milvus.test.mama.cn        192.168.9.66   80        41d
```
But it failed!  
How do i achieve it?
