### DISCUSSION TITLE
High disc usage for insertion and indexing in Milvus Standalone

### DISCUSSION THREAD

**Discussion by vikesh-raj** [milvus-io/milvus#19161] [Q&A and General discussion]
High disk usage of Milvus Standalone
----

We are experimenting on Milvus Standalone v2.1.1 to store Binary encoding for around 25 Million vectors with 786 dimensions.
The total size of vectors on disk is around 3 GB.

The insertion and indexing operation is using huge disk utilization.

Here is the sample disk utilization :

milvus
├── data
│   └── files
│       ├── index_files    - 292 MB
│       ├── insert_log     - 196 GB
│       └── stats_log      - 63 GB
├── etcd-data        - 3.5 GB
├── rdb_data         - 6.5 GB
├── rdb_data_meta_kv - 76 MB
└── logs             - 6.2 GB

5000 vectors are inserted in one insert call to milvus. This takes around 30 minutes.

Even search queries are writing to the stats log, and the size of it grows with usage.
I have checked with https://github.com/milvus-io/milvus/issues/16606 , which has removed
the rocksmq on the search path, but the size of stats_log keeps on increasing.

The logs folder have proper log rotation with each log file of size 300 MB.
The error logs are repeated a lot, and the same log message is repeated thousands of times.

```
[2022/09/12 19:27:55.632 +05:30] [ERROR] [datacoord/garbage_collector.go:143] ["parse segment id error"] [infoKey=/files/stats_log/435938417046716417/435938417046716418/435939041080508417/100/435939046664437772] [error="path \"/files/stats_log/435938417046716417/435938417046716418/435939041080508417/100/435939046664437772\" does not contains rootPath \"files\""] [stack="github.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).scan\n\t/root/milvusrpm-2.1/milvus/internal/datacoord/garbage_collector.go:143\ngithub.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).work\n\t/root/milvusrpm-2.1/milvus/internal/datacoord/garbage_collector.go:96"]
[2022/09/12 19:27:55.632 +05:30] [ERROR] [datacoord/garbage_collector.go:143] ["parse segment id error"] [infoKey=/files/stats_log/435938417046716417/435938417046716418/435939041080508417/100/435939046677282822] [error="path \"/files/stats_log/435938417046716417/435938417046716418/435939041080508417/100/435939046677282822\" does not contains rootPath \"files\""] [stack="github.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).scan\n\t/root/milvusrpm-2.1/milvus/internal/datacoord/garbage_collector.go:143\ngithub.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).work\n\t/root/milvusrpm-2.1/milvus/internal/datacoord/garbage_collector.go:96"]
```

Is it possible to remove writing of insert_log & stats_log ?

Here is the relavent config that we are using :

```yaml
etcd:
    log:
        path: stdout
        level: error
    rootPath : files
    use:
        embed: false

localStorage:
    path: /data/milvus/data

minio:
    rootPath: files
    
rocksmq:
    path: /data/milvus/rdb_data

proxy:
    http:
        enabled: true
        debug_mode: false
    ginLogging : false

log:
    level: error
    file:
        rootPath: /data/milvus/logs
        maxSize : 300

common:
    storageType: local
```
