### DISCUSSION TITLE
milvus中kafka的配置

### DISCUSSION THREAD

**Discussion by solaim** [milvus-io/milvus#19768] [Q&A and General discussion] [answered]
```
# Related configuration of pulsar, used to manage Milvus logs of recent mutation operations, output streaming log, and provide log publish-subscribe services.
# pulsar:
#   address: localhost # Address of pulsar
#   port: 6650 # Port of pulsar
#   webport: 80 # Web port of pulsar, if you connect direcly without proxy, should use 8080
#   maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes, Maximum size of each message in pulsar.

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList: "172.100.100.10:9092"
#  saslUsername: username
#  saslPassword: password
#  saslMechanisms: PLAIN
#  securityProtocol: SASL_SSL

# rocksmq:
#   # please adjust in embedded Milvus: /tmp/milvus/rdb_data
#   path: /var/lib/milvus/rdb_data # The path where the message is stored in rocksmq
#   rocksmqPageSize: 2147483648 # 2 GB, 2 * 1024 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
#   retentionTimeInMinutes: 7200 # 5 days, 5 * 24 * 60 minutes, The retention time of the message in rocksmq.
#   retentionSizeInMB: 8192 # 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
#   compactionInterval: 86400 # 1 day, trigger rocksdb compaction every day to remove deleted data
#   lrucacheratio:  0.06 # rocksdb cache memory ratio
```

上面是milvus.yaml文件中关于消息队列的配置，但是启动后连接kafka的是127.0.0.1:9092：
```%3|1665655767.639|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: localhost:9092: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 6 identical error(s) suppressed)
%3|1665655771.082|FAIL|rdkafka#consumer-1| [thrd:localhost:9092/1]: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 6 identical error(s) suppressed)
```

请问milvus.yaml中如何正确的配置kafka？

**Comment by solaim** [comment, marked as answer]
```
kafka:
  brokerList: "172.100.100.10:9092"
  saslUsername: admin1
  saslPassword: kafka1
  saslMechanisms: PLAIN
  securityProtocol: SASL_PLAINTEXT
```
必须所有字段打开，配置的brokerList才会生效，否则只能连接到127.0.0.1:9092

盲猜是为了数据安全吧😂

**Comment by ElapsedSoul** [comment]
不知道是不是更新了，可以不使用 sas链接Kafka。

```yaml
mq:
  type: kafka

kafka:
  brokerList: "127.0.0.1:9092"
  saslUsername:
  saslPassword:
  saslMechanisms:
  securityProtocol:
  readTimeout: 10 # read message timeout in seconds
  ssl:
    enabled: false # Whether to support kafka secure connection mode
    tlsCert: 
    tlsKey:
    tlsCACert:
    tlsKeyPassword:

```

```https://milvus.io/docs/zh/connect_kafka_ssl.md```
帖子在这，以便后来人吧。
