### DISCUSSION TITLE
Where is data stored

### DISCUSSION THREAD

**Discussion by davidlis** [milvus-io/milvus#20095] [Q&A and General discussion] [answered]
Where is data for the inserted embeddings stored with the standalone version of Milvus?
(i understand that this is handled by minio but don't see where this lands by default)

Looking at the default `docker-compose`, I thought it would be in the anonymous volumes created along with the containers. But `sudo docker system df` says that the volumes have a size of 0B even after inserting lots of vectors into the DB.

Thank you

**Comment by yhmo** [comment, marked as answer]
The standalone docker-compose file is:
wget https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus-standalone-docker-compose.yml -O docker-compose.yml

In this yml file, you can see the configuration of minio:
```
minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
```
The "volumes" defines the storage path. After you start the standalone server by **docker-compose up -d**, you will see a folder "volumes" created under the path where you run the command. All the data files are stored in the **./volumes/minio**
