### DISCUSSION TITLE
StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet

### DISCUSSION THREAD

**Discussion by SamrudhiRRao** [milvus-io/milvus#20430] [Q&A and General discussion]
Milvus was working fine for a while and I wanted to insert data. When I released the collection, milvus crashed with the error "**StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet**". I recreated the docker image several times and even tried to reinstall docker but the error persists . The error is visble in Attu. 

Details:
Milvus: 2.1.4
ETCD: 3.5.0
minio: RELEASE.2022-03-17T06-34-49Z

The docker compose file has been taken from: https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus-standalone-docker-compose.yml

![image](https://user-images.githubusercontent.com/44149956/200758384-91ec4a4a-b450-4049-9788-59caf1cd8150.png)

**Comment by yhmo** [comment]
Please try to open an issue in github issues with logs.
If you deployed milvus by standalone, just use **`docker logs [container id]`** to collect logs.
If you deployed milvus by k8s, just follow this doc to export logs: https://github.com/milvus-io/milvus/tree/master/deployments/export-log

**Reply by ghost** [reply]
- [ ]

**Comment by liamsteadman** [comment]
Facing a similar issue. If I change the values of the Minio access/secret keys and provide the same values to the Milvus container with the MINIO_ACCESS_KEY/MINIO_SECRET_KEY env vars, these variables don't override the values Milvus is trying to access Minio with. Either the [documentation](https://milvus.io/docs/configure_minio.md) is wrong or the environment variables aren't being picked up by the Milvus container?

Note: Minio now expects the env vars on the Minio container to be called MINIO_ROOT_USER/MINIO_ROOT_PASSWORD, rather than MINIO_ACCESS_KEY/MINIO_SECRET_KEY.

**Reply by yhmo** [reply]
I just test on my local with Milvus v2.2.6, it works with the following steps:
1. In the docker-compose.yml, change the MINIO_ACCESS_KEY to be "somebody", change the  MINIO_SECRET_KEY to be "helloworld". I add a port mapping "9001:9001" so that I can verify the ACCESS_KEY/SECRET by login to http://localhost:9001/
  ```
minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: somebody
      MINIO_SECRET_KEY: helloworld
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    ......
```

2. In the docker-compose.yml, add a file mapping for the milvus.yaml
```
  standalone:
    container_name: milvus-standalone
    ......
    volumes:
      ......
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
```

3. Change the minio configuration in the milvus.yaml under the path ${DOCKER_VOLUME_DIRECTORY:-.} which will overwrite the inside configurations
```
minio:
  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: somebody # accessKeyID of MinIO/S3
  secretAccessKey: helloworld # MinIO/S3 encryption string
```

4. `docker-compose up -d`
5. Use python sdk to create a collection, insert some rows
6. Open the http://localhost:9001/ in web browser, input "somebody" as user name, input "helloworld" as password. I can successfully login, and I can see the milvus data files in the "a-bucket"
