### DISCUSSION TITLE
"fake_register_link "  milvusdm M2M migration issue

### DISCUSSION THREAD

**Discussion by tom729** [milvus-io/milvus#20929] [Q&A and General discussion]
I used milvusdm to do migration from 0.10.0 to 2.2.0, the source and dest milvus are running in docker, I configure the M2M.yaml as below:
`M2M:
  milvus_version: 2.2.0
  source_milvus_path: '/var/lib/docker/overlay2/3c023d25e8a5229845d34dcda8c22330160c9c7aa6985f2aa495728f312eaeaf/merged/var/lib/milvus/'
  `mysql_parameter:`
  source_collection: # specify the 'partition_1' and 'partition_2' partitions of the 'test' collection
    milvus_mepai:
  dest_host: '127.0.0.1'
  dest_port: 19531
  mode: 'skip' # 'skip/append/overwrite'`

when I ran the command :" milvusdm --yaml M2M.yaml"， get the error :
`2022-12-01 14:44:30,352 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 72 ｜ 
Addr [127.0.0.1:19531] fake_register_link
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "unknown service milvus.proto.milvus.MilvusService"
        debug_error_string = "{"created":"@1669877070.352357170","description":"Error received from peer ipv4:127.0.0.1:19531","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"unknown service milvus.proto.milvus.MilvusService","grpc_status":12}"
>
        {'API start': '2022-12-01 14:44:30.351606', 'RPC start': '2022-12-01 14:44:30.351861', 'RPC error': '2022-12-01 14:44:30.352528'}`

Can anyone help me out ? thanks

**Comment by yhmo** [comment]
Looks like the M2M.yaml is incorrect.
In the README, we provide a sample M2M.yaml:
```
M2M:
  milvus_version: 1.x
  source_milvus_path: '/home/user/milvus'
  mysql_parameter:
    host: '127.0.0.1'
    user: 'root'
    port: 3306
    password: '123456'
    database: 'milvus'
  source_collection: # specify the 'partition_1' and 'partition_2' partitions of the 'test' collection.
    test:
      - 'partition_1'
      - 'partition_2'
  dest_host: '127.0.0.1'
  dest_port: 19530
  mode: 'skip' # 'skip/append/overwrite'
```
From the yaml, we can see the "milvus_version" is pointing to the old version, not 2.2
