### DISCUSSION TITLE
I want to specify milvus to use a certain graphics card

### DISCUSSION THREAD

**Discussion by ingale726** [milvus-io/milvus#21412] [Q&A and General discussion]
My GPU server has 4 graphics cards. I use docker to launch standalone milvus. How do I specify which graphics card to use?

**Comment by yhmo** [comment]
Currently, only the v1.x version can support GPU.
The configurations are in the server_config.yaml of v1.x:
```
gpu:
  enable: true
  cache.enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0, gpu1
  build_index_devices:
    - gpu2
```

For example, **search_devices=gpu0, gpu1**,  milvus will use the graphic card No.0 and No.1 for search.
```
search_devices:
    - gpu0, gpu1
```
