### DISCUSSION TITLE
GPU search is particularly slow

### DISCUSSION THREAD

**Discussion by ingale726** [milvus-io/milvus#21476] [Q&A and General discussion]
I installed the milvus 1.1.0 GPU version and set the parameters
my docker image
`milvusdb/milvus:1.1.0-gpu-d050721-5e559c`

parameters
```
gpu:
  enable: true
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
```
I only have one video card,I inserted 3 million pieces of data.But it took me 21 seconds to search for a query
My video card model is Tesla T4, which has 16 gigabytes of video memory

Do I need to set any other parameters? Why is the search so slow?
