### DISCUSSION TITLE
Insertion scheme of 100 million level data

### DISCUSSION THREAD

**Discussion by ingale726** [milvus-io/milvus#21950] [Q&A and General discussion] [answered]
I have 140 million data, each data is converted into 64 dimensional vector, I want to implement Milvus second level retrieval, how should I store the data, can you give me an implementation plan?
My plan
```
version: v1.1.0
_DIM = 64  # dimension of vector
_INDEX_FILE_SIZE = 2048 
param = {
    'collection_name': collection_name,
    'dimension': _DIM,
    'index_file_size': _INDEX_FILE_SIZE,  # 
    'metric_type': MetricType.IP  # optional
}
milvus.create_collection(param)
index_param = {
    'nlist': 2048
}
milvus.create_index(collection_name, IndexType.IVF_SQ8, index_param)
```
hardware:
Number of Gpus: 4
GPU video memory :32G

Can such hardware handle data queries on such a large scale?
Can you give me some advice?

**Comment by yhmo** [comment, marked as answer]
140 million 64 dim, raw data size = 35GB
index_file_size = 2048MB, there are will be 16 ~ 18 segments, each segment contains 8 million vectors, according to the recommended nlist = 4 × sqrt(n),  nlist = 4 × sqrt(8000000) = 11313, nlist is better to power of 2, so nlist = 8192
index_param = {
    'nlist': 8192
}

4 Gpus, each device video memory=32GB, I think the hardware can handle the data(I suppose the data is static, not growing).

Pseudocode to insert and create index:
```
milvus.create_collection()
for(...) {
    milvus.insert(10000 vectors)
}
milvus.create_index()
```

Make sure the CPU memory can hold the data, set cache_size > 35GB (>40GB is better).
To use GPU to query, modify the "gpu" section of the **server_config.yaml**:
```
cache:
  cache_size: 40GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: true
  cache.enable: true
  cache_size: 16GB
  gpu_search_threshold: 0
  search_devices:
    - gpu0
    - gpu1
    - gpu2
    - gpu3
  build_index_devices:
    - gpu0
    - gpu1
    - gpu2
    - gpu3
```
