### DISCUSSION TITLE
delete collections

### DISCUSSION THREAD

**Discussion by ingale726** [milvus-io/milvus#22283] [Q&A and General discussion]
`utility.drop_collection(collection_name=collection)`
Can this code delete data and index files from the hard disk?

**Comment by yhmo** [comment]
The drop_collection() will mark all data files and index files as "to-be-deleted" state, but they still be kept in storage until the Milvus GC progress to clear them.
In the milvus.yaml, the section to define GC behavior:
```
  gc:
    interval: 3600 # gc interval in seconds
    missingTolerance: 86400 # file meta missing tolerance duration in seconds, 60*24
    dropTolerance: 3600 # file belongs to dropped entity tolerance duration in seconds
```
The 'dropTolerance' define the time gap for GC progress to clear the files. By default, the value is 3600 seconds, which means the "to-be-deleted" files will kept in storage for 1 hour.
