### DISCUSSION TITLE
transfering my collections

### DISCUSSION THREAD

**Discussion by MaLo94** [milvus-io/milvus#22300] [Q&A and General discussion] [answered]
How to transfer my collections from one server to another without any loss of data or conflicts in indexing or query nodes? 
A description of the way I did once and worked for me: 
I launched milvus and use it on my server with docker images in docker-compose I made as below:
  `etcd:`
    `  container_name: milvus-etcd`
    `  image: quay.io/coreos/etcd:v3.5.0`
    `  environment:`
      `    - ETCD_AUTO_COMPACTION_MODE=revision`
      `    - ETCD_AUTO_COMPACTION_RETENTION=1000`
      `    - ETCD_QUOTA_BACKEND_BYTES=4294967296`
      `    - ETCD_SNAPSHOT_COUNT=50000`
    `  volumes:`
      `    - etcd:/etcd`
    `  command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://*.*.*.*:****--data-dir /etcd`

  `minio:`
    `  container_name: milvus-minio`
    `  image: minio/minio:RELEASE.2022-03-17T06-34-49Z`
    `  environment:`
      `    MINIO_ACCESS_KEY: minioadmin`
      `    MINIO_SECRET_KEY: minioadmin`
    `  ports:`
      `    - "****:****"`
    `  volumes:`
      `    - minio:/minio_data`
    `  command: minio server /minio_data --console-address ":****"`
    `  healthcheck:`
      `    test: ["CMD", "curl", "-f", "http://localhost:****/minio/health/live"]`
      `    interval: 30s`
      `    timeout: 20s`
      `    retries: 3`

  `standalone:`
    `  container_name: milvus-standalone`
    `  image: milvusdb/milvus:v2.2.0`
    `  command: ["milvus", "run", "standalone"]`
    `  environment:`
      `    ETCD_ENDPOINTS: etcd:****`
      `    MINIO_ADDRESS: minio:****`
    `  volumes:`
      `    - milvus:/var/lib/milvus`
    `  ports:`
      `    - "****:****"`
    `  depends_on:`
      `    - "etcd"`
      `    - "minio"` 
  
after my milvus collections were ready, I made copy of my etcd, minio, and milvus volumes and transferred them to another server, then stopped and removed related containers and then created them again to restore the collection I had on the previous server. 
This solution worked for me, but in the past week when my collections in another server have lots of records (one of them has about 3 million objects) and I wanted to do the same approach as before, the unknown problem occurred! I checked the Attu that the collection loaded successfully, but when I want to check the data preview in Attu, I faced this error : 
"**fail to search on all shard leaders, err=fail to Query, QueryNode ID = 9, reason=Query 9 failed, reason Head "http://minio:9000/a-bucket/files/insert_log/...**" 
I do not know why this happened, cause I made tar files from my volumes to prevent corruption or losing data in transferring process, but the conflict just happened and I don't know how to fix it. 
do you have any recommendation or solution to fix this flow for me?! I investigated docs and found out that I can use Milvus-tools like migrating my collection, but I think there is no support for milvus 2.2.0. 

should i change the code of Milvus-service (i made) in the way to load collections at first? 

thanks in advance

**Comment by yhmo** [comment, marked as answer]
For standalone, there are three volumes to store milvus data:
1. volume of etcd to store metadata
2. volume of minio to store data files
3. volume of milvus server to store un-consumed data

To start milvus server successfully, the metadata and all data files must be strongly consist.
If milvus server is still running when you copy the volumes, the metadata and data files may be inconsistent. So, it is better to stop the entire service before you backup the volumes.

**Reply by MaLo94** [reply]
Thanks for your recommendation, I think you are so right. 
So just to make it clear, first of all, I should stop the milvus service (the 3 containers you and I mentioned) to be prepared to take backups from the 3 containers, and then transfer the copied volumes to another server. Right? and with just stopping the containers, are all the metadata and all data files going to be strongly consistent?

**Reply by yhmo** [reply]
Just stop the three containers: "milvus-etcd", "milvus-minio", "milvus-standalone", then copy the volumes to another server.

**Reply by MaLo94** [reply]
> Just stop the three containers: "milvus-etcd", "milvus-minio", "milvus-standalone", then copy the volumes to another server.

thanks a lot

**Reply by MaLo94** [reply]
> Just stop the three containers: "milvus-etcd", "milvus-minio", "milvus-standalone", then copy the volumes to another server.

Hello again,
I think there is something wrong with the process I did to take backups, and stop or start my milvus. 
I did the same thing as you said to take backups from my milvus collections, I stopped 3 containers and copied volumes related to these containers. But I wanted to make these collections bigger with new records of data, so I started them again without any changes on the same server (i did not use the backups I got, it's kind of restarting the 3 containers). After they started, I saw that the collections were loading in Attu. So In my `insertion_service` i did not load the collection as I noticed that they were loading automatically, but after a while, when I was inserting new records of my data in batch mode, again i faced with the same error: "**fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=Query 10 failed, reason NoSuchKey(key=files/insert_log/43911..)**" 
should I first load the collections by code and then start the process of insertion? 
or can you tell me what this problem relates to?? I think this is going to be a catastrophe as my stored records will be a lot in numbers!!

thanks in advance

**Reply by yhmo** [reply]
"NoSuchKey" indicates the metadata and data files is inconsistent. The etcd stores a meta point to "files/insert_log/43911.." but the data file doesn't exist on minio.
So, you restarted the server in this sequence:
1. stop milvus-etcd
2. stop milvus-minio
3. stop milvus-standalone
4. copy the three volumes
5. restart the containsers
6. insert new records

Seems is a bug if this steps can reproduce the error. I am not sure the root cause, maybe related to this issue: https://github.com/milvus-io/milvus/issues/20769

I will report this problem to core dev team, wait our response.

**Reply by MaLo94** [reply]
I did the same approach you mentioned, but the error keeps happening...
thanks in advance

**Reply by yhmo** [reply]
So, let's do a clean test by v2.2.0.
Firstly, prepare the docker-compose.yml file:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
And a python script to insert vectors:
```
import random
import uuid

from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)


_HOST = '127.0.0.1'
_PORT = '19530'

# Const names
_COLLECTION_NAME = 'demo'

# Vector parameters
_DIM = 128

# Index parameters
_METRIC_TYPE = 'L2'
_INDEX_TYPE = 'IVF_FLAT'
_NLIST = 1024


# Create a Milvus connection
def create_connection():
    print(f"\nCreate connection...")
    connections.connect(host=_HOST, port=_PORT)
    print(f"\nList connections:")
    print(connections.list_connections())


def insert_items(collection, items:[]):
    cnt = len(items)
    data = [
        [items[i]["Object_id"] for i in range(cnt)],
        [items[i]["Post_id"] for i in range(cnt)],
        [items[i]["pk"] for i in range(cnt)],
        [items[i]["Embedding"] for i in range(cnt)],
    ]
    collection.insert(data)
    print(cnt, "items inserted")


def gen_data():
    if utility.has_collection(_COLLECTION_NAME):
        collection = Collection(_COLLECTION_NAME)
    else:
        field1 = FieldSchema(name="Object_id", dtype=DataType.VARCHAR, max_length=512, is_primary=True)
        field2 = FieldSchema(name="Post_id", dtype=DataType.VARCHAR, max_length=512)
        field3 = FieldSchema(name="pk", dtype=DataType.INT64)
        field4 = FieldSchema(name="Embedding", dtype=DataType.FLOAT_VECTOR, dim=_DIM)
        schema = CollectionSchema(fields=[field1, field2, field3, field4])
        collection = Collection(name=_COLLECTION_NAME, data=None, schema=schema)
        print("\ncollection created:", _COLLECTION_NAME)

        index_param = {
            "index_type": _INDEX_TYPE,
            "params": {"nlist": _NLIST},
            "metric_type": _METRIC_TYPE}
        collection.create_index("Embedding", index_param)


    items = []
    batch_cnt = 10000
    for i in range(100000):
        item = {
            "Object_id": str(uuid.uuid1()),
            "Post_id": str(uuid.uuid1()),
            "pk": i,
            "Embedding": [random.random() for _ in range(_DIM)],
        }
        items.append(item)
        if len(items) >= batch_cnt:
            insert_items(collection, items)
            items = []

    if len(items) > 0:
        insert_items(collection, items)

    collection.flush()
    print("row count:", collection.num_entities)



if __name__ == '__main__':
    create_connection()
    gen_data()

```

Now begin test:
1. copy the docker-compose.yml to a folder, and start the milvus server by this command:
`docker-compose up -d`

2. run the python script to insert some rows

3. stop the milvus server with this command:
`docker-compose stop`

4. copy the volumes folder to another place:
`cp -r ./volumes  ../volumes`

5. restart the milvus server:
`docker-compose start`

6. run the python script again to insert some rows

I test the steps on my local, it works fine.
