### DISCUSSION TITLE
索引写入期间负载周期性飙高

### DISCUSSION THREAD

**Discussion by gy7779** [milvus-io/milvus#23392] [Q&A and General discussion] [answered]
Milvus2.2.5 进行索引写入测试，单线程，每次写入 1000 条。

索引配置参数如下：
 .withIndexType(IndexType.IVF_PQ)
 .withMetricType(MetricType.L2)
 .withExtraParam("{\"nlist\":16384,\"m\":32}")

![image](https://user-images.githubusercontent.com/89443035/231397115-96a0c7c7-fde2-437c-8cd7-6cf96ac9f387.png)
![image](https://user-images.githubusercontent.com/89443035/231399013-34481215-78ab-4e34-9642-6b9b111b5cfd.png)
索引写入期间，机器负载变化如上，每隔十分钟会升高一次，期间 CPU 使用 40% ，IO 情况如下：
![image](https://user-images.githubusercontent.com/89443035/231398236-404a698f-8521-4566-8e86-dce8ab30464c.png)

我注意到默认配置中 segment 写入周期为十分钟与负载升高规律相同，负载升高是由于此操作升高的吗？可有相关优化配置，解决负载周期升高的问题？

**Comment by yhmo** [comment]
当insert数据进来之后，并不会立即建索引，而是先累积在一个buffer中，datanode会检查这个buffer的大小是否超过segment.maxSize与sealProportion的乘积，默认是512MB*0.23=117MB。当buffer超过这个值，就会把数据flush到一个sealed segment中存入minio/s3。只有变成sealed segment之后，这些数据才会被拿去建索引。
```
dataCoord:
  segment:
    maxSize: 512 # Maximum size of a segment in MB
    # Minimum proportion for a segment which can be sealed.
    # Sealing early can prevent producing large growing segments in case these segments might slow down our search/query.
    # Segments that sealed early will be compacted into a larger segment (within maxSize) eventually.
    sealProportion: 0.23
```

如果buffer size一直没有超过这个值，则会在10分钟之后强制flush到sealed segment，milvus,yml中这个参数控制datanode的强制写入sealed segment行为：
```
dataNode:
  segment:
    # The period to sync segments if buffer is not empty.
    syncPeriod: 600 # Seconds, 10min
```

你插入的数据因为在10分钟之内没有达到117MB，所以每隔10分钟会产生一个sealed segment，然后indexnode去为这个sealed segment建索引，建索引消耗CPU，因此每隔10分钟CPU就忙一阵。

修改那几个参数可以改变CPU忙的时间。比如把syncPeriod改成5分钟，那就会每隔5分钟忙一次。但把这些值改小，意味着会产生size更小的sealed segment，后台的compaction操作定期会去合并小segment，大量的小segment不但会使查询性能下降，还会加重compaction的负担。
