### DISCUSSION TITLE
Setting log.file.maxSize via cURL

### DISCUSSION THREAD

**Discussion by wilsonlimaneto** [milvus-io/milvus#23714] [Q&A and General discussion]
Hello is it possible to set log.file.maxSize using **curl** command just like we can do to set the log level?

**Comment by yhmo** [comment]
I think it is not possible. The log configuration is defined in milvus.yaml. For standalone, you can change it directly. For cluster, you need to use the value.yaml to apply it.
```
# Configures the system log output.
log:
  level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  stdout: "true" # default true, print log to stdout
  file:
    # please adjust in embedded Milvus: /tmp/milvus/logs
    rootPath: "" # root dir path to put logs, default "" means no log file will print
    maxSize: 300 # MB
    maxAge: 10 # Maximum time for log retention in day.
    maxBackups: 20
  format: text # text/json
```
