### DISCUSSION TITLE
set authorizationEnabled as true, but invalid

### DISCUSSION THREAD

**Discussion by shatealaboxiaowang** [milvus-io/milvus#23784] [Q&A and General discussion]
set authorizationEnabled as true in milvus.yaml, but invalid because any user name and password can connect.
The deployment mode is cluster docker-compose

**Comment by yhmo** [comment]
I guess your steps to change the authorizationEnabled value is wrong.

Follow these steps:
1. start a cluster by following the official document
2. by default, the authorizationEnabled is False, you can connect to the server with any user/password
`connections.connect(host='127.0.0.1', port="19530", user="aaa", password="bbb")`

3. copy a milvus.yaml from a container
`docker cp [milvus proxy container id]:/milvus/configs/milvus.yaml .`
4. change the docker-compose.yml, mapping the /milvus/configs/milvus.yaml to outside for each milvus component. 

```
services:
  ......	

  rootcoord:
    container_name: milvus-rootcoord
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  proxy:
    container_name: milvus-proxy
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  querycoord:
    container_name: milvus-querycoord
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  querynode:
    container_name: milvus-querynode
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  indexcoord:
    container_name: milvus-indexcoord
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  indexnode:
    container_name: milvus-indexnode
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  datacoord:
    container_name: milvus-datacoord
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml


  datanode:
    container_name: milvus-datanode
    image: milvusdb/milvus:v2.2.5
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml

```

5. change the **common.security.authorizationEnabled** to True in the  ${DOCKER_VOLUME_DIRECTORY:-.}/milvus
```
common:
  security:
    authorizationEnabled: true
```

6. restart the cluster to make sure the authorizationEnabled=True takes effect.
`docker-compose restart`

7. try connect with any user/password
`connections.connect(host='127.0.0.1', port="19530", user="aaa", password="bbb")`
now you will get this error: "auth check failure, please check username and password are correct"

8. use the default user/password to connect
 `connections.connect(host='127.0.0.1', port="19530", user="root", password="Milvus")`
it works well


10.
