### DISCUSSION TITLE
Can't connect to GCS bucket

### DISCUSSION THREAD

**Discussion by cjer** [milvus-io/milvus#24573] [Q&A and General discussion]
Hello, I am trying to use GCS as the persistent storage for milvus (version 2.2.8). After trying to understand the configuration parameters and going over some of the code, this is the `milvus.yaml` relevant config I came up with:
```
minio:
  # address: "storage.googleapis.com"
  # port: 9000
  accessKeyID: "ACCESS_KEY" # Access key generated in GCS settings
  secretAccessKey: "SECRET" # Secret generated in GCS settings
  useSSL: false
  bucketName: "milvus-bucket" 
  rootPath: "milvus"
  useIAM: false
  cloudProvider: "gcp"
  iamEndpoint: ""
```

But this does not work. When loading the docker it crashes, and I can see these errors in the log:
```
...
[2023/05/31 12:05:04.213 +00:00] [WARN] [storage/minio_chunk_manager.go:108] ["failed to check blob bucket exist"] [bucket=ai2i] [error="The Access Key Id you provided does not exist in our records."]
panic: All attempts results:
attempt #1:The Access Key Id you provided does not exist in our records.
attempt #2:The Access Key Id you provided does not exist in our records.
attempt #3:The Access Key Id you provided does not exist in our records.
attempt #4:The Access Key Id you provided does not exist in our records.
attempt #5:The Access Key Id you provided does not exist in our records.
attempt #6:The Access Key Id you provided does not exist in our records.
attempt #7:The Access Key Id you provided does not exist in our records.
attempt #8:The Access Key Id you provided does not exist in our records.
attempt #9:The Access Key Id you provided does not exist in our records.
attempt #10:The Access Key Id you provided does not exist in our records.
attempt #11:The Access Key Id you provided does not exist in our records.
```

Can you help me with the right way to configure GCS?
