### DISCUSSION TITLE
Enabling Authentication for Milvus

### DISCUSSION THREAD

**Discussion by Pranav-NG** [milvus-io/milvus#24803] [Q&A and General discussion]
I have my Milvus Standalone Running in server.(By docker-compose)
The issue I have is my application is able to connect without having to enter the username and password by default.
This seems to be risky in having my documentation and collections in the server.
However , I have created multiple users and changed password for root user.

How to enable authentication in the server so that username and password is made mandatory

**Comment by yhmo** [comment]
To enable user authentication, you need to set `common.security.authorizationEnabled` as true in **milvus.yaml**.
Please read this doc: https://milvus.io/docs/authenticate.md

**Reply by Pranav-NG** [reply]
Thanks you for the reply and reference !
I understand that a change needs to be made in the config file  (milvus.yaml).

However , few questions on setting up the config file - 
For the setup I just used docker-compose file. What should I do to setup the config file. ?

The steps explained in this link (https://milvus.io/docs/configure-docker.md) is sort of confusing .

How to use milvus.yaml and docker-compose.yaml together.

**Reply by yhmo** [reply]
Steps:
1. create a directory named "test", cmd line cd to the this directory
2. download a milvus.yaml file into "test": `wget https://raw.githubusercontent.com/milvus-io/milvus/v2.2.9/configs/milvus.yaml`
3. download the docker-compose.yml into "test": `wget https://github.com/milvus-io/milvus/releases/download/v2.2.9/milvus-standalone-docker-compose.yml -O docker-compose.yml`
4. use text edit tool to edit the docker-compose.yml, add a line to the standalone section:
 ```
 standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml   # Add this line to map the milvus.yaml from inside container to outside
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```
5. use text edit tool to edit the test/milvus.yaml
```
common:
  security:
    authorizationEnabled: true
```
6. under the "test" directory, start the service by command `docker-compose up -d`
