### DISCUSSION TITLE
Unable to connect to Milvus deployed in Kubernetes

### DISCUSSION THREAD

**Discussion by superpandaaa** [milvus-io/milvus#24844] [Q&A and General discussion]
Hi ,
I have deployed a Milvus through Kubernetes and use ingress to set the port as default. But I cannot connect it through the function `connections.connect(host=my_elb_url)`. It is similar to this [discuss](https://github.com/milvus-io/milvus/discussions/23728). Could you help me with that?

Helm override Ingress file
```
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", 
       "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: ENV['ARN']
        alb.ingress.kubernetes.io/subnets: subnet-f161f386, subnet-f13fe7da, subnet-e30219a5
        # change the following as needed
        # find the eks-reco-dev-default-elb-sg security group id in AWS console
        alb.ingress.kubernetes.io/load-balancer-name: milvus
        alb.ingress.kubernetes.io/security-groups: sg-0185b0b7d9b0605b0
        alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
      rules:
        - host: ""
          path: "/"
          pathType: "Prefix"
```
When I try to connect it, it will return timeout although it is deployed. Setting port `80` or `19530` are both not working.

```
raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on http://internal-milvus-1144794966.us-east-1.elb.amazonaws.com:19530. Timeout)>
```

Is there a simple curl or grpcurl example to test? like `curl http://something.something/status` 

Great thanks!
