### DISCUSSION TITLE
How to fully delete data

### DISCUSSION THREAD

**Discussion by ramialt** [milvus-io/milvus#24875] [Q&A and General discussion] [answered]
**By fully deleting, I mean making the vector data completely and absolutely unrecoverable from all logs, storage, or indexes.** 

From what I understand, this type of deletion does not occur until compaction, as described in [How to Compact Data in Milvus?](https://milvus.io/blog/2022-2-21-compact.md). After compact, even the Time Travel function will not recover or search deleted data.
As for vector indexes, data will never be truly deleted from them, and so the index must be dropped and re-created. (1) Is that right so far?

(2) I am looking for a way to completely remove data like this once every X hours/days. Is there any way to do this? How would you recommend I go about this?
As far as I can tell, compaction is not ever run regularly, instead depending on the filesize/amount of deleted files.

EDIT: According to [this page](https://milvus.io/docs/v1.1.0/storage_operation.md), the compact operation ignores segments without a large enough number of soft-deleted vectors. **(3) How do I bypass this?**

**Comment by yhmo** [comment]
I suppose we are talking about Milvus v2.x.

Compaction operation can remove the deleted data permanently. If a segment is compacted, index node will rebuild index for it so that the index won't contain the deleted items.
You can manually call `collection.compact()` to force trigger compaction. But sometimes not all the segments are included to be compacted because there are some threshold configurations to control compaction behavior.

In the milvus.yaml, you can see these configurations related to compaction:
```
dataCoord:
  enableCompaction: true # Enable data segment compaction
  segment:
    smallProportion: 0.5 # The segment is considered as "small segment" when its # of rows is smaller than
    # (smallProportion * segment max # of rows).
    compactableProportion: 0.85 # A compaction will happen on small segments if the segment after compaction will have
    # over (compactableProportion * segment max # of rows) rows.
    # MUST BE GREATER THAN OR EQUAL TO <smallProportion>!!!
    expansionRate: 1.25 # During compaction, the size of segment # of rows is able to exceed segment max # of rows by (expansionRate-1) * 100%.

  compaction:
    enableAutoCompaction: true
```

There are more thresholds in the source code.
The internal configurations for datacoord is here:
https://github.com/milvus-io/milvus/blob/b67ec563d2e887a24ea459699ac3d29624b2f36e/internal/util/paramtable/component_param.go#L1410

There is a threshold to decide whether a segment can be compacted by a ratio of deleted entities. The default value is 0.2, that means only when the ratio exceeds 20% in a segment, this segment can be compacted.
```
// if total delete entities is large than a ratio of total entities, trigger single compaction.
func (p *dataCoordConfig) initSingleCompactionRatioThreshold() {
	p.SingleCompactionRatioThreshold = float32(p.Base.ParseFloatWithDefault("dataCoord.compaction.single.ratio.threshold", 0.2))
}
```
Decrease this threshold and call `collection.compact()` then you will see more segments are compacted. But we don't recommend to set this threshold to zero because anytime you delete an entity, one segment will be compacted automatically, this will bring high pressure to data management.
