### DISCUSSION TITLE
grafana里除了proxy和runtime项，其他几项下的面板均无指标，从promethues控制台也搜不到

### DISCUSSION THREAD

**Discussion by baijinge0310** [milvus-io/milvus#24952] [Q&A and General discussion]
milvus是一个运维同事根据网上教程安装的，使用的helm离线安装，目前运行良好
前几天想通过将values.yaml文件中的serviceMonitor的enabled项设置为true以打开监控功能，也是根据官网来的，但是由于部署milvus的服务器处于离线环境导致各种错误，如：
![image](https://github.com/milvus-io/milvus/assets/74445362/049dba8f-d864-463b-a884-e8b98dedbc84)
尝试安装了prometheus-operator时，好像只成功了一部分，因为是离线环境没拉取到所需镜像，然后再想使用values.yaml更新集群时换了一种报错：
![image](https://github.com/milvus-io/milvus/assets/74445362/73ebdc9e-13c1-492f-9d02-aa70cce533ba)
但是`kubectl get servicemonitors --all-namespaces`这行命令是有显示prometheus-operator安装成功的
<img width="647" alt="截屏2023-06-16 15 48 55" src="https://github.com/milvus-io/milvus/assets/74445362/50e95cf2-bebd-481f-9f95-ae5efdfdb6a0">
无果，只能另辟蹊径，根据svc.yaml配置文件找到线索
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus
    meta.helm.sh/release-namespace: milvus
  labels:
    app.kubernetes.io/instance: milvus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.2.8
    component: proxy
    helm.sh/chart: milvus-4.0.20
  name: milvus
  namespace: milvus
spec:
  ports:
  - name: milvus
    port: 19530
    nodePort: 32000
    protocol: TCP
    targetPort: milvus
  - name: metrics
    port: 9091
    nodePort: 32001
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: milvus
    app.kubernetes.io/name: milvus
    component: proxy
  sessionAffinity: None
  type: NodePort
```
metric可能从32001这个端口拉取，尝试访问了一下果然有东西，于是从单用docker起了一个prometheus和granfana，在prometheus.yml配置文件中增加了job，如图
<img width="541" alt="截屏2023-06-16 15 54 28" src="https://github.com/milvus-io/milvus/assets/74445362/05a0bd9c-2c7f-4346-bdde-57079b21ca8a">
然后granfana上使用了github上的json模版并批量删除了一些筛选条件，现在有指标了，但是只有proxy项和runtime项下的面板有指标，其他项下的指标观察其promsql后从prometheus控制台搜索也无果，如图
这是有指标推送的proxy项
<img width="1438" alt="截屏2023-06-16 15 56 31" src="https://github.com/milvus-io/milvus/assets/74445362/5fbbbdff-4ae8-4fd2-9a4a-5fc0cfaf092e">
这是无指标推送的querynode项
<img width="1008" alt="截屏2023-06-16 15 57 02" src="https://github.com/milvus-io/milvus/assets/74445362/a4521c29-d735-4426-ae03-1ba922015ae8">
从prometheus控制台也搜索不到
<img width="1440" alt="截屏2023-06-16 15 57 41" src="https://github.com/milvus-io/milvus/assets/74445362/048fa4b9-f74a-4af9-bb51-2ccdf121f2f3">
是不是集群版的milvus监控必须使用prometheus-operator来监控，必须通过一开始说的打开serviceMonitor才能行呢，我这种单开prometheus是不是就行不通呢
