### DISCUSSION TITLE
如何限制容器内存的大小

### DISCUSSION THREAD

**Discussion by hemin110** [milvus-io/milvus#25026] [Q&A and General discussion]
load to menory 的时候内存涨的很快，如果达到物理内存的90%的时候可能会load fail， 已经修改了配置文件中queryNode,cacheSize=8G,  容器中实际占用内存约15G。
有什么配置可以限制内存的占用吗？

**Comment by yhmo** [comment]
如果是docker-compose起的standalone，在docker-compose.yml文件中设置 deploy.resources.limits.memory
```
services:
  ......
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.9
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    deploy:
      resources:
         limits:
            cpus: "12.00"
            memory: 20G
         reservations:
            memory: 200M
```
