### DISCUSSION TITLE
Milvus Remote connection Timeout Issue

### DISCUSSION THREAD

**Discussion by krisskad** [milvus-io/milvus#25370] [Q&A and General discussion]
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio

  attu:
    container_name: attu
    image: zilliz/attu:v2.2.3
                                                                                                                                                                                                 1,1           

```

Im trying to connect to my standalone milvus with remote server: 

connections.connect("default", host="172.174.70.230", port="2379")

I Tried connecting with multiple ports like : 2379, 9000, 19530, 9091, 8000, 8080 but getting following error ->
```
MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 172.174.70.230:2379. Timeout)>
```

Please give me some solution to connect with my remote server. BTW http://172.174.70.230:8080/ is live - you can check in browser.
