### DISCUSSION TITLE
User authentication not working with helm chart config update

### DISCUSSION THREAD

**Discussion by moinuddinsyed** [milvus-io/milvus#25520] [Q&A and General discussion] [answered]
I have updated the values.yaml file with ``` authorizationEnabled: true```, but still when i try to login with a certain username and a wrong password it still connects.

I'm not sure where I'm going wrong on this one.
Any help would be deeply appreciated.

**Comment by yhmo** [comment, marked as answer]
Did you add this section to value.yaml and `helm upgrade` ?

```
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
```

**Reply by moinuddinsyed** [reply]
Works thanks

**Reply by TaoWolf** [reply]
Hello, may I ask if you are able to log in using the client after running Milvus with this extended yaml file added to your docker-compose.yml? In my case, I'm unable to log in with any username and password, which is quite frustrating!

**Comment by pingliu** [comment]
helm upgrade --install my-release milvus/milvus -n {namespace} -f custom.yaml

custom.yaml
```
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
```
