### DISCUSSION TITLE
如何使用milvus operator配置外部s3存储？

### DISCUSSION THREAD

**Discussion by Yato-song** [milvus-io/milvus#25568] [Q&A and General discussion]
大家好，我在尝试milvus集群连接外部s3，根据官方文档给的示例，我可以去配置s3的endpoint，ak，sk，但我不清楚去哪里指定我要连接的bucket，我的配置文件（milvus_cluster_default.yaml）如下
```
spec:
  mode: cluster
  dependencies: 
    storage: # Optional
      external: true # Optional default=false
      type: "S3" # Optional ("MinIO", "S3") default:="MinIO"
      secretRef: s3-secret
      endpoint: "s3.xxxxxx:8080"
```
不配置bucketname初始化milvus集群的时候就会报错：message: The specified bucket does not exist.
因为通过helm安装milvus operator失败了，所以才选择使用kubectl+yaml直接装的milvus operator，所以没办法通过values.yaml去修改配置，只能是去改milvus_cluster_default.yaml。我查看了CRD的定义，没有找到buckname相关的field，求大佬们指教
下面是CRD中storage的定义：
<img width="505" alt="image" src="https://github.com/milvus-io/milvus/assets/76236279/d7c8f466-53b9-4093-a4ed-e18dcc9d08ad">
