### DISCUSSION TITLE
releasing some partitions after load collection is not supported

### DISCUSSION THREAD

**Discussion by opendatamarket** [milvus-io/milvus#25650] [Q&A and General discussion]
```
standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```
07-17 16:51:29.363 [http-nio-48084-exec-5] INFO  i.m.c.AbstractMilvusGrpcClient - [logInfo,2441] - ReleasePartitionsParam{collectionName='pdf_data', partitionNames='[pdf_data_2]'}
07-17 16:51:29.469 [http-nio-48084-exec-5] ERROR i.m.c.AbstractMilvusGrpcClient - [logError,2449] - ReleasePartitionsRequest failed:
failed to release partitions, err=releasing some partitions after load collection is not supported[LoadParameterMismatched]
```
// load
List<String> partitionNames = new ArrayList<>();
        partitionNames.add(PdfDataMilvusConstant.PARTITION_NAME(roleId));
        milvusClient.loadPartitions(
                LoadPartitionsParam.newBuilder()
                        .withCollectionName(PdfDataMilvusConstant.COLLECTION_NAME)
                        .withPartitionNames(partitionNames)

// release
milvusClient.releasePartitions(
                ReleasePartitionsParam.newBuilder()
                        .withCollectionName(PdfDataMilvusConstant.COLLECTION_NAME)
                        .withPartitionNames(partitionNames)

```
