### DISCUSSION TITLE
How to add dataCoord configuration via Operator.

### DISCUSSION THREAD

**Discussion by harpreetpaul** [milvus-io/milvus#25776] [Q&A and General discussion] [answered]
I am trying to update Milvus instance managed through operator. I am trying to update gc config for dataCord component as shown below, but the configuration is not accepted by operator and complaining dataCord.gc is not valid as per schema. 
Can someone please point out what is the correct way to apply configurations for daatCood. 

```

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvusdb
  namespace: milvusdb
  labels:
    app: milvus
spec:
  mode: cluster
  components:  
    dataCoord:
      gc:
        interval: 600 # gc interval in seconds. Default 60*60
        missingTolerance: 43200 # file meta missing tolerance duration in seconds, 60*60*24
        dropTolerance: 43200 # file belongs to dropped entity tolerance duration in seconds. default 60*60*24

```

**Comment by LoveEachDay** [comment, marked as answer]
@harpreetpaul You should specify milvus config under `spec.config` like this:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvusdb
  namespace: milvusdb
  labels:
    app: milvus
spec:
  mode: cluster
  config:  
    dataCoord:
      gc:
        interval: 600 # gc interval in seconds. Default 60*60
        missingTolerance: 43200 # file meta missing tolerance duration in seconds, 60*60*24
        dropTolerance: 43200 # file belongs to dropped entity tolerance duration in seconds. default 60*60*24

```
