### DISCUSSION TITLE
Milvus Minio disk increasing exponentially v2.2.8

### DISCUSSION THREAD

**Discussion by harpreetpaul** [milvus-io/milvus#25814] [Q&A and General discussion]
Hi,

I am looking for a solution and / or recommendation to issue we recently started facing. We are running Milvus v2.2.8 on GKE cluster managed via Operator. Our Minio has started acting up lately. The allocated persistence storage is filling up quick and not getting released. Not able to find right solution to fix that issue. 

This is how my milvus resource looks like. Please advise 

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvusdb
  namespace: milvusdb
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies:
    storage: #
      external: false
      type: "MinIO" # Optional ("MinIO", "S3") default:="MinIO"
      inCluster:
        pvcDeletion: false
        values:
          persistence:
            size: 750Gi
          resources:
            limits:
              cpu: '2'
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 2Gi
          statefulset:
            replicaCount: 8
  components:
    queryNode:
      replicas: 3
      resources:
        limits:
          cpu: '2'
          memory: 12Gi
        requests:
          cpu: '2'
          memory: 8Gi
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '3'
          memory: 12Gi
        requests:
          cpu: '1'
          memory: 4Gi

  config:
    common:
      security:
        authorizationEnabled: true
      retentionDuration: 86400 
      entityExpiration: 86400 
    dataCoord:
      gc:
        interval: 3600 
        missingTolerance: 43200 
        dropTolerance: 43200 
```

**Comment by yhmo** [comment]
Milvus storage mechanism:
1. All the insert requests are stored into Pulsar before consuming by milvus data nodes and query nodes. If you inserted 100MB data, there will be 100MB+ data stored in Pulsar
2. Milvus data nodes persist data into MinIO, data is split into segments. Each segment size is different according to insert pattern(stream insert or batch insert). By default, a segment max size is 512MB. If there are some small segments, data nodes will compact small segments into large segment. After compaction, the old segments are marked as soft-deleted, waiting for garbage collection. Garbage collection triggered every 10 minutes. That is to say, if you inserted 100MB data, the data node might occupy 200Mb disk space.
3. Milvus index nodes build index for embeddings. Each segment has an independent index. Index size is different for different index type. Typically, IVF_FLAT/HNSW index size is a bit larger than original data, IVF_SQ8/IVF_PQ is about 25%~30% of the original data. That is to say, if you inserted 100Mb data, there might be 30MB ~ 100MB+ index data on the disk.
4. sometimes log files also occupy quite a lot disk space.

Generally, the disk space might be 2x~3x times of the original data.

**Reply by harpreetpaul** [reply]
Thanks for the explanation. 

Can you please help me understand what can i do to resolve MinIO High memory consumption. My Minio instance is topping at 99% memory consumption and same is with Pulsar Bookie. How can i allocate more memory to Minio and Pulsar nodes. 

Here my Kubernetes object
```

# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvusdb
  namespace: milvusdb-np
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: {}
    
  components:
    resources:
      limits:
        cpu: '4'
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 1Gi
    queryNode:
      replicas: 3
      resources:
        limits:
          cpu: '2'
          memory: 12Gi
        requests:
          cpu: '2'
          memory: 8Gi
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '3'
          memory: 12Gi
        requests:
          cpu: '1'
          memory: 4Gi
    dataCoord:
      replicas: 2
    queryCoord:
      replicas: 2
    rootCoord:
      replicas: 2
    indexCoord:
      replicas: 2
    indexNode:
      replicas: 3
      resources:
        limits:
          cpu: '3'
          memory: 12Gi
        requests:
          cpu: '1'
          memory: 4Gi
  config:
    common:
      security:
        authorizationEnabled: true
      # retentionDuration: 86400 # time travel reserved time, insert/delete will not be cleaned in this period. default 0
      # entityExpiration: 86400 # Entity expiration in seconds, CAUTION make sure entityExpiration >= retentionDuration and -1 means never expire
    dataCoord:
      enableActiveStandby: true
      gc:
        interval: 3600 # gc interval in seconds. Default 60*60
        missingTolerance: 43200 # file meta missing tolerance duration in seconds, 60*60*24
        dropTolerance: 43200 # file belongs to dropped entity tolerance duration in seconds. default 60*60*24
    queryCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
