### DISCUSSION TITLE
How to Configure S3 with Docker Compose on Milvus v2.2.11?

### DISCUSSION THREAD

**Discussion by wmwsagara** [milvus-io/milvus#25881] [Q&A and General discussion]
I have a working Milvus setup configured as per:
https://milvus.io/docs/install_standalone-docker.md

I need to configure Milvus setup to store entities on a S3 service.

I followed this:
https://milvus.io/docs/deploy_s3.md

Stop Milvus:
docker-compose down

Downloaded the milvus.yaml:
wget -c https://raw.githubusercontent.com/milvus-io/milvus/master/configs/milvus.yaml

Modified only the "minio:" as follows:
minio:
  address: rgw.ourdomain.com # Address of MinIO/S3
  port: 443 # Port of MinIO/S3
  accessKeyID: "<your_s3_access_key_id>" # accessKeyID of MinIO/S3
  secretAccessKey: "<your_s3_secret_access_key>" # MinIO/S3 encryption string
  useSSL: true # Access to MinIO/S3 with SSL
  bucketName: "<your_bucket_name>" # Bucket name in MinIO/S3
  rootPath: files # The root path where the message is stored in MinIO/S3
  useIAM: false
  cloudProvider: aws
  iamEndpoint:

And included milvus.yaml to docker-compose.yml as follows:
  minio:
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml

Start Milvus:
docker compose up -d

docker compose ps

curl 192.168.1.110:9091/api/v1/health
{"status":"ok"}

I created a collection. No file created on the S3 bucket!

What else requires to be done to complete the S3 configuration?

Appreciate your reply.

Many thanks in advance.

Best regards
Sagara

**Comment by yhmo** [comment]
https://milvus.io/docs/deploy_s3.md#Configure-S3-with-Docker-Compose

**Comment by wmwsagara** [comment]
@yhmo, I have already mentioned in my post, I already configured as per the deploy_s3.md :) Yes, it's "Configure S3 with Docker Compose" I used. It just simply does not work! It's either deploy_s3.md incomplete or Milvus seems to be buggy. Do you store your embeddings on a S3 backend? Thanks for the reply anyway.

**Comment by wmwsagara** [comment]
I think my understanding is also insufficient. I'm new to Milvus. 

My objective are as follows:
1.  to protect embeddings that cost money to create. If the current machines crashes, I must be able to switch the machine and configure to S3.
2. to be compatible with upgrading to a highly available Milvus cluster.

I currently have Standalone setup with Docker Compose writing data to a local disk. 

I'm still not sure, is one S3 bucket sufficient or one need multiple S3 buckets in a cluster to operator. Of course, best is same S3 bucket to be used on cluster too. I have multiple collections with different schema.

It is best if someone could give me diffs to following config files to get S3 up:
1. https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml
2. https://github.com/milvus-io/milvus/blob/v2.2.11/configs/milvus.yaml

Do I need any other config file to update too?

I can upgrade to v2.2.12 if needed.

Thanks
Sagara

**Reply by yhmo** [reply]
Let me call @LoveEachDay for help.

**Comment by wmwsagara** [comment]
Appreciate @yhmo.

**Comment by LoveEachDay** [comment]
@wmwsagara You'd remove the `environment variable: MINIO_ADDRESS` from the docker-compose.yaml. By default the environment variable has the higher precedence than the `milvus.yaml`.
![image](https://github.com/milvus-io/milvus/assets/1573213/03084e3d-ff7c-47dc-be15-5c4e21dec754)

**Comment by wmwsagara** [comment]
@LoveEachDay, with lots of love, I tried :) But now cannot connect to Milvus:
connections.connect(alias="default", host="192.168.1.110", port="19530")
[__internal_register] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>


curl 192.168.1.110:9091/api/v1/health
{"status":"ok"}


milvus.yaml:
```minio:
address: rgw.ourdomain.com
port: 443
accessKeyID: "<my_s3_access_key_id>"
secretAccessKey: "<my_s3_secret_access_key>"
useSSL: true
bucketName: "<my_bucket_name>"
rootPath: files
useIAM: false
cloudProvider: aws
iamEndpoint:
```

cat docker-compose.yml
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
      - ./milvus.yaml:/milvus/configs/milvus.yaml
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
#      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

**Comment by LoveEachDay** [comment]
@wmwsagara Could you provide full  milvus log?

**Comment by wmwsagara** [comment]
I'm sorry log files are empty. Must be a config setting. I really have to ask how do I correctly set logging?

Here is what I did in milvus.yaml:
```
# Configures the system log output.
log:
  level: debug
  stdout: "false"
  file:
    rootPath: "/var/lib/milvus/logs"
    maxSize: 300 # MB
    maxAge: 10 # Maximum time for log retention in day.
    maxBackups: 20
  format: text # text/json
```

docker-compose.yml:
```
    standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ./milvus.yaml:/var/lib/milvus/conf/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```

When start Milvus, it creates an empty file named milvus-23-07-26-08:21-easylog.log in volumes/milvus/logs/.

**Comment by wmwsagara** [comment]
Ok, managed to get the logging working. It's a 10MB file. Let me see what's issue and feedback.

**Comment by wmwsagara** [comment]
In the Milvus log:

1. There is No reference to rgw.ourdomain.com or rgw or ourdomain.

2. There are references to "<my_bucket_name>"
```
[2023/07/26 09:42:28.503 +00:00] [WARN] [storage/minio_chunk_manager.go:118] ["failed to check blob bucket exist"] [bucket=my_bucket_name] [error="Get \"https://minio:9000/my_bucket_name/?location=\": dial tcp 216.40.34.41:9000: i/o timeout"]
[2023/07/26 09:42:28.503 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="Get \"https://minio:9000/my_bucket_name/?location=\": dial tcp 216.40.34.41:9000: i/o timeout"]
[2023/07/26 09:42:28.526 +00:00] [WARN] [rootcoord/proxy_client_manager.go:239] ["proxy client is empty, GetMetrics will not send to any client"]
[2023/07/26 09:42:28.528 +00:00] [WARN] [client/client.go:94] ["QueryCoordClient msess key not existed"] [key=querycoord]
[2023/07/26 09:42:28.528 +00:00] [WARN] [client/client.go:98] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2023/07/26 09:42:28.528 +00:00] [ERROR] [grpcclient/client.go:161] ["failed to get client address"] [error="find no available querycoord, check querycoord state"]
```

Observation:
1. rgw.ourdomain.com is NOT resolvable over the Internet. Our local DNS servers resolve that.

I have configured Docker daemon itself to resolve names as follows:
cat /etc/docker/daemon.json
{
  "bip": "172.26.0.1/16",
  "mtu": 1500,
  "dns": ["192.168.1.130","192.168.1.140","8.8.8.8"]
}

2. I'm not sure what "216.40.34.41:9000"? I have configured "minio:" as follows:
```
minio:
    address: rgw.ourdomain.com
    port: 443
    accessKeyID: "<my_s3_access_key_id>"
    secretAccessKey: "<my_s3_secret_access_key>"
    useSSL: true
    bucketName: "<my_bucket_name>"
    rootPath: files
    useIAM: false
    cloudProvider: aws
    iamEndpoint:
```

4. Does this mean Milvus does not make the right connection to rgw.ourdomain.com under TLS?
