### DISCUSSION TITLE
Milvus support for enabling SSL for S3 storage.

### DISCUSSION THREAD

**Discussion by lashsingh** [milvus-io/milvus#26652] [Q&A and General discussion] [answered]
Hi everyone, 

I have just started using Milvus and currently trying to enable SSL for external S3 storage but getting "X.509 Certificate Signed by Unknown Authority" when using useSSL = true.

My S3 storage is using self signed certs and I would like to know how or where I can update Milvus config to accept self signed certs. 

If that's not possible then what is the cert location Milvus uses to verify the certs for external S3 storage.

I went through the docs without any luck. 

I have TLS connection working already from both Go & Python SDK, does it use the same tls cert location provided by extraConfigFiles by any chance ?

Thanks for your help in advance.

**Comment by yhmo** [comment]
Milvus has a configuration file: milvus.yaml. After you launch a milvus server, the milvus.yaml is in the milvus container under the path /milvus/configs/milvus.yaml

If your milvus is deployed as standalone by docker-compose, follow this doc to modify the configurations: https://milvus.io/docs/configure-docker.md

For helm deployment: https://milvus.io/docs/configure-helm.md
And operator: https://milvus.io/docs/configure_operator.md

All these approaches eventually change the milvus.yaml

In the milvus source code, the milvus.yaml is: https://github.com/milvus-io/milvus/blob/2.2.0/configs/milvus.yaml
We can see there is a section for MinIO/S3 configurations, including "useSSL":
```
# Related configuration of MinIO/S3/GCS or any other service supports S3 API, which is responsible for data persistence for Milvus.
# We refer to the storage service as MinIO/S3 in the following description for simplicity.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: "a-bucket" # Bucket name in MinIO/S3
  rootPath: files # The root path where the message is stored in MinIO/S3
   # Whether to use IAM role to access S3/GCS instead of access/secret keys
  # For more infomation, refer to
  # aws: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html
  # gcp: https://cloud.google.com/storage/docs/access-control/iam
  # aliyun (ack): https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control
  # aliyun (ecs): https://www.alibabacloud.com/help/en/elastic-compute-service/latest/attach-an-instance-ram-role
  useIAM: false
  # Cloud Provider of S3. Supports: "aws", "gcp", "aliyun".
  # You can use "aws" for other cloud provider supports S3 API with signature v4, e.g.: minio
  # You can use "gcp" for other cloud provider supports S3 API with signature v2
  # You can use "aliyun" for other cloud provider uses virtual host style bucket
  # When useIAM enabled, only "aws", "gcp", "aliyun" is supported for now
  cloudProvider: aws
  # Custom endpoint for fetch IAM role credentials. when useIAM is true & cloudProvider is "aws".
  # Leave it empty if you want to use AWS default endpoint
  iamEndpoint: ""
  # Log level for aws sdk log. 
  # Supported level:  off, fatal, error, warn, info, debug, trace
  logLevel: error
  # Cloud data center region
  region: ""
  # Cloud whether use virtual host bucket mode
  useVirtualHost: false
```
