### DISCUSSION TITLE
How do I get S3 storage with useIAM: true working on milvus standalone?

### DISCUSSION THREAD

**Discussion by ndtreviv** [milvus-io/milvus#26832] [Q&A and General discussion] [answered]
I'm trying to store my data in S3 via minio using an IAM role.

I'm running milvus, etcd, and minio in docker-compose  on an ec2 instance like so:

```
version: '3.1'

services:

  etcd:
    container_name: milvus-etcd
    image: milvusdb/etcd:3.5.5-r2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/etcd/healthcheck.sh']
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    volumes:
      - ./volumes/milvus:/var/lib/milvus/db
      - ./configs/milvus.yaml:/configs/milvus.yaml
    depends_on:
      - "etcd"
      - "minio"

  milvus-backup:
    container_name: ncmec-milvus-backup
    image: milvus-backup
    ports:
      - "8088:8080"
    depends_on:
      - "milvus"

```

My milvus.yaml file is a copy of the version in source control but with this section changed:

```
minio:
  address: https://s3.amazonaws.com/
  port: 443 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: true # Access to MinIO/S3 with SSL
  bucketName: my-bucket-in-here # Bucket name in MinIO/S3
  rootPath: files # The root path where the message is stored in MinIO/S3
  # Whether to useIAM role to access S3/GCS instead of access/secret keys
  # For more information, refer to
  # aws: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html
  # gcp: https://cloud.google.com/storage/docs/access-control/iam
  # aliyun (ack): https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control
  # aliyun (ecs): https://www.alibabacloud.com/help/en/elastic-compute-service/latest/attach-an-instance-ram-role
  useIAM: true
  # Cloud Provider of S3. Supports: "aws", "gcp", "aliyun".
  # You can use "aws" for other cloud provider supports S3 API with signature v4, e.g.: minio
  # You can use "gcp" for other cloud provider supports S3 API with signature v2
  # You can use "aliyun" for other cloud provider uses virtual host style bucket
  # When useIAM enabled, only "aws", "gcp", "aliyun" is supported for now
  cloudProvider: aws
  # Custom endpoint for fetch IAM role credentials. when useIAM is true & cloudProvider is "aws".
  # Leave it empty if you want to use AWS default endpoint
  iamEndpoint:
  # Log level for aws sdk log.
  # Supported level:  off, fatal, error, warn, info, debug, trace
  logLevel: error
  # Cloud data center region
  region: "us-east-1"
  # Cloud whether use virtual host bucket mode
  useVirtualHost: false
```

When I `docker-compose up` and grep the milvus logs, it's still creating a bucket in minio local storage called `a-bucket`.

Why is it ignoring my config?
What am I doing wrong?
Thanks for any help!

**Comment by ndtreviv** [comment]
OK, it was ignoring my config because I should have mounted it at: `/milvus/configs/milvus.yaml`

After fixing that and changing the `minio.address` to `s3.us-east-1.amazonaws.com` then it starts trying to connect.

Instead I now get the following two errors:

```
[2023/09/04 13:24:14.213 +00:00] [WARN] [rootcoord/quota_center.go:146] ["quotaCenter sync metrics failed"] [error="err: find no available datacoord, check datacoord state\n, /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:387 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:130 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:425 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:216 github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).syncMetrics.func2\n/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit\n"]
```

```
panic: attempt #0: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #1: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #2: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #3: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #4: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #5: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #6: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #7: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #8: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #9: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #10: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #11: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #12: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #13: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #14: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #15: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #16: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #17: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #18: Put "http://169.254.169.254/latest/api/token": context deadline exceeded: attempt #19: Put "http://169.254.169.254/latest/api/token": context deadline exceeded
```

**Comment by ndtreviv** [comment]
It turns out that when you run something on EC2 in docker the AWS meta-data security prevents it from using meta-data endpoints unless you increase the number of "hops" (see here for more: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations):

```
aws ec2 modify-instance-metadata-options \
    --instance-id i-XXXXXXXXXXX \
    --http-put-response-hop-limit 3 \
    --http-endpoint enabled
``` 

Now I'm getting:

```
panic: attempt #0: Access Denied.: attempt #1: Access Denied.: attempt #2: Access Denied.: attempt #3: Access Denied.: attempt #4: Access Denied.: attempt #5: Access Denied.: attempt #6: Access Denied.: attempt #7: Access Denied.: attempt #8: Access Denied.: attempt #9: Access Denied.: attempt #10: Access Denied.: attempt #11: Access Denied.: attempt #12: Access Denied.: attempt #13: Access Denied.: attempt #14: Access Denied.: attempt #15: Access Denied.: attempt #16: Access Denied.: attempt #17: Access Denied.: attempt #18: Access Denied.: attempt #19: Access Denied.
```

**Comment by ndtreviv** [comment]
If I put access key and secret key in milvus.yaml it all works, but I want it to use IAM.

If I `docker exec [container] curl http://169.254.169.254/latest/meta-data/iam/info`
the resulting `InstanceProfileArn` has the right IAM role in it...which has full permissions on the S3 bucket I'm targeting.

**Comment by ndtreviv** [comment]
OK, I've resolved it! Next issue is that the vectors aren't being stored in S3. Only:

* `delta_log`
* `insert_log`
* `stats_log`

Where are the index files?

**Comment by ndtreviv** [comment, marked as answer]
Going to close this because it's now too similar to: #26244

To be clear, here's what I needed to do to get it working on EC2:

1. relax metadata security for my instance:
```
aws ec2 modify-instance-metadata-options \
    --instance-id i-XXXXXXXXXXXX \
    --http-put-response-hop-limit 3 \
    --http-endpoint enabled
```

2. use this docker-compose file:
```
version: '3.1'

services:

  etcd:
    container_name: milvus-etcd
    image: milvusdb/etcd:3.5.5-r2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/etcd/healthcheck.sh']
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
    ports:
      - "19530:19530"
    volumes:
      - ./volumes/milvus:/var/lib/milvus/db
      - ./configs/milvus.yaml:/milvus/configs/milvus.yaml
    depends_on:
      - "etcd"
      - "minio"

  milvus-backup:
    container_name: milvus-backup
    image: milvus-backup
    ports:
      - "8088:8080"
    volumes:
      - ./configs/backup.yaml:/configs/backup.yaml
    depends_on:
      - "milvus"
```
**Note**: You must remove `MINIO_ADDRESS` env var in the milvus service if you have it there.


3. Use the default milvus.yaml but update the `minio` section to be like this:

```
minio:
  address: s3.us-east-1.amazonaws.com # Assuming s3.amazonaws.com would also work, especially as we're declaring region below
  port: 80
  accessKeyID: not-used-so-ignore
  secretAccessKey: not-used-so-ignore
  useSSL: false
  bucketName: my-s3-bucket-name
  rootPath: files
  useIAM: true
  cloudProvider: aws
  iamEndpoint:
  logLevel: error
  region: "us-east-1"
  useVirtualHost: false
```

This gets everything writing to S3. The only issue is that it's a while before `index_files` start to be written - it's not clear what "forces" them to be written, but if you shut the system down and start it up again with no index_files, all your data will be gone.
