### DISCUSSION TITLE
Installing and Configuring Milvus - documentation talking about missing docker_compose sections?

### DISCUSSION THREAD

**Discussion by brandonbiggs** [milvus-io/milvus#27154] [Q&A and General discussion] [answered]
Hi,

I'm following the documentation for configuring milvus via docker compose. Hopefully I'm just missing something, but I ran into the following document https://milvus.io/docs/configure-docker.md#Modify-the-installation-file

On this page it says "In docker-compose.yml, add a volumes section under each Milvus component, i.e. root coord, data coord, data node, query coord, query node, index coord, index node, and proxy.". In the docker compose file I downloaded via the wget command further up the page, there are no sections in the file for each Milvus component, there are only sections for etcd, minio, and milvus-standalone. Is the documentation misleading or am I missing a step of what I needed to do?

**Comment by yhmo** [comment, marked as answer]
This doc is out of date. In v2.1 we support cluster mode for docker-compose deployment, but after v2.2 we only support standalone mode for docker-compose. There are only three sections under the "services": minio, etcd and milvus-standalone.

The sentence should be "In docker-compose.yml, add a volumes section under the milvus-standalone"
The yaml example should be:

```
services:
  etc:
    ......
  minio:
    ......

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.13
    command: ["milvus", "run", "standalone"]
    volumes:       # Add a volumes section.
      - /local/path/to/your/milvus.yaml:/milvus/configs/milvus.yaml   # Map the local path to the container path
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```
