### DISCUSSION TITLE
the milvus-standalone container contains insert_log and occupies lots of disk space.

### DISCUSSION THREAD

**Discussion by slientup** [milvus-io/milvus#27261] [Q&A and General discussion]
basic info : standalone version 2.2.11

fault description:  the milvus-standalone container is currently occupying "614GB" of disk space, with the "/milvus/files/insert_log" directory inside the container consuming "572GB" of storage. i have suspended write operations to the collection **443294057889508736**. 

```
root@:# docker system df -v
Containers space usage:

CONTAINER ID   IMAGE                                                            COMMAND                  LOCAL VOLUMES   SIZE      CREATED       STATUS                 NAMES
08dd4032889d   registry.datayes.com/devops/milvus:v2.2.11                       "/tini -- milvus run…"   0               614GB     6 weeks ago   Up 4 weeks             milvus-standalone
56b76971e8a6   registry.datayes.com/devops/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   1               0B        6 weeks ago   Up 6 weeks (healthy)   milvus-minio
bd3c01999568   registry.datayes.com/devops/etcd:v3.5.5                          "etcd -advertise-cli…"   0               0B        6 weeks ago   Up 6 weeks             milvus-etcd

>>>>enter milvus-standalone container
root@08dd4032889d:/milvus/files/insert_log# du -h --max-depth=1
1.2G	./443278392604257279
571G	./443294057889508736
13M	./443667744276825669
573G	.

```

two questions: 
1.  insert_log should be recorded in minio, but why is it located within the milvus-standalone container? 
2. Could you provide recommendations on how to reduce disk space usage?

**Comment by slientup** [comment]
@yhmo @xiaofan-luan  Could you please assist?

**Comment by yhmo** [comment]
> 1.insert_log should be recorded in minio, but why is it located within the milvus-standalone container?
Standalone contains 3 containers: milvus-standalone, minio, etcd. All of the components are running locally. So, the minio requires a local path to start its data files, the same as etcd.
In the docker-compose.yaml, we can see:
```
etcd:
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
minio:
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
```
Their data paths are redirected to the local path /volumes/etcd and /volumes/minio.

> 2.Could you provide recommendations on how to reduce disk space usage?
How much data is in the collection 443294057889508736? number of rows? dimensions?
Do you have continually/repeatedly insert actions for all the time? 

In the milvus.yaml, the following configurations can control the life-cycle of soft-deleted files:
```
dataCoord:
  gc:
    interval: 3600 # gc interval in seconds
    missingTolerance: 3600 # file meta missing tolerance duration in seconds, 3600
    dropTolerance: 10800 # file belongs to dropped entity tolerance duration in seconds. 10800
```
You can try:
- change the gc.interval to 600, it triggers internal GC process for every 600 seconds.
- change the gc.dropTolerance to 3600, so that soft-deleted files will be permanently deleted in an hour.
