### DISCUSSION TITLE
How many pre created external kafka topics/channels required in total ?

### DISCUSSION THREAD

**Discussion by lashsingh** [milvus-io/milvus#27487] [Q&A and General discussion]
Hi everyone,

I am trying to use the following option available in v2.3.0.
  
```
# preCreatedTopic decides whether using existed topic
  preCreatedTopic:
    enabled: false
    # support pre-created topics
    # the name of pre-created topics
    names: ["my-precreated-topic"]
    # need to set a separated topic to stand for currently consumed timestamp for each channel
    timeticker: "timetick-channel"
```
Question 1: Can just have one pre-created topic/channel in external kafka service to be used milvus ? 
Queston 2: If the anser to Question 1 is No, then how many topics/channels in total I need and do they have a specific names ?
Question 3: Do I need to create a separate topic/channel with name 'timetick-channel' and does the name has to be "timetick-channel" ?

Thanks a lot for your help in advance.
