### DISCUSSION TITLE
How to disable PProf in milvus

### DISCUSSION THREAD

**Discussion by StormstoutY** [milvus-io/milvus#27626] [Q&A and General discussion]
I try to deploy milvus in a product environment. I use helm chart to deploy milvus on my k8s cluster. Since the service type I am using is LoadBalancer, I created an externally accessible port. I found that by accessing "9091/debug/pprof/", I can enter go pprof debug mode, which has great security risks in a product environment. Does the milvus service enable pprof on port 9091 by default? Can I turn off this mode by modifying the configuration in the helm chart?

**Comment by yhmo** [comment]
The pprof is bound to port 9091 of an internal http server in milvus.
There is a configuration in the milvus.yaml for httpserver:
```
proxy:
  http:
    enabled: true # Whether to enable the http server
    debug_mode: false # Whether to enable http server debug mode
```

But after I set its value to "false", it seems doesn't work, I still can access it by web browser http://xxx.xxx.xxx.xxx:9091/debug/pprof/.
If you strongly want to disable it, raise an issue in the [issues](https://github.com/milvus-io/milvus/issues) panel so that we can assign proper engineer to fix it.
