### DISCUSSION TITLE
Automatic data flushing? And best practices for data flushing after insert?

### DISCUSSION THREAD

**Discussion by qqu0127** [milvus-io/milvus#27689] [Q&A and General discussion] [answered]
I'm using milvus 2.3.x (with pymilvus), and reading https://milvus.io/docs/insert_data.md, it seems to recommend users manually call flush() after each insert session, while not too frequently. 
I'm aware of the downside of creating too many segments by calling flush frequently, but do want to persist the data and have them indexed and have reasonable read/write performance.

Does milvus 2.x support automatic data flushing? I can't find any documentation on this. If not, what is the best practice for data flushing after insert?
Either case, could someone please clarify this on the user guide. Thanks.

**Comment by yhmo** [comment, marked as answer]
**All the milvus 2.x versions support automatic flush. Don't call flush() after each insert action.**

- If your data is streaming: continually insert every minute, for example, insert 10~20 rows every minute, sometimes delete some rows...
Don't call flush(), never. Let milvus auto-flush by itself.


- If your data is static: for example, 10 million rows, batch insert each batch 10000 rows, total insert 1000 times
After insert 1000 times, only call flush() one time to flush the "tail" data into storage.

**Reply by qqu0127** [reply]
Thank you so much for your prompt response. It's a nice and clear answer.
Just FYI, https://stackoverflow.com/questions/71524810/does-milvus-auto-flush-inserted-data-to-object-storage-or-do-we-have-to-manuall there is a pending question on SO too. I can't find the answer out there so I have to ask here.
(Please kindly make this OBVIOUS on the official user guide, IMHO this is very basic and simple use case, the current doc isn't clear)
Thanks again.

**Reply by yhmo** [reply]
The question is for the old version 1.x, the old version doesn't auto-flush.
Actually, the [doc](https://milvus.io/docs/insert_data.md#Flush-the-Data-in-Milvus) has mentioned "It is important to only call this method(flush) at the end of an insert session. Calling it too often will cause fragmented data that will need to be cleaned later on."

**Reply by qqu0127** [reply]
The problem is, correct me if I'm wrong, the doc doesn't mention automatic flush at all. Making it clear that users don't have to call it manually at all (e.g. in stream process scenario), is a totally different story.

The SO question is asking about the 2.0 version, I answered there and added a link to here.

**Reply by yhmo** [reply]
Ok, we will update the doc to describe the auto-flush.

**Reply by ice-cronus** [reply]
How can that auto flush interval be configured? I went through milvus.yaml and did not notice the param. Is it `queryCoord.checkInterval`?

**Reply by yhmo** [reply]
```
dataCoord:
  segment:
    maxSize: 512 # Maximum size of a segment in MB
    sealProportion: 0.23
    # If a segment didn't accept dml records in maxIdleTime and the size of segment is greater than
    # minSizeFromIdleToSealed, Milvus will automatically seal it.
    # The max idle time of segment in seconds, 10*60.
    maxIdleTime: 600
    minSizeFromIdleToSealed: 16 # The min size in MB of segment which can be idle from sealed.

dataNode:
  segment:
    insertBufSize: 16777216 # Max buffer size to flush for a single segment.
    syncPeriod: 600 # The period to sync segments if buffer is not empty.
```

In each segment, data is split into binlog files. When you do continue insertion, for each segment, the data is accumulated into a buffer, once a buffer size exceed **dataNode.segment.insertBufSize**, datanode will persist the buffer into storage as a binlog file. If a buffer size doesn't exceed insertBufSize and it is kept in memory for more than **dataNode.segment.syncPeriod**, datanode will force persist the buffer into storage as a binlog file.

dataNode.syncPeriod  ----------------------------------- the interval to persist buffer into storage, units: second
dataNode.segment.insertBufSize --------------------- if a buffer size exceeds this value, force persist the buffer into storage, unit: byte


If a growing segment size exceeds **dataCoord.segment.maxSize * dataCoord.segment.sealProportion**, the growing segment will be turned to "sealed" segment

If a growing segment didn't accept dml records in **dataCoord.segment.maxIdleTime** and the size of segment is greater than **dataCoord.segment.minSizeFromIdleToSealed**, Milvus will automatically seal it.
