### DISCUSSION TITLE
Where is the downloaded backup file

### DISCUSSION THREAD

**Discussion by 1292253144** [milvus-io/milvus#27740] [Q&A and General discussion]
![image](https://github.com/milvus-io/milvus/assets/123862896/0572f5c7-33a9-48b7-94b3-b5bf288f4530)

 curl --location --request GET 'http://10.20.0.0:8080/api/v1/get_backup?backup_id=fb574871-6bf7-11ee-bcc3-525400490658&backup_name=backup_1016_1' --header 'Content-Type: application/json'

[GIN] 2023/10/17 - 10:42:22 | 200 |   61.009013ms |     10.20.0.0 | GET      "/api/v1/get_backup?backup_id=fb574871-6bf7-11ee-bcc3-525400490658&backup_name=backup_1016_1"
{"requestId":"cc1167b5-6c96-11ee-8b2f-525400490658","msg":"success",......

**Comment by yhmo** [comment]
In the configuration file of backup tool: https://github.com/zilliztech/milvus-backup/blob/main/configs/backup.yaml
We can see:
```
minio:
  cloudProvider: "minio" # remote cloud storage provider: s3, gcp, aliyun, azure
  
  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: minioadmin  # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  iamEndpoint: ""
  
  bucketName: "a-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "a-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath
```

The **minio.bucketName** is the source bucket, **minio.rootPath** is the source root path(actually it is the root path of the source milvus cluster storage).
The **minio.backupBucketName** is the target bucket, the **minio.backupRootPath** is the target root path.

After you create a backup, the tool copies the data files from the source root path to the target root path. Assume the buckup name is "XXX", the backup files will be stored into [minio.backupBucketName]/[minio.backupRootPath]/XXX

I think the "get_backup" command is to return the detail information of a backup operation, it doesn't download files to local disk.
