### DISCUSSION TITLE
milvus-standalone case

### DISCUSSION THREAD

**Discussion by gaoyuan5251** [milvus-io/milvus#27802] [Q&A and General discussion]
Can milvus- standalone link minio&etcd cluster?

**Comment by yhmo** [comment]
If you download the docker-compose.yaml of standalone: 
`wget https://github.com/milvus-io/milvus/releases/download/v2.3.1/milvus-standalone-docker-compose.yml -O docker-compose.yml`

You will see there are three sections:
```
version: '3.5'

services:
  etcd:
    ......
  minio:
    ......
  standalone:
    .....
```
It launches an etcd container and a minio container(all standalone).

To use your etcd/minio cluster:
1. comment out the etcd section and minio section in the docker-compose.yaml
2. redirect the milvus configurations file to the outside of the container
```
version: '3.5'

services:
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.1
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"

networks:
  default:
    name: milvus
```

3. download the configurations file from here: https://github.com/milvus-io/milvus/blob/v2.3.1/configs/milvus.yaml to your local path ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml

4. edit the ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml, set the etcd/minio address to your etcd/minio cluster.
```
# Related configuration of etcd, used to store Milvus metadata & service discovery.
etcd:
  endpoints: localhost:2379
  rootPath: by-dev # The root path where data is stored in etcd
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath

# Related configuration of MinIO/S3/GCS or any other service supports S3 API, which is responsible for data persistence for Milvus.
# We refer to the storage service as MinIO/S3 in the following description for simplicity.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: a-bucket # Bucket name in MinIO/S3
  rootPath: files # The root path where the message is stored in MinIO/S3
```
6. start milvus server by `docker-compose up -d`, the docker-compose.yaml will launch a milvus container for you, the milvus container links to your etcd/minio cluter
