### DISCUSSION TITLE
How to configuration the milvus standalone with AWS S3

### DISCUSSION THREAD

**Discussion by nhannguyentrong** [milvus-io/milvus#27945] [Q&A and General discussion]
I've tried configuration milvus standalone with s3 but it's work.
Here is what I've done
MINIO_ADDRESS: s3.us-west-2.amazonaws.com
MINIO_ACCESS_KEY: MY_ACCESS_KEY
MINIO_SECRET_KEY: MY_SECRET_KEY

I also add new value in the milvus.yaml
minio:
  address: localhost # Address of MinIO/S3
  port: 9000 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: MY_AWS_BUCKET_NAME# Bucket name in MinIO/S3
  rootPath: files # The root path where the message is stored in MinIO/S3
 cloudProvider: aws
    # Cloud data center region
  region: "us-west-2"
  
I get this error log

`[2023/10/26 07:38:44.798 +00:00] [WARN] [storage/minio_chunk_manager.go:127] ["failed to check blob bucket exist"] [bucket=MY_AWS_BUCKET_NAME [error="Head \"http://s3.us-west-2.amazonaws.com:443/MY_AWS_BUCKET_NAME/\": Connection closed by foreign host http://s3.us-west-2.amazonaws.com:443/MY_AWS_BUCKET_NAME/. Retry again."]
`
Please guide me how to connect to my aws s3 bucket.

**Comment by yhmo** [comment]
"Connection closed by foreign host" ------ search this error on google, this error is returned by s3 api, it is a network issue.

**Reply by nhannguyentrong** [reply]
What is the right configuration to access the s3? I get the endpoint url from https://docs.aws.amazon.com/general/latest/gr/s3.html

**Reply by yhmo** [reply]
https://milvus.io/docs/deploy_s3.md#Configure-S3-with-Docker-Compose
No special configurations. Just make sure the address/key are correct. One thing you should double check is the `useSSL`.
```
minio:
  address: <your_s3_endpoint>
  port: <your_s3_port>
  accessKeyID: <your_s3_access_key_id>
  secretAccessKey: <your_s3_secret_access_key>
  useSSL: <true/false>
  bucketName: "<your_bucket_name>"
```
