### DISCUSSION TITLE
Milvus kafka not working with SASL authentication

### DISCUSSION THREAD

**Discussion by navneetrajput06** [milvus-io/milvus#27977] [Q&A and General discussion] [answered]
Hi team,

When i am trying to use external Kafka in my Milvus DB its trowing error. not able to apply yaml.
tC strict decoding error: unknown field "spec.dependencies.kafka.sasl", unknown field "spec.dependencies.kafka.securityProtocol"

Some one suggested me to upgrade to Milvus 2.3.1 and i tried to upgrade also. earlier it was running on 2.3.0
But still facing same issue. Below are my values config for kafka.

   msgStreamType: "kafka"
    kafka:
      external: true
      brokerList:
        - "HOSTNAME:9094"
      securityProtocol: SASL_SSL
      sasl:
        mechanisms: SCRAM-SHA-512
        username: "*******"
        password: "*********"

**Comment by yhmo** [comment]
There is a fix for kafka sasl_ssl in the latest milvus version v2.3.2.
In the [release note](https://github.com/milvus-io/milvus/releases/tag/v2.3.2), it says:
- Fixed connection issues with Kafka under SASL_SSL (#26617)

I think the yaml should be:
```
externalKafka:
  enabled: true
  brokerList:
    - "HOSTNAME:9094"
  securityProtocol: SASL_SSL
  sasl:
    mechanisms: SCRAM-SHA-512
    username: "**"
    password: "**"
```

**Reply by navneetrajput06** [reply]
I have upgraded to v2.3.2 and using same yaml which you shared but still getting below issue.
strict decoding error: unknown field "spec.dependencies.kafka.sasl", unknown field "spec.dependencies.kafka.securityProtocol"

**Reply by LoveEachDay** [reply]
@navneetrajput06 Could you upload the `milvus.yaml` file here?

**Reply by LoveEachDay** [reply]
@navneetrajput06 Seems you are deploying a milvus cluster with milvus-operator. For now milvus operator does not support to specify `securityProtocol`. You can use milvus-helm to install a milvus cluster with an external kafka enabling security protocol.

**Reply by xiaofan-luan** [reply]
why can we add specified params for operator?

**Reply by jaime0815** [reply]
We will support security protocol parameters in the operator to align these funcitons with helm ASAP and provide the corresponding specification doc.

**Reply by navneetrajput06** [reply]
Hi team,
We have already installed cluster and running. we can not make it to help on the fly. we have installed this cluster using milvus-operator. let me know if we can get this done with milvus-operator as well.

**Comment by jaime0815** [comment, marked as answer]
we have already supported to config kafka SASL in operator v0.8.5 or higher version, the more details see https://milvus.io/docs/message_storage_operator.md

**Reply by navneetrajput06** [reply]
I am currently on below combination:
Milvus-operator-version: 0.9.1
milvus:v2.3.4
I am still getting below issue while trying to deploy SASL configurations for external kafka.
Getting below error while runnning.
kubectl apply -f external_kafka_milvus_resources.yaml   
**strict decoding error: unknown field "spec.dependencies.kafka.sasl", unknown field "spec.dependencies.kafka.securityProtocol"**

Can you help me here. for your information we have deployed Operator and Milvus both by deploying through kubectl yaml not with helm.

**Reply by navneetrajput06** [reply]
Below is my Config:
    msgStreamType: "kafka"
    kafka:
      external: true
      brokerList:
      - "Hostname:9094"
      securityProtocol: SASL_SSL
      sasl:
        mechanisms: SCRAM-SHA-512
        username: "****"
        password: "*****"

**Reply by yhmo** [reply]
Seems your configuration format is incorrect.

The external kafka configuration example: https://milvus.io/docs/message_storage_operator.md#Example-4
```
apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config:
    kafka:
      # securityPolicy supports: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL 
      securityPolicy: PLAINTEXT
      # saslMechanisms supports: PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
      saslMechanisms: PLAIN
      saslUsername: ""
      saslPassword: ""
  # Omit other fields ...
  dependencies:
    # Omit other fields ...
    msgStreamType: "kafka"
    kafka:
      external: true
      brokerList: 
        - "kafkaBrokerAddr1:9092"
        - "kafkaBrokerAddr2:9092"
        # ...

```

**Reply by navneetrajput06** [reply]
I used below config now i am able to deploy configuration now but getting below error:
config:
    kafka:
      securityPolicy: SASL_SSL
      saslMechanisms: SCRAM-SHA-512
      saslUsername: "******"
      saslPassword: "*******"
  dependencies:
    msgStreamType: "kafka"
    kafka:
      external: true
      brokerList:
        - "Hostname:9094"
        - "Hostname:9094"
        - "Hostname:9094"

Below are the logs from Milvus operator:

2024/01/25 06:52:13 checkKafka with backoff failed, retry 0, err: check consume offset from borker failed: error dialing all brokers, one of the errors: EOF
2024/01/25 06:52:14 checkKafka with backoff failed, retry 1, err: check consume offset from borker failed: error dialing all brokers, one of the errors: EOF
2024/01/25 06:52:15 checkKafka with backoff failed, retry 2, err: check consume offset from borker failed: error dialing all brokers, one of the errors: EOF
2024-01-25T06:52:16.696Z        INFO    controller.milvus       milvus dependency unhealty      {"milvus": "*******", "reason": "DependencyNotReady", "msg": "dep[MsgStreamReady]: checkKafka with backoff failed: check consume offset from borker failed: error dialing all brokers, one of the errors: EOF;"}

**Reply by navneetrajput06** [reply]
<img width="499" alt="Screenshot 2024-01-25 at 8 29 12 AM" src="https://github.com/milvus-io/milvus/assets/144489426/861f351a-9f74-4e8d-a9f7-b5619bc1ab58">

**Reply by navneetrajput06** [reply]
THIS IS MY CONFIG.

**Reply by yhmo** [reply]
Wait [jaime0815](https://github.com/jaime0815) to comment.

**Reply by navneetrajput06** [reply]
Also check on kafka.go for SecurityProtocal SASA_SSL its making useTls = "true" which means it require  certificats. can you please check this should not use tls. check below snapshot.

<img width="819" alt="Screenshot 2024-01-26 at 8 23 15 AM" src="https://github.com/milvus-io/milvus/assets/144489426/1ac9c4af-85d6-42a0-bbd2-134d270dabc4">

**Reply by jaime0815** [reply]
The doc has been updated,  it should be SecurityProtocal instead of securityPolicy in the configuration file.

**Reply by navneetrajput06** [reply]
Could you please check my above comment also its using useTls=true which is not correct i guess

**Reply by yhmo** [reply]
I think this is a kafka question, kafka is a third-party service for milvus. We provide all the interfaces to connect kafka, but we don't have answers for each kafka question.
In [this page](https://docs.confluent.io/platform/current/kafka/authentication_ssl.html) I see this sentence: 
`Secure Sockets Layer (SSL) was the predecessor of Transport Layer Security (TLS), and has been deprecated since June 2015. For TLS configurations, the properties often still refer to SSL.`
So I think the answer is yes, SASL_SSL requires certificates.

**Reply by sahildevgon** [reply]
Yes connecting to Kafka in ssl will require certificate but as of the current configurations I don't see a config for specifying client cert details (keystroke/truststore). Without this the connection to external broker will fail  for certificate issues.

**Comment by xiaofan-luan** [comment]
@jaime0815 

I think we need support more configs https://github.com/confluentinc/librdkafka/wiki/Using-SSL-with-librdkafka
like 
<img width="1054" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/5b804ada-1023-4396-8d7f-513f4a037a32">

is that correct?

**Reply by xiaofan-luan** [reply]
@yhmo can you help to fix it?

**Reply by navneetrajput06** [reply]
@yhmo to connect without client side certificate using SASL_SSL as sicurityProtocol, we just need to remove below piece of code from kafka.go. we should have option to connect without client side certificate.
https://github.com/zilliztech/milvus-operator/blob/main/pkg/external/kafka.go

![Screenshot 2024-01-30 at 9 12 04 AM](https://github.com/milvus-io/milvus/assets/144489426/45cd4f55-e7cb-41b3-855a-358da78ac9e2)

**Reply by navneetrajput06** [reply]
Using option "SASL_PLAINTEXT" is getting success because its not using useTls=true. but in case of SASL_SSL its using useTls=true. just remove this piece of line should work for us.

**Reply by yhmo** [reply]
The milvus.yaml indeed has no configuration for kafka SSL certificate. Wait our fix.

**Reply by navneetrajput06** [reply]
Hello team,
Has anyone taken this up ?

**Reply by yhmo** [reply]
I have submitted a pull request for this issue: https://github.com/milvus-io/milvus/pull/30466
This pr is waiting for verification.

**Reply by navneetrajput06** [reply]
Its not yet approved right?

**Reply by yhmo** [reply]
The pr #30466  has been merged to the 2.3 branch, will be available in the next v2.3.x minor version.

**Reply by navneetrajput06** [reply]
We dont have client side TLS auth enable in external kafka. only SASL username and password if required to connect to kafka and using SASA_SSL securityPolicy. I see the kafka file in Milvus operator which is doing useTLS=true in case of  SecurityProtocal: SASA_SSL. it still wont work if i dont pass the certificate. see my previous change we need to handle non tls kfka as well.
See below: we should have option to disable client side certificate check also.
https://github.com/zilliztech/milvus-operator/blob/main/pkg/external/kafka.go


<img width="830" alt="Screenshot 2024-02-29 at 3 23 59 PM" src="https://github.com/milvus-io/milvus/assets/144489426/e7656c6d-511c-45b8-a9fb-67480076faa9">

**Reply by navneetrajput06** [reply]
Below should not be there.
![Screenshot 2024-02-29 at 3 23 59 PM](https://github.com/milvus-io/milvus/assets/144489426/f8eee8d0-811c-48f1-bb2e-818cae808745)

**Reply by yhmo** [reply]
Since the previous milvus versions cannot fully support SSL, the milvus-operator didn't provide parameters for certificates. Once the new version is ready, the owner of milvus-operator will rewrite the logic.

**Reply by navneetrajput06** [reply]
even after couple of new release, we did not see that option in Milvus-Operator. ideally we have have option to use external kafka with SASL username and password only but its using TLS=true when we are using SASL_SSL.

**Reply by xiaofan-luan** [reply]
this doesn't need to do anything with the operator.
you can set your customized configs and the operator doesn't really need to add anything.
this how you can config it https://milvus.io/docs/configure_operator.md

# If you want to enable kafka, needs to comment the pulsar configs
# kafka:
#   brokerList: 
#   saslUsername: 
#   saslPassword: 
#   saslMechanisms: 
#   securityProtocol: 
#   ssl:
#     enabled: false # whether to enable ssl mode
#     tlsCert:  # path to client's public key (PEM) used for authentication
#     tlsKey:  # path to client's private key (PEM) used for authentication
#     tlsCaCert:  # file or directory path to CA certificate(s) for verifying the broker's key
#     tlsKeyPassword:  # private key passphrase for use with ssl.key.location and set_ssl_cert(), if any
#   readTimeout: 10

**Reply by yhmo** [reply]
This is a doc about how to config Milvus standalone with external Kafka SASL/SSL:
[Milvus connects Kafka with SASL_SSL.pdf](https://github.com/milvus-io/milvus/files/15383428/Milvus.connects.Kafka.with.SASL_SSL.pdf)

Four samples here:
1. No SASL, No SSL
2. SASL/PLAIN only
3. SSL only
4. SASL/PLAIN+SSL

I believe the Milvus core has supported it. For Milvus-Operator, wait @LoveEachDay to confirm: are there any additional configurations required?

**Reply by yhmo** [reply]
@navneetrajput06 
Basically, SSL is equal to TLS. It is reasonable TLS=true for using SASL_SSL.
If you just use SASL only, set securityProtocol to be SASL_PLAINTEXT:
```
kafka:
  brokerList: "127.0.0.1:9093"
  saslUsername: kafka
  saslPassword: pass123
  saslMechanisms: PLAIN
  securityProtocol: SASL_PLAINTEXT
```

Read the section "Connect Kafka with SASL/PLAIN only" in the doc.

**Reply by navneetrajput06** [reply]
@yhmo we are using external kafka and that doesn't support SASL_PLAINTEXT for security reason. we need to use SASL_SSL only and that too without client side TLS.

**Reply by yhmo** [reply]
With SASL_SSL, you need to provide certificates and enable SSL. For standalone Milvus, this is not a problem since you can specify the paths of certificates locally. But for cluster deployed by helm or operator, we don't have a configuration to set the certificate files into the pods.

**Reply by navneetrajput06** [reply]
@yhmo i got your point. i tried to enable kafka ssl and used below config. could you please tell me if i am using anything wrong.

  config:
    kafka:
      securityProtocol: SASL_SSL
      saslMechanisms: SCRAM-SHA-512
      saslUsername: "*******"
      saslPassword: "********"
      ssl:
        enabled: true
        tlsCert:  "/<my local path>/tlsCert.pem"
        tlsKey:  "/<my local path>/tlsKey.pem"
        tlsCaCert:  "/<my local path>/cert.pem"
        tlsKeyPassword: "*********"
      readTimeout: 10

  dependencies:
    msgStreamType: "kafka"
    kafka:
      external: true

      brokerList:
        - "kafka-broker-host:9094"

Issue: getting SSL handshake error while trying. below are the proxy node hosts. I am not sure where these certificate files are being stored in proxy pod. i did not find the cert files in this container. could you please tell me how to check that.

**Milvus-Operator logs:**
2024/05/23 20:51:00 checkKafka with backoff failed, retry 0, err: check consume offset from borker failed: error dialing all brokers, one of the errors: failed to dial: x509: certificate signed by unknown authority
2024/05/23 20:51:01 checkKafka with backoff failed, retry 1, err: check consume offset from borker failed: error dialing all brokers, one of the errors: failed to dial: x509: certificate signed by unknown authority
2024/05/23 20:51:02 checkKafka with backoff failed, retry 2, err: check consume offset from borker failed: error dialing all brokers, one of the errors: failed to dial: x509: certificate signed by unknown authority
2024-05-23T20:51:03.410Z	INFO	controller.status-syncer	milvus dependency unhealty	{"reason": "DependencyNotReady", "msg": "dep[MsgStreamReady]: checkKafka with backoff failed: check consume offset from borker failed: error dialing all brokers, one of the errors: failed to dial: x509: certificate signed by unknown authority;"}
2024-05-23T20:51:03.410Z	INFO	controller.status-syncer	syncHealthyUpdated end	{"duration": "3.064587964s"}

**Proxy node logs:**
%3|1716495747.737|FAIL|rdkafka#producer-1| [thrd:sasl_ssl:/kafka-broker:9094]: sasl_ssl://kafka-broker:9094/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed (after 6ms in state SSL_HANDSHAKE, 31 identical error(s) suppressed)
[2024/05/23 20:22:27.738 +00:00] [ERROR] [kafka/kafka_client.go:127] ["kafka error"] ["error msg"="sasl_ssl://kafka-broker:9094/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed (after 6ms in state SSL_HANDSHAKE, 31 identical error(s) suppressed)"] [stack="github.com/milvus-io/milvus/pkg/mq/msgstream/mqwrapper/kafka.(*kafkaClient).getKafkaProducer.func1.1\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go:127"]

**Reply by navneetrajput06** [reply]
Looks like its not picking my mentioned certificate. ideally operator should pick this from my local automatically. could you please tell me how can i varify.

**Comment by navneetrajput06** [comment]
<img width="569" alt="Screenshot 2024-05-23 at 3 09 26 PM" src="https://github.com/milvus-io/milvus/assets/144489426/7abb1f57-9bd4-4349-bc9a-ad99fd94e281">

**Reply by yhmo** [reply]
This doc already shows how to config SASL_SSL for milvus standalone + kafka:
https://github.com/milvus-io/milvus/files/15383428/Milvus.connects.Kafka.with.SASL_SSL.pdf

Read the section:
"Generate certificate files"
"Start a Kafka service with SASL_SSL"
"Start a Milvus standalone connects to Kafka"

**Reply by navneetrajput06** [reply]
@yhmo Its for stand alone, we are running milvus in cluster mode. Is there any possibility to get this done in cluster mode?

**Reply by yhmo** [reply]
I think currently it is not possible for cluster, I have said "for cluster deployed by helm or operator, we don't have a configuration to set the certificate files into the pods."

**Reply by navneetrajput06** [reply]
@yhmo Any development in near future?

**Reply by yhmo** [reply]
Wait @LoveEachDay comment.

**Reply by yhmo** [reply]
@navneetrajput06 
If you are familiar with k8s, you should know how to mount volumes into pods.

In the doc, the three sections show how to generate the certificate files and mount the files into container.
"Generate certificate files"
"Start a Kafka service with SASL_SSL"
"Start a Milvus standalone connects to Kafka"

In the section "Start a Milvus standalone connects to Kafka", we put the certificate files into a directory "${DOCKER_VOLUME_DIRECTORY:-.}/my_secrets". And in the docker-compose.yml, we mount this path into the container path "/milvus/secrets"
```
version: '3.5'

services:
  etcd:
    ......
    
  minio:
    ......
      
  standalone:
    container_name: milvus-standalone
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/my_secrets:/milvus/secrets
```

And we also mount the configuration files by "${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml"
In the milvus.yaml we set these configurations:

```
mq:
  type: kafka

kafka:
  brokerList: "127.0.0.1:9093"
  saslUsername: 
  saslPassword: 
  saslMechanisms: 
  securityProtocol: SSL
  readTimeout: 10 # read message timeout in seconds
  ssl:
    enabled: true # Whether to support kafka secure connection mode
    tlsCert: /milvus/secrets/kafka_client.pem # path to client's public key
    tlsKey: /milvus/secrets/kafka_client.key # path to client's private key
    tlsCACert: /milvus/secrets/ca-cert # file or directory path to CA certificate
    tlsKeyPassword: abcdefgh # private key passphrase for use with private key, if any
```

The tlsCert/tlsKey/tlsCACert are pointing to the certificate files under /milvus/secrets, which is mounted to outside the contaner.

So, if you are familiar with k8s, you can do similar actions to mount the certificate files into pods.

In milvus-helm, all the configurations are configured by the value.yaml: https://milvus.io/docs/configure-helm.md
So, we can configure the kafka in the value.yaml:
```
extraConfigFiles:
  user.yaml: |+
    mq:
      type: kafka

    kafka:
      brokerList:
        -  <your_kafka_address>:<your_kafka_port>
      saslUsername: 
      saslPassword: 
      saslMechanisms: 
      securityProtocol: SSL
      readTimeout: 10 # read message timeout in seconds
      ssl:
        enabled: true # Whether to support kafka secure connection mode
        tlsCert: /milvus/secrets/kafka_client.pem # path to client's public key
        tlsKey: /milvus/secrets/kafka_client.key # path to client's private key
        tlsCACert: /milvus/secrets/ca-cert # file or directory path to CA certificate
        tlsKeyPassword: abcdefgh # private key passphrase for use with private key, if any
```
