### DISCUSSION TITLE
Milvus Standalone Docker error

### DISCUSSION THREAD

**Discussion by caststupider** [milvus-io/milvus#27971] [Q&A and General discussion]
Hello

I got the Docker compose File from the official website:
https://milvus.io/docs/install_standalone-docker.md

When i now run the Containers they work fine, i can write Date in the DB etc.
But after the contianers are stopped and started again with the "docker compose up" command i get errors left and right.

Does someone made the same experience?

Here is the log with all the errors...
[Log1.txt](https://github.com/milvus-io/milvus/files/13182943/Log1.txt)
[log.txt](https://github.com/milvus-io/milvus/files/13178982/log.txt)

I hope someone can help me

My compsoe file looks like this, i modifyed it a bit:

```
services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - int

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: my_pw,
    expose:
      - "9001"
      - "9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - int

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.1
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      ALLOW_ENABLE_API: true
      MILVUS_USERNAME: admin
      MILVUS_PASSWORD: 1234
      MILVUS_API_KEY: my_api_key
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    expose:
      - "19530"
      - "9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - int
networks:
  int:
  ext:
    driver: bridge
```

**Comment by yhmo** [comment]
[2023/10/26 18:53:21.497 +00:00] [WARN] [storage/minio_chunk_manager.go:127] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="The Access Key Id you provided does not exist in our records."]


Seems the accesskey is not accepted by the minio.

In our official docker compose file, the minio accesskey/secretkey is minioadmin/minioadmin
 ```
minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
```

But in your docker-compose file, the accesskey/secretkey
```
 minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: my_pw,
```
