### DISCUSSION TITLE
Managing GPU VRAM Usage in Milvus Standalone 2.3.1-gpu: Limiting and Optimizing VRAM Allocation

### DISCUSSION THREAD

**Discussion by dvquang2000** [milvus-io/milvus#27981] [Q&A and General discussion] [answered]
I have an issue with using GPU on Milvus Standalone 2.3.1-gpu. I tried running two Milvus docker-compose files independently on two computers, each with one GPU card. On Machine 1 (with a 4GB VRAM GPU card), after creating a collection with index type GPU_IVF_FLAT and adding 3000 rows to the collection, the GPU usage consumed approximately 2.1 GB of VRAM after the collection loading process. Similarly, on Machine 2 (with a 24GB VRAM GPU card), the GPU usage was approximately 12.1 GB of VRAM. How can I limit the VRAM usage of the GPU for Milvus server?

**Comment by yhmo** [comment]
https://milvus.io/docs/install_standalone-gpu-docker.md#Install-Milvus-Standalone-with-Docker-Compose-GPU

This document mentioned the **KNOWHERE_GPU_MEM_POOL_SIZE**: The format for the size is **initialSize;maximumSize**, where initialSize represents the initial size of the memory pool and maximumSize represents its maximum size. The unit is MB.
```
standalone:
  environment:
    ...
    KNOWHERE_GPU_MEM_POOL_SIZE: 2048:4096
```

If you didn't configure this value, milvus will use half of the GPU memory size by default.

**Reply by dvquang2000** [reply]
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0-gpu
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      KNOWHERE_GPU_MEM_POOL_SIZE: 2048:4096
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]  
    depends_on:
      - "etcd"
      - "minio"
    
  attu:
   container_name: attu
   image: zilliz/attu:v2.3.1
   environment:
     MILVUS_URL: milvus-standalone:19530
   ports:
     - "8000:3000"
   depends_on:
     - "standalone"

networks:
  default:
    name: milvus
```
