### DISCUSSION TITLE
How can I connect to Milvus from outside the VPC?

### DISCUSSION THREAD

**Discussion by mayankrathore** [milvus-io/milvus#28808] [Q&A and General discussion] [answered]
Hello team,

I've implemented Milvus on an EKS cluster using Helm. I've opted for the "LoadBalancer" service type, which sets up a Network Load Balancer in my AWS environment through the existing aws-load-balancer-controllers on the cluster. The NLB is effectively configuring Target groups that direct traffic to the correct service on the cluster.

Below are the configuration values I'm utilizing in Helm:
```
            name: milvus
            chart_repo_url: https://zilliztech.github.io/milvus-helm/
            chart_ref: milvus
            chart_version: 4.1.6              # This is specific to app version 2.3.1 
            namespace: milvus
            create_namespace: true
            values:
              pulsar:
                enabled: false
              kafka:
                enabled: true
              service:
                type: LoadBalancer
```

Using the described configuration, I'm attempting to establish a connection to Milvus using the Python `pymilvus` library and the `connections.connect()` method.

In the first scenario **(CASE-1)**, the connection is successfully established when running the test script from an AWS EC2 instance located within the VPC CIDR range associated with the cluster where Milvus is deployed.

However, in my intended use-case **(CASE-2)**, I aim to establish the connection with the above Milvus deployment from an AWS EC2 instance situated in a different VPC. In this scenario, the Milvus connection request is resulting in Timeout errors.

Additional Information:
1. I'm using the AWS Network Load Balancer's DNS as the **endpoint** in the `pymilvus.connections.connect()` method. This approach functions correctly in **CASE-1** but encounters issues in **CASE-2**.
2. The TCP port used is 19530 (default), and I've verified that the NLB listeners are set up to listen on the same port.
3. NLB Targets are in a healthy state, with the target port matching the NodePort of the Kubernetes LoadBalancer service.
4. In the Security Groups associated with the AWS NLB, inbound rules have been added to permit all traffic from external CIDR ranges attempting to connect to Milvus.
5. When executing `telnet <Milvus-endpoint> 19530`, the output is "connected," indicating that the AWS Load Balancer is reachable from external VPC addresses.

I am trying to understand why the Milvus connection fails when attempting to connect from machines in external VPCs. Kindly inform me of any additional configurations required during Milvus installation.

Please feel free to request further details if needed.
