### DISCUSSION TITLE
run milvus1.1.1 in k8s ,but can't running.I find no useful info from log file also.

### DISCUSSION THREAD

**Discussion by Hypoce** [milvus-io/milvus#29238] [Q&A and General discussion]
<img width="1063" alt="企业微信截图_2" src="https://github.com/milvus-io/milvus/assets/92577913/88edead8-27b6-4966-a615-bb3587a715e5">
<img width="1001" alt="企业微信截图_541ea-4f4b-88b5-8b56e1f60adc" src="https://github.com/milvus-io/milvus/assets/92577913/fde5befd-eaea-40e4-8ab3-42eeb8b8ff35">

if not mount db and wal dictionary, milvus can successfully run.

bug data will loss when pod restart.

**Comment by yhmo** [comment]
"if not mount dn and wal dictionary, milvus can successfully run" ---------- Sounds like the milvus could not access the path you mounted.

In the server_config.yaml, the default paths are under the /tmp. So, after you restart the pod, the data in the /tmp folder will be cleaned by OS. You can change the path to non-tmp folder.
```
storage:
  path: /tmp/milvus11
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /tmp/milvus11/wal
```
