### DISCUSSION TITLE
k8s 安装milvus，最小集群安装，zookeeper running 但是日志报错，bookie，booker，proxy一直是init状态

### DISCUSSION THREAD

**Discussion by haipengpeng** [milvus-io/milvus#29254] [Q&A and General discussion] [answered]
NIOServerCnxn EndOfStreamException Unbale to read additional data from client

**Comment by haipengpeng** [comment]
![微信图片_20231217152256](https://github.com/milvus-io/milvus/assets/61380253/367946de-37c2-4b28-aa4c-5040a1235f8f)
![微信图片_20231217151811](https://github.com/milvus-io/milvus/assets/61380253/211e4ad6-1d98-4262-85d5-544bf37a740b)

**Reply by yhmo** [reply]
拿那些报错信息去搜一下：https://blog.csdn.net/yy1209357299/article/details/115183920
可能设置一下那个tickTime就能解决

**Reply by haipengpeng** [reply]
遇到了两个问题：
一个是图一右边的图进到pod里面改tickTime之后不知道怎么重启，目前应该不支持pod重启
第二个是图一左边的图在stateFulSets，用sed命令进行修改之后不生效
![微信图片_20231218204819](https://github.com/milvus-io/milvus/assets/61380253/68e2d8cf-7f14-48c2-a77b-8a694bd93573)
另外

补充一下几个pod的报错日志，如图二。
![微信图片_20231218210202](https://github.com/milvus-io/milvus/assets/61380253/262af29a-e884-40b5-8d04-248eede15a14)

并且补充本人使用官方最小化安装的yaml
https://github.com/milvus-io/milvus-operator/blob/main/config/samples/milvus_cluster_minimum.yaml

**Reply by haipengpeng** [reply]
并且补充下my-release-pulsar-zookeeper的sataeFullSet ：apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: my-release-pulsar
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-17T06:06:29Z"
  generation: 5
  labels:
    app: pulsar
    app.kubernetes.io/managed-by: Helm
    chart: pulsar-2.7.8
    cluster: my-release-pulsar
    component: zookeeper
    heritage: Helm
    release: my-release-pulsar
  name: my-release-pulsar-zookeeper
  namespace: default
  resourceVersion: "630418"
  uid: b7c97722-b7fd-41c8-a4e7-e0cfbde06a86
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pulsar
      component: zookeeper
      release: my-release-pulsar
  serviceName: my-release-pulsar-zookeeper
  template:
    metadata:
      annotations:
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: pulsar
        cluster: my-release-pulsar
        component: zookeeper
        release: my-release-pulsar
    spec:
      containers:
      - args:
        - |
          bin/apply-config-from-env.py conf/zookeeper.conf;
          bin/generate-zookeeper-config.sh conf/zookeeper.conf; OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar zookeeper;
        command:
        - sh
        - -c
        env:
        - name: ZOOKEEPER_SERVERS
          value: my-release-pulsar-zookeeper-0
        envFrom:
        - configMapRef:
            name: my-release-pulsar-zookeeper
        image: k8s/apachepulsar/pulsar:2.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - bin/pulsar-zookeeper-ruok.sh
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: my-release-pulsar-zookeeper
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: follower
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - bin/pulsar-zookeeper-ruok.sh
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pulsar/data
          name: my-release-pulsar-zookeeper-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: my-release-pulsar-zookeeper-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: my-release-pulsar-zookeeper-5bd7568df8
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updateRevision: my-release-pulsar-zookeeper-5bd7568df8
  updatedReplicas: 1

**Comment by wyfeng001** [comment]
你是直接用的 Milvus 的 Helm Chart安装的吗？ helm install ? 你能把安装的方式描述一下？我看看能否复现

**Reply by haipengpeng** [reply]
实际搭建的时候本人没有安装helm，全程未连接互联网，离线状态操作
而是harbor【https+域名】+三台k8s虚拟机，离线方式安装的，而教程是通过官网的helm来安装
https://www.milvus-io.com/install_cluster-milvusoperator
拷了三个yaml，并把镜像上传到harbor上，通过拉取harbor的镜像来安装milvus
前两个yaml运行成功

![微信图片_20231219191907](https://github.com/milvus-io/milvus/assets/61380253/e87d6342-101d-48e8-8c9d-a37f319bb19d)


最后一个运行的时候会出现一直pending状态

一开始用的是
https://raw.githubusercontent.com/milvus-io/milvus-operator/main/config/samples/milvus_cluster_default.yaml
也是一直出现init状态
当时怀疑资源不够，于是改成最小化安装
https://github.com/milvus-io/milvus-operator/blob/main/config/samples/milvus_cluster_minimum.yaml

**Comment by wyfeng001** [comment]
可以确认一下你三台虚拟机的安全组配置吗，彼此是否可以通信？在你的截图里，etcd，zookeeper 等单副本的 Pod 都处于 Running，我根据你使用的 Operator 方式在一个新的 K8S 集群部署，直接 apply Yaml，结果是成功的；
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
kubectl apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/main/deploy/manifests/deployment.yaml
kubectl apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/main/config/samples/milvus_cluster_default.yaml

```
![image](https://github.com/milvus-io/milvus/assets/28752231/dd188d74-1007-418a-9207-ab6f0f8129ce)

**Reply by haipengpeng** [reply]
我用的不是云服务器，没有安全组的配置，我是把所有yaml跟镜像下载下来，导入到harbor里面，k8s从harbor拉取镜像，因为k8s好像默认没有sc，所以我自己创建的pv跟sc，【主要是全程没联网，自己把镜像下载下来导入的】
![微信图片_20231220150026](https://github.com/milvus-io/milvus/assets/61380253/b3fd4917-116d-4637-a866-16085b6a6813)
![微信图片_20231220150221](https://github.com/milvus-io/milvus/assets/61380253/67d8e884-54fc-4298-b5fa-450dc1f4153b)

**Comment by maxgjt** [comment]
楼主，请问一下，你自己创建的PV 怎么挂接上的？ 我现在安装的环境跟你类似，能请教一下吗？  我邮箱是 maxgong@yeah.net

**Reply by haipengpeng** [reply]
我是用另外一台作nfs服务器挂在上pv的
下面是sc

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: k8s.io/minikube-hostpath
parameters:
    monitors: 192.168.100.221:6789
    adminId: kube
    adminSecretName: ceph-secret
    adminSecretNamespace: kube-system
    pool: kube
    userId: kube
    userSecretName: ceph-secret-user

```

下面是生成pv的yaml

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-etcd-0
  labels:
    app.kubernetes.io/instance: my-release-etcd
    app.kubernetes.io/name: etcd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220
    path: "/nfs/data/nfs-data-k8s-pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-minio
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.17
    heritage: Helm
    release: my-release-minio
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv2"  # 替换为您的 NFS 共享路径
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0
  labels:
    app: pulsar
    component: bookie
    release: my-release-pulsar
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv3"  # 替换为您的 NFS 共享路径
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-pulsar-bookie-journal-my-release-pulsar-bookie-1
  labels:
    app: pulsar
    component: bookie
    release: my-release-pulsar
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv4"  # 替换为您的 NFS 共享路径
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-pulsar-bookie-ledgers-my-release-pulsar-bookie-0
  labels:
    app: pulsar
    component: bookie
    release: my-release-pulsar
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv5"  # 替换为您的 NFS 共享路径
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-pulsar-bookie-ledgers-my-release-pulsar-bookie-1
  labels:
    app: pulsar
    component: bookie
    release: my-release-pulsar
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv6"  # 替换为您的 NFS 共享路径
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-release-pulsar-zookeeper-data-my-release-pulsar-zookeeper-0
  labels:
    app: pulsar
    component: zookeeper
    release: my-release-pulsar
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 117.6.4.220  # 替换为您的 NFS 服务器 IP 地址
    path: "/nfs/data/nfs-data-k8s-pv7"  # 替换为您的 NFS 共享路径


```
