### DISCUSSION TITLE
How to use kafka with milvus-standlone cluster using docker compose

### DISCUSSION THREAD

**Discussion by shaiktas** [milvus-io/milvus#29331] [Q&A and General discussion]
Hello, i am deploying Milvus locally using docker-compose. Would like to mimic my cloud cluster which is using kafka as a streaming messaging service. please help how to set up milvus with kafka in standlone mode locally.  What configs should we provide to override rocksmq with kafka in milvus.yaml?

**Comment by yhmo** [comment]
In the milvus.yaml, change the mq type to kafka, and comment out the "pulsar" section, enable the "kafka" section. Carefully set the kafaka address under the brokerList.

```
# Milvus supports four MQ: rocksmq(based on RockDB), natsmq(embedded nats-server), Pulsar and Kafka.
# You can change your mq by setting mq.type field.
# If you don't set mq.type field as default, there is a note about enabling priority if we config multiple mq in this file.
# 1. standalone(local) mode: rocksmq(default) > Pulsar > Kafka
# 2. cluster mode:  Pulsar(default) > Kafka (rocksmq and natsmq is unsupported in cluster mode)
mq:
  # Default value: "default"
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: kafka

# # Related configuration of pulsar, used to manage Milvus logs of recent mutation operations, output streaming log, and provide log publish-subscribe services.
# pulsar:
#   address: localhost # Address of pulsar
#   port: 6650 # Port of Pulsar
#   webport: 80 # Web port of pulsar, if you connect directly without proxy, should use 8080
#   maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes, Maximum size of each message in pulsar.
#   tenant: public
#   namespace: default
#   requestTimeout: 60 # pulsar client global request timeout in seconds
#   enableClientMetrics: false # Whether to register pulsar client metrics into milvus metrics path.

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList:
    -  <your_kafka_address>:<your_kafka_port>
  saslUsername:
  saslPassword:
  saslMechanisms: PLAIN
  securityProtocol: SASL_SSL
  readTimeout: 10 # read message timeout in seconds
```
