### DISCUSSION TITLE
Information regarding memory and processor requirements of milvus

### DISCUSSION THREAD

**Discussion by cravishe** [milvus-io/milvus#29572] [Q&A and General discussion] [answered]
I built milvus from source for linux x86_64 arch and I'm able to run it. 
I have a query.. Is it possible to run **milvus standalone** with 200 MB memory (RAM) and quad core processor ?

**Comment by yhmo** [comment]
I think 200MB RAM is not enough to run a milvus server. Even if you start it successfully, it is easily OOM when you try inserting data.

**Reply by cravishe** [reply]
ohh ok, thanks for the info

**Comment by xiaofan-luan** [comment]
Milvus require for 4GB memory at least in production environment.
For test with 100K data I would still recommend you to have 1GB memory or more.

**Reply by cravishe** [reply]
okay. 
1. I want to run it on low memory devices (RPI device), is it possible to do that..? what are my options ?
2. Is there any way I can configure memory (define memory limit and number of cores) and cores via SDK?

**Comment by cravishe** [comment]
@yhmo , @xiaofan-luan 
1. I want to run it on low memory devices (RPI device), is it possible to do that..? what are my options ?
2. Is there any way I can configure memory and cores (define memory limit and number of cores) via SDK?

**Reply by yhmo** [reply]
[milvus-lite](https://github.com/milvus-io/milvus-lite) is the lightest milvus server, which is running on python environment. You can try it on your RPI device. We don't have RPI device to test.

SDK cannot configure CPU/RAM. It just tries to use all the resources of your device.

**Reply by yhmo** [reply]
Just notice the Raspberry Pi OS is ARM, mainly is 32bit. I don't think milvus can run on this kind of OS.

**Reply by cravishe** [reply]
Can I run milvus on ARM 64 based devices?

**Reply by yhmo** [reply]
Yes, we provide special docker image for arm64: https://hub.docker.com/r/milvusdb/milvus/tags?page=1&name=arm64

**Reply by cravishe** [reply]
Thanks, I will check this. Does building from source and running milvus work for arm 64? what about milvus-lite? does it work on ARM 64 based devices

**Reply by yhmo** [reply]
It is difficult to compile source code on arm64 by users, no need to try.

**Reply by cravishe** [reply]
ohh, okay

**Comment by cravishe** [comment]
> [milvus-lite](https://github.com/milvus-io/milvus-lite) is the lightest milvus server, which is running on python environment. You can try it on your RPI device. We don't have RPI device to test.
> 
> SDK cannot configure CPU/RAM. It just tries to use all the resources of your device.

Thank you for the information.
How can I configure CPU/RAM for milvus/milvus-lite standalone server?

**Reply by yhmo** [reply]
milvus-lite is a runnable binary compiled based on x86 and Apple Silicon, I think it cannot run on ARM.

Just note:
- Milvus server cannot configure the CPU/RAM.
- Only the deploy tools can limit resources.
For example, in docker-compose.yaml:
```
standalone:
    deploy:
      resources:
        limits:
          memory: 2048M
```

**Reply by cravishe** [reply]
Got it. I will try this

**Reply by cravishe** [reply]
@yhmo 
Since I want total memory used by milvus to be less than 200 MB, I have do the below settings for each of the 3 containers (minio, etcd and standalone) ?

```
    deploy:
      resources:
        limits:
          memory: 66M  //  200/3 or set it based on needs so that total is 200
```

**Reply by yhmo** [reply, marked as answer]
Separately assign resources for the 3 containers:
```
services:
  etcd:
    deploy:
      resources:
        limits:
          memory: 200M

  minio:
    deploy:
      resources:
        limits:
          memory: 200M

  standalone:
    deploy:
      resources:
        limits:
          memory: 200M
```

**Reply by cravishe** [reply]
@yhmo 
Does this allocate 200M + 200M + 200M = 600M totally?

**Reply by yhmo** [reply]
Yes, 600M

**Reply by cravishe** [reply]
okay. Thanks for all the information and clarifications. It was very helpful.

**Comment by cravishe** [comment]
Is there any way to use milvus standalone without using etcd and minio containers. I mean, can I build and run etcd and minio locally and use milvus (without using docker containers).
﻿

**Reply by yhmo** [reply]
After you successfully compile the source code, to run milvus standalone with embedded etcd and local storage, modify the configs/milvus.yaml

1. replace all the "/var/lib/milvus" to "/tmp/milvus"
2. change etcd.use.embed to true, and set a local path for etcd.data.dir
```
etcd:
  use:
    embed: true # Whether to enable embedded Etcd (an in-process EtcdServer).
  data:
    dir: /tmp/milvus/etcd # Embedded Etcd only. please adjust in embedded Milvus: /tmp/milvus/etcdData/

```
3. set a local path for localStorage.path
```
localStorage:
  path: /tmp/milvus/data/ # please adjust in embedded Milvus: /tmp/milvus/data/
```

4. change common.storageType to local
```
common:
  storageType: local # please adjust in embedded Milvus: local, available values are [local, remote, opendal], value minio is deprecated, use remote instead 
```

5. stop all the milvus instances and third-party containers, then start the milvus by scripts/start_standalone.sh.
