### DISCUSSION TITLE
milvus-backup utility is not working for TLS enabled Milvus

### DISCUSSION THREAD

**Discussion by radhamde** [milvus-io/milvus#29764] [Q&A and General discussion]
Hello Team
Could you please help to understand the changes required in milvus-backup tool for taking milvus collections backup from TLS enabled milvus helm instance. 
Is there any provision to add TLS key and certificate in the backup.yaml configuration file ? we are putting hostname Our TLS certificate has domain name (CN) as 

```
milvus:
  address: milvus-development.mydomain.com
  port: 19530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 1
  user: "milvus-root-user"
  password: "milvus-password"

```
Hope I need to add the TLS key and certificate path also in the backup file to securely connect Milvus. Could you please tell me where is that location in backup YAML file ?

Regards
Radha M De
