### DISCUSSION TITLE
Kafka topics are not creating by default

### DISCUSSION THREAD

**Discussion by chetan-shah01** [milvus-io/milvus#29820] [Q&A and General discussion]
Hello,

I have setup Kafka with Milvus-standalone using docker-compose. Kafka topics are not creating by default. only "reading" topic is created. I want to check when Milvus is started using docker-compose then which messages are publishing to Kafka

**Comment by yhmo** [comment]
Make sure your milvus.yaml is correctly configured for kafka.
Set mq.type=kafka, disable "pulsar" section and enable "kafka" section.
Read the kafka configuration doc: https://milvus.io/docs/configure_kafka.md#Kafka-related-Configurations
```
# Milvus supports four MQ: rocksmq(based on RockDB), natsmq(embedded nats-server), Pulsar and Kafka.
# You can change your mq by setting mq.type field.
# If you don't set mq.type field as default, there is a note about enabling priority if we config multiple mq in this file.
# 1. standalone(local) mode: rocksmq(default) > Pulsar > Kafka
# 2. cluster mode:  Pulsar(default) > Kafka (rocksmq and natsmq is unsupported in cluster mode)
mq:
  # Default value: "default"
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: kafka

# # Related configuration of pulsar, used to manage Milvus logs of recent mutation operations, output streaming log, and provide log publish-subscribe services.
# pulsar:
#   address: localhost # Address of pulsar
#   port: 6650 # Port of Pulsar
#   webport: 80 # Web port of pulsar, if you connect directly without proxy, should use 8080
#   maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes, Maximum size of each message in pulsar.
#   tenant: public
#   namespace: default
#   requestTimeout: 60 # pulsar client global request timeout in seconds
#   enableClientMetrics: false # Whether to register pulsar client metrics into milvus metrics path.

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList:
  saslUsername:
  saslPassword:
  saslMechanisms: PLAIN
  securityProtocol: SASL_SSL
  readTimeout: 10 # read message timeout in seconds
```

**Reply by chetan-shah01** [reply]
@yhmo Thanks for replying. I have already disabled pulsar & enabled Kafka in yaml but still topics are not creating

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList: kafka:9092 #kafka-1:9093
#  saslUsername:
#  saslPassword:
#  saslMechanisms: 
  securityProtocol: PLAINTEXT
  readTimeout: 100 # read message timeout in seconds

**Reply by yhmo** [reply]
1. make sure the kafka username has permission to create topics
2. make sure the `mq.type=kafk` in milvus.yaml
3. make sure the `common.preCreatedTopic.enabled=false` in milvus.yaml

**Reply by yhmo** [reply]
Send the full log for us if all these configurations are correct and it still cannot crate topic.

**Reply by chetan-shah01** [reply]
@yhmo mq.type=kafka & common.preCreatedTopic.enabled=false are available in Milvus.yaml.
How to check kafka username has permission to create topics.
I am using below yaml for Kafka :

kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/kafka:/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

**Reply by chetan-shah01** [reply]
@yhmo Please revert

**Comment by yhmo** [comment]
Milvus standalone 2.3.4 + kafka
Steps:
1. create a docker-compose.yaml with this content:
```
version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafa-manager
    hostname: kafka-manager
    ports:
      - "9005:9000"
    links:
      - kafka
    external_links:
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_AUTH_ENABLED: "false"
      KAFKA_BROKERS: kafka:9092



  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3


  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.4
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
      - "kafka"
      - "zookeeper"


networks:
  default:
    name: milvus
```

2. download the milvus.yaml of v2.3.4, put the milvus.yaml and the docker-compose.yaml to under the same folder.
`wget https://raw.githubusercontent.com/milvus-io/milvus/v2.3.4/configs/milvus.yaml`
Configure the mq type and kafka:
```
# Milvus supports four MQ: rocksmq(based on RockDB), natsmq(embedded nats-server), Pulsar and Kafka.
# You can change your mq by setting mq.type field.
# If you don't set mq.type field as default, there is a note about enabling priority if we config multiple mq in this file.
# 1. standalone(local) mode: rocksmq(default) > Pulsar > Kafka
# 2. cluster mode:  Pulsar(default) > Kafka (rocksmq and natsmq is unsupported in cluster mode)
mq:
  # Default value: "default"
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: kafka

# # Related configuration of pulsar, used to manage Milvus logs of recent mutation operations, output streaming log, and provide log publish-subscribe services.
# pulsar:
#   address: localhost # Address of pulsar
#   port: 6650 # Port of Pulsar
#   webport: 80 # Web port of pulsar, if you connect direcly without proxy, should use 8080
#   maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes, Maximum size of each message in pulsar.
#   tenant: public
#   namespace: default
#   requestTimeout: 60 # pulsar client global request timeout in seconds

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList: "172.16.50.29:9092"
  saslUsername:
  saslPassword:
  saslMechanisms: PLAIN
  securityProtocol: SASL_SSL
  readTimeout: 10 # read message timeout in seconds
```

4. start the server by command: `docker-compose up -d`

5. use milvus SDK to create a collection and insert/load/search

6. use your webrowser to open the local kafka manager web UI: http://localhost:9005/
Add the local kafka to the UI:
![Screenshot from 2024-01-18 11-01-34](https://github.com/milvus-io/milvus/assets/2282099/f302c6d5-7a32-4ac8-af31-dce0523ee7b2)

Go to kafka cluster view, you will see a topic is created by milvus:
![Screenshot from 2024-01-18 11-01-59](https://github.com/milvus-io/milvus/assets/2282099/08217a9b-62e7-4918-92fa-2e63ce2227c7)
