### DISCUSSION TITLE
Setting Up Milvus Standalone on minikube with k8s using local disk mount

### DISCUSSION THREAD

**Discussion by anrahman4** [milvus-io/milvus#30260] [Q&A and General discussion]
I am trying to run a standalone Milvus instance v2.3.5 on a Docker container running minikube. When following the instructions online, everything seems to work just fine when I tested it with VectorDBBench. However, it is using the disk storage of the boot drive of the bare metal server when I insert data into Milvus via VectorDBBench. I want it to instead use a local NVMe disk that is 3.84 TB in capacity.

**System Information**
Server: HPE ProLiant DL360
CPU: Intel(R) Xeon(R) Gold 6426Y
OS: Ubuntu 22.04.3 LTS
Kernel: 5.15.0-91-generic

minikube version: v1.32.0
kubectl:
  Client Version: v1.28.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.3
helm version: 3.14.0
milvus version: v2.3.5

I created an XFS file system on the drive and mounted the local disk to "/mnt/milvus_data"

I created a persistent volume with the following pv-volume.yaml file and `kubectl apply -f pv-volume.yaml`:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/milvus_data"
```

Created the following persistent volume claim with the following pv-claim.yaml file using `kubectl apply -f pv-claim.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi
```

Outputs showing that the persistent volume and persistent volume claim have "Bound" status.
`kubectl get pv task-pv-volume`
```
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
task-pv-volume   3000Gi     RWO            Retain           Bound    default/task-pv-claim   manual                  65m
```

`kubectl get pvc task-pv-claim`
```
NAME            STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
task-pv-claim   Bound    task-pv-volume   3000Gi     RWO            manual         65m
```

I am currently using the following command via Helm to start up the k8s pods for Milvus Standalone v2.3.5:

`helm install my-release milvus/milvus --set persistence.existingClaim=task-pv-claim --set cluster.enabled=false --set etcd.replicaCount=1 --set minio.mode=standalone --set pulsar.enabled=false`

But after all of this, the pods do not utilize the NVMe disk, but keep using the boot drive for data storage. How do I make the milvus pod use the local NVMe disk instead of what it is currently using which ends up using the boot drive of the host?
