### DISCUSSION TITLE
Does kafka connecting with milvus require topic auto_creation to be set to `True`?

### DISCUSSION THREAD

**Discussion by wookiist** [milvus-io/milvus#30916] [Q&A and General discussion] [answered]
Does kafka connecting with milvus require topic auto_creation to be set to `True`? ([link](https://github.com/milvus-io/milvus/blob/dcfc35316f382878827e662c3224ca7e4cbc09ef/pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go#L179C2-L179C50))
We're using kafka cluster with auto_creation turned off for security reasons, and it seems to cause milvus init to fail because it can't create topics automatically. 
Is there any way to know in advance the name of the topic that should be created? If there is, I can create them manually in advance. 

Thank you!

**Comment by yhmo** [comment, marked as answer]
Yes, by default, it automatically creates topics in pulsar/kafka.
If you want to use existing topics, you can specify them here: https://github.com/milvus-io/milvus/blob/dcfc35316f382878827e662c3224ca7e4cbc09ef/configs/milvus.yaml#L590

Set preCreatedTopic.enabled = true, once it is true, milvus no longer creates topics automatically.
Set existing topics in preCreatedTopic.names
The preCreatedTopic.timeticker is a special topic for data consistency, specify an existing topic for it.

Make sure these topics have been created by the kafka cluster maintainer.

 ```
common: 
# preCreatedTopic decides whether using existed topic
  preCreatedTopic:
    enabled: true
    # support pre-created topics
    # the name of pre-created topics
    names: ['topic1', 'topic2']
    # need to set a separated topic to stand for currently consumed timestamp for each channel
    timeticker: 'timetick-channel'
```

**Reply by wookiist** [reply]
@yhmo 
great! Is it still efficient to have the number of collections match the number of topics, as you say [here](https://github.com/milvus-io/milvus/discussions/27487#discussioncomment-7220466)?

**Reply by yhmo** [reply]
yes, it is better that the number of topics equals the number of collections. Just a suggestion, not a problem.

**Reply by wookiist** [reply]
@yhmo there is one more question that i have :D 

I don't think it's practical to create a topic every time a collection is created, reflect it, and then restart the milvus service.
So, is there any issue with having a large enough number of topics (around 300) pre-created at the time of the first milvus service startup?

**Reply by yhmo** [reply]
By default, Milvus only uses 16 topics at most, limited by this configuration:
```
rootCoord:
  dmlChannelNum: 16 # The number of dml channels created at system startup
```

Once you define preCreatedTopics, milvus will create the topics during startup. It is **not** "create a topic every time a collection is created".
```
common:
  preCreatedTopic:
    enabled: true
    names: ['topic1', 'topic2']
```

"dml channel" is milvus internal concept. Each collection, for each shard, for each partition, has a "dml channel". "dml channel" is created when a collection is created. A "dml channel" uses a topic to manage messages.

You create 300 topics, no problem, most of them are not used.
If you set the "dmlChannelNum" to 300, and you have created 300 collections, the 300 topics are used.
