### DISCUSSION TITLE
When a collection deleted, the storage on the disk will automatically be reused?

### DISCUSSION THREAD

**Discussion by LangKing9** [milvus-io/milvus#31760] [Q&A and General discussion]
deleted a big collection in attu, but in `df -h`, the storage of it is not withdrew.

**Comment by yhmo** [comment]
After a collection is dropped, the collection's data files will be kept in storage for 2~3 hours, waiting for GC process.
In milvus.yaml, there are configurations for GC process:
```
dataCoord:
  gc:
    interval: 3600 # gc interval in seconds
    scanInterval: 168 #gc residual file scan interval in hours
    missingTolerance: 3600 # file meta missing tolerance duration in seconds, 3600
    dropTolerance: 10800 # file belongs to dropped entity tolerance duration in seconds. 10800
```

By default, GC process is triggered in an interval(one hour). "missingTolerance=3600" means it doesn't guarantee that all dropped files are deleted permanently in a GC process, some of them might be kept in storage for more one hour. So, a dropped collection's data files could be kept in storage for 2~3 hours.
