### DISCUSSION TITLE
Max segment size in Milvus 2.4

### DISCUSSION THREAD

**Discussion by ronbarhen** [milvus-io/milvus#31933] [Q&A and General discussion]
Hi,

I think that the maxSize in the configuration file milvus.yaml has no effect in Milvus 2.4.
It had an important effect in previous versions, but now when I change it, I get always the same build times, recalls and latencies.

Thanks!

**Comment by yhmo** [comment]
I just verified the maxSize by a local standalone, it works well.
Test steps:
1. mount the milvus.yaml to outseide in the docker-compose.yaml
```
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0-rc.1
    ......
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
```
2. change the `dataCoord.segment.maxSize` to 1024(MB) in the milvus.yaml
3. docker-compose up -d to start the standalone
4. insert 200k vectors(dimension=1024) into a collection, the total data size is 200k * 1024 * 4bytes=800MB
5. deploy an Attu to observe, the collection has only 1 sealed segment, 200k/800Mb
![Screenshot from 2024-04-07 10-58-12](https://github.com/milvus-io/milvus/assets/2282099/dd53cdae-71f8-4ea2-9071-0e5e0adb9315)


Then stop the milvus, change the `dataCoord.segment.maxSize` to 256(MB) and try the steps again. Observe the Attu, there are 3 sealed segments in the collection: 60k/240MB, 60k/240MB, 80k/320MB. This is expected.
