### DISCUSSION TITLE
Question about quotaAndlimits

### DISCUSSION THREAD

**Discussion by hjlee9182** [milvus-io/milvus#32263] [Q&A and General discussion]
1. I'm set ```quotaAndLimits.limitWriting.memProtection.enabled=True```.
I limited the memory to 4gb for the querynode and 1gb for the datanode. And I loaded over 4gb of collection and wrote the collection, but I got both oom.
I thought that setting would help you avoid oom, but that's not it?
2. Is the only way to avoid oom in indexnode, querynode, datanode giving me moderately large memory? I wonder if there's any way to avoid oom as a setting

**Comment by yhmo** [comment]
1. If the index type is HNSW/IVF_FLAT, it is impossible to load a 4GB collection into a 4GB RAM query node.
Milvus splits data into segments. By default, each segment is about 512MB. Milvus is written by C++/Golang, to load a 512MB segment into query node, the memory usage is always larger than 512MB. Typically, the memory usage peak to load a 512MB segment into query node is 1GB ~ 1.5GB.
Query node load segments into memory one by one. For each segment, the query node will check the memory usage. If the free space is less than 1GB ~ 1.5GB, it will return an error that says "load segment failed, OOM if load".

If the index type is IVF_SQ8/IVF_PQ/DISKANN, then it is possible to load a 4GB collection into 4GB RAM.

2. quota center is the major configurable method to avoid oom. The indexnode/querynode/datanode have their internal logic to avoid oom, such as I described in the 1.

**Reply by hjlee9182** [reply]
Umm.. But in my case query node killed by oom. 
So query node pod was repeat kill and create.
I'm also use quotacenter!

**Reply by yhmo** [reply]
```
  limitWriting:
    memProtection:
      enabled: true
      dataNodeMemoryLowWaterLevel: 0.85 # (0, 1], memoryLowWaterLevel in DataNodes
      dataNodeMemoryHighWaterLevel: 0.95 # (0, 1], memoryHighWaterLevel in DataNodes
      queryNodeMemoryLowWaterLevel: 0.85 # (0, 1], memoryLowWaterLevel in QueryNodes
      queryNodeMemoryHighWaterLevel: 0.95 # (0, 1], memoryHighWaterLevel in QueryNodes
```

Set these values to be:
 ```
 limitWriting:
    memProtection:
      enabled: true
      dataNodeMemoryLowWaterLevel: 0.6 # (0, 1], memoryLowWaterLevel in DataNodes
      dataNodeMemoryHighWaterLevel: 0.65 # (0, 1], memoryHighWaterLevel in DataNodes
      queryNodeMemoryLowWaterLevel: 0.6 # (0, 1], memoryLowWaterLevel in QueryNodes
      queryNodeMemoryHighWaterLevel: 0.65 # (0, 1], memoryHighWaterLevel in QueryNodes
```
