### DISCUSSION TITLE
About DataNode OOM..

### DISCUSSION THREAD

**Discussion by wookiist** [milvus-io/milvus#32280] [Q&A and General discussion]
When I try to insert data that exceeds the memory size of the datanode, the datanode often crashes.
Currently, the memory of the datanode is 8GB, and it is configured with 3 replicas.
However, when I look at the [code](https://github.com/milvus-io/milvus/blob/v2.3.13/internal/datanode/flow_graph_insert_buffer_node.go), there is no part that limits the insert buffer size, so could this be the cause of the OOM?

**Comment by yhmo** [comment]
There is a configuration to define the buffer size of each segment:
https://github.com/milvus-io/milvus/blob/835862df22c5c8f531fedf6cc024f89f0a50a3c6/configs/milvus.yaml#L461

The default value is 16MB.

And these configurations define the actions to force flush buffer when total buffer size exceeds a threshold:
```
dataNode:
  memory:
    forceSyncEnable: true # `true` to force sync if memory usage is too high
    forceSyncSegmentNum: 1 # number of segments to sync, segments with top largest buffer will be synced.
    watermarkStandalone: 0.2 # memory watermark for standalone, upon reaching this watermark, segments will be synced.
    watermarkCluster: 0.5 # memory watermark for cluster, upon reaching this watermark, segments will be synced.
```
