### DISCUSSION TITLE
How do indexnode and querynode share GPU cards?

### DISCUSSION THREAD

**Discussion by luckercs** [milvus-io/milvus#32302] [Q&A and General discussion]
K8s deployment,  milvus 2.3.12, gpu: NVIDIA A10,  we have 6 GPU cards on each machine.

I followed the configuration on the official website,

```
indexNode:
  resources:
    requests:
      nvidia.com/gpu: "6"
    limits:
      nvidia.com/gpu: "6"
queryNode:
  resources:
    requests:
      nvidia.com/gpu: "6"
    limits:
      nvidia.com/gpu: "6"
```

After discovering that the indexnode is occupying 6 cards, the querynode remains in a pending state and cannot obtain GPU resources

How to share all GPU cards on the machine between indexnode and querynode?

Additionally, how should NVIDIA device plugin be configured?
