### DISCUSSION TITLE
What is the HTTP endpoint where each Milvus component exposes metrics

### DISCUSSION THREAD

**Discussion by kietheros** [milvus-io/milvus#33470] [Q&A and General discussion]
For some reasons, we deployed the Milvus cluster without using K8s. I need to find the HTTP endpoint where each Milvus component exposes its metrics for monitoring.

**Comment by yhmo** [comment]
https://milvus.io/docs/monitor.md#Monitor-metrics-with-Prometheus
**Prometheus then exports metrics of each Milvus component at http://<component-host>:9091/metrics**

**Reply by kietheros** [reply]
I have Prometheus, and in its scrape_configs, I need to include the HTTP endpoints where each Milvus component exposes its metrics. Example
```
global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rootcoord'
    metrics_path: /xxx/v2/metrics/
```

**Reply by kietheros** [reply]
@yhmo Could you help me a bit ?

**Reply by yhmo** [reply]
I don't know what do you mean, wait @LoveEachDay comment.

**Reply by LoveEachDay** [reply]
@kietheros You make use of `podMonitor` or `serviceMonitor` to dynamically discover milvus component for you. Or you can use static configs:
```
scrape_configs:
  - job_name: 'rootcoord'
    static_configs:
    - targets: ["xxx:9091']
```
