### DISCUSSION TITLE
search报错(grpc: trying to send message larger than max)

### DISCUSSION THREAD

**Discussion by walkerrbytes** [milvus-io/milvus#33592] [Q&A and General discussion] [answered]
使用Bulk-vector search提交12000个向量的search，并且TOP=400。在客户端报错RESOURCE_EXHAUSTED: grpc: trying to send message larger than max (347481031 vs. 268435456)。看了一下文档的是grpc通信有512M的限制，可是报错是256M。
我使用milvus java sdk 2.4.0，MilvusClientV2 client做search
请问我是使用错了java客户端版本吗？还有就是这个512M的grpc限制能否被修改？

**Comment by walkerrbytes** [comment]
milvus的版本是2.4.3的k8s分布式版本

**Reply by yhmo** [reply, marked as answer]
RPC请求由proxy节点接收，每个请求的大小有限制，在milvus.yaml里可以配置
```
proxy:
  grpc:
    serverMaxSendSize: 268435456
    serverMaxRecvSize: 67108864
```

改这个proxy.grpc.serverMaxSendSize即可。最大上限2GB，这是gRPC的最大上限。我们一般不建议改。12000个向量的search可以分成两次查询即可。
