### DISCUSSION TITLE
Need help understanding memory usage when mmap is enabled

### DISCUSSION THREAD

**Discussion by aping** [milvus-io/milvus#33721] [Q&A and General discussion]
I have a dataset which is about 1TB, the index is IVF_SQ8.
when I load it with mmap disabled, the total memory usage is ~360GB, which meets expectation.
however when I load it with mmap enabled, things became a little bit unexpected:
- I was able to load it into just one node with 64GB of memory
- the milvus process uses nearly 50GB of memory already, before any query was sent
- I then sent a lot of queries, with ~ 1-10 threads concurrently, the memory usage stayed pretty stable, only spiked to ~55GB

so questions are like: when mmap is enabled, I was kind of expecting memory usage to be very low initially, like <1GB before any queries, and increase quickly with enough load of queries. however the reality is the memory usage reached to ~50GB right after load and stayed pretty stable during large amounts of queires. so anybody can explain why is that?

PS: I took a [heap1.out.zip](https://github.com/user-attachments/files/15721966/heap1.out.zip) right after load, but not much to tell, only like ~400MB were accounted for

**Comment by aping** [comment]
even if I load the collection into a 128gb instance, the memory usage is still about the same, like close to 50GB. and after a series of queries with random vectors the memory usage barely changed.
here is query node's spec, I don't think there's any memory limit to the pod
```
apiVersion: v1
kind: Pod
metadata:
  ...
spec:
  containers:
  - args:
    - /milvus/tools/run-helm.sh
    - milvus
    - run
    - querynode
    env:
    - name: GOGC
      value: "50"
    - name: GOMEMLIMIT
      value: 110GiB
    ...  
    image: milvusdb/milvus:v2.4.3
    name: querynode
    ...
    resources:
      limits:
        cpu: "16"
        memory: 120Gi
      requests:
        cpu: "15"
        memory: 100Gi
    ...
```
so why is the memory usage almost constant?
@xiaofan-luan any idea?
