### DISCUSSION TITLE
If delete a deprecated database how to delete the corresponding slice .sst file

### DISCUSSION THREAD

**Discussion by sun15735717236** [milvus-io/milvus#33969] [Q&A and General discussion]
The data in the rbd_data folder keeps increasing after deleting the database, is there an easy way to completely delete the abandoned database?

**Comment by yhmo** [comment]
Message queue is a key component for Milvus.
For Milvus cluster, Pulsar is the message queue.
For Milvus standalone, a RocksDB is embedded in milvus, and the data path of the RocksDB is rbd_data. sst file is RocksDB file format.

Message queue is like a WAL(write-ahead-log) component for Milvus. Each message queue manages its data by itself.
For Milvus standalone, the configurations for the rocksdb. The retentionTimeInMinutes controls the retention time of the rocksdb. 
Default value is 3 days, which means data will be kept in rocksdb for 3 days. If you have inserted 10GB of data in the past 3 days, you will see the size of rdb_data increase.
You can reset this configuration to a small value. Don't set the value to a tiny value. At least 1 hour. Restart milvus after resetting the configuration.

```
rocksmq:
  # The path where the message is stored in rocksmq
  # please adjust in embedded Milvus: /tmp/milvus/rdb_data
  path: /var/lib/milvus/rdb_data
  lrucacheratio: 0.06 # rocksdb cache memory ratio
  rocksmqPageSize: 67108864 # 64 MB, 64 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
  retentionTimeInMinutes: 4320 # 3 days, 3 * 24 * 60 minutes, The retention time of the message in rocksmq.
  retentionSizeInMB: 8192 # 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
  compactionInterval: 86400 # 1 day, trigger rocksdb compaction every day to remove deleted data
  compressionTypes: 0,0,7,7,7 # compaction compression type, only support use 0,7. 0 means not compress, 7 will use zstd. Length of types means num of rocksdb level.
```
