### DISCUSSION TITLE
An error while starting milvus【Local: Unknown topic】

### DISCUSSION THREAD

**Discussion by suyestyle** [milvus-io/milvus#34023] [Q&A and General discussion]
I'm using version 2.3.4

docker-compose is configured as 
```
version: '3.5'

services:
  standalone002:
    container_name: milvus-standalone002
    image: xxxx/milvus:v2.3.4
    command: ["milvus", "run", "standalone"]
    volumes:
      - /opt/work/milvus/milvus002/milvus.yaml:/milvus/configs/milvus.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes002/milvus:/var/lib/milvus

  attu002:
    container_name: attu002
    image: xxxx/attu:v2.3.10
    environment:
      MILVUS_URL: standalone002:19530
    ports:
      - "53002:3000"
    depends_on:
      - "standalone002"
networks:
  default:
    name: milvus002
```

milvus.yaml is configured as 
```
etcd:
  endpoints: 192.168.1.2:2379
  rootPath: by-dev # The root path where data is stored in etcd
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath

metastore:
  # Default value: etcd
  # Valid values: [etcd, tikv]
  type: etcd

minio:
  address: xxxx
  port: xxxx
  accessKeyID: xxxx
  secretAccessKey: xxxx
  useSSL: true
  bucketName: milvus
  region: "ap-xxxx"
  useVirtualHost: true

mq:
  # Default value: "default"
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: kafka

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList: 192.168.1.3:9092
  readTimeout: 10 # read message timeout in seconds
```
The cluster is started through docker-compose, but there are some errors in the output log. Such as
【Local: Unknown topic】

I found that the configuration file did not specify the syntax of the topic, and then found some information to show that there is a need to create the topic permission, but I then opened the kafka server to allow the creation of the topic permission, but still will report an error.

Would you like to know how I should deal with this problem, please help.
