### DISCUSSION TITLE
Milvus cluster deployment on multiple node groups

### DISCUSSION THREAD

**Discussion by ramish-sidiqui** [milvus-io/milvus#34695] [Q&A and General discussion]
Hi community,

I was wondering if it was possible to install on a multi-node cluster and segregate different components of milvus to different node-types based on what its function is ?

For example:
Deploying Coordinators to low-resource nodes,
Deploying worker nodes to high-resource nodes.

Note: I am new to milvus and i am still learning ins and outs of it. So please correct me if this is fundamentally wrong.

**Comment by haorenfsa** [comment]
Yes of course. Suppose you're using kubernetes for deployment. You can add different labels & values for different node groups, for example, Label `nodegroup` with Values of `low/high-resources`.  And add `nodeSelector` for different components when deploying Milvus.

For milvus-operator CR you can write:
```yaml
# Milvus CR Manifest
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components: 
    proxy:
      nodeSelector:
        nodegroup: "low-resource"
    rootCoord:
      nodeSelector:
        nodegroup: "low-resource"
    dataCoord:
      nodeSelector:
        nodegroup: "low-resource"
    indexCoord:
      nodeSelector:
        nodegroup: "low-resource"
    queryNode:
      nodeSelector:
        nodegroup: "high-resource"
    indexNode:
      nodeSelector:
        nodegroup: "high-resource"
    dataNode:
      nodeSelector:
        nodegroup: "high-resource"
```

This also applies to milvus-helm with similar `values` configurations:
```yaml
# values file
proxy:
  nodeSelector:
    nodegroup: "low-resource"
# note here, helm uses xxxCoordinator instead of xxxCoord in operator
rootCoordinator:
  nodeSelector:
    nodegroup: "low-resource"
dataCoordinator:
  nodeSelector:
    nodegroup: "low-resource"
indexCoordinator:
  nodeSelector:
    nodegroup: "low-resource"
queryNode:
  nodeSelector:
    nodegroup: "high-resource"
indexNode:
  nodeSelector:
    nodegroup: "high-resource"
dataNode:
  nodeSelector:
    nodegroup: "high-resource"
```
