### DISCUSSION TITLE
DiskANN default `search_list` value

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#35302] [Q&A and General discussion] [answered]
What is the default `search_list` value in DiskANN indexes?

**Comment by yhmo** [comment]
DiskANN-related parameters are defined in milvus.yaml:
```
common:
  DiskIndex:
    MaxDegree: 56
    SearchListSize: 100
    PQCodeBudgetGBRatio: 0.125
    BuildNumThreadsRatio: 1
    SearchCacheBudgetGBRatio: 0.1
    LoadNumThreadRatio: 8
    BeamWidthRatio: 4
```
https://milvus.io/docs/disk_index.md#DiskANN-related-Milvus-configurations

The default value of search list is 100.
