### DISCUSSION TITLE
Search latency raise during other collection loading

### DISCUSSION THREAD

**Discussion by bingbb47** [milvus-io/milvus#35554] [Q&A and General discussion]
As the title, i found this phenomenon after upgrade a cluster from v2.2.8 to v2.3.19.
when load a collection, the latency of the collections already in searching raised, and the cpu usage of queryNodes raised a bit.
![image](https://github.com/user-attachments/assets/5652ee08-1443-4fac-918d-35cc23cb7068)
![image](https://github.com/user-attachments/assets/53b91e95-1ce1-4a3c-8c0d-b7ccc992a12d)

I want to know is this phenomenon expected？or how to avoid it.

**Comment by yhmo** [comment]
Possible reason: the interim index of growing segment occupies CPU resources.
In v2.3.x, there is a new feature ----- interim index for growing segment
The description in the release note of v2.3.0:
```
Growing index
Milvus distinguishes between indexed data and stream data, each treated differently. Indexed data benefits from the built index, which accelerates the search process. On the other hand, stream data relies on brute-force search, which can potentially lead to performance degradation. To address this issue, Milvus introduces the concept of a growing index. This growing index ensures consistent search performance for both indexed and stream data, mitigating any potential performance degradation caused by brute-force search.
```

By default, Growing index is IVF_FALT index. The parameters are configured in the milvus.yaml:
```
queryNode:
  segcore:
    interimIndex:
      enableIndex: true # Enable segment build with index to accelerate vector search when segment is in growing or binlog.
      nlist: 128 # temp index nlist, recommend to set sqrt(chunkRows), must smaller than chunkRows/8
      nprobe: 16 # nprobe to search small index, based on your accuracy requirement, must smaller than nlist
      memExpansionRate: 1.15 # extra memory needed by building interim index
      buildParallelRate: 0.5 # the ratio of building interim index parallel matched with cpu num
```

Collection A is already loaded, I guess collection B has a growing segment. When you load collection B, the query node needs to build a temp index for the growing segment. Half of the CPU resources are occupied by the temp index, so the search latency of collection A increased.

If you want to confirm the root cause, optionally you can:
1. change the `queryNode.segcore.interimIndex.enableIndex` to be false ----------> restart the server -------------> load collection A -----------------> continually search A -------------> load collection B -------------> observe the search latency.
2. **or**, change the `queryNode.segcore.interimIndex.buildParallelRate` to be 0.1 ----------> restart the server -------------> load collection A -----------------> continually search A -------------> load collection B -------------> observe the search latency.
