### DISCUSSION TITLE
GPU Usage by QueryNode

### DISCUSSION THREAD

**Discussion by Ald392** [milvus-io/milvus#35628] [Q&A and General discussion]
In the case of GPU indexes like GPU_CAGRA, GPU_IVF_FLAT, etc., when I load the collection, does the entire index gets loaded from the storage bucket to the CPU memory first, and then, based on the query, a subset of these indexes is loaded into the GPU memory pool?
If that’s the case, what happens if, for example, I have 10GB of CPU memory and 100GB of GPU memory? Will the maximum amount of index data I can load for search be limited to 10GB due to the lower CPU memory, potentially leading to under utilization of my GPU?

**Comment by yhmo** [comment]
Technically, the load process loads segments by multiple threads into CPU memory, then copies the data into GPU memory. Once a segment's index is copied into GPU memory, its data in CPU memory is freed. So, if the parallel loading tasks are controlled under 10GB, it can be successfully loaded.

To seg the thread pool for load process, set these values to 1. (These values are integer type)
```
common:
  threadCoreCoefficient:
    highPriority: 1 # This parameter specify how many times the number of threads is the number of cores in high priority pool
    middlePriority: 1 # This parameter specify how many times the number of threads is the number of cores in middle priority pool
    lowPriority: 1 # This parameter specify how many times the number of threads is the number of cores in low priority pool
```

If the query node has 5 CPU cores, the pool size is 1 * 5 = 5, which means there will be 5 threads to load the segments parallelly. By default, a segment size is around 1GB, so it is safe for 5 CPU cores. But if the number of CPU cores is 10, it might return an error message saying "load segment failed, OOM if load."

**Reply by Ald392** [reply]
So mine was the following
```
common:
  threadCoreCoefficient:
    highPriority: 10 # This parameter specify how many times the number of threads is the number of cores in high priority pool
    middlePriority: 5 # This parameter specify how many times the number of threads is the number of cores in middle priority pool
    lowPriority: 1 # This parameter specify how many times the number of threads is the number of cores in low priority pool
```
I set it to the one you suggested and tried. 
- In my cluster the querynode container is having  the limit for CPU set as 1 and memmory limit is 4G. I tried loading 1 Million vectors (Dimension 1024)  with the index GPU_IVF_PQ. The memmory used went from 750MB to 3.17GB and it plataued with slight increases upto 3.19GB. I did my search and waited for sometime to observe whether this would decrease because as you have pointed out when copying this index data from memmory to GPU it should be cleared from CPU memmory. But in this 30 minute time period i didn't observe the  memory used going down. What can be the cause for this behaviour ?
- On the same setup i also tried with GPU_CAGRA index and observed the memmory used going up from 1.27GB to 3.37GB  at where it errored out due to OOM.
- Also in both of these cases since the Max limit for CPU core is 1 and the thread parameters are all provided the value 1, maximum number of segments that gets loaded parallelly also should be 1. In that case the increase in memmory usage should also be around 1GB. But in both of these cases we are observing that there is more than 2GB increase. What can be the cause ?

NB: Milvus version used v2.4.0
