### DISCUSSION TITLE
Issue with loading GPU Based Index into Memory.

### DISCUSSION THREAD

**Discussion by rohitreddy1698** [milvus-io/milvus#35892] [Q&A and General discussion]
We have deployed Milvus on GKE using the Milvus-Operator which in turn is installed using its Helm Chart.
We have used : **milvusdb/milvus:v2.4.4-gpu** Image.

We are using 2 node pools
1) e2-highmen-8 , 4 nodes
2) n1-highment-8 , 2 nodes + T4 GPUs , 2 per node.

Configuration of Milvus CRD : 

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-gpu-milvus
spec:
  mode: cluster
  components:
    indexNode:
      replicas: 1
      resources:
        limits:
          cpu: "8"
          nvidia.com/gpu: "1"
          memory: 16Gi
        requests:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 2Gi
    queryNode:
      replicas: 1
      resources:
        limits:
          cpu: "8"
          nvidia.com/gpu: "1"
          memory: 64Gi
        requests:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 2Gi
```

We are trying to run the **zilliz benchmarking** on this cluster.
We have ingested the **Cohere 10 M Search Performance Dataset**  -

When we try to load this collection it is failing with error 

>>> collection.load()
RPC error: [get_loading_progress], <MilvusException: (code=2001, message=show collection failed: At LoadSegment:  => failed to Deserialize index: raft inner error)>, <Time:{'RPC start': '2024-09-01 10:59:47.502666', 'RPC error': '2024-09-01 10:59:47.813145'}>
RPC error: [wait_for_loading_collection], <MilvusException: (code=2001, message=show collection failed: At LoadSegment:  => failed to Deserialize index: raft inner error)>, <Time:{'RPC start': '2024-09-01 10:48:10.887850', 'RPC error': '2024-09-01 10:59:47.813735'}>
RPC error: [load_collection], <MilvusException: (code=2001, message=show collection failed: At LoadSegment:  => failed to Deserialize index: raft inner error)>, <Time:{'RPC start': '2024-09-01 10:46:02.282942', 'RPC error': '2024-09-01 10:59:47.813887'}>

I can see following error on query nodes :

[ERROR] [funcutil/parallel.go:88] [loadSegmentFunc] [error="At LoadSegment:  => failed to Deserialize index: raft inner error"] [errorVerbose="At LoadSegment:  => failed to Deserialize index: raft inner error\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func4\n  | \t/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment_loader.go:708\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/funcutil/parallel.go:86\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) At LoadSegment\nWraps: (3)  => failed to Deserialize index: raft inner error\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/pkg/util/funcutil/parallel.go:88"]

Is this because the Milvus Operator does not allow to configure the **initMemSize** and **maxMemSize**
https://milvus.io/docs/index-with-gpu.md#Configure-Milvus-settings-for-GPU-memory-control
https://milvus.io/docs/configure_gpu.md#gpuinitMemSize

Also where do I specify these configs.

**Comment by xiaofan-luan** [comment]
/assign @Presburger 
please help on this?

**Comment by presburger** [comment]
@rohitreddy1698 Hello, under the memory capacity of the T4, you can first test with the 1M Cohere dataset. The error here is likely caused by the loaded data exceeding the memory capacity.

**Reply by rohitreddy1698** [reply]
Hi Apologies, you are correct, it is related to the capacity issue. I have tried with smaller data sets and it is working fine.
I had increased the number of nodes from 2 to 6 and this was working. But i am running into a new issue :

raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 43: worker(43) query failed:  => failed to search: raft inner error: std::bad_alloc: out_of_memory: RMM failure at:/go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:273: Maximum pool size exceeded)>

I am assuming this is also related to memory capacity issue.

Also does the Milvus Operator allow to configure the initMemSize and maxMemSize:
https://milvus.io/docs/index-with-gpu.md#Configure-Milvus-settings-for-GPU-memory-control
https://milvus.io/docs/configure_gpu.md#gpuinitMemSize

Also where do I specify these configs.

Thank you !

**Reply by rohitreddy1698** [reply]
Thank you for your fast reply !

**Reply by presburger** [reply]
@rohitreddy1698 Hello, I recommend you try the latest GPU version of Milvus. In the new version, we have optimized GPU memory usage. thank you very much for your attention to and use of the Milvus GPU version. If you have any questions, I am more than happy to assist you.

**Reply by rohitreddy1698** [reply]
Hello, @Presburger , I am currently using : **milvusdb/milvus:v2.4.4-gpu**

Are you referring to an even newer version like : **2.4.10** or something ?


Also from the documentation : https://milvus.io/docs/index-with-gpu.md#Configure-Milvus-settings-for-GPU-memory-control
```
From Milvus 2.4.1 onwards, the GPU memory pool is only used for temporary GPU data during searches. Therefore, it is recommended to set it to 2048 and 4096.

gpu:
  initMemSize: 2048 #set the initial memory pool size.
  maxMemSize: 4096 #maxMemSize sets the maximum memory usage limit. When the memory usage exceed initMe
```

But currently we are using the Milvus Operator to Deploy the Milvus Cluster and by just mentioning the GPU resources for Index Node and Query Node :
```
resources:
        limits:
          cpu: "8"
          nvidia.com/gpu: "1"
          memory: 64Gi
        requests:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 2Gi
```

But the operator does not have the provision to for setting gpu memory sizes. I have logged onto the node and see in the conf.yaml file that these are set to null. Is this also a potential cause for the issue ? Or I do not need to set these values at all ?
```
gpu:
  initMemSize: 
  maxMemSize:
```



Also I have one more question which might not be very related to this forum but Ill just go ahead and ask it, if it seems relevant please do provide an answer.

To look at the memory usage I have installed the DCGM-exporter via Helm and the DCGM pods are running fine only if we assign GPU resources and unable to find the NVML if I am not assigning GPU resources. Can you confirm if adding GPU resources to the DCGM is necssary ?
