### DISCUSSION TITLE
How to configure Google Cloud storage as the storage for Milvus DB, without using kubernetes

### DISCUSSION THREAD

**Discussion by rsrs2013** [milvus-io/milvus#36166] [Q&A and General discussion]
This [GCP with milvus](https://milvus.io/docs/gcp.md) provides, how to configure GCP as storage for milvus using kubernetes. 

However, this [Configure S3 with Docker compose](https://milvus.io/docs/deploy_s3.md#Configure-S3-with-Docker-Compose) shows a way to do it using Amazon S3 compatible object storages.

Can I configure the docker-compose-devcontainer.yml, in some way, so that I can use GCP  or any other object storage with Milvus. One use case of this is that,  if I want to change the source code of Milvus and try build it using devcontainers and test it with GCP, instead of using the kubernetes and helm chart.

If possible, can you please provide any example or steps 

Thanks in advance.

**Comment by xiaofan-luan** [comment]
off course you can.

you will need to modify milvus.yaml to adapt gcp cloud storage.

```
minio:
  # IP address of MinIO or S3 service.
  # Environment variable: MINIO_ADDRESS
  # minio.address and minio.port together generate the valid access to MinIO or S3 service.
  # MinIO preferentially acquires the valid IP address from the environment variable MINIO_ADDRESS when Milvus is started.
  # Default value applies when MinIO or S3 is running on the same network with Milvus.
  address: localhost
  port: 9000 # Port of MinIO or S3 service.
  # Access key ID that MinIO or S3 issues to user for authorized access.
  # Environment variable: MINIO_ACCESS_KEY_ID or minio.accessKeyID
  # minio.accessKeyID and minio.secretAccessKey together are used for identity authentication to access the MinIO or S3 service.
  # This configuration must be set identical to the environment variable MINIO_ACCESS_KEY_ID, which is necessary for starting MinIO or S3.
  # The default value applies to MinIO or S3 service that started with the default docker-compose.yml file.
  accessKeyID: minioadmin
  # Secret key used to encrypt the signature string and verify the signature string on server. It must be kept strictly confidential and accessible only to the MinIO or S3 server and users.
  # Environment variable: MINIO_SECRET_ACCESS_KEY or minio.secretAccessKey
  # minio.accessKeyID and minio.secretAccessKey together are used for identity authentication to access the MinIO or S3 service.
  # This configuration must be set identical to the environment variable MINIO_SECRET_ACCESS_KEY, which is necessary for starting MinIO or S3.
  # The default value applies to MinIO or S3 service that started with the default docker-compose.yml file.
  secretAccessKey: minioadmin
  useSSL: false # Switch value to control if to access the MinIO or S3 service through SSL.
  ssl:
    tlsCACert: /path/to/public.crt # path to your CACert file
  # Name of the bucket where Milvus stores data in MinIO or S3.
  # Milvus 2.0.0 does not support storing data in multiple buckets.
  # Bucket with this name will be created if it does not exist. If the bucket already exists and is accessible, it will be used directly. Otherwise, there will be an error.
  # To share an MinIO instance among multiple Milvus instances, consider changing this to a different value for each Milvus instance before you start them. For details, see Operation FAQs.
  # The data will be stored in the local Docker if Docker is used to start the MinIO service locally. Ensure that there is sufficient storage space.
  # A bucket name is globally unique in one MinIO or S3 instance.
  bucketName: a-bucket
  # Root prefix of the key to where Milvus stores data in MinIO or S3.
  # It is recommended to change this parameter before starting Milvus for the first time.
  # To share an MinIO instance among multiple Milvus instances, consider changing this to a different value for each Milvus instance before you start them. For details, see Operation FAQs.
  # Set an easy-to-identify root key prefix for Milvus if etcd service already exists.
  # Changing this for an already running Milvus instance may result in failures to read legacy data.
  rootPath: files
  # Whether to useIAM role to access S3/GCS instead of access/secret keys
  # For more information, refer to
  # aws: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html
  # gcp: https://cloud.google.com/storage/docs/access-control/iam
  # aliyun (ack): https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control
  # aliyun (ecs): https://www.alibabacloud.com/help/en/elastic-compute-service/latest/attach-an-instance-ram-role
  useIAM: false
  # Cloud Provider of S3. Supports: "aws", "gcp", "aliyun".
  # You can use "aws" for other cloud provider supports S3 API with signature v4, e.g.: minio
  # You can use "gcp" for other cloud provider supports S3 API with signature v2
  # You can use "aliyun" for other cloud provider uses virtual host style bucket
  # When useIAM enabled, only "aws", "gcp", "aliyun" is supported for now
  cloudProvider: aws
  # Custom endpoint for fetch IAM role credentials. when useIAM is true & cloudProvider is "aws".
  # Leave it empty if you want to use AWS default endpoint
  iamEndpoint: 
  logLevel: fatal # Log level for aws sdk log. Supported level:  off, fatal, error, warn, info, debug, trace
  region:  # Specify minio storage system location region
  useVirtualHost: false # Whether use virtual host mode for bucket
  requestTimeoutMs: 10000 # minio timeout for request time in milliseconds
  # The maximum number of objects requested per batch in minio ListObjects rpc, 
  # 0 means using oss client by default, decrease these configration if ListObjects timeout
  listObjectsMaxKeys: 0
```

**Reply by rsrs2013** [reply]
I have changed the `milvus.yml` as shown below. I am using `'scripts/devcontainer.sh up'` command to start the docker containers. I believe it  uses `docker-compose-devcontainer.yml ` instead of `docker-compose.yml`
The `docker-compose-devcontainer.yml ` script has 'minio' service. Should I change the ACCESS_KEY and SECRET_KEY there as well ? 

Also I was getting a similar error as mentioned in this [discussion](https://github.com/milvus-io/milvus/issues/24864#issuecomment-1643320721).
However, in that they change the docker-compose.yml. How to change the docker-compose-devcontainer.yml accordingly ?


```
## milvus.yml
minio:
  # IP address of MinIO or S3 service.
  # Environment variable: MINIO_ADDRESS
  # minio.address and minio.port together generate the valid access to MinIO or S3 service.
  # MinIO preferentially acquires the valid IP address from the environment variable MINIO_ADDRESS when Milvus is started.
  # Default value applies when MinIO or S3 is running on the same network with Milvus.
  address: https://storage.googleapis.com
  port: 443 # Port of MinIO or S3 service.
  # Access key ID that MinIO or S3 issues to user for authorized access.
  # Environment variable: MINIO_ACCESS_KEY_ID or minio.accessKeyID
  # minio.accessKeyID and minio.secretAccessKey together are used for identity authentication to access the MinIO or S3 service.
  # This configuration must be set identical to the environment variable MINIO_ACCESS_KEY_ID, which is necessary for starting MinIO or S3.
  # The default value applies to MinIO or S3 service that started with the default docker-compose.yml file.
  accessKeyID: GOOG6LGK2YZ3J6Y6Y2XLAYD2
  # Secret key used to encrypt the signature string and verify the signature string on server. It must be kept strictly confidential and accessible only to the MinIO or S3 server and users.
  # Environment variable: MINIO_SECRET_ACCESS_KEY or minio.secretAccessKey
  # minio.accessKeyID and minio.secretAccessKey together are used for identity authentication to access the MinIO or S3 service.
  # This configuration must be set identical to the environment variable MINIO_SECRET_ACCESS_KEY, which is necessary for starting MinIO or S3.
  # The default value applies to MinIO or S3 service that started with the default docker-compose.yml file.
  secretAccessKey: /CWxc3FIpGZ3J38Mm9Gh2GY1ZqlmeGvWaaXxjlWQ
  useSSL: true # Switch value to control if to access the MinIO or S3 service through SSL.
  ssl:
    tlsCACert: /path/to/public.crt # path to your CACert file
  # Name of the bucket where Milvus stores data in MinIO or S3.
  # Milvus 2.0.0 does not support storing data in multiple buckets.
  # Bucket with this name will be created if it does not exist. If the bucket already exists and is accessible, it will be used directly. Otherwise, there will be an error.
  # To share an MinIO instance among multiple Milvus instances, consider changing this to a different value for each Milvus instance before you start them. For details, see Operation FAQs.
  # The data will be stored in the local Docker if Docker is used to start the MinIO service locally. Ensure that there is sufficient storage space.
  # A bucket name is globally unique in one MinIO or S3 instance.
  bucketName: rsrs2013-milvus-storage
  # Root prefix of the key to where Milvus stores data in MinIO or S3.
  # It is recommended to change this parameter before starting Milvus for the first time.
  # To share an MinIO instance among multiple Milvus instances, consider changing this to a different value for each Milvus instance before you start them. For details, see Operation FAQs.
  # Set an easy-to-identify root key prefix for Milvus if etcd service already exists.
  # Changing this for an already running Milvus instance may result in failures to read legacy data.
  rootPath: milvus/my-release
  # Whether to useIAM role to access S3/GCS instead of access/secret keys
  # For more information, refer to
  # aws: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html
  # gcp: https://cloud.google.com/storage/docs/access-control/iam
  # aliyun (ack): https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control
  # aliyun (ecs): https://www.alibabacloud.com/help/en/elastic-compute-service/latest/attach-an-instance-ram-role
  useIAM: false
  # Cloud Provider of S3. Supports: "aws", "gcp", "aliyun".
  # You can use "aws" for other cloud provider supports S3 API with signature v4, e.g.: minio
  # You can use "gcp" for other cloud provider supports S3 API with signature v2
  # You can use "aliyun" for other cloud provider uses virtual host style bucket
  # When useIAM enabled, only "aws", "gcp", "aliyun" is supported for now
  cloudProvider: gcp
  # Custom endpoint for fetch IAM role credentials. when useIAM is true & cloudProvider is "aws".
  # Leave it empty if you want to use AWS default endpoint
```

**Reply by rsrs2013** [reply]
@xiaofan-luan 

I have tried the following things and couldn't still make milvus use AWS S3 storage yet. Can you please suggest me some wayforward.

I have changed milvus.yaml  and docker-compose.yml file to what has been mentioned in this [link](https://github.com/milvus-io/milvus/issues/24864#issuecomment-1643320721). Then I received the below error

```
iitd@iitd-Precision-7920-Tower:~/milvus$ sudo docker compose up -d
[sudo] password for iitd: 
WARN[0000] /home/iitd/milvus/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/3
 ✔ Network milvus               Created                                                                                                                                                                0.3s 
 ✔ Container milvus-etcd        Started                                                                                                                                                                3.1s 
 ⠧ Container milvus-standalone  Starting                                                                                                                                                               3.7s 
Error response from daemon: failed to create task for container: 
failed to create shim task: OCI runtime create failed: 
runc create failed: unable to start container process: error during container init: 
error mounting "/home/iitd/milvus/milvus.yaml" to rootfs at "/milvus/configs/milvus.yaml": mount /home/iitd/milvus/milvus.yaml:/milvus/configs/milvus.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: 
unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```
So, I tried with the below docker-compose file and used devcontainer.sh script to start the builder

<details>

<summary> docker-compose.yml </summary>


```yaml

version: '3.5'

x-ccache: &ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  CCACHE_MAXSIZE: 2G
  CCACHE_DIR: /ccache

services:
  builder:
    image: ${IMAGE_REPO}/milvus-env:${OS_NAME}-${DATE_VERSION}
    # Build devcontainer
    build:
      context: .
      dockerfile: build/docker/builder/cpu/${OS_NAME}/Dockerfile
      args:
        TARGETARCH: ${IMAGE_ARCH}
      cache_from:
        - ${IMAGE_REPO}/milvus-env:${OS_NAME}-${LATEST_DATE_VERSION}
    platform: linux/${IMAGE_ARCH}
    shm_size: 2G
    # expose 19530 port so we can directly access milvus inside build container
    # ports:
    #  - "19530:19530"
    environment:
      <<: *ccache
      OS_NAME: ${OS_NAME}
      PULSAR_ADDRESS: ${PULSAR_ADDRESS}
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS}
      MINIO_ADDRESS: ${MINIO_ADDRESS}
      CONAN_USER_HOME: /home/milvus
      AZURE_STORAGE_CONNECTION_STRING: ${AZURITE_CONNECTION_STRING}
    volumes: &builder-volumes
      - .:/go/src/github.com/milvus-io/milvus:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-ccache:/ccache:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-go-mod:/go/pkg/mod:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-vscode-extensions:/home/milvus/.vscode-server/extensions:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-conan:/home/milvus/.conan:delegated
    working_dir: '/go/src/github.com/milvus-io/milvus'
    depends_on:
      - etcd
        #- minio
      - pulsar
      - azurite
    # Command
    command: &builder-command >
      /bin/bash -c "
        make check-proto-product && make verifiers && make unittest"

  gpubuilder:
    image: ${IMAGE_REPO}/milvus-env:gpu-${OS_NAME}-${GPU_DATE_VERSION}
    # Build devcontainer
    build:
      context: .
      dockerfile: build/docker/builder/gpu/${OS_NAME}/Dockerfile
      args:
        TARGETARCH: ${IMAGE_ARCH}
      cache_from:
        - ${IMAGE_REPO}/milvus-env:gpu-${OS_NAME}-${LATEST_GPU_DATE_VERSION}
    # user: {{ CURRENT_ID }}
    shm_size: 2G
    # expose 19530 port so we can directly access milvus inside build container
    # ports:
    #  - "19530:19530"
    environment:
      <<: *ccache
      OS_NAME: ${OS_NAME}
      PULSAR_ADDRESS: ${PULSAR_ADDRESS}
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS}
      MINIO_ADDRESS: ${MINIO_ADDRESS}
      CONAN_USER_HOME: /home/milvus
      AZURE_STORAGE_CONNECTION_STRING: ${AZURITE_CONNECTION_STRING}
    volumes: &builder-volumes-gpu
      - .:/go/src/github.com/milvus-io/milvus:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker-gpu}/${OS_NAME}-ccache:/ccache:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker-gpu}/${OS_NAME}-go-mod:/go/pkg/mod:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker-gpu}/${OS_NAME}-vscode-extensions:/home/milvus/.vscode-server/extensions:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker-gpu}/${OS_NAME}-conan:/home/milvus/.conan:delegated
    working_dir: '/go/src/github.com/milvus-io/milvus'
    depends_on:
      - etcd
        #- minio
      - pulsar
      - azurite
    # Command
    command: &builder-command-gpu >
      /bin/bash -c "
        make check-proto-product && make verifiers && make unittest"

  etcd:
    image: milvusdb/etcd:3.5.5-r2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/etcd/healthcheck.sh' ]
      interval: 30s
      timeout: 20s
      retries: 3

  pulsar:
    image: apachepulsar/pulsar:2.8.2
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
    environment:
      # 10MB
      - PULSAR_PREFIX_maxMessageSize=10485760
      # this is 104857600 + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840
      - PULSAR_GC=-XX:+UseG1GC

        # minio:
        #image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        #environment:
        #MINIO_ACCESS_KEY: minioadmin
        #MINIO_SECRET_KEY: minioadmin
        #command: minio server /minio_data
        #healthcheck:
        #test: [ 'CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
        #interval: 30s
        #timeout: 20s
        #retries: 3

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0

  jaeger:
    image: jaegertracing/all-in-one:latest

networks:
  default:
    name: milvus_dev
```

</details>

Steps to reproduce:
```
./scripts/devcontainer.sh

docker exec -ti milvus-builder-1 bash

make milvus

LIBJEMALLOC=$PWD/internal/core/output/lib/libjemalloc.so
export LD_PRELOAD="$LIBJEMALLOC"
export LD_LIBRARY_PATH=$PWD/internal/core/output/lib/:$LD_LIBRARY_PATH

./bin/milvus run standalone --run-with-subprocess
```

Then I was getting the below errors about the minio address and aws region.
```
[2024/09/16 13:10:30.530 +00:00] [ERROR] [components/data_coord.go:53] ["DataCoord starts error"] [error="Get \"https://minio:9000/rsrs2013-milvus-s3/?location=\": remote error: tls: internal error"] [stack="github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:123"]
panic: Get "https://minio:9000/rsrs2013-milvus-s3/?location=": remote error: tls: internal error

```
After I got the above error
I have exported the MINIO_ADDRESS and AWS_REGION in the container as follows:
```
export MINIO_ADDRESS=s3.ap-south-1.amazonaws.com:443
export AWS_REGION=ap-south-1
```
And I did again,
`./bin/milvus run standalone --run-with-subprocess
`
Can you please suggest me a way. Thanks in advance.

**Reply by yhmo** [reply]
@rsrs2013 
Seems you have compiled milvus source code and want to run milvus in local.
I supposed you have successfully compiled it and the ./bin/milvus have been generated.
Follow the steps to start a local milvus:
1. your command line is under the milvus project root path, go the the deployments/docker/dev, there is a docker-compose.yaml under this path. start the dependencies including Etcd, Pulsar. You can comment out the Minio from the docker-compose.yaml since you want to use GCP as storage.
`cd deployments/docker/dev`
`docker-compose up -d`

2. Back to the milvus project root path. Edit the configs/milvus.yaml, set the configurations for gcp: 
```
minio:
  address: xxxxxxxxxx   # address of GCP service.
  port: 9000 # Port of GCP service.
  accessKeyID: xxxxx
  secretAccessKey: xxxxxx
  bucketName: xxxxx
  rootPath: xxxxx
  cloudProvider: gcp
  region: xxxxx
```

3.  use this script to start a milvus standalone locally
`./scripts/start_standalone.sh`

The log is output to /tmp/standalone.log, check this log if it failed to start. If it successfully starts, you will see "Proxy successfully started" in the log.
