### DISCUSSION TITLE
Data nodes reporting - error="channel not found"

### DISCUSSION THREAD

**Discussion by shaiktas** [milvus-io/milvus#36430] [Q&A and General discussion]
Hello Milvus Team,
We applied below configs
```
 rootCoord:
      dmlChannelNum: 48
    proxy:
      maxShardNum: 48
    dataNode:
      # testing to scale
      import:
        maxConcurrentTaskNum: 20
    queryNode:
      # testing to scale
      dataSync:
        flowGraph:
          maxQueueLength: 32
```
with up to 50 data nodes,  started milvus with very high data ingestion .  We could able to monitor ingestion through Attu up to 17Million/Hour,  After one hour, Attu started reporting error "Milvus not ready yet" .  Captured below log from Data node. Trying to understand the impact of this on cluster.

``[error="channel not found[channel=xx-milvus-prod-east2-xxx-img-rootcoord-dml_12_452368979977863291v10]"]``
