### DISCUSSION TITLE
How to change the port each component is listening to?

### DISCUSSION THREAD

**Discussion by xiaobingxia-at** [milvus-io/milvus#36656] [Q&A and General discussion]
Hello, somehow my AWS EKS cluster doesn't allow the communication through ports >20000, so I need to change the the port number of each component. I have tried following ways:

1. Change the component config

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
    name: milvus-test-staging-s3
    namespace: starrocks-complex-query
    labels:
        app: milvus
spec:
    mode: cluster
    components:
        rootCoord:
            replicas: 1
            port: 13100
            resources:
                limits:
                    cpu: 2
                    memory: 8Gi
```

2. Change the config:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
    name: milvus-test-staging-s3
    namespace: starrocks-complex-query
    labels:
        app: milvus
spec:
    mode: cluster
    config:
        rootCoord:
            dmlChannelNum: 4
            maxDatabaseNum: 32
            maxGeneralCapacity: 100000
            port: 13100
```
            
Unfortunately, nothing works. the root coord still listens from 53100.
Does anyone know how to change the port of each component through k8s operator?

Thanks!

**Comment by xiaofan-luan** [comment]
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    rootCoord: 
      replicas: 1
      port: 13100

try this.
this is the answer askAI gives me

**Reply by xiaobingxia-at** [reply]
Thanks for your reply! But is this the same as my approach 1 above?

**Reply by xiaofan-luan** [reply]
you need to add components: before rootCoord

**Comment by xiaofan-luan** [comment]
![Uploading image.png…]()

**Comment by xiaofan-luan** [comment]
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    rootCoord: 
      replicas: 1
      port: 54000  # Set your desired port number here
```
