### DISCUSSION TITLE
rootcoord cannot connect etcd

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#37467] [Q&A and General discussion]
- milvus version: 2.4.14

```
{"level":"warn","ts":"2024-11-06T11:46:29.088+0900","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000286a80/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}

```

Why are the `etcd-endpoints` being set to localhost in the logs above? I've confirmed that etcd itself is healthy.

**Comment by yhmo** [comment]
I think the etcd address is not properly configured.

Configure etcd on docker-compose:
https://milvus.io/docs/deploy_etcd.md#Configure-etcd-with-Docker-Compose

Configure etcd on k8s:
https://milvus.io/docs/deploy_etcd.md#Configure-etcd-on-K8s

**Reply by rere950303** [reply]
@yhmo 
If we set `etcd.enabled` to true and `externalEtcd.enabled` to false, wouldn't we not need to set up a separate address?

**Reply by yhmo** [reply]
I think the etcd.enabled should always be true because currently we only support etcd as metadata server. (TiKV is experimental)

If externalEtcd.enabled is false, the milvus-helm will deploy an etcd pod for you.
If externalEtcd.enabled is true, the milvus-helm will not deploy the etcd pod, you need to provide an external etcd server address for milvus.

**Reply by rere950303** [reply]
@yhmo 
In the `/milvus/configs` directory, there are `default.yaml`, `milvus.yaml`, and `user.yaml` files, and it seems to operate by reading `milvus.yaml`, so I didn't touch the `customConfigMap` settings.

this is the helm chart


```yaml
        volumeMounts:
        {{- if .Values.customConfigMap }}
        - name: milvus-config
          mountPath: /milvus/configs/user.yaml
          subPath: milvus.yaml
          readOnly: true
        {{- else }}
        - name: milvus-config
          mountPath: /milvus/configs/default.yaml
          subPath: default.yaml
          readOnly: true
        - name: milvus-config
          mountPath: /milvus/configs/user.yaml
          subPath: user.yaml
          readOnly: true
        {{- end }}
```
```
etcd:
{{- if .Values.externalEtcd.enabled }}
  endpoints:
  {{- range .Values.externalEtcd.endpoints }}
    - {{ . }}
  {{- end }}
{{- else }}
  endpoints:
{{- range $i := until ( .Values.etcd.replicaCount | int ) }}
  - {{ $etcdReleaseName }}-{{ $i }}.{{ $etcdReleaseName }}-headless.{{ $namespace }}.svc.{{ $.Values.etcd.clusterDomain }}:{{ $etcdPort }}
{{- end }}
{{- end }}
```

i dont know why rootcoord try connecting to `localhost`
