### DISCUSSION TITLE
can't query large collection

### DISCUSSION THREAD

**Discussion by AndrewOYLK** [milvus-io/milvus#37578] [Q&A and General discussion]
When doing a large number of deletions or write operations on the collection, will it have any impact on read requests? I see that querynode has a large number of delete requests for this collection. I don't know if this will affect normal queries.

[2024/11/11 06:57:18.793 +00:00] [WARN] [checkers/index_checker.go:127] ["failed to get indexInfo for segment"] [collectionID=450679418892396320] [segmentID=453849863457179825] [error="index not found[segmentID=453849863457179825]"]

**Comment by yhmo** [comment]
Similar issue: https://github.com/milvus-io/milvus/issues/34221, which is fixed in >= v2.4.6
Not sure your issue is the same one. You can raise a new issue if the log is different.

Yes, heavy deletion operations might cause unexpected errors. Milvus developers have put a lot of effort to improve the performance and stability of large-scale deletion.

From the release note we can see: https://milvus.io/docs/release_notes.md
v2.4.15 ---------- "Additionally, Milvus 2.4.15 improved delete performance and stability through significant optimizations in L0 handling. "
v2.4.14 ---------- "Additionally, this release includes numerous enhancements focused on improving stability in large-scale delete operations and compaction performance."
v2.4.11 ---------- "This release introduces new features to view expressions and improve delete stability."
And a lot of related issues were fixed with the milvus version moving forward.

**Reply by AndrewOYLK** [reply]
I want to migrate v2.4.5 data (etcd and s3) to v.2.4.15. Are there any compatibility issues?

**Reply by yhmo** [reply]
Minor versions migration is safe.

**Reply by AndrewOYLK** [reply]
I would like to know if a large number of deletion operations are in progress, will it affect the read operation? For example, does querynode have the concept that the queue is not full? This is just my guess, because I always feel that a large number of deletion operations affect the retrieval operation?

**Reply by yhmo** [reply]
If you delete a large number of entities, at the same time insert a large number of entities, there will be more small segments generated, and search performance is affected(slower).
If you delete a large number of entities, and no new data is inserted, the search performance gets faster and faster(depend on index types, HNSW might be a curve(faster->slower->faster), IVF might be linear). Let's say the original collection has 1 million entities, and you delete 999999 entities, then only one entity is compute, much faster than search 1 million entities.

**Reply by AndrewOYLK** [reply]
@yhmo Regarding the process of upgrading from v2.4.5 to v2.4.15, in addition to replacing the milvus image, do the image versions of etcd and pulsar need to be replaced? Are there any precautions related to the upgrade? I am mainly worried about the confusion and loss of metadata during the upgrade process.

**Reply by AndrewOYLK** [reply]
@yhmo If the version of the milvus component is upgraded, then the milvus sdk used by the business must also be upgraded, right?

**Reply by yhmo** [reply]
Follow the doc to upgrade: 
https://milvus.io/docs/upgrade_milvus_cluster-helm.md

I suppose the version of etcd/pulsar has been configured by the milvus-helm, users no need to care the version.

The doc has provided the latest version of sdk which is compatible with the latest milvus: https://milvus.io/docs/install-pymilvus.md
Normally, an old version sdk also works well for normal interfaces such as create/insert/delete/search/query, the problem is the old version sdk doesn't have the new functions.
For example, I use pymilvus 2.3 to connect with milvus 2.4.15, the normal interface insert/search/query also work. But I cannot use this sdk to create sparse vector field, I cannot use hybrid_search because the old version sdk doesn't have this interface.

**Reply by AndrewOYLK** [reply]
I did not use helm to deploy the entire milvus system. I deployed etcd and pulsar components independently, and s3 used aliyun oss. So for this upgrade, I will independently upgrade the version of the milvus component (from v2.4.5->v2.4.15). I am not sure whether the current versions of etcd or pulsar will have any impact if I continue to use them.

**Reply by yhmo** [reply]
To know the required versions of etcd/pulsar/minio, download the milvus-helm latest release tar file form here: https://github.com/zilliztech/milvus-helm/releases/tag/milvus-4.2.19
Extract the tar file, open the requirements.yaml to see the version.


```
dependencies:
- name: etcd
  version: 6.3.3
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.17
  repository: https://zilliztech.github.io/milvus-helm
  condition: minio.enabled
  tags:
    - minio
- name: pulsar
  version: 2.7.8
  repository: https://pulsar.apache.org/charts
  condition: pulsar.enabled
  tags:
    - pulsar
- name: kafka
  version: 15.5.1
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: kafka.enabled
  tags:
    - kafka
```
