### DISCUSSION TITLE
how can i set the milvus log level

### DISCUSSION THREAD

**Discussion by huangxueliang** [milvus-io/milvus#37584] [Show and tell]
![image](https://github.com/user-attachments/assets/d0bb1f43-2f45-4ba3-8897-7d9ce5377221)

the milvus docker log is too big, how can i set the log level?

**Comment by yhmo** [comment]
I think it is a docker issue. Search "How to clean Docker container logs?" to get the answer.
Milvus log level default is info, defined in the milvus.yaml:

```
# Configures the system log output.
log:
  # Milvus log level. Option: debug, info, warn, error, panic, and fatal. 
  # It is recommended to use debug level under test and development environments, and info level in production environment.
  level: info
  file:
    # Root path to the log files.
    # The default value is set empty, indicating to output log files to standard output (stdout) and standard error (stderr).
    # If this parameter is set to a valid local path, Milvus writes and stores log files in this path.
    # Set this parameter as the path that you have permission to write.
    rootPath: 
    maxSize: 300 # The maximum size of a log file, unit: MB.
    maxAge: 10 # The maximum retention time before a log file is automatically cleared, unit: day. The minimum value is 1.
    maxBackups: 20 # The maximum number of log files to back up, unit: day. The minimum value is 1.
  format: text # Milvus log format. Option: text and JSON
  stdout: true # Stdout enable or not
```

To change the configuration, follow this doc: https://milvus.io/docs/configure-docker.md?tab=component#Configure-Milvus-with-Docker-Compose
