### DISCUSSION TITLE
No log is found after accessLog is configured

### DISCUSSION THREAD

**Discussion by 1292253144** [milvus-io/milvus#37854] [Q&A and General discussion]
helm
milvus：2.4.15
value.yaml:
proxy:
  enabled: true
  # You can set the number of replicas to -1 to remove the replicas field in case you want to use HPA
  replicas: 3
  accessLog:
    enable: true
    filename: "access_log.txt"
    localPath: "/var/log/milvus"
    maxSize: 500
    rotatedTime: 24
    maxBackups: 7
    minioEnable: true
    remotePath: "/milvus/logs/access_logs"
    remoteMaxTime: 0

No log is found after the cluster deployment. Procedure

**Comment by yhmo** [comment]
In the milvus.yaml, the access log configuration is under the "proxy" section: https://github.com/milvus-io/milvus/blob/714421997c01b90fd0c7992ece390428c98fb9f9/configs/milvus.yaml#L292
```
proxy:
  accessLog:
    enable: false # Whether to enable the access log feature.
    minioEnable: false # Whether to upload local access log files to MinIO. This parameter can be specified when proxy.accessLog.filename is not empty.
    filename:  # The name of the access log file. If you leave this parameter empty, access logs will be printed to stdout.
    remotePath: access_log/  # The path of the object storage for uploading access log files.
```

In values.yml, we configure milvus by the "extraConfigFiles" section:
https://github.com/zilliztech/milvus-helm/blob/6008482c88f5ba5976337fd86eb644d4716a6abb/charts/milvus/values.yaml#L67

So, I suppose the correct configuration should be:
```
extraConfigFiles:
  user.yaml: |+
      proxy:
        accessLog:
          enable: true
          minioEnable: true
          filename: access_log.txt
          remotePath: milvus/logs/access_logs
```
