### DISCUSSION TITLE
How to Disable Authorization Warnings in Milvus-Proxy?

### DISCUSSION THREAD

**Discussion by kietheros** [milvus-io/milvus#38093] [Announcement]
milvus-proxy prints a lot of lines like the following

> milvus-proxy-1  | [2024/11/29 04:58:36.237 +00:00] [WARN] [proxy/hook_interceptor.go:146] ["fail to get current user"] [error="fail to get authorization from the md, authorize:[authorization]"]
In the milvus.yaml file, I have the following configuration:
```yaml
common:
  security:
    authorizationEnabled: false
    # The superusers will ignore some system check processes,
    # like the old password verification when updating the credential
    # superUsers: root
    tlsMode: 0

```
I don’t need to use authentication for Milvus. How can I disable these warning logs?
