### DISCUSSION TITLE
Stand-alone deployment fails to dump access logs to a file when configured for it

### DISCUSSION THREAD

**Discussion by zeeIBM** [milvus-io/milvus#38115] [Q&A and General discussion] [answered]
Environment: Standalone on docker 
Version: 2.4

When configured for dumping access logs to a file. The access logs are not being generated in the file. I even manually created the directory and file with open permissions to it.

It did not work. My config in milvus.yaml are:

```
accessLog:
    enable: true # if use access log
    minioEnable: false # if upload sealed access log file to minio
    localPath: /tmp/milvus_access/
    filename: "access.log"  # Log filename, leave empty to use stdout.
    maxSize: 64 # Max size for a single file, in MB.
    cacheSize: 10240 # Size of log of memory cache, in B
    rotatedTime: 0 # Max time for single access log file in seconds
    remotePath: access_log/ # File path in minIO
    remoteMaxTime: 0 # Max time for log file in minIO, in hours
    formatters:
      base:
        format: "[ACCESS] [trace id: $trace_id] [database: $database_name] [$time_now] <$user_addr : $user_name> $method_name [method status: $method_status] [collection name: $collection_name] [response size: $response_size] [query expression: $method_expr] [error code: $error_code] [error msg: $error_msg]"
```

**Comment by aoiasd** [comment]
Can not reproduce in 2.4.7
![image](https://github.com/user-attachments/assets/14ac1e9d-0d6d-4e3c-9da9-49b0212e501b)
May caused by cacheSize set as 10240(10KB),  means log won't write to file till log data in memory size large than 10KB, and will loss some log if program died.

**Comment by yhmo** [comment]
Follow these steps:
1. set milvus.yaml
```
accessLog:
    enable: true
    localPath: /tmp/milvus_accesslog
    filename: "access.log"
```
2. docker compose up -d
3. docker ps
4. docker exec -it [milvus_container_id] bash
5. cd /tmp/milvus_accesslog
6. cat access.log
![Screenshot from 2024-12-02 12-03-35](https://github.com/user-attachments/assets/844ad8c5-5d19-4dd0-b0ad-f479d2dd70e9)
