### DISCUSSION TITLE
boolean expr filtering performance

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#38367] [Q&A and General discussion] [answered]
- milvus version: 2.4.x
- mode: cluster

When filtering with equality comparison based on specific metadata fields, is there a preferred method between `TermExpr` and `BinaryLogicalOp/CmpOp` in terms of performance? For example, I would like to know if there is a recommended approach between these two options:

- source_id in ["s1", "s2", "s3"]
- source_id == "s1" || source_id == "s2" || source_id == "s3"

Additionally, is there a limit to the number of items that can be included in the `ConstantArray` of `TermExpr`?

**Comment by yhmo** [comment, marked as answer]
I think "source_id in ["s1", "s2", "s3"]" is better, because it is shorter than another.

The length of a filtering expression is limited by RPC transfer limitation. In milvus, RPC transfer limitation is configured in the milvus.yaml
```
proxy:
  grpc:
    serverMaxSendSize: 268435456
    serverMaxRecvSize: 67108864
    clientMaxSendSize: 268435456
    clientMaxRecvSize: 67108864
```

The "serverMaxRecvSize" is the max size of a request received by proxy node. Default value is 64MB. Filtering expression is a parameter of the search interface, size of all the parameters should be less than 64MB, otherwise it will throw a rpc error.
