### DISCUSSION TITLE
Issue with using an external Kafka

### DISCUSSION THREAD

**Discussion by ivivi** [milvus-io/milvus#38713] [Q&A and General discussion]
When using an external Kafka, the Kafka parameter auto.create.topics.enable is set to false. 
By configuring the preCreatedTopic parameter, you can specify topics related to DML. 
So, how to configure topics related to the following: replicate-msg, rootcoord-delta, and queryTimeTick, or how to manually create them in Kafka?

**Comment by yhmo** [comment]
This discussion is about using pre-created-topics in milvus: https://github.com/milvus-io/milvus/discussions/30916

Only two kinds of topics: dml and time-tick
Define the pre-created-topics in the milvus.yaml:
```
common: 
# preCreatedTopic decides whether using existed topic
 preCreatedTopic:
   # support pre-created topics
   enabled: true
   
   # the name of pre-created topics
   names: ['topic1', 'topic2']

   # need to set a separated topic to stand for currently consumed timestamp for each channel
   timeticker: 'timetick-channel'
```

"how to manually create them in Kafka" ----------------- I suppose you can get the answer from the Kafka community/documents

**Reply by ivivi** [reply]
Thanks for your reply.

With below configs:
auto.create.topics.enable=false in external kafka cluster
as below in yaml file
```
preCreatedTopic:
    enabled: true
    names: ['milvus-dml-1', 'milvus-dml-2', ...,'milvus-dml-16']
    timeticker: 'milvus-timetick-channel'
```

I can create a collection, but when the queryNode tries to load this collection during creation, the following error occurs:

> 2024-12-25T02:28:00.539524880Z BACKTRACE:
> github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).WatchDmChannels
> 2024-12-25T02:28:31.457362927Z /workspace/source/internal/querynodev2/services.go:323 pc=0x4e4d4de
> panic: runtime error: invalid memory address or nil pointer dereference

The code with the error is:
```
position := &msgpb.MsgPosition{
ChannelName: channel.SeekPosition.ChannelName, //line 323
MsgID: channel.SeekPosition.MsgID,
Timestamp: channel.SeekPosition.Timestamp,
}
```

However, everything works fine when I use auto.create.topics.enable=true in external Kafka and
```
preCreatedTopic:
  enabled: false
```
in the YAML file. 
So, is there still a lack of some topics here?

milvus version: v2.4.17
