### DISCUSSION TITLE
K8s集群部署milvus-v2.4.9集群， 如何设置milvus用户名密码访问呢，求助

### DISCUSSION THREAD

**Discussion by jhyever** [milvus-io/milvus#38819] [Q&A and General discussion]
helm部署只有values.yaml文件，没有对应的milvus.yaml文件了啊
![image](https://github.com/user-attachments/assets/8a5c4397-4484-4d9c-bf45-e764fcbd65a6)

**Comment by yhmo** [comment]
在standalone模式下，milvus.yaml里，要开启authorization，设置common.security.authorizationEnabled=true
```
common:
  security:
    authorizationEnabled: false
    # The superusers will ignore some system check processes,
    # like the old password verification when updating the credential
    superUsers: 
    defaultRootPassword: Milvus # default password for root user
```

k8s部署milvus集群时，不直接设置milvus.yaml，而是设置value.yaml: https://milvus.io/docs/configure-helm.md?tab=component
value.yaml中extraConfigFiles.user.yaml下面的设置，都会被优先设置(即覆盖掉默认的milvus.yaml中的内容)
要开启authorization，这么设：
```
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
        superUsers: 
        defaultRootPassword: Milvus
```
默认会有个超级用户 "root"，密码是 "Milvus"
不建议在里面设置superusers和defaultRootPassword
启动集群之后，应该使用RBAC的create_users()接口来增加users，并使用update_password()接口修改你的super user password
https://milvus.io/docs/users_and_roles.md

**Reply by jhyever** [reply]
如果在这里设置了之后，
```
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
        superUsers:   root
        defaultRootPassword: Milvus@1234

或
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
        superUsers:   admin
        defaultRootPassword: admin@1234
```

原先的默认超级用户 "root"，密码是 "Milvus"会不会无效了

**Reply by yhmo** [reply]
你还是用RBAC接口create_users()来创建吧。我试了一下superUsers/defaultRootPassword这两个配置没有效果，也许是代码改坏了。

value.yaml里只设置authorizationEnabled
```
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
```
