### DISCUSSION TITLE
请问有没有一份最新的query node balancer的架构解释？

### DISCUSSION THREAD

**Discussion by xiaobingxia-at** [milvus-io/milvus#39069] [Q&A and General discussion]
请教一下各位大佬。Cluster 2.5.2, 600k partitions. 我发现我的query node频繁load / release segments，我怀疑是balancer频繁在不同query node上切segments。我的balancer的设置如下：
```
queryCoord:
            autoBalance: true
            autoBalanceChannel: true
            memoryUsageMaxDifferencePercentage: 10
            checkBalanceInterval: 120000 # check balance every 120 seconds
            overloadedMemoryThresholdPercentage: 90
```

请问有没有什么问题？

我在源码中看到有两个balancer: 
https://github.com/milvus-io/milvus/blob/master/internal/querycoordv2/balance/balance.go
https://github.com/milvus-io/milvus/blob/master/internal/querycoordv2/balance/score_based_balancer.go

config里默认的balancer type是score based balancer. 在运行中，这两个都在跑吗？还是只有score based balancer再跑？
目前有没有详细的材料解释一下所有的balancer的运行规则和使用手册？目前我只找到了这个： https://milvus.io/blog/2022-02-28-how-milvus-balances-query-load-across-nodes.md 但是感觉里面有些信息已经过时了。而且我发现score based的balancer，规则极为复杂。如果网站给篇doc详细解释一下就最好了。感谢！
