### DISCUSSION TITLE
Deploying Milvus CDC

### DISCUSSION THREAD

**Discussion by ayushk5-ai** [milvus-io/milvus#39360] [Q&A and General discussion]
I am trying to install Milvus CDC, on Milvus Standalone v2.4.x
I have followed through the steps mentioned here: https://milvus.io/docs/v2.4.x/deploy-cdc-server.md

But after creating the docker image of milvus-cdc, how to proceed and what next steps to follow?

**Comment by ayushk5-ai** [comment]
"For a Docker image, mount the compiled file to /app/server/configs/cdc.yaml within the container."

What does this line means in the official documentation?

**Comment by yhmo** [comment]
No need to build the image by yourself.
There is a docker-compose.yaml under the cdc repo: https://github.com/zilliztech/milvus-cdc/blob/main/deployment/docker/docker-compose.yaml

In this docker-compose.yaml, we can see:
```
services:
  milvus-cdc:
    container_name: milvus-cdc
    image: milvusdb/milvus-cdc:latest
    tty: true
    volumes:
      - type: bind
        source: ./cdc.yaml
        target: /app/configs/cdc.yaml
        read_only: true
    network_mode: "host"
```

This docker-compose.yaml download the official image from dockhub, and launch a cdc container for you.
The "volumes" defines a path mapping for the cdc.yaml
The inner cdc.yaml is mapped to the outside cdc.yaml: https://github.com/zilliztech/milvus-cdc/blob/main/deployment/docker/cdc.yaml

The cdc.yaml defines the source etcd and source pulsar address, and the metastore for milvus-cdc to store tasks infomation.
- sourceConfig.etcd is the etcd service of the source milvus cluster
- sourceConfig.pulsar is the pulsar service of the source milvus cluster
- metaStoreConfig.etcd is the etcd service to store milvus-cdc tasks

Once the milvus-cdc container started successfully, you can create tasks to sync data to target milvus. Read this doc for more info:
https://github.com/zilliztech/milvus-cdc/blob/main/doc/cdc-usage.md

**Reply by ayushk5-ai** [reply]
```
services:
  etcd:
    container_name: milvus-etcd
    image: custom-etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
```

This is a snippet of docker-compose file of the source etcd milvus.
In cdc.yaml file, I am using the etcd address as 127.0.0.1:2379, but still not working, what should be there?

Milvus-CDC and Milvus standalone are on the same server
Also, the metastore etcd is on the same server

Where would I get the address for metaStoreConfig.etcd and sourceConfig.etcd ??
Is it the address of the linux server on which it is installed?

**Reply by yhmo** [reply]
Expose the port 2379 of the "milvus-etcd" container to the host port 12379:
```
services:
  etcd:
    container_name: milvus-etcd
    ......
    ports:
      - "12379:2379"
```

Set 127.0.0.1:12379 as the sourceConfig.etcd.address
Set 127.0.0.1:2379 as the metaStoreConfig.etcd.address

**Reply by ayushk5-ai** [reply]
Thanks, that worked

Now, while running the container, it gives this and container isn't starting

<img width="815" alt="image" src="https://github.com/user-attachments/assets/9d59d583-4127-4b15-829e-c6b53812fd01" />


This is my cdc.yaml file

```
address: 0.0.0.0:8444
maxTaskNum: 100
metaStoreConfig:
  storeType: etcd
  etcd:
    address:
      - 127.0.0.1:2379
    enableAuth: false
    username: analytics
    password:
    enableTLS: false
    tlsCertPath: deployment/cert/client.pem # path to your cert file
    tlsKeyPath: deployment/cert/client.key # path to your key file
    tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
    tlsMinVersion: 1.3
#  mysqlSourceUrl: root:root@tcp(127.0.0.1:3306)/milvuscdc?charset=utf8
  rootPath: /data/analytics/milvus/volumes/etcd-cdc
sourceConfig:
  etcd:
    address:
      - 127.0.0.1:2379
    rootPath: /data/analytics/milvus/volumes/etcd
    metaSubPath: meta
    enableAuth: false
    username: analytics
    password:
    enableTLS: false
    tlsCertPath: deployment/cert/client.pem # path to your cert file
    tlsKeyPath: deployment/cert/client.key # path to your key file
    tlsCACertPath: deployment/cert/ca.pem # path to your CACert file
    tlsMinVersion: 1.3
  readChanLen: 4
  defaultPartitionName: _default
  replicateChan: by-dev-replicate-msg
  pulsar:
    address: pulsar://localhost:6650
    webAddress: localhost:80
    maxMessageSize: 5242880
    tenant: public
    namespace: default
#    authPlugin: org.apache.pulsar.client.impl.auth.AuthenticationToken
#    authParams: token:xxx
#  kafka:
#    address: 127.0.0.1:9092
maxNameLength: 256
logLevel: info
detectDeadLock: false
```

sourceConfig.rootpath is the location of my milvus etcd storage
metaStoreConfig.rootpath is the location of my cdc etcd storage

What is causing my current issue?

**Reply by xiaofan-luan** [reply]
check you pulsar address and see if it's connectable from your cdc server

**Reply by ayushk5-ai** [reply]
@yhmo 
Is pulsar even necessary for connection of Milvus Standalone with CDC?
Also, I think there is an issue with `replicateChan` and `defaultPartitionName` , how do I verify that it's correct?

**Reply by SimFG** [reply]
![image](https://github.com/user-attachments/assets/f2642590-de2e-4700-9350-63667f4dba94)
you can give more detail in the doc: https://github.com/zilliztech/milvus-cdc/blob/main/doc/cdc-usage.md

**Reply by ayushk5-ai** [reply]
But I am currently running Milvus standalone on a single node, so how does this makes sense?

**Reply by yhmo** [reply]
> But I am currently running Milvus standalone on a single node, so how does this makes sense?

Ok, the problem is Milvus standalone doesn't use pulsar/kafka, it uses a built-in rockdb to implement the message queue. So, the milvus-cdc could not access this built-in rockdb since the rockdb is not an independent service.

Only the milvus services that use pulsa/kafka can be accessed by milvus-cdc.

If you want to use Milvus standalone with Pulsar as message queue, use this docker-compose.yaml to deploy:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.16
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    ports:
      - "2379:2379"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.8.2
    ports:
      - "6650:6650"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/pulsar:/pulsar/data
    environment:
      # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
      # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
      
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.2
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
      - "pulsar"

networks:
  default:
    name: milvus
```

And configure the message queue type in the milvus.yaml:
```
mq:
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: pulsar
```

**Reply by ayushk5-ai** [reply]
In cdc.yaml
```
pulsar:
    address: pulsar://pulsar:6650
    webAddress: localhost:80
    maxMessageSize: 5242880
    tenant: public
    namespace: default
 ```
 
 In milvus.yaml
 ```
 pulsar:
  # IP address of Pulsar service.
  # Environment variable: PULSAR_ADDRESS
  # pulsar.address and pulsar.port together generate the valid access to Pulsar.
  # Pulsar preferentially acquires the valid IP address from the environment variable PULSAR_ADDRESS when Milvus is started.
  # Default value applies when Pulsar is running on the same network with Milvus.
  address: localhost
  port: 6650 # Port of Pulsar service.
  webport: 80 # Web port of of Pulsar service. If you connect direcly without proxy, should use 8080.
  # The maximum size of each message in Pulsar. Unit: Byte.
  # By default, Pulsar can transmit at most 2MB of data in a single message. When the size of inserted data is greater than this value, proxy fragments the data into multiple messages to ensure that they can be transmitted correctly.
  # If the corresponding parameter in Pulsar remains unchanged, increasing this configuration will cause Milvus to fail, and reducing it produces no advantage.
  maxMessageSize: 2097152
  # Pulsar can be provisioned for specific tenants with appropriate capacity allocated to the tenant.
  # To share a Pulsar instance among multiple Milvus instances, you can change this to an Pulsar tenant rather than the default one for each Milvus instance before you start them. However, if you do not want Pulsar multi-tenancy, you are advised to change msgChannel.chanNamePrefix.cluster to the different value.
  tenant: public
  namespace: default # A Pulsar namespace is the administrative unit nomenclature within a tenant.
  requestTimeout: 60 # pulsar client global request timeout in seconds
  enableClientMetrics: false # Whether to register pulsar client metrics into milvus metrics path.
  ``` 

It's still not working, giving same issue
Error : milvus-cdc         | panic: Failed to create consumer by-dev-replicate-msg, errors = connection error
Is this correct?
Also, will there be any change in value for ``replicateChan`` and ``defaultPartitionName`` ?
@yhmo

**Reply by yhmo** [reply]
Use this yaml to deploy a milvus standalone with pulsar:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.16
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    ports:
      - "2379:2379"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.8.2
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/pulsar:/pulsar/data
    environment:
      # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
      # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
      
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.2
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
      - "pulsar"

networks:
  default:
    name: milvus
```

Note that the port 8080 is exposed for the pulsar container.
Now we can see 4 container started:
![Screenshot from 2025-01-21 10-05-46](https://github.com/user-attachments/assets/9a9cb4b9-53b3-4407-a34d-81088ff8b1a0)

Use this command to test the pulsar server, this command returns the topics created by milvus:
`curl http://127.0.0.1:8080/admin/v2/persistent/public/default `
![Screenshot from 2025-01-21 10-32-56](https://github.com/user-attachments/assets/9404dd7e-d53f-4599-8c8f-c9ca0a8b7106)

Now edit the milvus-cdc/deployment/docker/cdc.yaml, since we expose the port 8080, we set pulsar.webAddress to be "localhost:8080"
```
sourceConfig:
  pulsar:
    address: pulsar://localhost:6650
    webAddress: localhost:8080
    maxMessageSize: 5242880
    tenant: public
    namespace: default
```
Then start the cdc server by the milvus-cdc/deployment/docker/docker-compose.yaml, now there are 5 containers
![Screenshot from 2025-01-21 10-35-58](https://github.com/user-attachments/assets/09cb435c-a179-4dc6-9c4f-e6686e52b120)

Check the log of the cdc server by command `docker logs [cdc container id]`, we can see it successfully started:
```
logLevel: info
[2025/01/21 02:29:12.960 +00:00] [INFO] [paramtable/component_param.go:4433] ["DeployModeEnv is not set, use default"] [default=0.5]
[2025/01/21 02:29:12.964 +00:00] [INFO] [paramtable/hook_config.go:21] ["hook config"] [hook={}]
[2025/01/21 02:29:12.965 +00:00] [INFO] [tag/tag.go:34] ["base info"] [BuildTime="Mon Dec  9 02:56:00 UTC 2024"] [GitCommit=369b60f] [GoVersion="go version go1.21.13 linux/amd64"]
[2025/01/21 02:29:12.970 +00:00] [INFO] [msgstream/mq_msgstream.go:121] ["Msg Stream state"] [can_produce=true]
[2025/01/21 02:29:13.038 +00:00] [INFO] [msgstream/mq_msgstream.go:211] ["Successfully create consumer"] [channel=by-dev-replicate-msg] [subname=by-dev-replicate-msg6177349651008098624]
[2025/01/21 02:29:13.038 +00:00] [INFO] [msgstream/mq_msgstream.go:221] ["start to close mq msg stream"] ["producer num"=0] ["consumer num"=1]
[2025/01/21 02:29:13.048 +00:00] [INFO] [server/server.go:56] ["start server..."]

```

**Reply by ayushk5-ai** [reply]
What if I use kafka in place of pulsar?
Should I follow the same steps - pull kafka image, then add the kafka address in cdc.yaml file ?
@yhmo

**Reply by yhmo** [reply]
In the milvus.yaml, set mq.type to kafka, comment out the pulsar configurations, enable kafka configurations, set kafka.brokerList to your kafka service
```
mq:
  # Default value: "default"
  # Valid values: [default, pulsar, kafka, rocksmq, natsmq]
  type: kafka

# # Related configuration of pulsar, used to manage Milvus logs of recent mutation operations, output streaming log, and provide log publish-subscribe services.
# pulsar:
#   # IP address of Pulsar service.
#   # Environment variable: PULSAR_ADDRESS
#   # pulsar.address and pulsar.port together generate the valid access to Pulsar.
#   # Pulsar preferentially acquires the valid IP address from the environment variable PULSAR_ADDRESS when Milvus is started.
#   # Default value applies when Pulsar is running on the same network with Milvus.
#   address: localhost
#   port: 6650 # Port of Pulsar service.
#   webport: 80 # Web port of of Pulsar service. If you connect direcly without proxy, should use 8080.
#   # The maximum size of each message in Pulsar. Unit: Byte.
#   # By default, Pulsar can transmit at most 2MB of data in a single message. When the size of inserted data is greater than this value, proxy fragments the data into multiple messages to ensure that they can be transmitted correctly.
#   # If the corresponding parameter in Pulsar remains unchanged, increasing this configuration will cause Milvus to fail, and reducing it produces no advantage.
#   maxMessageSize: 2097152
#   # Pulsar can be provisioned for specific tenants with appropriate capacity allocated to the tenant.
#   # To share a Pulsar instance among multiple Milvus instances, you can change this to an Pulsar tenant rather than the default one for each Milvus instance before you start them. However, if you do not want Pulsar multi-tenancy, you are advised to change msgChannel.chanNamePrefix.cluster to the different value.
#   tenant: public
#   namespace: default # A Pulsar namespace is the administrative unit nomenclature within a tenant.
#   requestTimeout: 60 # pulsar client global request timeout in seconds
#   enableClientMetrics: false # Whether to register pulsar client metrics into milvus metrics path.

# If you want to enable kafka, needs to comment the pulsar configs
kafka:
  brokerList: you_kafka_service:9092
  saslUsername: 
  saslPassword: 
  saslMechanisms: 
  securityProtocol: 
  ssl:
    enabled: false # whether to enable ssl mode
    tlsCert:  # path to client's public key (PEM) used for authentication
    tlsKey:  # path to client's private key (PEM) used for authentication
    tlsCaCert:  # file or directory path to CA certificate(s) for verifying the broker's key
    tlsKeyPassword:  # private key passphrase for use with ssl.key.location and set_ssl_cert(), if any
  readTimeout: 10
```

In the cdc.yaml, comment out pulsar configurations, enable kafka configurations, set sourceConfig.kafka.address to your kafka service:
```
sourceConfig:
#  pulsar:
#    address: pulsar://localhost:6650
#    webAddress: localhost:80
#    maxMessageSize: 5242880
#    tenant: public
#    namespace: default
#    authPlugin: org.apache.pulsar.client.impl.auth.AuthenticationToken
#    authParams: token:xxx
  kafka:
    address: your_kafka_service:9092
```
