### DISCUSSION TITLE
Milvus log location when running in a docker dev container.

### DISCUSSION THREAD

**Discussion by rsrs2013** [milvus-io/milvus#39609] [Q&A and General discussion] [answered]
Hello Community,

I am trying to include some log statements in the search code of Milvus.
I am following the steps mentioned in [Build Milvus from source code](https://github.com/milvus-io/milvus/blob/master/build/README.md) under the "Dev Containers" section. 

I went inside the build container 'milvus_builder_1' and did 'make milvus'. Milvus started successfully and printed the log to the standard output.
**Question:**
Is there any separate file in which the logs are stored or is it only printed to the standard output ? Where can I find the file. I searched in the /tmp/milvus directory. I couldn't find it.

- Thanks in advance.

**Comment by yhmo** [comment, marked as answer]
Once you successfully make a milvus docker container, there should be a configuration file under this path inside the container: /milvus/configs/milvus.yaml

In the milvus.yaml, you will see the configuration for log:
https://github.com/milvus-io/milvus/blob/b3791a6f903c0fdefaef4bc26b55f091de8334a0/configs/milvus.yaml#L757

```
# Configures the system log output.
log:
  # Milvus log level. Option: debug, info, warn, error, panic, and fatal. 
  # It is recommended to use debug level under test and development environments, and info level in production environment.
  level: info
  file:
    # Root path to the log files.
    # The default value is set empty, indicating to output log files to standard output (stdout) and standard error (stderr).
    # If this parameter is set to a valid local path, Milvus writes and stores log files in this path.
    # Set this parameter as the path that you have permission to write.
    rootPath: 
    maxSize: 300 # The maximum size of a log file, unit: MB.
    maxAge: 10 # The maximum retention time before a log file is automatically cleared, unit: day. The minimum value is 1.
    maxBackups: 20 # The maximum number of log files to back up, unit: day. The minimum value is 1.
  format: text # Milvus log format. Option: text and JSON
  stdout: true # Stdout enable or not
```

By default, the logs are output to stdout. To output a log file, you can set the log.rootPath to /milvus/log.txt
