### DISCUSSION TITLE
How to use with docker

### DISCUSSION THREAD

**Discussion by ChocoL0rd** [milvus-io/milvus#39774] [Q&A and General discussion]
I asked GPT to write code for using milvus in docker. It writes code like:

```
from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection
connections.connect(
    alias="default", 
    host="milvus", 
    port=settings.milvus_port
)

fields = [...] # Some FieldSchemas
schema = CollectionSchema(fields)
collection = Collection(name=collection_name, schema=schema)
```

this is part in docker-compose for milvus
```
milvus:
    image: milvusdb/milvus:latest
    platform: linux/amd64
    environment:
      MILVUS_MODE: standalone
      LD_PRELOAD: ""
      OTEL_TRACES_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
    command: [ "milvus", "run", "standalone" ]
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - milvus_data:/var/lib/milvus

```

This code look strange for me (idk is it even working), because milvus documentation uses MilvusClient. How can i connect to my milvus container and what the difference between MilvusClient and connections. What should i use?
