### DISCUSSION TITLE
milvus  访问etcd认证用户需要什么权限，配置了auth.enabled和auth.userName,auth.password，但是还是报错：Permission Denied

### DISCUSSION THREAD

**Discussion by bhxiaoxinba** [milvus-io/milvus#39821] [Q&A and General discussion]
是用户的访问权限不足吗？需要什么权限？
retrying of unary invoker failed","target":"etcd-endpoints://0xc001882540/xxxx:2379","attempt":0,"error":"rpc error: code = PermissionDenied desc = etcdserver: permission denied"

**Comment by yhmo** [comment]
1. 用这个docker-compose.yaml起一个etcd服务：
```
version: '3.5'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.16
    container_name: milvus-etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
    environment:
      - ETCD_NAME=etcd1
      - ETCD_DATA_DIR=/var/etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=no
      - ETCD_HEARTBEAT_INTERVAL=200
      - ETCD_ELECTION_TIMEOUT=1000
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LOGGER=zap
    volumes:
      - ./etcd1-data:/var/etcd
    networks:
      - milvus

networks:
  milvus:
```

2. 用etcdctl启用etcd的auth，建立一个名为"root"的user，密码为"123456"
```
etcdctl user add root
etcdctl auth enable
```
验证密码是否生效: `etcdctl --user=root --password="123456" endpoint health`
如果不用密码， `etcdctl endpoint health` 是连不上的
![Screenshot from 2025-02-12 17-12-55](https://github.com/user-attachments/assets/a343849b-06fe-48dc-94c1-db9390de3f90)

3. 用这个docker-compose.yaml起一个milvus standalone
注意这里面的ETCD_ENDPOINTS我是用了etcd所在机器的IP
```
version: '3.5'

services:
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.4
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: 172.16.50.29:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "minio"

networks:
  default:
    name: milvus

```
在milvus.yaml里我设置了etcd的user/password
```
etcd:
  auth:
    enabled: true
    userName: root
    password: 123456
```
milvus的日志里可以看到以下日志，表明它连接etcd成功
```
[2025/02/12 09:06:23.541 +00:00] [DEBUG] [paramtable/base_table.go:213] ["init etcd source"] [etcdInfo="{\"UseEmbed\":false,\"EnableAuth\":true,\"UserName\":\"root\",\"PassWord\":\"123456\",\"UseSSL\":false,\"Endpoints\":[\"172.16.50.29:2379\"],\"KeyPrefix\":\"by-dev\",\"CertFile\":\"/path/to/etcd-client.pem\",\"KeyFile\":\"/path/to/etcd-client-key.pem\",\"CaCertFile\":\"/path/to/ca.pem\",\"MinVersion\":\"1.3\",\"RefreshInterval\":5000000000}"]
[2025/02/12 09:06:23.542 +00:00] [INFO] [etcd/etcd_util.go:152] ["create etcd client(enable auth)"] [useSSL=false] [endpoints="[172.16.50.29:2379]"] [minVersion=1.3]
```
然后用milvus sdk随便调用几个milvus接口，工作正常。
