### DISCUSSION TITLE
how to set dependencies image version within milvus-operator

### DISCUSSION THREAD

**Discussion by cherrylzhao** [milvus-io/milvus#39912] [Q&A and General discussion]
hi, everyone

I have installed milvus-operator v1.2.0 in k8s, 
as docker images managed by private container repository, I need to create Milvus cluster modified the default image version label.
but I cannot found any dependencies image version in CRD doc, how can I modify it as below, thanks
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: opmilvus
  labels:
    app: opmilvus
spec:
  mode: cluster
  components:
    image: xxx/milvusdb/milvus:v2.5.4 # 指定 Milvus 的镜像版本
  dependencies:
    etcd:
        image: xxx/milvusdb/etcd:3.5.16-r1 # 指定 etcd 的镜像版本
    pulsar:
        image: xxx/milvusdb/pulsar:3.0.7 # 指定 Pulsar 的镜像版本
    minio:
        image: xxx/milvusdb/minio:RELEASE.2023-03-20T20-16-18Z # 指定 MinIO 的镜像版本
```

**Comment by haorenfsa** [comment]
The dependencies helm values are managed in 
-`spec.dependencies.etcd.inCluster.values`
-`spec.dependencies.pulsar.inCluster.values`
-`spec.dependencies.storage.inCluster.values`

You can manage these values according to their helm chart.
- https://artifacthub.io/packages/helm/bitnami/etcd/8.2.4?modal=values
- https://artifacthub.io/packages/helm/apache/pulsar/3.3.0?modal=values
- https://artifacthub.io/packages/helm/milvus/minio?modal=values

**Reply by cherrylzhao** [reply]
thanks very much, it worked for me.
by the way, can I override the default image according 'helm install milvus-operator' ?

**Reply by haorenfsa** [reply]
Of course, https://artifacthub.io/packages/helm/milvus-operator/milvus-operator?modal=values

**Reply by cherrylzhao** [reply]
but I can't find dependency field within value.yaml of  milvus-operator, I want to override the image of Etcd , pulsar, minio through value.yaml , but I can only find the milvus-operator repository itself.

**Reply by haorenfsa** [reply]
Oh, I know what you mean. But that's not supported for milvus-operator yet.

**Reply by cherrylzhao** [reply]
thanks, could you tell me how to replace the image of `pulsar-pulsar-init` pod, other pod worked well except for it. 
the modified yaml as below
```
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          image:
            registry: xxx
            repository: milvusdb/etcd
            tag: 3.5.16-r1
    pulsar:
      inCluster:
        chartVersion: pulsar-v3
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          images:
            zookeeper:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            autorecovery:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            broker:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            proxy:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            bookie:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            functions:
              repository: xxx/milvusdb/pulsar
              tag: 3.0.7
            pulsar-init:
              repository: xxxx/milvusdb/pulsar
              tag: 3.0.7
```

<img width="800" alt="image" src="https://github.com/user-attachments/assets/1486674c-d5a6-4abb-9162-416c5ea3adc4" />
