### DISCUSSION TITLE
求助：实际存储大小与Size Tool估算的差距比较大

### DISCUSSION THREAD

**Discussion by tanwei2012** [milvus-io/milvus#39947] [Q&A and General discussion]
Milvus版本是v2.3.2 standalone， 数据量31M左右，包括一个vector字段和2个标量，向量维度256。按照最新版的sizing tool估算，raw data是28.6G， Milvus的local disk是0B， ETCD和Minio的storage是130G。实际统计三者的目录大小分表为：etcd为423M， milvus为318G， minio为84k。为什么会这样？是因为Milvus版本太老，跟最新的sizing tool不匹配？还是配置有问题，额外占用了空间？还是有临时文件未清理？

**Comment by yhmo** [comment]
31M 256dim, 如果是这个大小，你会看到"Standalone"的按钮是灰色，表明这个大小在standalone上跑不好估计，它不好计算。所以你看到的数值是cluster的，分布式的etcd/minio自己有多副本，使用的存储当然会以倍计。你如果不想用那么多存储，那你就把看到的数值除以etcd/minio的节点数量，比如那个etcd显示"x3"，那你就除以3，那个minio显示"x4"，那你就除以4。
![Screenshot from 2025-02-18 10-36-01](https://github.com/user-attachments/assets/4590ab78-7703-4af7-9a18-c26b68ebdcbf)

**Reply by tanwei2012** [reply]
> 31M 256dim, 如果是这个大小，你会看到"Standalone"的按钮是灰色，表明这个大小在standalone上跑不好估计，它不好计算。所以你看到的数值是cluster的，分布式的etcd/minio自己有多副本，使用的存储当然会以倍计。你如果不想用那么多存储，那你就把看到的数值除以etcd/minio的节点数量，比如那个etcd显示"x3"，那你就除以3，那个minio显示"x4"，那你就除以4。 ![Screenshot from 2025-02-18 10-36-01](https://private-user-images.githubusercontent.com/2282099/414071785-4590ab78-7703-4af7-9a18-c26b68ebdcbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NDc0OTgsIm5iZiI6MTczOTg0NzE5OCwicGF0aCI6Ii8yMjgyMDk5LzQxNDA3MTc4NS00NTkwYWI3OC03NzAzLTRhZjctOWExOC1jMjZiNjhlYmRjYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMThUMDI1MzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDEwZWIzNzVlODE1YTQxNzljMjc1MWQ3M2NjM2VlMzFkYWE4NWEyOTM3NDkxMzY4MjBlODY1YjVlNDUwNjc3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iugkij1gQZncDJR_QnV408iI7162gnTpQIbjApOjmQ4)

感谢您的回复，我是按照30M 256dim来计算的，raw data大概30G，etcd+minio是130G，总共160G，但从磁盘来看，milvus的数据目录320G左右，这两个数值有什么联系吗？

**Reply by yhmo** [reply]
milvus以segment管理数据，每个segment有单独的索引，多个segment还会合并。milvus有自己的垃圾回收机制，一般被删除的segment仍会占据磁盘若干个小时才会被清理。不管是standalone还是cluster，都有一个消息流组件，standalone的消息流组件是内置的一个rockdb实现，消息流存储于本地磁盘。鉴于以上的机制，milvus的写放大挺严重，硬盘空间消耗是原始数据量的5，6倍是常事。
如果原始数据量30GB，那么索引根据不同类型会有10GB到30+GB不等，消息流里存储的东西基本等同于原始数据量也就是30GB。合并操作产生的垃圾就更多了，也许是原始数据量的两倍以上。这些粗粗算下来就差不多150GB以上。

这是一个standalone产生的目录，minio目录里主要存的是milvus的原始数据和索引数据，milvus/rdb_data里存的是消息流数据，一般都是这两个目录很大：
![Screenshot from 2025-02-18 11-26-01](https://github.com/user-attachments/assets/3400ee70-b5d6-4e76-ac6d-8d10992bb8b1)

**Reply by tanwei2012** [reply]
> milvus以segment管理数据，每个segment有单独的索引，多个segment还会合并。milvus有自己的垃圾回收机制，一般被删除的segment仍会占据磁盘若干个小时才会被清理。不管是standalone还是cluster，都有一个消息流组件，standalone的消息流组件是内置的一个rockdb实现，消息流存储于本地磁盘。鉴于以上的机制，milvus的写放大挺严重，硬盘空间消耗是原始数据量的5，6倍是常事。 如果原始数据量30GB，那么索引根据不同类型会有10GB到30+GB不等，消息流里存储的东西基本等同于原始数据量也就是30GB。合并操作产生的垃圾就更多了，也许是原始数据量的两倍以上。这些粗粗算下来就差不多150GB以上。
> 
> 这是一个standalone产生的目录，minio目录里主要存的是milvus的原始数据和索引数据，milvus/rdb_data里存的是消息流数据，一般都是这两个目录很大： ![Screenshot from 2025-02-18 11-26-01](https://private-user-images.githubusercontent.com/2282099/414081613-3400ee70-b5d6-4e76-ac6d-8d10992bb8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NTAxNDksIm5iZiI6MTczOTg0OTg0OSwicGF0aCI6Ii8yMjgyMDk5LzQxNDA4MTYxMy0zNDAwZWU3MC1iNWQ2LTRlNzYtYWM2ZC04ZDEwOTkyYmI4YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMThUMDMzNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY5NDdhZjdjOGFkMGUzZWU4MTRjZDRiYzlkMzRhMDgxYmFlYzViYThhYzcwODM3Y2VhMWUwNjg1NGU0ZTk0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fAuE15md9uGou70HgJYM3MDfUNwy_kaNZTm1lDIKhWo)

感谢您的回复。我们的场景下，会有大量的单条数据插入，这样会不会造成更多的segment？未清理的segment导致磁盘大于计算值。另外，您提到的目录结构信息很有用，我发现我们的minio目录下磁盘占用很小，但按照sizing tool的估算，minio是占大头的，是不是我们的配置有误导致的？我们的320G数据大多数都在milvus/data目录下

**Reply by yhmo** [reply]
不要用sdk调用collection.flush()或者client.flush()这个接口即可，这样就不会产生大量碎片segment。如能批量插入就批量插入。
不过，单条插入对于消息流组件来说，产生的消耗是会比批量插入大得多的。就好比你去银行存钱，总共10万块钱，你每次存1块钱存10万次，和10万块钱批量存一次，所产生的手续费明显不一样。standalone的消息流是存储在milvus/rdb_data下。

milvus/data主要是用于mmap磁盘映射，查询或load的时候会把大量文件映射在这个目录。你可以把mmap配置全部关闭：
https://github.com/milvus-io/milvus/blob/76959244ef466c9370a3ac8809c2b772d0401929/configs/milvus.yaml#L430
```
queryNode:
  mmap:
    vectorField: false # Enable mmap for loading vector data
    vectorIndex: false # Enable mmap for loading vector index
    scalarField: false # Enable mmap for loading scalar data
    scalarIndex: false # Enable mmap for loading scalar index
    chunkCache: false # Enable mmap for chunk cache (raw vector retrieving).
    # Enable memory mapping (mmap) to optimize the handling of growing raw data. 
    # By activating this feature, the memory overhead associated with newly added or modified data will be significantly minimized. 
    # However, this optimization may come at the cost of a slight decrease in query latency for the affected data segments.
    growingMmapEnabled: false
    fixedFileSizeForMmapAlloc: 1 # tmp file size for mmap chunk manager
    maxDiskUsagePercentageForMmapAlloc: 10 # disk percentage used in mmap chunk manager
```
