### DISCUSSION TITLE
The node was low on resource: ephemeral-storage

### DISCUSSION THREAD

**Discussion by jubingc** [milvus-io/milvus#40153] [Q&A and General discussion] [answered]
Few query pods and a mixcoord pod reported "The node was low on resource: ephemeral-storage" even though an S3 bucket is used as external storage.

What could consume the disk space, logs, cache? Should I put a limit on `resources.ephemeral-storage` of the deployment? If yes, how much is recommended?

**Comment by yhmo** [comment]
Only datanode and index can persist data into S3.

Query node only reads data from S3, and never writes data to S3. Query node could download data to local disk for "cache" or "mmap", according to the queryNode.cache and queryNode.mmap configurations, by default the mmap disk usage should be less than 50%:
https://github.com/milvus-io/milvus/blob/36a4fada02915d2c773737e1fd4fe6c6d32edb74/configs/milvus.yaml#L420
https://github.com/milvus-io/milvus/blob/36a4fada02915d2c773737e1fd4fe6c6d32edb74/configs/milvus.yaml#L430

Logs could be output to local disk if the log.file.rootPath is set to a valid path, the max size is limited by the configurations, by default no more than 3GB:
https://github.com/milvus-io/milvus/blob/36a4fada02915d2c773737e1fd4fe6c6d32edb74/configs/milvus.yaml#L758

You can check the disk usage of path "/var/lib/milvus/data/" inside the querynode.
How much disk space is available for the query node? I think you'd better assign at least 20GB ~ 30GB disk space to each query node.

The sizing tool can help you estimate resource requirement for each node: https://milvus.io/tools/sizing
For example, if the mmap is enabled, click the "With Scalar Fields" button, you can see the disk usage is estimated:
![Screenshot from 2025-02-25 11-23-07](https://github.com/user-attachments/assets/9e03983b-4cb6-455d-8522-a88afa07ccea)

**Reply by jubingc** [reply]
Thanks for sharing this. It would be very helpful when I need mmap in the future. Now it is more interesting because mmap is not enabled:
```
du -hs /var/lib/milvus/data/
0	/var/lib/milvus/data/
```

`log.file.rootPath` is empty. The logs are expected to ship to stdout and should not be persistent locally.

The event shows the query node was using 44GiB. What else could require much disk space?
```
  Warning  Evicted    4m22s                   kubelet            The node was low on resource: ephemeral-storage. Threshold quantity: 2683724430, available: 32400Ki. Container querynode was using 44721492Ki, request is 0, has larger consumption of ephemeral-storage.
```

Is there a way to tell how much disk space is used by the query node? The overlay file system is shared by several running pods. The output below is copied from a healthy query node pod, not the one that got evicted due to insufficient disk space.
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          50G   12G   39G  23% /
tmpfs            64M     0   64M   0% /dev
tmpfs           124G     0  124G   0% /sys/fs/cgroup
/dev/nvme0n1p1   50G   12G   39G  23% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            64G   12K   64G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            64G  4.0K   64G   1% /run/secrets/eks.amazonaws.com/serviceaccount
tmpfs           124G     0  124G   0% /proc/acpi
tmpfs           124G     0  124G   0% /sys/firmware
```

**Reply by bigsheeper** [reply]
@jubingc Could you please provide the following details to help us better understand the issue?
1. Milvus version you are using
2. Collection schema
3. Index type and parameters
4. Output fields specified in the query/search

**Reply by yhmo** [reply]
@jubingc 
By default, the queryNode.mmap.chunkCache is true, did you change it to false?
```
queryNode:
  cache:
    memoryLimit: 2147483648 # 2 GB, 2 * 1024 *1024 *1024
    readAheadPolicy: willneed # The read ahead policy of chunk cache, options: `normal, random, sequential, willneed, dontneed`
    # options: async, sync, disable. 
    # Specifies the necessity for warming up the chunk cache. 
    # 1. If set to "sync" or "async" the original vector data will be synchronously/asynchronously loaded into the 
    # chunk cache during the load process. This approach has the potential to substantially reduce query/search latency
    # for a specific duration post-load, albeit accompanied by a concurrent increase in disk usage;
    # 2. If set to "disable" original vector data will only be loaded into the chunk cache during search/query.
    warmup: disable
  mmap:
    vectorField: false # Enable mmap for loading vector data
    vectorIndex: false # Enable mmap for loading vector index
    scalarField: false # Enable mmap for loading scalar data
    scalarIndex: false # Enable mmap for loading scalar index
    chunkCache: true # Enable mmap for chunk cache (raw vector retrieving).
    # Enable memory mapping (mmap) to optimize the handling of growing raw data. 
    # By activating this feature, the memory overhead associated with newly added or modified data will be significantly minimized. 
    # However, this optimization may come at the cost of a slight decrease in query latency for the affected data segments.
    growingMmapEnabled: false
    fixedFileSizeForMmapAlloc: 1 # tmp file size for mmap chunk manager
    maxDiskUsagePercentageForMmapAlloc: 50 # disk percentage used in mmap chunk manager
```
