### DISCUSSION TITLE
Your cluster is experiencing issues: Milvus WebUI: metastore [etcd] some members are unavailable

### DISCUSSION THREAD

**Discussion by amzker** [milvus-io/milvus#40185] [Q&A and General discussion]
![image](https://github.com/user-attachments/assets/6faad91f-1a80-4a37-a7d4-55a6be5b5665)

![image](https://github.com/user-attachments/assets/71efa61c-e1cd-4b10-99e8-2c2fb6b0d9d8)

![image](https://github.com/user-attachments/assets/cc3debff-84ca-4998-a8b5-01cfd27bb966)

error: `metastore [etcd]	 some members are unavailable 	      Endpoint:http://127.0.0.1:2379Health:Unhealthy`

docker-compose.yaml
```yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.16
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.4
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - /home/ubuntu/milvus_backup/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

this is milvus standalone and whenever i upgrade milvus i do docker compose down and then get new docker yaml and docker compose up while keeping volume directory same 

also there are sudden spikes happening and cpu usage is also high

![image](https://github.com/user-attachments/assets/ef669671-36c6-4072-b9c8-bca0e9e9dd72)

![image](https://github.com/user-attachments/assets/3b18502c-67b6-465f-ad94-f5e899b965f9)

also i noticed , it is showing dropped segments as well , how do i remove them if they can be removed
