### DISCUSSION TITLE
Questions about mmap

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#40279] [Q&A and General discussion]
- milvus version: v2.4.20
- milvus mode: cluster
- reference: https://milvus.io/docs/v2.4.x/mmap.md

---

Q1:
In a situation where data is continuously streaming in and the size keeps growing, is it recommended to pre-activate mmap in advance, or is it better to monitor the situation and activate it only when needed?

Q2:
```python
# Get existing collection
collection = Collection("test_collection") # Replace with your collection name

# Set memory mapping property to True or Flase
collection.set_properties({'mmap.enabled': True})
```
When executing the above code, does it apply to all raw data, including the vector field, except for pk and timestamp?

Q3:
> After 2.4.10, the memory mapping settings within a collection, utilize the add_field method. Here, you can toggle mmap_enabled between True or False as needed.

The content mentioned above can be applied when creating a new collection, but is it not applicable to an already operational collection?

Q4:

```yaml
# This parameter was set in configs/milvus.yaml
...
queryNode:
  mmap:
    vectorField: false # Enable mmap for loading vector data
    vectorIndex: false # Enable mmap for loading vector index
    scalarField: false # Enable mmap for loading scalar data
    scalarIndex: false # Enable mmap for loading scalar index
....
```

> Can scalar data be memory-mapped?
Memory mapping can be applied to scalar data, but it is not applicable to indexes built on scalar fields.

The two statements seem contradictory. Does mmap also apply to the scalar index?

---
