### DISCUSSION TITLE
pulsar retention policy

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#40578] [Q&A and General discussion] [answered]
It seems that the Pulsar retention policy is not being applied in the Helm chart.
When inserting a large amount of data, the PVC volume keeps increasing and does not decrease. Upon checking, it appears that the following configurations specified in the Milvus Helm chart are not being applied:

```yaml
defaultRetentionTimeInMinutes: "10080"
defaultRetentionSizeInMB: "-1"
backlogQuotaDefaultLimitGB: "8"
ttlDurationDefaultInSeconds: "259200"
subscriptionExpirationTimeMinutes: "3"
backlogQuotaDefaultRetentionPolicy: producer_exception
```
According to [this issue](https://github.com/apache/pulsar/issues/22226), this appears to be a known issue in Apache Pulsar itself.
For now, I have applied the following commands as a workaround based on the official [Pulsar documentation](https://pulsar.apache.org/docs/3.0.x/cookbooks-retention-expiry/):

```bash
pulsar-admin namespaces set-retention public/default \
  --time 7d \
  --size -1

pulsar-admin namespaces set-backlog-quota public/default \
  --limit 8G \
  --policy producer_exception

pulsar-admin namespaces set-message-ttl public/default \
  --messageTTL 259200
```

Would it be possible to resolve this issue?
