### DISCUSSION TITLE
Milvus not honoring the logging configurations

### DISCUSSION THREAD

**Discussion by waqqas-vectara** [milvus-io/milvus#40582] [Q&A and General discussion]
Hi all,
I want to configure "warning" level in "json" format in my deployment. Milvus is outputting debug level logs.

My `user.yaml` is as follows
```
queryNode:
  enableDisk: true
  mmap:
    vectorField: true
    vectorIndex: true
    scalarField: true
    scalarIndex: true
indexNode:
  enableDisk: true
log:
  level: warn
  format: json
  ```
  
`default.yaml` is as follows
  
  ```
log:
  level: warn
  file:
    rootPath: ""
    maxSize: 300
    maxAge: 10
    maxBackups: 20
  format: json
```
  
and `milvus.yaml` is as follows
```
log:
  # Milvus log level. Option: debug, info, warn, error, panic, and fatal. 
  # It is recommended to use debug level under test and development environments, and info level in production environment.
  level: info
  file:
    # Root path to the log files.
    # The default value is set empty, indicating to output log files to standard output (stdout) and standard error (stderr).
    # If this parameter is set to a valid local path, Milvus writes and stores log files in this path.
    # Set this parameter as the path that you have permission to write.
    rootPath: 
    maxSize: 300 # The maximum size of a log file, unit: MB.
    maxAge: 10 # The maximum retention time before a log file is automatically cleared, unit: day. The minimum value is 1.
    maxBackups: 20 # The maximum number of log files to back up, unit: day. The minimum value is 1.
  format: text # Milvus log format. Option: text and JSON
  stdout: true # Stdout enable or not
```
  
I also configured `glog.conf` as follows
```
# `INFO``, ``WARNING``, ``ERROR``, and ``FATAL`` are 0, 1, 2, and 3
 --minloglevel=1
```
  
  Some related questions:
  1. If there are multiple configuration files, which file is actually read? If multiple files are read, what is the sequence? i.e. which file's configuration overrides which one?
  2. Is `/milvus/configs/` the correct location of the these config files?
  3. How can I configure the helm charts to provide the desired configuration?
  
  Thanks in advance
  Waqqas
