### DISCUSSION TITLE
helm文件中在QN节点上启用了mmap参数，为何从webui中看mmap的属性都是false的？

### DISCUSSION THREAD

**Discussion by midonKing** [milvus-io/milvus#40693] [Q&A and General discussion]
我用helm部署了一个2.5.6版本的milvus，在QN节点上，我配置了mmap参数，配置信息如下：
![image](https://github.com/user-attachments/assets/90b7e59f-fcef-43f8-9373-32d5f9464f53)
在集群部署完成后，我用webui检查了一下milvus的集群属性，但mmap属性似乎没有启用：
![image](https://github.com/user-attachments/assets/459e919b-2d3d-441f-8711-741e43144033)
![image](https://github.com/user-attachments/assets/5434999a-4d40-4d55-9db5-dff8d3fabd57)
请问这是为什么？

**Comment by yhmo** [comment]
多半是milvus.yaml没映射正确。
设置正确的情况下，显示的东西是跟配置一致的：
![Screenshot from 2025-03-17 16-38-28](https://github.com/user-attachments/assets/7b0903c8-a1f3-422e-8e0f-904c67b5ce62)
进入容器查看 /milvus/configs/milvus.yaml就能看到它真正使用的配置：
![Screenshot from 2025-03-17 16-39-34](https://github.com/user-attachments/assets/165136ed-dee3-4322-8a72-8a78e42ce09e)
在milvus.yaml映射正确的条件下，容器里的/milvus/configs/milvus.yaml内容跟WebUI上看到的是一致的。

**Reply by midonKing** [reply]
感谢回复！我这边检查了下，pod内部的参数确实有问题，但这个映射问题是如何造成的呢？或者我应该怎么去排查这个映射问题？
![image](https://github.com/user-attachments/assets/a80bc314-9e3a-4223-abb0-8aac71d9be01)

**Reply by yhmo** [reply]
milvus-helm configuration: https://milvus.io/docs/configure-helm.md?tab=component

在value.yaml里设置配置项：
```
extraConfigFiles:
  user.yaml: |+
    queryNode:
      mmap:
        vectorField: true
        vectorIndex: true
        scalarField: true
        scalarIndex: true
        chunkCache: true
```
然后helm upgrade
