### DISCUSSION TITLE
关于mmap开启的提问

### DISCUSSION THREAD

**Discussion by IeohMingChan** [milvus-io/milvus#40835] [Q&A and General discussion] [answered]
在官网中显示，关于mmap的配置包括集合，字段和索引三个方面，请问集合和字段的mmap设置是否有相互影响或优先级？比如说开启集合mmap即表示标量和向量字段均开启mmap？而开启集合mmap后只关闭某个字段的mmap即表示除了该字段关闭mmap外其他字段均开启？或者说集合mmap和字段mmap完全无关？
另外，我们的数据结构下图所示，请问建议开启哪些字段以及哪些索引的mmap？
![image](https://github.com/user-attachments/assets/8d232884-df8f-4998-ba8c-5c578a3b11e0)
![image](https://github.com/user-attachments/assets/2fd8c1a4-52eb-416a-bf03-dec988f2c66c)

**Comment by yhmo** [comment]
milvus.yaml中的配置是对整个库有效，但优先级最低
```
queryNode:
  mmap:
    vectorField: false # Enable mmap for loading vector data
    vectorIndex: false # Enable mmap for loading vector index
    scalarField: false # Enable mmap for loading scalar data
    scalarIndex: false # Enable mmap for loading scalar index
```

collection的mmap只对该表有效，高于milvus.yaml的优先级
`collection.set_properties({'mmap.enabled': True})`

field的mmap只对该字段有效，高于collection的优先级
`schema.add_field(field_name="embedding", datatype=DataType.FLOAT_VECTOR, dim=768, mmap_enabled=True)`

索引的mmap只对该索引有效，高于collection的优先级
```
collection.alter_index(
    index_name="vector_index", # Replace with your vector index name
    extra_params={"mmap.enabled": True} # Enable memory mapping for index
)
```

关于mmap的文档后面会更新，更详细的描述
