### DISCUSSION TITLE
单机milvus-2.5.1启动，数据盘7.1G，内存空闲59G，还是启动不起来，需要这么大内存麽，我用另外一个就1个G的数据就能启动

### DISCUSSION THREAD

**Discussion by jhyever** [milvus-io/milvus#41273] [Q&A and General discussion]
@yhmo 麻烦大佬帮忙看下，感谢
![img_v3_02lb_886ad473-85ec-4c1b-b88f-488c404f4fnh](https://github.com/user-attachments/assets/5d9b16ac-61a3-46c9-9751-71b5e667a291)
![image](https://github.com/user-attachments/assets/8dd644a2-b18d-480d-9c82-960513f2d429)

**Comment by yhmo** [comment]
跟内存没关系，etcd的硬盘空间不够了。
volumes/milvus下面的三个文件夹 etcd, milvus, minio分别占了多少硬盘空间？

**Reply by jhyever** [reply]
分别占用如下
![image](https://github.com/user-attachments/assets/4eb9d142-0ee4-4197-aff2-8e120fe5e2f4)

**Reply by xiaofan-luan** [reply]
> 分别占用如下 ![image](https://private-user-images.githubusercontent.com/88376429/433293960-4eb9d142-0ee4-4197-aff2-8e120fe5e2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2NDgzNjksIm5iZiI6MTc0NDY0ODA2OSwicGF0aCI6Ii84ODM3NjQyOS80MzMyOTM5NjAtNGViOWQxNDItMGVlNC00MTk3LWFmZjItOGUxMjBmZTVlMmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDE2Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYzEyOTg0ODk2YWFmY2IxNTgwYWU1N2JiODM4OWY3YTc1MDJmYzRiZmEyNGM4OTM2MjVhZmQ4NjkxZTRiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ahWuztQE3ytgGgWYf-_bHfoDMGPhw1opXM8-pMuGsgg)

数据盘写满了，你需要增加数据盘，内存100G的话，磁盘至少给200G以上

**Comment by yhmo** [comment]
正常的docker-compose.yaml里etcd容器的配置有这几项，检查你的docker-compose.yaml是否有这几项，如果删掉了就加回来吧。
```
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    ......
```

相似问题：
https://github.com/milvus-io/milvus/issues/36748
https://github.com/milvus-io/milvus/issues/18763
