### DISCUSSION TITLE
milvus connection failure after onboarding to service mesh / envoy

### DISCUSSION THREAD

**Discussion by eyang-2** [milvus-io/milvus#41334] [Q&A and General discussion]
saw this error `upstream connect error or disconnect/reset before headers. reset reason: connection failure` after trying to hit 9091 - all request timed out with the error message

however if i do port forward everything works but port forward is not the ideal way.

this is my milvus proxy config, has anyone seen this problem before?

```
  proxy:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "4000m"
        memory: "8Gi"
      limits:
        cpu: "4000m"
        memory: "8Gi"
```
