### DISCUSSION TITLE
High Latency on ANN Search, both for Single Vector Search and Hybrid Vector Search.

### DISCUSSION THREAD

**Discussion by rohitreddy1698** [milvus-io/milvus#41461] [Q&A and General discussion]
Hi,

I am trying to benchmark the query latencies on Milvus with different vector search scenarios.

Collection Size : 200 Million
Number of vector fields : 10
Indexes Built : HNSW with ( m = 32 , efCons = 128 ) , 
Search Params : ( efSearch = 32  , metric : "L2")
Vector Dimension : 1024

We initially started with Query Node : number - 52 , vCPU - 48 and memory - 230 GiB, and saw high latencies. 
So we scaled up to the resources as follows :
Query Node configuration :

```
queryCoord:
      env:
      - name: QUERY_COORD_ENABLE_ACTIVE_STANDBY
        value: "true"
      paused: false
      probes: null
      replicas: 2
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
    queryNode:
      paused: false
      probes: null
      replicas: 64
      resources:
        limits:
          cpu: "56"
          memory: 236Gi
```

Case 1 - Single Vector search on one of the vector fields : 
`{ 'ef': 32, 'concurrency': 100, 'mean_latency_ms': 264.34, 'p95_latency_ms': 332.53, 'p99_latency_ms': 398.08 }`

Case 2 - Hybrid Search with 5 vector fields : 
`{ 'ef': 32, 'concurrency': 100, 'mean_latency_ms': 1228.68, 'p95_latency_ms': 1404.41, 'p99_latency_ms': 1468.61 }`

Case 3 - Hybrid Search with 10 vector fields : 
`{ 'ef': 32, 'concurrency': 100, 'mean_latency_ms': 2002.01, 'p95_latency_ms': 2374.47, 'p99_latency_ms': 2543.6 }`

Case 4 - Single Vector Search with Filter : 
`{ 'ef': 32, 'concurrency': 100, 'mean_latency_ms': 326.41, 'p95_latency_ms': 434.51, 'p99_latency_ms': 466.73 }`

Case 5 - Hybrid Search with 10 vector fields + Filter : 
`{ 'ef': 32, 'concurrency': 100, 'mean_latency_ms': 2003.5, 'p95_latency_ms': 2379.47, 'p99_latency_ms': 2530.59 }`

Queries were run with 100 worker threads using following code :
```
def run_parallel(fn, args, concurrency):
    results = []
    for i in range(0, len(args), concurrency):
        batch = args[i:i + concurrency]
        with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
            futures = [executor.submit(fn, *arg) for arg in batch]
            results += [f.result() for f in concurrent.futures.as_completed(futures)]
    return results

```
Milvus Version in Use : v2.5.2.

Thanks,
Rohit
