### DISCUSSION TITLE
Load collection fail after scaling query nodes

### DISCUSSION THREAD

**Discussion by duc-pa-vn** [milvus-io/milvus#41492] [Q&A and General discussion]
Hello, I am using Milvus 2.5 in distributed mode with this setup
```
mixCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "8"
      memory: 32Gi
proxy:
  replicas: 1
  resources:
    limits:
      cpu: 8
      memory: 16Gi
indexNode:
  replicas: 1
  resources:
    limits:
      cpu: 4
      memory: 16Gi
queryNode:
  replicas: 7
  resources:
    limits:
      cpu: 10
      memory: 40Gi
etcd:
  autoCompactionMode: revision
  autoCompactionRetention: "1000"
  extraEnvVars:
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "4294967296"
  - name: ETCD_HEARTBEAT_INTERVAL
    value: "500"
  - name: ETCD_ELECTION_TIMEOUT
    value: "25000"
  - name: ETCD_SNAPSHOT_COUNT
    value: "10000"
  - name: ETCD_ENABLE_PPROF
    value: "true"
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 20Gi  #SSD Required
    storageClass:
  replicaCount: 3
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi

pulsar:
  enabled: false
kafka:
  enabled: true
  persistence:
    enabled: true
    storageClass:
    accessMode: ReadWriteOnce
    size: 300Gi
  resources:
    limits:
      cpu: 2
      memory: 8Gi
  zookeeper:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 30Gi   #SSD Required
    resources:
      limits:
        cpu: 0.5
        memory: 2Gi

minio:
  resources:
    limits:
      cpu: 1
      memory: 8Gi
  persistence:
    storageClass:
    accessMode: ReadWriteOnce
    size: 500Gi
```
It can load collection normally.

Issue:
After increasing the querynode replica to 10 and start loading collection, it stuck at 0% for a while and then back to unloaded.
Below is mixcoord log after loading collection fail:
`[2025/04/24 04:33:05.384 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=240]

[2025/04/24 04:33:05.888 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=360]

[2025/04/24 04:33:06.335 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=446]

[2025/04/24 04:33:06.638 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=303]

[2025/04/24 04:33:07.125 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=290]

[2025/04/24 04:33:07.693 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=567]

[2025/04/24 04:33:08.173 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=479]

[2025/04/24 04:33:08.315 +00:00] [WARN] [datacoord/metrics_info.go:74] ["failed to describe index, ignore to report index metrics"] 

[traceID=bb901e0d2dfdcb1d73fc9cde0b52a764] [collection=457111408218189869] [error="index not found[indexName=]"]

[2025/04/24 04:33:08.513 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=339]

[2025/04/24 04:33:09.019 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=506]
[2025/04/24 04:33:09.820 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=800]
[2025/04/24 04:33:10.417 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=597]
[2025/04/24 04:33:10.758 +00:00] [WARN] [rootcoord/timeticksync.go:314] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=340]`
Anyone face this before?
