### DISCUSSION TITLE
Generic Questions on GPU Indexing Speed

### DISCUSSION THREAD

**Discussion by 0-EricZhou-0** [milvus-io/milvus#41721] [Q&A and General discussion]
## GPU Indexing

In Milvus v2.5.x documentation [GPU Index](https://milvus.io/docs/gpu_index.md#:~:text=GPU%20Index-,GPU%20Index,-Milvus%20supports%20various), it shows that GPUs can help increase the throughput of indexing. However, I did some experiments on my local setup, and the indexing speed for the GPU algorithms seems to be almost the same as the CPU ones.

## Server Configuration

The server I used has the following configuration:
- CPU: Dual-socket AMD EPYC 9334 32-Core Processor.
- Memory: 1.48TB
- GPU: Two NVIDIA H100 NVL

## Milvus Setup

The Milvus we used is version 2.5.9, with setup following the documents [here](https://milvus.io/docs/install_standalone-docker-compose-gpu.md#:~:text=Docker%20Compose-,Run%20Milvus%20with%20GPU%20Support%20Using%20Docker%20Compose,-This%20page%20illustrates).

## Workload Description

The dataset we used contains around 28.5M entries, we only inserted the embeddings along with the unique ID into the database.

## Experiment Process

Using the `pymilvus` interface, we created 32000 requests in total beforehand, performing vector search by using 32 threads to send requests in parallel. We batch 100 searches in each of the requests.

### Basic Tests with one GPU

The following experiments are done with one of the H100 used and it seems that the GPU indexing does not accelerate the query speed much.
![image](https://github.com/user-attachments/assets/d9d1de74-16cf-465f-a24c-698debeeda16)

### Increasing vector dimension (still one GPU used)

We observed that the GPU occupation is quite low and thought that it might be because there is not enough computation compared to graph searching, so we proceeded to conduct the experiment with larger vector dimensions and limited the number of CPU cores. We limit the number of cores that can be used by the `standalone` service to 32 by changing the following fields in `docker-compose.yml`.

```yaml
services:
  standalone:
    deploy:
      resources:
        ...
        limits:         # added
          cpus: "32.0"  # added
```

The results are as follows:
![image](https://github.com/user-attachments/assets/3a794f44-1001-4590-a866-d0ce48caf8e2)

### Increasing the number of GPUs used

We also tried to use multiple GPUs, but it seems like the performance is almost the same (even a little bit slower) with multiple GPUs. In the docker setup, we changed the following field in `docker-compose.yml`

```yaml
services:
  standalone:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["GPU"]
              device_ids: ["0", "1"] # was device_ids: ["1"]
```

The results are as follows:
![image](https://github.com/user-attachments/assets/6ce5bff5-c30e-4deb-abe1-6a2a66180d85)

## Questions

1. It seems that the GPU is not helping much on indexing speed, is there anything that I wrongly configured?
2. Why increasing the number of GPUs that can be used does not increases query throughput? Are there any knobs we need to tune in order for the performance to be better?
