### DISCUSSION TITLE
external kafka配置问题，如何让多个milvus集群共用一个kafka？

### DISCUSSION THREAD

**Discussion by yangyangdy** [milvus-io/milvus#41785] [Q&A and General discussion]
下面是milvus中采用外部kafka服务的配置：
###################################
# External kafka
# - these configs are only used when `externalKafka.enabled` is true
# - note that the following are just examples, you should confirm the
#   value of brokerList and mechanisms according to the actual external
#   Kafka configuration. E.g. If you select the AWS MSK, the configuration
#   should look something like this:
#   externalKafka:
#     enabled: true
#     brokerList: "xxxx:9096"
#     securityProtocol: SASL_SSL
#     sasl:
#       mechanisms: SCRAM-SHA-512
#       password: "xxx"
#       username: "xxx"
###################################
externalKafka:
  enabled: false
  brokerList: localhost:9092
  securityProtocol: SASL_SSL
  sasl:
    mechanisms: PLAIN
    username: ""
    password: ""

如果我有三个milvus集群m1,m2,m3，希望共用一个kafka服务，在上面的配置中应该添加什么参数来满足要求？（我理解这块是多个milvus可能创建相同的topic引发冲突的问题）

**Comment by yhmo** [comment]
确认了，用这个配置项改：
https://github.com/milvus-io/milvus/blob/f094d026f80f5efb7d8291ac23738e94d4ccd1f7/configs/milvus.yaml#L759

```
msgChannel:
  chanNamePrefix:
    # Root name prefix of the channel when a message channel is created.
    # It is recommended to change this parameter before starting Milvus for the first time.
    # To share a Pulsar instance among multiple Milvus instances, consider changing this to a name rather than the default one for each Milvus instance before you start them.
    cluster: by-dev
```
把三个集群的 msgChannel.chanNamePrefix.cluster 这项改成不同的名字，它们就会创建不同的topic，相互只间不会干扰。
