### DISCUSSION TITLE
how to setup GCP bucket storage in milvus standalone?

### DISCUSSION THREAD

**Discussion by AashishChapain** [milvus-io/milvus#41832] [Q&A and General discussion]
i have modified milvus.yaml file:
```bash
minio:
  address: storage.googleapis.com
  port: 443
  useSSL: true
  cloudProvider: "gcp"
  bucketName: "my-milvus-bucket"
  rootPath: "milvus-files"  

  accessKeyID: "GCS-ACCESS-KEY>"
  secretAccessKey: "GCS-SECRET-KEY>"
```
docker containers are up and running. i tried to store the embeddings but the embeddings are only stored in volumes created by the docker-compose file, bucket is empty in google storage.

Docker-compose:
```bash
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.11
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      MINIO_REGION: us-east-1
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
can anyone tells me what's going on and what should i do?

**Comment by yhmo** [comment]
In milvus container, there is a default configuration file named **milvus.yaml** under the path **/milvus/configs/milvus.yaml**
So, to change milvus configurations, you can map the path to outside the container.
For example, I add one line under the "volumes", mapping the internal file **/milvus/configs/milvus.yaml** to path **${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml** outside of the container 
Note:  the **${DOCKER_VOLUME_DIRECTORY** is the path where you place the docker-compose.yaml.

```
  etcd:
    ......
  minio:
    ......
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.11
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    ......
```

You can download the milvus.yaml by this command:
```
wget https://raw.githubusercontent.com/milvus-io/milvus/v2.5.11/configs/milvus.yaml
```

Edit the file **${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml** with a text tool.
Edit the "minio" section, set address/port/accesskey/secretkey/bucketname/rootpath, and set "cloudProvider" to be "gcp".
```
minio:
  address: storage.googleapis.com
  port: 443
  
  accessKeyID: <access-key>
  secretAccessKey: <secret-key>

  useSSL: false # Switch value to control if to access the MinIO or S3 service through SSL.
  ssl:
    tlsCACert: /path/to/public.crt # path to your CACert file
  
  bucketName: a-bucket
  
  rootPath: files
  
  useIAM: false
  
  cloudProvider: gcp
  
  iamEndpoint: 
  logLevel: fatal # Log level for aws sdk log. Supported level:  off, fatal, error, warn, info, debug, trace
  region:  # Specify minio storage system location region
  useVirtualHost: false # Whether use virtual host mode for bucket
  requestTimeoutMs: 10000 # minio timeout for request time in milliseconds
  listObjectsMaxKeys: 0
```

Finally, use "docker compose up -d" to launch the milvus server.


This doc is about how to configure milvus standalone:
https://milvus.io/docs/configure-docker.md?tab=component#Configure-Milvus-with-Docker-Compose
