### DISCUSSION TITLE
GPU not being used, after enabling gpu=true and index being created

### DISCUSSION THREAD

**Discussion by shashi-netra** [milvus-io/milvus#4184] [Q&A and General discussion] [answered]
Installed Milvus on Ubuntu 18, GE Force GTX 1080 `NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2`
and created an index of ~10MM vectors of dimensionality 512. 

When I run a query it seems to use CPUs only and the GPU is dead quiet (verified using `nvidia-smi-l1`)

I also have **enable: true** (below). So not sure what I am doing wrong.

```
gpu:
  enable: true
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

```
