### DISCUSSION TITLE
Vector index of the growing segment

### DISCUSSION THREAD

**Discussion by YolandaLyj** [milvus-io/milvus#41890] [Q&A and General discussion]
Discussion (https://github.com/milvus-io/milvus/discussions/40652) states that IVF or SCANN indexes are used in the growing segment. Why not choose other indexes, such as HNSW, IVF_PQ, etc.

**Comment by yhmo** [comment]
The index for the growing segments is configured in the milvus.yaml:
https://github.com/milvus-io/milvus/blob/d3fff1769e51aff61c00681519ac3dd03ed95b23/configs/milvus.yaml#L422
```
queryNode:
  segcore:
    knowhereThreadPoolNumRatio: 4 # The number of threads in knowhere's thread pool. If disk is enabled, the pool size will multiply with knowhereThreadPoolNumRatio([1, 32]).
    chunkRows: 128 # Row count by which Segcore divides a segment into chunks.
    interimIndex:
      # Whether to create a temporary index for growing segments and sealed segments not yet indexed, improving search performance.
      # Milvus will eventually seals and indexes all segments, but enabling this optimizes search performance for immediate queries following data insertion.
      # This defaults to true, indicating that Milvus creates temporary index for growing segments and the sealed segments that are not indexed upon searches.
      enableIndex: true
      nlist: 128 # temp index nlist, recommend to set sqrt(chunkRows), must smaller than chunkRows/8
      nprobe: 16 # nprobe to search small index, based on your accuracy requirement, must smaller than nlist
```

In milvus, it is an IVF_FLAT index. In zilliz cloud, it could be an SCANN index. SCANN is similar to IVF_PQ.
The reason we choose IVF/SCANN is: lower CPU usage and memory usage, fast append.
Usually, a growing segment size is no more than 100+ MB. Especially in the partition-key case, each growing segment size may be a few MB, and there are hundreds/thousands of growing segments in memory. It builds clusters of IVF index once the row count of a growing segment exceeds 5000 rows. Once the clusters are built, the time/memory cost to insert a new vector is cheaper than HNSW.
