### DISCUSSION TITLE
Number Limit of values in the IN operator?

### DISCUSSION THREAD

**Discussion by wangheehgnaw** [milvus-io/milvus#41964] [Q&A and General discussion]
For a filtering query, is there a number limit of values in the IN operator? If it is too large (for example, more than 1000), will it have a significant impact on query performance?

**Comment by yhmo** [comment]
It is mainly limited by rpc transfer limitation. The max size of each request is configured by milvus.yaml:
```
proxy:
  grpc:
    serverMaxSendSize: 268435456 # The maximum size of each RPC request that the proxy can send, unit: byte
    serverMaxRecvSize: 67108864 # The maximum size of each RPC request that the proxy can receive, unit: byte
```
By default, the maximum size of each rpc request received by milvus proxy is 64MB. So, the length of the filter expression cannot exceed this value. The maximum size of each rpc response that the proxy can send is 256MB, you will get an error of query() if the returned result size exceeds this value.

Since more values in the IN operator will return more results(1000 values will return 1000 items, 10000 values will return 10000 items), the more items returned, the worse query performance.
