### DISCUSSION TITLE
milvus容器日志一直在增加，这个能限制麽，版本是2.5.1，启动方式是standalone模式

### DISCUSSION THREAD

**Discussion by jhyever** [milvus-io/milvus#42170] [Q&A and General discussion]
@yhmo  您好，这个能麻烦帮忙看下嘛
![image](https://github.com/user-attachments/assets/da818518-853e-4061-a31e-c63172987107)

**Comment by yhmo** [comment]
修改milvus.yaml里这项：
https://github.com/milvus-io/milvus/blob/3a74044149cd1801a5e7c64d2d512c5a2584b46e/configs/milvus.yaml#L813
注意是最外层的"log"，不是"etcd.log"
把stdout设为false，给rootPath设置一个路径，然后把这个路径通过docker compose的volumes映射到容器外面
```
# Configures the system log output.
log:
  level: info
  file:
    rootPath: /var/lib/milvus/log
    maxSize: 300 # The maximum size of a log file, unit: MB.
    maxAge: 10 # The maximum retention time before a log file is automatically cleared, unit: day. The minimum value is 1.
    maxBackups: 20 # The maximum number of log files to back up, unit: day. The minimum value is 1.
  format: text # Milvus log format. Option: text and JSON
  stdout: false
```
