### DISCUSSION TITLE
Sometimes Query latency was high. How to solve it?

### DISCUSSION THREAD

**Discussion by hjlee9182** [milvus-io/milvus#42418] [Q&A and General discussion]
Do you know how to improve it in this situation? Regarding a separate collection, the query splatters when the writing comes in, so I checked it with otlp and the query segments splatter like below. How can I improve this part?

<img width="773" alt="image" src="https://github.com/user-attachments/assets/611c6d97-6045-44f4-8a4c-20b9dcfe19ea" />

**Comment by yhmo** [comment]
Standalone or cluster? Which milvus version?
How many rows in the collection?
Which "consistency_level" is assigned?
How many rows are inserted per second?

**Reply by hjlee9182** [reply]
Milvus ver. 2.5.4-gpu

Cluster, Querynode 12 replica, cpu:48, mem:96

The collection receiving both queries and searches is around 16 million with IVF_SQ8 index.

We configured it to use eventual consistency when issuing get or search requests.

We’re using 10 executors, each inserting 2,000 records at a time with a 0.15-second sleep in between.
We first create and load the collection, and then start inserting data.
The collection we're inserting into is around 6 million in size.
Note that the collection used for insertions is different from the one receiving query and search requests.


```
queryNode:
          replicas: 12
          resources:
            requests:
              cpu: "48"
              memory: 96Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "48"
              memory: 96Gi
              nvidia.com/gpu: "1"
          env:
            - name: GOMAXPROCS
              value: "10"
....

queryNode:
          scheduler:
            maxReadConcurrentRatio: 2
          segcore:
            knowhereThreadPoolNumRatio: 8
            interimIndex:
              enableIndex: false
          cache:
            warmup: async
          enableDisk: false
          memoryLimit: 8589934592 # 8GB
          dataSync:
            flowGraph:
              maxParallelism: 32

```
