### DISCUSSION TITLE
关于milvus的配置问题

### DISCUSSION THREAD

**Discussion by AriesJin** [milvus-io/milvus#42493] [Q&A and General discussion]
我目前是通过3 台物理机通过 k8s 部署，每台物理机的内存是256G，存储时1T，但是我存储了700w数据就显示内存不足，向量维度时1536，存储的方式IVF_SQ8，按理说完全不应该呀，毕竟700w*1536*4*25%=10G左右。我是不是应该datanode来提高存储的数据量，这是我的配置信息
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-db
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    image: milvusdb/milvus:v2.3.5
    dataCoord:
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
    queryCoord:
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
    rootCoord:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 2Gi
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: 2
          memory: 8Gi
        requests:
          cpu: 1
          memory: 4Gi
    indexNode:
      replicas: 2
      resources:
        limits:
          cpu: 8
          memory: 16Gi
    queryNode:
      replicas: 1
      resources:
        limits:
          cpu: 4
          memory: 16Gi
        requests:
          cpu: 2
          memory: 8Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 1Gi
  config: {}
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi   #SSD Required
            storageClass:
          replicaCount: 3
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi

    msgStreamType: kafka
    kafka:
      inCluster:
        values:
          heapOpts: "-Xmx8192M -Xms8192M"
          persistence:
            enabled: true
            storageClass:
            accessMode: ReadWriteOnce
            size: 120Gi
          resources:
            limits:
              cpu: 1
              memory: 25Gi
          zookeeper:
            enabled: true
            replicaCount: 3
            heapSize: 2048  # zk heap size in MB
            persistence:
              enabled: true
              storageClass: ""
              accessModes:
                - ReadWriteOnce
              size: 20Gi #SSD Required
            resources:
              limits:
                cpu: 1
                memory: 4Gi

    storage:
      inCluster:
        values:
          mode: distributed
          resources:
            limits:
              cpu: 2
              memory: 16Gi
          persistence:
            storageClass:
            accessMode: ReadWriteOnce
            size: 1000Gi
```
