### DISCUSSION TITLE
disable mmap when using DiskANN

### DISCUSSION THREAD

**Discussion by rere950303** [milvus-io/milvus#42536] [Q&A and General discussion] [answered]
- milvus versoin: v2.4.23
- milvus mode: cluster

We are currently applying mmap globally with the following configuration, and using the HNSW indexing algorithm for all collections. 

```yaml
       queryNode:
         mmap:
           vectorField: true # Enable mmap for loading vector data
           vectorIndex: false # Enable mmap for loading vector index
           scalarField: true # Enable mmap for loading scalar data
           scalarIndex: true # Enable mmap for loading scalar index
```

However, we are planning to create a new collection that uses the DiskANN index type, and I have a question about that.

Since DiskANN seems to require mmap to be disabled, can we simply disable mmap for that specific collection only, as shown below?

```python3
# Release collection before changing mmap settings
client.release_collection("my_collection")

# Ensure that the collection has already been released 
# and run the following
client.alter_collection_properties(
    collection_name="my_collection",
    properties={
        "mmap.enabled": False
    }
)

# Load the collection to make the above change take effect
client.load_collection("my_collection")
```

- If we do this, will the collection-level setting take precedence over the global setting, and will mmap be disabled for the raw data and indexes of all fields in the collection. (i.e., vectorField, vectorIndex, scalarField, scalarIndex)?
