### DISCUSSION TITLE
Using External Message Queue (Kafka) simultaneously by two Milvus clusters.

### DISCUSSION THREAD

**Discussion by Wonki4** [milvus-io/milvus#42825] [Q&A and General discussion] [answered]
Can an external Kafka be used simultaneously by two Milvus clusters?

I’m thinking about the milvus cluster architecture to share milvus clusters with my coworker.
I decided to use my managed kafka cluster in milvus cluster.
I avoid that 1 milvus use 1 kafka cluster because i thought that it could be a resource waste. Instead, I want to share kafka cluster in MULTIPLE MILVUS CLUSTER. I’m also worried that the channel topics in multiple clusters could be affected each other.

Could you give me any idea? Or documentation?

**Comment by yhmo** [comment, marked as answer]
Two milvus clusters share a kafka, their topics must be different.
In the milvus.yaml, set different names of **msgChannel.chanNamePrefix.cluster**:

Milvus cluster 1
```
# This topic introduces the message channel-related configurations of Milvus.
msgChannel:
  chanNamePrefix:
    cluster: by-dev-1
```

Milvus cluster 2
```
# This topic introduces the message channel-related configurations of Milvus.
msgChannel:
  chanNamePrefix:
    cluster: by-dev-2
```

**Reply by Wonki4** [reply]
Thank you so much, yhmo!

In helm chart, I can add this option like this.
```
extraConfigFiles:
    user.yaml:
        msgChannel:
          chanNamePrefix:
                 ….
```
