### DISCUSSION TITLE
Is it possible to configure externalS3 with useSSL set to true but not do TLS verification?

### DISCUSSION THREAD

**Discussion by deepankermishra** [milvus-io/milvus#42996] [Q&A and General discussion]
I am trying to bring up Milvus cluster using helm deployment and I am trying to configure an externalS3 endpoint. 

Using:
```
externalS3:
  enabled: true
  host: "<my.ip>"
  port: "<my.port>"
  accessKey: "<my.key>"
  secretKey: "<my.key2>"
  useSSL: true
  bucketName: ""
  rootPath: ""
  useIAM: false
  cloudProvider: ""
  iamEndpoint: ""
  region: ""
  useVirtualHost: false
```
I have my own s3 backend. When I set things up then milvus data node try to connect over https:// but also starts doing TLS verification and fails with:
```
[WARN] [storage/minio_object_storage.go:139] ["failed to check blob bucket exist"] [bucket=gaiaviewfunctest] [error="Get \"https://173.173.26.14:3000/mybucket/?location=\": tls: failed to verify certificate: x509: cannot validate certificate for 173.173.26.14 because it doesn't contain any IP SANs"]
```

I want to disable TLS validation but still connect to an httpS endpoint. How can I do so?
