### DISCUSSION TITLE
data persistence

### DISCUSSION THREAD

**Discussion by xinjiguaike** [milvus-io/milvus#6669] [Q&A and General discussion]
how to keep data persistence after docker restart (docker-compose down && up)
I make the volumes map:

/data/milvus/rocksmq:/var/lib/milvus
/data/milvus/minio:/minio_data
/data/milvus/etcd:/default.etcd

but it seems the etcd keeps the old queryNode ip, 
the milvus-standalone report error as follows:
   ```
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48]["QueryNodeClient try connect "] [address=172.22.0.4:21123]
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{172.22.0.4:21123  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/20 08:48:52.970 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc001af25d0, {CONNECTING <nil>}"]
[2021/07/20 08:48:54.970 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.22.0.4:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.22.0.4:21123: operation was canceled\". Reconnecting..."]
```

**Comment by xiaofan-luan** [comment]
data should be persistent if you use persistent volumn, did you check all the datas for milvus, minio pulsar and etcd exist?

**Reply by xiaofan-luan** [reply]
sorry, not pulsar, the rocks mq. you may want to paste the full error message if possible

**Reply by xinjiguaike** [reply]
I have fired an issue #6686

**Reply by xinjiguaike** [reply]
> data should be persistent if you use persistent volumn, did you check all the datas for milvus, minio pulsar and etcd exist?

I confirmed that the minio data、etcd data、rocksmq data existed definitely, but I'm not sure if my volumes map is enough!

my docker-compose.yml like this:

```
version: "3.5"

services:
    etcd:
        container_name: milvus-etcd
        image: quay.io/coreos/etcd:latest
        command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --listen-metrics-urls=http://127.0.0.1:2381 --initial-cluster default=http://127.0.0.1:2380
        volumes:
            - /data/milvus/etcd:/default.etcd
        logging:
            driver: "json-file"
            options:
                max-size: "300m"
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "-q",
                    "--tries=1",
                    "--spider",
                    "http://localhost:2381/health",
                ]
            interval: 30s
            timeout: 20s
            retries: 3

    minio:
        container_name: milvus-minio
        image: minio/minio:RELEASE.2020-12-03T00-03-10Z
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: minio server /minio_data
        volumes:
            - /data/milvus/minio:/minio_data
        logging:
            driver: "json-file"
            options:
                max-size: "300m"
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    standalone:
        container_name: milvus-standalone
        image: milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2
        command: ["milvus", "run", "standalone"]
        volumes:
            - /data/milvus/rocksmq:/var/lib/milvus
        logging:
            driver: "json-file"
            options:
                max-size: "300m"
        environment:
            ETCD_ENDPOINTS: etcd:2379
            MINIO_ADDRESS: minio:9000
        ports:
            - "19530:19530"
        depends_on:
            - "etcd"
            - "minio"

networks:
    default:
        name: milvus
```

**Reply by ndtreviv** [reply]
I've also got issues whereby collections seem to disappear between restarts.

Some documentation on this would be really helpful.

My docker-compose file looks like this:

```
version: '3.1'

services:

  etcd:
    container_name: ncmec-milvus-etcd
    image: milvusdb/etcd:3.5.5-r2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
        #volumes:
            # - ./volumes/etcd:/bitnami/etcd/data:rw <-- this causes etcd to not work because of folder permissions
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/etcd/healthcheck.sh']
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    depends_on:
      - "etcd"
      - "minio"

  milvus-backup:
    container_name: milvus-backup
    image: milvus-backup
    ports:
      - "8088:8080"
    volumes:
      - ./configs/backup.yaml:/configs/backup.yaml
    depends_on:
      - "milvus"
```
