### DISCUSSION TITLE
May need more documents for deploying Milvus on k8s

### DISCUSSION THREAD

**Discussion by Chisdo** [milvus-io/milvus#6825] [Q&A and General discussion]
1. Hi there, I successfully enable CPU-Milvus on k8s through the link: [https://milvus.io/docs/v1.1.0/mishards.md#Install-Mishards](url). But I don't know how to test whether the CPU-Milvus is working or not. I may need an example doc for testing it. 

# I enabled the milvus through command:
'helm install \
   --set cluster.enabled=true     \
   --set persistence.enabled=true \
   --set mishards.replicas=2       \
   --set readonly.replicas=4       \
   milvus-release .'

2. Besides, I'm also using Ceph as persistence volume. There are three Ceph storage types: block storage, object storage, file storage. I'm wondering which one is the most appropriate for Milvus' storage class?

**Comment by yhmo** [comment]
You can refer https://github.com/milvus-io/milvus-helm, it is a project to deploy milvus by Helm.
File storage is recommended for milvus storage. We often use NAS as share storage for milvus.
In v1.1.1, milvus also support S3 storage, you need to provide S3 service information in the server_config.yaml, like this example:
https://github.com/milvus-io/milvus/blob/1.1/core/conf/demo/server_config.yaml

```
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_enabled           | If using s3 storage backend.                               | Boolean    | false           |
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_address           | The s3 server address, support domain/hostname/ipaddress   | String     | 127.0.0.1       |
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_port              | The s3 server port.                                        | Integer    | 80              |
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_access_key        | The access key for accessing s3 service.                   | String     | s3_access_key   |
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_secret_key        | The secrey key for accessing s3 service.                   | String     | s3_secret_key   |
#----------------------+------------------------------------------------------------+------------+-----------------+
# s3_bucket            | The s3 bucket name for store milvus's data.                | String     | s3_bucket       |
#                      | Note: please using differnet bucket for different milvus   |            |                 |
#                      |       cluster.                                             |            |                 |
#----------------------+------------------------------------------------------------+------------+-----------------+
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
  s3_enabled: true
  s3_address: 127.0.0.1
  s3_port: 80
  s3_access_key: xxx
  s3_secret_key: xxxx
  s3_bucket: xxxx

```
