### DISCUSSION TITLE
milvus1.1.1 support s3 of storage  (The specified key does not exist. )

### DISCUSSION THREAD

**Discussion by ggandycong** [milvus-io/milvus#7109] [Q&A and General discussion]
I am newer to milvus, want to build milvus  with minio(s3), but it not success, I need to your help.

milvus1.1.1  server  config the storage of s3(minio).  but it ocurrs error as follow listed.
```shell
[2021-08-15 12:36:30,513][ERROR][STORAGE][GetObjectFile][wal_thread] ERROR: GetObject: NoSuchKey: The specified key does not exist. with address : 172.17.0.3
```

## milvus server config
the storage of config
```yaml
storage:
   path: /tmp/milvus
   auto_flush_interval: 1
   s3_enabled: true
   s3_address: 172.17.0.3
   s3_port: 9000
   s3_access_key: minioadmin
   s3_secret_key: minioadmin
   s3_bucket: test
```

## minio server config.  
```json
"aws_s3": {
	"url": "http://172.17.0.3:9000",
	"accessKey":" minioadmin",
	"secretKey": "minioadmin",
	"api": "s3v4",
	"path": "auto"
},
```
aws_s3 have a bucket name **test**.
```shell
root@fb8c09742f42:~/work/minio# ./mc ls aws_s3/
[2021-08-14 18:58:28 +08]     0B test/
```

# Test
when I run example, milvus reporter error from log.
```shell
python3 example.py
```
error log.
```shell 
  1 [2021-08-15 12:36:30,494][ERROR][STORAGE][GetObjectFile][wal_thread] ERROR: GetObject: NoSuchKey: The specified key does not exist. with address : 172.17.0.3$
  2 [2021-08-15 12:36:30,513][ERROR][STORAGE][GetObjectFile][wal_thread] ERROR: GetObject: NoSuchKey: The specified key does not exist. with address : 172.17.0.3$
```

what is Key ?  is that  accessKey or secretKey?
