### ISSUE TITLE
[Bug]: [benchmark][performance] The number of concurrent increases, the search performance decreases

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#10735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211026-d6cc578
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc8.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Concurrency： 20;   run_id="1635249645"
Concurrency： 2;    run_id="1635250196"
```

grafana monitor:

1. The number of requests for the search interface in the same duration. 
2. High concurrency on the client side does not speed up the search speed.
<img width="1835" alt="截屏2021-10-27 14 24 45" src="https://user-images.githubusercontent.com/26307815/139011107-ccb5d2d7-3d34-4c93-9ca4-898a738c3848.png">

1. High average response time under high concurrency.
<img width="1832" alt="截屏2021-10-27 14 28 46" src="https://user-images.githubusercontent.com/26307815/139011579-b998a0e8-b9f8-4a04-85aa-3886a1ef3e4f.png">

1. Low rps under high concurrency.
<img width="1836" alt="截屏2021-10-27 14 30 20" src="https://user-images.githubusercontent.com/26307815/139011780-5250ddab-93f9-49c9-b1e6-7609046ba338.png">

### Expected Behavior

With high concurrency on the client side, the rps of search needs to be increased accordingly。

### Steps To Reproduce

```markdown
client number is equal to the number of concurrent.

argo task: benchmark-tag-g4wbh
test yaml: 
client-configmap:client-search-sift50m-hnsw-client2
server-configmap:server-cluster-4c32m-datanode1-indexnode1-querynode2-proxy2
client number: 2


argo task: benchmark-tag-8rg46
test yaml:
client-configmap:client-search-sift50m-hnsw-perf
server-configmap:server-cluster-4c32m-datanode1-indexnode1-querynode2-proxy2
client number: 20
```

### Anything else?

client-search-sift50m-hnsw-perf:
```
locust_random_performance:
      collections:
        -
          # collection_name: sift_50m_128_l2
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 16
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 99
                params:
                  top_k: 50
                  nq: 50
                  search_param:
                    ef: 64
              -
                type: load
                weight: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 3600
            # during_time: 60
```

client-search-sift50m-hnsw-client2:
```
locust_random_performance:
      collections:
        -
          # collection_name: sift_50m_128_l2
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 16
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 99
                params:
                  top_k: 50
                  nq: 50
                  search_param:
                    ef: 64
              -
                type: load
                weight: 1
            connection_num: 1
            clients_num: 2
            spawn_rate: 2
            during_time: 3600
            # during_time: 60
```
