### ISSUE TITLE
[Bug]: [benchmark][performance]The number of concurrency affects the performance of the load interface

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#10744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211026-d6cc578
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc8.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Concurrency： 20;   run_id="1635249645"
Concurrency： 2;    run_id="1635250196"
```

grafana monitor：

1. The number of requests for the load interface in the same duration.
2. The greater the number of concurrency, the less the total number of requests for the load interface in the same time.
<img width="1851" alt="截屏2021-10-27 15 22 07" src="https://user-images.githubusercontent.com/26307815/139018874-461f5f1c-34a2-4efc-b121-f800a9d220ce.png">

1. High average response time under high concurrency.
<img width="1848" alt="截屏2021-10-27 15 24 48" src="https://user-images.githubusercontent.com/26307815/139019252-0cf066cd-ae40-439e-8e26-8b75e7f2c487.png">

1. Low rps under high concurrency.
<img width="1850" alt="截屏2021-10-27 15 25 20" src="https://user-images.githubusercontent.com/26307815/139019347-44636696-ac92-4f47-adec-baf8bfea4128.png">

### Expected Behavior

rps、average response time and  the number of request of the load interface is not affected by the number of concurrency.

### Steps To Reproduce

```markdown
client number is equal to the number of concurrent.

argo task: benchmark-tag-g4wbh
test yaml: 
client-configmap:client-search-sift50m-hnsw-client2
server-configmap:server-cluster-4c32m-datanode1-indexnode1-querynode2-proxy2
client number: 2


argo task: benchmark-tag-8rg46
test yaml:
client-configmap:client-search-sift50m-hnsw-perf
server-configmap:server-cluster-4c32m-datanode1-indexnode1-querynode2-proxy2
client number: 20
```

### Anything else?

client-search-sift50m-hnsw-perf:
```
locust_random_performance:
      collections:
        -
          # collection_name: sift_50m_128_l2
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 16
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 99
                params:
                  top_k: 50
                  nq: 50
                  search_param:
                    ef: 64
              -
                type: load
                weight: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 3600
            # during_time: 60
```

client-search-sift50m-hnsw-client2:
```
locust_random_performance:
      collections:
        -
          # collection_name: sift_50m_128_l2
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 16
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 99
                params:
                  top_k: 50
                  nq: 50
                  search_param:
                    ef: 64
              -
                type: load
                weight: 1
            connection_num: 1
            clients_num: 2
            spawn_rate: 2
            during_time: 3600
            # during_time: 60
```
