### ISSUE TITLE
[Bug]: Milvus not connect to MySQL with SSL

### ISSUE THREAD

**Issue by TannedCung** [milvus-io/milvus#10840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.0.0, 1.1.1
- Deployment mode: standalone:
- SDK version: not used
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: i7-7500U/ 12GB
- GPU: None
- Others:
```

### Current Behavior

I tried to run milvus docker with ssl with below config 
MySQL is running on an other machine and connected successfully if i exec to the milvus docker and use `mysql` client commands with the same file as the one config file contains. 
```
general:
  timezone: UTC+7
  meta_uri: mysql://test:12346@x.x.x.x:3306/milvus
  meta_ssl_ca: "/certs/MySQL/ca-root"
  meta_ssl_key: "/certs/MySQL/ca-key"
  meta_ssl_cert: "/certs/MySQL/ca-cert" 
```

The return error shows 
```
[2021-10-28 19:09:00,194][ERROR][ENGINE][create][milvus_server] Failed to connect to database server: Access denied for user 'test'@'a.b.c.d' (using password: YES)
```

I'm not sure if the above config is correct because i only see it in an issue, not in official tutorial.
Thank you for your help!!!
