### ISSUE TITLE
[Bug]: Flush hangs after compact twice

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#12075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211118-cdf8e79
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: dataCooed.enableCompaction: true, compacrion.retentionDuration: 20
```

### Current Behavior

1. Deploy cluster milvus 
2. Run test case `test_compact_twice` twice
```
    def test_compact_twice(self):
        """
        target: test compact twice
        method: 1.create with shard_num=1
                2.insert and flush twice (two segments)
                3.compact
                4.insert new data
                5.compact
        expected: Merge into one segment
        """
        # init collection with one shard, insert into two segments
        collection_w = self.collection_insert_two_segments_one_shard(prefix, tmp_nb)

        # first compact two segments
        collection_w.compact()
        collection_w.wait_for_compaction_completed()
        c_plans1 = collection_w.get_compaction_plans()[0]
        target_1 = c_plans1.plans[0].target

        # insert new data
        df = cf.gen_default_dataframe_data(tmp_nb)
        collection_w.insert(df)
        log.debug(collection_w.num_entities)

        # second compact
        collection_w.compact()
        collection_w.wait_for_compaction_completed()
        collection_w.get_compaction_state()
        c_plans2 = collection_w.get_compaction_plans()[0]

        assert target_1 in c_plans2.plans[0].sources
        log.debug(c_plans2.plans[0].target)
``` 
The first run case passed. But the second run flush hangs.

**Client Logs:**
[client.log](https://github.com/milvus-io/milvus/files/7560769/client.log)

**Server Logs:** 
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7560780/milvus_logs.tar.gz)

### Anything else?

```
spec:
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
  components:
    image: harbor.zilliz.cc/milvus/milvus:master-20211118-cdf8e79
    proxy:
      serviceType: LoadBalancer
  config:
    queryNode:
      gracefulTime: 0
    dataCoord:
      enableCompaction: true
      compaction:
        retentionDuration: 20
```
