### ISSUE TITLE
[Bug]: [benchmark][standalone] Stability test of scene_test  lasting 84 hours, the processing time is getting slower and slower

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#13157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211206-67cab4e
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

locust statistics:
<img width="1910" alt="截屏2021-12-10 11 32 02" src="https://user-images.githubusercontent.com/26307815/145512765-3432aef2-a09c-4e9c-ad30-c3d2070321c9.png">

<img width="1854" alt="截屏2021-12-10 12 09 26" src="https://user-images.githubusercontent.com/26307815/145515829-4a243348-c485-4bd8-9b20-747621f27f7d.png">

### Expected Behavior

argo task: benchmark-tag-xbdbq

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-single-32c128m-noprobe

client pod: benchmark-tag-xbdbq-754080745

server:
```
NAME                                                        READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-xbdbq-1-etcd-0                                1/1     Running     0          3d13h   10.97.17.126   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-xbdbq-1-milvus-standalone-85b9974dcd-kq9sm    1/1     Running     0          3d13h   10.97.16.48    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-xbdbq-1-minio-6c8967fcfc-7lxwt                1/1     Running     0          3d13h   10.97.12.204   qa-node015.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 100 million vectors
4、flush collection
5、create index with the same params
6、load collection
7、locust concurrent：query->search, load, get->query, sence_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

```
def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)
        collection_info = self.get_info(collection_name)
        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
