### ISSUE TITLE
[Bug]: [Memory][benchmark][cluster] Stability test during 84 hours , memory of datacoord and rootcoord continue to rise

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#13876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211217-9d6ee4a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

monitor:
![Qu4PW18FQM](https://user-images.githubusercontent.com/26307815/146890044-3788abad-9e6d-4ab4-8d8a-41a7d6824249.png)
![KZJO6hK5fU](https://user-images.githubusercontent.com/26307815/146890053-660fb619-b45b-4c93-9453-a60f61c14c78.png)

### Expected Behavior

argo task: benchmark-tag-xm4sx

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-xm4sx-1-etcd-0                                      1/1     Running     0          3d17h   10.97.16.196   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-etcd-1                                      1/1     Running     0          3d17h   10.97.17.147   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-etcd-2                                      1/1     Running     0          3d17h   10.97.17.148   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-datacoord-74fd9c49f-9hn6p            1/1     Running     0          3d17h   10.97.8.216    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-datanode-6c457fbf58-lzn7l            1/1     Running     0          3d17h   10.97.13.35    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-indexcoord-7df977854-dz84k           1/1     Running     0          3d17h   10.97.4.85     qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-indexnode-7d6f794bd7-2nj85           1/1     Running     0          3d17h   10.97.15.115   qa-node012.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-proxy-7476485bc9-f4mtk               1/1     Running     0          3d17h   10.97.7.240    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-querycoord-76ccf8db9-45cbb           1/1     Running     0          3d17h   10.97.4.86     qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-querynode-5885d5c685-srkz2           1/1     Running     0          3d17h   10.97.16.194   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-milvus-rootcoord-5fcfb8c987-dpjwp           1/1     Running     0          3d17h   10.97.7.241    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-minio-0                                     1/1     Running     0          3d17h   10.97.19.58    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-minio-1                                     1/1     Running     0          3d17h   10.97.19.59    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-minio-2                                     1/1     Running     0          3d17h   10.97.19.60    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-minio-3                                     1/1     Running     0          3d17h   10.97.19.61    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-autorecovery-6df454448-dw7nb         1/1     Running     0          3d17h   10.97.7.239    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-bastion-5f679c4b5b-579h4             1/1     Running     0          3d17h   10.97.8.214    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-bookkeeper-0                         1/1     Running     0          3d17h   10.97.4.87     qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-bookkeeper-1                         1/1     Running     0          3d17h   10.97.7.242    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-bookkeeper-2                         1/1     Running     0          3d17h   10.97.8.219    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-broker-74d688bd44-5m9c5              1/1     Running     0          3d17h   10.97.11.180   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-proxy-857c97b7dd-6slgp               2/2     Running     0          3d17h   10.97.11.181   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-zookeeper-0                          1/1     Running     0          3d17h   10.97.8.217    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-zookeeper-1                          1/1     Running     0          3d17h   10.97.3.164    qa-node001.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-zookeeper-2                          1/1     Running     0          3d17h   10.97.8.218    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-xm4sx-1-pulsar-zookeeper-metadata-bmp5p             0/1     Completed   0          3d17h   10.97.8.215    qa-node006.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 100 million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query <- search, load, get <- query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

scene_test:
```
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
