### ISSUE TITLE
[Bug]: [benchmark][cluster][performance] 50 million data sets, create ivf_flat index, increase the number of indexnodes, the time reduction of index creation does not meet expectations

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**50 million data sets, create ivf_flat index, increase the number of indexnodes, the time reduction of index creation does not meet expectations**
<img width="1338" alt="截屏2022-01-13 15 14 07" src="https://user-images.githubusercontent.com/26307815/149283036-a6ebc3c9-c4d6-4510-aa38-d3c683137e7f.png">

### Steps To Reproduce

```markdown
1、create collection
2、insert 50 million dataset
3、flush collection
4、build index
```

### Anything else?

pre2.0-client-index-sift50m-ivf-flat-2048:
```
insert_build_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
```
