### ISSUE TITLE
[Bug]: [benchmark][cluster][performance] 50 million data sets create hnsw index, the index creation time does not decrease with the increase of indexnodes

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**50 million data sets create hnsw index, the index creation time does not decrease with the increase of indexnodes**

<img width="1344" alt="截屏2022-01-13 15 09 40" src="https://user-images.githubusercontent.com/26307815/149282464-e4eaac4e-850d-4a9a-9b23-7c8bd54d1778.png">

### Expected Behavior

**50 million datasets create hnsw index, the index creation time decreases with the increase of indexnodes**

### Steps To Reproduce

```markdown
1、create collection
2、insert 50 million dataset
3、flush collection
4、build index
```

### Anything else?

pre2.0-client-index-sift50m-hnsw-ef500:
```
insert_build_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 16
            efConstruction: 500
```
