### ISSUE TITLE
[Bug]: [benchmark][cluster][Memory Leak] Datanode's cpu and mem keep going up and not going down

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220120-21f999f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

monitor：
<img width="1860" alt="截屏2022-01-24 17 32 49" src="https://user-images.githubusercontent.com/26307815/150757248-86d462f9-88b3-4a7d-8f79-0df6c222f7a4.png">
<img width="1823" alt="截屏2022-01-24 17 33 06" src="https://user-images.githubusercontent.com/26307815/150757289-31ff32e5-e080-4d36-87b0-5c29bdc0f717.png">

### Expected Behavior

argo task: benchmark-no-clean-8bms6

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-no-clean-8bms6-1-etcd-0                                 1/1     Running     0          3d18h   10.97.17.55    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-etcd-1                                 1/1     Running     0          3d18h   10.97.16.101   qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-etcd-2                                 1/1     Running     0          3d18h   10.97.17.57    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-datacoord-5856dfb757-n864m      1/1     Running     0          3d18h   10.97.8.165    qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-datanode-6469ffb77b-mpkwn       1/1     Running     0          3d18h   10.97.16.99    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-indexcoord-fdd669778-vqwhf      1/1     Running     0          3d18h   10.97.8.163    qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-indexnode-57c678c94c-l5p8q      1/1     Running     0          3d18h   10.97.17.53    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-proxy-dbbbcd7b8-m58hh           1/1     Running     0          3d18h   10.97.8.166    qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-querycoord-548f7b69fc-grwlc     1/1     Running     0          3d18h   10.97.8.161    qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-querynode-fdb7f869-cbtqp        1/1     Running     0          3d18h   10.97.16.98    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-milvus-rootcoord-77b965945c-jjhb8      1/1     Running     0          3d18h   10.97.8.164    qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-minio-0                                1/1     Running     0          3d18h   10.97.12.119   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-minio-1                                1/1     Running     0          3d18h   10.97.19.248   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-minio-2                                1/1     Running     0          3d18h   10.97.19.247   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-minio-3                                1/1     Running     0          3d18h   10.97.12.121   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-autorecovery-6bfdb969cb-9tz95   1/1     Running     0          3d18h   10.97.3.163    qa-node001.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-bastion-74c8684986-pn5lj        1/1     Running     0          3d18h   10.97.9.133    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-bookkeeper-0                    1/1     Running     0          3d18h   10.97.11.205   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-bookkeeper-1                    1/1     Running     0          3d18h   10.97.7.99     qa-node005.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-bookkeeper-2                    1/1     Running     0          3d18h   10.97.9.138    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-broker-6df645cff-26gh2          1/1     Running     0          3d18h   10.97.11.202   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-proxy-646b7f5dc5-m56ml          2/2     Running     0          3d18h   10.97.6.68     qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-zookeeper-0                     1/1     Running     0          3d18h   10.97.4.234    qa-node002.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-zookeeper-1                     1/1     Running     0          3d18h   10.97.7.96     qa-node005.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-zookeeper-2                     1/1     Running     0          3d18h   10.97.9.135    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-8bms6-1-pulsar-zookeeper-metadata-7m6gl        0/1     Completed   0          3d18h   10.97.4.232    qa-node002.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 100million vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: search, load, query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

```
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
