### ISSUE TITLE
[Bug]: [benchmark][cluster] When inserting and querying, the response time of the interface is getting longer and longer

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220213-f74a9c2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-tag-xwtx2-71121370

client data: [1644808606]
<img width="1827" alt="截屏2022-02-15 17 03 24" src="https://user-images.githubusercontent.com/26307815/154028357-35691dd2-7793-4ac6-935e-39e731c98167.png">

<img width="1859" alt="截屏2022-02-15 17 03 37" src="https://user-images.githubusercontent.com/26307815/154028431-4dee23f2-1553-416f-b9e1-fb2ad407f564.png">

<img width="1853" alt="截屏2022-02-15 17 03 53" src="https://user-images.githubusercontent.com/26307815/154028480-8bf224cb-bae3-4eb7-80a1-8e49ff977ce5.png">

<img width="1836" alt="截屏2022-02-15 17 04 04" src="https://user-images.githubusercontent.com/26307815/154028519-079785b9-ccf1-4afc-a93b-acc7741c9c51.png">

### Expected Behavior

argo task: benchmark-tag-xwtx2

test yaml: 
client-configmap:client-random-locust-1m
server-configmap:server-cluster-8c32m

server:
```
NAME                                                         READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-xwtx2-1-etcd-0                                 1/1     Running     0          10h    10.97.4.172    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-etcd-1                                 1/1     Running     0          10h    10.97.6.93     qa-node004.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-etcd-2                                 1/1     Running     0          10h    10.97.11.16    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-datacoord-754c77cc57-ptkfb      1/1     Running     0          10h    10.97.14.29    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-datanode-f96fff74d-tgq6q        1/1     Running     0          10h    10.97.20.194   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-indexcoord-7f9d885496-48vwg     1/1     Running     0          10h    10.97.11.15    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-indexnode-76bfd9df4f-fmqrt      1/1     Running     0          10h    10.97.20.193   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-proxy-6445b58ccd-7hvrt          1/1     Running     0          10h    10.97.11.11    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-querycoord-c7c94f447-7jh4l      1/1     Running     0          10h    10.97.11.9     qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-querynode-5df995f999-6plx4      1/1     Running     0          10h    10.97.14.30    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-milvus-rootcoord-6875dbd55c-fjq84      1/1     Running     0          10h    10.97.11.8     qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-minio-0                                1/1     Running     0          10h    10.97.20.200   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-minio-1                                1/1     Running     0          10h    10.97.20.204   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-minio-2                                1/1     Running     0          10h    10.97.20.201   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-minio-3                                1/1     Running     0          10h    10.97.20.202   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-autorecovery-685647bbf8-4d5js   1/1     Running     0          10h    10.97.11.12    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-bastion-7bcffcc7d8-csmcn        1/1     Running     0          10h    10.97.11.13    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-bookkeeper-0                    1/1     Running     0          10h    10.97.10.51    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-bookkeeper-1                    1/1     Running     0          10h    10.97.20.205   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-bookkeeper-2                    1/1     Running     0          10h    10.97.20.207   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-broker-656567c569-6vp4p         1/1     Running     0          10h    10.97.11.14    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-proxy-d799f59f-s4q9m            2/2     Running     0          10h    10.97.20.195   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-zookeeper-0                     1/1     Running     0          10h    10.97.4.171    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-zookeeper-1                     1/1     Running     0          10h    10.97.4.173    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-zookeeper-2                     1/1     Running     0          10h    10.97.4.174    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-xwtx2-1-pulsar-zookeeper-metadata-v958s        0/1     Completed   0          10h    10.97.11.10    qa-node009.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1. create collection
2. build index of ivf_sq8
3. insert 1 million vectors
4. flush collection
5. build index with the same params
6. load colllection
7. locust concurrent: query<-search, insert, get<-query, load
```

### Anything else?

client-random-locust-1m:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_1m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 1024
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: insert
                weight: 10
                params:
                  ni_per: 500
              -
                type: load
                weight: 1
              -
                type: get
                weight: 2
                params:
                  ids_length: 10
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 10h
```
