### ISSUE TITLE
[Bug]: GRPC Operation hangs after host lost power.

### ISSUE THREAD

**Issue by fightingyuman** [milvus-io/milvus#15637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0-rc9/2.0.0
- Deployment mode(standalone or cluster): standalone/cluster in single host
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0-rc9 / pymilvus v2.0.0
- OS(Ubuntu or CentOS): CentOS 7.9 x86_64
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz / 128 GB
- GPU: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]
- Others: bootcamp --> reverse_image_search
```

### Current Behavior

When I load a lot of image into milvus, don't stop docker service, I lost power of the host, when it start again, it stucks when search or insert vector, it can't recover by restart docker or anything else.
I have test several times, with `standalone` version, it can be reproduced after shutdown by `poweroff` command. And cluster version with power off directly.

### Expected Behavior

It can be recovered for operations.

### Steps To Reproduce

```markdown
1. start a standalone/simple cluster with docker compose on host or in a Virtual Machine
2. insert into milvus continuous
3. unplug power cable for the host/ or shutdown a Virtual Machine without docker properly stop
4. restart the host, docker container
5. do search or insert with pymilvus, it hangs.
```

### Anything else?

sometimes, collection.num_entities don't return because of `_wait_for_flushed` in `pymilvus/client/grpc_handler.py` loops for ever. When it happens, one of the following operation can't be done, the other one can be done.
- insert or search one collection.
- get total count for collection by num_entities,

**Comment by fightingyuman** [comment]
Sure, how to get logs for standalone / clusters? just use `docker log` ?
> Hi, would you mind posting the logs here?

OK, I will replace this step to and post result here.
> And can you help to try a test? if step 3 is replaced with using `docker-compose down`, check this issue will be reproduced again?

**Comment by xiaofan-luan** [comment]
> ow to get logs for standalone / clusters? just use `docker log` ?
> 
> > Hi, would you mind posting the logs here?
> 
> OK, I will replace this step to and post result here.
> 
> > And can you help to try a test? if step 3 is replaced with using `docker-compose down`, check this issue will be reproduced again?

docker compose down may not be as equal as power off, if we can add pod crash test that might be a good way to simulate power off

**Comment by zhuwenxing** [comment]
>Sure, how to get logs for standalone / clusters? just use docker log ?
`docker-compose logs > standalone.log 2>&1`

**Comment by zhuwenxing** [comment]
> > ow to get logs for standalone / clusters? just use `docker log` ?
> > > Hi, would you mind posting the logs here?
> > 
> > 
> > OK, I will replace this step to and post result here.
> > > And can you help to try a test? if step 3 is replaced with using `docker-compose down`, check this issue will be reproduced again?
> 
> docker compose down may not be as equal as power off, if we can add pod crash test that might be a good way to simulate power off
Yes, I just want to exclude this possibility.

**Comment by fightingyuman** [comment]
I can't reproduce it by `docker down` with cluster, I reproduced it by VM ware `Power Off`. Here is the log:

[cluster.log](https://github.com/milvus-io/milvus/files/8098008/cluster.log)

My docker-compose.yml config like this:

```yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - /home/milvus-volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.7.3
    volumes:
      - /home/milvus-volumes/pulsar:/pulsar/data
    environment:
      # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
      # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - /home/milvus-volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rootcoord:
    container_name: milvus-rootcoord
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "rootcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      ROOT_COORD_ADDRESS: rootcoord:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  proxy:
    container_name: milvus-proxy
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "proxy"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    ports:
      - "19530:19530"

  querycoord:
    container_name: milvus-querycoord
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "querycoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      QUERY_COORD_ADDRESS: querycoord:19531
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  querynode:
    container_name: milvus-querynode
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "querynode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "querycoord"

  indexcoord:
    container_name: milvus-indexcoord
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "indexcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      INDEX_COORD_ADDRESS: indexcoord:31000
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  indexnode:
    container_name: milvus-indexnode
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "indexnode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      INDEX_COORD_ADDRESS: indexcoord:31000
    depends_on:
      - "indexcoord"

  datacoord:
    container_name: milvus-datacoord
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "datacoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      DATA_COORD_ADDRESS: datacoord:13333
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  datanode:
    container_name: milvus-datanode
    image: milvusdb/milvus:v2.0.0
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "datacoord"

  attu:
    container_name: milvus-insight
    image: zilliz/attu:latest
    environment:
      HOST_URL: "http://192.168.2.46:3000"
      MILVUS_URL: "192.168.2.46:19530"
    ports:
      - "3000:3000"
    depends_on:
      - "datanode"
      - "indexnode"
      - "querynode"

networks:
  default:
    name: milvus
```
