### ISSUE TITLE
[Bug]:  [benchmark][cluster][Memory Leak] Memory of datacoord and rootcoord keep going up and not going down when doing stability test

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220218-d0110732
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-no-clean-gd72b-1436584063

argo task: benchmark-no-clean-gd72b

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-no-clean-gd72b-1-etcd-0                                 1/1     Running     0          2d19h   10.97.11.139   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-etcd-1                                 1/1     Running     0          2d19h   10.97.20.67    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-etcd-2                                 1/1     Running     0          2d19h   10.97.6.80     qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-datacoord-6cd87f4cf8-9nd6z      1/1     Running     0          2d19h   10.97.11.137   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-datanode-f966849fc-qt422        1/1     Running     0          2d19h   10.97.20.60    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-indexcoord-7c675b9dff-m7rx6     1/1     Running     0          2d19h   10.97.11.136   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-indexnode-5c86bd59cb-b46sw      1/1     Running     0          2d19h   10.97.20.59    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-proxy-799fc44cfc-f2l9q          1/1     Running     0          2d19h   10.97.11.135   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-querycoord-5b67747c56-gvtzc     1/1     Running     0          2d19h   10.97.11.133   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-querynode-65fd6db958-2cv7w      1/1     Running     0          2d19h   10.97.11.138   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-milvus-rootcoord-7bd77d4f5d-bj9ps      1/1     Running     0          2d19h   10.97.11.134   qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-minio-0                                1/1     Running     0          2d19h   10.97.20.69    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-minio-1                                1/1     Running     0          2d19h   10.97.20.71    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-minio-2                                1/1     Running     0          2d19h   10.97.20.68    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-minio-3                                1/1     Running     0          2d19h   10.97.20.72    qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-autorecovery-54894bf868-z2m59   1/1     Running     0          2d19h   10.97.7.202    qa-node005.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-bastion-df9597dcb-jjfs2         1/1     Running     0          2d19h   10.97.7.200    qa-node005.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-bookkeeper-0                    1/1     Running     0          2d19h   10.97.5.105    qa-node003.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-bookkeeper-1                    1/1     Running     0          2d19h   10.97.10.242   qa-node008.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-bookkeeper-2                    1/1     Running     0          2d19h   10.97.3.114    qa-node001.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-broker-6d4b5645f5-wd8mz         1/1     Running     0          2d19h   10.97.14.219   qa-node011.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-proxy-74b67fc7-kvf2p            2/2     Running     0          2d19h   10.97.14.218   qa-node011.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-zookeeper-0                     1/1     Running     0          2d19h   10.97.3.112    qa-node001.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-zookeeper-1                     1/1     Running     0          2d19h   10.97.6.81     qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-zookeeper-2                     1/1     Running     0          2d19h   10.97.3.113    qa-node001.zilliz.local   <none>           <none>
benchmark-no-clean-gd72b-1-pulsar-zookeeper-metadata-52pwm        0/1     Completed   0          2d19h   10.97.7.201    qa-node005.zilliz.local   <none>           <none>
```

datacoord and rootcoord:
<img width="1857" alt="截屏2022-02-21 14 31 27" src="https://user-images.githubusercontent.com/26307815/154901141-986fffc8-ca97-4735-bc53-0129cb1d7043.png">

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 100million vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: search, load, query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```
```

    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
