### ISSUE TITLE
[Bug]: Use aliyun-OSS instead of MinIO  

### ISSUE THREAD

**Issue by chunyuforka** [milvus-io/milvus#15987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): null
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 24C/192G
- GPU: null
- Others:
```

## I am installing the Milvus cluster using Helm
```
# cat value.yaml
minio:
  enabled: false

externalS3:
  enabled: true
  host: "oss-cn-beijing-internal.aliyuncs.com"
  port: "80"
  accessKey: xxxx
  secretKey: xxxx
  useSSL: false
  bucketName: "milvus"
  rootPath: "milvus"
```
## The following log is displayed on the Datacoord service

```
[2022/03/10 02:22:55.748 +00:00] [ERROR] [service.go:166] ["Datacoord start failed"] lerrore"all attempts esults:`nattempt #1:Access Denied.\nattempt #2:Access Denied.\n"]
```

**Comment by LoveEachDay** [comment]
Try  set `externalS3.enabled` to `true`

**Comment by yanliang567** [comment]
@chunyuforka please try as suggested above
/assign @chunyuforka 
/unassign

**Comment by chunyuforka** [comment]
> 尝试设置`externalS3.enabled`为`true`

Sorry, it was set to "true" when I installed it.
Here is a copy of the wrong template when I submitted this issus

**Comment by chunyuforka** [comment]
My install config：
```
externalS3:
  enabled: true
  host: "oss-cn-beijing-internal.aliyuncs.com"
  port: "80"
  accessKey: xxxx
  secretKey: xxxx
  useSSL: false
  bucketName: "milvus"
  rootPath: "milvus"
```

**Comment by chunyuforka** [comment]
Now please review the question

**Comment by LoveEachDay** [comment]
Could you paste the `configmap` for milvus using the following command:
`kubectl get cm <release-name>-milvus -o yaml

And milvus server use `minio` sdk to access the object storage, can you check the aliyun oss access via the `mc` command, following instructions from [here](https://docs.min.io/docs/minio-client-complete-guide.html)

**Comment by chunyuforka** [comment]
### Thank you, I used mc to test, but found some problems
```
mc cp myeasylog.log s3/oss-aiaas/1.log
mc: <ERROR> Failed to copy `/milvus/myeasylog.log`. Aws MultiChunkedEncoding is not supported.
```
### The engineer of aliyunOSS told me:
```
  目前oss只是部分接口支持S3协议，参考 https://help.aliyun.com/document_detail/64919.html
```

**Comment by chunyuforka** [comment]
Did I hit a dead end

**Comment by LoveEachDay** [comment]
You can try to install a minio cluster instead of using aliyun oss.

**Comment by xiaofan-luan** [comment]
> Did I hit a dead end

We will leave the issue here see if anyone interested in integrating milvus with aliyun OSS

**Comment by chunyuforka** [comment]
Aliyun engineers advised me to switch to HTTPS.
The 'mc cp' command is successfully executed.
But the installation still failed, the error is still reported.

**Comment by chunyuforka** [comment]
### I successfully integrated OSS using MinIO's Gateway mode . 
```
minio:
  enabled: true
  name: minio
  mode: standalone   // Only the standalone mode can be used as a gateway  
  image:
    tag: "RELEASE.2020-11-06T23-17-07Z"
    pullPolicy: IfNotPresent
  accessKey: miniouserxxx
  secretKey: miniopassxxx
  existingSecret: ""
  bucketName: "oss-aiaas"   // The name of the OSS bucket . 
  rootPath: "milvus"

  gcsgateway:
    enabled: false
    replicas: 1
    gcsKeyJson: "/etc/credentials/gcs_key.json"
    projectId: ""

  s3gateway:
    enabled: true                       
    replicas: 3                       // Number of deployment copies of MinIO Gateway
    serviceEndpoint: "https://oss-cn-beijing-internal.aliyuncs.com"  
    accessKey: "xxxx"
    secretKey: "xxxxxxx"
```
### Data is successfully entered into OSS during the test
