### ISSUE TITLE
[Bug]: Bucket rootPath config not working as expected when using AWS S3

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#16106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): standalone
- Others: using external S3 storage from aws

config milvus's storage as:

``` yaml
minio:
  address: yelusion-test001.s3.ap-southeast-1.amazonaws.com
  bucketName: yelusion-test001
  port: 443
  rootPath: /0000001-milvus/in01-bdee1b970e4b2a20b3ab0659937
  useSSL: true
```

### Current Behavior

The rootPath milvus uses in bucket is in fact `/yelusion-test001//0000001-milvus/in01-bdee1b970e4b2a20b3ab0659937/`

it seems in the pattern `/${bucketName}/${rootPath}/`

### Expected Behavior

The rootPath  should be `/0000001-milvus/in01-bdee1b970e4b2a20b3ab0659937/` (`${rootPath}/`)

### Steps To Reproduce

using external S3 storage from aws, config milvus's storage as:

``` yaml
minio:
  address: ${address}
  bucketName: ${bucketName}
  port: 443
  rootPath: ${rootPath}
  useSSL: true
```
