### ISSUE TITLE
[Bug]: [benchmark]The response time of the concurrent test interface is longer than before

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220222-ce9662c1
- Deployment mode(standalone or cluster): cluster & standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Compared with the version after **master-20220222-ce9662c1** and the version before **master-20220218-d0110732**, the response time of the concurrent interface is longer than before。

current results：
<img width="1357" alt="截屏2022-03-25 16 16 49" src="https://user-images.githubusercontent.com/26307815/160081587-40b682af-5a4b-4abf-9485-3bec18c3a859.png">
<img width="1360" alt="截屏2022-03-25 16 17 03" src="https://user-images.githubusercontent.com/26307815/160081615-4551045f-f575-4286-9b03-86ec28c16740.png">
<img width="1360" alt="截屏2022-03-25 16 17 20" src="https://user-images.githubusercontent.com/26307815/160081642-1a6267cc-b748-4dc3-8e58-365977b2bcb6.png">
<img width="1367" alt="截屏2022-03-25 16 17 40" src="https://user-images.githubusercontent.com/26307815/160081693-9fbcbd20-33c5-4306-bd7f-1e291760f4d3.png">

### Expected Behavior

result of master-20220218-d0110732：
<img width="1356" alt="截屏2022-03-25 16 15 07" src="https://user-images.githubusercontent.com/26307815/160081348-9407cc03-afce-48a5-852c-f38f711bddaa.png">
<img width="1363" alt="截屏2022-03-25 16 15 30" src="https://user-images.githubusercontent.com/26307815/160081401-361137ab-47d8-4db7-934f-3dc6ad508061.png">
<img width="1351" alt="截屏2022-03-25 16 15 47" src="https://user-images.githubusercontent.com/26307815/160081442-82b35893-81f7-4cf0-b42b-d7a523065321.png">
<img width="1362" alt="截屏2022-03-25 16 16 00" src="https://user-images.githubusercontent.com/26307815/160081459-fda4ebdf-f534-4761-9bef-f248a4a48126.png">

### Anything else?

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

client-random-locust-100m-ddl-r8-w2：
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```
