### ISSUE TITLE
[Bug]: [benchmark][cluster] CPU of datanode keep going up and not going down when doing stability test

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2-20220324-8f4479a4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-tag-no-clean-7btlw

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

client pod: benchmark-tag-no-clean-7btlw-3672893248

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-no-clean-7btlw-1-etcd-0                             1/1     Running     0          3d17h   10.97.17.112   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-etcd-1                             1/1     Running     0          3d17h   10.97.16.90    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-etcd-2                             1/1     Running     0          3d17h   10.97.17.113   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-datacoord-5856b86c6-qdjxv   1/1     Running     0          3d17h   10.97.8.167    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-datanode-56949d7f95-vv6d7   1/1     Running     0          3d17h   10.97.17.88    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-indexcoord-7f46d9c4985mll   1/1     Running     0          3d17h   10.97.8.168    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-indexnode-8445f479982tv6h   1/1     Running     0          3d17h   10.97.14.140   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-proxy-5f5564c595-jd62c      1/1     Running     0          3d17h   10.97.3.104    qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-querycoord-7c496ddc69lrhx   1/1     Running     0          3d17h   10.97.8.170    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-querynode-7584d9c8b8zwbrz   1/1     Running     0          3d17h   10.97.16.89    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-milvus-rootcoord-7c6f5d9d76x6qw6   1/1     Running     0          3d17h   10.97.8.169    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-minio-0                            1/1     Running     0          3d17h   10.97.19.98    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-minio-1                            1/1     Running     0          3d17h   10.97.19.103   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-minio-2                            1/1     Running     0          3d17h   10.97.19.102   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-minio-3                            1/1     Running     0          3d17h   10.97.19.104   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-bookie-0                    1/1     Running     0          3d17h   10.97.19.97    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-bookie-1                    1/1     Running     0          3d17h   10.97.3.105    qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-bookie-2                    1/1     Running     0          3d17h   10.97.8.171    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-bookie-init-7s52j           0/1     Completed   0          3d17h   10.97.8.166    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-broker-0                    1/1     Running     0          3d17h   10.97.12.195   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-proxy-0                     1/1     Running     0          3d17h   10.97.8.165    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-pulsar-init-h6klc           0/1     Completed   0          3d17h   10.97.4.116    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-recovery-0                  1/1     Running     0          3d17h   10.97.4.117    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-zookeeper-0                 1/1     Running     0          3d17h   10.97.5.19     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-zookeeper-1                 1/1     Running     0          3d17h   10.97.5.20     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7btlw-1-pulsar-zookeeper-2                 1/1     Running     0          3d17h   10.97.5.21     qa-node003.zilliz.local   <none>           <none>
```

monitor:
<img width="1371" alt="截屏2022-03-28 11 21 54" src="https://user-images.githubusercontent.com/26307815/160321087-751ab381-3a8f-4aaf-97e8-e167ae246114.png">

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_sq8
3、insert 100m million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query<-search, load, get<-query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```
