### ISSUE TITLE
[Bug]: [benchmark][cluster]During the stability test, datacoord's CPU and memory kept going up, not down.

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220402-028c5cb8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-tag-b8htt

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-cluster-8c64m

client pod: benchmark-tag-b8htt-3255216514

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-b8htt-1-etcd-0                                      1/1     Running     0          3d15h   10.97.17.8     qa-node014.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-etcd-1                                      1/1     Running     0          3d15h   10.97.16.17    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-etcd-2                                      1/1     Running     0          3d15h   10.97.17.9     qa-node014.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-datacoord-58c78c8787-54t9b           1/1     Running     0          3d15h   10.97.11.77    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-datanode-6f8cdfcc4b-ztldq            1/1     Running     0          3d15h   10.97.20.117   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-indexcoord-644bd47d98-w84r6          1/1     Running     0          3d15h   10.97.11.79    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-indexnode-7564996c47-pdwpm           1/1     Running     0          3d15h   10.97.20.119   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-proxy-5bc7cd94d4-r69zr               1/1     Running     0          3d15h   10.97.11.85    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-querycoord-5b475b4f5c-f88h9          1/1     Running     0          3d15h   10.97.11.78    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-querynode-6cbc595865-njbwf           1/1     Running     0          3d15h   10.97.20.118   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-milvus-rootcoord-76d56d8f95-7kb8p           1/1     Running     0          3d15h   10.97.11.76    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-minio-0                                     1/1     Running     0          3d15h   10.97.20.121   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-minio-1                                     1/1     Running     0          3d15h   10.97.19.135   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-minio-2                                     1/1     Running     0          3d15h   10.97.19.132   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-minio-3                                     1/1     Running     0          3d15h   10.97.19.136   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-bookie-0                             1/1     Running     0          3d15h   10.97.19.131   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-bookie-1                             1/1     Running     0          3d15h   10.97.17.5     qa-node014.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-bookie-2                             1/1     Running     0          3d15h   10.97.5.48     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-bookie-init-wbg4p                    0/1     Completed   0          3d15h   10.97.18.4     qa-node017.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-broker-0                             1/1     Running     0          3d15h   10.97.12.238   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-proxy-0                              1/1     Running     0          3d15h   10.97.3.22     qa-node001.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-pulsar-init-gkwq8                    0/1     Completed   0          3d15h   10.97.4.252    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-recovery-0                           1/1     Running     0          3d15h   10.97.16.15    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-zookeeper-0                          1/1     Running     0          3d15h   10.97.4.253    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-zookeeper-1                          1/1     Running     0          3d15h   10.97.18.5     qa-node017.zilliz.local   <none>           <none>
benchmark-tag-b8htt-1-pulsar-zookeeper-2                          1/1     Running     0          3d15h   10.97.9.73     qa-node007.zilliz.local   <none>           <none>
```

monitor:
<img width="1371" alt="截屏2022-04-06 11 47 41" src="https://user-images.githubusercontent.com/26307815/161891942-cc708ed6-654e-417b-a83e-f592e02ec5dc.png">

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_sq8
3、insert 100m million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query<-search, load, get<-query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400

```
