### ISSUE TITLE
[Bug]: [benchmark][standalone] CPU of Milvus standalone keep going up and not going down

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2-20220331-c9cc2405
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-d4l42

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-single-32c128m

client pod: benchmark-d4l42-3286747703

server:
```
NAME                                                       READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-d4l42-1-etcd-0                                   1/1     Running     0          3d13h   10.97.16.61    qa-node013.zilliz.local   <none>           <none>
benchmark-d4l42-1-milvus-standalone-5d95564855-dfdjn       1/1     Running     0          3d13h   10.97.17.11    qa-node014.zilliz.local   <none>           <none>
benchmark-d4l42-1-minio-56bdc8d6c9-w26hz                   1/1     Running     0          3d13h   10.97.19.100   qa-node016.zilliz.local   <none>           <none>
```

monitor:
<img width="1373" alt="截屏2022-04-06 16 21 16" src="https://user-images.githubusercontent.com/26307815/161929577-2761927e-731d-42cb-b37e-2c0dc7721a05.png">

<img width="1384" alt="截屏2022-04-06 16 21 32" src="https://user-images.githubusercontent.com/26307815/161929625-5f64c5a2-0d6a-4b44-af2e-401bc1c3b0e1.png">

### Steps To Reproduce

```markdown
1、create collation
2、build index of ivf_sq8
3、insert 100 million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query<-search, load, get<-query, scene_test
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

scene_test:
```
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
