### ISSUE TITLE
[Bug]: [benchmark][standalone] RpcError: _MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220406-1e6f6bd0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:  benchmark-tag-8fgt5

test yaml: 
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-single-32c128m

client pod: benchmark-tag-8fgt5-4039138332
client log file: locust_report_2022-04-06_665.log

**A few occasional errors in concurrent interface requests**
client log:
```
[2022-04-06 11:24:35,130] [   ERROR] - grpc RpcError: [_execute_search_requests], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-06 11:23:35.129520', 'gRPC error': '2022-04-06 11:24:35.130327'}> (pymilvus.decorators:81)
[2022-04-06 11:24:35,131] [   ERROR] - grpc RpcError: [search], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-06 11:23:35.120453', 'gRPC error': '2022-04-06 11:24:35.131520'}> (pymilvus.decorators:81)
[2022-04-06 11:28:35,132] [   ERROR] - grpc RpcError: [query], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-06 11:23:35.121605', 'gRPC error': '2022-04-06 11:28:35.132182'}> (pymilvus.decorators:81)
```

server:
```
NAME                                                       READY   STATUS      RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-8fgt5-1-etcd-0                               1/1     Running     0          45h   10.97.16.207   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-8fgt5-1-milvus-standalone-7fbf97888c-57qnp   1/1     Running     0          45h   10.97.17.44    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-8fgt5-1-minio-6ccb6bb6dc-fbq7x               1/1     Running     0          45h   10.97.19.249   qa-node016.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_sq8
3、insert 100m million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query<-search, load, get<-query, scene_test 《- raise error
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

```
    @time_wrapper
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
