### ISSUE TITLE
[BUG] IVF_FLAT search out of memory

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#169]
**Describe the bug**
server_version:
0.5.1

logs :

```
2019-11-01 22:28:53,770 | ERROR | default | [ENGINE] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 1075200000 bytes (error 2 out of memory)

2019-11-01 22:28:53,771 | ERROR | default | [SERVER] Task failed with code: Error code(30117): out of memory: CPU2GPU
```

config:
```
cache_config:
  cache_insert_data: false
  cpu_cache_capacity: 50
  cpu_cache_threshold: 0.85
  gpu_cache_capacity: 6
db_config:
  backend_url: sqlite://:@:/
  insert_buffer_size: 4
  preload_table: null
  primary_path: /opt/milvus
  secondary_path: null
engine_config:
  use_blas_threshold: 1100
  use_gpu_threshold: 100
metric_config:
  collector: prometheus
  enable_monitor: true
  prometheus_config:
    port: 8080
resource_config:
  index_build_device: gpu0
  search_resources:
  - gpu0
  - gpu1
server_config:
  address: 0.0.0.0
  deploy_mode: single
  port: 19530
  time_zone: UTC+8
```

**Expected behavior**
No exception or error

**Screenshots**
N/A

**Additional context**
N/A
