### ISSUE TITLE
[Bug]: Flush data hangs

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220510-4ee78eb5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev39
- OS(Ubuntu or CentOS): 
- CPU/Memory:
- GPU: 
- Others:
```

### Current Behavior

Flush data hangs
```
[2022-05-11 09:27:20,773 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['stress_replicas_eLGkWaPH', {
  auto_id: False
  description:
  fields: [{
    name: int64
    description:
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: float
    description:
    type: 10
  }, {
    name: varchar
    description:
    type: 21
    params: {'max_length_pe......, kwargs: {'consistency_level': 'Strong'} (api_request.py:55)
[2022-05-11 09:27:20,861 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: stress_replicas_eLGkWaPH
<partitions>: [{"name": "_default", "collection_name": "stress_replicas_eLGkWaPH", "description": ""}]
<description>:
<schema>: {
  auto_id: False
  description:
  fields: [{
    name: int64
    description:
    type: 5
    is_primary: ......  (api_request.py:27)
[2022-05-11 09:27:26,712 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [       int64    float varchar                                       float_vector
0          0      0.0       0  [0.06867322373893722, 0.05835227366440098, 0.0...
1          1      1.0       1  [0.013481319409776404, 0.06465860859038637, 0....
2          2      2.0       2  [0.047658085016864096, 0......., kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-11 09:27:32,049 - DEBUG - ci_test]: (api_response) : (insert count: 25000, delete count: 0, upsert count: 0, timestamp: 433130372814340097)  (api_request.py:27)
[2022-05-11 09:27:34,087 - INFO - ci_test]: After 1 insert, num_entities: 25000 (test_chaos_memory_stress.py:277)
[2022-05-11 09:27:34,087 - INFO - ci_test]: 0 insert and flush data cost: 0:00:13.225349 (test_chaos_memory_stress.py:279)
[2022-05-11 09:27:40,343 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [       int64    float varchar                                       float_vector
0          0      0.0       0  [0.0002679418644478826, 0.054207371269376484, ...
1          1      1.0       1  [0.009930236797440846, 0.050268805196105396, 0...
2          2      2.0       2  [0.05172899793294425, 0.0......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-11 09:27:45,559 - DEBUG - ci_test]: (api_response) : (insert count: 25000, delete count: 0, upsert count: 0, timestamp: 433130376364032001)  (api_request.py:27)
... (flush hangs)
```
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8669220/mic_logs.tar.gz)

### Steps To Reproduce

```markdown
nb = 25000
        dim = 512
        connections.connect("default", host=host, port=19530)
        collection_w = ApiCollectionWrapper()
        c_name = "stress_replicas_eLGkWaPH"
        collection_w.init_collection(name=c_name,
                                     schema=cf.gen_default_collection_schema(dim=dim))

        # # insert 10 sealed segments
        for i in range(10):
            t0 = datetime.datetime.now()
            df = cf.gen_default_dataframe_data(nb=nb, dim=dim)
            res = collection_w.insert(df)[0]
            assert res.insert_count == nb
            log.info(f'After {i + 1} insert, num_entities: {collection_w.num_entities}')
            tt = datetime.datetime.now() - t0
            log.info(f"{i} insert and flush data cost: {tt}")

        log.debug(collection_w.num_entities)
```

### Anything else?

```
spec:
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          persistence:
            storageClass: local-path
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          proxy:
            configData:
              httpNumThreads: "80"
          zookeeper:
            volumes:
              data:
                storageClassName: local-path
            bookkeeper:
              volumes:
                journal:
                  storageClassName: local-path
                ledgers:
                  storageClassName: local-path
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          persistence:
            storageClass: local-path
  components:
    #image: harbor.zilliz.cc/milvus/milvus:master-20220406-909dd737
    image: milvusdb/milvus-dev:master-20220510-4ee78eb5
    proxy:
      serviceType: LoadBalancer
    queryNode:
      replicas: 5
      resources:
        limits:
          memory: 6Gi
  config:
    log:
      level: debug
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```
