### ISSUE TITLE
[Bug]: log.file.rootPath failed to apply in milvus 2.0.2

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#17283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Brought up the milvus cluster by running cmd `helm install -f ./charts/milvus/values.yaml milvus-dev milvus/milvus` with the following log settings:
```
log:
  level: "debug"
  file:
    rootPath: "/tmp"
    maxSize: 300    # MB
    maxAge: 10    # day
    maxBackups: 20
  format: "text"    # text/json

  persistence:
    mountPath: "/milvus/logs"
    ## If true, create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: false
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
      ## Milvus Logs Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.
      ## ReadWriteMany access mode required for milvus cluster.
      ##
      storageClass: gp3
      accessModes: ReadWriteMany
      size: 100Gi
      subPath: ""
```

After cluster was up, checked the queryNode but `/milvus/configs/milvus.yaml` showed `log.file.rootPath` as the empty string “”.
 

### Expected Behavior

Expect to see `logs` folder auto-created under the specified path `log.file.rootPath`.

**Comment by yanliang567** [comment]
@LoveEachDay Could you please take a look at this issue?

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
@yuliu-eric This is because we don't expose the `log.file.rootPath` configuration in the helm chart values.
You can find the configuration under `charts/milvus/templates/config.tpl` at [here](https://github.com/milvus-io/milvus-helm/blob/98e3f26d590cc1394ec0ebfdab1ce8170ce9dd7a/charts/milvus/templates/config.tpl#L258):
```
log:
  level: {{ .Values.log.level }}
  file:
{{- if .Values.log.persistence.enabled }}
    rootPath: "{{ .Values.log.persistence.mountPath }}"
{{- else }}
    rootPath: ""
{{- end }}
    maxSize: {{ .Values.log.file.maxSize }}
    maxAge: {{ .Values.log.file.maxAge }}
    maxBackups: {{ .Values.log.file.maxBackups }}
  format: {{ .Values.log.format }}
```

If you want to set up a log file output, you must enable `log.persistence.enabled`.

**Comment by yuliu-eric** [comment]
Thank you @LoveEachDay for the suggestion!

I've tried to uninstall the existing cluster and install it again, but one of the etcd node is kept in `CrashLoopBackOff` state. How shall I fix it?

Also, I've tried to config `nodeSelector`, `tolerations`, and `affinity` (see below) but didn't seem to work. Can you share the examples for them?

Thank you so much for your support!

```
nodeSelector:
  nodegroup: general

tolerations:
  - key: nodegroup
    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - ap-northeast-1b
```

**Comment by LoveEachDay** [comment]
```
I've tried to uninstall the existing cluster and install it again, but one of the etcd node is kept in CrashLoopBackOff state 
w/ the following errors Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax. How shall I fix it?
```
This is a known bitnami/etcd issue. You'd manually remove the `member_id` file under the `/bitnami/etcd/data/` directory.

```
Also, I've tried to config nodeSelector, tolerations, and affinity (see below) but didn't seem to work, expecting ID in Hex). 
Can you share the examples for them?
```
The `nodeSelector` , `tolerations`, and `affinity` only sets for milvus components, which does not affect the settings for dependencies such as etcd, pulsar, minio. 

If you set the `nodeSelector` for `etcd`, you need put this setting under the `etcd` section.

**Comment by yuliu-eric** [comment]
> This is a known bitnami/etcd issue. You'd manually remove the member_id file under the /bitnami/etcd/data/ directory.

I tried `kubectl exec -it -n sn-feature milvus2-ai-infra-dev-etcd-0 -- /bin/bash` but got the following error: `error: unable to upgrade connection: container not found ("etcd")`

**Comment by LoveEachDay** [comment]
> > This is a known bitnami/etcd issue. You'd manually remove the member_id file under the /bitnami/etcd/data/ directory.
> 
> I tried `kubectl exec -it -n sn-feature milvus2-ai-infra-dev-etcd-0 -- /bin/bash` but got the following error: `error: unable to upgrade connection: container not found ("etcd")`

This is because your etcd pod is crashing. Could you directly access the pvc that milvus2-ai-infra-dev-etcd-0 use ?

**Comment by yuliu-eric** [comment]
> Could you directly access the pvc that milvus2-ai-infra-dev-etcd-0 use ?

Haven't done that before, would you please share the instructions/cmd/examples?

**Comment by LoveEachDay** [comment]
> > Could you directly access the pvc that milvus2-ai-infra-dev-etcd-0 use ?
> 
> Haven't done that before, would you please share the instructions/cmd/examples? I can find and describe the pvc for that etcd, but now sure how to access it.

You'd better contact the kubernetes administrators which setup the storageclass. We have no idea of what kind of storage you use.

And due to this issue, we try to fix the etcd issue and we build a docker image: `milvusdb/etcd:3.5.0-debian-10-r117`, you can try to use this image by setting like this:
```
etcd:
    image:
      repository: milvusdb/etcd
      tag: "3.5.0-debian-10-r117"
```

**Comment by yuliu-eric** [comment]
Thanks, let me try out the new etcd docker image.

**Comment by LoveEachDay** [comment]
```
Caused by: java.lang.ClassNotFoundException: "-Xms1024m
```
This is the config error for pulsar zookeeper. Please keep the same format like this:
```
  zookeeper:
    resources:
      requests:
        memory: 1024Mi
        cpu: 0.3
    configData:
      PULSAR_MEM: >
        -Xms1024m
        -Xmx1024m
      PULSAR_GC: >
         -Dcom.sun.management.jmxremote
         -Djute.maxbuffer=10485760
         -XX:+ParallelRefProcEnabled
         -XX:+UnlockExperimentalVMOptions
         -XX:+DoEscapeAnalysis
         -XX:+DisableExplicitGC
         -XX:+PerfDisableSharedMem
         -Dzookeeper.forceSync=no
```

**Comment by yuliu-eric** [comment]
what about other `configData` under `pulsar`? 

also, update `BOOKIE_MEM` to `BOOKIE_MEM` and `BOOKIE_GC`?

saw similar error on pulsar proxy node: `Error: Could not find or load main class "-Xms2048m`

**Comment by yuliu-eric** [comment]
After applied above changes, got following errors on rootnode `running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition` with `log.persistence.enabled` setting to true;

Then set `log.persistence.enabled` back to false, got following errors on datacoord:
```
time="2022-05-31T15:32:33Z" level=error msg="[Failed to create consumer]" consumerID=20 error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Bookie handle is not available" name=zbyik subscription=by-dev-dataCoord topic="persistent://public/default/by-dev-datacoord-timetick-channel"
panic: Failed to create consumer by-dev-datacoord-timetick-channel, error = All attempts results:
attempt #1:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Bookie handle is not available
```

**Comment by JackLCL** [comment]
> 

It will be good to create a separate issue to track the etcd and zookeeper-related problems.

**Comment by JackLCL** [comment]
> After applied above changes, got following errors on rootnode `running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition` with `log.persistence.enabled` setting to true;
> 
> Then set `log.persistence.enabled` back to false, got following errors on datacoord:
> 
> ```
> time="2022-05-31T15:32:33Z" level=error msg="[Failed to create consumer]" consumerID=20 error="server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Bookie handle is not available" name=zbyik subscription=by-dev-dataCoord topic="persistent://public/default/by-dev-datacoord-timetick-channel"
> panic: Failed to create consumer by-dev-datacoord-timetick-channel, error = All attempts results:
> attempt #1:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Bookie handle is not available
> ```
It will be good to create a separate issue to track the etcd and zookeeper-related problems.

**Comment by LoveEachDay** [comment]
Another question to note is that:
```
"{"level":"warn","ts":"2022-06-02T02:57:30.296Z","caller":"rafthttp/http.go:500","msg":"request cluster ID mismatch","local-member-id":"3a40c4043d8c5dc6","local-member-cluster-id":"f5ab8dc0d0e31730","local-member-server-version":"3.5.0","local-member-server-minimum-cluster-version":"3.0.0","remote-peer-server-name":"64de156f740416f0","remote-peer-server-version":"3.5.0","remote-peer-server-minimum-cluster-version":"3.0.0","remote-peer-cluster-id":"d580a929db73018b"}"
```
When etcd member is starting, it will calculate the `cluster_id` based on the peer urls, we'd filter out the `pod-ip.<svc-name>.svc.cluster.local` dns name, using the `headless` svc name.

This is temporarily fixed using the following image:
```
etcd:
    image:
      repository: garfieldedward/etcd
      tag: "3.5.0-debian-10-r115"
```

After the performance test and stability test are all passed, we'll push this image to `milvusdb/etcd` repository.
