### ISSUE TITLE
[Bug]: [benchmark][cluster] Milvus is reinstalled with the same PVC, and the RT of query and search become larger

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#17339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220531-d920e5c9
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:
install: benchmark-tag-no-clean-7xxfw

reinstall: benchmark-restart-server-m5hsx

test yaml:
install：
client-configmap:client-random-locust-100m-ddl-r8-w2-1h
server-configmap:server-cluster-8c64m
reinstall:
client-configmap:client-random-locust-100m-ddl-r8-w2-concurrent
server-configmap:server-cluster-8c64m

server:
install:
```
NAME                                                              READY   STATUS        RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-no-clean-7xxfw-1-etcd-0                             1/1     Running       0          6m7s    10.97.16.237   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-etcd-1                             1/1     Running       0          6m7s    10.97.17.234   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-etcd-2                             1/1     Running       0          6m5s    10.97.16.241   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-datacoord-7bdc485cb7jbk4z   1/1     Running       1          6m7s    10.97.10.13    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-datanode-5f77c6cc8-6q9vt    1/1     Running       0          6m7s    10.97.11.69    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-indexcoord-79d46dbcbx5ljz   1/1     Running       1          6m7s    10.97.11.68    qa-node009.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-indexnode-7747646cd5lghhk   1/1     Running       0          6m7s    10.97.17.227   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-proxy-d6884d6-4cfwq         1/1     Running       1          6m7s    10.97.19.102   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-querycoord-6b555cb65wknzk   1/1     Running       0          6m7s    10.97.5.48     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-querynode-b7bd9cfff-kgwnv   1/1     Running       0          6m7s    10.97.20.185   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-rootcoord-55865dffbcsdjjh   1/1     Running       0          6m7s    10.97.5.47     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-0                            1/1     Running       0          6m7s    10.97.19.107   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-1                            1/1     Running       0          6m7s    10.97.19.108   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-2                            1/1     Running       0          6m7s    10.97.12.171   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-3                            1/1     Running       0          6m7s    10.97.12.173   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-0                    1/1     Running       0          6m7s    10.97.19.109   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-1                    1/1     Running       0          6m5s    10.97.12.174   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-2                    1/1     Running       0          6m4s    10.97.16.242   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-init-6wg22           0/1     Completed     0          6m7s    10.97.17.226   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-broker-0                    1/1     Running       0          6m7s    10.97.19.101   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-proxy-0                     1/1     Running       0          6m7s    10.97.5.46     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-pulsar-init-djhlk           0/1     Completed     0          6m7s    10.97.17.225   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-recovery-0                  1/1     Running       0          6m7s    10.97.12.167   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-0                 1/1     Running       0          6m7s    10.97.20.186   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-1                 1/1     Running       0          5m32s   10.97.5.50     qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-2                 1/1     Running       0          4m45s   10.97.5.54     qa-node003.zilliz.local   <none>           <none>
```

reinstall:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-no-clean-7xxfw-1-etcd-0                             1/1     Running     2          2m39s   10.97.16.163   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-etcd-1                             1/1     Running     0          2m39s   10.97.17.197   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-etcd-2                             1/1     Running     2          2m39s   10.97.16.168   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-datacoord-7bdc485cb7cg29h   1/1     Running     0          2m39s   10.97.5.185    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-datanode-5f77c6cc8-cnf6n    1/1     Running     0          2m39s   10.97.20.223   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-indexcoord-79d46dbcbnj6cs   1/1     Running     0          2m39s   10.97.5.186    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-indexnode-7747646cd5vqw6l   1/1     Running     0          2m39s   10.97.11.138   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-proxy-d6884d6-x9qdd         1/1     Running     0          2m39s   10.97.5.188    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-querycoord-6b555cb65vqxst   1/1     Running     0          2m39s   10.97.5.182    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-querynode-b7bd9cfff-sd764   1/1     Running     0          2m39s   10.97.19.196   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-milvus-rootcoord-55865dffbcmbqlz   1/1     Running     0          2m39s   10.97.5.187    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-0                            1/1     Running     0          2m39s   10.97.19.198   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-1                            1/1     Running     0          2m38s   10.97.19.197   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-2                            1/1     Running     0          2m38s   10.97.12.141   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-minio-3                            1/1     Running     0          2m37s   10.97.12.140   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-0                    1/1     Running     0          2m39s   10.97.19.195   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-1                    1/1     Running     0          2m39s   10.97.12.139   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-2                    1/1     Running     0          2m39s   10.97.16.165   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-bookie-init-52484           0/1     Completed   0          2m39s   10.97.5.184    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-broker-0                    1/1     Running     0          2m39s   10.97.5.189    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-proxy-0                     1/1     Running     0          2m39s   10.97.12.137   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-pulsar-init-wgksv           0/1     Completed   0          2m39s   10.97.12.138   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-recovery-0                  1/1     Running     0          2m39s   10.97.5.183    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-0                 1/1     Running     0          2m39s   10.97.20.224   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-1                 1/1     Running     0          2m18s   10.97.5.190    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-7xxfw-1-pulsar-zookeeper-2                 1/1     Running     0          107s    10.97.5.191    qa-node003.zilliz.local   <none>           <none>
```

client pod:
install: benchmark-tag-no-clean-7xxfw-2133504118

reinstall: benchmark-restart-server-m5hsx-3127541683

client monitor:
<img width="1385" alt="截屏2022-06-02 11 46 32" src="https://user-images.githubusercontent.com/26307815/171548985-f6d3e8fc-87b7-460c-a767-92f0aa5e98df.png">

![8nEltvvATz](https://user-images.githubusercontent.com/26307815/171549000-ea1556e1-95ab-4156-9178-6d98605c2f9d.png)

### Steps To Reproduce

```markdown
1、install Milvus Cluster
2、insert 100 million vector and locust concurrent: query<-search, load, get<-query, scene_test
3、after concurrent testing, wait for a while
4、reinstall Milvus Cluster with the same PVC
5、Concurrent query and search based on the previous collection of 100 million data

Step 5 takes longer to query and search than Step 2
```

### Anything else?

client-random-locust-100m-ddl-r8-w2-1h:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 1h
```
client-random-locust-100m-ddl-r8-w2-concurrent:
```
    locust_random_concurrent_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 1
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: get
                weight: 1
                params:
                  ids_length: 10
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 3600
```
