### ISSUE TITLE
[Bug]: [benchmark][50million] RT of search lager than before

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#17637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220618-50cecc65
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev78
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:benchmark-cron-1655568000

test yaml:
client-configmap:client-search-sift50m-ivf-flat-2048,instanceId:6,server-configmap:server-single-16c64m

server:
```
NAME                                                             READY   STATUS             RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1655568000-6-etcd-0                               1/1     Running            0          6h8m   10.97.16.18    qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1655568000-6-milvus-standalone-6ccbb8c86b-t5cp5   1/1     Running            0          6h8m   10.97.20.16    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1655568000-6-minio-7689cb78b8-dcljj               1/1     Running            0          6h8m   10.97.12.16    qa-node015.zilliz.local   <none>           <none>
```

client pod: benchmark-cron-1655568000-3132445966

client log:
<img width="1504" alt="截屏2022-06-20 10 37 14" src="https://user-images.githubusercontent.com/26307815/174515435-5dd969b7-aa87-4809-af55-2a60db49c148.png">

2022-5-11, log:
<img width="712" alt="截屏2022-06-20 10 37 51" src="https://user-images.githubusercontent.com/26307815/174515494-5cd47aed-7071-4598-b9a1-412994c2679b.png">

### Anything else?

client-search-sift50m-ivf-flat-2048:
```
    insert_search_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
          run_count: 30
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 500, 1000, 1200]
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32
```
