### ISSUE TITLE
[Bug]: drop collection do not release disk 

### ISSUE THREAD

**Issue by Sivannnnnn** [milvus-io/milvus#18288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvusdb/week-build: master-20220711-1DA970AF was changed. This time, there was no error in drop collection. However, the disk is not released. The official website says that the disk will be cleaned up after a day. Therefore, the disk space is still not released after a day.
My collection has 100 million pieces of data, each of which is a 128-dimensional vector

`
root@compute3:/data/milvus/volumes# du -sh ./*
406M	./etcd
150G	./milvus
285G	./minio
root@compute3:/data/milvus/volumes# cd ..
root@compute3:/data/milvus# docker ps
CONTAINER ID   IMAGE                                            COMMAND                  CREATED        STATUS                  PORTS                                           NAMES
ffbaa1d5e6ad   milvusdb/weekly-build:master-20220711-1da970af   "/tini -- milvus run…"   30 hours ago   Up 30 hours             0.0.0.0:19530->19530/tcp, :::19530->19530/tcp   milvus-standalone
25fa02727cab   quay.io/coreos/etcd:v3.5.0                       "etcd -advertise-cli…"   30 hours ago   Up 30 hours             2379-2380/tcp                                   milvus-etcd
2afe76d5cfe2   minio/minio:RELEASE.2020-12-03T00-03-10Z         "/usr/bin/docker-ent…"   30 hours ago   Up 30 hours (healthy)   9000/tcp                                        milvus-minio
`

**Comment by yanliang567** [comment]
@Sivannnnnn thank you for the issue. Could you please help to check the following configurations in milvus.yaml:
![image](https://user-images.githubusercontent.com/82361606/179328775-2700fd54-c07f-4e22-b907-be531053d7fe.png)

/assign @Sivannnnnn 
/unassign

**Comment by Sivannnnnn** [comment]
yes，My configuration is the same as yours.
I cannot delete a collection with a large amount of data using V2.0.2. I can delete it using this version, but the disk space is not released. What should I do? Also why milvus storage takes up so much disk space, I only store two fields, 400 million 128-dimensional float vectors, disk takes up 460GB?
In addition, I have built a new stand-alone MILvus with V2.0.2. Three days have passed, but the logs are not cleared. Why do the disks occupy so much? Is there any way to adjust it
![image](https://user-images.githubusercontent.com/46392469/179440488-1a9f30a8-bd44-434a-be29-e9a24e526be6.png)

**Comment by Sivannnnnn** [comment]
@yanliang567

**Comment by Sivannnnnn** [comment]
and in my environment, dataCoord.enableGarbageCollection = false，
![image](https://user-images.githubusercontent.com/46392469/179451147-765a1561-a0a2-4818-a94c-742fe34df8f2.png)

**Comment by LoveEachDay** [comment]
@Sivannnnnn We've enabled data compression for vector data in minio (#15840) which brings 3.3 compression ratio. Here's our test with 100 million data (128 dimension) with index type `ivfsq8` , the data usage in minio is about `26GB` .
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/1573213/179454276-dc7ebbfb-0f61-4416-a3e2-58c11c15fd71.png">

From your case, seems like you deploy a milvus standalone using `docker-compose`. I suspect that you use the same volume for multiple deployments, so the data usage is huge.

We can make a simple calculation: 400m*128*4/1024/1024/1024 = 200GB, and the compression ratio is 3.3, so the `insert_log` directory under `minio/milvus-bucket/file` is about 200/3.3 = 60GB. 

I suggest that you create a volume directory with `docker-compose.yaml` , startup a new milvus standalone, and check out the data usage.

And when you drop a collection, the data usage in minio will be decreased when the datacoord gc compaction happens. The default config is `gc.dropTolerance` is one day. 

And for the `milvus` directory which stores the data for `rocksmq`, you can change the following configuration in `milvus.yaml`:
```
rocksmq: # please adjust in embedded Milvus: /tmp/milvus/rdb_data
  path: /var/lib/milvus/rdb_data # The path where the message is stored in rocksmq
  rocksmqPageSize: 2147483648 # 2 GB, 2 * 1024 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
  retentionTimeInMinutes: 10080 # 7 days, 7 * 24 * 60 minutes, The retention time of the message in rocksmq.
  retentionSizeInMB: 8192 # 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
  lrucacheratio:  0.06 # rocksdb cache memory ratio
```

change the `retentionTimeInMinutes` to 1 days to decrease the `milvus` data usage.

**Comment by LoveEachDay** [comment]
> and in my environment, dataCoord.enableGarbageCollection = false， ![image](https://user-images.githubusercontent.com/46392469/179451147-765a1561-a0a2-4818-a94c-742fe34df8f2.png)

You should enable `enableGarbageCollection` .

**Comment by Sivannnnnn** [comment]
hello @LoveEachDay ,The configurations I use are the default configurations and have not been modified. In addition, I have many machines and there is no case of multiple deployments using the same volume. How to configure compression, now the disk occupy too much, I am very headache

**Comment by xiaofan-luan** [comment]
enableGarbageCollection and restart should probabaly help on your case, did you try that?

**Comment by LoveEachDay** [comment]
> hello @LoveEachDay ,The configurations I use are the default configurations and have not been modified. In addition, I have many machines and there is no case of multiple deployments using the same volume. How to configure compression, now the disk occupy too much, I am very headache

@Sivannnnnn  Since you're using docker-compose, you can login to the milvus standalone container, then edit the `/milvus/configs/milvus.yaml` to set `enableGarbageCollection` to `true` under the `dataCoord` section, and finally restart the milvus standalone container.  Now you set `enableGarbageCollection`  to `true`, when you drop a collection, the collection data will be released in a day. 

You can also change the `dropTolerance` to a much smaller value like `3600` under `dataCoord.gc` section, to shortify this process.


Data compression for minio is enabled by default, and we don't provide any setting options for this.

To decrease data usage, I suggest that you also change the `retentionTimeInMinutes` to `1440` under `rocksmq` section, which will cleanup the consumed messages in `rocksmq` and decrease the data usage.

**Comment by zhengsonglinge** [comment]
@LoveEachDay @xiaofan-luan 
I re-write 100 million pieces of data to milvus, each piece of data being a 128 dimensional vector and two Int type number.

We can make a simple calculation: 10^8 x 130 x 4 / 2^30 = 48G, if the compression ratio is 3.3, I  expected to get 14.5G of data, but I got 45G, so obviously the data wasn't compressed.

This is my milvus.yaml file:

```yaml
rocksmq:
  # please adjust in embedded Milvus: /tmp/milvus/rdb_data
  path: /var/lib/milvus/rdb_data # The path where the message is stored in rocksmq
  rocksmqPageSize: 1048576 # 2 GB, 2 * 1024 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
  retentionTimeInMinutes: 1 # 7 days, 7 * 24 * 60 minutes, The retention time of the message in rocksmq.
  retentionSizeInMB: 1024 # 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
  lrucacheratio:  0.06 # rocksdb cache memory ratio


dataCoord:
  address: localhost
  port: 13333
  enableCompaction: true # Enable data segment compression
  #enableGarbageCollection: false
  enableGarbageCollection: true

  segment:
    maxSize: 512 # Maximum size of a segment in MB
    sealProportion: 0.25 # It's the minimum proportion for a segment which can be sealed
    assignmentExpiration: 2000 # The time of the assignment expiration in ms
    maxLife: 86400 # The max lifetime of segment in seconds, 24*60*60

  compaction:
    enableAutoCompaction: true

  gc:
    interval: 10 # gc interval in seconds
    missingTolerance: 10 # file meta missing tolerance duration in seconds, 60*24
    dropTolerance: 10 # file belongs to dropped entity tolerance duration in seconds, 60*24
```

After restart the milvus-standalone with the command `docker restart dockerID`，I found that the minio directory size  from 80G reduced to 45G. 

When I want to compress data manually, I got the following

```
collection.compact()
while(1==1):
	time.sleep(5)
	print(collection.get_compaction_state())

CompactionState
 - compaction id: 434759724216290625
 - State: Completed
 - executing plan number: 0
 - timeout plan number: 133
 - complete plan number: 65
```

And the data is not be compacted. What should I do.

One more question, I have set retentionTimeInMinutes: 1, but milvus/rdb_data is not deleted, is there any way to delete the data after it has been entered into the database?
