### ISSUE TITLE
Milvus 0.7.0  crashed

### ISSUE THREAD

**Issue by chenrulongmaster** [milvus-io/milvus#1866]
**Describe the bug**
I setup a milvus server from docker image 0.7.0 version. After running around 30hours, it crashed and give below logs.

**Steps/Code to reproduce behavior**
May not be reproduced.

**Environment details**
- Nvidia RTX 2080Ti x 4
- Docker
- Milvus version 0.7.0
- Milvus configuration 
```
db_config:
  backend_url: mysql://root:123456@xxxx:3306/milvus
  preload_table:
  auto_flush_interval: 1

cache_config:
  cpu_cache_capacity: 20
  insert_buffer_size: 3
  cache_insert_data: true

engine_config:
  use_blas_threshold: 1000
  gpu_search_threshold: 1

gpu_resource_config:
  enable: true
  cache_capacity: 8
  search_resources:
    - GPU3
  build_index_resources:
    - GPU3

```

**Additional context**
docker logs
```
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>::copyFrom(faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>&, cudaStream_t) [with T = float; int Dim = 2; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits; cudaStream_t = CUstream_st*] at ./faiss/gpu/utils/Tensor-inl.cuh:154; details: CUDA error 719 unspecified launch failure
./start_server.sh: line 3:     7 Aborted                 (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf
```

milvus error logs:
```
2020-04-03 15:35:38,260 | ERROR | default | [WRAPPER] Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: scan failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
2020-04-03 15:35:38,260 | ERROR | default | [ENGINE] Search error:Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: scan failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
```
