### ISSUE TITLE
[Bug]: milvus-etcd usage spikes and makes the container go OOM

### ISSUE THREAD

**Issue by Uzay-G** [milvus-io/milvus#18707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8 GB ram
- GPU: N/A
- Others:
```

### Current Behavior

Since the past few days, when I launch milvus through docker-compose, the memory usage of the `milvus-etcd` container slowly spikes until it goes above the memory usage limit / container in docker, which for my system is ~7.6 GB. I have about ~80k vectors in milvus.

Then it exits with code 137 and I can't connect to milvus.

I've attached the etcdlogs.
[etcdlogs.txt](https://github.com/milvus-io/milvus/files/9368200/etcdlogs.txt)

### Expected Behavior

I should be able to connect to milvus normally.

This is a continuation of https://github.com/milvus-io/milvus/issues/17436#issuecomment-1217691162.

**Comment by LoveEachDay** [comment]
@Uzay-G Did you keep the default etcd config in the `docker-compose.yaml`? 
Here a revised docker-compose yaml which enabled pprof, so that you can check etcd memory usage:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_ENABLE_PPROF=true
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    ports:
    - "2379:2379"
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.1.1
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```

Now you can access `localhost:2379/metrics` to check the etcd memory usage `process_resident_memory_bytes`, and etcd db size `etcd_mvcc_db_total_size_in_bytes`.

And you can check etcd profile at `localhost:2379/debug/pprof`, you can use `pprof` to profile etcd heap and show which part takes up memory.

If `Raft log entry` takes up many memory usage, you can add the following env to etcd:
```
ETCD_SNAPSHOT_COUNT=50000
```
