### ISSUE TITLE
[Bug]: Logs copy issue in 2.1

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#19015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Script `export-milvus-log.sh` only copy very few logs. Please see config details below:

Milvus git repo version

- commit b427450593245f1ce49e9df2d1d2700be581e75c (HEAD -> dev, tag: v2.1.0-testing-20220804, origin/master, origin/HEAD, master)

Cmd to copy logs

-  ./deployments/export-log/export-milvus-log.sh -i <milvus-release> -n <k8s-name-space> -p <output-logs-path>

Milvus-helm git repo version

- commit 74a99498567372b5e299e075d7e8844ab6c7b29a (HEAD -> 2.1-dev, tag: milvus-3.1.1)

Cmd to deploy Milvus 

- helm install <milvus-release> milvus/milvus -f ./charts/milvus/values.yaml -n <k8s-name-space>

Log config:
```
log:
  level: "debug"
  file:
    maxSize: 300    # MB
    maxAge: 10    # day
    maxBackups: 20
  format: "text"    # text/json

  persistence:
    mountPath: "/milvus/logs"
    ## If true, create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
      ## Milvus Logs Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.
      ## ReadWriteMany access mode required for milvus cluster.
      ##
      storageClass: efs
      accessModes: ReadWriteMany
      size: 100Gi
      subPath: ""
```
