### ISSUE TITLE
[Bug]: Milvus V2.1.0 benchmark search latency 400ms+

### ISSUE THREAD

**Issue by cndpzc** [milvus-io/milvus#19098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.0
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We did benchmark with following params.

```
row_count: 1000000
dim: 128
index:
  index_type: IVF_FLAT
  metric_type: IP
  nlist: 2048
search:
  nq: 1
  topk: 1
  nprobe: 16
  concurrency: 50
```
We got a result of `460 QPS` with `470ms latency`
<img width="1794" alt="image" src="https://user-images.githubusercontent.com/3941929/189028873-adb743f9-8e10-45f8-bcf0-7d2bf71193c2.png">

### Expected Behavior

What we expect:

- QPS > 2000
- Latency 
  - 35ms for nq=100
  - 10ms for nq=1

### Steps To Reproduce

```markdown
See the files below.

1. Setup clusters with values.txt
2. Run the script with `python perf_test.py -c benchmark.yaml`
```

### Anything else?

Env 
[values.txt](https://github.com/milvus-io/milvus/files/9523334/values.txt)

Script 
[perf_test.zip](https://github.com/milvus-io/milvus/files/9523422/perf_test.zip)
