### ISSUE TITLE
[Bug]: ChunkManager path is not set correctly

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#19138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Some of the code using Params.LocalStorageCfg.Path, while others using params.MinioCfg.Address.

This could cause garbage collector try to gc the wrong minio path, and garbage collector won't work as expect

### Expected Behavior

if params.CommonCfg.StorageType == "local"
        cache -> no cache
        persistent -> params.LocalStorageCfg.Path

if  params.CommonCfg.StorageType == "minio"
        cache ->  params.LocalStorageCfg.Path
        persistent -> params.MinioCfg.RootPath

**Comment by camper42** [comment]
our milvus standalone pod use lots of ephemeral storage due to `/tmp/milvus/data/file/insert_log/*`

Does this bug cause this problem? @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> ilvus/d

Hi Camper, I'm assuming you are using embedding milvus?

Embedding milvus use local storage to avoid actual depdency and by default the directory is /tmp/milvus/data/.

If you want to change the storage location, then localStorage.path is config you want to change

**Comment by camper42** [comment]
we use helm to deploy a milvus standalone

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
test   milvus             10              2022-10-08 11:55:20.420016 +0800 CST    deployed        milvus-3.2.6    2.1.4      


```

```
standalone:
  persistence:
    mountPath: "/var/lib/milvus"
    ## If true, alertmanager will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
```

in `/var/lib/milvus':
```
logs
lost+found
rdb_data
rdb_data_meta_kv
```

may I open an issue in milvus-io/milvus-helm ?
