### ISSUE TITLE
[Bug]: [vdc-diskann]Milvus reads and writes data after creating a diskann index, not based on minio.rootPath in milvus.yaml

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:zhagnlu-test-aws-sdk-v-webIden-log-cbeacdae0-20220914
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the uat environment, after Milvus has created the diskANN instance and run the test cases, go to the s3 bucket and look at the data, which is not under the user instance directory

Milvus.yaml
```
log:
  file:
    rootPath: ""
minio:
  rootPath: usr-eiuyb3LWyrbJEsH5EjVzvg/in01-0930d11e0408208
etcd:
  rootPath: in01-0930d11e0408208
```

![20220916-190625](https://user-images.githubusercontent.com/34296482/190625803-ee4e6aec-69f2-479e-b04f-6b0ffd2d7747.jpeg)
