### ISSUE TITLE
[Bug]: External Kafka will not change its security.protocol configuration

### ISSUE THREAD

**Issue by erezweissgloat** [milvus-io/milvus#19379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment mode(standalone or cluster): cluster, with helm
```

### Current Behavior

I use MSK (managed kafka) of AWS, with SASL_SSL and SCRAM-SHA-512.
I deployed the helm:
```
externalKafka:
  enabled: true
  brokerList: x1.kafka.eu-central-1.amazonaws.com:9096, x2.kafka.eu-central-1.amazonaws.com:9096
  securityProtocol: SASL_SSL
  sasl:
    mechanisms: SCRAM-SHA-512
    username: "***"
    password: "***"
```
All the pods return this error:
`FAIL|rdkafka#consumer-1| [thrd:xyz.kafka.eu-central-1.amazonaws.]: xyz.kafka.eu-central-1.amazonaws.com:9096/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY, 4 identical error(s) suppressed)`

I've validated the configmap inside the pods and it's the same.

### Expected Behavior

Milvus suppose to talk with AWS MSK

### Steps To Reproduce

```markdown
Detailed above.
```

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas ?

/assign

**Comment by LoveEachDay** [comment]
@erezweissgloat I've tested that milvus support aws msk with sasl_ssl. Given the above settings in helm chart, it will generate the configmap like this:
```
kafka:
  brokerList: ***:9096,***:9096,***:9096
  securityProtocol: SASL_SSL
  saslMechanisms: SCRAM-SHA-512
  saslUsername: ****
  saslPassword: ****
```
Could you double check this config inside milvus pod. And also check the settings for msk:
1. `Access control methods` -- enable SASL/SCRAM authentication
2. `Encryption` -- enable TLS encryption for traffic between clients and brokers
3.  associate secrets from AWS Secrets Manager follow the directions from here: https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html
