### ISSUE TITLE
[Bug]: [benchmark][standalone][memory]Concurrent create and drop collection, the memory of Milvus Standalone continues to rise

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#19492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220927-67b95597
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouram-2bn8t

client yaml:
client-configmap: client-random-locust-search-filter-100m-ddl-6d
server-configmap: server-single-32c128m

client pod: fouram-2bn8t-3147776694

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-2bn8t-1-etcd-0                                             1/1     Running     0               63m     10.104.4.167   4am-node11   <none>           <none>
fouram-2bn8t-1-milvus-standalone-7f68d6999c-9zfgq                 1/1     Running     0               63m     10.104.5.75    4am-node12   <none>           <none>
fouram-2bn8t-1-minio-5b9f74d47b-6b7ws                             1/1     Running     0               63m     10.104.5.74    4am-node12   <none>           <none>
```

<img width="1580" alt="截屏2022-09-27 下午9 40 27" src="https://user-images.githubusercontent.com/26307815/192542457-e74977d6-58df-4c62-9c9c-964bb6ebb58e.png">

<img width="1634" alt="截屏2022-09-27 下午9 39 35" src="https://user-images.githubusercontent.com/26307815/192542195-88ef98ab-d411-4917-b370-89f36d560435.png">

**Memory increased by 3G in an hour**

### Expected Behavior

Memory usage remains stable without significant fluctuations

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 100000 vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: search, load, query, scene_test 《- during 1h
```

### Anything else?

client-random-locust-search-filter-100m-ddl-6d:
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          other_fields: float1
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 1h
```

```
    def scene_test(self, collection_name=None, vectors=None, ids=None, index_type="ivf_sq8",
                   index_param={'nlist': 2048}, metric_type="l2"):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] {0} start create index:{1}, index_param:{2}, metric_type:{3}".format(collection_name,
                                                                                                        index_type,
                                                                                                        index_param,
                                                                                                        metric_type))
        self.create_index(field_name='float_vector', index_type=index_type, metric_type=metric_type,
                          collection_name=collection_name, index_param=index_param)
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```
