### ISSUE TITLE
[Bug]: Size of `rdb_data` folder keeps increasing

### ISSUE THREAD

**Issue by devennavani** [milvus-io/milvus#19574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: PVC for standalone pod is 50GB
- GPU: 
- Others:
```

### Current Behavior

The size of the `rdb_data` folder keeps increasing, despite the following `rocksmq` configuration:

```
rocksmq:
    retentionTimeInMinutes: 60 ## 1 hour
    retentionSizeInMB: 500
    rocksmqPageSize: "2147483648" ## 2 GB
    lrucacheratio: 0.06 ## rocksdb cache memory ratio
```

It ultimately hits 50GB, the size of the PVC for the standalone pod, and causes the standalone pod go into CrashLoopBackoff.

### Expected Behavior

Given the `rocksmq` configuration above, I would expect `rdb_data` folder to be cleared every hour.

### Steps To Reproduce

```markdown
Deploy Milvus standalone to K8s via Helm chart, with following values.yaml:

https://gist.github.com/devennavani/3629603122333e8a245a1f564d691838
```

### Anything else?

milvus PV usage:

![Screen Shot 2022-09-29 at 12 52 49 PM](https://user-images.githubusercontent.com/4031146/193128743-b3bb74ce-a7c1-4e81-8de0-71c5d5b80f04.png)

**Comment by LoveEachDay** [comment]
@devennavani This is known issue. We have problems for confirming the messages are consumed which won't trigger retention for rocksmq. So it's no use to decrease the `rocksmq. retentionTimeInMinutes`.

Our developer is investigating this issue and the fix will coming soon.

If all the vector data are searchable, you may delete the directory `rdb_data` and `rdb_data_meta_kv`, and restart milvus standalone.

**Comment by devennavani** [comment]
@LoveEachDay Thanks for the response!

Is this only an issue with using rocksmq, or is it also an issue with using Pulsar and Kafka (in Milvus standalone).

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
I thought aoiasd is working on the fix~

**Comment by heph** [comment]
Hate to be a pest, but @aoiasd could you confirm this issue has been correctly assigned, and if so what is its priority? The current workaround is fairly disruptive in production to the point we're considering Kafka, and I'd really hate to have to bring zookeeper into our stack 😆

**Comment by aoiasd** [comment]
> Hate to be a pest, but @aoiasd could you confirm this issue has been correctly assigned, and if so what is its priority? The current workaround is fairly disruptive in production to the point we're considering Kafka, and I'd really hate to have to bring zookeeper into our stack 😆

sry, we had a week's holiday because of the festival, and now it is over. I will work for this immediately.

**Comment by LoveEachDay** [comment]
> @LoveEachDay Thanks for the response! I'm looking forward to the fix :)
> 
> Is this only an issue with using rocksmq, or is it also an issue with using Pulsar and Kafka (in Milvus standalone)?

This is only an issue with rocksmq (in milvus standalone).

**Comment by yanliang567** [comment]
@LoveEachDay any updates

**Comment by ErezWeiss** [comment]
Same here with external kafka.
Is there any way to create a retention?

**Comment by LoveEachDay** [comment]
@ErezWeiss You can set the `log.retention.hours` or `log.retention.bytes` for kafka brokers. And it's not a config controlled by milvus.

**Comment by xiaofan-luan** [comment]
Should be fixed on recent 2.2 release, check it

**Comment by guillaumebu** [comment]
Using v2.2.2 in standalone mode and this seems to still be an issue.
I am using the standalone docker-compose.yml config file as is.

As soon as I create a Collection with pymilvus I observe a constant increase in rdb_data folder files.
As long as I don't have any collection the problem does not exist. I don't even insert anything, just creating the collection causes the problem.
The data increases then by approx 3 Mb per minute.

Minimal code on pymilvus to reproduce
```python3
from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
)
import numpy as np
connections.connect("default", host="localhost", port="19530")

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="vect", dtype=DataType.FLOAT_VECTOR, dim=100)
]
schema = CollectionSchema(fields)
mlv_vectors = Collection("test", schema)
```

**Comment by xiaofan-luan** [comment]
> Using v2.2.2 in standalone mode and this seems to still be an issue. I am using the standalone docker-compose.yml config file as is.
> 
> As soon as I create a Collection with pymilvus I observe a constant increase in rdb_data folder files. As long as I don't have any collection the problem does not exist. I don't even insert anything, just creating the collection causes the problem. The data increases then by approx 3 Mb per minute.
> 
> Minimal code on pymilvus to reproduce
> 
> ```python
> from pymilvus import (
>     connections,
>     utility,
>     FieldSchema,
>     CollectionSchema,
>     DataType,
>     Collection,
> )
> connections.connect("default", host="localhost", port="19530")
> 
> fields = [
>     FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
>     FieldSchema(name="vect", dtype=DataType.FLOAT_VECTOR, dim=100)
> ]
> schema = CollectionSchema(fields)
> mlv_vectors = Collection("test", schema)
> ```

the rdb data will be purged if it's more than 2GB * 256 size or 5 days after consume.
you can change rocksdb.retentionTimeInMinutes to 1 day if your disk space is limited but we don't recommend disk retention time to be shorter than one day

**Comment by guader** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/10419703/221513507-f19f35ee-4909-4fc2-b9f6-6dd79fc447fe.png">
Disk usage of `rdb_data` above, timestamp for x and size for y.
`retentionTimeInMinutes` has been set to 1440 for milvus version 2.2.3 running with `standalone` mode.
Indeed the usage of disk has been released at every certain time, but it's still increasing on the whole.

Now we can do nothing about it, FYI.

**Comment by xiaofan-luan** [comment]
seems that the cleanup is not working.
Might be related to page size issue. 
One way u can do is to change rocksmq.rocksmqPageSize to 256M and see if it works.

@aoiasd can we change the rocksmq pages zie to by default 256M?

**Comment by xiaofan-luan** [comment]
the disk size should be limit to 256 M * 256(channel number)

**Comment by PeterPilley** [comment]
Hi is there any update on this, I cant use Milvus as a result of this issue. rdb_data is now 52GB

**Comment by aoiasd** [comment]
> Hi is there any update on this, I cant use Milvus as a result of this issue. rdb_data is now 52GB

rdb_data retention was related with rocksmqPageSize. You could set it to 256M (2G default), if you want trigger retention with less disk use.

**Comment by xiaofan-luan** [comment]
already 256M. 
I've changed it to 64M for latest versions

**Comment by ponponon** [comment]
milvus2.2.2 standalone 

rdb_data keeps getting bigger


Can the stuff under rdb_data be deleted? Why does this rdb_data keep getting bigger and bigger without any new vectors being entered?

```yaml
version: "3.5"

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: always
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "standalone"]
    restart: always
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  zilliz_attu:
    container_name: zilliz_attu
    image: zilliz/attu:v2.2.4
    restart: always
    environment:
      HOST_URL: http://172.16.21.151:8000
      MILVUS_URL: 172.16.21.151:19530
    ports:
      - "8000:3000"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

networks:
  default:
    name: milvus
```



<img width="557" alt="图片" src="https://user-images.githubusercontent.com/38725104/234452350-8a681016-f741-434f-8bf7-6db98b428304.png">


<img width="528" alt="图片" src="https://user-images.githubusercontent.com/38725104/234452346-66408000-be57-4440-97c2-e4c2458fd00a.png">


<img width="603" alt="图片" src="https://user-images.githubusercontent.com/38725104/234452381-18c08159-a045-4114-a61f-2e6d3e37f79e.png">

**Comment by thomastraum** [comment]
I am having the same problem in milvus standalone launched with Docker compose

**Comment by xiaofan-luan** [comment]
@aoiasd pls take a look on it?

**Comment by aoiasd** [comment]
> milvus2.2.2 standalone
> 
> rdb_data keeps getting bigger
> 
> Can the stuff under rdb_data be deleted? Why does this rdb_data keep getting bigger and bigger without any new vectors being entered?
> 
> ```yaml
> version: "3.5"
> 
> services:
>   etcd:
>     container_name: milvus-etcd
>     image: quay.io/coreos/etcd:v3.5.0
>     restart: always
>     environment:
>       - ETCD_AUTO_COMPACTION_MODE=revision
>       - ETCD_AUTO_COMPACTION_RETENTION=1000
>       - ETCD_QUOTA_BACKEND_BYTES=4294967296
>       - ETCD_SNAPSHOT_COUNT=50000
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
>     command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
>     logging:
>       driver: "json-file"
>       options:
>         max-file: "1"
>         max-size: "50m"
> 
>   minio:
>     container_name: milvus-minio
>     image: minio/minio:RELEASE.2022-03-17T06-34-49Z
>     restart: always
>     environment:
>       MINIO_ACCESS_KEY: minioadmin
>       MINIO_SECRET_KEY: minioadmin
>     ports:
>       - "9001:9001"
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
>     command: minio server /minio_data --console-address ":9001"
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
>     logging:
>       driver: "json-file"
>       options:
>         max-file: "1"
>         max-size: "50m"
> 
>   standalone:
>     container_name: milvus-standalone
>     image: milvusdb/milvus:v2.2.2
>     command: ["milvus", "run", "standalone"]
>     restart: always
>     environment:
>       ETCD_ENDPOINTS: etcd:2379
>       MINIO_ADDRESS: minio:9000
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
>     ports:
>       - "19530:19530"
>       - "9091:9091"
>     depends_on:
>       - "etcd"
>       - "minio"
>     logging:
>       driver: "json-file"
>       options:
>         max-file: "1"
>         max-size: "50m"
> 
>   zilliz_attu:
>     container_name: zilliz_attu
>     image: zilliz/attu:v2.2.4
>     restart: always
>     environment:
>       HOST_URL: http://172.16.21.151:8000
>       MILVUS_URL: 172.16.21.151:19530
>     ports:
>       - "8000:3000"
>     logging:
>       driver: "json-file"
>       options:
>         max-file: "1"
>         max-size: "50m"
> 
> networks:
>   default:
>     name: milvus
> ```
> 
> <img alt="图片" width="557" src="https://user-images.githubusercontent.com/38725104/234452350-8a681016-f741-434f-8bf7-6db98b428304.png">
> 
> <img alt="图片" width="528" src="https://user-images.githubusercontent.com/38725104/234452346-66408000-be57-4440-97c2-e4c2458fd00a.png">
> 
> <img alt="图片" width="603" src="https://user-images.githubusercontent.com/38725104/234452381-18c08159-a045-4114-a61f-2e6d3e37f79e.png">

Rocksmq pagesize was 2G by default at Milvus 2.2.2. Means that every channel will keep 2G data(and 256 channel at most by default), and each collection will use 2 channel default. So 24G was normal, if you use more than 12 Channel, should set pagesize in rocksmq:rocksmqPageSize to 256M or smaller to use less disk.

**Comment by aoiasd** [comment]
> I am having the same problem in milvus standalone launched with Docker compose

Could you tell me your milvus version?  May same question as above.

**Comment by thomastraum** [comment]
I am using `milvusdb/milvus:v2.2.4` 
yhmo in the Slack group helped me out. I deleted everything in the rdb data after flushing the collections, but its filling back up. 

` Usage of /:                       35.8% of 74.79GB` 


I will update docker compose with the settings below and see how it goes
```
rocksmq:
    retentionTimeInMinutes: 60 ## 1 hour
    retentionSizeInMB: 256
    rocksmqPageSize: "2147483648" ## 2 GB
    lrucacheratio: 0.06 ## rocksdb cache memory ratio
    
```
