### ISSUE TITLE
[Bug]: [benchmark][standalone] [DML&DQL] QueryNode restart and search/query raise error:fail to search on all shard leaders, err=fail to Query, QueryNode ID = 13, reason=Query 13 failed, reason context canceled err %!w(<nil>))

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#19731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221012-a561614d
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:fouram-qzfbn

test yaml:
client-configmap: client-random-locust-hnsw-search-filter-insert
server-configmap: server-cluster-8c32m-querynode

server:
```
NAME                                                         READY   STATUS             RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-qzfbn-1-etcd-0                                        1/1     Running            0               8h      10.104.6.209   4am-node13   <none>           <none>
fouram-qzfbn-1-etcd-1                                        1/1     Running            0               8h      10.104.1.92    4am-node10   <none>           <none>
fouram-qzfbn-1-etcd-2                                        1/1     Running            0               8h      10.104.4.97    4am-node11   <none>           <none>
fouram-qzfbn-1-milvus-datacoord-6587746c5f-zd58h             1/1     Running            0               8h      10.104.1.81    4am-node10   <none>           <none>
fouram-qzfbn-1-milvus-datanode-85857fbbdb-gq5mz              1/1     Running            0               8h      10.104.1.86    4am-node10   <none>           <none>
fouram-qzfbn-1-milvus-indexcoord-8699fbd568-b4pxp            1/1     Running            0               8h      10.104.1.84    4am-node10   <none>           <none>
fouram-qzfbn-1-milvus-indexnode-57c787495-hltx4              1/1     Running            0               8h      10.104.1.83    4am-node10   <none>           <none>
fouram-qzfbn-1-milvus-proxy-c66f6bb44-s8mn9                  1/1     Running            0               8h      10.104.4.92    4am-node11   <none>           <none>
fouram-qzfbn-1-milvus-querycoord-6845c9d89f-f59mm            1/1     Running            0               8h      10.104.1.79    4am-node10   <none>           <none>
fouram-qzfbn-1-milvus-querynode-5d5b6b8bcc-47zvj             1/1     Running            4 (4h13m ago)   8h      10.104.6.205   4am-node13   <none>           <none>
fouram-qzfbn-1-milvus-querynode-5d5b6b8bcc-dm5ln             1/1     Running            0               8h      10.104.5.5     4am-node12   <none>           <none>
fouram-qzfbn-1-milvus-rootcoord-679785689c-czdwb             1/1     Running            0               8h      10.104.4.91    4am-node11   <none>           <none>
fouram-qzfbn-1-minio-0                                       1/1     Running            0               8h      10.104.1.93    4am-node10   <none>           <none>
fouram-qzfbn-1-minio-1                                       1/1     Running            0               8h      10.104.4.95    4am-node11   <none>           <none>
fouram-qzfbn-1-minio-2                                       1/1     Running            0               8h      10.104.5.10    4am-node12   <none>           <none>
fouram-qzfbn-1-minio-3                                       1/1     Running            0               8h      10.104.6.212   4am-node13   <none>           <none>
fouram-qzfbn-1-pulsar-bookie-0                               1/1     Running            0               8h      10.104.1.90    4am-node10   <none>           <none>
fouram-qzfbn-1-pulsar-bookie-1                               1/1     Running            0               8h      10.104.5.9     4am-node12   <none>           <none>
fouram-qzfbn-1-pulsar-bookie-2                               1/1     Running            0               8h      10.104.4.100   4am-node11   <none>           <none>
fouram-qzfbn-1-pulsar-bookie-init-gf4q2                      0/1     Completed          0               8h      10.104.1.85    4am-node10   <none>           <none>
fouram-qzfbn-1-pulsar-broker-0                               1/1     Running            0               8h      10.104.4.93    4am-node11   <none>           <none>
fouram-qzfbn-1-pulsar-proxy-0                                1/1     Running            0               8h      10.104.1.82    4am-node10   <none>           <none>
fouram-qzfbn-1-pulsar-pulsar-init-tn46c                      0/1     Completed          0               8h      10.104.6.206   4am-node13   <none>           <none>
fouram-qzfbn-1-pulsar-recovery-0                             1/1     Running            0               8h      10.104.1.80    4am-node10   <none>           <none>
fouram-qzfbn-1-pulsar-zookeeper-0                            1/1     Running            0               8h      10.104.6.210   4am-node13   <none>           <none>
fouram-qzfbn-1-pulsar-zookeeper-1                            1/1     Running            0               8h      10.104.5.12    4am-node12   <none>           <none>
fouram-qzfbn-1-pulsar-zookeeper-2                            1/1     Running            0               8h      10.104.4.102   4am-node11   <none>           <none>
```

client pod: fouram-qzfbn-1913802001
client log:
<img width="1703" alt="截屏2022-10-12 20 11 17" src="https://user-images.githubusercontent.com/26307815/195339271-fc685826-0739-4f4b-9bbf-c90ffaa86518.png">

### Steps To Reproduce

```markdown
1、create collection
2、build index of hnsw
3、insert 100000 vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: search, flush, query, insert 《- raise error
```

### Anything else?

client-random-locust-hnsw-search-filter-insert:
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          other_fields: float1
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 30
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: flush
                weight: 5
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 24h
```
