### ISSUE TITLE
[Bug]: [rate limit] Memory protection is invalid,the milvus server crashed

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus#19750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221012-e6c76aba
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):java-sdk-2.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/103410837/195502697-88156d19-0737-4552-b5bf-baa74be305a6.png)

### Steps To Reproduce

```markdown
@Test(description = "InsertRateTest")
  public void InsertRateTest() {

    String collectionName = "book128";
    int dim = 128;
    FieldType bookIdField =
        FieldType.newBuilder()
            .withName("book_id")
            .withDataType(DataType.Int64)
            .withPrimaryKey(true)
            .withAutoID(false)
            .build();
    FieldType wordCountField =
        FieldType.newBuilder().withName("word_count").withDataType(DataType.Int64).build();
    FieldType bookIntroField =
        FieldType.newBuilder()
            .withName("book_intro")
            .withDataType(DataType.FloatVector)
            .withDimension(dim)
            .build();
    CreateCollectionParam createCollectionParam =
        CreateCollectionParam.newBuilder()
            .withCollectionName(collectionName)
            .withDescription("Test book search")
            .withShardsNum(2)
            .addFieldType(bookIdField)
            .addFieldType(wordCountField)
            .addFieldType(bookIntroField)
            .build();
    R<RpcStatus> collection = milvusClient.createCollection(createCollectionParam);
    log.info(collection.toString());
    // insert data with customized ids
    Random ran = new Random();
    int singleNum = 10000;
    int insertRounds = 1000;
    double insertTotalTime = 0.00;
    for (int r = 0; r < insertRounds; r++) {
      List<Long> book_id_array = new ArrayList<>();
      List<Long> word_count_array = new ArrayList<>();
      List<List<Float>> book_intro_array = new ArrayList<>();
      for (long i = r * singleNum; i < (r + 1) * singleNum; ++i) {
        book_id_array.add(i);
        word_count_array.add(i + 10000);
        List<Float> vector = new ArrayList<>();
        for (int k = 0; k < dim; ++k) {
          vector.add(ran.nextFloat());
        }
        book_intro_array.add(vector);
      }
      List<InsertParam.Field> fields = new ArrayList<>();
      fields.add(new InsertParam.Field(bookIdField.getName(), book_id_array));
      fields.add(new InsertParam.Field(wordCountField.getName(), word_count_array));
      fields.add(new InsertParam.Field(bookIntroField.getName(), book_intro_array));
      InsertParam insertParam =
          InsertParam.newBuilder().withCollectionName(collectionName).withFields(fields).build();
      long startTime = System.currentTimeMillis();
      R<MutationResult> insertR = milvusClient.insert(insertParam);
      log.info(insertR.getStatus().toString());
      long endTime = System.currentTimeMillis();
      insertTotalTime = (endTime - startTime) / 1000.00;
      log.info("------ insert " + singleNum + " entities cost " + insertTotalTime + " seconds");
      try {
        Thread.sleep(2000);
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }
  }
```

### Milvus Log

[log1.log](https://github.com/milvus-io/milvus/files/9770826/log1.log)

**Comment by yongpengli-z** [comment]
![47804e38-6acb-4d96-9105-e331fb881c9b](https://user-images.githubusercontent.com/103410837/195506608-ef460099-9323-4e4b-98a1-4018d9bcdf5a.jpeg)
![a5797523-a861-4f74-b11d-f20422e85d59](https://user-images.githubusercontent.com/103410837/195506621-6fbe3726-efd8-4a1b-aa9a-af2b06368838.jpeg)
When memoryLowWaterLevel < memory usage < memoryHighWaterLevel, the dml rate was not been reduced

**Comment by yongpengli-z** [comment]
[log2.log](https://github.com/milvus-io/milvus/files/9771013/log2.log)
[log3.log](https://github.com/milvus-io/milvus/files/9771014/log3.log)

**Comment by bigsheeper** [comment]
limitWriting:
    forceDeny: false

    ttProtection:
      enabled: true
      maxTimeTickDelay: 30  # seconds

    memProtection:
      enabled: true
      dataNodeMemoryLowWaterLevel: 0.85
      dataNodeMemoryHighWaterLevel: 0.95
      queryNodeMemoryLowWaterLevel: 0.85
      queryNodeMemoryHighWaterLevel: 0.95

**Comment by bigsheeper** [comment]
```yaml
quotaAndLimits:
 enabled: true
 quotaCenterCollectInterval: 3 # seconds

 ddl:
  enabled: true
  collectionRate: 1
  partitionRate: 1

 indexRate:
  enabled: true
  max: 1
 flushRate:
  enabled: true
  max: 1
 compactionRate:
  enabled: true
  max: 1

 dml:
  enabled: true
  insertRate:
   max: 2
  deleteRate:
   max: 1
  bulkLoadRate:
   max: 1

 dql:
  enabled: true
  searchRate:
   max: -1
  queryRate:
   max: 2000

 limitWriting:
  forceDeny: false

  ttProtection:
   enabled: true
   maxTimeTickDelay: 30 # seconds

  memProtection:
   enabled: true
   dataNodeMemoryLowWaterLevel: 0.85
   dataNodeMemoryHighWaterLevel: 0.95
   queryNodeMemoryLowWaterLevel: 0.85
   queryNodeMemoryHighWaterLevel: 0.95

```
