### ISSUE TITLE
[Bug]: [benchmark][diskann]Milvus insert delete, search causes pod restart, search reports error“sift_10w_128_l2 or partition:[] not loaded into memory when query”

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221103-151e0c42
- Deployment mode(standalone or cluster):stanalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-bpmgr-1
server-configmap
server-single-8c32m256d-diskann
client-configmap
client-random-locust-insert-delete-search-filter-diskann

```
fouram-bpmgr-1-etcd-0                                             1/1     Running     0          112s    10.104.1.220   4am-node10
 <none>           <none>
fouram-bpmgr-1-milvus-standalone-66cc45c6cb-7zzkx                 1/1     Running     0          112s    10.104.6.231   4am-node13
 <none>           <none>
fouram-bpmgr-1-minio-77c6c895ff-x9g4t                             1/1     Running     0          112s    10.104.1.219   4am-node10
 <none>           <none>
```

after restart：
```
fouram-bpmgr-1-etcd-0                                            1/1     Running     0               4h30m   10.104.1.220   4am-node
10   <none>           <none>
fouram-bpmgr-1-milvus-standalone-66cc45c6cb-7zzkx                1/1     Running     3 (4h31m ago)   24h     10.104.6.231   4am-node
13   <none>           <none>
fouram-bpmgr-1-minio-77c6c895ff-t9btd                            1/1     Running     0               4h33m   10.104.1.211   4am-node
10   <none>           <none>
```

<img width="1341" alt="截屏2022-11-07 12 05 59" src="https://user-images.githubusercontent.com/34296482/200224383-cd0b4d69-66f3-4e60-a21f-1f97fb254ea0.png">

### Milvus Log

[fouram-bpmgr-1.txt](https://github.com/milvus-io/milvus/files/9948193/fouram-bpmgr-1.txt)

### Anything else?

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: diskann
          index_param: {}
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    search_list: 30
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}"
              -
                type: load
                weight: 2
              -
                type: get
                weight: 5
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
              -
                type: delete
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 24h
```
