### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus insert-delete search causes pod restart, search reports error "Server unavailable. Retry timeout. 60s"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221103-151e0c42
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-4gdzv-1
server-configmap
server-single-8c64m
client-configmap
client-random-locust-insert-delete-search-filter

Before restart：

```

NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE
 NOMINATED NODE   READINESS GATES
fouram-4gdzv-1-etcd-0                                             1/1     Running     0          102s    10.104.9.176   4am-node14
 <none>           <none>
fouram-4gdzv-1-milvus-standalone-7976c898b4-xv9n6                 1/1     Running     0          102s    10.104.1.222   4am-node10
 <none>           <none>
fouram-4gdzv-1-minio-5bd68d8588-snnqx                             1/1     Running     0          102s    10.104.9.175   4am-node14
 <none>           <none>
```

After restart：
```
NAME                                                             READY   STATUS      RESTARTS        AGE     IP             NODE
     NOMINATED NODE   READINESS GATES
fouram-4gdzv-1-etcd-0                                            1/1     Running     0               24h     10.104.9.176   4am-node
14   <none>           <none>
fouram-4gdzv-1-milvus-standalone-7976c898b4-wgwx4                1/1     Running     0               4h27m   10.104.1.210   4am-node
10   <none>           <none>
fouram-4gdzv-1-minio-5bd68d8588-snnqx                            1/1     Running     0               24h     10.104.9.175   4am-node
14   <none>           <none>
```

<img width="1375" alt="截屏2022-11-07 11 31 20" src="https://user-images.githubusercontent.com/34296482/200220838-04502abf-0525-4bcc-a688-6b04567f5585.png">

### Steps To Reproduce

```markdown
1. create a collection
2. build hnsw index
3. insert 10m data
4. build index again
5. insert ，delete ，search， query ，raise an error
```

### Milvus Log

[fouram-4gdzv-1.txt](https://github.com/milvus-io/milvus/files/9948008/fouram-4gdzv-1.txt)

### Anything else?

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}"
              -
                type: load
                weight: 2
              -
                type: get
                weight: 5
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
              -
                type: delete
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 24h
```
