### ISSUE TITLE
[Bug]: [benchmark][cluster]After Milvus updated the image and rebuilt the new index, search reported an error“fail to search on all shard leaders, err=fail to Search, QueryNode ID=33, reason=Search 33 failed”

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221107-57d96a11
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

rebuild hnsw index
server-instance
fouram-tag-no-clean-p4l24-1
server-configmap
server-cluster-8c64m-querynode2
client-configmap
client-random-locust-100m-ddl-rebuild-hnsw-con

```
fouram-tag-no-clean-p4l24-1-etcd-0                                1/1     Running     0             14h     10.104.5.249   4am-node12   <none>           <none>
fouram-tag-no-clean-p4l24-1-etcd-1                                1/1     Running     0             14h     10.104.1.43    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-etcd-2                                1/1     Running     0             14h     10.104.6.87    4am-node13   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-datacoord-6766db4d76-stxlc     1/1     Running     0             14h     10.104.1.39    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-datanode-c5cc88b79-lnfzm       1/1     Running     0             14h     10.104.4.113   4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-indexcoord-79d8995b8c-cj72w    1/1     Running     0             14h     10.104.1.40    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-indexnode-687fb57df4-mkj5g     1/1     Running     0             14h     10.104.1.38    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-proxy-7cfc795cd7-bxjp7         1/1     Running     0             14h     10.104.4.114   4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-querycoord-67d874754d-5qrd5    1/1     Running     0             14h     10.104.1.41    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-querynode-685768ccd8-pscjh     1/1     Running     0             14h     10.104.1.44    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-querynode-685768ccd8-vblg4     1/1     Running     0             14h     10.104.4.115   4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-milvus-rootcoord-64f74d744b-6mcwl     1/1     Running     0             14h     10.104.1.42    4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-minio-0                               1/1     Running     0             3d18h   10.104.1.216   4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-minio-1                               1/1     Running     0             3d20h   10.104.5.213   4am-node12   <none>           <none>
fouram-tag-no-clean-p4l24-1-minio-2                               1/1     Running     0             3d20h   10.104.6.112   4am-node13   <none>           <none>
fouram-tag-no-clean-p4l24-1-minio-3                               1/1     Running     0             3d20h   10.104.9.58    4am-node14   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-bookie-0                       1/1     Running     0             3d20h   10.104.4.13    4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-bookie-1                       1/1     Running     0             3d20h   10.104.5.212   4am-node12   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-bookie-2                       1/1     Running     0             3d18h   10.104.1.235   4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-broker-0                       1/1     Running     0             3d20h   10.104.6.115   4am-node13   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-proxy-0                        1/1     Running     0             3d20h   10.104.9.55    4am-node14   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-recovery-0                     1/1     Running     0             3d20h   10.104.4.10    4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-zookeeper-0                    1/1     Running     0             3d20h   10.104.4.12    4am-node11   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-zookeeper-1                    1/1     Running     0             3d18h   10.104.1.219   4am-node10   <none>           <none>
fouram-tag-no-clean-p4l24-1-pulsar-zookeeper-2                    1/1     Running     0             3d20h   10.104.6.124   4am-node13   <none>           <none>
```
client log：
<img width="1335" alt="截屏2022-11-08 10 54 22" src="https://user-images.githubusercontent.com/34296482/200463918-8684aa7d-8062-43a8-8df4-f09f58756658.png">

### Steps To Reproduce

```markdown
1.create an collection
2.build ivfsq8 index
3.insert 100m data
4.build index again
5.search load,query,normal
6.upgrade image to 2.2.0-20221107-57d96a11, sleep  more than 1h 
7.release collection , drop index 
8.create hnsw index successfully
9.search failed
```

### Anything else?

```
data:
  config.yaml: |
    locust_rebuild_index_random_concurrent_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 12h
```
