### ISSUE TITLE
[Bug]: [benchmark][cluster] After milvus creates the diskann index, it search while insert and delete,  reports an OOM killed error.

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221110-0d5fbe89
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-zkgxg-1
server-configmap
server-cluster-4c16m256d-diskann-querynode2
client-configmap
client-random-locust-insert-delete-search-filter-diskann

server:

```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-zkgxg-1-etcd-0                                             1/1     Running     0               2d12h   10.104.9.18    4am-node14   <none>           <none>
fouram-zkgxg-1-etcd-1                                             1/1     Running     0               2d12h   10.104.5.202   4am-node12   <none>           <none>
fouram-zkgxg-1-etcd-2                                             1/1     Running     0               2d12h   10.104.1.185   4am-node10   <none>           <none>
fouram-zkgxg-1-milvus-datacoord-6955d57944-sxhzj                  1/1     Running     1 (2d12h ago)   2d12h   10.104.5.191   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-datanode-8597bb554b-nnncq                   1/1     Running     0               2d12h   10.104.4.207   4am-node11   <none>           <none>
fouram-zkgxg-1-milvus-indexcoord-bf6dbc6f5-nhk5l                  1/1     Running     0               2d12h   10.104.5.196   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-indexnode-69fb8f48c6-dfnnh                  1/1     Running     0               2d12h   10.104.5.193   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-proxy-765b8fc7bc-x7nxb                      1/1     Running     0               2d12h   10.104.5.192   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-querycoord-687746ddfb-sbdc2                 1/1     Running     1 (2d12h ago)   2d12h   10.104.5.198   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-querynode-7cb59f7494-7mj8g                  1/1     Running     0               2d12h   10.104.5.197   4am-node12   <none>           <none>
fouram-zkgxg-1-milvus-querynode-7cb59f7494-h2tnc                  1/1     Running     0               2d12h   10.104.6.207   4am-node13   <none>           <none>
fouram-zkgxg-1-milvus-rootcoord-5498b855cb-dvp7m                  1/1     Running     1 (2d12h ago)   2d12h   10.104.5.194   4am-node12   <none>           <none>
fouram-zkgxg-1-minio-0                                            1/1     Running     0               2d12h   10.104.9.20    4am-node14   <none>           <none>
fouram-zkgxg-1-minio-1                                            1/1     Running     0               2d12h   10.104.5.204   4am-node12   <none>           <none>
fouram-zkgxg-1-minio-2                                            1/1     Running     0               2d12h   10.104.6.209   4am-node13   <none>           <none>
fouram-zkgxg-1-minio-3                                            1/1     Running     0               2d12h   10.104.1.184   4am-node10   <none>           <none>
fouram-zkgxg-1-pulsar-bookie-0                                    1/1     Running     0               2d12h   10.104.9.23    4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-bookie-1                                    1/1     Running     0               2d12h   10.104.5.207   4am-node12   <none>           <none>
fouram-zkgxg-1-pulsar-bookie-2                                    1/1     Running     0               2d12h   10.104.4.210   4am-node11   <none>           <none>
fouram-zkgxg-1-pulsar-bookie-init-8cbhc                           0/1     Completed   0               2d12h   10.104.5.195   4am-node12   <none>           <none>
fouram-zkgxg-1-pulsar-broker-0                                    1/1     Running     0               2d12h   10.104.9.11    4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-proxy-0                                     1/1     Running     0               2d12h   10.104.9.9     4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-pulsar-init-7qqqh                           0/1     Completed   0               2d12h   10.104.9.10    4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-recovery-0                                  1/1     Running     0               2d12h   10.104.9.8     4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-zookeeper-0                                 1/1     Running     0               2d12h   10.104.9.19    4am-node14   <none>           <none>
fouram-zkgxg-1-pulsar-zookeeper-1                                 1/1     Running     0               2d12h   10.104.1.187   4am-node10   <none>           <none>
fouram-zkgxg-1-pulsar-zookeeper-2                                 1/1     Running     0               2d12h   10.104.5.209   4am-node12   <none>           <none>
```

client log：
<img width="1384" alt="截屏2022-11-14 11 00 33" src="https://user-images.githubusercontent.com/34296482/201566044-f8c629cd-0503-4972-bc69-d21151ca4c5d.png">

grafana:
querynode1：
<img width="1389" alt="截屏2022-11-14 11 01 57" src="https://user-images.githubusercontent.com/34296482/201566188-5f31539e-45bc-497d-a57d-12847849dbe5.png">
querynode2:
<img width="1393" alt="截屏2022-11-14 11 02 57" src="https://user-images.githubusercontent.com/34296482/201566279-c0a63921-f5a1-41f2-8e4d-875a775a06ad.png">

### Steps To Reproduce

```markdown
1. create a collection
2. build diskann index
3. insert 10w data
4. build index again
5. load collection
6. insert ,delete ,search,query ,load
```

### Anything else?

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: diskann
          index_param: {}
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    search_list: 30
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}"
              -
                type: load
                weight: 2
              -
                type: get
                weight: 5
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
              -
                type: delete
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 60h
```
