### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus insert delete with search, raise OOM killed error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221110-0d5fbe89
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-2vtnb-1
server-configmap
server-single-8c64m
client-configmap
client-random-locust-insert-delete-search-filter

server:
```
fouram-tag-no-clean-2vtnb-1-etcd-0                                1/1     Running     0               3d12h   10.104.5.177   4am-node12   <none>           <none>
fouram-tag-no-clean-2vtnb-1-milvus-standalone-58d89c68bb-k4d87    1/1     Running     0               3d12h   10.104.1.152   4am-node10   <none>           <none>
fouram-tag-no-clean-2vtnb-1-minio-5d6854577f-h9d9m                1/1     Running     0               3d12h   10.104.1.153   4am-node10   <none>           <none>
```
client log:
<img width="1331" alt="截屏2022-11-14 10 46 29" src="https://user-images.githubusercontent.com/34296482/201564548-d64df9da-1897-4f0e-87a3-164a6bea4630.png">

grafana:
<img width="1381" alt="截屏2022-11-14 10 48 57" src="https://user-images.githubusercontent.com/34296482/201564791-db3934a9-0a4f-4730-95ee-e55e1b79ad53.png">
<img width="1386" alt="截屏2022-11-14 10 49 07" src="https://user-images.githubusercontent.com/34296482/201564804-3580081f-223e-4213-abde-e30119d63dd2.png">

### Steps To Reproduce

```markdown
1. create a collection
2. build hnsw index
3. insert 10w data
4. build index again
5. load collection
7. search,query,load,insert,delete
```

### Anything else?

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}"
              -
                type: load
                weight: 2
              -
                type: get
                weight: 5
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
              -
                type: delete
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 24h
```
