### ISSUE TITLE
[Bug]: [benchmark][cluster] Milvus is reinstalled with the same PVC，rasie an error"force to deny /milvus.proto.milvus.MilvusService/Insert"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221115-bb43497f
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After restart
server-instance
fouram-tag-no-clean-z2mmt-1
server-configmap
server-cluster-8c64m-querynode2-kafka
client-configmap
client-random-locust-100m-ddl-rebuild-hnsw-con
image:2.2.0-20221114-c5c68753
pymilvus:2.2.0dev70

restart milvus:

server-instance
fouram-tag-no-clean-z2mmt-1
server-configmap
server-cluster-8c64m-querynode2-kafka
client-configmap
client-random-locust-100m-hnsw-ddl-r8-w2-12h-con

image:2.2.0-20221115-bb43497f
pymilvus:2.2.0.dev70

server：
```
fouram-tag-no-clean-z2mmt-1-etcd-0                                1/1     Running            0              13h     10.104.5.202   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-etcd-1                                1/1     Running            0              13h     10.104.9.207   4am-node14   <none>           <none>
fouram-tag-no-clean-z2mmt-1-etcd-2                                1/1     Running            0              13h     10.104.1.11    4am-node10   <none>           <none>
fouram-tag-no-clean-z2mmt-1-kafka-0                               1/1     Running            1 (13h ago)    13h     10.104.5.207   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-kafka-1                               1/1     Running            2 (13h ago)    13h     10.104.4.110   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-kafka-2                               1/1     Running            1 (13h ago)    13h     10.104.9.209   4am-node14   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-datacoord-76f7c97f69-hqlxq     1/1     Running            4 (142m ago)   13h     10.104.5.205   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-datanode-df5675666-bv7jd       1/1     Running            0              13h     10.104.4.108   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-indexcoord-5c769b47b6-k9z4x    1/1     Running            0              13h     10.104.4.106   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-indexnode-55ff99d877-bxg5g     1/1     Running            0              13h     10.104.4.107   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-proxy-6fc957866b-xdc67         1/1     Running            0              13h     10.104.5.204   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-querycoord-b9c985d4f-z5p99     1/1     Running            0              13h     10.104.4.105   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-querynode-5f9dffd667-574pb     1/1     Running            0              13h     10.104.9.206   4am-node14   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-querynode-5f9dffd667-s6bnk     1/1     Running            0              13h     10.104.5.200   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-milvus-rootcoord-5c64fb955c-hmc6p     1/1     Running            0              13h     10.104.5.203   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-minio-0                               1/1     Running            0              13h     10.104.5.201   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-minio-1                               1/1     Running            0              13h     10.104.9.205   4am-node14   <none>           <none>
fouram-tag-no-clean-z2mmt-1-minio-2                               1/1     Running            0              13h     10.104.1.10    4am-node10   <none>           <none>
fouram-tag-no-clean-z2mmt-1-minio-3                               1/1     Running            0              13h     10.104.6.189   4am-node13   <none>           <none>
fouram-tag-no-clean-z2mmt-1-zookeeper-0                           1/1     Running            0              13h     10.104.5.206   4am-node12   <none>           <none>
fouram-tag-no-clean-z2mmt-1-zookeeper-1                           1/1     Running            0              13h     10.104.4.109   4am-node11   <none>           <none>
fouram-tag-no-clean-z2mmt-1-zookeeper-2                           1/1     Running            0              13h     10.104.9.208   4am-node14   <none>           <none>
```

client log：
<img width="1390" alt="截屏2022-11-16 10 29 07" src="https://user-images.githubusercontent.com/34296482/202069183-99d6f7e0-8567-495e-9515-428bf76f039a.png">

querynode:
<img width="1389" alt="截屏2022-11-16 10 51 42" src="https://user-images.githubusercontent.com/34296482/202071938-6154a635-b255-4f7b-815b-d9e5d94a23ba.png">
querynode2:
<img width="1386" alt="截屏2022-11-16 10 52 51" src="https://user-images.githubusercontent.com/34296482/202072047-973e1853-0d49-4815-b173-f04d335c5feb.png">

### Steps To Reproduce

```markdown
1. create a collection
2. build hnsw index
3. insert 100m data
4. build index again
5. load collection
6. search, load, query, scene_test search normal
7. uninstall milvus, reinstall milvus with 2.2.0-20221115-bb43497f, stop 1 hours
8. search ,load ,query,scene_test raise error
```

### Anything else?

```
data:
  config.yaml: |
    locust_random_concurrent_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 12h
```
