### ISSUE TITLE
[Bug]: [benchmark][cluster] Milvus downtime upgrade load failed , raise error:"collection:sift_100m_128_l2 or partition:[] not loaded into memory when search"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#20898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221129-e2dd7a41
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-cbtcd-1
server-configmap
server-cluster-8c64m
client-configmap
client-random-locust-search-filter-100m-ddl

argo task: fouram-restart-server-n47jt

before upgrade: `2.2.0-20221126-dd10e571`
after upgrade:  `2.2.0-20221129-e2dd7a41`

server:
```
fouram-tag-no-clean-cbtcd-1-etcd-0                               1/1     Running     0              9m10s   10.104.6.194   4am-node13   <none>           <none>
fouram-tag-no-clean-cbtcd-1-etcd-1                               1/1     Running     0              9m10s   10.104.5.53    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-etcd-2                               1/1     Running     0              9m10s   10.104.4.59    4am-node11   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-datacoord-69f5f5785b-bwcjx    1/1     Running     0              9m10s   10.104.5.51    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-datanode-7bc4fc4bc7-h6b67     1/1     Running     2 (2m8s ago)   9m11s   10.104.5.50    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-indexcoord-f4b458bfc-84xfk    1/1     Running     2 (99s ago)    9m11s   10.104.9.137   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-indexnode-84dfbccc46-pr59l    1/1     Running     0              9m10s   10.104.9.136   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-proxy-ff948994f-jrs7z         1/1     Running     1 (5m9s ago)   9m10s   10.104.9.138   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-querycoord-5b85856c46-4gbp7   1/1     Running     2 (100s ago)   9m11s   10.104.9.132   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-querynode-6b6487f448-x5zhz    1/1     Running     0              9m11s   10.104.5.49    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-milvus-rootcoord-77b8f477b-g2dbt     1/1     Running     1 (5m9s ago)   9m11s   10.104.5.48    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-minio-0                              1/1     Running     0              9m11s   10.104.1.244   4am-node10   <none>           <none>
fouram-tag-no-clean-cbtcd-1-minio-1                              1/1     Running     0              9m11s   10.104.5.55    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-minio-2                              1/1     Running     0              9m10s   10.104.6.195   4am-node13   <none>           <none>
fouram-tag-no-clean-cbtcd-1-minio-3                              1/1     Running     0              9m10s   10.104.4.58    4am-node11   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-bookie-0                      1/1     Running     0              9m11s   10.104.6.193   4am-node13   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-bookie-1                      1/1     Running     0              9m11s   10.104.5.54    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-bookie-2                      1/1     Running     0              9m10s   10.104.9.139   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-bookie-init-6qfb6             0/1     Completed   0              9m10s   10.104.9.133   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-broker-0                      1/1     Running     0              9m10s   10.104.5.52    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-proxy-0                       1/1     Running     0              9m11s   10.104.5.47    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-pulsar-init-tkfvj             0/1     Completed   0              9m10s   10.104.9.135   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-recovery-0                    1/1     Running     0              9m11s   10.104.9.134   4am-node14   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-zookeeper-0                   1/1     Running     0              9m11s   10.104.5.46    4am-node12   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-zookeeper-1                   1/1     Running     0              8m39s   10.104.6.196   4am-node13   <none>           <none>
fouram-tag-no-clean-cbtcd-1-pulsar-zookeeper-2                   1/1     Running     0              8m9s    10.104.4.60    4am-node11   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/204703630-5ccb4bb7-42df-4790-8f78-27e49d079c83.png)

### Steps To Reproduce

```markdown
1.create an collection
2.build index of ivf_sq8
3.insert 100m data
4.build index again
5.search ,query, load, scene_test    ===>  load failed
```

### Anything else?

client-random-locust-search-filter-100m-ddl
```
    locust_random_concurrent_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          # collection_name: sift_1m_128_l2
          other_fields: float1
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            # during_time: 60h
            during_time: 12h
```
