### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus upgrade image, ivf sq8 index search slowed down

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#20925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221130-c5f215da
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-m9sd9-1
server-configmap
server-single-32c128m
client-configmap
client-random-locust-100m-ddl-r8-w2-12h

argo task: fouram-upgrade-server-6n5dp

before upgrade:2.2.0-20221129-e2dd7a41
after upgrade:2.2.0-20221130-c5f215da

server
```
fouram-tag-no-clean-m9sd9-1-etcd-0                               1/1     Running            0                 2d1h    10.104.6.45    4am-node13   <none>           <none>
fouram-tag-no-clean-m9sd9-1-milvus-standalone-796c467f47-n5bnv   1/1     Running            0                 106s    10.104.9.179   4am-node14   <none>           <none>
fouram-tag-no-clean-m9sd9-1-minio-744d4c7b47-rdwz5               1/1     Running            0                 2d1h    10.104.4.17    4am-node11   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/204980522-3a06477f-f736-4bfb-b8e4-4eeee3f58718.png)

grafana:
![image](https://user-images.githubusercontent.com/48523564/204980848-35f26d29-b932-4ee5-83f9-9ec567053451.png)

Problem 1: The latency in the front has not been reduced.
Problem 2: the latency to the back stage is also still a few hundred milliseconds

 

### Steps To Reproduce

```markdown
1. create a collection  
2. build index of ivf_sq8
3. insert 100m data
4. build index again
5. search ,query, load     ===>   increased latency, slower query
```

### Anything else?

client-random-locust-100m-ddl-r8-w2-12h
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              # -
                # type: scene_test
                # weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            # during_time: 1h
            during_time: 12h
```
