### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus has restarted 44 times, report an error:"server Unavailable: Retry timeout: 60s"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#20988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221202-90ca7e1e
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev72 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
hnsw index compaction scenario, milvus restarted 44 times.  query , search , describe_collection and other interfaces 
report an error: "server Unavailable: Retry timeout: 60s"

Parameters:
server-instance
fouram-stable-1670173200-4
server-configmap
server-single-8c32m
client-configmap
client-random-locust-hnsw-compaction-search-5h

argo task:fouram-stable-1670173200 

server 
```
NAME                                                              READY   STATUS        RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-stable-1670173200-4-etcd-0                                 1/1     Running       0               5h10m   10.104.9.87    4am-node14   <none>           <none>
fouram-stable-1670173200-4-milvus-standalone-6bc7c56874-wkgfx     1/1     Running       44 (11m ago)    5h10m   10.104.1.35    4am-node10   <none>           <none>
fouram-stable-1670173200-4-minio-bc798cdc4-rxbvj                  1/1     Running       0               5h10m   10.104.6.128   4am-node13   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/205582735-454e987f-2d6a-4487-a606-e79737ce15bb.png)
 

grafana:
milvus pod memory:
![image](https://user-images.githubusercontent.com/48523564/205582050-d7151f14-9f7a-4a15-8308-a9337dd0c993.png)

### Steps To Reproduce

```markdown
1.create an collection
2.build index of hnsw
3.insert 100 thousand data
4.build index again
5.search ,query, load, scene_insert_delete_flush    ===>  raise error
```

### Anything else?

client-random-locust-hnsw-compaction-search-5h
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_insert_delete_flush
                weight: 1
                params:
                  insert_len: 1
                  del_len: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 5h
```
