### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus insert with delete,  search ,query interface report an error:"server Unavailable: Retry run out of 10 retry times" 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#20992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221202-90ca7e1e
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev72 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

hnsw index query、search 、insert、delete scenario, milvus restart, query 、search 、 describe_collection interface report an error:"server Unavailable: Retry run out of 10 retry times" 

Parameters:
server-instance
fouram-stable-1670173200-3
server-configmap
server-single-8c32m
client-configmap
client-random-locust-insert-delete-search-filter-5h

argo task:fouram-stable-1670173200

server
```
fouram-stable-1670173200-3-etcd-0                                 1/1     Running     0               5h10m   10.104.9.89    4am-node14   <none>           <none>
fouram-stable-1670173200-3-milvus-standalone-6bd98c7d98-f5rvq     1/1     Running     16 (37m ago)    5h10m   10.104.6.146   4am-node13   <none>           <none>
fouram-stable-1670173200-3-minio-6bc47ff8c8-2vntc                 1/1     Running     0               5h10m   10.104.9.81    4am-node14   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/205621207-81e74c8d-1150-4165-bd44-c8f6cd38502a.png)

### Steps To Reproduce

```markdown
1.create a collection
2.build index of hnsw
3.insert 100 thousand data
4.build index again
5.search ,query, load, insert, delete  ===>  raise error
```

### Anything else?

client-random-locust-insert-delete-search-filter-5h
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}"
              -
                type: load
                weight: 2
              -
                type: get
                weight: 5
                params:
                  ids_length: 10
              -
                type: insert
                weight: 1
                params:
                  ni_per: 1
              -
                type: delete
                weight: 1
                params:
                  ni_per: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            # during_time: 84h
            during_time: 5h
```

**Comment by yanliang567** [comment]
@soothing-rain sounds like a regression issue for 2.2 branch
/assign @soothing-rain 
/unassign

**Comment by soothing-rain** [comment]
Should be fixed by https://github.com/milvus-io/milvus/pull/21034

**Comment by xiaofan-luan** [comment]
need to figure out why we fall into this branch.
From my knowledge distance can not be negative value.

**Comment by elstic** [comment]
### Current Behavior
 
server-instance
fouram-stable-1670778000-3
server-configmap
server-single-8c32m
client-configmap
client-random-locust-insert-delete-search-filter-5h

argo task: fouram-stable-1670778000

server
```
fouram-stable-1670778000-3-etcd-0                                 1/1     Running     0                2m2s    10.104.5.129   4am-node12   <none>           <none>
fouram-stable-1670778000-3-milvus-standalone-5655bdfc5c-lvkzn     1/1     Running     0                2m2s    10.104.5.128   4am-node12   <none>           <none>
fouram-stable-1670778000-3-minio-7c8fbd46b8-mrdct                 1/1     Running     0                2m2s    10.104.9.164   4am-node14   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/206957203-dfed0798-584f-4281-abff-f8b99257f9a2.png)

### Steps To Reproduce
1.create an collection
2.build index of hnsw
3.insert 100 thousand data
4.build index again
5.search ,query, load, insert, delete  ===>  raise error

**Comment by elstic** [comment]
### Current Behavior

server-instance
fouram-stable-1670778000-4
server-configmap
server-single-8c32m
client-configmap
client-random-locust-hnsw-compaction-search-5h

server
```
fouram-stable-1670778000-4-etcd-0                                 1/1     Running     0                106s    10.104.5.127   4am-node12   <none>           <none>
fouram-stable-1670778000-4-milvus-standalone-6dcbdfc968-sms2t     1/1     Running     0                106s    10.104.9.169   4am-node14   <none>           <none>
fouram-stable-1670778000-4-minio-c5cf79f8f-78qsj                  1/1     Running     0                106s    10.104.5.116   4am-node12   <none>           <none>
```

client log
 
![image](https://user-images.githubusercontent.com/48523564/206957983-6e450c31-c7c6-4a6c-b270-49ae7fa82f18.png)


### Steps To Reproduce
1.create an collection
2.build index of hnsw
3.insert 100 thousand data
4.build index again
5.search ,query, load, scene_insert_delete_flush  ===> raise error
### Anything else
client-random-locust-hnsw-compaction-search-5h
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          # other_fields: int1,int2,float1,double1
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_insert_delete_flush
                weight: 1
                params:
                  insert_len: 1
                  del_len: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            # during_time: 84h
            during_time: 5h
```
