### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus standalone search interface all report an error:"Unexcepted error: [search], search_requests_with_expr() got multiple values for argument 'schema'"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#21008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221205-7ea86ed3
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

All search interfaces report an error: "Unexcepted error: [search], search_requests_with_expr() got multiple values for argument 'schema'"

server-instance
fouram-stable-1670259600-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

argo task:fouram-stable-1670259600

server
```
fouram-stable-1670259600-1-etcd-0                                 1/1     Running     0               3m      10.104.6.78    4am-node13   <none>           <none>
fouram-stable-1670259600-1-milvus-standalone-6bf688c79b-79rbr     1/1     Running     0               3m      10.104.6.84    4am-node13   <none>           <none>
fouram-stable-1670259600-1-minio-756cd958d-px7rz                  1/1     Running     0               3m      10.104.1.131   4am-node10   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/205842758-65b491f7-5be6-4a38-a16d-fe9d8777ce39.png)

### Steps To Reproduce

```markdown
1. create a collection  
2. build index of diskann
3. insert 10m data
4. build index again
5. search ,query, load ===> raise error
```

### Anything else?

client-locust-search-sift10m-diskann
```
   locust_random_performance:
      collections:
        -
          collection_name: sift_10m_128_l2
          ni_per: 50000
          build_index: true
          index_type: diskann
          index_param: {}
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    search_list: 30
              -
                type: load
                weight: 1
              -
                type: get
                weight: 2
                params:
                  ids_length: 10  
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 1h
```
