### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus insert and delete, search, query, pod restart, interface reports error: "Retry timeout: 60s, message=server Unavailable: Retry timeout: 60s"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#21216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221213-437e4430
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Parameters:
server-instance
fouram-stable-1670950800-4
server-configmap
server-single-8c32m
client-configmap
client-random-locust-hnsw-compaction-search-5h

argo task: fouram-stable-1670950800

server
```
NAME                                                              READY   STATUS      RESTARTS       AGE    IP             NODE         NOMINATED NODE   READINESS GATES
fouram-stable-1670950800-4-etcd-0                                 1/1     Running     0              117s   10.104.1.163   4am-node10   <none>           <none>
fouram-stable-1670950800-4-milvus-standalone-85b5d968b9-shx7l     1/1     Running     0              117s   10.104.9.123   4am-node14   <none>           <none>
fouram-stable-1670950800-4-minio-64cfc6587f-76mqs                 1/1     Running     0              117s   10.104.1.157   4am-node10   <none>           <none>
```
client pod: fouram-stable-1670950800-3526100876
client log:
![image](https://user-images.githubusercontent.com/48523564/207503326-e48c0ec1-c9f8-4c22-8ff5-a9ca8fd2a7a9.png)

![image](https://user-images.githubusercontent.com/48523564/207502790-699d7c21-7e4a-4e66-b9c2-9a04fc5d55ec.png)

### Steps To Reproduce

```markdown
1.create a collection
2.build index of hnsw
3.insert 100 thousand data
4.build index again
5.search ,query,laod,scene_insert_delete_flush ===>  raise error
```

### Anything else?

complete client log：
[client-logs.txt](https://github.com/milvus-io/milvus/files/10224225/client-logs.txt)

client-random-locust-hnsw-compaction-search-5h:
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_10w_128_l2
          ni_per: 50000
          # other_fields: int1,int2,float1,double1
          other_fields: float1
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    ef: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_insert_delete_flush
                weight: 1
                params:
                  insert_len: 1
                  del_len: 1
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            # during_time: 84h
            during_time: 5h
```
