### ISSUE TITLE
[Bug]: After I upgraded 2.2.0 to 2.2.2, indexnode restarted without any reason and there was no exception log. Datanodes also restarted frequently due to the bloom filter and channel reporting errors.

### ISSUE THREAD

**Issue by eliassama** [milvus-io/milvus#21460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): @zilliz/milvus2-sdk-node@v2.2.1
- OS(Ubuntu or CentOS): container
- CPU/Memory: 4/4
- GPU: 0
- Others:
```

### Current Behavior

After I upgraded 2.2.0 to 2.2.2, indexnode restarted without any reason and there was no exception log. Datanodes also restarted frequently due to the bloom filter and channel reporting errors.

dataNode log:
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/79587688/210030956-cbfc99f2-175c-4a8a-8bf5-c11a5313f89b.png">
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/79587688/210030959-a21cd1eb-12b0-4ac7-9ea7-2845f2d269f0.png">

indexNode log:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/79587688/210030907-a83ed9ea-0265-4fd6-800a-ec3b9e6d9384.png">

**Comment by xiaofan-luan** [comment]
It shows access denied and EOF. Did we change any minio configs?
@LoveEachDay

**Comment by eliassama** [comment]
[log.zip](https://github.com/milvus-io/milvus/files/10323049/log.zip)
this is all pod log

**Comment by xiaofan-luan** [comment]
The error shows it's access deny, did you change any configs on Minio

**Comment by eliassama** [comment]
> It shows access denied and EOF. Did we change any minio configs? @LoveEachDay

no, we use s3 , and we not change s3 any thing.

**Comment by LoveEachDay** [comment]
@eliassama Could you provide some information about the install procedures? And how do you proceed a version upgrade?

**Comment by xiaofan-luan** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/83447078/210037946-f93dc5f7-6b7a-4ec7-b7bc-cdac6f3c79ae.png">

**Comment by xiaofan-luan** [comment]
If you are using helm install, did you check your S3 host and accesskey?
helm upgrade --install --set cluster.enabled=true --set externalS3.enabled=true --set externalS3.host='s3.us-east-2.amazonaws.com' --set externalS3.port=80 --set externalS3.accessKey=${access-key} --set externalS3.secretKey=${secret-key} --set externalS3.bucketName=${bucket-name} --set minio.enabled=False --set service.type=LoadBalancer milvus milvus/milvus

**Comment by xiaofan-luan** [comment]
you can probably download a aws cli and try to list on your milvus cluster see if S3 is able to access

**Comment by eliassama** [comment]
> @eliassama Could you provide some information about the install procedures? And how do you proceed a version upgrade?

Since the milvus image itself is stateless, I upgraded the image itself directly

**Comment by eliassama** [comment]
> 你可能可以下载一个 aws cli 并尝试在你的 milvus 集群上列出，看看 S3 是否能够访问

I installed and used aws cli to link to s3, which was accessible normally.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/79587688/210042085-b2e0b1e5-29fe-4f3b-822f-9201323ec7de.png">

**Comment by eliassama** [comment]
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/83447078/210037946-f93dc5f7-6b7a-4ec7-b7bc-cdac6f3c79ae.png">

and i can download this file.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/79587688/210043048-f7563ab0-bd62-4e92-a218-77f2949d86e2.png">

**Comment by LoveEachDay** [comment]
@eliassama How do your milvus access s3 using ak/sk or iam? 
Could you paste the `minio` section under `configs/milvus.yaml`? 

Note: remove the sensitive info, using `****` instead.

**Comment by eliassama** [comment]
> @eliassama How do your milvus access s3 using ak/sk or iam? Could you paste the `minio` section under `configs/milvus.yaml`?
> 
> Note: remove the sensitive info, using `****` instead.

```yaml
# Related configuration of MinIO/S3/GCS or any other service supports S3 API, which is responsible for data persistence for Milvus.
# We refer to the storage service as MinIO/S3 in the following description for simplicity.
minio:
  address: ****** # Address of MinIO/S3
  port: ******   # Port of MinIO/S3
  accessKeyID: ****** # accessKeyID of MinIO/S3
  secretAccessKey: ****** # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: ****** # Bucket name in MinIO/S3
  rootPath: mdata # The root path where the message is stored in MinIO/S3

```
