### ISSUE TITLE
[Bug]: panic: invalid channel name when upgrading v2.2.2 to master- image

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#21710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.2 -> 2. master-20230113-90d9e165
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone by operator manifests
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: config-upgrade
  namespace: chaos-testing
spec:
  mode: standalone
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    rocksmq:
      persistence:
        enabled: true
  components:
    image: harbor.milvus.io/dockerhub/milvusdb/milvus:v2.2.2
    imagePullPolicy: Always
    standalone:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 6Gi
          cpu: 2
  config:
    log:
      level: debug
```

2. upgrade image to `master-20230113-90d9e165` by edit milvus crd
```
kubectl edit mi config-upgrade
```
3. standalone pod panic
```
457 [2023/01/13 08:22:32.223 +00:00] [WARN] [server/rocksmq_impl.go:357] ["rocksmq topic already exists "] [topic=by-dev-rootcoord-dml_255]
 458 [2023/01/13 08:22:32.223 +00:00] [DEBUG] [rootcoord/dml_channels.go:175] ["init dml channels"] [num=256]
 459 [2023/01/13 08:22:32.223 +00:00] [ERROR] [rootcoord/dml_channels.go:279] ["invalid channel name"] [chanName=config-upgrade-rootcoord-dml_14] [stack="gi     thub.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).addChannels\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:279\n     github.com/milvus-io/milvus/internal/rootcoord.newTimeTickSync\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:117\ngithub.co     m/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:431\ngithub.com/milv     us-io/milvus/internal/rootcoord.(*Core).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:472\nsync.(*Once).doSlow\n\t     /usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\     t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:471\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\     t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:204\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server     ).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:127\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run     \n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/githu     b.com/milvus-io/milvus/cmd/roles/roles.go:91"]
 460 panic: invalid channel name: config-upgrade-rootcoord-dml_14
 461 
 462 goroutine 322 [running]:
 463 panic({0x31e9660, 0xc001895190})
 464     /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc000e69598 sp=0xc000e694d8 pc=0x11c5cf7
 465 github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).addChannels(0xc000d6e900, {0xc000e14260?, 0x2, 0xc00075af60?})
 466     /go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:280 +0x267 fp=0xc000e69658 sp=0xc000e69598 pc=0x2c60167
 467 github.com/milvus-io/milvus/internal/rootcoord.newTimeTickSync({0x3a663b0?, 0xc00069e900}, 0x17, {0x7fa5fab18470, 0xc00075af60}, 0xc000449f20?)
 468     /go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:117 +0x17f fp=0xc000e69828 sp=0xc000e69658 pc=0x2cb6a7f
 469 github.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal(0xc000e7f380)
 470     /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:431 +0x20f fp=0xc000e69948 sp=0xc000e69828 pc=0x2c8e86f
 471 github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func1()
 472     /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:472 +0x26 fp=0xc000e69968 sp=0xc000e69948 pc=0x2c8f1e6
 473 sync.(*Once).doSlow(0x0?, 0x10?)
 474     /usr/local/go/src/sync/once.go:68 +0xc2 fp=0xc000e699c8 sp=0xc000e69968 pc=0x12081c2
 475 sync.(*Once).Do(...)
 476     /usr/local/go/src/sync/once.go:59
 477 github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init(0xc000865c98?)
 478     /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:471 +0x65 fp=0xc000e69a10 sp=0xc000e699c8 pc=0x2c8f185
 479 github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc000d61900)
 480     /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:204 +0x852 fp=0xc000e69e48 sp=0xc000e69a10 pc=0x2cbd0f2
 481 github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc0005f1780?)
 482     /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:127 +0x25 fp=0xc000e69e88 sp=0xc000e69e48 pc=0x2cbc805
 483 github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0xc00059e1c0?)
 484     /go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:52 +0x2f fp=0xc000e69f58 sp=0xc000e69e88 pc=0x2cc114f
 485 github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
 486     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:91 +0x15c fp=0xc000e69fe0 sp=0xc000e69f58 pc=0x2cc34dc
 487 runtime.goexit()
 488     /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000e69fe8 sp=0xc000e69fe0 pc=0x11fb0a1
 489 created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
 490     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:78 +0x151
 491 
 492 goroutine 1 [semacquire]:
```
[standalone.log](https://github.com/milvus-io/milvus/files/10409695/standalone.log)
