### ISSUE TITLE
[Bug]: Memory and disk usage above expectation

### ISSUE THREAD

**Issue by amir-hojjati** [milvus-io/milvus#22002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8 core, 32G ram
- GPU: 
- Others:
```

### Current Behavior

This is a combination of two issues that I have seen before (https://github.com/milvus-io/milvus/issues/19574 and https://github.com/milvus-io/milvus/issues/18764) both of them have been closed.

I am testing milvus for our solution to store 768-dim vectors. I create a collection for each new user and then insert / upsert (delete+insert) vectors on a daily basis. Currently after 1 week, there are around 50k vectors residing in 300 collections in total which is not that much. At the moment of writing this Milvus is taking:
- 6G of ram and growing
- 44G of ssd storage and growing almost linearly! (All of which is stored in rdb_data folder, I already decreased retention time and retention size for rocksmq)

Ram:

![image](https://user-images.githubusercontent.com/47317451/216927031-1d5c76e3-0a23-4a2e-9774-2b4994700b07.png)

Disk:

`/path/to/milvus_docker/milvus/rdb_data:   44G`

<img width="673" alt="image" src="https://user-images.githubusercontent.com/47317451/216977709-c273d7da-8496-4cff-ae8d-94893ce628f2.png">

This definitely won't be scalable for us, but according to the sizing tool and most people's comments, it should be way less than that (less than 1G) for only 50k 768-dim vectors. I am new too Milvus though, so I could be missing something. Any help would be much appreciated.

### Expected Behavior

Milvus should take up much less ram and storage.

**Comment by xiaofan-luan** [comment]
Hi @amir-hojjati 
How long did you change your rocksmq retention time and size to?

**Comment by xiaofan-luan** [comment]
The reason memory is growing is probably due to compaction setups.
You could try to trigger compaction manually and see if  memory decrease, if true then tuning compaction metrics would help

**Comment by LoveEachDay** [comment]
@amir-hojjati Could you paste the `rocksmq` config section under `config/milvus.yaml`? You may need to decrease the `rocsmq.compactionInterval` to trigger compaction more frequently.

Rocksmq will store all the data that you had inserted into milvus (including all the deleted records).

**Comment by amir-hojjati** [comment]
@xiaofan-luan @LoveEachDay 
Thanks for your quick responses, this is the rocksmq section of my milvus.yaml:
```
rocksmq:
  # please adjust in embedded Milvus: /tmp/milvus/rdb_data
  path: /var/lib/milvus/rdb_data # The path where the message is stored in rocksmq
  rocksmqPageSize: 2147483648 # 2 GB, 2 * 1024 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
  retentionTimeInMinutes: 1440 # 1 days, 1 * 24 * 60 minutes, The retention time of the message in rocksmq.
  retentionSizeInMB: 2048 # 2 GB, 2 * 1024 MB, The retention size of the message in rocksmq.
  compactionInterval: 21600 # 1/4 day, trigger rocksdb compaction every 1/4 day to remove deleted data
  lrucacheratio: 0.06 # rocksdb cache memory ratio
```
I already decreased retention time to 1 day, retention size to 2G and compaction interval to 1/4 day (I see rocksmq deleting old .sst files but still the overall number is always on the rise) . Do you think this could be the reason for both memory and storage issues?
