### ISSUE TITLE
[Bug]: log related configrations in milvus.yaml  is not available

### ISSUE THREAD

**Issue by vesa1123** [milvus-io/milvus#22151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): CentOS Linux release 7.9.2009 (Core)
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz 6*2/ 128G
- GPU: /
- Others: /
```

### Current Behavior

When I install milvus witn docker-compose, update the volumes for rootcoord,querycoord,querynode,indexcoord,indexnode,datacoord,datanode as belowing:

    volumes:
      - /data/milvus/config/milvus.yaml:/milvus/configs/milvus.yaml

Then I update the log related configration in milvus.yaml and set the rootPath to stdout as belowing

# Configures the system log output.
log:
  level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  file:
    # please adjust in embedded Milvus: /tmp/milvus/logs
    rootPath: /data/milvus/logs # default to stdout, stderr
    maxSize: 300 # MB
    maxAge: 10 # Maximum time for log retention in day.
    maxBackups: 20
  format: text # text/json 

As all above have been done ,I start the container of milvus and get no error. all containers are started  successful!

### Expected Behavior

When I redirect to the path of milvus log  as  '/tmp/milvus/logs', the dictionary is still empty. It seems the configration is not available...?

**Comment by LoveEachDay** [comment]
@vesa1123 From the above config:
```
log:
level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
file:
  # please adjust in embedded Milvus: /tmp/milvus/logs
  rootPath: /data/milvus/logs # default to stdout, stderr
  maxSize: 300 # MB
  maxAge: 10 # Maximum time for log retention in day.
  maxBackups: 20
  format: text # text/json
```
The `rootPath` is `/data/milvus.logs`, you should find logs in the `/data/milvus/logs` directory, instead of `/tmp/milvus/logs` .
