### ISSUE TITLE
[Bug]: i can't use milvus grafana

### ISSUE THREAD

**Issue by eliassama** [milvus-io/milvus#22381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): container
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 i can't use grafana by 7.1.3
 
 grafana report e.replace is not a fuction 
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/79587688/220884746-d865d1b3-c385-4a76-9188-f11033476604.png">

**Comment by eliassama** [comment]
e.replace must upgrade.

i upgrade 8.5.5.

**Comment by eliassama** [comment]
now, i don't have any data. but prometheus data being collected.

![image](https://user-images.githubusercontent.com/79587688/220898918-b59b40d1-ffd9-4252-90b8-cc340ac5464f.png)
![image](https://user-images.githubusercontent.com/79587688/220899146-4dbecc56-fd36-4015-91da-cd71beb42466.png)

**Comment by eliassama** [comment]
Prometheus config:

```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    cluster: pulsar-cluster

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ['localhost:9090']

  # pulsar indicator configuration was omitted
  
  - job_name: 'milvus'
    static_configs:
    - targets: ['milvus-proxy-1:9091','milvus-proxy-2:9091','milvus-proxy-3:9091','milvus-proxy-4:9091','milvus-proxy-5:9091','milvus-proxy-6:9091',]
```
