### ISSUE TITLE
[Bug]: [benchmark][RG][replicas] After searching for a short time, queryNode panics and restarts

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#22397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230224-62d0c2fa
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**server:**
```
NAME                                                              READY   STATUS              RESTARTS          AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-rv4p5-88-5186-etcd-0                                      1/1     Running             0                 5m58s   10.104.1.187    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-etcd-1                                      1/1     Running             0                 5m58s   10.104.9.210    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-etcd-2                                      1/1     Running             0                 5m58s   10.104.6.80     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-datacoord-5588578477-4q9f2           1/1     Running             1 (116s ago)      5m58s   10.104.6.73     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-datanode-87c965dbb-b8bnp             1/1     Running             1 (118s ago)      5m58s   10.104.9.198    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-milvus-indexcoord-5b7569b45d-wv6hc          1/1     Running             1 (111s ago)      5m58s   10.104.1.180    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-milvus-indexnode-68744549c9-bv94l           1/1     Running             0                 5m58s   10.104.1.179    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-milvus-proxy-667457c448-ctpkb               1/1     Running             1 (116s ago)      5m58s   10.104.6.71     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querycoord-67684f5849-lpt7p          1/1     Running             1                 5m58s   10.104.5.215    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-hqqpx           1/1     Running             0                 5m58s   10.104.4.118    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-mxzfw           1/1     Running             0                 5m58s   10.104.5.213    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-vbpfk           1/1     Running             0                 5m58s   10.104.9.200    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-w8f94           1/1     Running             0                 5m58s   10.104.6.70     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-rootcoord-6f5995cfb7-5gbcj           1/1     Running             1                 5m58s   10.104.5.214    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-minio-0                                     1/1     Running             0                 5m58s   10.104.1.186    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-minio-1                                     1/1     Running             0                 5m58s   10.104.9.209    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-minio-2                                     1/1     Running             0                 5m58s   10.104.5.228    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-minio-3                                     1/1     Running             0                 5m57s   10.104.4.135    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-0                             1/1     Running             0                 5m58s   10.104.4.133    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-1                             1/1     Running             0                 5m58s   10.104.5.224    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-2                             1/1     Running             0                 5m58s   10.104.9.211    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-init-jgxz7                    0/1     Completed           0                 5m58s   10.104.5.216    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-broker-0                             1/1     Running             0                 5m58s   10.104.6.69     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-proxy-0                              1/1     Running             0                 5m58s   10.104.4.119    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-pulsar-init-2qhzh                    0/1     Completed           0                 5m58s   10.104.4.120    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-recovery-0                           1/1     Running             0                 5m58s   10.104.6.74     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-0                          1/1     Running             0                 5m58s   10.104.4.132    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-1                          1/1     Running             0                 4m56s   10.104.1.190    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-2                          1/1     Running             0                 4m20s   10.104.9.222    4am-node14   <none>           <none>
```

**queryNode restart:**
```
NAME                                                              READY   STATUS              RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-rv4p5-88-5186-etcd-0                                      1/1     Running             0                5h39m   10.104.1.187    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-etcd-1                                      1/1     Running             0                5h39m   10.104.9.210    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-etcd-2                                      1/1     Running             0                5h39m   10.104.6.80     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-datacoord-5588578477-4q9f2           1/1     Running             1 (5h35m ago)    5h39m   10.104.6.73     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-datanode-87c965dbb-b8bnp             1/1     Running             1 (5h35m ago)    5h39m   10.104.9.198    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-milvus-indexcoord-5b7569b45d-wv6hc          1/1     Running             1 (5h35m ago)    5h39m   10.104.1.180    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-milvus-indexnode-68744549c9-bv94l           1/1     Running             0                5h39m   10.104.1.179    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-milvus-proxy-667457c448-ctpkb               1/1     Running             1 (5h35m ago)    5h39m   10.104.6.71     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querycoord-67684f5849-lpt7p          1/1     Running             1                5h39m   10.104.5.215    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-hqqpx           1/1     Running             0                5h39m   10.104.4.118    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-mxzfw           1/1     Running             0                5h39m   10.104.5.213    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-vbpfk           1/1     Running             0                5h39m   10.104.9.200    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-milvus-querynode-5867445657-w8f94           1/1     Running             1 (5h3m ago)     5h39m   10.104.6.70     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-milvus-rootcoord-6f5995cfb7-5gbcj           1/1     Running             1                5h39m   10.104.5.214    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-minio-0                                     1/1     Running             0                5h39m   10.104.1.186    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-minio-1                                     1/1     Running             0                5h39m   10.104.9.209    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-minio-2                                     1/1     Running             0                5h39m   10.104.5.228    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-minio-3                                     1/1     Running             0                5h39m   10.104.4.135    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-0                             1/1     Running             0                5h39m   10.104.4.133    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-1                             1/1     Running             0                5h39m   10.104.5.224    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-2                             1/1     Running             0                5h39m   10.104.9.211    4am-node14   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-bookie-init-jgxz7                    0/1     Completed           0                5h39m   10.104.5.216    4am-node12   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-broker-0                             1/1     Running             0                5h39m   10.104.6.69     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-proxy-0                              1/1     Running             0                5h39m   10.104.4.119    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-pulsar-init-2qhzh                    0/1     Completed           0                5h39m   10.104.4.120    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-recovery-0                           1/1     Running             0                5h39m   10.104.6.74     4am-node13   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-0                          1/1     Running             0                5h39m   10.104.4.132    4am-node11   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-1                          1/1     Running             0                5h38m   10.104.1.190    4am-node10   <none>           <none>
fouramf-rv4p5-88-5186-pulsar-zookeeper-2                          1/1     Running             0                5h37m   10.104.9.222    4am-node14   <none>           <none>
```

**logs for fouramf-rv4p5-88-5186-milvus-querynode-5867445657-w8f94:**
```
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:309 +0x2e fp=0xc00d923fe0 sp=0xc00d923fc0 pc=0x2c1622e
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func4()
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:287 +0xbb fp=0xc00d923fc0 sp=0xc00d923f70 pc=0x2c1631b
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func1({0x420b0c8, 0xc00be32b00})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:337 +0xf2 fp=0xc00d923f70 sp=0xc00d923ef8 pc=0x2c165b2
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processReadTask(0xc000525320, {0x420b0c8, 0xc00be32b00})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:164 +0x5b fp=0xc00d923ef8 sp=0xc00d923ec0 pc=0x2c184db
github.com/milvus-io/milvus/internal/querynode.(*searchTask).Execute(0xc00be32b00?, {0xc002458720?, 0x1433d85?})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:125 +0x80e fp=0xc00d923ec0 sp=0xc00d923c18 pc=0x2c17b2e
github.com/milvus-io/milvus/internal/querynode.(*searchTask).searchOnStreaming(0xc00be32b00)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:228 +0x15c fp=0xc00d923c18 sp=0xc00d923970 pc=0x2c18e5c
github.com/milvus-io/milvus/internal/querynode.(*searchTask).reduceResults(0xc00be32b00, {0x41ef710, 0xc00a404700}, 0xc00be3dad0, {0xc003092f00, 0x9, 0x9})
	/go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:100 +0x2bc fp=0xc00d923970 sp=0xc00d9238c0 pc=0x2c3ccdc
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc00badee70, {0xc003092f00, 0x9, 0x3e8?}, 0x64?, {0xc052787b50, 0x1, 0x0?}, {0xc052787b58, 0x1, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:100 +0xdd fp=0xc00d9238c0 sp=0xc00d923830 pc=0x2c3ce9d
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData.func1(0x394aa60?, 0xc002f3e440?, 0xc00d923960?, 0x2c3c93a?, 0x0?, 0x58282c0?, 0x0?)
	_cgo_gotypes.go:776 +0x55 fp=0xc00d923830 sp=0xc00d923808 pc=0x2c25975
github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceSearchResultsAndFillData(0xc000feb3a8, 0x7f42cc208000, 0xc002ae7d00, 0x9, 0xc052787b50, 0xc052787b58, 0x1)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00d923808 sp=0xc00d9237d0 pc=0x13bc37c
runtime.cgocall(0x2f5d2f0, 0xc00d923830)
goroutine 35630 [syscall]:
	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9
runtime.sigpanic()
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.throw({0x3e1f3e7?, 0x0?})
runtime stack:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x9 pc=0x7f47940c0bce]
```
 
<img width="843" alt="截屏2023-02-24 16 59 58" src="https://user-images.githubusercontent.com/26307815/221136481-bded9b92-1c43-4c88-9e53-4d3e958b12f4.png">

server argo task：fouramf-rv4p5
cmd：
```
deploy_config: fouramf-server-cluster-2c16m-querynode4-datanode1
other_params: --milvus_tag=2.2.0-20230224-62d0c2fa -k test_server_custom_parameters -s --deploy_retain
```

client task： fouramf-concurrent-p6zc7
cmd:
```
other_params: --host=10.104.6.71 --deploy_skip -s --case_skip_prepare_clean  --case_skip_clean_collection --async_report
case_name: -k test_concurrent_locust_custom_parameters
case_params: fouramf-client-sift-rg1-replica2-1 and fouramf-client-sift-rg1-replica2-2
```

### Expected Behavior

**server run normally, and queryNode not restart**

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、Concurrent 2 clients
3、per client：
   1. insert 10m vectors
   2. flush
   3. build HNSW index
   4. load
   5. locust search <- concurrent
```

### Anything else?

fouramf-server-cluster-2c16m-querynode4-datanode1:
```
   queryNode:
      replicas: 4
      resources:
        limits:
          cpu: 2
        requests:
          cpu: 2
    dataNode:
      replicas: 1
      resources:
        limits:
          memory: 8Gi
          cpu: 1
        requests:
          memory: 5Gi
          cpu: 1
```
fouramf-client-sift-rg1-replica2-1:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_1'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_1']
    collection_params:
      collection_name: 'RG_1'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 60
```
fouramf-client-sift-rg1-replica2-2:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_2'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_2']
    collection_params:
      collection_name: 'RG_2'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 6h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 60
```
