### ISSUE TITLE
[Bug]: [benchmark][ResourceGroup][replicas] The number of segments and vectors counted by the get_query_segment_info interface is less than the actual number

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#22525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230301-820ec0fc
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: **fouramf-brtqc**
cmd: 
```
deploy_config: fouramf-server-cluster-2c16m-querynode4-datanode1
other_params:  --milvus_tag=2.2.0-20230301-820ec0fc -k test_server_custom_parameters -s --deploy_retain
```

server: 
```
NAME                                                              READY   STATUS      RESTARTS       AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-brtqc-78-4405-etcd-0                                      1/1     Running     0              21h     10.104.5.41     4am-node12   <none>           <none>
fouramf-brtqc-78-4405-etcd-1                                      1/1     Running     0              21h     10.104.6.239    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-etcd-2                                      1/1     Running     0              21h     10.104.4.232    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-milvus-datacoord-6759d55d56-fnh5b           1/1     Running     0              21h     10.104.6.222    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-milvus-datanode-566f6696db-vh7md            1/1     Running     0              21h     10.104.1.118    4am-node10   <none>           <none>
fouramf-brtqc-78-4405-milvus-indexcoord-5c7b9b4794-bnvkm          1/1     Running     0              21h     10.104.9.78     4am-node14   <none>           <none>
fouramf-brtqc-78-4405-milvus-indexnode-57c68fc7c9-wm2d9           1/1     Running     0              21h     10.104.1.119    4am-node10   <none>           <none>
fouramf-brtqc-78-4405-milvus-proxy-79db9d9db8-q2krg               1/1     Running     0              21h     10.104.6.225    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-milvus-querycoord-56f7f9bdfc-fn8bp          1/1     Running     0              21h     10.104.6.224    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-milvus-querynode-695ddbd585-4ztxv           1/1     Running     0              21h     10.104.4.224    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-milvus-querynode-695ddbd585-fqdrj           1/1     Running     0              21h     10.104.5.37     4am-node12   <none>           <none>
fouramf-brtqc-78-4405-milvus-querynode-695ddbd585-mwfr6           1/1     Running     0              21h     10.104.6.231    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-milvus-querynode-695ddbd585-n2ljt           1/1     Running     0              21h     10.104.9.79     4am-node14   <none>           <none>
fouramf-brtqc-78-4405-milvus-rootcoord-98d998bf9-6wxsq            1/1     Running     0              21h     10.104.6.230    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-minio-0                                     1/1     Running     0              21h     10.104.6.234    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-minio-1                                     1/1     Running     0              21h     10.104.5.40     4am-node12   <none>           <none>
fouramf-brtqc-78-4405-minio-2                                     1/1     Running     0              21h     10.104.4.230    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-minio-3                                     1/1     Running     0              21h     10.104.9.84     4am-node14   <none>           <none>
fouramf-brtqc-78-4405-pulsar-bookie-0                             1/1     Running     0              21h     10.104.4.228    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-pulsar-bookie-1                             1/1     Running     0              21h     10.104.9.83     4am-node14   <none>           <none>
fouramf-brtqc-78-4405-pulsar-bookie-2                             1/1     Running     0              21h     10.104.6.240    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-bookie-init-hz9sg                    0/1     Completed   0              21h     10.104.6.221    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-broker-0                             1/1     Running     0              21h     10.104.6.220    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-proxy-0                              1/1     Running     0              21h     10.104.4.223    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-pulsar-pulsar-init-rtqrp                    0/1     Completed   0              21h     10.104.6.223    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-recovery-0                           1/1     Running     0              21h     10.104.6.229    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-zookeeper-0                          1/1     Running     0              21h     10.104.6.235    4am-node13   <none>           <none>
fouramf-brtqc-78-4405-pulsar-zookeeper-1                          1/1     Running     0              21h     10.104.4.234    4am-node11   <none>           <none>
fouramf-brtqc-78-4405-pulsar-zookeeper-2                          1/1     Running     0              21h     10.104.9.86     4am-node14   <none>           <none>
```

client argo task: **fouramf-concurrent-dcl57**
cmd:
```
other_params: --host=10.104.6.225 --deploy_skip -s --case_skip_prepare_clean  --case_skip_clean_collection --async_report
case_name: -k test_concurrent_locust_custom_parameters
case_params: fouramf-client-sift-rg1-replica2-1 and fouramf-client-sift-rg1-replica2-2
```

client log: 
collection : RG_2
![image](https://user-images.githubusercontent.com/26307815/222361416-c5bf208b-cc33-4382-acc8-bdfb359b14ea.png)

collection : RG_1
![image](https://user-images.githubusercontent.com/26307815/222361861-d01ab5b2-bfa5-44fe-82d4-912ea0bef418.png)

client argo task: **fouramf-w9mlt**
cmd:
```
other_params:  --host=10.104.6.225 --deploy_skip -s --case_skip_prepare  --case_skip_clean_collection -k test_concurrent_locust_custom_parameters --async_report
case_params: fouramf-client-sift-rg1-replica2-transfer-replica1
```
client log:
![image](https://user-images.githubusercontent.com/26307815/222363424-78474fc1-c268-405a-816f-8c50cabbc690.png)

### Expected Behavior

**result returned from get_query_segment_info is correct**

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、Concurrent 2 clients
3、per client：
   1. insert 10m vectors
   2. flush
   3. build HNSW index
   4. load
<get_query_segment_info> 《- return result not match
   5. locust search <- concurrent

4、transfer one replica of RG_1 to RG_2
   1. get_query_segment_info <- result is correct
   2. locust search RG_1 <- concurrent
```

### Anything else?

fouramf-server-cluster-2c16m-querynode4-datanode1:
```
   queryNode:
      replicas: 4
      resources:
        limits:
          cpu: 2
        requests:
          cpu: 2
    dataNode:
      replicas: 1
      resources:
        limits:
          memory: 8Gi
          cpu: 1
        requests:
          memory: 5Gi
          cpu: 1
```
fouramf-client-sift-rg1-replica2-1:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_1'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_1']
    collection_params:
      collection_name: 'RG_1'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 60
```
fouramf-client-sift-rg1-replica2-2:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_2'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_2']
    collection_params:
      collection_name: 'RG_2'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 6h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 60
```

fouramf-client-sift-rg1-replica2-transfer-replica1:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_replicas:
          - source: 'RG_1'
            target: 'RG_2'
            collection_name: 'RG_1'
            num_replica: 1
    load_params:
      replica_number: 2
      _resource_groups: ['RG_1']
    dataset_params:
      collection_name: 'RG_1'
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 600
```
