### ISSUE TITLE
[Bug]: [benchmark][ResourceGroup][replicas] The CPU usage of queryNode dropped for nearly 2 hours in the middle

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#22552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230302-a58abe16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

serevr argo task: fouramf-8fjv2
cmd:
```
deploy_config: fouramf-server-cluster-2c16m-querynode4-datanode1
other_params:   --milvus_tag=2.2.0-20230302-a58abe16 -k test_server_custom_parameters -s --deploy_retain
```

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-8fjv2-74-7086-etcd-0                                      1/1     Running     0               19h     10.104.9.28    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-etcd-1                                      1/1     Running     0               19h     10.104.4.42    4am-node11   <none>           <none>
fouramf-8fjv2-74-7086-etcd-2                                      1/1     Running     0               19h     10.104.6.35    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-milvus-datacoord-55544ff7b9-4lqnl           1/1     Running     1 (19h ago)     19h     10.104.6.29    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-milvus-datanode-66679fb7f9-cf5t8            1/1     Running     1 (19h ago)     19h     10.104.1.184   4am-node10   <none>           <none>
fouramf-8fjv2-74-7086-milvus-indexcoord-684f6f6c89-9rv28          1/1     Running     1 (19h ago)     19h     10.104.9.19    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-milvus-indexnode-7bbf778578-dwnvg           1/1     Running     0               19h     10.104.1.187   4am-node10   <none>           <none>
fouramf-8fjv2-74-7086-milvus-proxy-65854dcd97-wlw9w               1/1     Running     1 (19h ago)     19h     10.104.6.28    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-milvus-querycoord-7c49cfc7d-fmqs5           1/1     Running     1 (19h ago)     19h     10.104.4.32    4am-node11   <none>           <none>
fouramf-8fjv2-74-7086-milvus-querynode-555cf7645b-cffhz           1/1     Running     0               19h     10.104.5.204   4am-node12   <none>           <none>
fouramf-8fjv2-74-7086-milvus-querynode-555cf7645b-hn42b           1/1     Running     0               19h     10.104.9.21    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-milvus-querynode-555cf7645b-htppf           1/1     Running     0               19h     10.104.6.30    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-milvus-querynode-555cf7645b-nxcj8           1/1     Running     0               19h     10.104.4.33    4am-node11   <none>           <none>
fouramf-8fjv2-74-7086-milvus-rootcoord-7b446859c6-r54bq           1/1     Running     1 (19h ago)     19h     10.104.1.185   4am-node10   <none>           <none>
fouramf-8fjv2-74-7086-minio-0                                     1/1     Running     0               19h     10.104.4.43    4am-node11   <none>           <none>
fouramf-8fjv2-74-7086-minio-1                                     1/1     Running     0               19h     10.104.6.36    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-minio-2                                     1/1     Running     0               19h     10.104.9.30    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-minio-3                                     1/1     Running     0               19h     10.104.5.216   4am-node12   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-bookie-0                             1/1     Running     0               19h     10.104.5.213   4am-node12   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-bookie-1                             1/1     Running     0               19h     10.104.4.46    4am-node11   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-bookie-2                             1/1     Running     0               19h     10.104.6.39    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-bookie-init-drpp9                    0/1     Completed   0               19h     10.104.6.26    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-broker-0                             1/1     Running     0               19h     10.104.6.27    4am-node13   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-proxy-0                              1/1     Running     0               19h     10.104.1.186   4am-node10   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-pulsar-init-52v7t                    0/1     Completed   0               19h     10.104.9.18    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-recovery-0                           1/1     Running     0               19h     10.104.9.20    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-zookeeper-0                          1/1     Running     0               19h     10.104.5.210   4am-node12   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-zookeeper-1                          1/1     Running     0               19h     10.104.9.32    4am-node14   <none>           <none>
fouramf-8fjv2-74-7086-pulsar-zookeeper-2                          1/1     Running     0               19h     10.104.4.48    4am-node11   <none>           <none>
```

queryNode monitor:
collection RG_2:
**The CPU usage of fouramf-8fjv2-74-7086-milvus-querynode-555cf7645b-hn42b dropped, but client RG_2 search continues**
<img width="1868" alt="截屏2023-03-03 14 26 53" src="https://user-images.githubusercontent.com/26307815/222647397-cabf3718-ce23-4988-b9d5-ebb0226951af.png">
<img width="1866" alt="截屏2023-03-03 14 27 59" src="https://user-images.githubusercontent.com/26307815/222647597-ee4fee57-64f0-4288-8803-f1acdb4f2b3c.png">

collection RG_1:
<img width="1873" alt="截屏2023-03-03 14 28 39" src="https://user-images.githubusercontent.com/26307815/222647689-88969ba3-522d-44d1-a2c2-a70ac582f619.png">
**transfer one replica of collection RG_1 to RG_2**
<img width="1864" alt="截屏2023-03-03 14 29 39" src="https://user-images.githubusercontent.com/26307815/222647847-b59b7ea8-3170-4295-b2f0-1c202419d2f2.png">

client argo task: fouramf-concurrent-l695j
**Each replica has an exclusive queryNode**
cmd:
```
other_params: --host=10.104.6.28 --deploy_skip -s --case_skip_prepare_clean  --case_skip_clean_collection --async_report
case_name: -k test_concurrent_locust_custom_parameters
case_params: fouramf-client-sift-rg1-replica2-1 and fouramf-client-sift-rg1-replica2-2
```

**transfer replica**
client argo task: fouramf-sleep-jrh7p
cmd:
```
other_params:   --host=10.104.6.28 --deploy_skip -s --case_skip_prepare  --case_skip_clean_collection -k test_concurrent_locust_custom_parameters --async_report
case_params: fouramf-client-sift-rg1-replica2-transfer-replica1
```

![image](https://user-images.githubusercontent.com/26307815/222649196-624825ca-8b73-419e-8c05-699e57117c12.png)

### Expected Behavior

**The cpu usage of queryNode is stable**

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、Concurrent 2 clients
3、per client：
   1. insert 10m vectors
   2. flush
   3. build HNSW index
   4. load
   5. locust search <- concurrent

4、transfer one replica of RG_1 to RG_2
   2. locust search RG_1 <- concurrent
```

### Anything else?

fouramf-server-cluster-2c16m-querynode4-datanode1:
```
   queryNode:
      replicas: 4
      resources:
        limits:
          cpu: 2
        requests:
          cpu: 2
    dataNode:
      replicas: 1
      resources:
        limits:
          memory: 8Gi
          cpu: 1
        requests:
          memory: 5Gi
          cpu: 1
```
fouramf-client-sift-rg1-replica2-1:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_1'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_1']
    collection_params:
      collection_name: 'RG_1'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 3600
```
fouramf-client-sift-rg1-replica2-2:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_nodes:
          - source: '__default_resource_group'
            target: 'RG_2'
            num_node: 2
    load_params:
      replica_number: 2
      _resource_groups: ['RG_2']
    collection_params:
      collection_name: 'RG_2'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 6h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 3600
```

fouramf-client-sift-rg1-replica2-transfer-replica1:
```
    resource_groups_params:
      reset: false
      groups:
        transfer_replicas:
          - source: 'RG_1'
            target: 'RG_2'
            collection_name: 'RG_1'
            num_replica: 1
    load_params:
      replica_number: 2
      _resource_groups: ['RG_1']
    dataset_params:
      collection_name: 'RG_1'
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 50
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 1
          search_param:
            ef: 64
          timeout: 600
```
