### ISSUE TITLE
[Bug]: [benchmark][LoadBalance] Under multiple collections, queryNode memory distribution is uneven

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#23365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230411-9075cede
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task:  fouramf-rrg7q
client argo task:  fouramf-concurrent-hwn9k

server: 
```
NAME                                                              READY   STATUS      RESTARTS       AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-rrg7q-87-5383-etcd-0                                      1/1     Running     0              142m    10.104.9.169    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-etcd-1                                      1/1     Running     0              142m    10.104.1.161    4am-node10   <none>           <none>
fouramf-rrg7q-87-5383-etcd-2                                      1/1     Running     0              142m    10.104.6.19     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-milvus-datacoord-5f45989cc5-dw99k           1/1     Running     1 (138m ago)   142m    10.104.9.164    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-milvus-datanode-5c84779cbd-grx22            1/1     Running     1 (138m ago)   142m    10.104.6.12     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-milvus-indexcoord-7d7dd988d-z6t7v           1/1     Running     1 (138m ago)   142m    10.104.5.110    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-milvus-indexnode-68547df7c7-qnk7q           1/1     Running     0              142m    10.104.9.165    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-milvus-proxy-79c666b8f8-zpnxm               1/1     Running     1 (138m ago)   142m    10.104.5.103    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querycoord-6b9546b97f-fgg7p          1/1     Running     1 (138m ago)   142m    10.104.5.107    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-529v9           1/1     Running     0              142m    10.104.4.183    4am-node11   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-5xtw8           1/1     Running     0              142m    10.104.1.159    4am-node10   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-h8vcn           1/1     Running     0              142m    10.104.5.112    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-kfbqb           1/1     Running     0              142m    10.104.9.163    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-l6n9m           1/1     Running     0              142m    10.104.1.157    4am-node10   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-qh9th           1/1     Running     0              142m    10.104.5.111    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-rl9gq           1/1     Running     0              142m    10.104.4.184    4am-node11   <none>           <none>
fouramf-rrg7q-87-5383-milvus-querynode-675d86fb99-zt42x           1/1     Running     0              142m    10.104.6.11     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-milvus-rootcoord-b88f69b9c-84p29            1/1     Running     1 (138m ago)   142m    10.104.5.106    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-minio-0                                     1/1     Running     0              142m    10.104.5.114    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-minio-1                                     1/1     Running     0              142m    10.104.1.163    4am-node10   <none>           <none>
fouramf-rrg7q-87-5383-minio-2                                     1/1     Running     0              142m    10.104.6.22     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-minio-3                                     1/1     Running     0              142m    10.104.9.172    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-bookie-0                             1/1     Running     0              142m    10.104.9.170    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-bookie-1                             1/1     Running     0              142m    10.104.6.25     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-bookie-2                             1/1     Running     0              142m    10.104.5.117    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-bookie-init-qg76j                    0/1     Completed   0              142m    10.104.5.108    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-broker-0                             1/1     Running     0              142m    10.104.5.109    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-proxy-0                              1/1     Running     0              142m    10.104.4.182    4am-node11   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-pulsar-init-qqsnz                    0/1     Completed   0              142m    10.104.5.104    4am-node12   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-recovery-0                           1/1     Running     0              142m    10.104.1.158    4am-node10   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-zookeeper-0                          1/1     Running     0              142m    10.104.6.18     4am-node13   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-zookeeper-1                          1/1     Running     0              141m    10.104.9.174    4am-node14   <none>           <none>
fouramf-rrg7q-87-5383-pulsar-zookeeper-2                          1/1     Running     0              141m    10.104.4.186    4am-node11   <none>           <none>
```
<img width="1847" alt="gohm9h9Kdi" src="https://user-images.githubusercontent.com/26307815/231150104-6d2a2874-5c0e-4d99-92ac-5fba92156277.png">

<img width="1862" alt="rF3JPz6rUx" src="https://user-images.githubusercontent.com/26307815/231150143-c619dee1-ef48-4bc2-9d01-7148c4d0a483.png">

client  collections's segments:
```
collection name: fouram_kodTWxcu
[segmentID: 440717602273300939
collectionID: 440717602273100844
partitionID: 440717602273100845
num_rows: 200689
state: Sealed
nodeIds: 1
, segmentID: 440717602273300920
collectionID: 440717602273100844
partitionID: 440717602273100845
num_rows: 199971
state: Sealed
nodeIds: 3
, segmentID: 440717602273300943
collectionID: 440717602273100844
partitionID: 440717602273100845
num_rows: 199396
state: Sealed
nodeIds: 5
, segmentID: 440717602273300935
collectionID: 440717602273100844
partitionID: 440717602273100845
num_rows: 200167
state: Sealed
nodeIds: 7
, segmentID: 440717602273300931
collectionID: 440717602273100844
partitionID: 440717602273100845
num_rows: 199777
state: Sealed
nodeIds: 4
]
collection name: fouram_VyERhhUA
[segmentID: 440717602273300945
collectionID: 440717602273100853
partitionID: 440717602273100854
num_rows: 199777
state: Sealed
nodeIds: 7
, segmentID: 440717602273300937
collectionID: 440717602273100853
partitionID: 440717602273100854
num_rows: 199396
state: Sealed
nodeIds: 1
, segmentID: 440717602273300932
collectionID: 440717602273100853
partitionID: 440717602273100854
num_rows: 200689
state: Sealed
nodeIds: 8
, segmentID: 440717602273300940
collectionID: 440717602273100853
partitionID: 440717602273100854
num_rows: 199971
state: Sealed
nodeIds: 2
, segmentID: 440717602273300923
collectionID: 440717602273100853
partitionID: 440717602273100854
num_rows: 200167
state: Sealed
nodeIds: 3
]
collection name: fouram_Yjype7Ok
[segmentID: 440717602273300917
collectionID: 440717602273100858
partitionID: 440717602273100859
num_rows: 199971
state: Sealed
nodeIds: 8
, segmentID: 440717602273300934
collectionID: 440717602273100858
partitionID: 440717602273100859
num_rows: 200167
state: Sealed
nodeIds: 2
, segmentID: 440717602273300930
collectionID: 440717602273100858
partitionID: 440717602273100859
num_rows: 199777
state: Sealed
nodeIds: 9
, segmentID: 440717602273300938
collectionID: 440717602273100858
partitionID: 440717602273100859
num_rows: 200689
state: Sealed
nodeIds: 3
, segmentID: 440717602273300942
collectionID: 440717602273100858
partitionID: 440717602273100859
num_rows: 199396
state: Sealed
nodeIds: 5
]
collection name: fouram_25nJ0Tw9
[segmentID: 440717602273300949
collectionID: 440717602273100868
partitionID: 440717602273100869
num_rows: 200689
state: Sealed
nodeIds: 9
, segmentID: 440717602273300951
collectionID: 440717602273100868
partitionID: 440717602273100869
num_rows: 199971
state: Sealed
nodeIds: 5
, segmentID: 440717602273300952
collectionID: 440717602273100868
partitionID: 440717602273100869
num_rows: 199777
state: Sealed
nodeIds: 7
, segmentID: 440717602273300948
collectionID: 440717602273100868
partitionID: 440717602273100869
num_rows: 200167
state: Sealed
nodeIds: 4
, segmentID: 440717602273300950
collectionID: 440717602273100868
partitionID: 440717602273100869
num_rows: 199396
state: Sealed
nodeIds: 1
]
collection name: fouram_PbUwV9EH
[segmentID: 440717602273300941
collectionID: 440717602273100873
partitionID: 440717602273100874
num_rows: 199396
state: Sealed
nodeIds: 4
, segmentID: 440717602273300944
collectionID: 440717602273100873
partitionID: 440717602273100874
num_rows: 199971
state: Sealed
nodeIds: 8
, segmentID: 440717602273300933
collectionID: 440717602273100873
partitionID: 440717602273100874
num_rows: 200167
state: Sealed
nodeIds: 2
, segmentID: 440717602273300936
collectionID: 440717602273100873
partitionID: 440717602273100874
num_rows: 200689
state: Sealed
nodeIds: 9
, segmentID: 440717602273300929
collectionID: 440717602273100873
partitionID: 440717602273100874
num_rows: 199777
state: Sealed
nodeIds: 5
]
```

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、Concurrent 5 clients
3、per client：
   1. insert 1m vectors
   2. flush
   3. build IVF_SQ8 index
   4. load
   5. locust search <- concurrent
```

### Anything else?

server config fouramf-server-cluster-loadbalance-8qn:
```
queryNode:
  resources:
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 8
      memory: 32Gi
  replicas: 8
indexNode:
  resources:
    limits:
      cpu: '8.0'
      memory: 16Gi
    requests:
      cpu: '5.0'
      memory: 9Gi
dataNode:
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 2
      memory: 5Gi
  replicas: 1
cluster:
  enabled: true
pulsar:
  bookkeeper:
    volumes:
      journal:
        storageClassName: local-path
      ledgers:
        storageClassName: local-path
  zookeeper:
    volumes:
      data:
        storageClassName: local-path
kafka:
  persistence:
    storageClass: local-path
minio:
  persistence:
    storageClass: local-path
  metrics:
    serviceMonitor:
      enabled: false
etcd:
  global:
    storageClass: local-path
  metrics:
    enabled: true
    podMonitor:
      enabled: true
metrics:
  serviceMonitor:
    enabled: true
log:
  level: debug
extraConfigFiles:
  user.yaml: |
    queryCoord:
      balancer: ScoreBasedBalancer  
      globalRowCountFactor: 0.1
      scoreUnbalanceTolerationFactor: 1.3
image:
  all:
    repository: harbor.milvus.io/milvus/milvus
    tag: 2.2.0-20230411-9075cede
```

client config fouramf-client-loadbalance-5shard:
```
dataset_params:
  dim: 128
  dataset_name: sift
  dataset_size: 1m
  ni_per: 1000
  metric_type: L2
collection_params:
  shards_num: 5
index_params:
  index_type: IVF_SQ8
  index_param:
    nlist: 1024
concurrent_params:
  concurrent_number:
    - 1
  during_time: 1m
  interval: 20
concurrent_tasks:
  - type: search
    weight: 1
    params:
      nq: 1
      top_k: 1
      search_param:
        nprobe: 16
      timeout: 60
      random_data: true
```
