### ISSUE TITLE
[Bug]: [benchmark][LoadBalance] Scale out queryNode, after load balancing, the old queryNode memory will not drop

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#23367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230411-9075cede
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-79t9p
client argo task: fouramf-s2z28
scale argo task: fouram-scale-fh8ch

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-79t9p-9-7793-etcd-0                                       1/1     Running     0               4m13s   10.104.5.98     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-etcd-1                                       1/1     Running     0               4m12s   10.104.4.176    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-etcd-2                                       1/1     Running     0               4m12s   10.104.9.162    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-milvus-datacoord-5d58c5cfff-hcfkq            1/1     Running     0               4m12s   10.104.5.90     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-datanode-85db786f5-7qk2c              1/1     Running     0               4m13s   10.104.5.86     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-indexcoord-857d8c5d7f-klfm5           1/1     Running     0               4m13s   10.104.5.89     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-indexnode-6c4b874f4-2sjn4             1/1     Running     0               4m13s   10.104.6.5      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-milvus-proxy-5cf88cc98f-wqq6q                1/1     Running     0               4m13s   10.104.4.164    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-milvus-querycoord-c79c944b8-g6pgb            1/1     Running     0               4m13s   10.104.6.4      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-4kvks            1/1     Running     0               4m13s   10.104.9.157    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-bvjlb            1/1     Running     0               4m13s   10.104.5.88     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-sncv4            1/1     Running     0               4m13s   10.104.1.152    4am-node10   <none>           <none>
fouramf-79t9p-9-7793-milvus-rootcoord-5d57847d6-546mp             1/1     Running     0               4m13s   10.104.5.87     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-minio-0                                      1/1     Running     0               4m13s   10.104.4.171    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-minio-1                                      1/1     Running     0               4m13s   10.104.5.97     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-minio-2                                      1/1     Running     0               4m12s   10.104.6.8      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-minio-3                                      1/1     Running     0               4m12s   10.104.9.161    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-0                              1/1     Running     0               4m13s   10.104.5.93     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-1                              1/1     Running     0               4m12s   10.104.4.179    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-2                              1/1     Running     0               4m12s   10.104.1.156    4am-node10   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-init-lfjcp                     0/1     Completed   0               4m13s   10.104.5.78     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-broker-0                              1/1     Running     0               4m13s   10.104.5.83     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-proxy-0                               1/1     Running     0               4m13s   10.104.4.162    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-pulsar-init-mlknq                     0/1     Completed   0               4m13s   10.104.5.80     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-recovery-0                            1/1     Running     0               4m13s   10.104.5.81     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-0                           1/1     Running     0               4m13s   10.104.4.170    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-1                           1/1     Running     0               3m30s   10.104.5.100    4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-2                           1/1     Running     0               2m55s   10.104.6.10     4am-node13   <none>           <none> 
```
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-79t9p-9-7793-etcd-0                                       1/1     Running     0               73s     10.104.5.24     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-etcd-1                                       1/1     Running     0               2m26s   10.104.4.204    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-etcd-2                                       1/1     Running     0               3m36s   10.104.9.234    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-milvus-datacoord-5d58c5cfff-hcfkq            1/1     Running     0               166m    10.104.5.90     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-datanode-85db786f5-7qk2c              1/1     Running     0               166m    10.104.5.86     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-indexcoord-857d8c5d7f-klfm5           1/1     Running     0               166m    10.104.5.89     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-indexnode-6c4b874f4-2sjn4             1/1     Running     0               166m    10.104.6.5      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-milvus-proxy-5cf88cc98f-wqq6q                1/1     Running     0               166m    10.104.4.164    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-milvus-querycoord-c79c944b8-g6pgb            1/1     Running     0               166m    10.104.6.4      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-4kvks            1/1     Running     0               166m    10.104.9.157    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-bvjlb            1/1     Running     0               166m    10.104.5.88     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-hz2vl            1/1     Running     0               3m42s   10.104.4.203    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-milvus-querynode-86d4fb74bd-sncv4            1/1     Running     0               166m    10.104.1.152    4am-node10   <none>           <none>
fouramf-79t9p-9-7793-milvus-rootcoord-5d57847d6-546mp             1/1     Running     0               166m    10.104.5.87     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-minio-0                                      1/1     Running     0               166m    10.104.4.171    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-minio-1                                      1/1     Running     0               166m    10.104.5.97     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-minio-2                                      1/1     Running     0               166m    10.104.6.8      4am-node13   <none>           <none>
fouramf-79t9p-9-7793-minio-3                                      1/1     Running     0               166m    10.104.9.161    4am-node14   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-0                              1/1     Running     0               166m    10.104.5.93     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-1                              1/1     Running     0               166m    10.104.4.179    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-bookie-2                              1/1     Running     0               166m    10.104.1.156    4am-node10   <none>           <none>
fouramf-79t9p-9-7793-pulsar-broker-0                              1/1     Running     0               166m    10.104.5.83     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-proxy-0                               1/1     Running     0               166m    10.104.4.162    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-recovery-0                            1/1     Running     0               166m    10.104.5.81     4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-0                           1/1     Running     0               166m    10.104.4.170    4am-node11   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-1                           1/1     Running     0               166m    10.104.5.100    4am-node12   <none>           <none>
fouramf-79t9p-9-7793-pulsar-zookeeper-2                           1/1     Running     0               165m    10.104.6.10     4am-node13   <none>           <none>
```
<img width="1838" alt="截屏2023-04-11 20 19 54" src="https://user-images.githubusercontent.com/26307815/231160601-1083346b-f1da-4862-a3a1-4b018fee9c97.png">
<img width="1867" alt="截屏2023-04-11 20 20 24" src="https://user-images.githubusercontent.com/26307815/231160614-5f35196a-27a8-4920-9604-566643f5b0f5.png">
<img width="1868" alt="截屏2023-04-11 20 20 41" src="https://user-images.githubusercontent.com/26307815/231160619-537710ca-852a-4328-8770-718ff0600033.png">

client : 
<img width="1498" alt="截屏2023-04-11 20 19 20" src="https://user-images.githubusercontent.com/26307815/231160297-a499b242-c663-4eb3-85ba-cf5b2c705c9b.png">

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、client：
   1. create collection
   2. build index of IVF_SQ8
   3. insert 20m vectors
   4. flush
   5. rebuild IVF_SQ8 index
   6. load
   7. locust search <- concurrent
```

### Anything else?

server config, fouramf-server-cluster-loadbalance:
```
queryNode:
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi
  replicas: 3
indexNode:
  resources:
    limits:
      cpu: '8.0'
      memory: 16Gi
    requests:
      cpu: '5.0'
      memory: 9Gi
dataNode:
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 2
      memory: 5Gi
  replicas: 1
cluster:
  enabled: true
pulsar:
  bookkeeper:
    volumes:
      journal:
        storageClassName: local-path
      ledgers:
        storageClassName: local-path
  zookeeper:
    volumes:
      data:
        storageClassName: local-path
kafka:
  persistence:
    storageClass: local-path
minio:
  persistence:
    storageClass: local-path
  metrics:
    serviceMonitor:
      enabled: false
etcd:
  global:
    storageClass: local-path
  metrics:
    enabled: true
    podMonitor:
      enabled: true
metrics:
  serviceMonitor:
    enabled: true
log:
  level: debug
extraConfigFiles:
  user.yaml: |
    dataCoord:
      segment:
        maxSize: 51
    queryCoord:
      balancer: ScoreBasedBalancer  
      globalRowCountFactor: 0.1
      scoreUnbalanceTolerationFactor: 1.3
image:
  all:
    repository: harbor.milvus.io/milvus/milvus
    tag: 2.2.0-20230411-9075cede
```

client config, fouramf-client-loadbalance:
```
dataset_params:
  dim: 128
  dataset_name: sift
  dataset_size: 20m
  ni_per: 10000
  metric_type: L2
index_params:
  index_type: IVF_SQ8
  index_param:
    nlist: 1024
concurrent_params:
  concurrent_number:
    - 1
  during_time: 1m
  interval: 20
concurrent_tasks:
  - type: search
    weight: 1
    params:
      nq: 1
      top_k: 1
      search_param:
        nprobe: 16
      timeout: 60
      random_data: true
```
