### ISSUE TITLE
[Bug]: There are 132 flushed segments, but there is no completed compaction from the logs and monitoring

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#23378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bigsheeper-2304-memory-sync-3849f72-20230410
- Deployment mode(standalone or cluster): cluster 
- MQ type(rocksmq, pulsar or kafka): pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. milvus config
```
dataNode:
      memory:
        forceSyncPeriod: 2
        forceSyncSegmentRatio: 0.8
        watermarkCluster: 0.3
    etcd:
      endpoints:
      - fouramf-6s79w-op-73-7527-etcd.qa-milvus:2379
      rootPath: fouramf-6s79w-op-73-7527
    log:
      level: debug
    messageQueue: pulsar
    minio:
      accessKeyID: minioadmin
      address: fouramf-6s79w-op-73-7527-minio.qa-milvus
      bucketName: fouramf-6s79w-op-73-7527
      port: 9000
      secretAccessKey: minioadmin
    msgChannel:
      chanNamePrefix:
        cluster: fouramf-6s79w-op-73-7527
    pulsar:
      address: fouramf-6s79w-op-73-7527-pulsar-proxy.qa-milvus
      port: 6650
```
2. Test steps
   a. create collection (dim 128, shards_num=2) -> create hnsw index -> insert 5k entities -> load
   b. concurrent 120 users, during 1h
       - release
       - scene_insert_partition: create partition -> insert 10w entities (per_ni=1000) -> drop partition
3. birdwatcher `show segment --collection 440721844035389281 --state Flushed`
```
SegmentID: 440721844073819261 State: Flushed, Row Count:46934
--- Growing: 0, Sealed: 0, Flushed: 132
--- Total Segments: 132, row count: 6161000
```
4.  monitor -> datanode -> Compaction Latency
![image](https://user-images.githubusercontent.com/27288593/231343938-003bf947-0349-4890-b96d-1211cf4d16ae.png)

5. There is no indication in the datanode / datacoord logs that `compaction done`, start to execute compaction`, `generate a plan for small candidates`, `generate a plan for priority candidates`

![image](https://user-images.githubusercontent.com/27288593/231344628-58c4dcfa-5e84-4640-81b6-3904ba49f1cd.png)

### Milvus Log

`fouram` cluster and `qa-milvus` ns:
```
fouramf-6s79w-op-73-7527-etcd-0                                   1/1     Running     0                47h     10.104.9.65     4am-node14   <none>           <none>
fouramf-6s79w-op-73-7527-etcd-1                                   1/1     Running     0                47h     10.104.6.110    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-etcd-2                                   1/1     Running     0                47h     10.104.4.98     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-datacoord-cc7f9c9d4-mzxnh         1/1     Running     0                14h     10.104.4.69     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-datanode-5844bd585b-7wdhd         1/1     Running     0                14h     10.104.4.66     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-indexcoord-649fc4f7d8-phx69       1/1     Running     0                14h     10.104.1.204    4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-indexnode-697b4cc75b-4l76b        1/1     Running     0                14h     10.104.4.68     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-proxy-57d85555dc-xdkhq            1/1     Running     0                14h     10.104.4.67     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-querycoord-67d977dcd8-m5klv       1/1     Running     0                14h     10.104.1.201    4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-querynode-857ddd4f68-wgl6q        1/1     Running     0                14h     10.104.1.200    4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-milvus-rootcoord-7469f775bd-8sgwt        1/1     Running     0                14h     10.104.4.70     4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-minio-0                                  1/1     Running     0                47h     10.104.9.66     4am-node14   <none>           <none>
fouramf-6s79w-op-73-7527-minio-1                                  1/1     Running     0                47h     10.104.6.111    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-minio-2                                  1/1     Running     0                47h     10.104.1.36     4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-minio-3                                  1/1     Running     0                47h     10.104.4.104    4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-bookie-0                          1/1     Running     0                47h     10.104.6.115    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-bookie-1                          1/1     Running     0                47h     10.104.4.108    4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-bookie-2                          1/1     Running     0                47h     10.104.1.39     4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-bookie-init-7hzxh                 0/1     Completed   0                47h     10.104.6.104    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-broker-0                          1/1     Running     0                47h     10.104.1.34     4am-node10   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-proxy-0                           1/1     Running     0                47h     10.104.6.106    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-pulsar-init-g9wm6                 0/1     Completed   0                47h     10.104.9.63     4am-node14   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-recovery-0                        1/1     Running     0                47h     10.104.6.105    4am-node13   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-zookeeper-0                       1/1     Running     0                47h     10.104.4.106    4am-node11   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-zookeeper-1                       1/1     Running     0                47h     10.104.9.68     4am-node14   <none>           <none>
fouramf-6s79w-op-73-7527-pulsar-zookeeper-2                       1/1     Running     0                47h     10.104.5.10     4am-node12   <none>           <none>
```
