### ISSUE TITLE
[Bug]: [benchmark][cluster] Build index stuck

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#23469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230417-c810c97b
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.7.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-prqb4

server:
```
NAME                                                              READY   STATUS      RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-prqb4-15-6729-etcd-0                                      1/1     Running     0                99m     10.104.5.16     4am-node12   <none>           <none>
fouramf-prqb4-15-6729-etcd-1                                      1/1     Running     0                99m     10.104.4.46     4am-node11   <none>           <none>
fouramf-prqb4-15-6729-etcd-2                                      1/1     Running     0                99m     10.104.1.158    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-datacoord-bf946498b-kbb8c            1/1     Running     0                99m     10.104.1.150    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-datanode-5bb5f96575-gmnv8            1/1     Running     0                99m     10.104.1.149    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-indexcoord-8499fff57-lg248           1/1     Running     0                99m     10.104.1.154    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-indexnode-df4645c66-j7qpz            1/1     Running     0                99m     10.104.6.43     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-milvus-proxy-76b8f5f689-mq8vz               1/1     Running     0                99m     10.104.1.155    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-querycoord-74f985dd46-7hr66          1/1     Running     0                99m     10.104.6.46     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-milvus-querynode-5d9c6dc8d-72rh4            1/1     Running     0                99m     10.104.6.40     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-milvus-querynode-5d9c6dc8d-84dh9            1/1     Running     0                99m     10.104.9.65     4am-node14   <none>           <none>
fouramf-prqb4-15-6729-milvus-querynode-5d9c6dc8d-9bmd9            1/1     Running     0                99m     10.104.1.142    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-milvus-querynode-5d9c6dc8d-pzd28            1/1     Running     0                99m     10.104.5.5      4am-node12   <none>           <none>
fouramf-prqb4-15-6729-milvus-rootcoord-75964954b8-pjr5m           1/1     Running     0                99m     10.104.6.42     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-minio-0                                     1/1     Running     0                99m     10.104.5.14     4am-node12   <none>           <none>
fouramf-prqb4-15-6729-minio-1                                     1/1     Running     0                99m     10.104.4.50     4am-node11   <none>           <none>
fouramf-prqb4-15-6729-minio-2                                     1/1     Running     0                99m     10.104.1.161    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-minio-3                                     1/1     Running     0                99m     10.104.6.48     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-pulsar-bookie-0                             1/1     Running     0                99m     10.104.5.19     4am-node12   <none>           <none>
fouramf-prqb4-15-6729-pulsar-bookie-1                             1/1     Running     0                99m     10.104.4.51     4am-node11   <none>           <none>
fouramf-prqb4-15-6729-pulsar-bookie-2                             1/1     Running     0                99m     10.104.1.163    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-pulsar-bookie-init-nzx4g                    0/1     Completed   0                99m     10.104.1.151    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-pulsar-broker-0                             1/1     Running     0                99m     10.104.1.148    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-pulsar-proxy-0                              1/1     Running     0                99m     10.104.4.44     4am-node11   <none>           <none>
fouramf-prqb4-15-6729-pulsar-pulsar-init-9khbv                    0/1     Completed   0                99m     10.104.1.153    4am-node10   <none>           <none>
fouramf-prqb4-15-6729-pulsar-recovery-0                           1/1     Running     0                99m     10.104.6.45     4am-node13   <none>           <none>
fouramf-prqb4-15-6729-pulsar-zookeeper-0                          1/1     Running     0                99m     10.104.5.17     4am-node12   <none>           <none>
fouramf-prqb4-15-6729-pulsar-zookeeper-1                          1/1     Running     0                98m     10.104.4.53     4am-node11   <none>           <none>
fouramf-prqb4-15-6729-pulsar-zookeeper-2                          1/1     Running     0                98m     10.104.1.168    4am-node10   <none>           <none>
```
<img width="1390" alt="截屏2023-04-17 17 41 03" src="https://user-images.githubusercontent.com/26307815/232447230-73acb24a-928d-4c7b-8cd8-17cbcc7e3d17.png">
<img width="1381" alt="截屏2023-04-17 17 44 02" src="https://user-images.githubusercontent.com/26307815/232447980-2d35386c-68f3-4a92-b0e7-815cdf426936.png">

client:
<img width="1479" alt="截屏2023-04-17 17 40 29" src="https://user-images.githubusercontent.com/26307815/232447074-896d8427-ae01-443d-8bd3-5cf6ac3898ee.png">

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、client：
   1. create collection
   2. build index of IVF_SQ8
   3. insert 20m vectors
   4. flush
   5. rebuild IVF_SQ8 index <- stuck, client has no response
```

### Anything else?

server config **fouramf-server-cluster-loadbalance-4qn**:
```
    queryNode:
      replicas: 4
      resources:
        limits:
          memory: 32Gi
          cpu: 8
        requests:
          memory: 16Gi
          cpu: 4
    dataNode:
      replicas: 1
      resources:
        limits:
          memory: 8Gi
          cpu: 2
        requests:
          memory: 5Gi
          cpu: 2
    extraConfigFiles:
      user.yaml: |+
        dataCoord:
          segment:
            maxSize: 51
        queryCoord:
          balancer: ScoreBasedBalancer  
          globalRowCountFactor: 0.2
          scoreUnbalanceTolerationFactor: 1.2
```

client config **fouramf-client-loadbalance-replica2**:
```
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 20m
      ni_per: 10000
      metric_type: L2
    load_params: 
      replica_number: 2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 1024
    concurrent_params:
      concurrent_number: [1]
      during_time: 1m
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 16
          timeout: 60
          random_data: true
```
