### ISSUE TITLE
Index building time increased with type IVF_PQ

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2357]
**Describe the bug**
![Screenshot_2020-05-15 cpu_build_perf_pq(1)](https://user-images.githubusercontent.com/56623710/82032469-d38e4580-96cd-11ea-8540-4af961e09b16.png)
![Screenshot_2020-05-15 cpu_build_perf_pq](https://user-images.githubusercontent.com/56623710/82032471-d5580900-96cd-11ea-90f8-a81a56b0e2de.png)

**Steps/Code to reproduce behavior**
build params
```
      server:
        db_config.primary_path: /test/milvus/db_data_8/sift_1m_128_128_l2_pq
        cache_config.cpu_cache_capacity: 32
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 1
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
      collection_name: sift_1m_128_128_l2
      index_type: ivf_pq
      index_param:
        nlist: 8092
        m: 32
```
**Expected behavior**

**Environment details**
old-commit: `3c46b22d730704903e5746c488edd446fee3b745`
new-commit: `cb92b10c1d7894aa79e1a9673fe29a02eb2975bb`

**Screenshots**

**Additional context**
