### ISSUE TITLE
[Bug]: Milvus does not free disk space when deleting collections

### ISSUE THREAD

**Issue by novemberdude** [milvus-io/milvus#23643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2 (Install with docker image: milvusdb/milvus:2.2.2-latest)
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16 core / 24 GB
- GPU: 
- Others:
```

### Current Behavior

I have two original collections, with total about 800k 768-demension vectors

### Before deleting collections

![all_collection](https://user-images.githubusercontent.com/40812793/233889644-52da1614-2a67-4f88-9eb7-5fc048fb7d55.png)

The disk usage look like this:

![before_delete_collection](https://user-images.githubusercontent.com/40812793/233889719-2f9d512b-8863-418a-bced-06c4270d2eb5.png)

### After delete all my collections
- The disk usage did not descrease

![image](https://user-images.githubusercontent.com/40812793/233889827-5fa98c4b-2c57-420d-94e8-969f4d0dda55.png)
![after_delete_all_collections](https://user-images.githubusercontent.com/40812793/233889794-db00c0bc-8933-4877-aecf-b6bcad21cba6.png)

### Expected Behavior

When I delete a collection, Milvus must free all disk usage of it.

### Steps To Reproduce

```markdown
1. Create a collection and tnsert vectors to this.
2. Delete the collection
```

### Anything else?

Here is my docker-compose.yml file to deploy all services

```yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    restart: always
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:2.2.2-latest
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "9531:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    restart: always

  attu:
    container_name: attu
    image: zilliz/attu:latest
    environment:
      MILVUS_URL: standalone:19530
    ports:
      - "8005:3000"
    restart: always

networks:
  default:
    name: milvus
```
_No response_
