### ISSUE TITLE
[Bug]: Pod CPU and memory grows linearly.

### ISSUE THREAD

**Issue by elonzh** [milvus-io/milvus#23670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.6
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): Alibaba Cloud Linux 3 (Soaring Falcon)
- Kernel Version : 5.10.134-12.2.al8.x86_64
- CPU/Memory: 4c8g
- GPU: None
```

### Current Behavior

I changed the milvus config and reset the data, still not working.

```
extraConfigFiles:
  user.yaml: |+
    rocksmq:
      # The path where the message is stored in rocksmq
      lrucacheratio: 0.06 # rocksdb cache memory ratio
      rocksmqPageSize: 16777216 # default is 256 MB, 256 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
      retentionTimeInMinutes: 1440 # default is 5 days, 5 * 24 * 60 minutes, The retention time of the message in rocksmq.
      retentionSizeInMB: 1024 # default is 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
      compactionInterval: 86400 # 1 day, trigger rocksdb compaction every day to remove deleted data
    rootCoord:
      # changing this value will make the cluster unavailable
      dmlChannelNum: 4
    dataCoord:
      segment:
        maxSize: 128 # Maximum size of a segment in MB
        diskSegmentMaxSize: 256 # Maximun size of a segment in MB for collection which has Disk index
```

![image](https://user-images.githubusercontent.com/8749411/233990473-92a83c4b-8400-4d17-8431-2a85aaa418ed.png)

![image](https://user-images.githubusercontent.com/8749411/233990804-370ec35b-fc25-4e68-868a-6924355ead1b.png)

![image](https://user-images.githubusercontent.com/8749411/233990731-18cdbc03-cd1d-4591-a46b-67579a25b748.png)

### Steps To Reproduce

```markdown
Just deploy the standalone server with Helm
```

### Milvus Log

https://wormhole.app/onvd4#OJRkw87z5RA7pAWlu2VmbQ
