### ISSUE TITLE
[Bug]: [benchmark][balance] After `kubectl rollout restart` Milvus's pods, the number of segments loaded less than before

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#23815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.7-20230428-cbcdebdd
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.7.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. test case: test_concurrent_locust_score_balance_cluster
2. client argo task: fouramf-bpmb6
3. scale queryNode 4-5: fouram-scale-fdp9d
4. scale queryNode 5-6: fouram-scale-hs9t2
5. rollout restart:`kubectl get deploy -n qa-milvus |grep fouramf-bpmb6-94-5413 | awk '{print $1}' | xargs kubectl rollout restart deploy -n qa-milvus`

server:
```
NAME                                                              READY   STATUS             RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-bpmb6-94-5413-etcd-0                                      1/1     Running            0                161m    10.104.17.54    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-etcd-1                                      1/1     Running            0                162m    10.104.4.106    4am-node11   <none>           <none>
fouramf-bpmb6-94-5413-etcd-2                                      1/1     Running            0                164m    10.104.15.149   4am-node20   <none>           <none>
fouramf-bpmb6-94-5413-milvus-datacoord-69c8cd5c49-c6c7c           1/1     Running            0                23m     10.104.17.58    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-milvus-datanode-9cd6c7f66-lp2p8             1/1     Running            0                24m     10.104.24.106   4am-node29   <none>           <none>
fouramf-bpmb6-94-5413-milvus-datanode-9cd6c7f66-t2qn6             1/1     Running            0                20m     10.104.21.82    4am-node24   <none>           <none>
fouramf-bpmb6-94-5413-milvus-datanode-9cd6c7f66-xvwm7             1/1     Running            0                22m     10.104.17.59    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-milvus-indexcoord-5c994569c8-4rxld          1/1     Running            0                24m     10.104.17.56    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-milvus-indexnode-6688d84b9f-4869n           1/1     Running            0                24m     10.104.22.61    4am-node26   <none>           <none>
fouramf-bpmb6-94-5413-milvus-proxy-74c9c48d5b-8c64h               1/1     Running            0                24m     10.104.24.107   4am-node29   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querycoord-58954fb565-xssqs          1/1     Running            0                24m     10.104.17.57    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-2xkkw            1/1     Running            0                24m     10.104.6.108    4am-node13   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-bhkvv            1/1     Running            0                24m     10.104.18.37    4am-node25   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-jc5x7            1/1     Running            0                22m     10.104.24.109   4am-node29   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-jtj56            1/1     Running            0                24m     10.104.21.81    4am-node24   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-lb5lp            1/1     Running            0                22m     10.104.19.186   4am-node28   <none>           <none>
fouramf-bpmb6-94-5413-milvus-querynode-8d69dd74f-lch8c            1/1     Running            0                22m     10.104.22.62    4am-node26   <none>           <none>
fouramf-bpmb6-94-5413-milvus-rootcoord-75564d579-9kk2v            1/1     Running            0                24m     10.104.24.108   4am-node29   <none>           <none>
fouramf-bpmb6-94-5413-minio-0                                     1/1     Running            0                4h28m   10.104.17.22    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-minio-1                                     1/1     Running            0                4h28m   10.104.23.34    4am-node27   <none>           <none>
fouramf-bpmb6-94-5413-minio-2                                     1/1     Running            0                4h28m   10.104.5.152    4am-node12   <none>           <none>
fouramf-bpmb6-94-5413-minio-3                                     1/1     Running            0                4h28m   10.104.15.118   4am-node20   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-bookie-0                             1/1     Running            0                4h28m   10.104.20.131   4am-node22   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-bookie-1                             1/1     Running            0                4h28m   10.104.6.105    4am-node13   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-bookie-2                             1/1     Running            0                4h28m   10.104.23.37    4am-node27   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-broker-0                             1/1     Running            0                4h28m   10.104.4.89     4am-node11   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-proxy-0                              1/1     Running            0                4h28m   10.104.17.20    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-recovery-0                           1/1     Running            0                4h28m   10.104.23.27    4am-node27   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-zookeeper-0                          1/1     Running            0                4h28m   10.104.20.130   4am-node22   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-zookeeper-1                          1/1     Running            0                4h27m   10.104.17.28    4am-node23   <none>           <none>
fouramf-bpmb6-94-5413-pulsar-zookeeper-2                          1/1     Running            0                4h26m   10.104.24.78    4am-node29   <none>           <none>
```

### segment: from 1500 -> 500

<img width="1382" alt="截屏2023-04-28 23 56 55" src="https://user-images.githubusercontent.com/26307815/235196442-3a588a69-699b-42a8-b72b-40c9649f4497.png">
<img width="1440" alt="截屏2023-04-28 23 57 07" src="https://user-images.githubusercontent.com/26307815/235196453-495d2472-3e08-4a3a-a2e8-7c151f812cc9.png">
<img width="1381" alt="截屏2023-04-28 23 57 23" src="https://user-images.githubusercontent.com/26307815/235196460-34809e23-7cf9-4767-8373-29ed18177b67.png">
<img width="1388" alt="截屏2023-04-28 23 57 59" src="https://user-images.githubusercontent.com/26307815/235196467-ac4bfab2-27a1-4b40-a6ec-ae0c5c9d31fd.png">

### Steps To Reproduce

- Test case: test_concurrent_locust_score_balance_cluster
  - Create one collection with None data, replica=1, shards_num=2
  - Concurrently create 100 collections, each of them insert 10k vectors with 128 dim, replicas=3, shards_num=5, building FLAT index type, search with nprobe=16, nq=10, tok=100 for 5hours

- scale queryNode 4-5, 5-6
- rollout restart Milvus's pods

### Anything else?
server config:
```
queryNode:
  resources:
    limits:
      cpu: '4.0'
      memory: 16Gi
    requests:
      cpu: '3.0'
      memory: 9Gi
  replicas: 4
indexNode:
  resources:
    limits:
      cpu: '4.0'
      memory: 16Gi
    requests:
      cpu: '3.0'
      memory: 9Gi
  replicas: 1
dataNode:
  resources:
    limits:
      cpu: '2.0'
      memory: 8Gi
    requests:
      cpu: '2.0'
      memory: 5Gi
  replicas: 3
cluster:
  enabled: true
pulsar:
  bookkeeper:
    volumes:
      journal:
        storageClassName: local-path
      ledgers:
        storageClassName: local-path
  zookeeper:
    volumes:
      data:
        storageClassName: local-path
kafka:
  persistence:
    storageClass: local-path
minio:
  persistence:
    storageClass: local-path
  metrics:
    serviceMonitor:
      enabled: false
etcd:
  global:
    storageClass: local-path
  metrics:
    enabled: true
    podMonitor:
      enabled: true
metrics:
  serviceMonitor:
    enabled: true
log:
  level: debug
extraConfigFiles:
  user.yaml: |
    queryCoord:
      balancer: ScoreBasedBalancer
image:
  all:
    repository: harbor.milvus.io/milvus/milvus
    tag: 2.2.7-20230428-cbcdebdd
```

test config:
```
{
     "dataset_params": {
          "metric_type": "L2",
          "dim": 128,
          "dataset_name": "sift",
          "dataset_size": 0,
          "ni_per": 0
     },
     "collection_params": {
          "other_fields": [],
          "shards_num": 2
     },
     "load_params": {
          "replica_number": 1
     },
     "query_params": {},
     "search_params": {},
     "resource_groups_params": {
          "reset": false
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 8,
               "efConstruction": 200
          }
     },
     "concurrent_params": {
          "concurrent_number": [
               100
          ],
          "during_time": "5h",
          "interval": 20
     },
     "concurrent_tasks": [
          {
               "type": "scene_search_test",
               "weight": 1,
               "params": {
                    "dim": 128,
                    "shards_num": 5,
                    "data_size": "1w",
                    "nb": 10000,
                    "index_type": "FLAT",
                    "index_param": {},
                    "metric_type": "L2",
                    "replica_number": 3,
                    "nq": 10,
                    "top_k": 100,
                    "search_param": {
                         "nprobe": 16
                    },
                    "search_counts": 500000,
                    "new_connect": false
               }
          }
     ]
}
```
