### ISSUE TITLE
[Bug]: [benchmark]When searching, the output_fileds field is set, and the id field is returned.

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230506-7f5294b1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task : fouramf-6lbnn
case_params
```
    dataset_params:
      dataset_size: 10w
    concurrent_params:
      during_time: 10m
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            ef: 16
          output_fields:
          - float_1
          - float_vector
          timeout: 60
          random_data: true
```
 

response: 
![image](https://user-images.githubusercontent.com/48523564/236984396-8c847918-2881-4408-bead-57ad8e1137a3.png)
