### ISSUE TITLE
[Bug]: [hybird search] There is no performance gain for the gist  dataset hnsw index at an expr ratio of 1%

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#24146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230508-946ddc70
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Set the expr ratio to 1%, concurrency to 20 concurrent search , compare the performance improvement before and after optimization .

dataset: gist
metric_type: L2

image | 2.2.0-20230508-82be9e83 | 2.2.0-20230508-946ddc70
-- | -- | --
qps | 121  |  122
search latency | 123ms  |  123ms

client params:
```
    dataset_params:
      dataset_name: gist
      dim: 768
      dataset_size: 1000000
      ni_per: 10000
      metric_type: L2
    collection_params:
      other_fields:
      - float_1
      shards_num: 2
    load_params: {}
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    query_params: {}
    search_params: {}
    resource_groups_params:
      reset: false
    concurrent_params:
      concurrent_number:
      - 20
      during_time: 30m
      interval: 20
    concurrent_tasks:
    - type: search
      weight: 20
      params:
        nq: 10
        top_k: 10
        search_param:
          ef: 16
        expr:
          float_1:
            GT: -1
            LT: 10000
        guarantee_timestamp:
        output_fields:
        ignore_growing: false
        timeout: 60
        random_data: true
```

### Expected Behavior

 The higher the performance improvement for hnsw and diskann indexes as the expr ratio approaches 0 after entering hybird search pr

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors (1m)
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations (search)
        10. clean all collections or not
```
