### ISSUE TITLE
[Bug]: Standalone pod oomkilled after searching multi collections concurrent for a period of time

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230516-20054dc4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.9.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with config (you can clone my deploy task 1684222109125)
```
extraConfigFiles:{
user.yaml:"queryNode:
scheduler:
scheduleReadPolicy:
name: "user-task-polling"
common:
security:
authorizationEnabled: "true"
"
}
standalone:{
resources:{
requests:{
memory:"6Gi"
cpu:"3"
}
limits:{
memory:"12Gi"
cpu:"3"
}
}
}
}
```
2. start 10 clients to do the following thing: (each client do the same thing)
2.1 root connect, create a user and bind admin role
2.2 use the created user to connect milvus
2.3 create a collection -> create diskann index -> insert 1m-768d data -> flush -> create index again -> load -> concurrent search

After a while, standalone oomkilled.
I'm not sure the oomkilled reason is load or search. Because some collections was doing search while some collections was doing loading. Please help
standalone memory:
![image](https://github.com/milvus-io/milvus/assets/27288593/e0f5b8cc-58f6-4c45-96a2-1f23c5d23104)

- client params (configmap: 'zong-user-task-schedule'):
```
    dataset_params:
      dataset_name: gist
      dim: 768 
      dataset_size: 1000000
      ni_per: 1000
      metric_type: L2
    collection_params:
      other_fields: []
    load_params: {}
    index_params:
      index_type: DISKANN
      index_param: {}
    query_params: {}
    search_params: {}
    concurrent_params:
      concurrent_number:
        - 1
        - 20
      during_time: 3600
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 10
          top_k: 10
          search_param:
            search_list: 30
          random_data: true
```

### Steps To Reproduce
test case:
```
test_concurrent_locust_custom_parameters
```

```markdown
workflow name in fouram cluster: `fouramf-concurrent-rbac-3`
```

### Milvus Log

fouram cluster qa-milvus ns pods:
```
zong-users-xopiy-etcd-0                                           1/1     Running            0                  24h     10.104.21.238   4am-node24   <none>           <none>
zong-users-xopiy-milvus-standalone-687cbfcc87-gxd6q               1/1     Running            1 (12h ago)        24h     10.104.17.193   4am-node23   <none>           <none>
zong-users-xopiy-minio-556544bd97-tmpz2                           1/1     Running            0                  24h     10.104.17.191   4am-node23   <none>           <none>
```
