### ISSUE TITLE
[Bug]: File size grows rapidly /var/lib/docker/containers/${milvus-standalone-conainter-id}/${milvus-standalone-conainter-id}-json.log

### ISSUE THREAD

**Issue by chanjetsdp** [milvus-io/milvus#24285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  milvusdb/milvus:v2.2.5 
- Deployment mode(standalone or cluster): docker-compose standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  CentOS Linux release 7.9.2009
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When the service is unavailable, it is found that the disk is occupied by 100%. 
After analysis, it is found that the file size has increased rapidly, almost +1m/s.

/var/lib/docker/containers/${milvus-standalone-conainter-id}/${milvus-standalone-conainter-id}-json.log
tail -300f the_file
```
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=303.258µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321457393Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=443.454µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321487445Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=464.347µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321532051Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=635.994µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321552817Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=632.675µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321558261Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=594.656µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321563171Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=409.333µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.3215759Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=650.304µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321634931Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=856.164µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321641828Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=56.727µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321652186Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=638.245µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321831723Z"}
{"log":"[2023/05/22 02:57:24.321 +00:00] [DEBUG] [rmq/rmq_producer.go:47] [\"tr/send msg to stream\"] [msg=\"send msg to stream done\"] [duration=52.165µs]\n","stream":"stdout","time":"2023-05-22T02:57:24.321838665Z"}

```

### Expected Behavior

Turn off DEBUG log output, and output these logs to file in the container

### Steps To Reproduce

```markdown
1. docker-compose up -d

docker-compose.yml 

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.5
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yanliang567** [comment]
@chanjetsdp thank you for the issue. We have noticed this issue and we are trying to improve the tt logs, as well as seting info for log level. 
Here is a workaround which could reduce the log size.
 ```
 "log-driver": "json-file",
  "log-opts": {
    "max-size": "128m",
    "max-file": "3" 
  }
```

**Comment by chanjetsdp** [comment]
```
docker cp milvus-standalone:/milvus/configs/milvus.yaml milvus.yaml.milvus-standalone

#修改
log:
  level: info 
  stdout: "false" 
  file:
    rootPath: "/tmp/milvus/logs" 

#修改 docker-compose.yml 增加：

       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus-logs:/tmp/milvus/logs
       - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml.milvus-standalone:/milvus/configs/milvus.yaml
```


cat docker-compose.yml

``` yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.5
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus-logs:/tmp/milvus/logs
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml.milvus-standalone:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

```
