### ISSUE TITLE
[Bug]: The ttProtection of limitWriting doesn't seem to work and no trigger deny writing

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230523-8c1f9118
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.9.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with quota and limit config
```
quotaAndLimits:
  compactionRate:
    enabled: false
    max: -1
  ddl:
    collectionRate: -1
    enabled: false
    partitionRate: -1
  dml:
    bulkLoadRate:
      collection:
        max: -1
      max: -1
    deleteRate:
      collection:
        max: -1
      max: -1
    enabled: true
    insertRate:
      collection:
        max: 10
      max: -1
  dql:
    enabled: false
    queryRate:
      collection:
        max: -1
      max: -1
    searchRate:
      collection:
        max: 1000
      max: -1
  enabled: true
  flushRate:
    enabled: false
    max: -1
indexRate:
    enabled: false
    max: -1
  limitReading:
    coolOffSpeed: 0.9
    forceDeny: false
    queueProtection:
      enabled: false
      nqInQueueThreshold: -1
      queueLatencyThreshold: -1
    resultProtection:
      enabled: false
      maxReadResultRate: -1
  limitWriting:
    diskProtection:
      diskQuota: -1
      diskQuotaPerCollection: -1
      enabled: true
    forceDeny: false
    growingSegmentsSizeProtection:
      enabled: false
      highWaterLevel: 0.4
      lowWaterLevel: 0.2
    memProtection:
      dataNodeMemoryHighWaterLevel: 0.9
      dataNodeMemoryLowWaterLevel: 0.85
      enabled: true
      queryNodeMemoryHighWaterLevel: 0.9
      queryNodeMemoryLowWaterLevel: 0.85
    ttProtection:
      enabled: true
      maxTimeTickDelay: 290
  limits:
    maxCollectionNum: 65536
    maxCollectionNumPerDB: 65536
  quotaCenterCollectInterval: 3
```
node resource config:
```
    dataNode:
      replicas: 2
      resources:
        requests:
          memory: 2Gi
          cpu: 0.5
        limits:
          memory: 8Gi
          cpu: 0.5
    queryNode:
      replicas: 2
      resources:
        requests:
          memory: 2Gi
          cpu: 1.0
        limits:
          memory: 8Gi
          cpu: 2.0
```

2. Start 2 clients run the following test in parallel
  - create a collection with 1 shard
  - create index `{'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}}`
  - load collection
  - concurrent 1 user to run the tsaks: 
            - scene_insert_partition: create a partition -> insert 1m and ni is 5  (run 1h)
```
    concurrent_tasks:
        -
          type: scene_insert_partition
          weight: 20
          params:
            data_size: '1m'
            ni: 5
            timeout: 600
        -
          type: release
          weight: 1
          params:
            timeout: 600
```
3. Client all insert requests successful
![image](https://github.com/milvus-io/milvus/assets/27288593/184b27f2-2f9d-43f2-828c-568200c72137)

3. metrics datanode tt behind
![image](https://github.com/milvus-io/milvus/assets/27288593/87e78258-cd9c-4a9e-9e84-c833a3dbbc8f)

### Steps To Reproduce

```markdown
argo test name in 4am cluster: tt-deny-cluster-14
configmap in 4am qa ns: multi-partition-cm-small

    collection_params:
      shards_num: 1
    dataset_params:
      dataset_size: 0
      ni_per: 0
    concurrent_params:
      concurrent_number: 1
      during_time: '1h'
      interval: 30
    concurrent_tasks:
        -
          type: scene_insert_partition
          weight: 20
          params:
            data_size: '1m'
            ni: 5
            timeout: 600
        -
          type: release
          weight: 1
          params:
            timeout: 600
```
```


### Milvus Log

server pods in 4am cluster:
```
zong-limit-tt-etcd-0                                              1/1     Running                  0                31h     10.104.4.213    4am-node11   <none>           <none>
zong-limit-tt-etcd-1                                              1/1     Running                  0                31h     10.104.17.162   4am-node23   <none>           <none>
zong-limit-tt-etcd-2                                              1/1     Running                  0                31h     10.104.20.242   4am-node22   <none>           <none>
zong-limit-tt-milvus-datacoord-587c849444-mq8l7                   1/1     Running                  0                167m    10.104.24.98    4am-node29   <none>           <none>
zong-limit-tt-milvus-datanode-7c985f5889-6wnnt                    1/1     Running                  0                167m    10.104.5.105    4am-node12   <none>           <none>
zong-limit-tt-milvus-datanode-7c985f5889-vsqjn                    1/1     Running                  0                166m    10.104.24.99    4am-node29   <none>           <none>
zong-limit-tt-milvus-indexcoord-74494d6894-8zb77                  1/1     Running                  0                167m    10.104.24.97    4am-node29   <none>           <none>
zong-limit-tt-milvus-indexnode-7dc895bd59-l8p8d                   1/1     Running                  0                167m    10.104.16.164   4am-node21   <none>           <none>
zong-limit-tt-milvus-proxy-77d6b8b8b4-qwtcm                       1/1     Running                  0                167m    10.104.20.169   4am-node22   <none>           <none>
zong-limit-tt-milvus-querycoord-5695b5594f-m5tfk                  1/1     Running                  0                167m    10.104.20.170   4am-node22   <none>           <none>
zong-limit-tt-milvus-querynode-8d9649756-gnj98                    1/1     Running                  0                167m    10.104.5.106    4am-node12   <none>           <none>
zong-limit-tt-milvus-querynode-8d9649756-vmwqr                    1/1     Running                  0                166m    10.104.20.172   4am-node22   <none>           <none>
zong-limit-tt-milvus-rootcoord-5656cccbc5-t5mdk                   1/1     Running                  0                167m    10.104.20.171   4am-node22   <none>           <none>
```

### Anything else?

_No response_
