### ISSUE TITLE
[Bug]: There is a slight error of the diskProtection config

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230529-1dde46bd
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. quotaAndLimits config:
```
  limitWriting:
    diskProtection:
      diskQuota: 45260.8
      diskQuotaPerCollection: 2263.04
      enabled: true
    forceDeny: false
    growingSegmentsSizeProtection:
      enabled: false
      highWaterLevel: 0.4
      lowWaterLevel: 0.2
    memProtection:
      dataNodeMemoryHighWaterLevel: 0.95
      dataNodeMemoryLowWaterLevel: 0.85
      enabled: true
      queryNodeMemoryHighWaterLevel: 0.95
      queryNodeMemoryLowWaterLevel: 0.85
```

2. create a collection with 1 shard and 768 dim 
3. insert 1000 data and  concurrent insert data into collection. After a while, the total num entities is 853000. It means 853000*768*4/1024/1024 = 2499 MB. It has a slight error compared to the configuration `2263.04`
4. By the way, the milvus metrics `Datacoord.Stored binglog size` is inconsistent with the config
![image](https://github.com/milvus-io/milvus/assets/27288593/9e46af92-7f05-4cf2-8c46-1ebd8182127c)

### Expected Behavior

Fix the metrics

### Steps To Reproduce

```markdown
argo workflow in 4am: insert-rate-no-limit2

server pods in 4am:

zong-disk-quota-etcd-0                                            1/1     Running            0                 8h      10.104.17.179   4am-node23   <none>           <none>
zong-disk-quota-milvus-standalone-585944f79d-8m8hb                1/1     Running            0                 3h9m    10.104.6.38     4am-node13   <none>           <none>
zong-disk-quota-minio-7c4d5c9b44-ggt4x                            1/1     Running            0                 8h      10.104.17.180   4am-node23   <none>           <none>
```
```


### Milvus Log

_No response_

### Anything else?

_No response_
