### ISSUE TITLE
[Bug]: Standalone panic: insertBufferNode flushBufferData failed when inserting data concurrently and enable ttProtection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230531-b341f43e
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.7.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy config
```
    log:
      level: debug
    common:
      security:
        authorizationEnabled: true
    queryNode:
      scheduler:
        scheduleReadPolicy:
          name: user-task-polling
    quotaAndLimits:
      enabled: true
      limits:
        maxCollectionNum: 40
        maxCollectionNumPerDB: 3
      dml:
        enabled: true
        insertRate:
          collection:
            max: 6
          max: -1
        deleteRate:
          collection:
            max: 0.5 
          max: 0.5 
      flushRate:
        enabled: true
        max: 4
      compactionRate:
        enabled: true
        max: 4
      limitWriting:
        ttProtection:
          enabled: true
          maxTimeTickDelay: 1
        memProtection:
          enabled: true
          dataNodeMemoryLowWaterLevel: 0.85
          dataNodeMemoryHighWaterLevel: 0.95
          queryNodeMemoryLowWaterLevel: 0.85
          queryNodeMemoryHighWaterLevel: 0.95
        diskProtection:
          enabled: true
          diskQuota: -1
          diskQuotaPerCollection: -1
```
2. Insert concurrently and standalone pod completed
![image](https://github.com/milvus-io/milvus/assets/27288593/4d95f94b-2da5-4277-8bfc-97788b08ad73)

3. standalone pod restarted twice, first is completed and second is panic error
```
zong-insert-etcd-0                                                1/1     Running     0               17h
zong-insert-milvus-standalone-65f966b8d8-5xjhr                    1/1     Running     2 (10m ago)     74m
zong-insert-minio-746ffc9b85-ngb4z                                1/1     Running     0               17h
```
4. panic log
```
[2023/05/31 09:25:07.545 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"]
[2023/05/31 09:25:07.545 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:504] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal\nattempt #2:context canceled\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:504\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:140\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal
attempt #2:context canceled


goroutine 967 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc002a88dd0, 0xc00737e9c0?, {0xc005943b68?, 0x1?, 0x1?}, 0xc0080fe480)
    /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:505 +0x1285
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc002a88dd0, {0xc001985730, 0x1, 0x1}) 
    /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:140 +0x485
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00527fa90)
    /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
    /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```
5. first completed previous log
[standalone_tt_pre.log](https://github.com/milvus-io/milvus/files/11611131/standalone_tt_pre.log)

6. second panic previous log
[standalone_tt_pre.log](https://github.com/milvus-io/milvus/files/11611184/standalone_tt_pre.log)

### Steps To Reproduce

```markdown
argo workflow name: `insert-rate-tt-3`

case params:

  config.yaml: |
    dataset_params:
      dataset_name: gist
      dim: 768 
      dataset_size: 10000
      ni_per: 1000
      metric_type: L2
    collection_params:
      other_fields: []
    load_params: {}
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200 
    query_params: {}
    search_params: {}
    concurrent_params:
      concurrent_number:
        - 4
      during_time: '25m'
      interval: 30
    concurrent_tasks:
      - type: insert
        weight: 1
        params:
          nb: 1000
          random_id: true
          random_vector: true
          timeout: 600
```
```


### Milvus Log

_No response_

### Anything else?

_No response_
