### ISSUE TITLE
[Bug]: [benchmark][cosine] diskann index cosine recall is too low compared to IP

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#24776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230608-330ab936
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### COSINE

server
```
cosine-recall-fwh8g-1-etcd-0                                      1/1     Running     0               4m38s   10.104.16.64    4am-node21   <none>           <none>
cosine-recall-fwh8g-1-milvus-standalone-dcb54bc48-5gxh4           1/1     Running     0               4m38s   10.104.23.161   4am-node27   <none>           <none>
cosine-recall-fwh8g-1-minio-868bf5f76-47gpd                       1/1     Running     0               4m38s   10.104.16.63    4am-node21   <none>           <none> 
```

server config :
```
{'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '8.0',
                                                               'memory': '16Gi'},
                                                    'requests': {'cpu': '5.0',
                                                                 'memory': '9Gi'}},
                                      'persistence': {'persistentVolumeClaim': {'storageClass': 'local-path'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'podMonitor': {'enabled': True}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'log': {'level': 'debug'},
                       'image': {'all': {'repository': 'harbor.milvus.io/dockerhub/milvusdb/milvus',
                                         'tag': 'master-20230608-54306a10'}}},
```

#### result:
If search_list is greater than 15, recall is 0.02 ：
![image](https://github.com/milvus-io/milvus/assets/48523564/029e8e0c-cc9b-4e21-9a83-a18677259f21)

### Expected Behavior
cosine's recall should be the same as the normalized ip
#### DISKANN IP 
![image](https://github.com/milvus-io/milvus/assets/48523564/669bd692-a2a9-4890-9baa-f10c57ab806b)

### Steps To Reproduce

```markdown
1. create a collection 
        2. insert training dataset: glove-200-angular
        3. flush collection
        4. clean index and build new index: DISKANN
        5. load collection
        6. serial search with different parameters
        7. clean all collections
```

### Anything else?

client param:
```
dataset_params:
  metric_type: COSINE
  dim: 200
  dataset_name: glove-200-angular
  ni_per: 10000
collection_params:
  other_fields: []
load_params:
  replica_number: 1
search_params:
  top_k:
  - 10
  nq:
  - 10000
  search_param:
    search_list:
    - 10
    - 15
    - 20
    - 30
    - 40
    - 150
    - 170
    - 200
index_params:
  index_type: DISKANN
  index_param: {}
```
