### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] indexNode keeps restarting, error: 'Get configuration by items failed'

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230628-31122a68
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.9.dev36
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-mrt4w

deploy_config: fouramf-server-replicas-lb-4qn
case_params: fouramf-client-sift-replica2-search
other_params
`--milvus_tag=master-20230628-31122a68 -k test_concurrent_locust_custom_parameters -s --case_skip_clean_collection --deploy_retain --deploy_mode=cluster --release_name=lb-helm-upgrade`
test-sdk-version: 2.2.9.dev36

server:
```
NAME                                                              READY   STATUS             RESTARTS       AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-upgrade-etcd-0                                            1/1     Running            0              33m     10.104.21.9     4am-node24   <none>           <none>
lb-helm-upgrade-etcd-1                                            1/1     Running            0              33m     10.104.24.127   4am-node29   <none>           <none>
lb-helm-upgrade-etcd-2                                            1/1     Running            0              33m     10.104.19.161   4am-node28   <none>           <none>
lb-helm-upgrade-milvus-datacoord-594c5f7d49-n2hjw                 1/1     Running            0              33m     10.104.21.248   4am-node24   <none>           <none>
lb-helm-upgrade-milvus-datanode-d4749dd44-nwvgg                   1/1     Running            0              33m     10.104.23.19    4am-node27   <none>           <none>
lb-helm-upgrade-milvus-indexcoord-c7f9bcc46-t7jsw                 1/1     Running            0              33m     10.104.21.253   4am-node24   <none>           <none>
lb-helm-upgrade-milvus-indexnode-6449c4cf58-6k5wc                 0/1     CrashLoopBackOff   5 (5s ago)     33m     10.104.9.133    4am-node14   <none>           <none>
lb-helm-upgrade-milvus-proxy-7c4c47cb64-2s5fd                     1/1     Running            0              33m     10.104.21.246   4am-node24   <none>           <none>
lb-helm-upgrade-milvus-querycoord-ccd4b4b77-jmgcl                 1/1     Running            0              33m     10.104.21.247   4am-node24   <none>           <none>
lb-helm-upgrade-milvus-querynode-86cd884c5-88jxb                  1/1     Running            0              33m     10.104.21.4     4am-node24   <none>           <none>
lb-helm-upgrade-milvus-querynode-86cd884c5-gq6v8                  1/1     Running            0              33m     10.104.15.157   4am-node20   <none>           <none>
lb-helm-upgrade-milvus-querynode-86cd884c5-jnx5l                  1/1     Running            0              33m     10.104.16.44    4am-node21   <none>           <none>
lb-helm-upgrade-milvus-querynode-86cd884c5-rbbfm                  1/1     Running            0              33m     10.104.23.20    4am-node27   <none>           <none>
lb-helm-upgrade-milvus-rootcoord-cc87cf979-rvdq8                  1/1     Running            0              33m     10.104.21.249   4am-node24   <none>           <none>
lb-helm-upgrade-minio-0                                           1/1     Running            0              33m     10.104.21.10    4am-node24   <none>           <none>
lb-helm-upgrade-minio-1                                           1/1     Running            0              33m     10.104.9.135    4am-node14   <none>           <none>
lb-helm-upgrade-minio-2                                           1/1     Running            0              33m     10.104.15.159   4am-node20   <none>           <none>
lb-helm-upgrade-minio-3                                           1/1     Running            0              33m     10.104.19.157   4am-node28   <none>           <none>
lb-helm-upgrade-pulsar-bookie-0                                   1/1     Running            0              33m     10.104.24.126   4am-node29   <none>           <none>
lb-helm-upgrade-pulsar-bookie-1                                   1/1     Running            0              33m     10.104.18.172   4am-node25   <none>           <none>
lb-helm-upgrade-pulsar-bookie-2                                   1/1     Running            0              33m     10.104.19.162   4am-node28   <none>           <none>
lb-helm-upgrade-pulsar-bookie-init-jshjr                          0/1     Completed          0              33m     10.104.24.121   4am-node29   <none>           <none>
lb-helm-upgrade-pulsar-broker-0                                   1/1     Running            0              33m     10.104.21.254   4am-node24   <none>           <none>
lb-helm-upgrade-pulsar-proxy-0                                    1/1     Running            0              33m     10.104.24.122   4am-node29   <none>           <none>
lb-helm-upgrade-pulsar-pulsar-init-6wjxk                          0/1     Completed          0              33m     10.104.21.250   4am-node24   <none>           <none>
lb-helm-upgrade-pulsar-recovery-0                                 1/1     Running            0              33m     10.104.9.132    4am-node14   <none>           <none>
lb-helm-upgrade-pulsar-zookeeper-0                                1/1     Running            0              33m     10.104.21.11    4am-node24   <none>           <none>
lb-helm-upgrade-pulsar-zookeeper-1                                1/1     Running            0              33m     10.104.24.129   4am-node29   <none>           <none>
lb-helm-upgrade-pulsar-zookeeper-2                                1/1     Running            0              32m     10.104.17.242   4am-node23   <none>           <none>
```
indexNode logs:
<img width="1853" alt="截屏2023-06-28 16 18 19" src="https://github.com/milvus-io/milvus/assets/26307815/bdbaeab0-bc5f-4107-be97-d05244254509">

client:
<img width="1419" alt="截屏2023-06-28 16 17 31" src="https://github.com/milvus-io/milvus/assets/26307815/eefac0cf-4798-438f-9154-6acf0a75c006">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus using helm
2、create a collection
3、build index of HNSW
4、insert 5m vectors
5、build index with the same params <- indexNode error
```

### Anything else?

fouramf-server-replicas-lb-4qn:
```
    queryNode:
      resources:
        limits:
          cpu: '8.0'
          memory: 8Gi
        requests:
          cpu: '4.0'
          memory: 4Gi
      replicas: 4
    indexNode:
      resources:
        limits:
          cpu: '4.0'
          memory: 4Gi
        requests:
          cpu: '3.0'
          memory: 3Gi
      replicas: 1
    dataNode:
      resources:
        limits:
          cpu: '2.0'
          memory: 2Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-replica2-search:
```
    load_params:
      replica_number: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 5m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 100
      during_time: 1h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 10
          search_param:
            ef: 64
          timeout: 3600
```
