### ISSUE TITLE
[Bug]: search fail after insert

### ISSUE THREAD

**Issue by tianyunzqs** [milvus-io/milvus#25251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.2.13 
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 32G
- GPU: 
- Others:
```

### Current Behavior

I installed milvus with docker-compose 
First time I insert data into milvus, it's OK!  
```python
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.vectorstores.milvus import Milvus

embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict["text2vec"], model_kwargs={'device': "cuda"})
milvus_instance = Milvus(
    embedding_function=embeddings,
    connection_args=MILVUS_CONNECTION
)

title = "模型已成功加载"
content = "我是人工智能助手，很高兴见到你，欢迎问我任何问题。"
docs = [
    Document(page_content=content, metadata={"source": title, "time": "20230626"}),
    Document(page_content=content, metadata={"source": title, "time": "20230625"}),
    Document(page_content=content, metadata={"source": title, "time": "20230624"})
]
milvus_instance = Milvus.from_documents(docs, embeddings, connection_args=MILVUS_CONNECTION)
```

but, next time I search data, it's exited
```python
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict["text2vec"], model_kwargs={'device': "cuda"})
milvus_instance = Milvus(
    embedding_function=embeddings,
    connection_args=MILVUS_CONNECTION
)
b = milvus_instance.similarity_search("人工智能")
print(b)
```
![image](https://github.com/milvus-io/milvus/assets/23567448/824ccb12-323a-49ba-a464-e27392847754)

here is log file
[https://github.com/tianyunzqs/empty-repository/blob/main/milvus.log](https://github.com/tianyunzqs/empty-repository/blob/main/milvus.log)

### Steps To Reproduce

```markdown
1.insert data;  --- ok
2.search  --- abort
```

### Milvus Log

[https://github.com/tianyunzqs/empty-repository/blob/main/milvus.log](https://github.com/tianyunzqs/empty-repository/blob/main/milvus.log)

**Comment by yanliang567** [comment]
@tianyunzqs thank you for the feedback, but i did not find any logs about search in your attachment. could you please reproduce the issue and recollect the logs?
/assign @tianyunzqs

**Comment by tianyunzqs** [comment]
@yanliang567   when `similarity_search` function run, the docker container of milvus will exited, so the log has not any error about search.
here is `similarity_search` function run result.
![image](https://github.com/milvus-io/milvus/assets/23567448/5620e140-1747-4eef-b018-eef30b284709)

Thanks for your reply.

**Comment by tianyunzqs** [comment]
```python
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict["text2vec"], model_kwargs={'device': "cuda"})
milvus_instance = Milvus(
    embedding_function=embeddings,
    connection_args=MILVUS_CONNECTION
)
b = milvus_instance.similarity_search("人工智能")
print(b)    #### output: []

title = "模型已成功加载"
content = "我是人工智能助手，很高兴见到你，欢迎问我任何问题。"
docs = [
    Document(page_content=content, metadata={"source": title, "time": "20230626"}),
    Document(page_content=content, metadata={"source": title, "time": "20230625"}),
    Document(page_content=content, metadata={"source": title, "time": "20230624"})
]
milvus_instance = Milvus.from_documents(docs, embeddings, connection_args=MILVUS_CONNECTION)
b = milvus_instance.similarity_search("人工智能")   #### abort
print(b)
```
![image](https://github.com/milvus-io/milvus/assets/23567448/047eccfa-7d32-4f38-89ba-cc018f6775ec)

**Comment by xiaofan-luan** [comment]
try to expose 19530 port in the milvus.yaml

    # expose 19530 port so we can directly access milvus inside build container
    # ports:
    #  - "19530:19530"

**Comment by tianyunzqs** [comment]
I downloaded the docker-compose.yml  from `https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml`. 

pymilvus-2.2.13 
the error happend very time, I have no idea about it. 
Can you helpe me?

```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
