### ISSUE TITLE
[Bug]: Query fails with error: cannot found tSafer

### ISSUE THREAD

**Issue by KonstantinKorotaev** [milvus-io/milvus#25262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Getting error on query using the filter `task != " "`

> [ERROR] Vector DB returned error for your request: {"detail":"Error occured during query: fail to query on all shard leaders, err=All attempts results:\nattempt #1:code: UnexpectedError, error: fail to Query, QueryNode ID = 807, reason=Query 807 failed, reason code: NotFoundTSafer, error: cannot found tSafer, vChannel = by-dev-rootcoord-delta_4_441970964915216290v0 err %!w(<nil>)\nattempt #2:context canceled\n"}

### Expected Behavior

Query successfully using the filter

### Steps To Reproduce

```markdown
1. Running query() with simple filter `task != " "`
```

### Milvus Log

Several errors of each type on querynode:

> 
> time="2023-06-30T08:11:02Z" level=info msg="Closing consumer=1675" consumerID=1675 name=jqjnm subscription=querynode-delta-loader-807-442379709495742848-3052003987568002487 topic="persistent://public/default/by-dev-rootcoord-dml_12"
> time="2023-06-30T08:11:02Z" level=info msg="The consumer[1675] successfully unsubscribed" consumerID=1675 name=jqjnm subscription=querynode-delta-loader-807-442379709495742848-3052003987568002487 topic="persistent://public/default/by-dev-rootcoord-dml_12"
> time="2023-06-30T08:11:02Z" level=info msg="[Reconnected consumer to broker]" consumerID=1675 name=jqjnm subscription=querynode-delta-loader-807-442379709495742848-3052003987568002487 topic="persistent://public/default/by-dev-rootcoord-dml_12"
> time="2023-06-30T08:11:02Z" level=info msg="[Reconnecting to broker in  109.4741ms]" consumerID=1675 name=jqjnm subscription=querynode-delta-loader-807-442379709495742848-3052003987568002487 topic="persistent://public/default/by-dev-rootcoord-dml_12"
> time="2023-06-30T08:11:02Z" level=info msg="Broker notification of Closed consumer: 1675" local_addr="10.88.3.23:36570" remote_addr="pulsar://milvus-pulsar-proxy:6650"

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11916518/milvus-log.tar.gz)

**Comment by jiaoew1991** [comment]
From the log, the network with pulsar is not stable. 🤔

**Comment by KonstantinKorotaev** [comment]
It seems that zookeeper is restarting during this issue:
```
LAST SEEN   TYPE      REASON      OBJECT                          MESSAGE
19m         Warning   Unhealthy   pod/milvus-pulsar-zookeeper-2   Liveness probe failed: ZK server is not ok
6m59s       Warning   Unhealthy   pod/milvus-pulsar-zookeeper-0   Liveness probe failed: ZK server is not ok
89s         Warning   Unhealthy   pod/milvus-pulsar-zookeeper-0   Readiness probe failed: ZK server is not ok
```

**Comment by farioas** [comment]
Hi @jiaoew1991,
I work with @KonstantinKorotaev, so he invited me to participate in troubleshooting of this issue.
We decided switch to kafka instead of Pulsar as it requires less level of support.

The Milvus version is 2.2.8 !

Here's our config file:
```
rootCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
indexCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "0.5"
      memory: 0.5Gi
queryCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "0.5"
      memory: 0.5Gi
dataCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "0.5"
      memory: 0.5Gi
proxy:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 4Gi
queryNode:
  replicas: 3
  resources:
    limits:
      cpu: 4
      memory: 16Gi
dataNode:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 4Gi
indexNode:
  replicas: 2
  resources:
    limits:
      cpu: 8
      memory: 16Gi
etcd:
  autoCompactionMode: revision
  autoCompactionRetention: "1000"
  extraEnvVars:
    - name: ETCD_QUOTA_BACKEND_BYTES
      value: "4294967296"
    - name: ETCD_HEARTBEAT_INTERVAL
      value: "500"
    - name: ETCD_ELECTION_TIMEOUT
      value: "25000"
    - name: ETCD_SNAPSHOT_COUNT
      value: "10000"
    - name: ETCD_ENABLE_PPROF
      value: "true"
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 30Gi
    storageClass: premium-rwo #SSD Required
  replicaCount: 3
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

pulsar:
  enabled: false
kafka:
  enabled: true
  heapOpts: "-Xmx4096M -Xms4096M"
  persistence:
    enabled: true
    storageClass:
    accessMode: ReadWriteOnce
    size: 20G
  resources:
    limits:
      cpu: 2
      memory: 13Gi
  zookeeper:
    enabled: true
    replicaCount: 3
    heapSize: 1024  # zk heap size in MB
    persistence:
      enabled: true
      storageClass: premium-rwo #SSD Required
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    resources:
      limits:
        cpu: 1
        memory: 2Gi
```

Here are new logs, since the issue still reproducible. 
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11950274/milvus-log.tar.gz)
