### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] `Segcore Request Latency` latency suddenly rises, nearly doubles

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230629-b30517d3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-wsxjs

**test configs**
deploy_config: fouramf-server-replicas-lb-4qn
case_params: fouramf-client-sift-rg-replica2
other_params
`--milvus_tag=master-20230629-b30517d3 -k test_concurrent_locust_custom_parameters -s --case_skip_clean_collection --deploy_retain --deploy_mode=cluster --release_name=lb-helm-rg-pod-failure`

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-rg-pod-failure-etcd-0                                     1/1     Running     0               125m    10.104.19.170   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-etcd-1                                     1/1     Running     0               125m    10.104.24.102   4am-node29   <none>           <none>
lb-helm-rg-pod-failure-etcd-2                                     1/1     Running     0               125m    10.104.23.222   4am-node27   <none>           <none>
lb-helm-rg-pod-failure-milvus-datacoord-746fc77bf8-5lljq          1/1     Running     0               125m    10.104.19.163   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-datanode-8f44f9bb7-jp64r            1/1     Running     1 (121m ago)    125m    10.104.19.154   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-indexcoord-98f45d55f-r5zl7          1/1     Running     0               125m    10.104.19.153   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-indexnode-5f6b6cdd88-bjbf4          1/1     Running     0               125m    10.104.19.161   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-proxy-777445b4c9-qmjd5              1/1     Running     1 (121m ago)    125m    10.104.19.164   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-querycoord-5c98bb6d5b-fdnn8         1/1     Running     1 (121m ago)    125m    10.104.19.162   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-querynode-95cdb6546-5r89w           1/1     Running     0               125m    10.104.19.160   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-milvus-querynode-95cdb6546-88mdz           1/1     Running     0               125m    10.104.21.230   4am-node24   <none>           <none>
lb-helm-rg-pod-failure-milvus-querynode-95cdb6546-9ksk9           1/1     Running     0               125m    10.104.24.96    4am-node29   <none>           <none>
lb-helm-rg-pod-failure-milvus-querynode-95cdb6546-zr4x5           1/1     Running     0               125m    10.104.22.186   4am-node26   <none>           <none>
lb-helm-rg-pod-failure-milvus-rootcoord-fbc55bc6-dwgvp            1/1     Running     1 (121m ago)    125m    10.104.19.159   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-minio-0                                    1/1     Running     0               125m    10.104.19.169   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-minio-1                                    1/1     Running     0               125m    10.104.24.103   4am-node29   <none>           <none>
lb-helm-rg-pod-failure-minio-2                                    1/1     Running     0               125m    10.104.18.231   4am-node25   <none>           <none>
lb-helm-rg-pod-failure-minio-3                                    1/1     Running     0               125m    10.104.23.223   4am-node27   <none>           <none>
lb-helm-rg-pod-failure-pulsar-bookie-0                            1/1     Running     0               125m    10.104.19.172   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-bookie-1                            1/1     Running     0               125m    10.104.24.105   4am-node29   <none>           <none>
lb-helm-rg-pod-failure-pulsar-bookie-2                            1/1     Running     0               125m    10.104.18.236   4am-node25   <none>           <none>
lb-helm-rg-pod-failure-pulsar-bookie-init-8bvlx                   0/1     Completed   0               125m    10.104.19.157   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-broker-0                            1/1     Running     0               125m    10.104.19.165   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-proxy-0                             1/1     Running     0               125m    10.104.19.158   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-pulsar-init-2xqh4                   0/1     Completed   0               125m    10.104.19.151   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-recovery-0                          1/1     Running     0               125m    10.104.24.95    4am-node29   <none>           <none>
lb-helm-rg-pod-failure-pulsar-zookeeper-0                         1/1     Running     0               125m    10.104.24.98    4am-node29   <none>           <none>
lb-helm-rg-pod-failure-pulsar-zookeeper-1                         1/1     Running     0               125m    10.104.19.174   4am-node28   <none>           <none>
lb-helm-rg-pod-failure-pulsar-zookeeper-2                         1/1     Running     0               124m    10.104.23.225   4am-node27   <none>           <none>
```
<img width="1868" alt="截屏2023-07-03 15 55 39" src="https://github.com/milvus-io/milvus/assets/26307815/291e8e83-ad22-41de-b806-bff33644f809">
<img width="1866" alt="截屏2023-07-03 15 56 10" src="https://github.com/milvus-io/milvus/assets/26307815/a278af25-b6d1-4160-a5ef-2029281b1ee7">

<img width="1862" alt="截屏2023-07-03 15 56 28" src="https://github.com/milvus-io/milvus/assets/26307815/c867f8af-0e83-415f-9981-f3f3372b76f1">

<img width="1867" alt="截屏2023-07-03 15 56 41" src="https://github.com/milvus-io/milvus/assets/26307815/e1744c69-d718-4760-8d5f-19533e608069">

<img width="1859" alt="截屏2023-07-03 15 56 59" src="https://github.com/milvus-io/milvus/assets/26307815/ec3ab8d1-cceb-4116-8cc2-d5b79c2d2015">

<img width="1870" alt="截屏2023-07-03 15 57 59" src="https://github.com/milvus-io/milvus/assets/26307815/b54a5ca1-0f17-4353-8dd5-eb7b61fd7e9e">

<img width="460" alt="截屏2023-07-03 16 04 14" src="https://github.com/milvus-io/milvus/assets/26307815/612dff05-a01d-4e65-a8d7-643a78782dee">

client:
<img width="1433" alt="截屏2023-07-03 15 20 27" src="https://github.com/milvus-io/milvus/assets/26307815/abea78d7-9c1a-4998-a4f6-ac11ed336cb3">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 4 queryNodes
2、create a collection
3、setting 2 resource groups， and each one adding 2 queryNodes
4、build IVF_SQ8 index
5、insert 10m data and flush
6、build index with the same params
7、load collection with replicas=2， resource groups=2
8、concurrent search
```

### Anything else?

fouramf-server-replicas-lb-4qn:
```
    queryNode:
      resources:
        limits:
          cpu: '8.0'
          memory: 8Gi
        requests:
          cpu: '4.0'
          memory: 4Gi
      replicas: 4
    indexNode:
      resources:
        limits:
          cpu: '8.0'
          memory: 8Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 1
    dataNode:
      resources:
        limits:
          cpu: '2.0'
          memory: 2Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-rg-replica2:
```
    resource_groups_params:
      reset: false
      groups: [2, 2]
    load_params:
      replica_number: 2
      _resource_groups: ['RG_0', 'RG_1']
    collection_params:
      collection_name: 'RG_2_2'
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 5h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1000
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 3600
```
