### ISSUE TITLE
[Bug]: [Perf-nightly] Milvus1m 768d data searched for a decrease in qps

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#25310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230628-63b6a4a6
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus search qps drops from 28th June, latency gets higher

<img width="430" alt="截屏2023-07-04 15 31 11" src="https://github.com/milvus-io/milvus/assets/34296482/8c895c16-1753-4ecb-9d6c-dd3fddb3eb40">

### Steps To Reproduce

```markdown
1. create a collection
2. build an index
3. insert gist 1m 768d
4. build index again
5. load collection
6. concurrent search
```

### Anything else?

```
data:
  config.yaml: |
    dataset_params:
      dataset_name: gist
      dim: 768
      dataset_size: 1m
      ni_per: 1000
      metric_type: L2
    collection_params:
      other_fields: []
    load_params: {}
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    query_params: {}
    search_params: {}
    concurrent_params:
      concurrent_number:
        - 1
        - 20
        - 50
        - 100
      during_time: 3600
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            ef: 16
          random_data: true
```
