### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] `Index Task Count` metric incorrect, the number of unissued tasks does not decrease after indexing finished

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230706-823ede3a
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-9p776

**test configs**
deploy_config: fouramf-server-replicas-lb-3qn-maxnq
case_params: fouramf-client-sift-replica3-shard1-ivfsq8-go-search
other_params:
`--milvus_tag=master-20230706-823ede3a -k test_go_bench_custom_parameters -s --case_skip_clean_collection --deploy_retain --deploy_mode=cluster --update_helm_file --release_name=lb-helm-minnq-go-scale-r3`

server:
```
NAME                                                              READY   STATUS        RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-minnq-go-scale-r3-etcd-0                                  1/1     Running     0               70m     10.104.5.240    4am-node12   <none>           <none>
lb-helm-minnq-go-scale-r3-etcd-1                                  1/1     Running     0               70m     10.104.6.214    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-etcd-2                                  1/1     Running     0               70m     10.104.20.213   4am-node22   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-datacoord-64db4b9865-gkn5p       1/1     Running     0               70m     10.104.6.207    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-datanode-6449c8d69c-7n7bk        1/1     Running     0               70m     10.104.6.209    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-indexcoord-6c86c67999-s4pj6      1/1     Running     0               70m     10.104.6.206    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-indexnode-5c9f68dd7b-lkjb8       1/1     Running     0               70m     10.104.21.149   4am-node24   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-proxy-56d4896df9-cqbm8           1/1     Running     0               70m     10.104.15.95    4am-node20   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-querycoord-66dbfd5944-lkl47      1/1     Running     0               70m     10.104.18.254   4am-node25   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-querynode-57d6599cbb-chkqj       1/1     Running     0               70m     10.104.15.92    4am-node20   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-querynode-57d6599cbb-s6gj5       1/1     Running     0               70m     10.104.4.10     4am-node11   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-querynode-57d6599cbb-xfkws       1/1     Running     0               70m     10.104.22.113   4am-node26   <none>           <none>
lb-helm-minnq-go-scale-r3-milvus-rootcoord-d7f6f98cd-6xchk        1/1     Running     0               70m     10.104.22.111   4am-node26   <none>           <none>
lb-helm-minnq-go-scale-r3-minio-0                                 1/1     Running     0               70m     10.104.6.210    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-minio-1                                 1/1     Running     0               70m     10.104.21.151   4am-node24   <none>           <none>
lb-helm-minnq-go-scale-r3-minio-2                                 1/1     Running     0               70m     10.104.18.9     4am-node25   <none>           <none>
lb-helm-minnq-go-scale-r3-minio-3                                 1/1     Running     0               70m     10.104.5.242    4am-node12   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-bookie-0                         1/1     Running     0               70m     10.104.18.10    4am-node25   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-bookie-1                         1/1     Running     0               70m     10.104.6.215    4am-node13   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-bookie-2                         1/1     Running     0               70m     10.104.17.247   4am-node23   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-bookie-init-qjggs                0/1     Completed   0               70m     10.104.22.110   4am-node26   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-broker-0                         1/1     Running     0               70m     10.104.22.107   4am-node26   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-proxy-0                          1/1     Running     0               70m     10.104.22.106   4am-node26   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-pulsar-init-wztpd                0/1     Completed   0               70m     10.104.15.90    4am-node20   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-recovery-0                       1/1     Running     0               70m     10.104.21.148   4am-node24   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-zookeeper-0                      1/1     Running     0               70m     10.104.15.96    4am-node20   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-zookeeper-1                      1/1     Running     0               69m     10.104.20.215   4am-node22   <none>           <none>
lb-helm-minnq-go-scale-r3-pulsar-zookeeper-2                      1/1     Running     0               68m     10.104.18.20    4am-node25   <none>           <none>
```
<img width="1860" alt="截屏2023-07-07 12 10 15" src="https://github.com/milvus-io/milvus/assets/26307815/4bd996e1-24e1-41ce-8d17-deea6d63b191">

<img width="1864" alt="截屏2023-07-07 12 10 47" src="https://github.com/milvus-io/milvus/assets/26307815/2f196ce3-5d3f-41ce-a900-a63a6231123c">

client test:
![image](https://github.com/milvus-io/milvus/assets/26307815/6f1f7ab1-418f-42f8-85d5-31c47d7b4870)

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 3 queryNodes
2、create a collection 
3、build IVF_SQ8 index
4、insert 10m data
5、flush and build index with the same params
6、load collection and concurrent search by go_bench
```

### Anything else?

fouramf-server-replicas-lb-3qn-maxnq:
```
    extraConfigFiles:
      user.yaml: |+
        queryNode:
          grouping:
            maxNQ: 1000
    queryNode:
      resources:
        limits:
          cpu: '8.0'
          memory: 8Gi
        requests:
          cpu: '4.0'
          memory: 4Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          # cpu: '4.0'
          # memory: 4Gi
          cpu: '8.0'
          memory: 8Gi
        requests:
          # cpu: '3.0'
          # memory: 3Gi
          cpu: '5.0'
          memory: 5Gi
      replicas: 1
    dataNode:
      resources:
        limits:
          cpu: '2.0'
          memory: 2Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-replica3-shard1-ivfsq8-go-search:
```
    load_params:
      replica_number: 3
    collection_params:
      shards_num: 1
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    search_params:
      top_k:
        - 10
      nq:
        - 1000
      search_param:
        nprobe:
          - 64
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    go_search_params:
      concurrent_number: 100
      during_time: 10h
      interval: 20
```
