### ISSUE TITLE
[Bug]: The querynode's memory not decrease after dropping some collections

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230711-70c4ddc6
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev81
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- deploy milvus with configmap: 2 querynodes and each node cpu limit 8
```
    spec:
      components:
        dataNode:
          replicas: 1
          resources:
            limits:
              cpu: "1"
              memory: 32Gi
            requests:
              cpu: "1"
              memory: 4Gi
        indexNode:
          replicas: 1
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "2"
              memory: 2Gi
        queryNode:
          replicas: 2
          resources:
            limits:
              cpu: "8"
              memory: 63Gi
            requests:
              cpu: "4"
              memory: 16Gi
      config:
        log:
          level: debug
        common:
          security:
            authorizationEnabled: true
        queryNode:
          grouping:
            maxNQ: 1000
          scheduler:
            scheduleReadPolicy:
              name: user-task-polling
```

- test steps: 5 clients tun the following steps in parallel
1. create a collection -> index -> flush -> index -> load -> concurrent scene_search_test
scene_search_test: create a collection -> index -> load -> insert 1m 768d -> flush -> index -> load -> search 5w times -> drop collection

Because each client has 2 `scene_search_test` success requests, so there are 5*1  collections been dropped. However the querynode's memory no decrease
![image](https://github.com/milvus-io/milvus/assets/27288593/771729f3-971e-484b-97ef-40971d2742a1)

### Steps To Reproduce

```markdown
- 4am argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/803318c4-7a2e-4847-a62f-a57b0e01b490?nodeId=fouramf-concurrent-db-13

- 4am server pods:

NAME                                                            STATUS      RESTARTS     AGE       IP                NODE           
fouramf-concurrent-db-13-milvus-datacoord-6d6486f4c7-lhkmn      Running     0            10h3m     10.104.23.103     4am-node27     
fouramf-concurrent-db-13-milvus-datanode-74d8895985-n4hxl       Running     0            10h3m     10.104.23.106     4am-node27     
fouramf-concurrent-db-13-milvus-indexcoord-54f86d8585-trtlz     Running     0            10h3m     10.104.23.108     4am-node27     
fouramf-concurrent-db-13-milvus-indexnode-8476787cfb-9hvp6      Running     0            10h3m     10.104.23.105     4am-node27     
fouramf-concurrent-db-13-milvus-proxy-76d78fbfd4-fzbdj          Running     0            10h3m     10.104.23.109     4am-node27     
fouramf-concurrent-db-13-milvus-querycoord-85f6d8bc77-v8p4m     Running     0            10h3m     10.104.23.110     4am-node27     
fouramf-concurrent-db-13-milvus-querynode-8fd488d66-645gp       Running     0            10h3m     10.104.19.15      4am-node28     
fouramf-concurrent-db-13-milvus-querynode-8fd488d66-m8n6t       Running     0            10h3m     10.104.23.107     4am-node27     
fouramf-concurrent-db-13-milvus-rootcoord-64db867489-g6w55      Running     0            10h3m     10.104.23.104     4am-node27     
fouramf-concurrent-db-13-etcd-0                                 Running     0            10h7m     10.104.23.98      4am-node27     
fouramf-concurrent-db-13-etcd-1                                 Running     0            10h7m     10.104.19.9       4am-node28     
fouramf-concurrent-db-13-etcd-2                                 Running     0            10h7m     10.104.21.152     4am-node24     
fouramf-concurrent-db-13-pulsar-bookie-0                        Running     0            10h7m     10.104.23.102     4am-node27     
fouramf-concurrent-db-13-pulsar-bookie-1                        Running     0            10h7m     10.104.19.12      4am-node28     
fouramf-concurrent-db-13-pulsar-bookie-2                        Running     0            10h7m     10.104.21.155     4am-node24     
fouramf-concurrent-db-13-pulsar-broker-0                        Running     0            10h7m     10.104.23.89      4am-node27     
fouramf-concurrent-db-13-pulsar-proxy-0                         Running     0            10h7m     10.104.23.90      4am-node27     
fouramf-concurrent-db-13-pulsar-recovery-0                      Running     0            10h7m     10.104.23.88      4am-node27     
fouramf-concurrent-db-13-pulsar-zookeeper-0                     Running     0            10h7m     10.104.23.101     4am-node27     
fouramf-concurrent-db-13-pulsar-zookeeper-1                     Running     0            10h6m     10.104.19.14      4am-node28     
fouramf-concurrent-db-13-pulsar-zookeeper-2                     Running     0            10h5m     10.104.20.45      4am-node22     
fouramf-concurrent-db-13-minio-0                                Running     0            10h7m     10.104.23.95      4am-node27     
fouramf-concurrent-db-13-minio-1                                Running     0            10h7m     10.104.19.7       4am-node28     
fouramf-concurrent-db-13-minio-2                                Running     0            10h7m     10.104.21.150     4am-node24     
fouramf-concurrent-db-13-minio-3                                Running     0            10h7m     10.104.20.43      4am-node22 
```
```


### Milvus Log

_No response_

### Anything else?

grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=fouramf-concurrent-db-13&var-collection=All&var-app_name=milvus&from=1689084654744&to=1689130637894
