### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] In the scenario of multiple clients, high concurrency, and large nq, search raises error

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230711-cb721781
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-wgc6v
concurrent client argo task：fouramf-concurrent-6x44k

server：
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-multi-collections-etcd-0                                  1/1     Running     0               42h     10.104.21.108   4am-node24   <none>           <none>
lb-helm-multi-collections-etcd-1                                  1/1     Running     0               42h     10.104.23.13    4am-node27   <none>           <none>
lb-helm-multi-collections-etcd-2                                  1/1     Running     0               42h     10.104.19.200   4am-node28   <none>           <none>
lb-helm-multi-collections-milvus-datacoord-877d575-q67vg          1/1     Running     0               42h     10.104.5.13     4am-node12   <none>           <none>
lb-helm-multi-collections-milvus-datanode-6cbf5d67d7-dpntp        1/1     Running     1 (42h ago)     42h     10.104.1.34     4am-node10   <none>           <none>
lb-helm-multi-collections-milvus-datanode-6cbf5d67d7-kpcqk        1/1     Running     1 (42h ago)     42h     10.104.19.198   4am-node28   <none>           <none>
lb-helm-multi-collections-milvus-indexcoord-79579c8555-4j4dr      1/1     Running     0               42h     10.104.5.10     4am-node12   <none>           <none>
lb-helm-multi-collections-milvus-indexnode-86875d8c44-6j8tx       1/1     Running     0               42h     10.104.9.161    4am-node14   <none>           <none>
lb-helm-multi-collections-milvus-indexnode-86875d8c44-zcg5q       1/1     Running     0               42h     10.104.5.12     4am-node12   <none>           <none>
lb-helm-multi-collections-milvus-proxy-6764cc5875-74s4h           1/1     Running     1 (42h ago)     42h     10.104.5.11     4am-node12   <none>           <none>
lb-helm-multi-collections-milvus-querycoord-75d668fb-hn2n4        1/1     Running     1 (42h ago)     42h     10.104.19.197   4am-node28   <none>           <none>
lb-helm-multi-collections-milvus-querynode-97cc79578-fxvtd        1/1     Running     0               42h     10.104.17.203   4am-node23   <none>           <none>
lb-helm-multi-collections-milvus-querynode-97cc79578-zpbtg        1/1     Running     0               42h     10.104.5.16     4am-node12   <none>           <none>
lb-helm-multi-collections-milvus-rootcoord-85fd96d8b-xd87f        1/1     Running     1 (42h ago)     42h     10.104.21.102   4am-node24   <none>           <none>
lb-helm-multi-collections-minio-0                                 1/1     Running     0               42h     10.104.1.39     4am-node10   <none>           <none>
lb-helm-multi-collections-minio-1                                 1/1     Running     0               42h     10.104.23.11    4am-node27   <none>           <none>
lb-helm-multi-collections-minio-2                                 1/1     Running     0               42h     10.104.21.105   4am-node24   <none>           <none>
lb-helm-multi-collections-minio-3                                 1/1     Running     0               42h     10.104.18.88    4am-node25   <none>           <none>
lb-helm-multi-collections-pulsar-bookie-0                         1/1     Running     0               42h     10.104.1.40     4am-node10   <none>           <none>
lb-helm-multi-collections-pulsar-bookie-1                         1/1     Running     0               42h     10.104.21.109   4am-node24   <none>           <none>
lb-helm-multi-collections-pulsar-bookie-2                         1/1     Running     0               42h     10.104.23.16    4am-node27   <none>           <none>
lb-helm-multi-collections-pulsar-bookie-init-7mp2s                0/1     Completed   0               42h     10.104.19.196   4am-node28   <none>           <none>
lb-helm-multi-collections-pulsar-broker-0                         1/1     Running     0               42h     10.104.5.15     4am-node12   <none>           <none>
lb-helm-multi-collections-pulsar-proxy-0                          1/1     Running     0               42h     10.104.5.14     4am-node12   <none>           <none>
lb-helm-multi-collections-pulsar-pulsar-init-zmld4                0/1     Completed   0               42h     10.104.19.195   4am-node28   <none>           <none>
lb-helm-multi-collections-pulsar-recovery-0                       1/1     Running     0               42h     10.104.23.7     4am-node27   <none>           <none>
lb-helm-multi-collections-pulsar-zookeeper-0                      1/1     Running     0               42h     10.104.23.10    4am-node27   <none>           <none>
lb-helm-multi-collections-pulsar-zookeeper-1                      1/1     Running     0               42h     10.104.19.202   4am-node28   <none>           <none>
lb-helm-multi-collections-pulsar-zookeeper-2                      1/1     Running     0               42h     10.104.21.121   4am-node24   <none>           <none>
```
<img width="1858" alt="截屏2023-07-13 15 06 41" src="https://github.com/milvus-io/milvus/assets/26307815/c205aa63-d8cc-4ce8-920c-b6bf1b4345c8">

<img width="1864" alt="截屏2023-07-13 15 07 20" src="https://github.com/milvus-io/milvus/assets/26307815/73c47aa4-56f7-4c62-8863-235a45188d92">

<img width="1861" alt="截屏2023-07-13 15 07 35" src="https://github.com/milvus-io/milvus/assets/26307815/122f0c09-d6f6-42e9-9e90-b368215424fe">

<img width="1864" alt="截屏2023-07-13 15 07 58" src="https://github.com/milvus-io/milvus/assets/26307815/cf41ecef-72aa-4faa-a972-42334ae3a766">

<img width="1864" alt="截屏2023-07-13 15 08 14" src="https://github.com/milvus-io/milvus/assets/26307815/2470629d-73e0-42cd-8faa-0f8c20442062">

<img width="1870" alt="截屏2023-07-13 15 08 36" src="https://github.com/milvus-io/milvus/assets/26307815/78dd9ad3-5942-4fd2-a933-fa203569fd22">

<img width="1755" alt="截屏2023-07-13 15 21 13" src="https://github.com/milvus-io/milvus/assets/26307815/ee004d3e-4bd0-4593-8b60-71ef2b2c9fe0">

client test result:
**search fail counts**
<img width="1872" alt="截屏2023-07-13 15 03 56" src="https://github.com/milvus-io/milvus/assets/26307815/5f31049d-d6ef-454b-bad7-64ddc7fa95e6">

**search max RT**
<img width="1872" alt="截屏2023-07-13 15 05 59" src="https://github.com/milvus-io/milvus/assets/26307815/2a621725-24e8-4ee3-92d2-189d0d445832">

**search avg RT**
<img width="1868" alt="截屏2023-07-13 15 06 20" src="https://github.com/milvus-io/milvus/assets/26307815/ac817620-a1c5-4478-b129-428a0679da8c">

<img width="1752" alt="截屏2023-07-13 15 21 34" src="https://github.com/milvus-io/milvus/assets/26307815/8f4fc7e3-82d4-483a-8839-5d21fa9e2a28">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 2 queryNodes
2、concurrent 10 client which have 2 types: replica=1 and replica=2; each type has 5 clients
   a. create a collection with shard_num=2
   b. insert 10m data, build IVF_SQ8 index
   c. load with replica=1 or 2
   d. concurrent search by locust: nq=100, topk=10, concurrent_number=100, timeout=60  <- search raise error
```

### Anything else?

fouramf-server-lb-2qn-2dn-large:
```
queryNode:
  resources:
    limits:
      cpu: '50.0'
      memory: 100Gi
    requests:
      cpu: '25.0'
      memory: 50Gi
  replicas: 2
indexNode:
  resources:
    limits:
      cpu: '8.0'
      memory: 8Gi
    requests:
      cpu: '5.0'
      memory: 5Gi
  replicas: 2
dataNode:
  resources:
    limits:
      cpu: '2.0'
      memory: 16Gi
    requests:
      cpu: '2.0'
      memory: 2Gi
  replicas: 2
```

fouramf-client-sift-ivfsq8-replica2-shard2-nq1-search-high:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
```

fouramf-client-sift-ivfsq8-replica1-shard2-nq1-search-high:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
```
