### ISSUE TITLE
[Bug]: Insert request is rejected by grpc RateLimiter but proxy received rate less than the collection and global config

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230712-dbf01308
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev81
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- server quota and limit config
```
     quotaAndLimits:
      ddl:
        collectionRate: -1
        enabled: false
        partitionRate: -1
      dml:
        deleteRate:
          collection:
            max: -1
          max: -1
        enabled: true
        insertRate:
          collection:
            max: 1
          max: 4
      limitWriting:
        diskProtection:
          diskQuota: -1
          diskQuotaPerCollection: -1
          enabled: true
        forceDeny: false
        growingSegmentsSizeProtection:
          enabled: false
          highWaterLevel: 0.4
          lowWaterLevel: 0.2
        memProtection:
          dataNodeMemoryHighWaterLevel: 0.8
          dataNodeMemoryLowWaterLevel: 0.6
          enabled: true
          queryNodeMemoryHighWaterLevel: 0.8
          queryNodeMemoryLowWaterLevel: 0.6
        ttProtection:
          enabled: false
          maxTimeTickDelay: 300
```
- server resource config:
```
   queryNode:
      paused: false
      replicas: 2
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 2Gi
    dataNode:
      paused: false
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 2Gi
```

- test steps:
 6 clients insert data into 8 collections with dim=768 and ni=400 in parallel, one of the 3 collections inserts failed by rate limiter but their proxy received bytes rate metrics not reach the `collection.max=1Mb/s` and also not reach the global limit 4Mb/s. Meanwhile the datanode's memory and querynode's memory are both less than the ratelimit low water level 8G*0.6=4.8G

collection's received bytes rate
![image](https://github.com/milvus-io/milvus/assets/27288593/53cc0d8d-d762-4933-9b17-e219cf20f08f)

global received bytes rate
![image](https://github.com/milvus-io/milvus/assets/27288593/fb133184-9e03-4fdc-947c-0c29511909b5)

memory usage:
![image](https://github.com/milvus-io/milvus/assets/27288593/c56a35c4-ac05-4a0f-af69-b5c829d40e58)

- grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-1&var-collection=All&var-app_name=milvus&from=1689225203109&to=1689229753649

### Expected Behavior

When collection bytes rate reach the `collection.max` config or global bytes rate reach the global rate config, some insert requests will be rejected

### Steps To Reproduce

```markdown
- 4am argo workflow name: `master-insert-rate-5-drjzq`
- case params

    collection_params:
      shards_num: 1
    dataset_params:
      dataset_name: gist
      dim: 768 
      dataset_size: '1m'
      ni_per: 400 
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200 
    load_params:
      skip_load: true
```

4am server pods:
```
quota-limit-1-etcd-0                                              1/1     Running     0               5d23h   10.104.9.33     4am-node14   <none>           <none>
quota-limit-1-etcd-1                                              1/1     Running     0               5d23h   10.104.18.93    4am-node25   <none>           <none>
quota-limit-1-etcd-2                                              1/1     Running     0               5d23h   10.104.22.217   4am-node26   <none>           <none>
quota-limit-1-milvus-datacoord-5854c5dbc6-p4cns                   1/1     Running     0               24h     10.104.19.172   4am-node28   <none>           <none>
quota-limit-1-milvus-datanode-965944468-g6x5p                     1/1     Running     0               24h     10.104.1.103    4am-node10   <none>           <none>
quota-limit-1-milvus-indexcoord-78c5d7b6cb-zk67s                  1/1     Running     0               24h     10.104.15.170   4am-node20   <none>           <none>
quota-limit-1-milvus-indexnode-77d664b88b-jzwnb                   1/1     Running     0               24h     10.104.9.45     4am-node14   <none>           <none>
quota-limit-1-milvus-proxy-655f759df5-ltp6q                       1/1     Running     0               24h     10.104.1.102    4am-node10   <none>           <none>
quota-limit-1-milvus-querycoord-6b9f7c6cd4-5rvr6                  1/1     Running     0               24h     10.104.19.171   4am-node28   <none>           <none>
quota-limit-1-milvus-querynode-68bd5db474-98lg6                   1/1     Running     0               24h     10.104.16.176   4am-node21   <none>           <none>
quota-limit-1-milvus-querynode-68bd5db474-v2wvp                   1/1     Running     0               24h     10.104.21.240   4am-node24   <none>           <none>
quota-limit-1-milvus-rootcoord-d674bdc48-d99wb                    1/1     Running     0               24h     10.104.15.171   4am-node20   <none>           <none>
quota-limit-1-minio-0                                             1/1     Running     0               5d23h   10.104.9.34     4am-node14   <none>           <none>
quota-limit-1-minio-1                                             1/1     Running     0               5d23h   10.104.18.95    4am-node25   <none>           <none>
quota-limit-1-minio-2                                             1/1     Running     0               5d23h   10.104.15.229   4am-node20   <none>           <none>
quota-limit-1-minio-3                                             1/1     Running     0               5d23h   10.104.22.220   4am-node26   <none>           <none>
quota-limit-1-pulsar-bookie-0                                     1/1     Running     0               5d23h   10.104.22.222   4am-node26   <none>           <none>
quota-limit-1-pulsar-bookie-1                                     1/1     Running     0               5d23h   10.104.15.235   4am-node20   <none>           <none>
quota-limit-1-pulsar-bookie-2                                     1/1     Running     0               5d23h   10.104.18.98    4am-node25   <none>           <none>
quota-limit-1-pulsar-broker-0                                     1/1     Running     0               5d23h   10.104.9.31     4am-node14   <none>           <none>
quota-limit-1-pulsar-proxy-0                                      1/1     Running     0               5d23h   10.104.18.92    4am-node25   <none>           <none>
quota-limit-1-pulsar-recovery-0                                   1/1     Running     0               5d23h   10.104.9.30     4am-node14   <none>           <none>
quota-limit-1-pulsar-zookeeper-0                                  1/1     Running     0               5d23h   10.104.15.230   4am-node20   <none>           <none>
quota-limit-1-pulsar-zookeeper-1                                  1/1     Running     0               5d23h   10.104.18.101   4am-node25   <none>           <none>
quota-limit-1-pulsar-zookeeper-2                                  1/1     Running     0               5d23h   10.104.9.36     4am-node14   <none>           <none>
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by ThreadDao** [comment]
You also can see this test workflow `master-insert-rate-6` (in 4am cluster)
6 collections insert 768-dim data with ni=1000 in parallel, some collection just start insert and gets rate rejected but global insert rate(3Mb/s) is less than the config (4MB/s)
 - rate config
```
  dml:
    enabled: true
    insertRate:
      collection:
        max: 3
      max: 4
    memProtection:
      dataNodeMemoryHighWaterLevel: 0.8
      dataNodeMemoryLowWaterLevel: 0.6
      enabled: true
      queryNodeMemoryHighWaterLevel: 0.8
      queryNodeMemoryLowWaterLevel: 0.6
```
- collection received bytes rate
![image](https://github.com/milvus-io/milvus/assets/27288593/37c0b64c-519d-4ba7-b705-548f0a71d903)

- total received bytes rate
![image](https://github.com/milvus-io/milvus/assets/27288593/b3e13974-4930-43d8-9db4-b9d934b09023)

- memory usage
![image](https://github.com/milvus-io/milvus/assets/27288593/71fa41b9-2a34-402f-9c56-402ae86c24a7)

grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-1&var-collection=All&var-app_name=milvus&from=1689236338933&to=1689237576260
