### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] In the scenario of ddl and dql, dataNode、 dataCoord and queryCoord panic

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230713-65cb52d0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-q44s8
client argo task: fouramf-concurrent-h9rnd

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-scene10-ivfsq8-etcd-0                                     1/1     Running     0               4m2s    10.104.14.187   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-etcd-1                                     1/1     Running     0               4m2s    10.104.20.198   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-etcd-2                                     1/1     Running     0               4m1s    10.104.9.187    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4lt          1/1     Running     0               4m2s    10.104.14.182   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4           1/1     Running     0               4m2s    10.104.4.179    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-nlmt9           1/1     Running     0               4m2s    10.104.19.208   4am-node28   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexcoord-5864d6bc4-w94pq          1/1     Running     0               4m2s    10.104.17.172   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-9pmw9          1/1     Running     0               4m2s    10.104.4.178    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-chk59          1/1     Running     0               4m2s    10.104.14.184   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-nhhtr          1/1     Running     0               4m2s    10.104.9.182    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-proxy-58476654b8-wwkfx              1/1     Running     0               4m2s    10.104.5.180    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stc         1/1     Running     0               4m2s    10.104.14.183   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-lr9ph          1/1     Running     0               4m2s    10.104.19.209   4am-node28   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-lvfl8          1/1     Running     0               4m2s    10.104.17.170   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-rzg4k          1/1     Running     0               4m2s    10.104.5.179    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-rootcoord-8686b55677-n2vmc          1/1     Running     0               4m2s    10.104.5.183    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-minio-0                                    1/1     Running     0               4m2s    10.104.20.200   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-minio-1                                    1/1     Running     0               4m1s    10.104.14.191   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-minio-2                                    1/1     Running     0               4m1s    10.104.4.182    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-minio-3                                    1/1     Running     0               4m1s    10.104.9.191    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-0                            1/1     Running     0               4m2s    10.104.9.185    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-1                            1/1     Running     0               4m1s    10.104.20.201   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-2                            1/1     Running     0               4m1s    10.104.14.193   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-init-wbdkf                   0/1     Completed   0               4m2s    10.104.5.178    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-broker-0                            1/1     Running     0               4m2s    10.104.5.184    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-proxy-0                             1/1     Running     0               4m2s    10.104.20.190   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-pulsar-init-47nmx                   0/1     Completed   0               4m2s    10.104.17.171   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-recovery-0                          1/1     Running     0               4m2s    10.104.5.181    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-0                         1/1     Running     0               4m2s    10.104.14.188   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-1                         1/1     Running     0               3m21s   10.104.20.204   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-2                         1/1     Running     0               2m46s   10.104.4.184    4am-node11   <none>           <none>
```

```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-scene10-ivfsq8-etcd-0                                     1/1     Running            0               18h     10.104.14.187   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-etcd-1                                     1/1     Running            0               18h     10.104.20.198   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-etcd-2                                     1/1     Running            0               18h     10.104.9.187    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4lt          1/1     Running            2 (16h ago)     18h     10.104.14.182   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4           1/1     Running            2 (16h ago)     18h     10.104.4.179    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-nlmt9           1/1     Running            1 (16h ago)     18h     10.104.19.208   4am-node28   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexcoord-5864d6bc4-w94pq          1/1     Running            0               18h     10.104.17.172   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-9pmw9          1/1     Running            0               18h     10.104.4.178    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-chk59          1/1     Running            0               18h     10.104.14.184   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-indexnode-65845b564d-nhhtr          1/1     Running            0               18h     10.104.9.182    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-proxy-58476654b8-wwkfx              1/1     Running            0               18h     10.104.5.180    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stc         1/1     Running            1 (17h ago)     18h     10.104.14.183   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-lr9ph          1/1     Running            0               18h     10.104.19.209   4am-node28   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-lvfl8          1/1     Running            0               18h     10.104.17.170   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-querynode-68c4c95989-rzg4k          1/1     Running            0               18h     10.104.5.179    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-milvus-rootcoord-8686b55677-n2vmc          1/1     Running            0               18h     10.104.5.183    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-minio-0                                    1/1     Running            0               18h     10.104.20.200   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-minio-1                                    1/1     Running            0               18h     10.104.14.191   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-minio-2                                    1/1     Running            0               18h     10.104.4.182    4am-node11   <none>           <none>
lb-helm-scene10-ivfsq8-minio-3                                    1/1     Running            0               18h     10.104.9.191    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-0                            1/1     Running            0               18h     10.104.9.185    4am-node14   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-1                            1/1     Running            0               18h     10.104.20.201   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-2                            1/1     Running            0               18h     10.104.14.193   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-bookie-init-wbdkf                   0/1     Completed          0               18h     10.104.5.178    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-broker-0                            1/1     Running            0               18h     10.104.5.184    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-proxy-0                             1/1     Running            0               18h     10.104.20.190   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-pulsar-init-47nmx                   0/1     Completed          0               18h     10.104.17.171   4am-node23   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-recovery-0                          1/1     Running            0               18h     10.104.5.181    4am-node12   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-0                         1/1     Running            0               18h     10.104.14.188   4am-node18   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-1                         1/1     Running            0               18h     10.104.20.204   4am-node22   <none>           <none>
lb-helm-scene10-ivfsq8-pulsar-zookeeper-2                         1/1     Running            0               18h     10.104.4.184    4am-node11   <none>           <none>
```
dataNode log:
[lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4.log](https://github.com/milvus-io/milvus/files/12046980/lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4.log)

```
datanodedatanode4am-node28lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-nlmt9stderr | /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0040adb40 sp=0xc0040ada80 pc=0x14d9337Show context
-- | --
  |   | datanodedatanode4am-node28lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-nlmt9stderr | panic({0x3b1a860, 0xc0050aecf0})
  |   | datanodedatanode4am-node28lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-nlmt9stderr | panic: attempt #0: err: find no available datacoord, check datacoord state
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | runtime.sigpanic()
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | /usr/local/go/src/runtime/panic.go:220
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | runtime.panicmem(...)
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc000851258 sp=0xc000851198 pc=0x14d9337
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | panic({0x39b6b60, 0x599b220})
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstderr | panic: runtime error: invalid memory address or nil pointer dereference
  |   | datacoorddatacoord4am-node18lb-helm-scene10-ivfsq8-milvus-datacoord-7cd8cf76fb-nf4ltstdout | [2023/07/13 11:01:15.721 +00:00] [FATAL] [logutil/logutil.go:132] [panic] [recover="\"datacoord ServerHandler HasCollection finally failed\""] [stack="github.com/milvus-io/milvus/pkg/util/logutil.LogPanic\n\t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/logutil.go:132\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:838\ngithub.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).HasCollection\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:386\ngithub.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).CheckShouldDropChannel\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:412\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).isMarkedDrop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:883\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).Reassign\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:777\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).processAck\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:656\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).watchChannelStatesLoop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:740"]
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | runtime.sigpanic()
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | /usr/local/go/src/runtime/panic.go:220
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | runtime.panicmem(...)
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001a819c0 sp=0xc001a81900 pc=0x14d9337
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | panic({0x39b6b60, 0x599b220})
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | panic: runtime error: invalid memory address or nil pointer dereference
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | runtime.sigpanic()
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | /usr/local/go/src/runtime/panic.go:220
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | runtime.panicmem(...)
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0044cc9c0 sp=0xc0044cc900 pc=0x14d9337
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | panic({0x39b6b60, 0x599b220})
  |   | datanodedatanode4am-node11lb-helm-scene10-ivfsq8-milvus-datanode-84fff6988d-5zlx4stderr | panic: runtime error: invalid memory address or nil pointer dereference
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | runtime.sigpanic()
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | /usr/local/go/src/runtime/panic.go:220
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | runtime.panicmem(...)
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc00152f030 sp=0xc00152ef70 pc=0x14d9337
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | panic({0x39b6b60, 0x599b220})
  |   | querycoordquerycoord4am-node18lb-helm-scene10-ivfsq8-milvus-querycoord-7d5b446869-46stcstderr | panic: runtime error: invalid memory address or nil pointer dereference

```

client logs:
[clients.log](https://github.com/milvus-io/milvus/files/12046988/clients.log)

![image](https://github.com/milvus-io/milvus/assets/26307815/aa7ac5e9-f0ab-4e84-b976-e7dc4ba78196)

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 3 queryNodes
2、concurrent 9 clients which have 3 types: replica=1, replica=2 and replica=3; each type has 3 clients
   a. create a collection with shard_num=2
   b. insert 10m data, build IVF_SQ8 index
   c. load with replica=1 or 2 or 3
   d. concurrent query, search, scene_search_test by locust <- raise error

scene_search_test:
1. create a collection with dim=128
2. insert 3000 data
3. flush collection
4. count entities of collection
5. build IVF_SQ8 index with nlist=2048
6. load collection with replica=1 or 2 or 3
7. search collection once with nprobe=1028, nq=1, topk=10
8. drop collection
```

### Anything else?

fouramf-server-lb-3qn-2dn-large:
```
    queryNode:
      resources:
        limits:
          cpu: '50.0'
          memory: 100Gi
        requests:
          cpu: '25.0'
          memory: 50Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          cpu: '16.0'
          memory: 16Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 3
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '2.0'
          memory: 16Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-ivfsq8-replica3-shard2-search-query-scene:
```
    load_params:
      replica_number: 3
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 3
```

fouramf-client-sift-ivfsq8-replica2-shard2-search-query-scene:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 2
```

fouramf-client-sift-ivfsq8-replica1-shard2-search-query-scene:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 1
```
