### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] In the scenario of multiple clients, high concurrency query and search, that api raise error

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230713-ed3e4b0b
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-dltq7
upgrade image: fouramf-h9fwl
client argo task: fouramf-concurrent-pjf5f

server:
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-multi-hnsw-etcd-0                                         1/1     Running            0               31h     10.104.1.87     4am-node10   <none>           <none>
lb-helm-multi-hnsw-etcd-1                                         1/1     Running            0               31h     10.104.18.130   4am-node25   <none>           <none>
lb-helm-multi-hnsw-etcd-2                                         1/1     Running            0               31h     10.104.23.225   4am-node27   <none>           <none>
lb-helm-multi-hnsw-milvus-datacoord-68c885846d-m4xxh              1/1     Running            0               31h     10.104.13.75    4am-node16   <none>           <none>
lb-helm-multi-hnsw-milvus-datanode-7df65cd9d9-h74j4               1/1     Running            0               31h     10.104.13.72    4am-node16   <none>           <none>
lb-helm-multi-hnsw-milvus-datanode-7df65cd9d9-qw77h               1/1     Running            0               31h     10.104.12.222   4am-node17   <none>           <none>
lb-helm-multi-hnsw-milvus-indexcoord-595b6fc7f9-mspl7             1/1     Running            0               31h     10.104.13.74    4am-node16   <none>           <none>
lb-helm-multi-hnsw-milvus-indexnode-bb4c5fcd8-hxzbx               1/1     Running            0               31h     10.104.13.77    4am-node16   <none>           <none>
lb-helm-multi-hnsw-milvus-indexnode-bb4c5fcd8-l6p8s               1/1     Running            0               31h     10.104.4.42     4am-node11   <none>           <none>
lb-helm-multi-hnsw-milvus-proxy-6c59b46c47-n986z                  1/1     Running            0               31h     10.104.24.191   4am-node29   <none>           <none>
lb-helm-multi-hnsw-milvus-querycoord-5685ccdbbd-6gwm8             1/1     Running            0               31h     10.104.13.73    4am-node16   <none>           <none>
lb-helm-multi-hnsw-milvus-querynode-798ffb99f8-g4gxg              1/1     Running            0               31h     10.104.24.192   4am-node29   <none>           <none>
lb-helm-multi-hnsw-milvus-querynode-798ffb99f8-wrpdj              1/1     Running            0               31h     10.104.12.223   4am-node17   <none>           <none>
lb-helm-multi-hnsw-milvus-rootcoord-759777467b-l62p7              1/1     Running            0               31h     10.104.13.76    4am-node16   <none>           <none>
lb-helm-multi-hnsw-minio-0                                        1/1     Running            0               2d21h   10.104.18.144   4am-node25   <none>           <none>
lb-helm-multi-hnsw-minio-1                                        1/1     Running            0               2d21h   10.104.1.104    4am-node10   <none>           <none>
lb-helm-multi-hnsw-minio-2                                        1/1     Running            0               2d21h   10.104.23.50    4am-node27   <none>           <none>
lb-helm-multi-hnsw-minio-3                                        1/1     Running            0               2d21h   10.104.20.29    4am-node22   <none>           <none>
lb-helm-multi-hnsw-pulsar-bookie-0                                1/1     Running            0               2d21h   10.104.18.145   4am-node25   <none>           <none>
lb-helm-multi-hnsw-pulsar-bookie-1                                1/1     Running            0               2d21h   10.104.1.105    4am-node10   <none>           <none>
lb-helm-multi-hnsw-pulsar-bookie-2                                1/1     Running            0               2d21h   10.104.23.53    4am-node27   <none>           <none>
lb-helm-multi-hnsw-pulsar-broker-0                                1/1     Running            0               2d21h   10.104.18.134   4am-node25   <none>           <none>
lb-helm-multi-hnsw-pulsar-proxy-0                                 1/1     Running            0               2d21h   10.104.18.133   4am-node25   <none>           <none>
lb-helm-multi-hnsw-pulsar-recovery-0                              1/1     Running            0               2d21h   10.104.16.165   4am-node21   <none>           <none>
lb-helm-multi-hnsw-pulsar-zookeeper-0                             1/1     Running            0               2d21h   10.104.16.168   4am-node21   <none>           <none>
lb-helm-multi-hnsw-pulsar-zookeeper-1                             1/1     Running            0               2d21h   10.104.1.107    4am-node10   <none>           <none>
lb-helm-multi-hnsw-pulsar-zookeeper-2                             1/1     Running            0               2d21h   10.104.21.135   4am-node24   <none>           <none>
```

clients logs:
[clients.log](https://github.com/milvus-io/milvus/files/12049656/clients.log)

<img width="1860" alt="截屏2023-07-14 18 55 11" src="https://github.com/milvus-io/milvus/assets/26307815/1049acb0-ea53-4c3e-9621-1548be8ad2b6">

<img width="1693" alt="截屏2023-07-14 19 02 16" src="https://github.com/milvus-io/milvus/assets/26307815/f567dce3-07dc-4d23-afcc-a9676c5326bb">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 2 queryNodes
2、concurrent 10 client which have 2 types: replica=1 and replica=2; each type has 5 clients
   a. create a collection with shard_num=2
   b. insert 5m data, build HNSW index
   c. load with replica=1 or 2
   d. concurrent query and search by locust <- raise error
```

### Anything else?

fouramf-server-lb-2qn-2dn-large:
```
queryNode:
  resources:
    limits:
      cpu: '50.0'
      memory: 100Gi
    requests:
      cpu: '25.0'
      memory: 50Gi
  replicas: 2
indexNode:
  resources:
    limits:
      cpu: '8.0'
      memory: 8Gi
    requests:
      cpu: '5.0'
      memory: 5Gi
  replicas: 2
dataNode:
  resources:
    limits:
      cpu: '2.0'
      memory: 16Gi
    requests:
      cpu: '2.0'
      memory: 2Gi
  replicas: 2
```

fouramf-client-sift-hnsw-replica1-shard2-nq1-search-query-high:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 5m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 100
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 10000
          top_k: 10
          search_param:
            ef: 64
          timeout: 60
          random_data: true
```

fouramf-client-sift-hnsw-replica2-shard2-nq1-search-query-high:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 5m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 100
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 10000
          top_k: 10
          search_param:
            ef: 64
          timeout: 60
          random_data: true
```
