### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] In the scenario of high concurrency ddl and dql, load collection raise error: `collection has not been loaded to memory or load failed` when resources are sufficient

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230714-f2b14b43
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-jgwzr
clients argo task: fouramf-concurrent-lfhnc

server:
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-ivfsq8-scene-high-etcd-0                                  1/1     Running            0               2d19h   10.104.17.236   4am-node23   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-1                                  1/1     Running            0               2d19h   10.104.16.40    4am-node21   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-2                                  1/1     Running            0               2d19h   10.104.19.90    4am-node28   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datacoord-77bf5b6bdd-m9w4m       1/1     Running            0               2d19h   10.104.6.70     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-6695b89dfd-k4xtb        1/1     Running            0               2d19h   10.104.24.192   4am-node29   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-6695b89dfd-sm8qm        1/1     Running            0               2d19h   10.104.6.69     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexcoord-5f5cf7c57d-dj6d4      1/1     Running            0               2d19h   10.104.6.72     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-59c9c54966-2gzrr       1/1     Running            0               2d19h   10.104.23.208   4am-node27   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-59c9c54966-5qfk2       1/1     Running            0               2d19h   10.104.17.231   4am-node23   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-59c9c54966-nsb6g       1/1     Running            0               2d19h   10.104.5.46     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-proxy-7fb7f74fcd-qf7zx           1/1     Running            0               2d19h   10.104.17.232   4am-node23   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querycoord-67bd9549b9-hqz26      1/1     Running            0               2d19h   10.104.5.47     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-774c95c859-jww9j       1/1     Running            0               2d19h   10.104.24.193   4am-node29   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-774c95c859-kvxk6       1/1     Running            0               2d19h   10.104.4.208    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-774c95c859-x4r2z       1/1     Running            0               2d19h   10.104.6.74     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-rootcoord-7fbf6987df-fmkc5       1/1     Running            0               2d19h   10.104.24.191   4am-node29   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-0                                 1/1     Running            0               2d19h   10.104.23.209   4am-node27   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-1                                 1/1     Running            0               2d19h   10.104.16.43    4am-node21   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-2                                 1/1     Running            0               2d19h   10.104.19.89    4am-node28   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-3                                 1/1     Running            0               2d19h   10.104.5.49     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-0                         1/1     Running            0               2d19h   10.104.16.45    4am-node21   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-1                         1/1     Running            0               2d19h   10.104.19.97    4am-node28   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-2                         1/1     Running            0               2d19h   10.104.5.55     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-init-8dzcx                0/1     Completed          0               2d19h   10.104.6.71     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-broker-0                         1/1     Running            0               2d19h   10.104.16.36    4am-node21   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-proxy-0                          1/1     Running            0               2d19h   10.104.23.206   4am-node27   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-pulsar-init-5v5vl                0/1     Completed          0               2d19h   10.104.6.73     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-recovery-0                       1/1     Running            0               2d19h   10.104.16.37    4am-node21   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-0                      1/1     Running            0               2d19h   10.104.17.235   4am-node23   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-1                      1/1     Running            0               2d19h   10.104.12.127   4am-node17   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-2                      1/1     Running            0               2d19h   10.104.13.162   4am-node16   <none>           <none>
```
<img width="1394" alt="截屏2023-07-17 14 46 53" src="https://github.com/milvus-io/milvus/assets/26307815/584a96e0-adc5-4c81-93fd-147f4dd0826f">
<img width="1388" alt="截屏2023-07-17 14 47 03" src="https://github.com/milvus-io/milvus/assets/26307815/4ac4d9b4-ef38-4f32-8865-230493448a73">
<img width="1389" alt="截屏2023-07-17 14 47 15" src="https://github.com/milvus-io/milvus/assets/26307815/f60cfdd4-1af3-4625-9315-6b28461acec8">
<img width="1381" alt="截屏2023-07-17 14 48 25" src="https://github.com/milvus-io/milvus/assets/26307815/127a2c39-fc2f-46a3-85b8-765735a5d84c">

clients log:
[clients.log](https://github.com/milvus-io/milvus/files/12066622/clients.log)
<img width="1391" alt="截屏2023-07-17 14 45 48" src="https://github.com/milvus-io/milvus/assets/26307815/3917e439-c275-4784-a9b8-5e594c894c99">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 3 queryNodes
2、concurrent 9 clients which have 3 types: replica=1, replica=2 and replica=3; each type has 3 clients
   a. create a collection with shard_num=2
   b. insert 10m data, build IVF_SQ8 index
   c. load with replica=1 or 2 or 3
   d. concurrent query, search, scene_search_test by locust <- raise error

scene_search_test:
1. create a collection with dim=128, shards_num=1 or 2 or 3
2. insert 3000 data
3. flush collection
4. count entities of collection
5. build IVF_SQ8 index with nlist=2048
6. load collection with replica=1 or 2 or 3
7. search collection once with nprobe=1028, nq=1, topk=10
8. drop collection
```

### Anything else?

fouramf-server-lb-3qn-2dn-large:
```
    queryNode:
      resources:
        limits:
          cpu: '50.0'
          memory: 100Gi
        requests:
          cpu: '25.0'
          memory: 50Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          cpu: '16.0'
          memory: 16Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 3
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '2.0'
          memory: 16Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-ivfsq8-replica3-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 3
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 1
          replica_number: 3
```

fouramf-client-sift-ivfsq8-replica2-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 2
          replica_number: 2
```

fouramf-client-sift-ivfsq8-replica1-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 3
          replica_number: 1
```
