### ISSUE TITLE
[Bug]: S3 storage doesn't work with index node (curlCode: 3, URL using bad/illegal format or missing URL)

### ISSUE THREAD

**Issue by mkotsalainen** [milvus-io/milvus#25748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.10 - Helm chart 4.0.25
- Deployment mode(standalone or cluster): cluster
```

### Current Behavior

After switching to S3 storage from Minio I can’t index my data any more. I see that data gets into s3 the bucket and it shows up in milvus-attu but when I try to load the collection nothing happens. When I check the logs I see this:
```
indexnode [2023/07/19 07:21:06.702 +00:00] [WARN] [indexcgowrapper/helper.go:76] ["failed to create index, C Runtime Exception: [UnexpectedError] Error:GetObjectS
ize:  curlCode: 3, URL using bad/illegal format or missing URL\n"]
```

These are my Heml chart settings (I use IRSA roles for s3 access)
```
milvus:
  externalS3:
    enabled: true
    bucketName: xxx-milvus
    host: s3.eu-west-1.amazonaws.com
    useIAM: true
  minio:
    enabled: false
```

Because of this error the indexnode keeps crashing. I wonder if this is related to: https://github.com/milvus-io/milvus/issues/25725 - they mention S3 also but they have a different stack trace.

### Expected Behavior

when I index my data it should work

### Steps To Reproduce

```markdown
Use the 4.0.25 Helm chart and try to store data to S3.
```
