### ISSUE TITLE
[Bug]: Minio Disk Size Increasing Exponentially

### ISSUE THREAD

**Issue by harpreetpaul** [milvus-io/milvus#25815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We are running Milvus v2.2.8 on GKE cluster managed via Operator. Our Minio has started acting up lately. The allocated persistence storage is filling up quick and not getting released. Below is our Milvus resource file.

We have a daily job that purges and adds fresh collections. Looks like the old collections are not getting cleaned up. We have changes the retentionDuration from initial '0' to a values that is last 24hrs / 86400 secs. Not sure it that had any impact on cleaning up of data. 

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvusdb
  namespace: milvusdb
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies:
    storage: #
      external: false
      type: "MinIO" # Optional ("MinIO", "S3") default:="MinIO"
      inCluster:
        pvcDeletion: false
        values:
          persistence:
            size: 750Gi
          resources:
            limits:
              cpu: '2'
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 2Gi
          statefulset:
            replicaCount: 8
  components:
    queryNode:
      replicas: 3
      resources:
        limits:
          cpu: '2'
          memory: 12Gi
        requests:
          cpu: '2'
          memory: 8Gi
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '3'
          memory: 12Gi
        requests:
          cpu: '1'
          memory: 4Gi

  config:
    common:
      security:
        authorizationEnabled: true
      retentionDuration: 86400 
      entityExpiration: 86400 
    dataCoord:
      gc:
        interval: 3600 
        missingTolerance: 43200 
        dropTolerance: 43200 
```

### Expected Behavior

Minio disk size should not rapidly increase
