### ISSUE TITLE
[Bug]: The diskQuota config does not limit the disk as expected and trigger insert deny

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230719-e418ab2f
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.0.dev100
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone and config disk quota protection
```
    limitWriting:
      diskProtection:
        diskQuota: 1000
        diskQuotaPerCollection: 500
        enabled: true
```
2. Insert 2m-128d data into 3 collections sequentially
 2.1 collection-1: insert id 1090000 gets disk quota deny error
 2.2 collection-2: insert id 1040000 gets disk quota deny error
 2.3 New 3 collection and insert data 1m successfully, but expect to trigger global disk quota protection and gets quota deny error at the first id

3. collections and num_entities
```
fouram_17pl6bX9 1040000
fouram_JbxP9HhR 970000
fouram_O0efHTkx 540000
fouram_eJRc2Pt8 1090000
fouram_hPVjQacA 1040000
```

3. dataCoord Stored Binglog Size
![image](https://github.com/milvus-io/milvus/assets/27288593/e9834874-3d07-40dc-9c57-bd75416ada94)

### Steps To Reproduce

```markdown
argo workflow name: https://argo-workflows.zilliz.cc/archived-workflows/qa/4413d058-78ff-48ef-91c3-801fd09a960f?nodeId=master-insert-disk-stand-3-jm8vd

grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-3&var-collection=All&var-app_name=milvus&from=1689926749000&to=1689930010000

server pods:

quota-limit-3-etcd-0                                              1/1     Running            0                 25h     10.104.18.171   4am-node25   <none>           <none>
quota-limit-3-milvus-standalone-685c678f9-gpxr9                   1/1     Running            0                 57m     10.104.13.219   4am-node16   <none>           <none>
quota-limit-3-minio-575986b859-l78gm                              1/1     Running            0                 25h     10.104.13.5     4am-node16   <none>           <none>
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by bigsheeper** [comment]
Did not reproduce.

**Comment by ThreadDao** [comment]
I didn't reproduce either

image: `master-20230811-9489e140`
config:
```
  config:
    log:
      level: debug
    quotaAndLimits:
      limitWriting:
        diskProtection:
          diskQuota: 1000
          diskQuotaPerCollection: 500
          enabled: true
```

1. first collection insert 1050000 entities -> gets disk deny error
2. second collection insert 950000 entities -> gets disk deny error
3. 3th collection insert  0 -> gets disk deny error
```
fouram_cPANnBhF 0
fouram_F6uIGwCx 1050000
fouram_eND4LfeI 950000
```
