### ISSUE TITLE
[Bug]: The deny error message of growingSegmentSizeProtection is same with the deny message of memProtection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230719-e418ab2f
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev100
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy with quotaAndLimit config
```
growingSegmentsSizeprotection:
    enabled: true
    lowWaterLevel: 0.05
    highWaterLevel: 0.1
memProtection:
    enabled: false
```
resource config
```
standalone:
      resources:
        limits:
          cpu: "8" 
          memory: 10Gi
```

2. Test and trigger the growing mem protection
create a collection -> create index -> load -> concurrent 20 users to insert 30min with batch 100 and dim 768 -> insert deny with the message
```
[2023-07-21 07:09:14,110 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-07-21 07:09:10.371375', 'RPC error': '2023-07-21 07:09:14.110595'}> (decorators.py:125)
[2023-07-21 07:09:14,112 - ERROR - fouram]: (api_response) : <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)> (api_request.py:53)
```
the error message is the same with memProtection mem deny. If the error message shows that the insert deny reason is related to growing segment size will be better. Users will upgrade the config other upgrade the datanode or querynode memory

### Expected Behavior

If the error message shows that the insert deny reason is related to growing segment size will be better.

### Steps To Reproduce

```markdown
argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/1cf64b4f-38eb-4f58-8c78-859cd5510352?nodeId=master-insert-growing-stand-5-vxx92
```

### Milvus Log

![image](https://github.com/milvus-io/milvus/assets/27288593/3f1260ad-dd82-410b-b8e0-dc079c2fb5a7)

### Anything else?

server grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-3&var-collection=All&var-app_name=milvus&from=1689922646308&to=1689923975187

**Comment by bigsheeper** [comment]
/assign @ThreadDao 

should be fixed, please help to verify

**Comment by ThreadDao** [comment]
@bigsheeper 
/assign @bigsheeper 
I can't trigger the growingSegmentSize protection insert deny. I did not set the insertRate, so when the queryable growing segment memory reaches the `growingSegmentsSizeProtection.highWaterLevel` value, a write deny error will be returned. But it seems that the python-sdk will retry many times, and finally either the growing memory decrease or pod oomkilled or memoryProtection deny. Do you have any suggestions for triggering the growingSegmentsSizeProtection write deny ?
- image: `master-20230811-9489e140`
- config
```
  config:
    dataCoord:
      segment:
        maxSize: 2048
    log:
      level: debug
    quotaAndLimits:
      limitWriting:
        growingSegmentsSizeProtection:
          enabled: true
          highWaterLevel: 0.03
          lowWaterLevel: 0.03
        memProtection:
          enabled: false
```
- resource
```
    standalone:
      paused: false
      replicas: 1
      resources:
        limits:
          cpu: "8"
          memory: 16Gi
        requests:
          cpu: "4"
          memory: 5Gi
```
- growing queryable size
![image](https://github.com/milvus-io/milvus/assets/27288593/be782bd3-1706-4533-b899-65e689662b6a)


grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=zong-issue&var-collection=All&var-app_name=milvus&from=1691774652334&to=1691776015899

argo link:  https://argo-workflows.zilliz.cc/archived-workflows/qa?namePrefix=master-insert-growing-issue&minStartedAt=2023-07-11T16%3A00%3A00.000Z&maxStartedAt=2023-08-12T16%3A00%3A00.000Z
