### ISSUE TITLE
[Bug]: [benchmark][multi-replicas-loadbalance] queryNodes keep restarting, clients' request raise error

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#25940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230726-6f18587f
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server argo task: fouramf-jtx7q
clients argo task: fouramf-concurrent-n8b7q

server: 
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-ivfsq8-scene-high-etcd-0                                  1/1     Running            0               4m23s   10.104.9.154    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-1                                  1/1     Running            0               4m23s   10.104.5.152    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-2                                  1/1     Running            0               4m22s   10.104.6.85     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datacoord-769c9d848d-wkcfv       1/1     Running            0               4m23s   10.104.9.147    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-69bfbcc6b6-28mpk        1/1     Running            0               4m23s   10.104.9.146    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-69bfbcc6b6-gzcsf        1/1     Running            0               4m23s   10.104.5.143    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexcoord-6c55b8758-tw9hx       1/1     Running            0               4m23s   10.104.4.208    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-6dqp5       1/1     Running            0               4m22s   10.104.21.60    4am-node24   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-h5z58       1/1     Running            0               4m22s   10.104.13.94    4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-q2wbv       1/1     Running            0               4m23s   10.104.5.140    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-proxy-6b4c549846-cp7tr           1/1     Running            0               4m23s   10.104.5.142    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querycoord-68d589fc85-mqdng      1/1     Running            0               4m23s   10.104.9.148    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-jvkk7       1/1     Running            0               4m22s   10.104.4.211    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-mvqkb       1/1     Running            0               4m23s   10.104.9.151    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-zfdpt       1/1     Running            0               4m22s   10.104.12.161   4am-node17   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-rootcoord-6547f7b86f-4cfrd       1/1     Running            0               4m23s   10.104.9.141    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-0                                 1/1     Running            0               4m23s   10.104.9.155    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-1                                 1/1     Running            0               4m23s   10.104.5.151    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-2                                 1/1     Running            0               4m22s   10.104.6.81     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-3                                 1/1     Running            0               4m22s   10.104.15.225   4am-node20   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-0                         1/1     Running            0               4m23s   10.104.5.146    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-1                         1/1     Running            0               4m22s   10.104.6.86     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-2                         1/1     Running            0               4m22s   10.104.15.227   4am-node20   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-init-thfhv                0/1     Completed          0               4m23s   10.104.9.150    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-broker-0                         1/1     Running            0               4m23s   10.104.9.142    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-proxy-0                          1/1     Running            0               4m23s   10.104.4.209    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-pulsar-init-cxbmv                0/1     Completed          0               4m23s   10.104.9.149    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-recovery-0                       1/1     Running            0               4m23s   10.104.9.145    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-0                      1/1     Running            0               4m22s   10.104.5.149    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-1                      1/1     Running            0               3m33s   10.104.6.88     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-2                      1/1     Running            0               2m57s   10.104.14.181   4am-node18   <none>           <none>
```

```
NAME                                                              READY   STATUS             RESTARTS          AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-ivfsq8-scene-high-etcd-0                                  1/1     Running            0                 153m    10.104.9.154    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-1                                  1/1     Running            0                 153m    10.104.5.152    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-2                                  1/1     Running            0                 153m    10.104.6.85     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datacoord-769c9d848d-wkcfv       1/1     Running            0                 153m    10.104.9.147    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-69bfbcc6b6-28mpk        1/1     Running            0                 153m    10.104.9.146    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-69bfbcc6b6-gzcsf        1/1     Running            0                 153m    10.104.5.143    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexcoord-6c55b8758-tw9hx       1/1     Running            0                 153m    10.104.4.208    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-6dqp5       1/1     Running            0                 153m    10.104.21.60    4am-node24   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-h5z58       1/1     Running            0                 153m    10.104.13.94    4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-6c44dc8b66-q2wbv       1/1     Running            0                 153m    10.104.5.140    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-proxy-6b4c549846-cp7tr           1/1     Running            0                 153m    10.104.5.142    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querycoord-68d589fc85-mqdng      1/1     Running            0                 153m    10.104.9.148    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-jvkk7       0/1     Error              20 (6m10s ago)    153m    10.104.4.211    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-mvqkb       1/1     Running            13 (28m ago)      153m    10.104.9.151    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-597dfb95dc-zfdpt       0/1     CrashLoopBackOff   8 (4m16s ago)     153m    10.104.12.161   4am-node17   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-rootcoord-6547f7b86f-4cfrd       1/1     Running            0                 153m    10.104.9.141    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-0                                 1/1     Running            0                 153m    10.104.9.155    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-1                                 1/1     Running            0                 153m    10.104.5.151    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-2                                 1/1     Running            0                 153m    10.104.6.81     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-3                                 1/1     Running            0                 153m    10.104.15.225   4am-node20   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-0                         1/1     Running            0                 153m    10.104.5.146    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-1                         1/1     Running            0                 153m    10.104.6.86     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-2                         1/1     Running            0                 153m    10.104.15.227   4am-node20   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-init-thfhv                0/1     Completed          0                 153m    10.104.9.150    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-broker-0                         1/1     Running            0                 153m    10.104.9.142    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-proxy-0                          1/1     Running            0                 153m    10.104.4.209    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-pulsar-init-cxbmv                0/1     Completed          0                 153m    10.104.9.149    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-recovery-0                       1/1     Running            0                 153m    10.104.9.145    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-0                      1/1     Running            0                 153m    10.104.5.149    4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-1                      1/1     Running            0                 152m    10.104.6.88     4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-2                      1/1     Running            0                 151m    10.104.14.181   4am-node18   <none>           <none>
```
<img width="1843" alt="截屏2023-07-26 17 46 19" src="https://github.com/milvus-io/milvus/assets/26307815/257a1cb0-618d-48bd-905a-2f7da57f4fe6">

clients log:
[clients.log](https://github.com/milvus-io/milvus/files/12170744/clients.log)

<img width="1857" alt="截屏2023-07-26 17 45 00" src="https://github.com/milvus-io/milvus/assets/26307815/089b18e6-886a-42f7-863b-20ab18fd130e">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 3 queryNodes
2、concurrent 9 clients which have 3 types: replica=1, replica=2 and replica=3; each type has 3 clients
   a. create a collection with shard_num=2
   b. insert 10m data, build IVF_SQ8 index
   c. load with replica=1 or 2 or 3
   d. concurrent query, search, scene_search_test by locust <- raise error

scene_search_test:
1. create a collection with dim=128, shards_num=1 or 2 or 3
2. insert 3000 data
3. flush collection
4. count entities of collection
5. build IVF_SQ8 index with nlist=2048
6. load collection with replica=1 or 2 or 3
7. search collection once with nprobe=1028, nq=1, topk=10
8. drop collection
```

### Anything else?

fouramf-server-lb-3qn-2dn-large:
```
    queryNode:
      resources:
        limits:
          cpu: '50.0'
          memory: 100Gi
        requests:
          cpu: '25.0'
          memory: 50Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          cpu: '16.0'
          memory: 16Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 3
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '2.0'
          memory: 16Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-ivfsq8-replica3-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 3
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 1
          replica_number: 3
```

fouramf-client-sift-ivfsq8-replica2-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 2
          replica_number: 2
```

fouramf-client-sift-ivfsq8-replica1-shard2-search-query-scene-high:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 100
      during_time: 12h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          random_data: true
          random_count: 10
          random_range: [0, 500000]
      - type: search
        weight: 1
        params:
          nq: 100
          top_k: 10
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          shards_num: 3
          replica_number: 1
```

**Comment by yah01** [comment]
related #25931

**Comment by yah01** [comment]
related #25931

**Comment by weiliu1031** [comment]
related to #25895

**Comment by wangting0128** [comment]
image: master-20230731-a3e22786
server argo task: fouramf-ltr4n
clients argo task: fouramf-concurrent-s85jp

server config:
```
    extraConfigFiles:
      user.yaml: |+
        common:
          threadCoreCoefficient: 50
    queryNode:
      resources:
        limits:
          cpu: '50.0'
          memory: 100Gi
        requests:
          cpu: '25.0'
          memory: 50Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          # cpu: '4.0'
          # memory: 4Gi
          cpu: '16.0'
          memory: 16Gi
        requests:
          # cpu: '3.0'
          # memory: 3Gi
          cpu: '5.0'
          memory: 5Gi
      replicas: 3
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '2.0'
          memory: 16Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

server:
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-ivfsq8-scene-high-etcd-0                                  1/1     Running            0               111m    10.104.5.42     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-1                                  1/1     Running            0               111m    10.104.14.200   4am-node18   <none>           <none>
lb-helm-ivfsq8-scene-high-etcd-2                                  1/1     Running            0               111m    10.104.9.159    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datacoord-7f6fdbd68f-fw8w6       1/1     Running            0               111m    10.104.13.106   4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-7789d7ff59-8xmdx        1/1     Running            0               111m    10.104.14.195   4am-node18   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-datanode-7789d7ff59-ctgtw        1/1     Running            0               111m    10.104.4.137    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexcoord-65fb99d7f9-t8886      1/1     Running            0               111m    10.104.13.104   4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-9fdb57fcc-2zzmr        1/1     Running            0               111m    10.104.9.152    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-9fdb57fcc-rxjrg        1/1     Running            0               111m    10.104.4.139    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-indexnode-9fdb57fcc-vj8kq        1/1     Running            0               111m    10.104.24.45    4am-node29   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-proxy-75b89b669c-xfcfj           1/1     Running            0               111m    10.104.9.150    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querycoord-7dcfc99ffb-pfxxt      1/1     Running            0               111m    10.104.13.100   4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-b6b57d8-9dqrh          1/1     Running            4 (5m16s ago)   111m    10.104.12.15    4am-node17   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-b6b57d8-qzzbm          1/1     Running            0               111m    10.104.13.101   4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-querynode-b6b57d8-wtg4f          1/1     Running            9 (5m ago)      111m    10.104.6.122    4am-node13   <none>           <none>
lb-helm-ivfsq8-scene-high-milvus-rootcoord-5ff454568-7fw68        1/1     Running            0               111m    10.104.13.105   4am-node16   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-0                                 1/1     Running            0               111m    10.104.5.41     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-1                                 1/1     Running            0               111m    10.104.14.198   4am-node18   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-2                                 1/1     Running            0               111m    10.104.9.161    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-minio-3                                 1/1     Running            0               111m    10.104.4.141    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-0                         1/1     Running            0               111m    10.104.9.160    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-1                         1/1     Running            0               111m    10.104.14.202   4am-node18   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-2                         1/1     Running            0               111m    10.104.5.47     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-bookie-init-svg5j                0/1     Completed          0               111m    10.104.9.154    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-broker-0                         1/1     Running            0               111m    10.104.5.36     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-proxy-0                          1/1     Running            0               111m    10.104.9.151    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-pulsar-init-5bzg7                0/1     Completed          0               111m    10.104.9.153    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-recovery-0                       1/1     Running            0               111m    10.104.4.138    4am-node11   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-0                      1/1     Running            0               111m    10.104.5.43     4am-node12   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-1                      1/1     Running            0               111m    10.104.9.164    4am-node14   <none>           <none>
lb-helm-ivfsq8-scene-high-pulsar-zookeeper-2                      1/1     Running            0               110m    10.104.14.204   4am-node18   <none>           <none>
```

client logs:
<img width="1378" alt="截屏2023-07-31 16 45 53" src="https://github.com/milvus-io/milvus/assets/26307815/9108fa8d-432d-4daf-8a5d-fcdfeb5b682d">
