### ISSUE TITLE
[Bug]: The upsert throughput on the proxy side exceeds the upsertRate configuration

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230725-33685c02
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev103
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with upsertRate config
```
dml:
  enabled: true
  upsertRate:
    collection:
      max: 5
    max: 10
limitWriting:
  diskProtection:
    diskQuota: 1000
    diskQuotaPerCollection: 500
    enabled: false
  forceDeny: false
  growingSegmentsSizeProtection:
    enabled: false
    highWaterLevel: 0.2
    lowWaterLevel: 0.1
  memProtection:
    dataNodeMemoryHighWaterLevel: 0.9
    dataNodeMemoryLowWaterLevel: 0.85
    enabled: true
    queryNodeMemoryHighWaterLevel: 0.9
    queryNodeMemoryLowWaterLevel: 0.85
  ttProtection:
    enabled: false
    maxTimeTickDelay: 300
```
2. Two collections insert with dim=768 and ni=500, but proxy received bytes rate exceed collection level upsertRate 5MB/s
- client params
```
'concurrent_params': {'concurrent_number': 1,
                                                       'during_time': '20m',
                                                       'interval': 60,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'upsert',
                                                       'weight': 10,
                                                       'params': {'nb': 500,
                                                                  'random_vector': True,
                                                                  'random_id': True,
                                                                  'timeout': 6000}}]
``` 

- proxy received bytes rate

promql: `sum(increase(milvus_proxy_receive_bytes_count{app_kubernetes_io_instance=~"$instance", app_kubernetes_io_name="$app_name", namespace="$namespace"}[1m])/60) by(pod, node_id, collection_name)`

![image](https://github.com/milvus-io/milvus/assets/27288593/4b2a5619-c187-412d-81f7-f3543eed7bfe)

The metrics show that the collection max bytes rate exceeds 5MB/s but the min bytes rate is only 460KB/s. 
It is worth mentioning that each request size is only 1.46 MB (500*768*4/1024/1024), so there should be no punishment period.

3. grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-3&var-collection=All&var-app_name=milvus&from=1690384084361&to=1690385674723

4. argo workflow link: https://argo-workflows.zilliz.cc/archived-workflows/qa/dd8e4e1c-3476-46f1-ae54-1447480a1964?nodeId=master-upsert-stand6-limit&container= 

### Expected Behavior

The trend of the proxy received bytes rate is as shown in the figure below, but the value remains at around 5MB/s. The figure below is the metrics when disable upsertRate limit

![image](https://github.com/milvus-io/milvus/assets/27288593/82ecceab-ca4f-4713-8b58-4f55e87d3836)

**Comment by ThreadDao** [comment]
@bigsheeper It seems that insert does not have this problem
config:
```
dml:
    enabled: true
    insertRate:
      collection:
        max: 9
      max: 10
```
 2 collection insert with batch 500 and dim768, the collection rate and total rate are both inside configuration
![image](https://github.com/milvus-io/milvus/assets/27288593/4a7d13b8-1279-47a1-861c-184ba89a5da5)

![image](https://github.com/milvus-io/milvus/assets/27288593/47303636-60b2-42ab-820d-c0f3548603f7)
