### ISSUE TITLE
[Bug]: [benchmark]After doing a concurrent query and returning the vector, release gets stuck.

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#25986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230728-84253f25
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I tested concurrent query and then prepared the release collection. But as of now, it has been stuck for more than 1h. After checking the log, I found that there are 4 segments in total, and only one has been released.

server:
```
new-stable-mastmswv4-1-57-6044-etcd-0                             1/1     Running            0                5h27m   10.104.6.194    4am-node13   <none>           <none>
new-stable-mastmswv4-1-57-6044-milvus-standalone-c988558fbjmf6h   1/1     Running            0                5h27m   10.104.16.109   4am-node21   <none>           <none>
new-stable-mastmswv4-1-57-6044-minio-65cd47665b-gf6l6             1/1     Running            0                5h27m   10.104.6.193    4am-node13   <none>           <none>
```

loki command:
```
{pod="new-stable-mastmswv4-1-57-6044-milvus-standalone-c988558fbjmf6h"} |~ "(?i)release"
```

![image](https://github.com/milvus-io/milvus/assets/48523564/71b45cdb-6890-4c64-9294-1e8ecc096738)

The following 4 segments see only one segment (443157442447230009) release completed.
segmentID=443157442447230009
segmentID=443157442446429907
segmentID=443157442447230008
segmentID=443157442446429906
 

segment loaded num: 
 
![image](https://github.com/milvus-io/milvus/assets/48523564/2448d6b3-2242-406f-ad85-76151ebe7a96)

 
 
 
 After some speculation, I think I'm stuck at the delete segment from memory step.
![image](https://github.com/milvus-io/milvus/assets/48523564/dedc93a3-e5cc-4208-8757-f25d64bd107b)

### Expected Behavior

release shouldn't be stuck, it can be released normally. 

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column 
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

### Anything else?

Unlike a normal concurrent query, the query output_fields returns the vector. 
client params: 
```
    dataset_params:
      metric_type: L2
      dim: 128
      dataset_name: sift
      dataset_size: 1000000
      ni_per: 50000
    collection_params:
      other_fields:
      - float_1
      shards_num: 2
    load_params: {}
    query_params: {}
    search_params: {}
    resource_groups_params:
      reset: false
    index_params:
      index_type: DISKANN
      index_param: {}
    concurrent_params:
      concurrent_number:
      - 20
      during_time: 4h
      interval: 20
    concurrent_tasks:
    - type: query
      weight: 5
      params:
        limit: 1
        offset: 10
        expr:
          float_1:
            GT: -1
            LT: 500000
        output_fields:
        - float_vector
        timeout: 60
```
