### ISSUE TITLE
[Bug]: [benchmark] queryNode panic and restarts, causing requests to fail

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#26576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230823-b9bc6681
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev73
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-server-client-concurrent-8kgx2

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lb-helm-ivfsq8-low-etcd-0                                         1/1     Running     0               118m    10.104.21.12    4am-node24   <none>           <none>
lb-helm-ivfsq8-low-etcd-1                                         1/1     Running     0               118m    10.104.4.231    4am-node11   <none>           <none>
lb-helm-ivfsq8-low-etcd-2                                         1/1     Running     0               118m    10.104.9.53     4am-node14   <none>           <none>
lb-helm-ivfsq8-low-milvus-datacoord-6ccbc7588-x4wc6               1/1     Running     0               118m    10.104.4.227    4am-node11   <none>           <none>
lb-helm-ivfsq8-low-milvus-datanode-7b9f59b78c-lsn5p               1/1     Running     1 (114m ago)    118m    10.104.24.15    4am-node29   <none>           <none>
lb-helm-ivfsq8-low-milvus-datanode-7b9f59b78c-tcqgk               1/1     Running     1 (114m ago)    118m    10.104.1.150    4am-node10   <none>           <none>
lb-helm-ivfsq8-low-milvus-indexcoord-6b9dbfbc97-kdjpb             1/1     Running     0               118m    10.104.19.128   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-milvus-indexnode-55775cd869-9hnsz              1/1     Running     0               118m    10.104.19.121   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-milvus-indexnode-55775cd869-dfhvv              1/1     Running     0               118m    10.104.9.51     4am-node14   <none>           <none>
lb-helm-ivfsq8-low-milvus-indexnode-55775cd869-xtrqv              1/1     Running     0               118m    10.104.21.7     4am-node24   <none>           <none>
lb-helm-ivfsq8-low-milvus-proxy-695f8b89c-6sj48                   1/1     Running     1 (114m ago)    118m    10.104.19.127   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-milvus-querycoord-5fcc6b485d-tcqnc             1/1     Running     1 (114m ago)    118m    10.104.19.120   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-milvus-querynode-5fd7fd7964-7lxcw              1/1     Running     1 (39m ago)     118m    10.104.6.67     4am-node13   <none>           <none>
lb-helm-ivfsq8-low-milvus-querynode-5fd7fd7964-q57dp              1/1     Running     0               118m    10.104.21.8     4am-node24   <none>           <none>
lb-helm-ivfsq8-low-milvus-querynode-5fd7fd7964-xwct9              1/1     Running     0               118m    10.104.19.126   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-milvus-rootcoord-7d9d8866cd-sjdsm              1/1     Running     1 (114m ago)    118m    10.104.19.122   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-minio-0                                        1/1     Running     0               118m    10.104.6.74     4am-node13   <none>           <none>
lb-helm-ivfsq8-low-minio-1                                        1/1     Running     0               118m    10.104.21.11    4am-node24   <none>           <none>
lb-helm-ivfsq8-low-minio-2                                        1/1     Running     0               118m    10.104.12.18    4am-node17   <none>           <none>
lb-helm-ivfsq8-low-minio-3                                        1/1     Running     0               118m    10.104.18.109   4am-node25   <none>           <none>
lb-helm-ivfsq8-low-pulsar-bookie-0                                1/1     Running     0               118m    10.104.6.73     4am-node13   <none>           <none>
lb-helm-ivfsq8-low-pulsar-bookie-1                                1/1     Running     0               118m    10.104.12.17    4am-node17   <none>           <none>
lb-helm-ivfsq8-low-pulsar-bookie-2                                1/1     Running     0               118m    10.104.4.232    4am-node11   <none>           <none>
lb-helm-ivfsq8-low-pulsar-bookie-init-gk24v                       0/1     Completed   0               118m    10.104.19.118   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-pulsar-broker-0                                1/1     Running     0               118m    10.104.6.66     4am-node13   <none>           <none>
lb-helm-ivfsq8-low-pulsar-proxy-0                                 1/1     Running     0               118m    10.104.19.123   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-pulsar-pulsar-init-zghk6                       0/1     Completed   0               118m    10.104.19.119   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-pulsar-recovery-0                              1/1     Running     0               118m    10.104.19.124   4am-node28   <none>           <none>
lb-helm-ivfsq8-low-pulsar-zookeeper-0                             1/1     Running     0               118m    10.104.6.72     4am-node13   <none>           <none>
lb-helm-ivfsq8-low-pulsar-zookeeper-1                             1/1     Running     0               117m    10.104.9.55     4am-node14   <none>           <none>
lb-helm-ivfsq8-low-pulsar-zookeeper-2                             1/1     Running     0               117m    10.104.4.236    4am-node11   <none>           <none>
```
[lb-helm-ivfsq8-low-milvus-querynode-5fd7fd7964-7lxcw.log](https://github.com/milvus-io/milvus/files/12417260/lb-helm-ivfsq8-low-milvus-querynode-5fd7fd7964-7lxcw.log)

<img width="1683" alt="截屏2023-08-23 16 49 11" src="https://github.com/milvus-io/milvus/assets/26307815/fb544b1a-f5d6-4bb1-8aaa-a9bc02a146fe">

clients log:
[clients.log](https://github.com/milvus-io/milvus/files/12417330/clients.log)

<img width="1911" alt="截屏2023-08-23 17 00 03" src="https://github.com/milvus-io/milvus/assets/26307815/8996662d-fbb6-41f0-b7f0-173b75439004">

### Steps To Reproduce

```markdown
1、deploy cluster Milvus with 3 queryNodes
2、concurrent 9 clients which have 3 types: replica=1, replica=2 and replica=3; each type has 3 clients
   a. create a collection with shard_num=2
   b. insert 10m data, build IVF_SQ8 index
   c. load with replica=1 or 2 or 3
   d. concurrent query, search, scene_search_test by locust <- raise error

scene_search_test:
1. create a collection with dim=128
2. insert 3000 data
3. flush collection
4. count entities of collection
5. build IVF_SQ8 index with nlist=2048
6. load collection with replica=1 or 2 or 3
7. search collection once with nprobe=1028, nq=1, topk=10
8. drop collection
```

### Anything else?

fouramf-server-lb-3qn-2dn-large:
```
    queryNode:
      resources:
        limits:
          cpu: '50.0'
          memory: 100Gi
        requests:
          cpu: '25.0'
          memory: 50Gi
      replicas: 3
    indexNode:
      resources:
        limits:
          cpu: '16.0'
          memory: 16Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 3
    dataNode:
      replicas: 2
      resources:
        limits:
          cpu: '2.0'
          memory: 16Gi
        requests:
          cpu: '2.0'
          memory: 2Gi
```

fouramf-client-sift-ivfsq8-replica3-shard2-search-query-scene:
```
    load_params:
      replica_number: 3
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 3
```

fouramf-client-sift-ivfsq8-replica2-shard2-search-query-scene:
```
    load_params:
      replica_number: 2
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 2
```

fouramf-client-sift-ivfsq8-replica1-shard2-search-query-scene:
```
    load_params:
      replica_number: 1
    collection_params:
      shards_num: 2
    dataset_params:
      dim: 128
      dataset_name: sift
      dataset_size: 10m
      ni_per: 50000
      metric_type: L2
    index_params:
      index_type: IVF_SQ8
      index_param:
        nlist: 2048
    concurrent_params:
      concurrent_number: 3
      during_time: 2h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          ids: [1, 100, 1000]
      - type: search
        weight: 1
        params:
          nq: 1
          top_k: 1
          search_param:
            nprobe: 64
          timeout: 60
          random_data: true
      - type: scene_search_test
        weight: 1
        params:
          replica_number: 1
```
