### ISSUE TITLE
[Bug]: [laion-1b] Restore a 100m-768d collection failed and milvus-backup process sleep

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230828-bc6b376c
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: milvus-backup version: 1.0-beta
```

### Current Behavior

1. 2023-08-29 08:24:31 backup collection that has 100m-768d entities successfully with cmd `./milvus-backup create -n backup --config backup.yaml`. By the way, there are only 1 collection and 94 segments. The backup.yaml is as following. If you need the minio host and accessKey you can contact me.
```
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup_1.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: *
  port: 8443
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: 10.*.*.201 # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: * # accessKeyID of MinIO/S3
  secretAccessKey: * # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""

  bucketName: "laion-test-3" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "laion-test-3" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup1" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G
```

2. At 2023-09-05 06:32:05, Restore backup collection with cmd `./milvus-backup restore -n backup -s "_bak" --config backup.yaml`. However only 31 segments bulkinsert successfully and no more restore logs are printed. The log file and coredump are as following:

[backup.tgz](https://github.com/milvus-io/milvus/files/12535084/backup.tgz)

3. milvus logs link:  https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,namespace%3D%5C%22qa-milvus%5C%22,pod%3D~%5C%22laion-test-3-milvus-.*%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%221693866004000%22,%22to%22:%221693879245000%22%7D%7D

### Expected Behavior

restore succ

### Milvus Log

4am pods:
```
laion-test-3-etcd-0                                               1/1     Running     9 (33h ago)    15d     10.104.14.95    4am-node18   <none>           <none>
laion-test-3-etcd-1                                               1/1     Running     3 (2d2h ago)   15d     10.104.12.76    4am-node17   <none>           <none>
laion-test-3-etcd-2                                               1/1     Running     0              15d     10.104.24.195   4am-node29   <none>           <none>
laion-test-3-milvus-datanode-85dfdc68d4-ldv9x                     1/1     Running     0              8d      10.104.15.155   4am-node20   <none>           <none>
laion-test-3-milvus-datanode-85dfdc68d4-xh5x4                     1/1     Running     0              8d      10.104.16.214   4am-node21   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-2hg4g                     1/1     Running     0              6d17h   10.104.20.123   4am-node22   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-5cpmn                     1/1     Running     0              6d17h   10.104.15.160   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-j5tgk                     1/1     Running     0              8d      10.104.15.156   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-pdw44                     1/1     Running     0              6d17h   10.104.16.220   4am-node21   <none>           <none>
laion-test-3-milvus-mixcoord-65b4c7b6d8-m5s28                     1/1     Running     0              8d      10.104.16.213   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-fjxxx                        1/1     Running     0              8d      10.104.16.218   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-l2sg6                        1/1     Running     0              8d      10.104.20.121   4am-node22   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-vtkbr                        1/1     Running     0              8d      10.104.15.159   4am-node20   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-2p7fg                    1/1     Running     0              7d      10.104.20.122   4am-node22   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-ccvdk                    1/1     Running     0              8d      10.104.15.157   4am-node20   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-hwvdb                    1/1     Running     0              8d      10.104.20.119   4am-node22   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-rlxs9                    1/1     Running     0              8d      10.104.16.217   4am-node21   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-tqdvt                    1/1     Running     0              7d      10.104.16.219   4am-node21   <none>           <none>
laion-test-3-minio-0                                              1/1     Running     0              15d     10.104.13.182   4am-node16   <none>           <none>
laion-test-3-minio-1                                              1/1     Running     0              15d     10.104.14.97    4am-node18   <none>           <none>
laion-test-3-minio-2                                              1/1     Running     0              15d     10.104.12.78    4am-node17   <none>           <none>
laion-test-3-minio-3                                              1/1     Running     0              15d     10.104.1.2      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-0                                      1/1     Running     0              15d     10.104.24.199   4am-node29   <none>           <none>
laion-test-3-pulsar-bookie-1                                      1/1     Running     0              15d     10.104.1.3      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-2                                      1/1     Running     0              15d     10.104.12.82    4am-node17   <none>           <none>
laion-test-3-pulsar-bookie-init-jkh2k                             0/1     Completed   0              15d     10.104.24.193   4am-node29   <none>           <none>
laion-test-3-pulsar-broker-0                                      1/1     Running     0              6d14h   10.104.9.148    4am-node14   <none>           <none>
laion-test-3-pulsar-proxy-0                                       1/1     Running     0              15d     10.104.13.180   4am-node16   <none>           <none>
laion-test-3-pulsar-pulsar-init-wr8kc                             0/1     Completed   0              15d     10.104.14.91    4am-node18   <none>           <none>
laion-test-3-pulsar-recovery-0                                    1/1     Running     0              15d     10.104.14.93    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-0                                   1/1     Running     8 (5d7h ago)   15d     10.104.14.98    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-1                                   1/1     Running     1 (13d ago)    15d     10.104.12.89    4am-node17   <none>           <none>
laion-test-3-pulsar-zookeeper-2                                   1/1     Running     3 (6d4h ago)   15d     10.104.13.185   4am-node16   <none>           <none>
```
