### ISSUE TITLE
[Bug]: [laion-1b] It takes 5 hours to restore 100m-768d data, which is a bit long

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230828-bc6b376c
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: milvus-backup 1.0-beta
```

### Current Behavior

1. milvus cluster resource
```
- proxy: 3 * 2c8g
- mixCoord: 1 * 2c8g
- dataNode: 2 * 2c8g
- indexNode: 4 * 16c64g
- queryNode: 5 * 16c128g 
```

2. milvus cluster config
```
  config:
    dataCoord:
      compaction:
        timeout: 2400
      segment:
        expansionRate: 1.15
        maxSize: 4096
        sealProportion: 0.08
    log:
      level: info
    rootCoord:
      dmlChannelNum: 16
```

3. insert 100m-768d data into the collection. It has 94 segments after compaction.
4. Spend 30min backup the collection
5. It takes 5 hours to restore 100m-768d the collection, which is a bit long. Hopefully it will take about 1~2 hours

- backup cmd: `./milvus-backup restore -n backup -s "_bak" --config backup.yaml`
- backup.yaml
```
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup_1.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: ****
  port: 8443
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: 10.....201 # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: * # accessKeyID of MinIO/S3
  secretAccessKey: * # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""

  bucketName: "laion-test-3" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "laion-test-3" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup1" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G
```

- backup info logs:
[backup.zip](https://github.com/milvus-io/milvus/files/12546954/backup.zip)

### Milvus Log

4am pods:
```
laion-test-3-etcd-0                                               1/1     Running       10 (15h ago)    16d     10.104.14.95    4am-node18   <none>           <none>
laion-test-3-etcd-1                                               1/1     Running       3 (3d1h ago)    16d     10.104.12.76    4am-node17   <none>           <none>
laion-test-3-etcd-2                                               1/1     Running       0               16d     10.104.24.195   4am-node29   <none>           <none>
laion-test-3-milvus-datanode-85dfdc68d4-ldv9x                     1/1     Running       0               9d      10.104.15.155   4am-node20   <none>           <none>
laion-test-3-milvus-datanode-85dfdc68d4-xh5x4                     1/1     Running       0               9d      10.104.16.214   4am-node21   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-2hg4g                     1/1     Running       0               7d17h   10.104.20.123   4am-node22   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-5cpmn                     1/1     Running       0               7d17h   10.104.15.160   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-j5tgk                     1/1     Running       0               9d      10.104.15.156   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-98d48bbbb-pdw44                     1/1     Running       0               7d17h   10.104.16.220   4am-node21   <none>           <none>
laion-test-3-milvus-mixcoord-65b4c7b6d8-m5s28                     1/1     Running       0               9d      10.104.16.213   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-fjxxx                        1/1     Running       0               9d      10.104.16.218   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-l2sg6                        1/1     Running       0               9d      10.104.20.121   4am-node22   <none>           <none>
laion-test-3-milvus-proxy-7445588f8d-vtkbr                        1/1     Running       0               9d      10.104.15.159   4am-node20   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-2p7fg                    1/1     Running       0               8d      10.104.20.122   4am-node22   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-ccvdk                    1/1     Running       0               9d      10.104.15.157   4am-node20   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-hwvdb                    1/1     Running       0               9d      10.104.20.119   4am-node22   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-rlxs9                    1/1     Running       0               9d      10.104.16.217   4am-node21   <none>           <none>
laion-test-3-milvus-querynode-575c4d9c57-tqdvt                    1/1     Running       0               8d      10.104.16.219   4am-node21   <none>           <none>
laion-test-3-minio-0                                              1/1     Running       0               16d     10.104.13.182   4am-node16   <none>           <none>
laion-test-3-minio-1                                              1/1     Running       0               16d     10.104.14.97    4am-node18   <none>           <none>
laion-test-3-minio-2                                              1/1     Running       0               16d     10.104.12.78    4am-node17   <none>           <none>
laion-test-3-minio-3                                              1/1     Running       0               16d     10.104.1.2      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-0                                      1/1     Running       0               16d     10.104.24.199   4am-node29   <none>           <none>
laion-test-3-pulsar-bookie-1                                      1/1     Running       0               16d     10.104.1.3      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-2                                      1/1     Running       0               16d     10.104.12.82    4am-node17   <none>           <none>
laion-test-3-pulsar-bookie-init-jkh2k                             0/1     Completed     0               16d     10.104.24.193   4am-node29   <none>           <none>
laion-test-3-pulsar-broker-0                                      1/1     Running       0               7d14h   10.104.9.148    4am-node14   <none>           <none>
laion-test-3-pulsar-proxy-0                                       1/1     Running       0               16d     10.104.13.180   4am-node16   <none>           <none>
laion-test-3-pulsar-pulsar-init-wr8kc                             0/1     Completed     0               16d     10.104.14.91    4am-node18   <none>           <none>
laion-test-3-pulsar-recovery-0                                    1/1     Running       0               16d     10.104.14.93    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-0                                   1/1     Running       8 (6d7h ago)    16d     10.104.14.98    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-1                                   1/1     Running       1 (14d ago)     16d     10.104.12.89    4am-node17   <none>           <none>
laion-test-3-pulsar-zookeeper-2                                   1/1     Running       3 (7d3h ago)    16d     10.104.13.185   4am-node16   <none>           <none>
```
