### ISSUE TITLE
[Bug]: GPU version not hitting GPU.

### ISSUE THREAD

**Issue by KirylKovaliov** [milvus-io/milvus#27377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.1-gpu
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): N/A   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): Ubuntu 22
- CPU/Memory: 4 CPU 16 RAM, EC2: g4dn.xlarge
- GPU: Tesla T4
- Others: 
NVIDIA-SMI 535.86.05
CUDA Version: 12.2 
  Index: GPU_IVF_FLAT
  metric_type: L2
  nlist:1024
  entities: ~1M

Docker Compose version v2.19.1
Docker version 24.0.6, build ed223bc

NVIDIA Container Runtime Hook version 1.14.1
commit: 6094effd58d88becdfb7900ef5df7fa274686620
```

### Current Behavior

I would like to test Milvus on GPU to compare performance and calculate costs. Using the docker-compose below I can achieve only CPU load and do not see any consumption on GPU. 

`nvtop` reports that no processes are loaded to the the memory and there are not consumption
`nvidia-smi -l 1` also shows nothing

Tue Sep 26 10:53:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P8              10W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

This is my docker-compose file
```
version: "3.9"

services:
  s3-storage:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - monio-data:/data
    networks:
      - milvus-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - milvus-network

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.1-gpu
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: s3-storage:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: milvus-bucket
      KNOWHERE_GPU_MEM_POOL_SIZE: 2048:4096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              device_ids: ["0"]
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - milvus-network
    depends_on:
      - "etcd"
      - "s3-storage"

    #### Monitoring
  attu:
    container_name: milvus-attu
    image: zilliz/attu:latest
    environment:
      MILVUS_URL: milvus:19530
    depends_on:
      - "milvus"
    networks:
      - milvus-network
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.4.22
    restart: always
    ports:
      - "27017:27017"
    networks:
      - milvus-network
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin --quiet | grep 1
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 20s

networks:
  milvus-network:
    driver: bridge

volumes:
  monio-data:
```

### Expected Behavior

I would like to see memory and GPU consumption in `nvtop`  or `nvidia-smi`
