### ISSUE TITLE
[Bug]: Milvus runs with SSE4_2 even I set the simd type to AVX when deploying

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#27872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231021-d2dbbbc1
deploy milvus with milvus operator
```

### Current Behavior

Milvus runs with SSE4_2 even I set the simd type to AVX when deploying
```
[2023/10/23 11:06:05.450 +00:00] [INFO] [segments/segment.go:883] ["updateFieldRawDataSize done"] [segmentID=445135989542424461]
I20231023 11:04:02.124192    72 knowhere_config.cc:78] [KNOWHERE][SetSimdType][milvus] FAISS expect simdType::SSE4_2
I20231023 11:04:02.124207    72 knowhere_config.cc:88] [KNOWHERE][SetSimdType][milvus] FAISS hook SSE4_2

```

### Expected Behavior

Milvus runs with avx when setting the simd type to avx
1. update the simd type to avx, and deploy milvus with milvus-operator
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  namespace: chaos-testing
  labels:
    app: milvus
spec:
  config:
    log:
      level: debug
    common:
      simdType: avx
  components: {}
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          metrics:
            podMonitor:
              enabled: true
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          metrics:
            podMonitor:
              enabled: true
  
```

### Steps To Reproduce

```markdown
as above
```

### Milvus Log

the test machine supports avx as shown below:
![img_v2_5a4f5941-44d0-4c0a-872d-671860d1285g](https://github.com/milvus-io/milvus/assets/82361606/2d3e467f-36bf-411c-8147-9248475a750d)

### Anything else?

if I set the yaml config to avx512, avx2, sse4-2, auto, it works as expected.
