### ISSUE TITLE
[Enhancement]: Milvus can trace more info for diagnostic

### ISSUE THREAD

**Issue by yiwen92** [milvus-io/milvus#28086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Use access log to trace more info from user request for Milvus:

1. Record the source of user requests, such as whether they come from an SDK, RESTful API, or web UI. For SDK requests, pls include the version information.

2. Record the key info of user requests, particularly the parameters used in search operations. This allows for better analysis and optimization of user query, such as search keywords and filtering criteria.

3. Record response for each request. Include details such as processing time, returned results for successful requests, and error codes and messages for failed requests. This helps with quick issue identification, resolution, performance analysis, and troubleshooting.

### Why is this needed?

By implementing these optimizations, Milvus server can obtain more detailed information in log/ access logs, enabling better analysis, monitoring, and improvement of the system.

### Anything else?

- This should be done in Proxy part
- Expect a more structured and accurate error message

**Comment by xiaofan-luan** [comment]
good suggestion.
Any volunteers?

**Comment by jiaoew1991** [comment]
/assign @aoiasd 

We already have some access logs, and we can update more detailed designs here.

**Comment by xiaofan-luan** [comment]
I think @SimFG  is wokring on a more detailed access log
contains all the user infomation, error information and parameters

**Comment by aoiasd** [comment]
New pr support that access log could create a new formatter and set it owner(method) by config yaml.
Could set proxy.accessLog.formatters.XXX to create a formatter,a string with some supported variable.
Such as：
```
proxy:
   accessLog:
        formatters:
            base: "test formatter $method_name"
            query: "query formatter $method_name $collection_name"
```

Could set owner of formetter by proxy.accessLog.formatterOwners.XXX.  All method use formatter "base" default.
Such as：
```
proxy:
  accessLog:
      formatterOwners:
          query: ["Query", "Search"]
```

Supported variable: "$method_name","$method_status","$trace_id","$user_addr","$user_name","$response_size""$error_code","$error_msg","$database_name","$collection_name","$partition_name","$time_cost","$time_now","$time_start","$time_end","$method_expr",
