### ISSUE TITLE
[Bug]: Load hang after flush failed and  upgrading image

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231117-d2f53aef
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2.post1.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone with image master-20231116-82915a96
2. run delete_query cases: (https://argo-workflows.zilliz.cc/archived-workflows/qa/2fad409c-0ac5-40c2-a71f-87dc4d0aa6b1?nodeId=test-delete-functional-6m-partitions-2)
   a. create collection fouram_vQ12SZ5s
   b. insert 2m-128d data into each partition, 6m in total for 3 partitions. The data in each partition are all the same.
   c. delete 3000 entities from _default partition
3. Concurrent insert_delete_flush and search, but flush failed (https://argo-workflows.zilliz.cc/archived-workflows/qa/b7429dbc-067d-4296-bc6b-91172883f21d?nodeId=test-delete-stable-3-fcd-fk9ts-2330860851)
   - insert_delete_flush: insert -> delete -> flush
   - search
```
   concurrent_tasks:
      -   
        type: search
        weight: 10
        params:
          nq: 100 
          top_k: 100 
          search_param:
            ef: 128 
          timeout: 6000
      -   
        type: scene_insert_delete_flush
        weight: 4
        params:
          insert_length: 2000
          delete_length: 1000
          random_id: true
          random_vector: true
```

4. Upgrade image to master-20231117-d2f53aef, load collection hang. (No response for more than 1.5h)
(https://argo-workflows.zilliz.cc/archived-workflows/qa/4d2d7bfd-a0b7-4bc4-901c-5189b00e0c23?nodeId=test-delete-stable-4-1334500042)

### Milvus Log

4am pods:
```
test-delete-1-etcd-0                                           1/1     Running     0               3d5h    10.104.18.145   4am-node25   <none>           <none>
test-delete-1-milvus-standalone-6887c96bc9-flhpk               1/1     Running     0               110m    10.104.18.97    4am-node25   <none>           <none>
test-delete-1-minio-b65bd5cd6-49xsc                            1/1     Running     0               3d5h    10.104.18.146   4am-node25   <none>           <none>
```

previous standalone pod: 
test-delete-1-milvus-standalone-57545b959-9jhbl
