### ISSUE TITLE
[Bug]: The distribution of queryable entities on querynodes is not row-based balanced

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.15
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection `fouram_XepQhvAI` and enable partition-key with 64 num_partitions -> create diskann index -> load
2. insert 50m-768d data -> flush
3. concurrent insert + delete + flush + search
```
    concurrent_tasks:
      - type: search
        weight: 3
        params:
          nq: 100 
          top_k: 100 
          random_data: true
          output_fields: ['int64_pk_5b']
          search_param:
            search_list: 100 
          timeout: 1200
      - type: flush
        weight: 1
        params:
          timeout: 1200
      - type: query
        weight: 2
        params:
         expr: 'id >= 50000000'
         timeout: 600 
      - type: delete
        weight: 1
        params:
          expr: null
          delete_length: 20
          timeout: 60
      - type: insert
        weight: 3
        params:
          nb: 100 
          timeout: 600 
          start_id: 0
          random_id: true
          random_vector: true
```
4.
But the queryable entity num distribution is not row-based balance.
![image](https://github.com/milvus-io/milvus/assets/27288593/7e44a1f5-4897-4afa-9c8f-cfcf0f944faa)

5. I tried to execute `explain-balance` by birdwatcher tool, gets error:
![image](https://github.com/milvus-io/milvus/assets/27288593/1420c00f-2b31-4562-8a12-cb230cd1bd5c)

6. The two delegators querynodes with half the entities but twice the memory usage of other querynode workers. Is it as expected? Can you help me check?
![image](https://github.com/milvus-io/milvus/assets/27288593/d486491a-966a-4092-bb0e-7321828323c8)

![image](https://github.com/milvus-io/milvus/assets/27288593/a28db649-7b6a-44db-addc-4f9361e722b7)

### Expected Behavior

- test argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/19581152-1e35-4a08-8b08-48d74b97663e?nodeId=yanliang-est-128cu-cron-nj

- grafana metrics: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=test-delete-cluster-2&var-collection=All&var-app_name=milvus&from=1700633401905&to=1700655360522
