### ISSUE TITLE
[Bug]: Can't search in concurrency with diskann

### ISSUE THREAD

**Issue by siwenyang** [milvus-io/milvus#28713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After insert data (3 million 256 dim), build diskann index and load with replica_num=2.
Perform 1162 search, 1 concurrency, avg search latency 31.62 ms
Perform 1162 search, 3 concurrency, avg search latency 95.2 ms

### Expected Behavior

3 concurrency search latency should be same as 1 concurrency search latency

### Steps To Reproduce

```markdown
1. Insert 3 million 256 dim data
2. Build diskann index
3. load index with replica_num=2
4. perform search
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13455515/milvus-log.tar.gz)

### Anything else?

Here is our customized milvus.yaml:

```
extraConfigFiles:
  user.yaml: |+
    queryCoord:
      loadTimeoutSeconds: 36000
    dataCoord:
      segment:
        diskSegmentMaxSize: 5120
    queryNode:
      scheduler:
        cpuRatio: 60
        maxReadConcurrentRatio: 20
rootCoordinator:
  nodeSelector:
    milvustype: "on"
  replicas: 1
  resources: 
    limits:
      cpu: 1
      memory: 2Gi
indexCoordinator:
  nodeSelector:
    milvustype: "on"
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
queryCoordinator:
  nodeSelector:
    milvustype: "on"
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
dataCoordinator:
  nodeSelector:
    milvustype: "on"
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
proxy:
  nodeSelector:
    milvustype: "on"
  replicas: 1
  resources: 
    limits:
      cpu: 1
      memory: 4Gi
queryNode:
  nodeSelector:
    milvustype: "qn"  
  replicas: 7
  resources: 
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 8
      memory: 32Gi
  sts:
    enabled: true
    persistence:
      storageClass:
      size: 60Gi
dataNode:
  nodeSelector:
    milvustype: "on"    
  replicas: 1
  resources: 
    limits:
      cpu: 2
      memory: 8Gi
indexNode:
  nodeSelector:
    milvustype: "in"
  replicas: 2
  resources: 
    limits:
      cpu: 32
      memory: 64Gi
etcd:
  nodeSelector:
    milvustype: "on"  
  autoCompactionMode: revision
  autoCompactionRetention: "1000"
  extraEnvVars:
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "4294967296"
  - name: ETCD_HEARTBEAT_INTERVAL
    value: "500"
  - name: ETCD_ELECTION_TIMEOUT
    value: "25000"
  - name: ETCD_SNAPSHOT_COUNT
    value: "10000"
  - name: ETCD_ENABLE_PPROF
    value: "true"
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 30Gi  #SSD Required
    storageClass:
  replicaCount: 3
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 4
      memory: 8Gi

pulsar:
  enabled: true
  proxy:
    nodeSelector:
      milvustype: "on"      
    resources:
      requests:
        memory: 9Gi
        cpu: 4
    replicaCount: 2
    configData:
      PULSAR_MEM: >
        -Xms4096M
        -Xmx4096M
        -XX:MaxDirectMemorySize=4096M
      httpNumThreads: "100"
  zookeeper:
    nodeSelector:
      milvustype: "on"
    volumes:
      persistence: true
      data:
        name: data
        size: 20Gi   #SSD Required
        storageClassName:
    resources:
      requests:
        memory: 4Gi
        cpu: 2
    configData:
      PULSAR_MEM: >
        -Xms2048M
        -Xmx2048M
  bookkeeper:
    nodeSelector:
      milvustype: "on"      
    volumes:
      journal:
        name: journal
        size: 60Gi
        storageClassName:
      ledgers:
        name: ledgers
        size: 150Gi  #SSD Required
        storageClassName:
    resources:
      requests:
        memory: 32Gi
        cpu: 4
    configData:
      PULSAR_MEM: >
        -Xms8192M
        -Xmx8192M
        -XX:MaxDirectMemorySize=16384M
  broker:
    nodeSelector:
      milvustype: "on"
    component: broker
    podMonitor:
      enabled: false
    replicaCount: 2
    resources:
      requests:
        memory: 36Gi
        cpu: 4
    configData:
      PULSAR_MEM: >
        -Xms8192M
        -Xmx8192M
        -XX:MaxDirectMemorySize=16384M
  
minio:
  nodeSelector:
    milvustype: "on"
  resources:
    limits:
      cpu: 4
      memory: 16Gi
  persistence:
    storageClass:
    accessMode: ReadWriteOnce
    size: 540Gi
```
