### ISSUE TITLE
[Bug]: Search failed context canceled when performing concurrent operations on partition-key collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231128-4bd426db-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2.post1.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection `fouram_jT1ce0Po` and enable partition_key with default num_partitions 64, 2 shards
2. hnsw index -> insert 10m-128d data -> flush -> index -> load
3. concurrent requests:
```
    concurrent_params:
      concurrent_number: 100 
      during_time: '3h'
      interval: 120 
    concurrent_tasks:
      -   
        type: search
        weight: 4
        params:
          nq: 100 
          top_k: 100 
          search_param:
            ef: 128 
          timeout: 600 
      -   
        type: flush
        weight: 1
        params:
          timeout: null
      -   
        type: insert
        weight: 2
        params:
          nb: 100 
          timeout: 600 
          start_id: 10000000
          random_id: true
          random_vector: true
      -   
        type: delete
        weight: 3
        params:
          delete_length: 50
          timeout: 600 
```
4. All pods is running but search failed context canceled
```
[2023-11-28 04:29:20,304 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=65535, message=failed to search/query delegator 3 for channel test-delete-key2-rootcoord-dml_0_445944811419861140v0: fail to Search, QueryNode ID=3, reason=worker(2) query failed: context canceled)>, <Time:{'RPC start': '2023-11-28 04:29:17.744315', 'RPC error': '2023-11-28 04:29:20.304017'}> (decorators.py:128)
```
5. There is another thong to focus on. The querynode memory usage peaked at 17GiB, and the number of growing and sealed  segments loaded by querynode is in the thousands, although the queryable datasize is within 7Gib. I'm not sure if the 17GiB memory usage is as expected.
![image](https://github.com/milvus-io/milvus/assets/27288593/f2aaae91-b6ba-4ced-9675-60238955e086)

![image](https://github.com/milvus-io/milvus/assets/27288593/89032827-d060-49a5-a5ed-be6eca59ad94)

![image](https://github.com/milvus-io/milvus/assets/27288593/385f540b-617c-4b5c-8c41-b60eb8d27ecf)

### Expected Behavior

1. all search succ
2. check the querynode memory usage

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/381aab7a-4a2e-44f4-a92c-a5c59a46aeae

grafana: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=test-delete-key2&var-collection=All&var-app_name=milvus&from=1701144003978&to=1701151812982
```

### Milvus Log

pods:
```
test-delete-key2-milvus-datanode-648b48f995-9s6vm                 1/1     Running            0                  134m    10.104.24.83    4am-node29   <none>           <none>
test-delete-key2-milvus-datanode-648b48f995-qj6q5                 1/1     Running            0                  134m    10.104.12.168   4am-node17   <none>           <none>
test-delete-key2-milvus-indexnode-54bcbc984c-zdnr7                1/1     Running            0                  134m    10.104.5.164    4am-node12   <none>           <none>
test-delete-key2-milvus-mixcoord-59f96d9d5d-hsfbq                 1/1     Running            0                  134m    10.104.24.84    4am-node29   <none>           <none>
test-delete-key2-milvus-proxy-548594966-7z8z7                     1/1     Running            0                  134m    10.104.24.85    4am-node29   <none>           <none>
test-delete-key2-milvus-querynode-6b876d866c-qcjgl                1/1     Running            0                  134m    10.104.1.161    4am-node10   <none>           <none>
test-delete-key2-milvus-querynode-6b876d866c-v8t48                1/1     Running            0                  134m    10.104.6.50     4am-node13   <none>           <none>
```
