### ISSUE TITLE
[Bug]:Files in minio not observed after uploading files with accesslog enabled

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#29169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231213-c2ce7bce
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server config: 
```
proxy:
  accessLog:
    enable: 'true'
    minioEnable: 'true'
    remotePath: /access_log/
    localPath: /tmp/milvus_accesslog
    maxSize: 16
    rotatedTime: 600
    filename: 'access.log'
    maxBackups: 2
```

After some testing, I would like to see the uploaded files that should be present in minio in addition to the local access log file

local file： 
![image](https://github.com/milvus-io/milvus/assets/48523564/98b113f9-851f-478c-bef6-e40e04206f91)

minio:
![image](https://github.com/milvus-io/milvus/assets/48523564/153fcebf-917a-4046-9580-2bb6cefa75b8)

### Expected Behavior

The corresponding accesslog should exist in minio. 

### Steps To Reproduce

```markdown
1. deploy milvus and turn on accesslog 
2. perform search and other operations on milvus
3. observe the access log file
```
