### ISSUE TITLE
[Bug]: [laion1b-test] querynode terminated due to a SIGSEV error

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.3-af54ce9-20231219
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. milvus with config
```
  config:
    dataCoord:
      compaction:
        rpcTimeout: 600 
      enableActiveStandby: true
      segment:
        expansionRate: 1.15
        maxSize: 4096
        sealProportion: 0.08
    dataNode:
      dataSync:
        maxParallelSyncTaskNum: 64
    log:
      level: debug
    minio:
      accessKeyID: xxx
      bucketName: xx
      secretAccessKey: xxx
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      dmlChannelNum: 16
      enableActiveStandby: true
```
2. concurrent search + query + insert_delete_flush -> querynode terminated with 139 error code
![image](https://github.com/milvus-io/milvus/assets/27288593/b0ed7f09-faca-47d5-9bfc-c009f14ccbaf)

![image](https://github.com/milvus-io/milvus/assets/27288593/30ceebf4-38bb-4a86-bb99-58881b8c7f73)

Loki log: https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,namespace%3D%5C%22qa-milvus%5C%22,pod%3D%5C%22laion1b-test-2-milvus-querynode-d9f5478d6-v84kc%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221703183663000%22,%22to%22:%221703183700000%22%7D%7D

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/workflows/qa/laion1b-test-cron-pr6vl?tab=workflow&nodeId=laion1b-test-cron-pr6vl&nodePanelView=inputs-outputs
```

### Milvus Log

[qn_v84kc.log](https://github.com/milvus-io/milvus/files/13747800/qn_v84kc.log)
