### ISSUE TITLE
[Bug]:  helm charts 部署 milvus 集群，怎么修改etcd 以及 minio 的pvc ？ 在最外层的values.yaml 中修改无效

### ISSUE THREAD

**Issue by maxgjt** [milvus-io/milvus#29491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

我在最外层的values.yaml 里面修改 持久化存储，但是都没有生效，需要到底层的values.yaml 中修改吗？怎么修改呢求助一下

**Comment by luckercs** [comment]
You can try modifying the following configuration in values. yml   @maxgjt 

```
minio:
  enabled: true
  persistence:
    enabled: true
    existingClaim: ""
    storageClass:
    accessMode: ReadWriteOnce
    size: 100Gi
etcd:
  persistence:
    enabled: true
    storageClass:
    accessMode: ReadWriteOnce
    size: 30Gi
```
