### ISSUE TITLE
[Bug]: The GC of the L0 segments is not triggered every hour as configured

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231225-13aa174b
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. milvus config
```
  config:
    dataCoord:
      enableActiveStandby: true
      segment:
        enableLevelZero: true
    dataNode: null
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    mixCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
2. default GC config
```
  gc:
    interval: 3600 # gc interval in seconds
    missingTolerance: 3600 # file meta missing tolerance duration in seconds, 3600
    dropTolerance: 10800 # file belongs to dropped entity tolerance duration in seconds. 10800
```
3. test: concurrent upsert + flush + search
4. As we can seen from the dataCoord.segment_num metrics, the number of Droppe-L0 segments has been increasing and does not trigger cleanup once an hour like Doppped-L1 segments.
https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=upgrade-level-zero-3&var-collection=All&var-app_name=milvus&from=1703558983649&to=1703576206271
![image](https://github.com/milvus-io/milvus/assets/27288593/e428f61c-fe7d-4bcd-a3cf-8beaf03ad3bf)

### Steps To Reproduce

```markdown
argo workflow name: fouramf-rolling-upgrade-all-cluster-2
```

### Milvus Log

pods:
```
upgrade-level-zero-3-milvus-datanode-5c7b669694-9d5rv             1/1     Running            0               5h21m   10.104.24.160   4am-node29   <none>           <none>
upgrade-level-zero-3-milvus-datanode-5c7b669694-rcll9             1/1     Running            0               5h21m   10.104.34.133   4am-node37   <none>           <none>
upgrade-level-zero-3-milvus-indexnode-7b8c8f6496-bfzh5            1/1     Running            0               5h25m   10.104.23.236   4am-node27   <none>           <none>
upgrade-level-zero-3-milvus-mixcoord-7f67c4bd69-qvkl4             1/1     Running            0               5h24m   10.104.6.241    4am-node13   <none>           <none>
upgrade-level-zero-3-milvus-proxy-59b79978c7-9fg7h                1/1     Running            0               5h19m   10.104.14.57    4am-node18   <none>           <none>
upgrade-level-zero-3-milvus-querynode-756ff5bd8d-c7t7c            1/1     Running            0               5h23m   10.104.23.243   4am-node27   <none>           <none>
upgrade-level-zero-3-milvus-querynode-756ff5bd8d-x2mq5            1/1     Running            0               5h23m   10.104.6.242    4am-node13   <none>           <none>
```
