### ISSUE TITLE
[Bug]: Search failed: code=503, message=failed to search: segment lacks[segment=xxx]: channel not available

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-a903ae64-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0rc15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create cluster with 3 querynodes
```
    proxy:
      resources:
        limits:
          cpu: "1" 
          memory: 8Gi 
      serviceType: ClusterIP
    queryNode:
      replicas: 3
      resources:
        limits:
          cpu: "8" 
          memory: 32Gi
        requests:
          cpu: "4" 
          memory: 8Gi
```
2. create collection `fouram_vMD3qwv6` -> hnsw index -> insert 9m-128d data -> flush -> index again -> load
3. concurrent search + upsert + flush + scene_search_test from 2024-01-09 05:26 to 2024-01-09 17:11 (All times mentioned are in UTC)
scene_search_test: create a collection -> build index -> load -> insert 5w-128d data -> flush -> index again -> load again -> search 20 times -> drop collection
```
    concurrent_params:
      concurrent_number: 100 
      during_time: '12h'
      interval: 120 
    concurrent_tasks:
      -   
        type: search
        weight: 3
        params:
          nq: 100 
          top_k: 100 
          search_param:
            ef: 128 
          timeout: 600 
      -   
        type: upsert
        weight: 3
        params:
          nb: 200 
          random_id: true
          random_vector: true
          start_id: 0
          timeout: 600 
      -   
        type: flush
        weight: 2
        params:
          timeout: 600 
      -   
        type: scene_search_test
        weight: 2
        params:
          dataset: local
          data_size: '5w'
          nb: 50000
          dim: 128 
          search_counts: 20
          prepare_before_insert: true
```
```
[2024-01-09 06:08:04,999 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: segment lacks[segment=446895675883223969]: channel not available[channel=delta-scene-3-rootcoord-dml_1_446895675880620209v1])>, <Time:{'RPC start': '2024-01-09 06:08:04.997872', 'RPC error': '2024-01-09 06:08:04.999922'}> (decorators.py:134)
[2024-01-09 06:08:05,000 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: segment lacks[segment=446895675883223969]: channel not available[channel=delta-scene-3-rootcoord-dml_1_446895675880620209v1])> (api_request.py:54)
[2024-01-09 06:08:05,000 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=503, message=failed to search: segment lacks[segment=446895675883223969]: channel not available[channel=delta-scene-3-rootcoord-dml_1_446895675880620209v1])> (func_check.py:48)
[2024-01-09 06:08:05,002 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: segment lacks[segment=446895675883223969]: channel not available[channel=delta-scene-3-rootcoord-dml_1_446895675880620209v1])>, <Time:{'RPC start': '2024-01-09 06:08:05.000601', 'RPC error': '2024-01-09 06:08:05.002622'}> (decorators.py:134)
[2024-01-09 06:08:05,002 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: segment lacks[segment=446895675883223969]: channel not available[channel=delta-scene-3-rootcoord-dml_1_446895675880620209v1])> (api_request.py:54)
```

4. At around 13:47, querynode `delta-scene-3-milvus-querynode-5bcbbf6fd-sk5vw` terminated with completed reason
[qn_sk5vw.log](https://github.com/milvus-io/milvus/files/13884381/qn_sk5vw.log)

5. At around 13:51, proxy `delta-scene-3-milvus-proxy-695596c785-p5p2c` oomkilled for the first time, oom four times in total
6. At around 16:06, querynode `delta-scene-3-milvus-querynode-5bcbbf6fd-fmdkj` terminated with error reason and 143 exitcode
[qn_fmdkj.log](https://github.com/milvus-io/milvus/files/13884391/qn_fmdkj.log)

### Expected Behavior

1. before pod terminated, all requests succ
2. why the querynode terminated with error or completed reason ?

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/87bfac48-63d6-44e4-8ed8-09696b43d4b7?nodeId=delta-stable-scene-3-1021912765
```

### Milvus Log

4am pods:
```
delta-scene-3-etcd-0                                              1/1     Running     0               27h     10.104.29.51    4am-node35   <none>           <none>
delta-scene-3-etcd-1                                              1/1     Running     0               27h     10.104.32.110   4am-node39   <none>           <none>
delta-scene-3-etcd-2                                              1/1     Running     0               27h     10.104.25.78    4am-node30   <none>           <none>
delta-scene-3-milvus-datanode-6df8884dcd-9ct9d                    1/1     Running     0               27h     10.104.28.69    4am-node33   <none>           <none>
delta-scene-3-milvus-datanode-6df8884dcd-zc5cw                    1/1     Running     0               27h     10.104.20.33    4am-node22   <none>           <none>
delta-scene-3-milvus-indexnode-54b75f56f7-65jkk                   1/1     Running     0               27h     10.104.16.78    4am-node21   <none>           <none>
delta-scene-3-milvus-indexnode-54b75f56f7-7w6cd                   1/1     Running     0               27h     10.104.20.34    4am-node22   <none>           <none>
delta-scene-3-milvus-mixcoord-77c89dc6c7-p9zq9                    1/1     Running     0               27h     10.104.28.71    4am-node33   <none>           <none>
delta-scene-3-milvus-proxy-695596c785-p5p2c                       1/1     Running     4 (15h ago)     27h     10.104.28.70    4am-node33   <none>           <none>
delta-scene-3-milvus-querynode-5bcbbf6fd-fmdkj                    1/1     Running     1 (15h ago)     27h     10.104.14.123   4am-node18   <none>           <none>
delta-scene-3-milvus-querynode-5bcbbf6fd-k2tnl                    1/1     Running     0               27h     10.104.4.131    4am-node11   <none>           <none>
delta-scene-3-milvus-querynode-5bcbbf6fd-sk5vw                    1/1     Running     1 (17h ago)     27h     10.104.20.37    4am-node22   <none>           <none>
delta-scene-3-minio-0                                             1/1     Running     0               27h     10.104.28.57    4am-node33   <none>           <none>
delta-scene-3-minio-1                                             1/1     Running     0               27h     10.104.20.21    4am-node22   <none>           <none>
delta-scene-3-minio-2                                             1/1     Running     0               27h     10.104.25.77    4am-node30   <none>           <none>
delta-scene-3-minio-3                                             1/1     Running     0               27h     10.104.32.109   4am-node39   <none>           <none>
delta-scene-3-pulsar-bookie-0                                     1/1     Running     0               27h     10.104.30.71    4am-node38   <none>           <none>
delta-scene-3-pulsar-bookie-1                                     1/1     Running     0               27h     10.104.17.2     4am-node23   <none>           <none>
delta-scene-3-pulsar-bookie-2                                     1/1     Running     0               27h     10.104.27.188   4am-node31   <none>           <none>
delta-scene-3-pulsar-bookie-init-4zkzw                            0/1     Completed   0               27h     10.104.9.49     4am-node14   <none>           <none>
delta-scene-3-pulsar-broker-0                                     1/1     Running     0               27h     10.104.9.50     4am-node14   <none>           <none>
delta-scene-3-pulsar-proxy-0                                      1/1     Running     0               27h     10.104.1.200    4am-node10   <none>           <none>
delta-scene-3-pulsar-pulsar-init-967lr                            0/1     Completed   0               27h     10.104.1.198    4am-node10   <none>           <none>
delta-scene-3-pulsar-recovery-0                                   1/1     Running     0               27h     10.104.1.199    4am-node10   <none>           <none>
delta-scene-3-pulsar-zookeeper-0                                  1/1     Running     0               27h     10.104.25.79    4am-node30   <none>           <none>
delta-scene-3-pulsar-zookeeper-1                                  1/1     Running     0               27h     10.104.28.59    4am-node33   <none>           <none>
delta-scene-3-pulsar-zookeeper-2                                  1/1     Running     0               27h     10.104.19.227   4am-node28   <none>           <none>
```

### Anything else?

[grafana metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=delta-scene-3&var-collection=All&var-app_name=milvus&from=1704777000000&to=1704841800000)
