### ISSUE TITLE
[Feature]: Add metric for rate limited rpc requests

### ISSUE THREAD

**Issue by LoveEachDay** [milvus-io/milvus#30052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus has added the quota and limits for important rpc requests. And the sdk will automatically retry if received a ratelimit response, which will increase the rpc latency. We'd like to add a metric to show when the ratelimit has been activitated and which rule has been hit.

### Describe the solution you'd like.

We'd like to add a counter for the ratelimited rpc requests, with the label to the `hit rule`. For example, when we set up the following configs:
```
quotaAndLimits
  ddl:
    enabled: true
    partitionRate: 1 # qps, default no limit, rate for CreatePartition, DropPartition, LoadPartition, ReleasePartition
```
When we create partitions for a collection and exceed the this 1/s limit and we'd like the add the 1 to the ratelimit failed rpc counter, like this `milvus_proxy_ratelimited_failed{label='partitionRate'} 1`.
