### ISSUE TITLE
[Bug]: Milvus standalone container stopped by time

### ISSUE THREAD

**Issue by tufailkhan45** [milvus-io/milvus#30434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

Milvus container is stopping after some time. Initially, I supposed that it occurred due to storage size as Milvus was continuously creating logs and it was causing container storage issues. So I stopped the logs by adding `stdout: "false"` in the following:
```
etcd
log
grpc
```

The logs issue was fixed by doing this but the container still stopping by the time.
Here's my docker yml for standalone:
```
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.5
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus-logs:/tmp/milvus/logs
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml.milvus-standalone:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

```
