### ISSUE TITLE
[Enhancement]: Update the memory protection water level down to 90%

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#30493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Update the water level of memProtection down as below:
```
quotaAndLimits    
  memProtection:
      enabled: true
      dataNodeMemoryLowWaterLevel: 0.85  -> 0.8
      dataNodeMemoryHighWaterLevel: 0.95  -> 0.9
      queryNodeMemoryLowWaterLevel: 0.85  -> 0.8
      queryNodeMemoryHighWaterLevel: 0.95  -> 0.9
```

### Why is this needed?

currently the high water level of memory protection is 95%, which is too high for standalone deployment, especially for those with limited resource, to protect Milvus service from OOM.
