### ISSUE TITLE
[Bug]: Fail to Search: reason=distribution is no servcieable: channel not available

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.3-ef086dc-20240222
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6rc3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. collection `laion_stable_4` has about 60m-768d data and it's schema is:
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 768}}, {'name': 'int64_pk_5b', 'description': '', 'type': <DataType.INT64: 5>, 'is_partition_key': True}, {'name': 'varchar_caption', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'varchar_NSFW', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'float64_similarity', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'int64_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'varchar_md5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}], 'enable_dynamic_field': True}
```
2. reload collection and concurrent requests: insert + delete + flush + search
```
    concurrent_params:
      concurrent_number: 50
      during_time: '10h'
      interval: 120 
    concurrent_tasks:
      -   
        type: query
        weight: 9
        params:
          #output_fields: ['float_vector']
          expr: "50000000 < id < 5010000"
          timeout: 1200
      -   
        type: search
        weight: 50
        params:
          nq: 10
          top_k: 100 
          #output_fields: ["float32_vector"]
          random_data: true
          search_param:
            ef: 100 
          timeout: 600 
      -   
        type: insert
        weight: 20
        params:
          nb: 200 
          start_id: 63000000
          random_id: true
          random_vector: true
          timeout: 600 
      -   
        type: delete
        weight: 20
        params:
          delete_length: 100 
          timeout: 600 
      -   
        type: flush
        weight: 1
        params:
          timeout: 600 
```
3. many search/query failed:
```
[2024-02-23 08:19:15,986 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=65535, message=failed to search/query delegator 1652 for channel laion1b-test-2-rootcoord-dml_5_447902879639453431v1: fail to Search, QueryNode ID=1652
, reason=distribution is not servcieable: channel not available[channel=laion1b-test-2-rootcoord-dml_5_447902879639453431v1])>, <Time:{'RPC start': '2024-02-23 08:17:52.318713', 'RPC error': '2024-02-23 08:19:15.986667'}> (decorators.py:134
)
[2024-02-23 08:19:15,989 - ERROR - fouram]: (api_response) : [Collection.search] <MilvusException: (code=65535, message=failed to search/query delegator 1652 for channel laion1b-test-2-rootcoord-dml_5_447902879639453431v1: fail to Search, Q
ueryNode ID=1652, reason=distribution is not servcieable: channel not available[channel=laion1b-test-2-rootcoord-dml_5_447902879639453431v1])>, [requestId: 09fad0ee-d224-11ee-82c2-825c0a4c1e06] (api_request.py:57)
[2024-02-23 08:19:15,989 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=65535, message=failed to search/query delegator 1652 for channel laion1b-test-2-rootcoord-dml_5_447902879639453431v1: fail
 to Search, QueryNode ID=1652, reason=distribution is not servcieable: channel not available[channel=laion1b-test-2-rootcoord-dml_5_447902879639453431v1])> (func_check.py:48)
[2024-02-23 08:19:15,995 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=65535, message=failed to search/query delegator 1652 for channel laion1b-test-2-rootcoord-dml_5_447902879639453431v1: fail to Search, QueryNode ID=1652
, reason=distribution is not servcieable: channel not available[channel=laion1b-test-2-rootcoord-dml_5_447902879639453431v1])>, <Time:{'RPC start': '2024-02-23 08:17:52.268824', 'RPC error': '2024-02-23 08:19:15.995875'}> (decorators.py:134
)
```

### Milvus Log

- argo workflow name: laion1b-test-cron-flush  https://argo-workflows.zilliz.cc/workflows/qa/laion1b-test-cron-flush?tab=workflow&nodeId=laion1b-test-cron-flush&nodePanelView=summary
- pods:
```
laion1b-test-2-etcd-0                                             1/1     Running       1 (42d ago)     70d     10.104.25.31    4am-node30   <none>           <none>
laion1b-test-2-etcd-1                                             1/1     Running       0               70d     10.104.30.94    4am-node38   <none>           <none>
laion1b-test-2-etcd-2                                             1/1     Running       0               70d     10.104.34.225   4am-node37   <none>           <none>
laion1b-test-2-milvus-datanode-648fd8c79c-6c5sl                   1/1     Running       0               19h     10.104.9.228    4am-node14   <none>           <none>
laion1b-test-2-milvus-datanode-648fd8c79c-psk8h                   1/1     Running       0               19h     10.104.15.115   4am-node20   <none>           <none>
laion1b-test-2-milvus-indexnode-fffb75cd7-8c7mt                   1/1     Running       0               18h     10.104.17.173   4am-node23   <none>           <none>
laion1b-test-2-milvus-indexnode-fffb75cd7-9ssh7                   1/1     Running       0               18h     10.104.26.104   4am-node32   <none>           <none>
laion1b-test-2-milvus-indexnode-fffb75cd7-lmnnc                   1/1     Running       0               18h     10.104.5.134    4am-node12   <none>           <none>
laion1b-test-2-milvus-indexnode-fffb75cd7-pb6nt                   1/1     Running       0               18h     10.104.9.230    4am-node14   <none>           <none>
laion1b-test-2-milvus-indexnode-fffb75cd7-x8gdm                   1/1     Running       0               18h     10.104.29.169   4am-node35   <none>           <none>
laion1b-test-2-milvus-mixcoord-676bd65bcf-vqlkf                   1/1     Running       0               19h     10.104.18.76    4am-node25   <none>           <none>
laion1b-test-2-milvus-proxy-db5b89665-j9xsr                       1/1     Running       0               19h     10.104.27.159   4am-node31   <none>           <none>
laion1b-test-2-milvus-querynode-1-5956458d77-4bntq                1/1     Running       0               18h     10.104.32.44    4am-node39   <none>           <none>
laion1b-test-2-milvus-querynode-1-5956458d77-bt7dt                1/1     Running       0               18h     10.104.28.226   4am-node33   <none>           <none>
laion1b-test-2-milvus-querynode-1-5956458d77-jpf7x                1/1     Running       0               18h     10.104.17.175   4am-node23   <none>           <none>
laion1b-test-2-milvus-querynode-1-5956458d77-qw8s6                1/1     Running       0               18h     10.104.33.242   4am-node36   <none>           <none>
laion1b-test-2-pulsar-bookie-0                                    1/1     Running       0               70d     10.104.33.107   4am-node36   <none>           <none>
laion1b-test-2-pulsar-bookie-1                                    1/1     Running       0               46d     10.104.18.240   4am-node25   <none>           <none>
laion1b-test-2-pulsar-bookie-2                                    1/1     Running       0               70d     10.104.25.32    4am-node30   <none>           <none>
laion1b-test-2-pulsar-broker-0                                    1/1     Running       0               64d     10.104.1.69     4am-node10   <none>           <none>
laion1b-test-2-pulsar-proxy-0                                     1/1     Running       0               70d     10.104.4.218    4am-node11   <none>           <none>
laion1b-test-2-pulsar-recovery-0                                  1/1     Running       0               70d     10.104.14.151   4am-node18   <none>           <none>
laion1b-test-2-pulsar-zookeeper-0                                 1/1     Running       0               70d     10.104.29.87    4am-node35   <none>           <none>
laion1b-test-2-pulsar-zookeeper-1                                 1/1     Running       0               70d     10.104.21.124   4am-node24   <none>           <none>
laion1b-test-2-pulsar-zookeeper-2                                 1/1     Running       0               70d     10.104.34.229   4am-node37   <none>           <none>
```
