### ISSUE TITLE
[Bug]: Kafka Consumer - Decompression (codec 0x1) of message at N of M bytes failed. "Local: Not implemented"

### ISSUE THREAD

**Issue by aptmess** [milvus-io/milvus#31047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.8-gpu, 2.3.10-gpu
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 50 / 800
- GPU: 3
- Others:
```

### Current Behavior

good day!

when I am trying to insert data to Milvus in `DataNode` where is exception with my `ExternalKafka`:

```
[kafka/kafka_consumer.go:138] 
["consume msg failed"] 
[topic=image-search] 
[groupID=datanode-17-image-search_448173793396654839v0-true] 
[error="Decompression (codec 0x1) of message at 1284334 of 256 bytes failed: Local: Not implemented"]
```

externalKafka settings: (config.yaml)

```
common:
  preCreatedTopic:
    enabled: true
    names: ['image-search']
  kafka:
    brokerList: <>
    securityProtocol: SASL_PLAINTEXT
    saslUsername: <>
    saslPassword: <>
    saslMechanisms: SCRAM-SHA-256
    readTimeout: 10
  mq:
    type: kafka
```

are there any ideas how to fix this?

### Expected Behavior

no decompression error message

### Steps To Reproduce

```markdown
Deployment on cluster with helm chart, local Etcd, external Kafka.
```

### Milvus Log

[kafka/kafka_consumer.go:138] 
["consume msg failed"] 
[topic=image-search] 
[groupID=datanode-17-image-search_448173793396654839v0-true] 
[error="Decompression (codec 0x1) of message at 1284334 of 256 bytes failed: Local: Not implemented"]
