### ISSUE TITLE
[Mishards] Failed to search vectors across partitions

### ISSUE THREAD

**Issue by unilj** [milvus-io/milvus#3133]
**Describe the bug**

I have inserted a list of vectors into different partitions through Mishards. (Flush and wait for a reasonable amount of time to make sure the vectors are inserted.)
Since I am using FLAT index, I expect that searching for exactly the same vectors should return vectors with very high similarities, if not exactly the same. But it didn't.

> This always happens when I create a lot of partitions. 
> This sometimes happens when I create 2 partitions.

**Steps/Code to reproduce behavior**

1. Clone the project
2. cd into [`shards/all_in_one`](https://github.com/milvus-io/milvus/tree/master/shards/all_in_one)
3. Modifies the `all_in_one.yml` to use CPU version, see the config below
3. run `docker-compose -f all_in_one.yml up -d` to start Mishards
4. Unzip [sample_v2.zip](https://github.com/milvus-io/milvus/files/5026634/sample_v2.zip) to get a `sample_v2.json` file
5. Use the following code and the above data to reproduce the behaviour (This can be reproduced on my laptop and a remote server)

```python
import json
import time
from milvus import Milvus, MetricType
    
client = Milvus("127.0.0.1", 19531)

collection_name = "debug_v1"

# drop the collection if it exists
status, has_collection = client.has_collection(collection_name)
if has_collection:
    status = client.drop_collection(collection_name)
    assert status.OK()
    time.sleep(1)

# create the collection
collection_param = {
    "collection_name": collection_name, 
    "dimension": 100, 
    "index_file_size": 1024, 
    "metric_type": MetricType.IP,
}
status = client.create_collection(collection_param)
assert status.OK()  # make sure the collection is created
print(f"Collection {collection_name} created.")

# load vectors from file and insert into different partitions
all_vector_ids = []
with open("sample_v2.json", "r") as fin:
    for line in fin:
        json_dict = json.loads(line)
        partition_tag = json_dict["partition_tag"]
        vectors = json_dict["vectors"]
        client.create_partition(collection_name, partition_tag)
        status, ids = client.insert(collection_name, records=vectors, partition_tag=partition_tag)
        status = client.flush([collection_name])
        assert status.OK()
        all_vector_ids.extend(ids)

print(f"{len(all_vector_ids)} vectors inserted.")

status, existing_partitions = client.list_partitions(collection_name)
print(f"{len(existing_partitions)} existing partitions.")

print("Will sleep for 5 seconds.")
time.sleep(5)
status, count = client.count_entities(collection_name)
print(f"There are {count} entities in the collection.")

# retrieve inserted vectors with their ids
status, inserted_vectors = client.get_entity_by_id(collection_name, ids=all_vector_ids)
print(f"Retrieved {len(inserted_vectors)} vectors.")

# search for the retrieved vectors
status, results = client.search(collection_name, query_records=inserted_vectors, top_k=1)

# We expect that all the distances are >=0.99, since we are using FLAT index (i.e. brute force searching)
# But the returned results contain a lot vectors with distance far less than 0.99
print(results)
```

**Expected behavior**
For the final `print(results)`, I expect the returned results should at least have similarities 0.99.

**Environment details**

The `all_in_one.yml` config is attached below:
```yaml
version: "2.3"
services:
    milvus_wr:
        #runtime: nvidia
        restart: always
        image: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
        ports:
            - "0.0.0.0:19540:19530"
        volumes:
            - /home/i/envs/mishards/db:/var/lib/milvus/db
            - ./wr_server.yml:/opt/milvus/conf/server_config.yaml

    milvus_ro:
        #runtime: nvidia
        restart: always
        image: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
        ports:
            - "0.0.0.0:19541:19530"
        volumes:
            - /home/i/envs/mishards/db:/var/lib/milvus/db
            - ./ro_server.yml:/opt/milvus/conf/server_config.yaml

    jaeger:
        restart: always
        image: jaegertracing/all-in-one:1.14
        ports:
            - "0.0.0.0:5775:5775/udp"
            - "0.0.0.0:16686:16686"
            - "0.0.0.0:9441:9441"
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411

    mishards:
        restart: always
        image: milvusdb/mishards
        ports:
            - "0.0.0.0:19531:19531"
            - "0.0.0.0:19532:19532"
        volumes:
            - /home/i/envs/mishards/db:/tmp/milvus/db
            # - /tmp/mishards_env:/source/mishards/.env
        command: ["python", "mishards/main.py"]
        environment:
            FROM_EXAMPLE: 'true'
            DEBUG: 'true'
            SERVER_PORT: 19531
            WOSERVER: tcp://milvus_wr:19530
            DISCOVERY_PLUGIN_PATH: static
            DISCOVERY_STATIC_HOSTS: milvus_wr,milvus_ro
            TRACER_CLASS_NAME: jaeger
            TRACING_SERVICE_NAME: mishards-demo
            TRACING_REPORTING_HOST: jaeger
            TRACING_REPORTING_PORT: 5775

        depends_on:
            - milvus_wr
            - milvus_ro
            - jaeger
```

**Additional context**
Logs for `all_in_one_mishards_1` is quite normal, except for these lines:
```
2020-08-05 06:34:47,578 | DEBUG: [172.18.0.3:19530] file id: 376.  pre update time 0 is small than 1596609280467947 (file_based_hash_ring_router.py:28) (ThreadPoolExecutor-0_41)
```
