### ISSUE TITLE
[Bug]: ExternalETCD - user name is empty error (authentication)

### ISSUE THREAD

**Issue by aptmess** [milvus-io/milvus#31631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.12-gpu
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.10
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 40 / 1024
- GPU: 3
- Others:
```

### Current Behavior

Good day!

I am trying to deploy milvus-on-cluster with external components and the latest problem is ETCD. I got the error (the same as in this [issue](https://github.com/milvus-io/milvus/issues/28895)) while milvus is trying to connect:

```
{"level":"warn",
"ts":"2024-03-26T16:31:03.204Z",
"logger":"etcd-client",
"caller":"v3@v3.5.5/retry_interceptor.go:62",
"msg":"retrying of unary invoker failed",
"target":"etcd-endpoints://<host>:2379",
"attempt":0,
"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
```

I used all configurations in user.yaml - change `authorizationEnabled` true/false, `rbac.enabled` true/false:

```
    common:
      security:
        authorizationEnabled: true
    etcd:
      endpoints:
        - http://<host>:2379
      auth:
        rbac:
          enabled: true
        enable: true
        userName: user
        password: pass
```

How can I connect to external etcd and solve this problem? Thank you

### Expected Behavior

Milvus can connect to External ETCD with authorization.

### Steps To Reproduce

```markdown
Deployment with milvus-on-cluster with `externalEtcd.enabled=true`
```

### Milvus Log

```
{"level":"warn","ts":"2024-03-26T16:31:03.204Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://<host>:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
```
