### ISSUE TITLE
[Bug]: [benchmark] Continuous concurrent upsert and count(*) testing milvus OOM

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#31705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240327-d37e1fdd-amd64 
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0rc19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After inserting 2 million vectors and a string scalar, the string column is the partition key. Concurrency is 5, with continuous concurrent upserts and count(*). Each time you upsert 2000 pieces of data, milvus oom and restart.

argo task : upsert-count-5d5dk
client pod: upsert-count-5d5dk-99120586 (qa ns)

test env: 4am cluster, qa-milvus ns
```
upsert-count-5d5dk-1-41-1560-etcd-0                               1/1     Running                           0                125m    10.104.21.35    4am-node24   <none>           <none>
upsert-count-5d5dk-1-41-1560-milvus-standalone-6f47687599-smpwm   0/1     CrashLoopBackOff                  15 (3m10s ago)   125m    10.104.30.8     4am-node38   <none>           <none>
upsert-count-5d5dk-1-41-1560-minio-78d5bffc84-p59g8               1/1     Running                           0                125m    10.104.34.102   4am-node37   <none>           <none>
```
![image](https://github.com/milvus-io/milvus/assets/48523564/be01c76a-0221-4304-a8aa-763ca131a03a)

resource: 8c16g 
![image](https://github.com/milvus-io/milvus/assets/48523564/1f1320fe-fb94-46ae-afb7-ece331472f1e)

### Steps To Reproduce

```markdown
1. Deployment of milvus
2. Create index, load after inserting 2 million data
3. concurrent upsert and count(*)
```

**Comment by xiaofan-luan** [comment]
I think this might be as expected. you need enough memory buffer before compaction done.
But we quota limitation is not working as expected?

**Comment by xiaofan-luan** [comment]
Another thing is how we can improve compaction throughput to catch up intense write/delete workload.
We kind like to rethink the compaction policy and compction implementation

**Comment by yanliang567** [comment]
I think a 8c16g standalone pod shall be able to hold 2m_128d entities with 5-concurrents upsert requests without OOM.

> I think this might be as expected. you need enough memory buffer before compaction done. But we quota limitation is not working as expected?

**Comment by xiaofan-luan** [comment]
> I think a 8c16g standalone pod shall be able to hold 2m_128d entities with 5-concurrents upsert requests without OOM.
> 
> > I think this might be as expected. you need enough memory buffer before compaction done. But we quota limitation is not working as expected?

based on how fast compaction can work

**Comment by bigsheeper** [comment]
> I think this might be as expected. you need enough memory buffer before compaction done. But we quota limitation is not working as expected?

I believe this is because the memory growth is too rapid, and the quota center takes several seconds to provide feedback to the proxy interceptor.
On the other hand, the memory growth may also be attributed to datanode/querynode consuming the remaining messages in the message queue (MQ), further exacerbating the situation.

**Comment by xiaofan-luan** [comment]
> > I think this might be as expected. you need enough memory buffer before compaction done. But we quota limitation is not working as expected?
> 
> I believe this is because the memory growth is too rapid, and the quota center takes several seconds to provide feedback to the proxy interceptor. On the other hand, the memory growth may also be attributed to datanode/querynode consuming the remaining messages in the message queue (MQ), further exacerbating the situation.

We may want to add insertion throughput limit earlier? could that be an option?

for example 0%-60% - not limit
60-70 -   20MB/s
70 - 80 - 10MB/s
80 - 90 - 5MB/s
90 + - No limit allowed

**Comment by bigsheeper** [comment]
@elstic Maybe you can try to set `quotaAndLimits.dml.upsertRate.max` to `0.5` (means 0.5MB/s), and also accelerate the quota center check frequency by setting `quotaAndLimits.quotaCenterCollectInterval` from `3(s)` to `1(s)`

**Comment by elstic** [comment]
> @elstic Maybe you can try to set `quotaAndLimits.dml.upsertRate.max` to `0.5` (means 0.5MB/s), and also accelerate the quota center check frequency by setting `quotaAndLimits.quotaCenterCollectInterval` from `3(s)` to `1(s)`

milvus still crashes, here are the test details
```
upsert-count-zpm8n-1-4-6358-etcd-0                                1/1     Running                           0                  32m     10.104.26.166   4am-node32   <none>           <none>
upsert-count-zpm8n-1-4-6358-milvus-standalone-66f9f44c65-f69ls    0/1     CrashLoopBackOff                  5 (59s ago)        32m     10.104.33.104   4am-node36   <none>           <none>
upsert-count-zpm8n-1-4-6358-minio-5f9cf686db-dmb7s                1/1     Running                           0                  32m     10.104.33.103   4am-node36   <none>           <none>
```

I changed the quota parameter as you provided.

```
  quotaAndLimits:
    dml:
      upsertRate:
        max: 0.5
    quotaCenterCollectInterval: 1
```

milvus  resources:
```
  standalone:
    resources:
      limits:
        cpu: 8
        memory: 16Gi
      requests:
        cpu: 8
        memory: 16Gi
```

 client parameters:
```
    dataset_params:
      dataset_name: sift
      dim: 128
      dataset_size: 2m
      ni_per: 5000
      metric_type: L2
      scalars_params:
        varchar_1:
          params:
            is_partition_key: true
            max_length: 100
    collection_params:
      other_fields:
        - varchar_1
      shards_num: 2
      num_partitions: 16
    load_params: {}
    release_params: {}
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    query_params: {}
    search_params: {}
    resource_groups_params:
      reset: false
    database_user_params:
      reset_rbac: false
      reset_db: false
    concurrent_params:
      concurrent_number:
        - 1
      during_time: 3h
      interval: 20
    concurrent_tasks:
      - type: query
        weight: 1
        params:
          expr: ''
          output_fields:
            - count(*)
      - type: upsert
        weight: 1
        params:
          nb: 2000
          random_id: false
          start_id: 1
```
It means to insert 2 million 128d vectors and str columns of length 100. Continuous serial count(*) and upsert (concurrency reduced to 1), upserting 2000 pieces of data at a time.

resource grafana:
![image](https://github.com/milvus-io/milvus/assets/48523564/c039c15f-3ab5-48ec-b03e-dec1eaa6b002)

**Comment by xiaofan-luan** [comment]
@elstic 
Is this related to count?

**Comment by elstic** [comment]
> @elstic Is this related to count?

I think it's irrelevant, the count operation is just added to verify if upsert causes the amount of data to increase or decrease. 
I will start another test with only upsert operations to verify my opinion.

**Comment by elstic** [comment]
> > @elstic Is this related to count?
> 
> I think it's irrelevant, the count operation is just added to verify if upsert causes the amount of data to increase or decrease. I will start another test with only upsert operations to verify my opinion.

crash from upsert only. 
```
upsert-count-wbvb7-1-7-2291-etcd-0                                1/1     Running                           0                 36m     10.104.16.188   4am-node21   <none>           <none>
upsert-count-wbvb7-1-7-2291-milvus-standalone-578cdc9c59-tbsx4    0/1     CrashLoopBackOff                  6 (2m10s ago)     36m     10.104.27.228   4am-node31   <none>           <none>
upsert-count-wbvb7-1-7-2291-minio-84b8454844-kcmmc                1/1     Running                           0                 36m     10.104.30.6     4am-node38   <none>           <none>
```

**Comment by elstic** [comment]
> @elstic Has the `quotaAndLimits.dml.enabled` been configured to `true`?

No modification, default value

**Comment by bigsheeper** [comment]
> > @elstic Has the `quotaAndLimits.dml.enabled` been configured to `true`?
> 
> No modification, default value. Do I need to set it to true and then run it? Are there any other configurations that need to be changed?

Nope, I'll shard you a user document about quota and limits.

**Comment by elstic** [comment]
When I set `quotaAndLimits.dml.enabled` to `true` , continually upsert , the memory of milvus does not grow rapidly.
```
quotaAndLimits:
  dml:
    enabled: true
    upsertRate:
      max: 0.5
  quotaCenterCollectInterval: 1
```

![image](https://github.com/milvus-io/milvus/assets/48523564/d141c292-1e10-48c4-a9bd-9d2af878ac2f)

**Comment by xiaofan-luan** [comment]
> `quotaAndLimits.dml.enabled`

So this is the back pressure of memory works?

**Comment by bigsheeper** [comment]
> > `quotaAndLimits.dml.enabled`
> 
> So this is the back pressure of memory works?

The memory did not reach the memory low watermark, so it's just rate limiting. To observe the backpressure effect, we need to continue upserting for a longer period.

![image](https://github.com/milvus-io/milvus/assets/42060877/6a920df2-6690-4598-8452-15a4c9bfa70b)

**Comment by elstic** [comment]
This case works fine in the 2.4 branch, but crashes in the master branch.
image: master-20240426-c080dc16-amd64


server:
```
upsert-count-1744400-1-58-9840-etcd-0                             1/1     Running                       0                  11m     10.104.32.58    4am-node39   <none>           <none>
upsert-count-1744400-1-58-9840-milvus-standalone-86894b955z7rsg   1/1     Running                       0                  11m     10.104.15.137   4am-node20   <none>           <none>
upsert-count-1744400-1-58-9840-minio-bfcf4c7d8-cdwld              1/1     Running                       0                  11m     10.104.32.53    4am-node39   <none>           <none> (base.py:257)
[2024-04-28 00:25:57,207 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'NAME|upsert-count-1744400-1-58-9840-milvus|upsert-count-1744400-1-58-9840-minio|upsert-count-1744400-1-58-9840-etcd|upsert-count-1744400-1-58-9840-pulsar|upsert-count-1744400-1-58-9840-zookeeper|upsert-count-1744400-1-58-9840-kafka|upsert-count-1744400-1-58-9840-log|upsert-count-1744400-1-58-9840-tikv'  (util_cmd.py:14)
[2024-04-28 00:26:07,024 -  INFO - fouram]: [CliClient] pod details of release(upsert-count-1744400-1-58-9840): 
 I0428 00:25:58.458175    3223 request.go:665] Waited for 1.16826314s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/autoscaling/v2beta1?timeout=32s
NAME                                                              READY   STATUS                        RESTARTS           AGE     IP              NODE         NOMINATED NODE   READINESS GATES
upsert-count-1744400-1-58-9840-etcd-0                             1/1     Running                       0                  5h22m   10.104.32.58    4am-node39   <none>           <none>
upsert-count-1744400-1-58-9840-milvus-standalone-86894b955z7rsg   0/1     CrashLoopBackOff              37 (2m6s ago)      5h22m   10.104.15.137   4am-node20   <none>           <none>
upsert-count-1744400-1-58-9840-minio-bfcf4c7d8-cdwld              1/1     Running                       0                  5h22m   10.104.32.53    4am-node39   <none>           <none>
```

deploy config:
```
    standalone:
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 8
          memory: 16Gi
      profiling:
        enabled: true
    extraConfigFiles:
      user.yaml: |+
        quotaAndLimits:
          dml:
            enabled: true
            upsertRate:
              max: 0.5
          quotaCenterCollectInterval: 1
```

grafana:
![image](https://github.com/milvus-io/milvus/assets/48523564/fc82515b-0b4b-4fe0-b948-9c36106cb82a)

client pod:  fouramf-6tth5-60-4232-milvus-standalone-5f9fd547d-m5mgs

**Comment by elstic** [comment]
@bigsheeper  please pay attention to this issue.

**Comment by bigsheeper** [comment]
> @bigsheeper please pay attention to this issue.

@elstic Could you please provide me the full milvus config? thanks

**Comment by bigsheeper** [comment]
![image](https://github.com/milvus-io/milvus/assets/42060877/1cec3e8d-7667-43fd-87d5-2c9ee99af79b)

related to https://github.com/milvus-io/milvus/pull/32647

should be fixed, please help to verify @elstic

**Comment by elstic** [comment]
Verified and fixed
Verify image: master-20240430-42d0412e

**Comment by elstic** [comment]
The issue has resurfaced. 
When I turn on dml flow limiting and continue to concurrently upsert, milvus crashes. 
image: master-20240521-3d105fcb-amd64
deploy config:
```
    standalone:
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 8
          memory: 16Gi
      profiling:
        enabled: true
    extraConfigFiles:
      user.yaml: |+
        quotaAndLimits:
          dml:
            enabled: true
            upsertRate:
              max: 0.5
          quotaCenterCollectInterval: 1
```

server:
```
upsert-count-1718000-1-71-5787-etcd-0                             1/1     Running       0               11m     10.104.26.12    4am-node3
2   <none>           <none>
upsert-count-1718000-1-71-5787-milvus-standalone-9d776678-rwvjh   1/1     Running       0               11m     10.104.20.245   4am-node2
2   <none>           <none>
upsert-count-1718000-1-71-5787-minio-697ff7664-z4mj8              1/1     Running       0               11m     10.104.25.97    4am-node3
0   <none>           <none> (base.py:257)
[2024-05-22 00:23:22,654 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'NAME|upsert-count-1718000-1-71-
5787-milvus|upsert-count-1718000-1-71-5787-minio|upsert-count-1718000-1-71-5787-etcd|upsert-count-1718000-1-71-5787-pulsar|upsert-count-1
718000-1-71-5787-zookeeper|upsert-count-1718000-1-71-5787-kafka|upsert-count-1718000-1-71-5787-log|upsert-count-1718000-1-71-5787-tikv'
(util_cmd.py:14)
[2024-05-22 00:23:32,987 -  INFO - fouram]: [CliClient] pod details of release(upsert-count-1718000-1-71-5787):
 I0522 00:23:24.303787    3444 request.go:665] Waited for 1.198514145s due to client-side throttling, not priority and fairness, request:
 GET:https://kubernetes.default.svc.cluster.local/apis/autoscaling/v1?timeout=32s
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE
         NOMINATED NODE   READINESS GATES
upsert-count-1718000-1-71-5787-etcd-0                             1/1     Running            0               5h18m   10.104.26.12    4am-
node32   <none>           <none>
upsert-count-1718000-1-71-5787-milvus-standalone-9d776678-rwvjh   0/1     CrashLoopBackOff   9 (34s ago)     5h18m   10.104.20.245   4am-
node22   <none>           <none>
upsert-count-1718000-1-71-5787-minio-697ff7664-z4mj8              1/1     Running            0               5h18m   10.104.25.97    4am-
node30   <none>           <none> (cli_client.py:138)
```
grafana:
![image](https://github.com/milvus-io/milvus/assets/48523564/b37b726d-1ec0-4d66-96f5-2d061ecbd108)

prometheus:
![image](https://github.com/milvus-io/milvus/assets/48523564/33d87ae7-b93d-47e3-a6a9-7036466a5aca)
