### ISSUE TITLE
[Bug]: Rootcoord did not started normally.

### ISSUE THREAD

**Issue by muazhari** [milvus-io/milvus#31992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-latest-gpu
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2): -
- OS(Ubuntu or CentOS): Windows WSL2
- CPU/Memory: I9-13900K/32GB
- GPU: RTX4090
- Others: -
```

### Current Behavior

This condition in the image came up when I was using Milvus in a separate mode, like in [this](https://github.com/muazhari/research-assistant-infrastructure/blob/8ffef5d65c9cc1140242bade0306c58d2868f846/many/docker-compose.yml#L441-L460)
![image](https://github.com/milvus-io/milvus/assets/39398937/dd859de8-a8b0-4658-82fb-8ce3c42eeb74)

```yaml
  milvus-root-coord:
    image: milvusdb/milvus:2.4-latest-gpu
    deploy:
      replicas: 3
    hostname: ${MILVUS_PROXY_HOST}
    entrypoint: [ "milvus" ]
    command:
      - run
      - rootcoord
    environment:
      - ETCD_ENDPOINTS=${NGINX_TWO_HOST}:${GATEWAY_ETCD_CLIENT_PORT}
      - MINIO_ADDRESS=${NGINX_TWO_HOST}:${GATEWAY_MINIO_NODE_PORT}
      - MINIO_ACCESS_KEY_ID=${GATEWAY_MINIO_ROOT_USER}
      - MINIO_SECRET_ACCESS_KEY=${GATEWAY_MINIO_ROOT_PASSWORD}
      - KAFKA_ADDRESS=${NGINX_TWO_HOST}:${GATEWAY_KAFKA_PORT}
      - ROOT_COORD_ENABLE_ACTIVE_STANDBY=true
    volumes:
      - ./milvus/root-coord/data:/var/lib/milvus
    depends_on:
      - nginx-two
   ```

### Expected Behavior

When I deploy Milvus in a separate mode, it behaves normally.

### Steps To Reproduce

```markdown
1. Run this [docker-compose.yml](https://github.com/muazhari/research-assistant-infrastructure/blob/main/many/docker-compose.yml)
```

### Milvus Log

```
2024-04-08 11:24:59 [2024/04/08 04:24:59.873 +00:00] [DEBUG] [rootcoord/root_coord.go:768] ["RootCoord current state"] [StateCode=Initializing]
```

### Anything else?

The [`docker-compose.yml`](https://github.com/muazhari/research-assistant-infrastructure/blob/main/many/docker-compose.yml) will be used in the docker swarm with multi-worker nodes. However, I still using one machine deployment because I have not yet supported it.
