### ISSUE TITLE
[Bug]: Cannot Connect to ETCD with user/password 2.4.0 - no configuration?

### ISSUE THREAD

**Issue by aptmess** [milvus-io/milvus#32365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0-gpu
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 40
- GPU: 3
- Others:
```

### Current Behavior

In [issue](https://github.com/milvus-io/milvus/issues/31631#issuecomment-2057853846) there were some PR that says about "fixed connection to etc by user/password". I am deploying milvus-on-cluster using helm chart and I have no changes - still empty password. What type of configuration should I use? Help me please - I haven't found any configuration files and settings in 2.4.0 release

My configuration files in `values.yaml`:

```yaml
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true
    etcd:
      endpoints:
        - <host>
      auth:
        enable: true
        userName: <user>
        password: <password>

externalEtcd:
  enabled: true
  auth: enabled
  userName: <user>
  password: <password>
  endpoints:
    - <host>
```

### Expected Behavior

I can connect to etc with user and password by helm deploying milvus-on-cluster

### Steps To Reproduce

```markdown
Deployment Milvus on cluster with ExternalETCD
```

**Comment by aptmess** [comment]
Absolutely the same as in the issue

```
{"level":"warn","ts":"2024-03-26T16:31:03.204Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://<host>:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
```

**Comment by aptmess** [comment]
In [ETCD](https://milvus.io/docs/configure_etcd.md#etcdendpoints) documentation there is now parameters that I can add to use user and password in external etcd. May be it is the reason why I can't connect?

**Comment by LoveEachDay** [comment]
@aptmess Your values files is incorrect, the config item should be `etcd.auth.enabled`. Try the following configuration instead:
```
extraConfigFiles:
  user.yaml: |+
    etcd:
      auth:
        enabled: true
        userName: <user>
        password: <password>
```
