### ISSUE TITLE
[Bug]: [benchmark][standalone][LRU] milvus restart and search raises error`collection not loaded` in serial search scene

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#32398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-io-lru-dev-003dc9f-20240417
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: lru-fouramf-95bwd-recall
test case name: test_recall_sift_hnsw_standalone

server:
```
[2024-04-17 13:20:30,721 -  INFO - fouram]: [Base] Deploy initial state: 
I0417 12:26:37.161354     399 request.go:665] Waited for 1.166144288s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/apiregistration.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS                            RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-recall-etcd-0                                                 1/1     Running                           0               4m21s   10.104.29.194   4am-node35   <none>           <none>
lru-recall-milvus-standalone-5d7b947cf5-5d8jl                     1/1     Running                           0               4m21s   10.104.23.98    4am-node27   <none>           <none>
lru-recall-minio-74ddd96699-kjfsv                                 1/1     Running                           0               4m21s   10.104.19.110   4am-node28   <none>           <none>
lru-recall-pulsar-bookie-0                                        1/1     Running                           0               4m21s   10.104.29.197   4am-node35   <none>           <none>
lru-recall-pulsar-bookie-1                                        1/1     Running                           0               4m20s   10.104.16.221   4am-node21   <none>           <none>
lru-recall-pulsar-bookie-2                                        1/1     Running                           0               4m20s   10.104.21.238   4am-node24   <none>           <none>
lru-recall-pulsar-bookie-init-w5wh4                               0/1     Completed                         0               4m21s   10.104.17.22    4am-node23   <none>           <none>
lru-recall-pulsar-broker-0                                        1/1     Running                           0               4m21s   10.104.19.106   4am-node28   <none>           <none>
lru-recall-pulsar-proxy-0                                         1/1     Running                           0               4m21s   10.104.4.250    4am-node11   <none>           <none>
lru-recall-pulsar-pulsar-init-9pfrb                               0/1     Completed                         0               4m21s   10.104.4.248    4am-node11   <none>           <none>
lru-recall-pulsar-recovery-0                                      1/1     Running                           0               4m21s   10.104.17.23    4am-node23   <none>           <none>
lru-recall-pulsar-zookeeper-0                                     1/1     Running                           0               4m21s   10.104.19.109   4am-node28   <none>           <none>
lru-recall-pulsar-zookeeper-1                                     1/1     Running                           0               3m41s   10.104.30.29    4am-node38   <none>           <none>
lru-recall-pulsar-zookeeper-2                                     1/1     Running                           0               3m5s    10.104.17.26    4am-node23   <none>           <none> (base.py:257)
[2024-04-17 13:20:30,722 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'NAME|lru-recall-milvus|lru-recall-minio|lru-recall-etcd|lru-recall-pulsar|lru-recall-zookeeper|lru-recall-kafka|lru-recall-log|lru-recall-tikv'  (util_cmd.py:14)
[2024-04-17 13:20:40,552 -  INFO - fouram]: [CliClient] pod details of release(lru-recall): 
 I0417 13:20:32.001577    1748 request.go:665] Waited for 1.174129857s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/batch/v1?timeout=32s
NAME                                                              READY   STATUS                            RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-recall-etcd-0                                                 1/1     Running                           0                58m     10.104.29.194   4am-node35   <none>           <none>
lru-recall-milvus-standalone-5d7b947cf5-5d8jl                     0/1     Running                           4 (25s ago)      58m     10.104.23.98    4am-node27   <none>           <none>
lru-recall-minio-74ddd96699-kjfsv                                 1/1     Running                           0                58m     10.104.19.110   4am-node28   <none>           <none>
lru-recall-pulsar-bookie-0                                        1/1     Running                           0                58m     10.104.29.197   4am-node35   <none>           <none>
lru-recall-pulsar-bookie-1                                        1/1     Running                           0                58m     10.104.16.221   4am-node21   <none>           <none>
lru-recall-pulsar-bookie-2                                        1/1     Running                           0                58m     10.104.21.238   4am-node24   <none>           <none>
lru-recall-pulsar-bookie-init-w5wh4                               0/1     Completed                         0                58m     10.104.17.22    4am-node23   <none>           <none>
lru-recall-pulsar-broker-0                                        1/1     Running                           0                58m     10.104.19.106   4am-node28   <none>           <none>
lru-recall-pulsar-proxy-0                                         1/1     Running                           0                58m     10.104.4.250    4am-node11   <none>           <none>
lru-recall-pulsar-pulsar-init-9pfrb                               0/1     Completed                         0                58m     10.104.4.248    4am-node11   <none>           <none>
lru-recall-pulsar-recovery-0                                      1/1     Running                           0                58m     10.104.17.23    4am-node23   <none>           <none>
lru-recall-pulsar-zookeeper-0                                     1/1     Running                           0                58m     10.104.19.109   4am-node28   <none>           <none>
lru-recall-pulsar-zookeeper-1                                     1/1     Running                           0                57m     10.104.30.29    4am-node38   <none>           <none>
lru-recall-pulsar-zookeeper-2                                     1/1     Running                           0                57m     10.104.17.26    4am-node23   <none>           <none> (
```

client pod name: lru-fouramf-95bwd-recall-585225513
client log:
[client.log](https://github.com/milvus-io/milvus/files/15019317/client.log)

<img width="1916" alt="截屏2024-04-18 10 54 04" src="https://github.com/milvus-io/milvus/assets/26307815/c49e1c5d-8b05-4a5c-920b-5e3e3006ea06">

### Steps To Reproduce

```markdown
1. create a collection
2. insert dataset: sift-128-euclidean
3. flush collection
4. build HNSW index
5. load collection
6. serial search <- milvus restart and search failed
```

### Anything else?

server config:
```
    standalone:
      resources:
        limits:
          cpu: '2'
          memory: 2Gi
          ephemeral-storage: 3Gi
        requests:
          cpu: '2'
          memory: 2Gi
      messageQueue: pulsar
      extraEnv:
        - name: LOCAL_STORAGE_SIZE
          value: '3'
      disk:
        size:
          enabled: true
    etcd:
      replicaCount: 1
      metrics:
        enabled: true
        podMonitor:
          enabled: true
    minio:
      mode: standalone
      metrics:
        podMonitor:
          enabled: true
      persistence:
        size: 15Gi
    pulsar:
      enabled: true
    metrics:
      serviceMonitor:
        enabled: true
    log:
      level: debug
    extraConfigFiles:
      user.yaml: |+
        queryNode:
          mmap:
            mmapEnabled: true
          lazyloadEnabled: true
          useStreamComputing: true
          cache:
            warmup: sync
          lazyloadWaitTimeout: 300000
```
