### ISSUE TITLE
[Bug]: [benchmark][standalone][LRU] Build index raises error `failed to upload index` and milvus restarts multiple times

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#32487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-io-lru-dev-27cb486-20240419
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: lru-fouramf-nk4fk

server:
```
NAME                                                              READY   STATUS                            RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-500g-etcd-0                                                   1/1     Running                           0               2d2h    10.104.20.193   4am-node22   <none>           <none>
lru-500g-milvus-standalone-844c594b58-fkpwr                       1/1     Running                           8 (17m ago)     2d2h    10.104.31.236   4am-node34   <none>           <none>
lru-500g-pulsar-bookie-0                                          1/1     Running                           0               2d2h    10.104.20.195   4am-node22   <none>           <none>
lru-500g-pulsar-bookie-1                                          1/1     Running                           0               2d2h    10.104.29.179   4am-node35   <none>           <none>
lru-500g-pulsar-bookie-2                                          1/1     Running                           0               2d2h    10.104.26.180   4am-node32   <none>           <none>
lru-500g-pulsar-bookie-init-h9xz8                                 0/1     Completed                         0               2d2h    10.104.1.4      4am-node10   <none>           <none>
lru-500g-pulsar-broker-0                                          1/1     Running                           1 (21h ago)     2d2h    10.104.1.8      4am-node10   <none>           <none>
lru-500g-pulsar-proxy-0                                           1/1     Running                           0               2d2h    10.104.6.221    4am-node13   <none>           <none>
lru-500g-pulsar-pulsar-init-drpwj                                 0/1     Completed                         0               2d2h    10.104.6.220    4am-node13   <none>           <none>
lru-500g-pulsar-recovery-0                                        1/1     Running                           0               2d2h    10.104.6.222    4am-node13   <none>           <none>
lru-500g-pulsar-zookeeper-0                                       1/1     Running                           0               2d2h    10.104.20.194   4am-node22   <none>           <none>
lru-500g-pulsar-zookeeper-1                                       1/1     Running                           0               2d2h    10.104.29.181   4am-node35   <none>           <none>
lru-500g-pulsar-zookeeper-2                                       1/1     Running                           0               2d2h    10.104.34.8     4am-node37   <none>           <none>
```

![image](https://github.com/milvus-io/milvus/assets/26307815/f21209f8-5d23-46f3-a935-5cf4f2a631ed)
<img width="1920" alt="截屏2024-04-22 00 49 20" src="https://github.com/milvus-io/milvus/assets/26307815/5243351f-6e2e-4789-b61e-a5f5a1ee48dc">

<img width="1916" alt="截屏2024-04-22 00 50 39" src="https://github.com/milvus-io/milvus/assets/26307815/52d9ef83-4469-433f-a6b0-52746a83cd54">

client pod name: lru-fouramf-nk4fk-1027207446
client log:
<img width="1540" alt="截屏2024-04-22 00 45 31" src="https://github.com/milvus-io/milvus/assets/26307815/732c046a-b4a2-4396-b8d0-3b044a2a1481">

### Steps To Reproduce

```markdown
1. create a collection, 2 fields: "id"(primary key), "float_vector"(768dim),
2. build HNSW index
3. insert 270m data
4. flush collection
5. build index again with the same params <- failed
```

### Anything else?

client config:
```
{
     "dataset_params": {
          "dataset_name": "laion1b_nolang",
          "column_name": "float32_vector",
          "dim": 768,
          "dataset_size": "270m",
          "ni_per": 10000,
          "metric_type": "L2",
          "extra_partitions": {
               "partitions": 27,
               "data_repeated": false
          }
     },
     "collection_params": {
          "other_fields": [],
          "collection_name": "fouram_270m",
          "shards_num": 1
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 30,
               "efConstruction": 360
          }
     },
     "concurrent_tasks": [
          {
               "type": "search",
               "weight": 1,
               "params": {
                    "top_k": 100,
                    "nq": 10,
                    "search_param": {
                         "ef": 64
                    },
                    "timeout": 3000,
                    "random_data": true
               }
          }
     ],
     "concurrent_params": {
          "interval": 20,
          "during_time": "1h",
          "concurrent_number": 1
     }
}
```

server config:
```
    standalone:
      resources:
        limits:
          cpu: '16'
          memory: 32Gi
          ephemeral-storage: 70Gi
        requests:
          cpu: '16'
          memory: 32Gi
      messageQueue: pulsar
      extraEnv:
        - name: LOCAL_STORAGE_SIZE
          value: '70'
      disk:
        size:
          enabled: true
    etcd:
      replicaCount: 1
      metrics:
        enabled: true
        podMonitor:
          enabled: true
    minio:
      enabled: false
    externalS3:
      enabled: true
      accessKey: miniolru500g
      secretKey: miniolru500g
      bucketName: lru-500g
      host: minio-1.minio
      port: 9000
      rootPath: lru500g
    pulsar:
      enabled: true
    metrics:
      serviceMonitor:
        enabled: true
    log:
      level: debug
    extraConfigFiles:
      user.yaml: |+
        queryNode:
          diskCacheCapacityLimit: 51539607552
          mmap:
            mmapEnabled: true
          lazyloadEnabled: true
          useStreamComputing: true
          cache:
            warmup: sync
          lazyloadWaitTimeout: 300000
```
