### ISSUE TITLE
[Bug]: [benchmark][cluster][LRU] DQL requests rases error `fail to Query on QueryNode 2: worker(2) query failed: service internal error: time out`

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#32513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-io-lru-dev-b26c3cf-20240422
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: lru-fouramf-qsjqr

server:
```
NAME                                                              READY   STATUS                            RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-verify-32135-cluster-etcd-0                                   1/1     Running                           0               6h39m   10.104.20.190   4am-node22   <none>           <none>
lru-verify-32135-cluster-etcd-1                                   1/1     Running                           0               6h39m   10.104.21.243   4am-node24   <none>           <none>
lru-verify-32135-cluster-etcd-2                                   1/1     Running                           0               6h39m   10.104.29.210   4am-node35   <none>           <none>
lru-verify-32135-cluster-milvus-datacoord-57df5d9789-qjl77        1/1     Running                           0               6h39m   10.104.6.128    4am-node13   <none>           <none>
lru-verify-32135-cluster-milvus-datanode-64bbb86546-dhnf8         1/1     Running                           0               6h39m   10.104.4.168    4am-node11   <none>           <none>
lru-verify-32135-cluster-milvus-indexcoord-68c7d9d6d4-mn85x       1/1     Running                           0               6h39m   10.104.1.75     4am-node10   <none>           <none>
lru-verify-32135-cluster-milvus-indexnode-5467b7789c-szn75        1/1     Running                           0               6h39m   10.104.13.8     4am-node16   <none>           <none>
lru-verify-32135-cluster-milvus-indexnode-5467b7789c-xzml9        1/1     Running                           0               6h39m   10.104.6.126    4am-node13   <none>           <none>
lru-verify-32135-cluster-milvus-proxy-6bbd94d696-4qf22            1/1     Running                           0               6h39m   10.104.1.76     4am-node10   <none>           <none>
lru-verify-32135-cluster-milvus-querycoord-56d667c855-jr6xm       1/1     Running                           0               6h39m   10.104.6.124    4am-node13   <none>           <none>
lru-verify-32135-cluster-milvus-querynode-75f7c5984d-pg98l        1/1     Running                           0               6h39m   10.104.6.122    4am-node13   <none>           <none>
lru-verify-32135-cluster-milvus-rootcoord-cf888d55c-t85hz         1/1     Running                           0               6h39m   10.104.6.125    4am-node13   <none>           <none>
lru-verify-32135-cluster-minio-0                                  1/1     Running                           0               6h39m   10.104.20.196   4am-node22   <none>           <none>
lru-verify-32135-cluster-minio-1                                  1/1     Running                           0               6h39m   10.104.15.191   4am-node20   <none>           <none>
lru-verify-32135-cluster-minio-2                                  1/1     Running                           0               6h39m   10.104.34.146   4am-node37   <none>           <none>
lru-verify-32135-cluster-minio-3                                  1/1     Running                           0               6h39m   10.104.21.245   4am-node24   <none>           <none>
lru-verify-32135-cluster-pulsar-bookie-0                          1/1     Running                           0               6h39m   10.104.20.192   4am-node22   <none>           <none>
lru-verify-32135-cluster-pulsar-bookie-1                          1/1     Running                           0               6h39m   10.104.34.144   4am-node37   <none>           <none>
lru-verify-32135-cluster-pulsar-bookie-2                          1/1     Running                           0               6h39m   10.104.15.193   4am-node20   <none>           <none>
lru-verify-32135-cluster-pulsar-bookie-init-jmqtx                 0/1     Completed                         0               6h39m   10.104.1.72     4am-node10   <none>           <none>
lru-verify-32135-cluster-pulsar-broker-0                          1/1     Running                           0               6h39m   10.104.1.73     4am-node10   <none>           <none>
lru-verify-32135-cluster-pulsar-proxy-0                           1/1     Running                           0               6h39m   10.104.1.74     4am-node10   <none>           <none>
lru-verify-32135-cluster-pulsar-pulsar-init-x7xxq                 0/1     Completed                         0               6h39m   10.104.13.6     4am-node16   <none>           <none>
lru-verify-32135-cluster-pulsar-recovery-0                        1/1     Running                           0               6h39m   10.104.13.7     4am-node16   <none>           <none>
lru-verify-32135-cluster-pulsar-zookeeper-0                       1/1     Running                           0               6h39m   10.104.20.191   4am-node22   <none>           <none>
lru-verify-32135-cluster-pulsar-zookeeper-1                       1/1     Running                           0               6h38m   10.104.21.249   4am-node24   <none>           <none>
lru-verify-32135-cluster-pulsar-zookeeper-2                       1/1     Running                           0               6h38m   10.104.29.212   4am-node35   <none>           <none>
```

client pod name:  lru-fouramf-qsjqr-2174733771
client log:
<img width="1527" alt="截屏2024-04-22 21 08 13" src="https://github.com/milvus-io/milvus/assets/26307815/d666299a-5ddc-4ae8-bd81-1272e3fe6c06">

### Steps To Reproduce

```markdown
1. create a collection, 3 fields: "id"(primaryKey), "float_vector"(768dim), "int64_1"(partition num=64)
2. build HNSW index
3. insert 10w
4. flush collection
5. build index again with the same params
6. concurrent request:
   - insert
   - delete
   - load
   - search
   - query
```

### Anything else?

client config:
```
{
     "dataset_params": {
          "dataset_name": "laion1b_nolang",
          "column_name": "float32_vector",
          "dim": 768,
          "dataset_size": "10w",
          "ni_per": 10000,
          "metric_type": "L2",
          "scalars_params": {
               "int64_1": {
                    "params": {
                         "is_partition_key": true
                    }
               }
          }
     },
     "collection_params": {
          "other_fields": [
               "int64_1"
          ],
          "num_partitions": 64
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 30,
               "efConstruction": 360
          }
     },
     "concurrent_tasks": [
          {
               "type": "insert",
               "weight": 1,
               "params": {
                    "nb": 64,
                    "timeout": 3000,
                    "random_vector": true
               }
          },
          {
               "type": "delete",
               "weight": 1,
               "params": {
                    "delete_length": 64,
                    "timeout": 3000
               }
          },
          {
               "type": "flush",
               "weight": 0,
               "params": {
                    "timeout": 3000
               }
          },
          {
               "type": "load",
               "weight": 1,
               "params": {
                    "timeout": 3000
               }
          },
          {
               "type": "search",
               "weight": 1,
               "params": {
                    "top_k": 1,
                    "nq": 10,
                    "search_param": {
                         "ef": 64
                    },
                    "expr": "int64_1 >= 0 && int64_1 <= 4",
                    "timeout": 3000,
                    "random_data": true
               }
          },
          {
               "type": "query",
               "weight": 1,
               "params": {
                    "expr": "int64_1 != 2",
                    "timeout": 3000,
                    "offset": 0,
                    "limit": 10
               }
          }
     ],
     "concurrent_params": {
          "interval": 20,
          "during_time": "12h",
          "concurrent_number": 10
     }
}
```

server config:
```
    queryNode:
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          ephemeral-storage: 70Gi
        requests:
          cpu: '2'
          memory: 8Gi
      replicas: 1
      extraEnv:
        - name: LOCAL_STORAGE_SIZE
          value: '70'
    indexNode:
      resources:
        limits:
          cpu: '8.0'
          memory: 8Gi
        requests:
          cpu: '5.0'
          memory: 5Gi
      replicas: 2
    dataNode:
      resources:
        limits:
          cpu: '2.0'
          memory: 8Gi
        requests:
          cpu: '2.0'
          memory: 8Gi
      replicas: 1
    minio:
      metrics:
        podMonitor:
          enabled: true
      persistence:
        size: 320Gi
    etcd:
      metrics:
        enabled: true
        podMonitor:
          enabled: true
    metrics:
      serviceMonitor:
        enabled: true
    log:
      level: debug
    extraConfigFiles:
      user.yaml: |
        queryNode:
          diskCacheCapacityLimit: 51539607552
          mmap:
            mmapEnabled: true
          lazyloadEnabled: true
          useStreamComputing: true
          cache:
            warmup: sync
          lazyloadWaitTimeout: 300000
```
