### ISSUE TITLE
Search performance descreased based on sift1b when nq equals 1

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3266]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
Searching time cost almost `1s` based on sift-1m dataset, ivf_sq8 index created.
```
│  Nq/Top-k   │      1      │     10      │     100     │    1000     │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           1 │        0.04 │        0.04 │        0.04 │        0.05 │
│          10 │        0.05 │        0.04 │        0.05 │        0.06 │
│         100 │         0.1 │        0.12 │        0.13 │        0.18 │
│        1000 │        0.58 │        0.58 │        0.63 │        1.05 │
│        1200 │        0.76 │        0.73 │        0.75 │        1.15 │
```

**Steps/Code to reproduce behavior**
create collection and index
insert 50000 vectors per request,
create index again,
and then search.
```
segment_row_count: 50000
index:
   type: ivf_sq8
   nlist: 1024
   metric_type: L2
search:
   nprobe: 8
   metric_type: L2
```

**Expected behavior**

**Environment details**
master-branch
GPU server version and searching with CPU (nq < gpu_search_threshold)
```
      collection_name: sift_1m_50000_128_l2_2
      run_count: 2
      top_ks: [1, 10, 100, 1000]
      nqs: [1, 10, 100, 1000, 1200]
      # filter:
      #   term: 
      #     int64: 
      #       LT: 500000
      #       GT: 700000
      search_params:
        -
          nprobe: 8
```
**Screenshots**

**Additional context**
