### ISSUE TITLE
[Bug]: multi-col top-k unexpected

### ISSUE THREAD

**Issue by JackTan25** [milvus-io/milvus#33146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment standalone  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7
- CPU/Memory: 12c 128G
- GPU: 
- Others:
```

### Current Behavior

multi-col top-k where k is 50, we can get only ten results.

### Expected Behavior

get 50 results.

**Comment by JackTan25** [comment]
[unexpected_top_k.zip](https://github.com/milvus-io/milvus/files/15369214/unexpected_top_k.zip)

**Comment by JackTan25** [comment]
step to reprocess:
1. unzip https://github.com/milvus-io/milvus/files/15369214/unexpected_top_k.zip
2. python3 small_data/data_load_small_data.py # load data
3. python3 small_data/milvus_small_multi_vector.py # run multi-top-k test
@yanliang567

**Comment by yanliang567** [comment]
I did not reproduce the issue on latest milvus 2.4.2 build, I got 50 results as expected. 
![image](https://github.com/milvus-io/milvus/assets/82361606/c37402d2-02cf-415a-a761-553c156a7b84)
could you please retry?
/assign @JackTan25 
/unassign

**Comment by JackTan25** [comment]
@yanliang567 Hi, did you modify the code of mine? is there any error?

**Comment by yanliang567** [comment]
> @yanliang567 Hi, did you modify the code of mine? is there any error?
I changed the milvus server ip only

**Comment by JackTan25** [comment]
milvusdb/milvus:v2.4.0-rc.1  this is the version of mine @yanliang567

**Comment by JackTan25** [comment]
Is there any change about miles multi vector search between these two versions?

**Comment by JackTan25** [comment]
```yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.1
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
This is my docker-compose.yaml file, Is there any problem? before I upgrade milvus from 2.3.5 to 2.4.1,  So I run 
```shell
docker compose down
docker compose up -d
```
and I will get warning like below:
```text
WARN[0000] /home/tanboyu/cpp_workspace/milvus/docker-compose.yml: `version` is obsolete 
```
I'm not sure whether it will cause this? @yanliang567
