### ISSUE TITLE
[Bug]: [cluster-mode] Milvus crash and cannot auto-recover successfully

### ISSUE THREAD

**Issue by tianshihan818** [milvus-io/milvus#33338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.1
- Deployment mode(standalone or cluster): cluster, by helm, based on chart milvus-4.1.31
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- milvus cluster deployment scale
``` bash
# The nodes info on k8s
6 nodes, centos OS, each 256cpu/500Gi/3.5T*4 (NVMe SSD)
```
``` bash
# The deployment method
on k8s, by helm, using milvus v2.4.1
```
``` yaml
# The main deployment values
dataCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi

dataNode:
  replicas: 4
  resources:
    limits:
      cpu: 2
      memory: 8Gi

etcd:
  persistence:
    size: 30Gi
  replicaCount: 3
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi  

indexCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi

indexNode:
  replicas: 4
  resources:
    limits:
      cpu: 8
      memory: 16Gi

minio:
  persistence:
    size: 10500Gi
  resources:
    limits:
      cpu: 8
      memory: 32Gi

proxy:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 8Gi

pulsar:
  autorecovery:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
  bookkeeper:
    configData:
      PULSAR_GC: |
        -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails
      PULSAR_MEM: |
        -Xms16384M -Xmx16384M -XX:MaxDirectMemorySize=32768M
      nettyMaxFrameSizeBytes: "104867840"
    replicaCount: 3
    resources:
      requests:
        cpu: 8
        memory: 64Gi
    volumes:
      journal:
        name: journal
        size: 1150Gi
      ledgers:
        name: ledgers
        size: 2870Gi
  broker:
    component: broker
    configData:
      PULSAR_GC: |
        -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError
      PULSAR_MEM: |
        -Xms16384M -Xmx16384M -XX:MaxDirectMemorySize=32768M
      backlogQuotaDefaultLimitGB: "8"
      backlogQuotaDefaultRetentionPolicy: producer_exception
      defaultRetentionSizeInMB: "-1"
      defaultRetentionTimeInMinutes: "10080"
      maxMessageSize: "104857600"
      subscriptionExpirationTimeMinutes: "3"
      ttlDurationDefaultInSeconds: "259200"
    replicaCount: 2
    resources:
      requests:
        cpu: 8
        memory: 72Gi
  maxMessageSize: "5242880"

  proxy:
    configData:
      PULSAR_MEM: |
        -Xms8192M -Xmx8192M -XX:MaxDirectMemorySize=8192M
      httpNumThreads: "100"
    replicaCount: 2
    resources:
      requests:
        cpu: 8
        memory: 18Gi

  zookeeper:
    configData:
      PULSAR_GC: |
        -Dcom.sun.management.jmxremote -Djute.maxbuffer=10485760 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -Dzookeeper.forceSync=no
      PULSAR_MEM: |
        -Xms4096M -Xmx4096M
    resources:
      requests:
        cpu: 4
        memory: 8Gi
    volumes:
      data:
        size: 20Gi

queryCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi

queryNode:
  replicas: 16
  resources:
    limits:
      cpu: 16
      memory: 128Gi

rootCoordinator:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 4Gi
```

- What I do
``` text
1. create a collection (schema: auto-id field + 768-dim float vector field; partition: default; shard: 4/8 both tried)
2. generate random data and insert (single call pymilvus insert API, insert 10000 entites each time)
3. create IVF_SQ8 index (metric type: L2; nlist: default 1024) and then load data after the entites reached about 1 million level
4. Then insert continually, and milvus will create index & load data automatically
```

- What happens
Any discussion before is here: [Failed to reload the collections after restarting the milvus cluster.](https://github.com/milvus-io/milvus/discussions/33135)
1. I have a collection (one auto-id field + one 768 dim vector field, one partition + one shard) before, HNSW indexed (M: 8, efConstruction: 128) and loaded. Later I consider that the HNSW index will cost a lot memory resource, so I deleted the original index and rebuilt the IVF_SQ8 index on this collection, and reload it.
2. Later, I want to increase the shards amount, so I create a new collection (one auto-id field + one 768 dim vector field, one partition + 4/8 shard both tried), batch insert 10000 entities by single thread, IVF_SQ8 indexed and loaded at the 1 million entities level, then it will trigger indexing and loading the segments automatically after inserting.
3. The milvus cluster is stable before the collection entities num arrives near to 300 million, after that the milvus cluster will crash. 
4. At that crash moment, pods will keep crashing and restarting but cannot recover back to normal. So I reboot the milvus cluster by helm like:
``` bash
helm uninstall {milvus_instance_name}
# after all pods terminated
helm install {milvus_instance_name} zilliztech/milvus -f ./values.yaml
```
And the milvus cluster will run successfully again.

However, there is another problem.
The restarted milvus cluster will reload the previous loaded 300-million-level collection, and during this process, the milvus cluster will crash again. I checked the k8s events, pods logs and grafana metrics, founding out that the disk usage of the directory `/var` will increase a lot during the reloading process, which leads to some nodes be tainted with the label `{node.kubernetes.io/disk-pressure: }` by k8s when the usage rate exceeds 85%. And k8s will evict the pods on these nodes then, as sometimes there are not any clean nodes without the above taint, these pods cannot be re-scheduled, just keep crashing here, finally the whole milvus cluster became unavailable.

Moreover, when I reproduce a case I met before (that is some components such as rootcoord or datacoord will disconnect from etcd during milvus running , I also find this werid scene: speedy increasing disk usage on the directory `/var`, and sometimes it will decrease to a normal level so the milvus cluster keep running normally, but sometimes it will trigger the threshold and lead to pods eviction and milvus crash.
By the way, the method that I simulate the etcd service down & up is scale down the etcd statefulset replicas to 1 and scale up the replicas to 3 later, and during this process the milvus components will crash and restart automatically.
When the components are restarting:
![image (3)](https://github.com/milvus-io/milvus/assets/154961771/753e8253-4656-4806-9664-f12fbaeac835)
And trigger the k8s diskpressure taint threshold:
![image (4)](https://github.com/milvus-io/milvus/assets/154961771/1b16fccc-bf1a-463f-9c80-e036049b39fc)
Then many pods are evicted and re-scheduled:
![image (5)](https://github.com/milvus-io/milvus/assets/154961771/34968b49-f6f6-4415-9178-41956799cb0e)

- My questions
1. Why there is such a lot disk usage on the directory `/var`?
From what I know, this directory is for storing some k8s default files, such as kubelet logs or docker images or container runtimes. And I saw the disk i/o rate is too high at that moment, so I want to know whether the cotainer services of milvus will write a lot things into the directory `/var`?

2. The weird thing is, why the crash happens each time the collection entities num arrives to 300 million level.
The minio disk space is enough, only 25% used now, so I am super wondering the reason. And referring to your suggestions, I am doing a new test and preparing to grab the milvus cluster & node metrics at that crash time, will update here later.

3. Why the milvus became available again if I create a new collection for insertion each time I reboot the crash milvus cluster and cancel the reloading process immediately?

### Expected Behavior

When milvus met the above crash, it can recover back to normal automatically.
