### ISSUE TITLE
[Bug]: Paramtable cache cause some dynamic config non-dynamic.

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#33461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Some config support dynamic change been non-dynamic.

**Comment by haorenfsa** [comment]
@aoiasd Does `ttMsgEnabled` support dynamic changes? Please help @anhnch30820 with  this issue: https://github.com/zilliztech/milvus-operator/issues/129

**Comment by haorenfsa** [comment]
@anhnch30820 Would you please provide your new milvus' log here?

**Comment by anhnch30820** [comment]
@haorenfsa @aoiasd here is the logs of milvus v2.4.5
[milvus-milvus-proxy-746fbd5d-724dk_proxy.log](https://github.com/user-attachments/files/15949944/milvus-milvus-proxy-746fbd5d-724dk_proxy.log)

**Comment by aoiasd** [comment]
> @haorenfsa @aoiasd here is the logs of milvus v2.4.5 [milvus-milvus-proxy-746fbd5d-724dk_proxy.log](https://github.com/user-attachments/files/15949944/milvus-milvus-proxy-746fbd5d-724dk_proxy.log)
![image](https://github.com/milvus-io/milvus/assets/45024769/d1fbd769-baee-44bd-b976-fc2882abc434)
![image](https://github.com/milvus-io/milvus/assets/45024769/b55a55f7-43d2-4bd2-90dd-a557c6f09a8e)
From proxy logs we could see this, means ttmsgenable has dynamic changed in proxy. There was some other problem cause collection can't be loaded, but there only logs of proxy, i can't find the question. 
So could you provide logs of querycoord and querynode?

**Comment by anhnch30820** [comment]
@aoiasd here is the logs of querycoord and querynode.
[milvus-milvus-querynode-0-865dff889-xftxs_querynode.log](https://github.com/user-attachments/files/15951130/milvus-milvus-querynode-0-865dff889-xftxs_querynode.log)
[milvus-milvus-querycoord-5f558b84ff-4dw8p_querycoord.log](https://github.com/user-attachments/files/15951133/milvus-milvus-querycoord-5f558b84ff-4dw8p_querycoord.log)

**Comment by aoiasd** [comment]
> @aoiasd here is the logs of querycoord and querynode. [milvus-milvus-querynode-0-865dff889-xftxs_querynode.log](https://github.com/user-attachments/files/15951130/milvus-milvus-querynode-0-865dff889-xftxs_querynode.log) [milvus-milvus-querycoord-5f558b84ff-4dw8p_querycoord.log](https://github.com/user-attachments/files/15951133/milvus-milvus-querycoord-5f558b84ff-4dw8p_querycoord.log)

![image](https://github.com/milvus-io/milvus/assets/45024769/30abaa8b-47e7-4c9f-8a38-aaf8710859de)
Seems kafka connect has some problem. Querynode can't comsume message from kafka after 2024/06/24 04:44:47.960.
Is this kafka config right?
![image](https://github.com/milvus-io/milvus/assets/45024769/024388fd-75e7-4be8-820c-ec059f24240c)

**Comment by anhnch30820** [comment]
@aoiasd  Yeah, The kafka config I get from milvus sizing tool
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  dependencies:
    msgStreamType: kafka
    kafka:
      inCluster:
        values:
          heapOpts: "-Xmx4096M -Xms4096M"
          persistence:
            enabled: true
            storageClass:
            accessMode: ReadWriteOnce
            size: 40Gi
          resources:
            limits:
              cpu: 2
              memory: 13Gi
          zookeeper:
            enabled: true
            replicaCount: 3
            heapSize: 1024  # zk heap size in MB
            persistence:
              enabled: true
              storageClass: ""
              accessModes:
                - ReadWriteOnce
              size: 20Gi #SSD Required
            resources:
              limits:
                cpu: 1
                memory: 2Gi
```
