### ISSUE TITLE
[Bug]:  Slow query on first load of partition in Milvus v2.4.3

### ISSUE THREAD

**Issue by shivabohemian** [milvus-io/milvus#33516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-go/v2 v2.4.0
- OS(Ubuntu or CentOS): debian
- CPU/Memory: 
- GPU: 
- Others: arm64
```

### Current Behavior

After upgrading `Milvus` from version `2.3.13` to `2.4.3`, I noticed that the first search after loading a partition is very slow, taking several minutes (while subsequent searches take only seconds). Once this initial search is completed, subsequent searches remain fast until the partition is released. In version `2.3.13`, the search was almost instantaneous after the partition was loaded. 

Additionally, I am using the `HNSW` index with `mmap` and basically using the `milvus.yaml` configuration file from version `2.4.3`.

### Expected Behavior

After successfully loading the partition, the first search should maintain normal speed, similar to the search speed after loading the partition.

### Milvus Log

The logs only show two loading entries, which makes me curious why there are two.
```
5月 31 16:52:07 testserver milvus[49485]: [2024/05/31 16:52:07.219 +08:00] [INFO] [load_index_info.go:119] ["load with index params"] [indexParams="{\"M\":\"8\",\"dim\":\"1024\",\"efConstruction\":\"96\",\"index_type\":\"HNSW\",\"metric_type\":\"IP\"}"]
5月 31 16:52:07 testserver milvus[49485]: [2024/05/31 16:52:07.501 +08:00] [INFO] [load_index_info.go:119] ["load with index params"] [indexParams="{\"M\":\"8\",\"dim\":\"1024\",\"efConstruction\":\"96\",\"index_type\":\"HNSW\",\"metric_type\":\"IP\"}"]
```

**Comment by yanliang567** [comment]
@shivabohemian could you please share the configs about how you enable mmap? 
/assign @shivabohemian 

/assign @sunby 
please help to take a look, was it running in lazy load?

**Comment by xiaofan-luan** [comment]
do we have any deletions?

**Comment by shivabohemian** [comment]
The mmap configuration is as follows, while other configurations remain consistent with tag 0.4.3. It appears not to be running in lazy loading mode.
```
  mmap:
    mmapEnabled: true # Enable mmap for loading data
    mmapDirPath: /app/milvus/mmap
  lazyload:
    enabled: false # Enable lazyload for loading data
    waitTimeout: 30000 # max wait timeout duration in milliseconds before start to do lazyload search and retrieve
    requestResourceTimeout: 5000 # max timeout in milliseconds for waiting request resource for lazy load, 5s by default
    requestResourceRetryInterval: 2000 # retry interval in milliseconds for waiting request resource for lazy load, 2s by default
    maxRetryTimes: 1 # max retry times for lazy load, 1 by default
    maxEvictPerRetry: 1 # max evict count for lazy load, 1 by default
```
