### ISSUE TITLE
[Bug]: Milvus standalone container crashes automatically 

### ISSUE THREAD

**Issue by hoangph3** [milvus-io/milvus#33782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): no
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 24 cores, 64GB
- GPU: No
- Others:
```

### Current Behavior

When i run docker-compose up -d with compose file:
```
version: "3.0"

services:
  etcd:
    container_name: milvus_etcd
    image: hoangph3/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /opt/db/milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http:/127.0.0.1:2379 -listen-client-urls http:/0.0.0.0:2379 --data-dir /etcd
    restart: always
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus_minio
    image: hoangph3/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - /opt/db/milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: hoangph3/milvus:v2.2.12
    container_name: milvus_standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /opt/db/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
```

After some seconds, the container crashes automatically and restarting, because i set `restart: always`.
I am try on other machine, it's working.
What's going on? I have attached the log image to this issue below.

### Milvus Log

Restarting:
![image](https://github.com/milvus-io/milvus/assets/54660554/8fa52a32-c9cc-47e1-a3b8-370a4ada624e)

Milvus logs before it crashes:
![Screenshot from 2024-06-12 13-26-57](https://github.com/milvus-io/milvus/assets/54660554/3acb842d-e193-4711-a319-505b21e59b38)
![Screenshot from 2024-06-12 10-27-29](https://github.com/milvus-io/milvus/assets/54660554/929bd38d-4c1f-4c6a-bec3-54dc57677150)
