### ISSUE TITLE
[Bug]: Run Milvus with GPU Support Using Docker Compose，After modifying the yaml file, an error message appears: docker-compose.yml: services.standalone Additional property gpu is not allowed

### ISSUE THREAD

**Issue by youqugit** [milvus-io/milvus#33903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I refer to the official document [Run Milvus with GPU Support Using Docker Compose](https://milvus.io/docs/install_standalone-docker-compose-gpu.md), I modified the yaml file to configure 
```
gpu:
    initMemSize:
    maxMemSize:
```

I execute this command `docker compose up -d `. Then I encountered an error: `validating milvus_deploy/docker-compose.yml: services.standalone Additional property gpu is not allowed`

Below is the yaml file I modified:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: m.daocloud.io/quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2389 -listen-client-urls http://0.0.0.0:2389 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: m.daocloud.io/docker.io/minio/minio:RELEASE.2024-03-26T22-10-45Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    gpu:
      initMemSize: 5120
      maxMemSize: 10240
    container_name: milvus-standalone
    image: m.daocloud.io/docker.io/milvusdb/milvus:v2.4.4-gpu
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2389
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "3005:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              device_ids: [ "0", "1", "2" ]
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

```

### Expected Behavior

Correctly configure `initMemSize`  `maxMemSize:` parameters
