### ISSUE TITLE
[Bug]: No milvus processes were found on the GPU.

### ISSUE THREAD

**Issue by wpx1997-stack** [milvus-io/milvus#34895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.6-gpu
- OS(Ubuntu or CentOS): Ubuntu 
- GPU: 3090(nvidia-driver-535)
```

### Current Behavior

Launch milvus-standalone in gpu mode using docker：
```
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.6-gpu
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0","1"]
```

Create a collection and create a GPU-type index：

![index](https://github.com/user-attachments/assets/4b30cdd2-b6fa-4d1c-8a9e-189a40f21484)

No milvus processes were found on the GPU：

![poro](https://github.com/user-attachments/assets/6190b553-2009-47ad-ae76-934d5d578573)
