### ISSUE TITLE
Config URI for database is `meta_uri` but doc says `backend_url`

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#3530]
**Please state your issue using the following template and, most importantly, in English.**

1. URI for metadata storage is under `meta_url`.

```yaml
#----------------------+------------------------------------------------------------+------------+-----------------+
# General Config       | Description                                                | Type       | Default         |
#----------------------+------------------------------------------------------------+------------+-----------------+
# timezone             | Use UTC-x or UTC+x to specify a time zone.                 | Timezone   | UTC+8           |
#----------------------+------------------------------------------------------------+------------+-----------------+
# meta_uri             | URI for metadata storage, using SQLite (for single server  | URI        | sqlite://:@:/   |
#                      | Milvus) or MySQL (for distributed cluster Milvus).         |            |                 |
#                      | Format: dialect://username:password@host:port/database     |            |                 |
#                      | Keep 'dialect://:@:/', 'dialect' can be either 'sqlite' or |            |                 |
#                      | 'mysql', replace other texts with real values.             |            |                 |
#----------------------+------------------------------------------------------------+------------+-----------------+
general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/
```
But the doc says `backend_url`
![backend_url](https://user-images.githubusercontent.com/51370125/91696225-d8560700-eba1-11ea-9017-7a84076fafd7.png)

**Location of incorrect documentation**
https://www.milvus.io/cn/docs/v0.10.2/data_manage.md

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:
