### ISSUE TITLE
[0.8.0-cpu version] throughput descrease when deploy two milvus instance in kubernetes

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#3544]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
throughout descrease when deploy two milvus instance in kubernetes

**Steps/Code to reproduce behavior**
1. a machine with 48 core
2. deploy one milvus instance with the following cpu limit
```yaml
        resources:
          limits:
            cpu: "11"
            memory: 40Gi
          requests:
            cpu: "11"
            memory: 1Gi
```
3. give request stress, and milvus instance almost use out 11 core with 50 qps and 80ms avearge request cost
4. deploy one more milvus instance with same cpu limit above
5. give the same request stress to the two instance(as whole), and every instance use less than 5 core with whole 15 qps and 80ms avearge request cost

**Expected behavior**
the two instance use out their own 11g, and whole throughput double

**Method of installation**
- [x] Docker/cpu under k8s

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

memory: 
```text
              total        used        free      shared  buff/cache   available
Mem:           124G         12G         94G        4.1G         17G        105G
Swap:            0B          0B          0B
```
os: CentOS Linux release 7.5.1804 (Core)
cpu: 
```text
[xxx@xxx ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
Stepping:              7
CPU MHz:               2200.000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              16896K
NUMA node0 CPU(s):     0-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts pku ospke spec_ctrl intel_stibp arch_capabilities
```

- Milvus version (master or released version)
0.8.0 cpu version

**Configuration file**
```yaml
apiVersion: v1
data:
  config.yml: |
    version: 0.3

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Server Config        | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # address              | IP address that Milvus server monitors.                    | IP         | 0.0.0.0         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # port                 | Port that Milvus server monitors. Port range (1024, 65535) | Integer    | 19530           |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # deploy_mode          | Milvus deployment type:                                    | DeployMode | single          |
    #                      |   single, cluster_readonly, cluster_writable               |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # time_zone            | Use UTC-x or UTC+x to specify a time zone.                 | Timezone   | UTC+8           |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # web_port             | Port that Milvus web server monitors.                      | Integer    | 19121           |
    #                      | Port range (1024, 65535)                                   |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    server_config:
      address: 0.0.0.0
      port: 19530
      deploy_mode: cluster_readonly
      time_zone: UTC+8
      web_port: 19121

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # DataBase Config      | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # backend_url          | URL for metadata storage, using SQLite (for single server  | URL        | sqlite://:@:/   |
    #                      | Milvus) or MySQL (for distributed cluster Milvus).         |            |                 |
    #                      | Format: dialect://username:password@host:port/database     |            |                 |
    #                      | Keep 'dialect://:@:/', 'dialect' can be either 'sqlite' or |            |                 |
    #                      | 'mysql', replace other texts with real values.             |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # preload_collection   | A comma-separated list of collection names that need to    | StringList |                 |
    #                      | be pre-loaded when Milvus server starts up.                |            |                 |
    #                      | '*' means preload all existing tables (single-quote or     |            |                 |
    #                      | double-quote required).                                    |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # auto_flush_interval  | The interval, in seconds, at which Milvus automatically    | Integer    | 1 (s)           |
    #                      | flushes data to disk.                                      |            |                 |
    #                      | 0 means disable the regular flush.                         |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    db_config:
      backend_url: mysql://root:milvusroot@milvus-mysql:3306/iht00xa
      preload_collection: "*"
      auto_flush_interval: 1

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Storage Config       | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # primary_path         | Primary directory used to save meta data, vector data and  | Path       | /var/lib/milvus |
    #                      | index data.                                                |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # secondary_path       | A semicolon-separated list of secondary directories used   | Path       |                 |
    #                      | to save vector data and index data.                        |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    storage_config:
      primary_path: /var/milvus/data
      secondary_path:

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Metric Config        | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # enable_monitor       | Enable monitoring function or not.                         | Boolean    | false           |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # address              | Pushgateway address                                        | IP         | 127.0.0.1       +
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # port                 | Pushgateway port, port range (1024, 65535)                 | Integer    | 9091            |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    metric_config:
      enable_monitor: false
      address: 127.0.0.1
      port: 9091

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Cache Config         | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # cpu_cache_capacity   | The size of CPU memory used for caching data for faster    | Integer    | 4 (GB)          |
    #                      | query. The sum of 'cpu_cache_capacity' and                 |            |                 |
    #                      | 'insert_buffer_size' must be less than system memory size. |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # insert_buffer_size   | Buffer size used for data insertion.                       | Integer    | 1 (GB)          |
    #                      | The sum of 'insert_buffer_size' and 'cpu_cache_capacity'   |            |                 |
    #                      | must be less than system memory size.                      |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # cache_insert_data    | Whether to load data to cache for hot query                | Boolean    | false           |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    cache_config:
      cpu_cache_capacity: 4
      insert_buffer_size: 1
      cache_insert_data: false

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Engine Config        | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # use_blas_threshold   | A Milvus performance tuning parameter. This value will be  | Integer    | 1100            |
    #                      | compared with 'nq' to decide if OpenBLAS should be used.   |            |                 |
    #                      | If nq >= use_blas_threshold, OpenBLAS will be used, search |            |                 |
    #                      | response time will be stable but the search speed will be  |            |                 |
    #                      | slower; if nq < use_blas_threshold, AVX or SSE will be     |            |                 |
    #                      | used, search speed will be faster but search response time |            |                 |
    #                      | will fluctuate.                                            |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # gpu_search_threshold | A Milvus performance tuning parameter. This value will be  | Integer    | 1000            |
    #                      | compared with 'nq' to decide if the search computation will|            |                 |
    #                      | be executed on GPUs only.                                  |            |                 |
    #                      | If nq >= gpu_search_threshold, the search computation will |            |                 |
    #                      | be executed on GPUs only;                                  |            |                 |
    #                      | if nq < gpu_search_threshold, the search computation will  |            |                 |
    #                      | be executed on both CPUs and GPUs.                         |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    engine_config:
      use_blas_threshold: 1100
      gpu_search_threshold: 1000

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # GPU Resource Config  | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # enable               | Enable GPU resources or not.                               | Boolean    | false           |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # cache_capacity       | The size of GPU memory per card used for cache.            | Integer    | 1 (GB)          |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # search_resources     | The list of GPU devices used for search computation.       | DeviceList | gpu0            |
    #                      | Must be in format gpux.                                    |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # build_index_resources| The list of GPU devices used for index building.           | DeviceList | gpu0            |
    #                      | Must be in format gpux.                                    |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    gpu_resource_config:
      enable: false
      cache_capacity: 1
      search_resources:
        - gpu0
      build_index_resources:
        - gpu0

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # Tracing Config       | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # json_config_path     | Absolute path for tracing config file.                     | Path       |                 |
    #                      | Leave it empty, a no-op tracer will be created.            |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    tracing_config:
      json_config_path:

    #----------------------+------------------------------------------------------------+------------+-----------------+
    # WAL Config           | Description                                                | Type       | Default         |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # enable               | Whether to enable write-ahead logging (WAL) in Milvus.     | Boolean    | true            |
    #                      | If WAL is enabled, Milvus writes all data changes to log   |            |                 |
    #                      | files in advance before implementing data changes. WAL     |            |                 |
    #                      | ensures the atomicity and durability for Milvus operations.|            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # recovery_error_ignore| Whether to ignore logs with errors that happens during WAL | Boolean    | true            |
    #                      | recovery. If true, when Milvus restarts for recovery and   |            |                 |
    #                      | there are errors in WAL log files, log files with errors   |            |                 |
    #                      | are ignored. If false, Milvus does not restart when there  |            |                 |
    #                      | are errors in WAL log files.                               |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # buffer_size          | Sum total of the read buffer and the write buffer in MBs.  | Integer    | 256 (MB)        |
    #                      | buffer_size must be in range [64, 4096] (MB).              |            |                 |
    #                      | If the value you specified is out of range, Milvus         |            |                 |
    #                      | automatically uses the boundary value closest to the       |            |                 |
    #                      | specified value. It is recommended you set buffer_size to  |            |                 |
    #                      | a value greater than the inserted data size of a single    |            |                 |
    #                      | insert operation for better performance.                   |            |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    # wal_path             | Location of WAL log files.                                 | String     |                 |
    #----------------------+------------------------------------------------------------+------------+-----------------+
    wal_config:
      enable: false
      recovery_error_ignore: true
      buffer_size: 256
      wal_path: /var/milvus/data/wal
  log.conf: |
    * GLOBAL:
        FORMAT                  =   "%datetime | %level | %logger | %msg"
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-global.log"
        ENABLED                 =   true
        TO_FILE                 =   true
        TO_STANDARD_OUTPUT      =   true
        SUBSECOND_PRECISION     =   3
        PERFORMANCE_TRACKING    =   false
        MAX_LOG_FILE_SIZE       =   209715200 ## Throw log files away after 200MB
    * DEBUG:
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-debug.log"
        ENABLED                 =   false
    * WARNING:
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-warning.log"
    * TRACE:
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-trace.log"
    * VERBOSE:
        FORMAT                  =   "%datetime{%d/%M/%y} | %level-%vlevel | %msg"
        TO_FILE                 =   true
        TO_STANDARD_OUTPUT      =   true
    ## Error logs
    * ERROR:
        ENABLED                 =   true
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-error.log"
    * FATAL:
        ENABLED                 =   true
        FILENAME                =   "/var/milvus/logs/milvus-ro-%datetime{%Y-%M-%d-%H}-fatal.log"
kind: ConfigMap
metadata:
  name: xxx
  namespace: xxx

```

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
