### ISSUE TITLE
[Bug]: miluvs task: non-zero exit (134)

### ISSUE THREAD

**Issue by hetao29** [milvus-io/milvus#35623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu 22.04.4
- CPU/Memory: 4cpu 16g
- GPU: 
- Others:
```

### Current Behavior

<img width="807" alt="image" src="https://github.com/user-attachments/assets/1c0358f1-5f17-4e2d-be14-1f930d3ce3a0">
<img width="321" alt="image" src="https://github.com/user-attachments/assets/b9de9a50-1a01-41ce-a57e-dd1a8888a017">

### Milvus Log

[milvus.log](https://github.com/user-attachments/files/16690299/milvus.log)

**Comment by xiaofan-luan** [comment]
134 seems to be a crash. 

Can you explain what kind of the traffic you are runing with?
Like if mmap enabled? if sparse embedding enabled? filters?

**Comment by hetao29** [comment]
1. traffic about 1-3 qps
2. host have 4cpu/16G memory, ubuntu 22.04
3. docker swarm version is 27.1.0, 3 nodes
4. from start to now, crash every many hours 
5. the only app is https://github.com/hetao29/reverse_image_search, /milvus/img/add interface
6. collection scheme is , defined in https://github.com/hetao29/reverse_image_search/blob/main/server/milvus_helpers.py
```python
fields = [
        FieldSchema(name="fileid", dtype=DataType.INT64, descrition="int64", is_primary=True),
        FieldSchema(name="vectors", dtype=DataType.FLOAT_VECTOR, descrition="float vector", dim=VECTOR_DIMENSION, is_primary=False),
        FieldSchema(name="itemid", dtype=DataType.INT64),
        FieldSchema(name="tags", dtype=DataType.ARRAY, element_type=DataType.VARCHAR, max_capacity=10, max_length=240),
        FieldSchema(name="brief", dtype=DataType.JSON)
        ]
schema = CollectionSchema(fields, description="collection description")
self.collection = Collection(name=collection_name, schema=schema)
LOGGER.debug(f"Create Milvus collection: {collection_name}")
```

**Comment by hetao29** [comment]
[milvus.2.log](https://github.com/user-attachments/files/16721455/milvus.2.log)

[milvus.log.zip](https://github.com/user-attachments/files/16721465/milvus.log.zip)

I found the **key error** in this milvus.2.log

```bash
sudo docker service logs milvus > milvus.log 2>milvus.2.log
```
```log
milvus.1.o8k81yr8eqry@online-23    | terminate called after throwing an instance of 'milvus::SegcoreError'
milvus.1.o8k81yr8eqry@online-23    |   what():  Error:RemoveDir:Directory not empty
milvus.1.o8k81yr8eqry@online-23    | SIGABRT: abort
milvus.1.o8k81yr8eqry@online-23    | PC=0x7f4cd16099fc m=376 sigcode=18446744073709551610
milvus.1.o8k81yr8eqry@online-23    | signal arrived during cgo execution
```

**Comment by hetao29** [comment]
I use the nfs version 4 volume, this is the part of docker-compose.yml
```yml
services:
  milvus:
    image: milvusdb/milvus:v2.4.8
    networks:
        - network
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - data_milvus:/var/lib/milvus
    depends_on:
      - "etcd"
      - "minio"
volumes:
  data_milvus:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.10.xx,rw,vers=4,minorversion=0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/data/milvus/data/milvus/"
```
