### ISSUE TITLE
[Bug]: Can't update the port

### ISSUE THREAD

**Issue by xiaobingxia-at** [milvus-io/milvus#36661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Hello, somehow my AWS EKS cluster doesn't allow the communication through ports >20000, so I need to change the the port number of each component. I have tried following ways:

1. Change the component config

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
    name: milvus-test-staging-s3
    namespace: starrocks-complex-query
    labels:
        app: milvus
spec:
    mode: cluster
    components:
        rootCoord:
            replicas: 1
            port: 13100
            resources:
                limits:
                    cpu: 2
                    memory: 8Gi
```

2. Change the config:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
    name: milvus-test-staging-s3
    namespace: starrocks-complex-query
    labels:
        app: milvus
spec:
    mode: cluster
    config:
        rootCoord:
            dmlChannelNum: 4
            maxDatabaseNum: 32
            maxGeneralCapacity: 100000
            port: 13100
```
            
Unfortunately, nothing works. the root coord still listens from 53100.
Does anyone know how to change the port of each component through k8s operator?

Thanks!

### Expected Behavior

After updating the port number at the k8s yaml file, root-coord should listen to the port I specified.
