### ISSUE TITLE
[Bug]: Setting the user name and password does not take effect.

### ISSUE THREAD

**Issue by wpx1997-stack** [milvus-io/milvus#36987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.4.13
```

### Current Behavior

When using Docker Compose for deployment, setting the username and password does not take effect. The Docker Compose configuration information is as follows:

```yaml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/milvus/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
#    ports:
#      - "9001:9001"
#      - "9000:9000"
    volumes:
      - /mnt/milvus/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.13
    restart: always
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    logging: 
      driver: "json-file"
      options: 
            max-size: "1g"
    volumes:
      - /mnt/milvus/volumes/milvus:/var/lib/milvus
      - /mnt/milvus/volumes/milvus/config/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4.8
    restart: always
    environment:
      MILVUS_URL: "192.168.1.141:19530"
    ports:
      - "3010:3000"
      
networks:
  default:  
    driver: bridge
  milvus:  
    external: true
```
The milvus.yaml sets the username and password as follows:
```yaml
  security:
    authorizationEnabled: true
    # The superusers will ignore some system check processes
    # like the old password verification when updating the credential
    superUsers: root
    defaultRootPassword: 1234 # default password for root user
    tlsMode: 0
```
When using Attu, I found that I cannot log in.
![image](https://github.com/user-attachments/assets/fa3dd76d-dc35-4265-a4fb-cf2121e3f908)

After entering the Docker container and checking the /milvus/configs/milvus.yaml file, I found that the settings have been successfully applied.
![image](https://github.com/user-attachments/assets/23410c14-6f58-4310-a977-af4ba7d50144)
