### ISSUE TITLE
[Bug]: Latency spikes were observed when deleting 60% entities during concurrent searches

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#37413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20241101-ce7d4090-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
```
  config:
    dataCoord:
      compaction:
        globnal:
          interval: 1
        taskPrioritizer: level
      enableActiveStandby: true
      segment:
        expansionRate: 1.15
        maxSize: 2048
        sealProportion: 0.12
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    minio:
      accessKeyID: xxx
      bucketName: bucket-zong
      rootPath: compact_2
      secretAccessKey: xx
    queryCoord:
      enableActiveStandby: true
    queryNode:
      levelZeroForwardPolicy: RemoteLoad
      streamingDeltaForwardPolicy: Direct
    quotaAndLimits:
      dml:
        deleteRate:
          max: 0.5
        enabled: true
        insertRate:
          max: 16
      limitWriting:
        deleteBufferRowCountProtection:
          enabled: true
          highWaterLevel: 6000000
          lowWaterLevel: 3000000
        deleteBufferSizeProtection:
          enabled: true
          highWaterLevel: 536870912
          lowWaterLevel: 134217728
        growingSegmentsSizeProtection:
          enabled: true
          highWaterLevel: 0.2
          lowWaterLevel: 0.1
          minRateRatio: 0.5
        l0SegmentsRowCountProtection:
          enabled: true
          highWaterLevel: 6000000
          lowWaterLevel: 5000000
        memProtection:
          dataNodeMemoryHighWaterLevel: 0.85
          dataNodeMemoryLowWaterLevel: 0.75
          queryNodeMemoryHighWaterLevel: 0.85
          queryNodeMemoryLowWaterLevel: 0.75
      limits:
        complexDeleteLimitEnable: true
    rootCoord:
      enableActiveStandby: true
    trace:
      exporter: jaeger
```
### test steps
1. delete 60m of 100m collection entities when concurrent search, concurrent user is 22
```
    concurrent_params:
      concurrent_number: 22
      during_time: '1h'
      interval: 20
    concurrent_tasks:
      -   
        type: search
        weight: 10
        params:
          nq: 10
          top_k: 100 
          #output_fields: ['int64_1']
          search_param:
            ef: 128 
          timeout: 600 
          random_data: false
```

### results
- proxy qps and avg, p99 search latency
![image](https://github.com/user-attachments/assets/21170a4c-43a1-4b38-8759-3d08cb47a1e1)
- qn mem usage
![image](https://github.com/user-attachments/assets/64bc3abf-40a0-4393-904d-d1a6f2b74da1)
- segcore search latency
![image](https://github.com/user-attachments/assets/c91cdbef-f547-45b3-aae6-03bd2e13181c)

[metrics of compact-opt-100m-2](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=compact-opt-100m-2&var-collection=All&var-app_name=milvus&from=1730694166600&to=1730698530314)
