### ISSUE TITLE
[Bug][Cluster][Kubernetes]: All Milvus nodes and coordinators are stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by SalBakraa** [milvus-io/milvus#37459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.13
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): pulsar/kafka
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): Ubuntu 24.10
- Linux Kernel: 6.11.0-9-generic 
- HOST CPU/Memory: AMD Ryzen Threadripper PRO 5995WX 64-Cores / 995 GiB
- VM CPU: QEMU Virtual CPU version 2.5+
- GPU: 2x Nvidia A6000
- Others:
```

### Current Behavior

Milvus Cluster fails to run on a Virtual Kubernetes Cluster. All milvus nodes and coordinators become stuck in CrashLoopBackOff state.

```
NAME                                             READY   STATUS             RESTARTS        AGE
my-release-etcd-0                                1/1     Running            0               21m
my-release-etcd-1                                1/1     Running            0               21m
my-release-etcd-2                                1/1     Running            0               21m
my-release-milvus-datacoord-d8c598b86-vdm8p      0/1     CrashLoopBackOff   7 (3m21s ago)   15m
my-release-milvus-datanode-6c9b95645f-rrl24      0/1     CrashLoopBackOff   7 (3m55s ago)   15m
my-release-milvus-indexcoord-694758d846-djgds    0/1     CrashLoopBackOff   7 (3m45s ago)   15m
my-release-milvus-indexnode-87c6cd97-8hjzv       0/1     CrashLoopBackOff   7 (3m40s ago)   15m
my-release-milvus-proxy-6cc57f7b7d-tlpdv         0/1     CrashLoopBackOff   7 (4m2s ago)    15m
my-release-milvus-querycoord-9b84c6974-ff4ss     0/1     CrashLoopBackOff   7 (3m30s ago)   15m
my-release-milvus-querynode-0-7485d47ffd-9v94m   0/1     CrashLoopBackOff   7 (3m51s ago)   14m
my-release-milvus-rootcoord-6746987cc4-d4xdp     0/1     CrashLoopBackOff   7 (3m44s ago)   15m
my-release-minio-0                               1/1     Running            0               21m
my-release-minio-1                               1/1     Running            0               21m
my-release-minio-2                               1/1     Running            0               21m
my-release-minio-3                               1/1     Running            0               21m
my-release-pulsar-bookie-0                       1/1     Running            0               21m
my-release-pulsar-bookie-1                       1/1     Running            0               21m
my-release-pulsar-bookie-2                       1/1     Running            0               21m
my-release-pulsar-bookie-init-qjg58              0/1     Completed          0               21m
my-release-pulsar-broker-0                       1/1     Running            0               21m
my-release-pulsar-proxy-0                        1/1     Running            0               21m
my-release-pulsar-pulsar-init-8zkqc              0/1     Completed          0               21m
my-release-pulsar-zookeeper-0                    1/1     Running            0               21m
my-release-pulsar-zookeeper-1                    1/1     Running            0               20m
my-release-pulsar-zookeeper-2                    1/1     Running            0               19m
```

### Expected Behavior

All milvus pods are Running and Ready.

### Steps To Reproduce

```markdown
1. Create the directory milvus-cluster and `cd` into it
2. Create the virtual machine images using `create_vm_images.sh`:
   
   #!/usr/bin/sh

   # Create image file for workers
   for i in $(seq 6); do
   	qemu-img create -f raw "worker_image_file_$i" 40G
   done

   # Create image file for master
   qemu-img create -f raw "master_image_file" 10G
   
3. download the ubuntu server iso into the *milvus-cluster* directory.
4. Install and prepare the virtual machines in the cluster using `setup_vms.sh`:
   ```sh
   #!/usr/bin/sh

   LOGIN_PASSWORD="$(mkpasswd password)"

   # Create ssh key to access the virtual machiens
   ssh-keygen -f ./ed25519_vm_key -t ed25519

   # mount the image
   mkdir mnt_iso
   sudo mount -o loop ./ubuntu-24.10-live-server-amd64.iso ./mnt_iso

   # Install os on worker nodes
   for i in $(seq 6); do
   	# Setup http server
   	mkdir -p ./www_$i

   	cat > ./www_$i/user-data << YAML
   #cloud-config
   autoinstall:
     version: 1

     # No interactive sections
     interactive-sections: []

     # default behavior
     locale: "en_US.UTF-8"

     # default behavior
     keyboard:
       layout: us
       variant: "dvorak"

     source:
       search_drivers: true

     storage:
       swap:
         size: 0
       layout:
         name: lvm
         sizing-policy: all

     ssh:
       install-server: true
       authorized-keys: []
       allow-pw: true

     codecs:
       install: true

     drivers:
       install: true

     # Updates from both the security and updates pockets are installed.
     updates: all

     # shutdown instead of reboot
     shutdown: poweroff

     packages:
         - ufw
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common
         - netcat-traditional
         - containerd
         - runc
         - nfs-common

     late-commands:
       # Allow all incoming and outgoing traffic in UFW
       - curtin in-target --target=/target -- echo "Configuring UFW to allow all traffic"
       - curtin in-target --target=/target -- /usr/sbin/ufw allow in on any
       - curtin in-target --target=/target -- /usr/sbin/ufw allow out on any
       - curtin in-target --target=/target -- /usr/sbin/ufw reload

       # System config
       - curtin in-target --target=/target -- echo "Disabling swap"
       - curtin in-target --target=/target -- /usr/sbin/swapoff -a
       - curtin in-target --target=/target -- sed -i '/ swap / s/^/#/' /etc/fstab
       - curtin in-target --target=/target -- rm -vf /swap.img

       # K8s Steps
       - curtin in-target --target=/target -- echo "Creating keyring directory if it does not exist"
       - curtin in-target --target=/target -- mkdir -p -m 755 /etc/apt/keyrings

       - curtin in-target --target=/target -- echo "Downloading Kubernetes signing key"
       - curtin in-target --target=/target -- sh -c '/usr/bin/curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'

       - curtin in-target --target=/target -- echo "Adding Kubernetes apt repository for v1.31"
       - curtin in-target --target=/target -- sh -c "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list"

       - curtin in-target --target=/target -- echo "Updating package index and installing Kubernetes components"
       - curtin in-target --target=/target -- apt-get update
       - curtin in-target --target=/target -- apt-get install -y kubelet kubeadm kubectl
       - curtin in-target --target=/target -- apt-mark hold kubelet kubeadm kubectl

       - curtin in-target --target=/target -- echo "Enabling kubelet service"
       - curtin in-target --target=/target -- systemctl enable kubelet
       - curtin in-target --target=/target -- echo "Loading required kernel modules"

       - |
         curtin in-target --target=/target -- sh -c 'cat <<EOF > /etc/modules-load.d/k8s.conf
         overlay
         br_netfilter
         EOF'

       - curtin in-target --target=/target -- echo "Setting sysctl parameters for Kubernetes"
       - |
         curtin in-target --target=/target -- sh -c 'cat <<EOF | tee /etc/sysctl.d/kubernetes.conf
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1
         net.ipv4.ip_forward = 1
         EOF'
       - curtin in-target --target=/target -- /usr/sbin/sysctl --system

       # Containerd stuff
       - curtin in-target --target=/target -- mkdir -p -m 755 /etc/containerd
       - curtin in-target --target=/target -- sh -c 'containerd config default | tee /etc/containerd/config.toml'
       - curtin in-target --target=/target -- systemctl enable containerd

       # Write netplan configuration file
       - curtin in-target --target=/target -- echo "Setting up netplan"
       - |
         curtin in-target --target=/target -- sh -c "cat <<EOF > /etc/netplan/01-netcfg.yaml
         network:
           version: 2
           ethernets:
             ens3:
               dhcp4: false
               dhcp6: false
               addresses:
                 - 192.168.2.$((2+$i))/24  # Static IP address
               routes:
                 - to: 0.0.0.0/0
                   via: 192.168.2.1  # Gateway
               nameservers:
                 addresses:
                   - 8.8.8.8  # Google DNS
                   - 8.8.4.4
         EOF"
       - curtin in-target --target=/target -- netplan apply

       # Add root user ssh keys
       - curtin in-target --target=/target -- mkdir -p -m 700 /root/.ssh
       - curtin in-target --target=/target -- sh -c 'echo $(cat ./ed25519_vm_key) > /root/.ssh/authorized_keys'

       # Allow password ssh
       - curtin in-target --target=/target -- sh -c 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config'

     user-data:
       disable_root: false
       chpasswd:
         expire: false
         list:
           - "root:password"

     ssh:
       install-server: true
       authorized-keys:
         - $(cat ./ed25519_vm_key)
       allow-pw: true

     identity:
       hostname: worker-node-$i
       username: user
       password: "$LOGIN_PASSWORD"
   YAML
   	touch ./www_$i/meta-data
   	cd ./www_$i
   		python3 -m http.server 300$((i+3)) 2>/dev/null 1>&2 &
   		{
   			qemu-system-x86_64 -no-reboot -m 64G \
   				-cdrom ../ubuntu-24.10-live-server-amd64.iso \
   				-boot order=d \
   				-drive file=../worker_image_file_$i,format=raw,cache=none,if=virtio \
   				-kernel ../mnt_iso/casper/vmlinuz \
   				-initrd ../mnt_iso/casper/initrd \
   				-append "autoinstall ds=nocloud-net;s=http://_gateway:300$(($i+3))/";
   			printf "Completed worker $i setup\n\n";
   			kill $(pgrep --full "python3 -m http.server 300$((i+3))");
   		} &
   	cd ..
   done

   # Install os on master node
   # Setup http server
   mkdir -p ./www
   cd ./www
   	python3 -m http.server 3003 2>/dev/null 1>&2 &
   cd ..
   cat > ./www/user-data << YAML
   #cloud-config
   autoinstall:
     version: 1

     # No interactive sections
     interactive-sections: []

     # default behavior
     locale: "en_US.UTF-8"

     # default behavior
     keyboard:
       layout: us
       variant: "dvorak"

     source:
       search_drivers: true

     storage:
       swap:
         size: 0
       layout:
         name: lvm
         sizing-policy: all

     ssh:
       install-server: true
       authorized-keys: []
       allow-pw: true

     codecs:
       install: true

     drivers:
       install: true

     # Updates from both the security and updates pockets are installed.
     updates: all

     # shutdown instead of reboot
     shutdown: poweroff

     packages:
         - ufw
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common
         - netcat-traditional
         - containerd
         - runc
         - nfs-common

     late-commands:
       # Allow all incoming and outgoing traffic in UFW
       - curtin in-target --target=/target -- echo "Configuring UFW to allow all traffic"
       - curtin in-target --target=/target -- /usr/sbin/ufw allow in on any
       - curtin in-target --target=/target -- /usr/sbin/ufw allow out on any
       - curtin in-target --target=/target -- /usr/sbin/ufw reload

       # System config
       - curtin in-target --target=/target -- echo "Disabling swap"
       - curtin in-target --target=/target -- /usr/sbin/swapoff -a
       - curtin in-target --target=/target -- sed -i '/ swap / s/^/#/' /etc/fstab
       - curtin in-target --target=/target -- rm -vf /swap.img

       # K8s Steps
       - curtin in-target --target=/target -- echo "Creating keyring directory if it does not exist"
       - curtin in-target --target=/target -- mkdir -p -m 755 /etc/apt/keyrings

       - curtin in-target --target=/target -- echo "Downloading Kubernetes signing key"
       - curtin in-target --target=/target -- sh -c '/usr/bin/curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'

       - curtin in-target --target=/target -- echo "Adding Kubernetes apt repository for v1.31"
       - curtin in-target --target=/target -- sh -c "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list"

       - curtin in-target --target=/target -- echo "Updating package index and installing Kubernetes components"
       - curtin in-target --target=/target -- apt-get update
       - curtin in-target --target=/target -- apt-get install -y kubelet kubeadm kubectl
       - curtin in-target --target=/target -- apt-mark hold kubelet kubeadm kubectl

       - curtin in-target --target=/target -- echo "Enabling kubelet service"
       - curtin in-target --target=/target -- systemctl enable kubelet
       - curtin in-target --target=/target -- echo "Loading required kernel modules"

       - |
         curtin in-target --target=/target -- sh -c 'cat <<EOF > /etc/modules-load.d/k8s.conf
         overlay
         br_netfilter
         EOF'

       - curtin in-target --target=/target -- echo "Setting sysctl parameters for Kubernetes"
       - |
         curtin in-target --target=/target -- sh -c 'cat <<EOF | tee /etc/sysctl.d/kubernetes.conf
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1
         net.ipv4.ip_forward = 1
         EOF'
       - curtin in-target --target=/target -- /usr/sbin/sysctl --system

       # Containerd stuff
       - curtin in-target --target=/target -- mkdir -p -m 755 /etc/containerd
       - curtin in-target --target=/target -- sh -c 'containerd config default | tee /etc/containerd/config.toml'
       - curtin in-target --target=/target -- systemctl enable containerd

       # Write netplan configuration file
       - curtin in-target --target=/target -- echo "Setting up netplan"
       - |
         curtin in-target --target=/target -- sh -c "cat <<EOF > /etc/netplan/01-netcfg.yaml
         network:
           version: 2
           ethernets:
             ens3:
               dhcp4: false
               dhcp6: false
               addresses:
                 - 192.168.2.2/24  # Static IP address
               routes:
                 - to: 0.0.0.0/0
                   via: 192.168.2.1  # Gateway
               nameservers:
                 addresses:
                   - 8.8.8.8  # Google DNS
                   - 8.8.4.4
         EOF"
       - curtin in-target --target=/target -- netplan apply

       # Add root user ssh keys
       - curtin in-target --target=/target -- mkdir -p -m 700 /root/.ssh
       - curtin in-target --target=/target -- sh -c 'echo $(cat ./ed25519_vm_key) > /root/.ssh/authorized_keys'

       # Allow password ssh
       - curtin in-target --target=/target -- sh -c 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config'

     user-data:
       disable_root: false
       chpasswd:
         expire: false
         list:
           - "root:password"

     ssh:
       install-server: true
       authorized-keys:
         - $(cat ./ed25519_vm_key)
       allow-pw: true

     identity:
       hostname: master-node
       username: user
       password: "$LOGIN_PASSWORD"
   YAML
   touch ./www/meta-data
   cd ./www
   	{
   		qemu-system-x86_64 -no-reboot -m 64G \
   			-cdrom ../ubuntu-24.10-live-server-amd64.iso \
   			-boot order=d \
   			-drive file=../master_image_file,format=raw,cache=none,if=virtio \
   			-kernel ../mnt_iso/casper/vmlinuz \
   			-initrd ../mnt_iso/casper/initrd \
   			-append 'autoinstall ds=nocloud-net;s=http://_gateway:3003/';
   		printf "Completed master setup\n\n";
   		kill $(pgrep --full "python3 -m http.server 3003");
   	} &
   cd ..

   wait
   sudo umount ./mnt_iso
   ```
5. Prepare the nfs server that will be user for the storage class using `setup_nfs_server.sh`:
   ```sh
   #!/usr/bin/sh

   mkdir -pv /srv/nfs/milvus-storage
   chmod 777 /srv/nfs/milvus-storage
   chown nobody:nogroup /srv/nfs/milvus-storage
   echo '/srv/nfs/milvus-storage 192.168.2.0/24(rw,sync,no_subtree_check)' >> /etc/exports
   exportfs -a
   ```
6. Start the cluster using `run_cluster.sh`:
   ```sh
   #!/usr/bin/sh

   # Setup the network

   # Create the tap devices
   tunctl -u user -t kmtap
   tunctl -u user -t kwtap1
   tunctl -u user -t kwtap2
   tunctl -u user -t kwtap3
   tunctl -u user -t kwtap4
   tunctl -u user -t kwtap5
   tunctl -u user -t kwtap6

   # Bring up the tap devices
   ip link set kmtap up
   ip link set kwtap1 up
   ip link set kwtap2 up
   ip link set kwtap3 up
   ip link set kwtap4 up
   ip link set kwtap5 up
   ip link set kwtap6 up

   # Create the bridge to link the tap devices
   brctl addbr kbr0
   brctl addif kbr0 kmtap
   brctl addif kbr0 kwtap1
   brctl addif kbr0 kwtap2
   brctl addif kbr0 kwtap3
   brctl addif kbr0 kwtap4
   brctl addif kbr0 kwtap5
   brctl addif kbr0 kwtap6

   # Bring up the bridge
   ip link set kbr0 up

   # Set an ip adddress to the bridge
   ifconfig kbr0 192.168.2.1 netmask 255.255.255.00 broadcast 192.168.2.255

   # Have a nat to allow the guest oses to acces the internet
   iptables -t nat -A POSTROUTING -o enp36s0f1 -j MASQUERADE
   iptables -I DOCKER-USER 1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
   iptables -I DOCKER-USER 2 -i kbr0 -o enp36s0f1 -j ACCEPT

   # setup port forwarding
   sysctl -w net.ipv4.ip_forward=1

   for i in $(seq 6); do
   	qemu-system-x86_64 -no-reboot -m 64G -smp cpus=18 -name “worker-$i” \
   		-nographic -serial none -monitor none \
   		-netdev tap,id=network0,ifname=kwtap$i,script=no,downscript=no \
   		-device virtio-net,netdev=network0,mac=de:ad:be:ef:00:0$i  \
   		-drive file=./worker_image_file_$i,format=raw,cache=none,if=virtio &
   done

   qemu-system-x86_64 -no-reboot -m 64G -smp cpus=12  -name “master” \
   	-nographic -serial none -monitor none \
   	-netdev tap,id=network0,ifname=kmtap,script=no,downscript=no \
   	-device virtio-net,netdev=network0,mac=de:ad:be:ef:00:00  \
   	-drive file=./master_image_file,format=raw,cache=none,if=virtio &

   # wait for all the machines to turn off
   wait

   # Disable the network

   # disable port forwarding
   sysctl -w net.ipv4.ip_forward=0

   # Disable the nat
   iptables -t nat -D POSTROUTING -o enp36s0f1 -j MASQUERADE
   iptables -D DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
   iptables -D DOCKER-USER -i kbr0 -o enp36s0f1 -j ACCEPT

   # Bring down the bridge
   ifconfig kbr0 down

   # Delete the bridge
   brctl delbr kbr0

   # Delete the tap devices
   tunctl -d kmtap
   tunctl -d kwtap1
   tunctl -d kwtap2
   tunctl -d kwtap3
   tunctl -d kwtap4
   tunctl -d kwtap5
   tunctl -d kwtap6
   ```
7. Finish the setup of the k8s cluster using kubeadm `setup_cluster.sh`:
   ```sh
   #!/usr/bin/sh
   # Remove the host keys form known_hosts
   for i in $(seq 2 8); do
   	ssh-keygen -R 192.168.2.$i
   	ssh -o StrictHostKeyChecking=no -i ./ed25519_vm_key "root@192.168.2.$i" "apt update && apt install -y nfs-common"
   done

   # Define the pod network CIDR
   POD_NETWORK_CIDR="10.244.0.0/16"

   # Initialize the Kubernetes cluster with the specified pod network CIDR
   JOIN_CMD="$(ssh -o StrictHostKeyChecking=no -i ./ed25519_vm_key "root@192.168.2.2" "kubeadm init --pod-network-cidr=${POD_NETWORK_CIDR}" 2>&1 | tail -n 2)"
   echo "join command = '$JOIN_CMD'"

   # Wait for the master node to initialize (optional)
   sleep 30  # Adjust sleep time as needed

   # Join worker nodes to the cluster
   for i in $(seq 3 8); do
       ssh -o StrictHostKeyChecking=no -i ./ed25519_vm_key "root@192.168.2.$i" "$JOIN_CMD"
   done

   # Copy admin.conf to the local machine for kubectl access
   sshpass -p password rsync -Pavhrz root@192.168.2.2:/etc/kubernetes/admin.conf .

   # Apply the Flannel CNI configuration
   kubectl --kubeconfig=./admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

   # # Optionally, restart the Flannel DaemonSet to ensure it picks up the correct settings
   # kubectl delete pods -n kube-flannel --all

   # get node status
   kubectl --kubeconfig=./admin.conf describe nodes
   kubectl --kubeconfig=./admin.conf get pods -n kube-flannel
   ```
8. Setup the milvus config `operator-milvus-config.yaml`:
   ```yaml
   # This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
   apiVersion: milvus.io/v1beta1
   kind: Milvus
   metadata:
     name: my-release
     namespace: milvus-workshop
     labels:
       app: milvus
   spec:
     mode: cluster
     dependencies:
       storage:
         external: false
         type: "MinIO"
         inCluster:
           deletionPolicy: Delete
           pvcDeletion: true
           values:
             persistence:
               size: 200Gi
       etcd:
         inCluster:
           deletionPolicy: Delete
           pvcDeletion: true
           values:
             autoCompactionMode: revision
             autoCompactionRetention: "1000"
             extraEnvVars:
             - name: ETCD_QUOTA_BACKEND_BYTES
               value: "4294967296"
             - name: ETCD_HEARTBEAT_INTERVAL
               value: "500"
             - name: ETCD_ELECTION_TIMEOUT
               value: "25000"
             - name: ETCD_SNAPSHOT_COUNT
               value: "10000"
             - name: ETCD_ENABLE_PPROF
               value: "true"
             persistence:
               accessMode: ReadWriteOnce
               enabled: true
               size: 30Gi   #SSD Required
               storageClass:
             replicaCount: 3
             resources:
               limits:
                 cpu: 2
                 memory: 4Gi
               requests:
                 cpu: 2
                 memory: 4Gi
       pulsar:
         inCluster:
           deletionPolicy: Delete
           pvcDeletion: true
           values:
             components:
               autorecovery: false
             zookeeper:
               volumes:
                 data:
                   size: 20Gi
             bookkeeper:
               volumes:
                 useSingleCommonVolume: true
                 common:
                   size: 50Gi
             proxy:
               resources:
                 requests:
                   memory: 10Gi
                   cpu: 4
     components:
       resources:
         limits:
           cpu: 4
           memory: 8Gi
         requests:
           cpu: 4
           memory: 8Gi
       dataCoord:
         replicas: 1
       dataNode:
         replicas: 1
       indexCoord:
         replicas: 1
       indexNode:
         replicas: 1
       proxy:
         replicas: 1
         serviceType: LoadBalancer
       queryCoord:
         replicas: 1
       queryNode:
         replicas: 1
       rootCoord:
         replicas: 1
     config: {}
   ```
9. Finally install and setup the milvus cluster using `install_milvus.sh`
   ```sh
   #!/usr/bin/sh

   # Setup nfs storage class
   helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
   helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server=192.168.2.1 --set nfs.path=/srv/nfs/milvus-storage

   kubectl patch storageclass nfs-client -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class":"true"}}}'

   # install cert manager
   kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml

   # install milvus operator
   helm install milvus-operator -n milvus-operator --create-namespace --wait --wait-for-jobs https://github.com/zilliztech/milvus-operator/releases/download/v1.0.1/milvus-operator-1.0.1.tgz

   # setup milvus cluster
   kubectl create namespace milvus-workshop
   kubectl apply -f operator-milvus-config.yaml -n milvus-workshop
   ```
```


### Milvus Log

using the `export-milvus-log.sh` the logs are here: 
[logs.tar.gz](https://github.com/user-attachments/files/17633965/logs.tar.gz)


### Anything else?

the logs show the same error as #28242
