### ISSUE TITLE
The file showed in result of get_collection_stats cannot be found in db path

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3756]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
create ivf_flat index , and get_collection_stats, the part files shown bellow: 
```
{'data_size': 213956198,
                               'files': [{'data_size': 3204100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_57/P_57/S_45031/F_180230'},
                                         {'data_size': 2211260,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_57/P_57/S_45031/F_180233'},
                                         {'data_size': 0,
                                          'field': '_id',
                                          'name': '_del',
                                          'path': '/C_57/P_57/S_45031/F_180232'},
                                         {'data_size': 204804100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_57/P_57/S_45031/F_180231'},
                                         {'data_size': 3736738,
                                          'field': 'float_vector',
                                          'index_type': 'IVF_FLAT',
                                          'name': '',
                                          'path': '/C_57/P_57/S_45031/F_180250'}],
                               'id': 45031,
                               'row_count': 400000}],
                 'tag': '_default'}],
```
the db files shown bellow, file `F_180232` cannot be found
```
zong@zong-System-Product-Name:~/milvus/db$ cd collections/C_57/P_57/S_45031/
zong@zong-System-Product-Name:~/milvus/db/collections/C_57/P_57/S_45031$ ll
total 208972
drwxr-xr-x  2 root root      4096 9月  15 18:05 ./
drwxr-xr-x 19 root root     12288 9月  15 18:05 ../
-rw-r--r--  1 root root   3204100 9月  15 18:04 F_180230
-rw-r--r--  1 root root 204804100 9月  15 18:04 F_180231
-rw-r--r--  1 root root   2211260 9月  15 18:04 F_180233.blf
-rw-r--r--  1 root root   3736738 9月  15 18:05 F_180250.idx
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
build_performance:
  collections:
    -
      server:
        db_config.primary_path: /test/milvus/db_data_011/sift_50m_100000_128_l2_ivf_flat
        cache_config.cpu_cache_capacity: 8GB
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 1
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
          - gpu2
          - gpu3
      collection_name: sift_10m_100000_128_l2
      index_type: ivf_flat
      index_param:
        nlist: 1024
```

**Screenshots**

**Additional context**
