### ISSUE TITLE
[Bug]: A deleted vector appears again when restarting milvus standalone container

### ISSUE THREAD

**Issue by prodriguezu** [milvus-io/milvus#37782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.15
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I delete a vector entity and an internal milvus process seals a segment and store the bin logs in object storage (minio) if I restart the milvus standalone container. The deleted vector appears again in the collection.

Next, I describe the steps follow. I'm able to reproduce it using Attu interface and using pymilvus client. I'll show the example using Attu so as the process can be easily follow.

1) Adding two vectors to collection.
    - Vectors in collection: 
      ![Screenshot from 2024-11-18 12-11-41](https://github.com/user-attachments/assets/17dd32b1-e057-44b6-81a8-fbba74b4c632)
    - No segments created
      ![Screenshot from 2024-11-18 12-10-13](https://github.com/user-attachments/assets/d0784da5-e37b-4718-95a1-98ed745707d9)
   - Object storage empty so far
     
![Screenshot from 2024-11-18 12-09-52](https://github.com/user-attachments/assets/4d34d8e2-324e-486d-a146-399e51d235d3)
  
 2) Remove one of them
   - Vectors in collection:
     ![Screenshot from 2024-11-18 12-10-27](https://github.com/user-attachments/assets/78af504c-d60a-4bfa-b9c3-0e862bc99f4c)

3) Wait for normal functioning. Internal milvus task generate bin logs in minio. I've inspected the content of the delta log folder and the pk identifier of the deleted vector.
   - milvus logs at the time of saving the bin logs
     ![Screenshot from 2024-11-18 12-11-21](https://github.com/user-attachments/assets/fc6d873d-5fad-4f97-aec0-f6d10639c2b6)
   - object storage folder
     ![Screenshot from 2024-11-18 12-18-11](https://github.com/user-attachments/assets/530158ab-fdfe-40cf-a4dd-0ae1c5509814)
 
4) Restarting the milvus standalone container and inspecting the data within the collection gives the two original vectors including the one removed.

If after deletion I do apply a flush operation this behavior is not happening. Removed vectors do not appear again after restarting the containers.I must say that after flushing manually the segments partition id identifiers differ from when the flush is automatic. Check this image out.

![Screenshot from 2024-11-18 12-31-11](https://github.com/user-attachments/assets/5fb238f5-7c8e-435e-b5d8-5b8fa6fd252f)

### Expected Behavior

I'd have expected that deleting a vector will be consistent at the event of restarting milvus standalone container. From documentation it not easy to extract whether we must perform a flush operation after deleting entities. In fact, I guess that sealing segments too often could lead to performance degradation if many low size segments are created.

### Steps To Reproduce

```markdown
1. Create a collection and add two entities.
2. Remove one of them.
3. Wait milvus for internal operation to store logs in object storage.
4. Restart milvus-standalone container.
```

### Anything else?

I've been able to keep a vector gone from the system in a consistent manner if I apply a flush of the collection after deleting a vector. Is this something expected? I mean, it is mandatory to flush to permanently delete vector entities?

Many thanks in advance!

**Comment by yanliang567** [comment]
@prodriguezu thank you for the detailed info of the issue. quick questions:
1. how do you deploy and restart milvus-standalone container?
2. what about if doing a flush after restart the milvus? does it reproduce the issue?
/assign @prodriguezu 

/assign @aoiasd  
please help to take a look, does it mean the MQ did not persist the delete request?

**Comment by prodriguezu** [comment]
Thanks @yanliang567 for the quick answer.

> how do you deploy and restart milvus-standalone container?

This is the configuration of the docker compose file with all components related with milvus:
```yaml
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.15
    command: [ "milvus", "run", "standalone" ]
    environment:
        ETCD_ENDPOINTS: etcd:2379
        MINIO_ADDRESS: minio:9000
    ports:
        - "19530:19530"
        - "9091:9091"
    depends_on:
        - etcd
        - minio
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://milvus-standalone:9091/healthz" ]
        interval: 30s
        start_period: 90s
        timeout: 20s
        retries: 3
    deploy:
        resources:
            limits:
                memory: 8G
    networks:
        - vcspnet
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
        - vcspnet
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
        - vcspnet
  attu:
    container_name: attu
    image: zilliz/attu:v2.3.10
    ports:
        - "3001:3000"
    environment:
        - MILVUS_URL=milvus-standalone:19530
    restart: always
    depends_on:
        - milvus-standalone
    networks:
        - vcspnet
```

I just restart the milvus-standalone docker with docker command : `docker restart milvus-standalone`.

I must say that this occurred also in a cluster k8s deployment and I just reproduced it locally with standalone deployment by following the described steps.

> what about if doing a flush after restart the milvus? does it reproduce the issue?

After restarting milvus container, if I apply a flush over the collection indeed, the deleted vector disappears from the collection (the expected behavior). But, does it means that if a restart of a container or a pod in k8s we do need to flush all the collections programatically?

Thanks again for your support!
