### ISSUE TITLE
Segments of collection stats do not match expectations

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3779]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The total count of collection is 10m(million), and the parameter segment_row_limit is 2m, the count of each insert is 50000, but the segments of collection stats are:
```
{'data_size': 960342989,
 'partition_count': 1,
 'partitions': [{'data_size': 960342989,
                 'id': 60,
                 'row_count': 10000000,
                 'segment_count': 6,
                 'segments': [{'data_size': 1067045760,
                               'files': [{'data_size': 16004100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68554/F_274416'},
                                         {'data_size': 11033460,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68554/F_274420'},
                                         {'data_size': 1024004100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68554/F_274417'},
                                         {'data_size': 16004100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68554/F_274418'}],
                               'id': 68554,
                               'row_count': 2000000},
                              {'data_size': 1067045760,
                               'files': [{'data_size': 16004100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68627/F_274781'},
                                         {'data_size': 11033460,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68627/F_274785'},
                                         {'data_size': 1024004100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68627/F_274782'},
                                         {'data_size': 16004100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68627/F_274783'}],
                               'id': 68627,
                               'row_count': 2000000},
                              {'data_size': 1067045760,
                               'files': [{'data_size': 16004100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68696/F_275126'},
                                         {'data_size': 11033460,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68696/F_275130'},
                                         {'data_size': 1024004100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68696/F_275127'},
                                         {'data_size': 16004100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68696/F_275128'}],
                               'id': 68696,
                               'row_count': 2000000},
                              {'data_size': 1093721456,
                               'files': [{'data_size': 16404100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68769/F_275491'},
                                         {'data_size': 11309156,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68769/F_275495'},
                                         {'data_size': 1049604100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68769/F_275492'},
                                         {'data_size': 16404100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68769/F_275493'}],
                               'id': 68769,
                               'row_count': 2050000},
                              {'data_size': 880315904,
                               'files': [{'data_size': 13204100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68826/F_275776'},
                                         {'data_size': 9103604,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68826/F_275780'},
                                         {'data_size': 844804100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68826/F_275777'},
                                         {'data_size': 13204100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68826/F_275778'}],
                               'id': 68826,
                               'row_count': 1650000},
                              {'data_size': 160072172,
                               'files': [{'data_size': 2404100,
                                          'field': '_id',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68835/F_275821'},
                                         {'data_size': 1659872,
                                          'field': '_id',
                                          'name': '_blf',
                                          'path': '/C_60/P_60/S_68835/F_275825'},
                                         {'data_size': 153604100,
                                          'field': 'float_vector',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68835/F_275822'},
                                         {'data_size': 2404100,
                                          'field': 'int64',
                                          'name': '_raw',
                                          'path': '/C_60/P_60/S_68835/F_275823'}],
                               'id': 68835,
                               'row_count': 300000}],
                 'tag': '_default'}],
 'row_count': 10000000}
```
**Steps/Code to reproduce behavior**
insert yaml:
```
insert_performance:
  collections:
     -
       server:
         db_config.primary_path: /test/milvus/db_data_011/sift_10m_2000000_128_l2
         cache_config.cpu_cache_capacity: 4GB
         engine_config.use_blas_threshold: 1100
         engine_config.gpu_search_threshold: 1
         gpu_resource_config.enable: true
         gpu_resource_config.cache_capacity: 4GB
         gpu_resource_config.search_resources:
           - gpu0
           - gpu1
         gpu_resource_config.build_index_resources:
           - gpu0
           - gpu1
         wal_enable: true
       collection_name: sift_10m_2000000_128_l2
       other_fields: int,float
       ni_per: 50000
       build_index: false
       index_type: ivf_sq8
       index_param:
         nlist: 1024
```
command:
```
python3 main.py --local --host='192.168.1.x' --port=19530 --suite=suites/011_insert_data.yaml
```
**Expected behavior**
total 5(10m/2m) segments and every segment row_count is 2m

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
cache:
  cache_size: 6GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: true
  cache_size: 6GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
```

**Screenshots**

**Additional context**
