### ISSUE TITLE
milvus admin not working in k8s cluster

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3795]
Installed milvus in k8s with helm chart 
https://github.com/milvus-io/milvus-helm/tree/master/charts/milvus

I am putting up relevant values for milvus admin (I also tested with image milvusdb/milvus-em, version: v0.4.0)
```
admin:
  enabled: true
  image:
    repository: milvusdb/milvus-admin
    tag: v0.3.0
    pullPolicy: IfNotPresent

  replicas: 1
  resources:
    limits:
      memory: "4Gi"
      cpu: "1.0"
    requests:
      memory: "4Gi"
      cpu: "1.0"
  service:
    type: ClusterIP
    port: 3000
    annotations: {}
    labels: {}
    externalIPs: []
    #   - externalIp1

    loadBalancerSourceRanges:
    - 0.0.0.0/0
    # Optionally assign a known public LB IP
    # loadBalancerIP: 1.2.3.4
```

I am getting following statements in milvus admin logs & cannot view admin UI if I port forward to 3000 port

```
x.x.x.x - - [17/Sep/2020:12:08:52 +0000] "GET / HTTP/1.1" 200 1184 "-" "kube-probe/1.16+" "-"
x.x.x.x - - [17/Sep/2020:12:09:07 +0000] "GET / HTTP/1.1" 200 1184 "-" "kube-probe/1.16+" "-"
x.x.x.x - - [17/Sep/2020:12:09:16 +0000] "GET / HTTP/1.1" 200 1184 "-" "kube-probe/1.16+" "-"
x.x.x.x - - [17/Sep/2020:12:09:22 +0000] "GET / HTTP/1.1" 200 1184 "-" "kube-probe/1.16+" "-"
x.x.x.x - - [17/Sep/2020:12:09:31 +0000] "GET / HTTP/1.1" 200 1184 "-" "kube-probe/1.16+" "-"
```
