### ISSUE TITLE
The search time  of a dsl query is much longer than only vector query

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3808]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
collection info:
```
{'fields': [{'field': 'float_vector', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}, 'indexes': [{'index_type': 'IVF_SQ8_HYBRID', 'metric_type': 'L2', 'params': {'nlist': 1024}}]}, {'field': 'int64', 'type': <DataType.INT64: 5>, 'params': {}, 'indexes': [{}]}, {'field': 'float', 'type': <DataType.FLOAT: 10>, 'params': {}, 'indexes': [{}]}], 'auto_id': False, 'segment_row_limit': 2000000}
```
1. search just with vectors
```
    query = {"bool": {"must": [
        {"vector": {"float_vector": {
        "topk": 10,
        "query": [],
        "metric_type": "L2",
        "params": {}
        }}}
    ]}}
```
2. search with dsl query:
```
    query = {"bool": {"must": [
        {"vector": {"float_vector": {
        "topk": topk,
        "query": [],
        "metric_type": "L2",
        "params": {}
        }}},
        {"range": {"int64": {
            "LT": 0,
            "GT": 8000000
        }}},
        {"term": {"float": {
            "values": [float(i) for i in range(collection_size // 2)]
        }}}
    ]}}
```
3. search time

a. vector-only nprobe = 8

|      Nq/Top-k       |1          |10        | 100      | 1000    |
|:------------|:--------:|:--------:|:--------:|:-------:|
| 1   |        0.03 |       0.03 |        0.05 |        0.03 |
|          10 |        0.05 |       0.04 |      0.04 |        0.05 |
|         100 |        0.11 |        0.12 |        0.13 |        0.14 |
|        1000 |        0.46 |        0.49 |        0.48 |        0.68 |
|        1200 |        0.53 |        0.53 |        0.55 |         0.8 |

b. vector-only nprobe = 32

Nq/Top-k | 1 | 10 | 100 | 1000
|--|--|--|--|--|
1 | 0.03 | 0.04 | 0.03 | 0.07
10 | 0.07 | 0.07 | 0.07 | 0.07
100 | 0.31 | 0.3 | 0.31 | 0.35
1000 | 1.28 | 1.29 | 1.31 | 1.62
1200 | 1.52 | 1.53 | 1.57 | 1.93

c. dsl search nprobe = 8

Nq/Top-k | 1 | 10 | 100 | 1000
-- | -- | -- | -- | --
1 | 6.42 | 6.23 |       6.27 |        6.21 | 
10 | 6.27 | 6.13 |     6.2 |        6.22 | 
100 | 6.22 | 6.24 |        6.29 |        6.25 |
1000 | 6.56 | 6.53 | 6.57 | 6.74 |
1200 | 6.61 |  6.62 |        6.63 |        6.82 |

d. dsl search nprobe = 32

Nq/Top-k | 1 | 10 | 100 | 1000
-- | -- | -- | -- | --
1 | 6.18 | 6.2 |       6.18 |        6.2 | 
10 | 6.15 | 6.2 |     6.19 |        6.18 | 
100 | 6.24 | 6.22 |        6.25 |        6.26 |
1000 | 7.33 | 7.39 | 7.38 | 7.58 |
1200 | 7.58 |  7.7 |        7.69 |        7.85 |

**Steps/Code to reproduce behavior**
1. create a collection with fields
```
     -
       server:
         db_config.primary_path: /test/milvus/db_data_011/filter/sift_10m_2000000_128_l2
         cache_config.cpu_cache_capacity: 4GB
         engine_config.use_blas_threshold: 1100
         engine_config.gpu_search_threshold: 1
         gpu_resource_config.enable: true
         gpu_resource_config.cache_capacity: 4GB
         gpu_resource_config.search_resources:
           - gpu0
           - gpu1
         gpu_resource_config.build_index_resources:
           - gpu0
           - gpu1
         wal_enable: true
       collection_name: sift_10m_2000000_128_l2
       other_fields: int,float
       ni_per: 50000
       build_index: false
       index_type: ivf_sq8
       index_param:
         nlist: 1024
```
2. build index ivf_sq8h
```
    -
      server:
        db_config.primary_path: /test/milvus/db_data_011/filter/sift_10m_2000000_128_l2_sq8h
        cache_config.cpu_cache_capacity: 8GB
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 100
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
          - gpu2
          - gpu3
      collection_name: sift_10m_2000000_128_l2
      index_type: ivf_sq8h
      index_param:
        nlist: 1024
```
3. search with vector-only or dsl
```
    -
      server:
        db_config.primary_path: /test/milvus/db_data_011/filter/sift_10m_2000000_128_l2_sq8h
        cache_config.cpu_cache_capacity: 32GB
        engine_config.use_blas_threshold: 0
        engine_config.gpu_search_threshold: 100
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
        wal_enable: true
      collection_name: sift_10m_2000000_128_l2
      run_count: 2
      top_ks: [1, 10, 100, 1000]
      nqs: [1, 10, 100, 1000, 1200]
```

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
"cache.cache_size":"6GB"
"gpu.cache_size":"6GB"
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
collection size is 10m.
1. only range:
```
filter_query = [
                 {"range": {"int64": {
                     "LT": 0,
                     "GT": 5000000
                 }}}]
```
Nq/Top-k | 1 | 10 | 100 | 1000
-- | -- | -- | -- | --
1 | 0.26 |    0.26 |  0.26 |   0.26 | 
10 | 0.33 |   0.26 |  0.29 |   0.32 | 
100 | 0.24 |  0.26 |  0.26 |   0.27 |
1000 | 1.36 | 1.32 |  1.36 |   1.55 |
1200 | 1.59 | 1.58 |  1.58 |   1.79 |

2. only term:
```
filter_query = [
                {"term": {"float": {
                    "values": [float(i) for i in range(collection_size // 2)]
                }}}
            ]
```
Nq/Top-k | 1 | 10 | 100 | 1000
-- | -- | -- | -- | --
1 | 6.12 |    6.14 |  6.13 |   6.11 | 
10 | 6.14 |   6.14 |  6.12 |   6.12 | 
100 | 6.18 |  6.22 |  6.24 |   6.25 |
1000 | 7.49 | 7.48 |  7.42 |   7.58 |
1200 | 7.76 | 7.66 |  7.7 |   7.86 |

**Comment by JinHai-CN** [comment]
Need to re-test it.

**Comment by ThreadDao** [comment]
The problem remains.
Term filters half of the collection data 
```
      collection_name: sift_10m_2000000_128_l2
      run_count: 2
      top_ks: [1, 10, 100, 1000]
      nqs: [1, 10, 100, 1000, 1200]
      filters:
       -
         term: "{'term': {'float': {'values': [float(i) for i in range(collection_size // 2)]}}}"
      search_params:
        -
          nprobe: 32
```
```
2020-09-27 18:30:16,485 - milvus_benchmark.local_runner - INFO - Search param: {"nprobe": 32}
╭─────────────┬─────────────┬─────────────┬─────────────┬─────────────╮
│  Nq/Top-k   │      1      │     10      │     100     │    1000     │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           1 │        6.15 │        6.15 │        6.16 │        6.11 │
│          10 │         6.1 │        6.09 │        6.11 │        6.11 │
│         100 │        6.24 │        6.25 │        6.31 │        6.31 │
│        1000 │        7.26 │        7.23 │        7.29 │        7.57 │
│        1200 │        7.52 │        7.54 │        7.57 │        7.87 │
╰─────────────┴─────────────┴─────────────┴─────────────┴─────────────╯

```
