### ISSUE TITLE
[Bug]: State not loaded when moving volumes directory to new machine (milvus standalone using docker compose)

### ISSUE THREAD

**Issue by cdalinghaus** [milvus-io/milvus#38189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.13-hotfix
- Deployment mode(standalone or cluster): standalone, docker compose
- MQ type(rocksmq, pulsar or kafka):    /
- SDK version(e.g. pymilvus v2.0.0rc2): / 
- OS(Ubuntu or CentOS): ubuntu 24.04 LTS
- CPU/Memory: Varied, x64
- GPU: /
- Others: /
```

### Current Behavior

Using the docker compose file [provided from the documentation](https://milvus.io/docs/install_standalone-docker.md), milvus works properly and saves its data to the volumes directory, which grows to substantial size.

However, when the multi-container application is stopped and the entire folder is moved to a different machine, milvus does NOT recognize the previous state and starts from an empty collection instead.

So I guess there must be some location on the host that milvus is using, which is not correctly mapped to the volumes directory, given the provided milvus docker compose configuration.

docker-compose.yml
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: REDACTED
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.13-hotfix
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
        #ports:
        #- "19530:19530"
        #- "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

(.. other containers)

networks:
  default:
    name: milvus
```

### Expected Behavior

Move / back up volumes directory to recover state

### Steps To Reproduce

```markdown
1. Deploy milvus using the developer-provided docker compose configuration
2. Create collection, write some data
3. Shut down application
4. Move to new machine
5. Build and start
6. Observe that the previous state is fully missing
```
