### ISSUE TITLE
[Bug]: Milvus is not able to index 100M data with DISKANN

### ISSUE THREAD

**Issue by piyatu** [milvus-io/milvus#38459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.x
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    i think pulsar(not sure) 
- SDK version(e.g. pymilvus v2.0.0rc2):  
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: m6gd.8xlarge - 32 cores, 128 GB
- GPU: 
- Others:
```

### Current Behavior

Hi I have installed Milvus on a single node on aws machine linux, 32vcpu, 128 GB RAM, using Docker [https://milvus.io/docs/v2.4.x/install_standalone-docker.md](url)

I have provided the NVME SSD Disk of 1.8 TB

this is the memory is seen after the run using df -h :

```Filesystem                  Size  Used Avail Use% Mounted on
devtmpfs                     62G     0   62G   0% /dev
tmpfs                        62G     0   62G   0% /dev/shm
tmpfs                        62G  616K   62G   1% /run
tmpfs                        62G     0   62G   0% /sys/fs/cgroup
/dev/nvme0n1p1               32G  4.7G   28G  15% /
/dev/nvme0n1p128             10M  3.8M  6.2M  38% /boot/efi
/dev/mapper/vg-cb_data_ebs  1.8T  115G  1.7T   7% /data
tmpfs                        13G     0   13G   0% /run/user/0
overlay                      32G  4.7G   28G  15% /var/lib/docker/overlay2/2a3456789
overlay                      32G  4.7G   28G  15% /var/lib/docker/overlay2/3e6785345q```

In /data (NVME SSD) directory, i have created 3 folders minio, milvus, etcd

My docker-compose.yml looks like this :
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - /data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.17
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /root/milvus.yaml:/milvus/configs/milvus.yaml
      - /data/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

I have downloaded the milvus.yaml file as per documentation but not changed any configuration except queryNode.enableDisk:true

DISKANN configuration:
```
DiskIndex:
    MaxDegree: 56
    SearchListSize: 100
    PQCodeBudgetGBRatio: 0.125
    BuildNumThreadsRatio: 1
    SearchCacheBudgetGBRatio: 0.1
    LoadNumThreadRatio: 8
    BeamWidthRatio: 4
```


I am building index using 
```
        collection.create_index(
        field_name="emb",
        index_params={
            "index_type": "DISKANN",  # Index type
            "metric_type": "L2"    # Distance metric
        },
        sync = True,
        index_name="vector_index",
        )
        ```
        
        I have added sync=True parameter so that only after building index, it will move to next line of code. After execution i was not able to connect to node. So then, i down the docker and again up the docker  and tried to get info about the index :
        
        Using describe        
         index = client.describe_index(
            collection_name="demo10",
            index_name="vector_index"    
        )
        print(index)
        
{'index_type': 'DISKANN', 'metric_type': 'L2', 'field_name': 'emb', 'index_name': 'vector_index', 'total_rows': 100000000, 'indexed_rows': 100000000, 'pending_index_rows': 69900000, 'state': 'Finished'}

As we can see index creation state is Finished but still 69900000 rows are pending. 
1. This is a bug if its not indexed then it should throw an error as my previous tests are all not of no-use.
2. How can i tune the memory or configuration file to index using DISKANN.

Thanks





### Expected Behavior

There should be guidance or some calculation in documentation to set the parameters as required, as there are multiple parameters to set to get better performance. I need the solution to index 100M using DISKANN successfully.

### Steps To Reproduce

```markdown
I have stated all above as well mostly

1. Make 32 vcpu, 128 GB machine - m6gd.8xlarge.
2. Give /data dir 1.7 TB memory.
3. Created 3 folders - etcd, milvus, minio.
4. Installed milvus with docker-compose with provided doc and milvus file, my docker file is provided for ref. Changed query.enableDisk:true
5. Load 100M data
6. create index on 100M data using DISKANN with default config. 
7. you will see in approx 4 hours its not been indexed
```

**Comment by piyatu** [comment]
Please specify if any issue related to
how can i change the config related to memory or index for mivus-standalone - single node only. using docker 
if any change in config

I am ok with any initial number for 100M but not default.

**Comment by foxspy** [comment]
Can provide some indexing logs? You can search for `IndexNode` or `KNOWHERE` keywords

**Comment by piyatu** [comment]
Hi @foxspy I was unable to find it. 


Also I tried changing the config file yesterday after this issue like 

```
queryNode:
  stats:
    publishInterval: 1000 # The interval that query node publishes the node statistics information, including segment status, cpu usage, memory usage, health status, etc. Unit: ms.
  segcore:
    knowhereThreadPoolNumRatio: 4 # The number of threads in knowhere's thread pool. If disk is enabled, the pool size will multiply with knowhereThreadPoolNumRatio([1, 32]).
    chunkRows: 128 # Row count by which Segcore divides a segment into chunks.
    interimIndex:
      # Whether to create a temporary index for growing segments and sealed segments not yet indexed, improving search performance.
      # Milvus will eventually seals and indexes all segments, but enabling this optimizes search performance for immediate queries following data insertion.
      # This defaults to true, indicating that Milvus creates temporary index for growing segments and the sealed segments that are not indexed upon searches.
      enableIndex: true
      nlist: 128 # temp index nlist, recommend to set sqrt(chunkRows), must smaller than chunkRows/8
      nprobe: 16 # nprobe to search small index, based on your accuracy requirement, must smaller than nlist
      memExpansionRate: 1.15 # extra memory needed by building interim index
      buildParallelRate: 0.5 # the ratio of building interim index parallel matched with cpu num
    knowhereScoreConsistency: false # Enable knowhere strong consistency score computation logic
  loadMemoryUsageFactor: 1 # The multiply factor of calculating the memory usage while loading segments
  enableDisk: true # enable querynode load disk index, and search on disk index
  maxDiskUsagePercentage: 95
  cache:
    memoryLimit: 21474836480 # 2 GB, 2 * 1024 *1024 *1024
    readAheadPolicy: willneed # The read ahead policy of chunk cache, options: `normal, random, sequential, willneed, dontneed`
    # options: async, sync, disable. 
    # Specifies the necessity for warming up the chunk cache. 
    # 1. If set to "sync" or "async" the original vector data will be synchronously/asynchronously loaded into the 
    # chunk cache during the load process. This approach has the potential to substantially reduce query/search latency
    # for a specific duration post-load, albeit accompanied by a concurrent increase in disk usage;
    # 2. If set to "disable" original vector data will only be loaded into the chunk cache during search/query.
    warmup: disable
  mmap: 
    vectorField: true # Enable mmap for loading vector data
    vectorIndex: true # Enable mmap for loading vector index
    scalarField: true # Enable mmap for loading scalar data
    scalarIndex: true # Enable mmap for loading scalar index
    chunkCache: true # Enable mmap for chunk cache (raw vector retrieving).
    # Enable memory mapping (mmap) to optimize the handling of growing raw data. 
    # By activating this feature, the memory overhead associated with newly added or modified data will be significantly minimized. 
    # However, this optimization may come at the cost of a slight decrease in query latency for the affected data segments.
    growingMmapEnabled: false

```

then build index using DISKANN, after then with describe_index I am seeing 

```{'index_type': 'DISKANN', 'metric_type': 'L2', 'field_name': 'emb', 'index_name': 'vector_index', 'total_rows': 100000000, 'indexed_rows': 100000000, 'pending_index_rows': 100000000, 'state': 'Finished'}
```


I am ok for a call at any time if that can have more help on this or anything if you need to know (config files or something). Hel me resolve building index using DISKANN
