### ISSUE TITLE
Search performance descreased based on sift1b when nq equals 1

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3846]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
http://192.168.1.112:5000/queries/56/source#127
The search performance of 0.11.0 is much lower than that of 0.10.x when topk and nq both 1
```
{
    "query": {
        "metrics.type": "search_performance",
        "server.value.mode": "CPU",
        "$or":[{"collection.dataset_name": "sift_1b_2048_128_l2"},{"collection.dataset_name": "sift_1b_4000000_128_l2"}],
        "index.index_type": "ivf_sq8",
        "index.index_param.nlist": 16384,
        "search.search_param.nprobe": 32,
        "search.topk": 1,
        "search.nq": 1
    }
```
![image](https://user-images.githubusercontent.com/27288593/93964618-aac04000-fd92-11ea-8934-8a2243db73a5.png)

**Steps/Code to reproduce behavior**
create a collection and insert 1billion vectors with segment_row_limit = 4000000
create index ivf_sq8
and then search.
```
segment_row_count: 4000000
index:
   type: ivf_sq8
   nlist: 16384
   metric_type: L2
search:
   nprobe: 32
   metric_type: L2
```
search with CPU
```
server:
        db_config.primary_path: /test/milvus/db_data_011/sift_1b_4000000_128_l2_sq8
        cache_config.cpu_cache_capacity: 150GB
        engine_config.use_blas_threshold: 0
        engine_config.gpu_search_threshold: 100
        gpu_resource_config.enable: false
        gpu_resource_config.cache_capacity: 6GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
        wal_enable: true
      collection_name: sift_1b_4000000_128_l2
      run_count: 2
      top_ks: [1, 10, 100, 1000]
      nqs: [1, 10, 100, 1000, 1200]
      search_params:
        -
          nprobe: 8
        -
          nprobe: 32
```

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
