### ISSUE TITLE
[Bug]: LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by roablep** [milvus-io/milvus#38468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.4.17
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): default(rocksmq)
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): Ubuntu 24.04.1 LTS
- CPU/Memory: 
CPU(s):                               2
On-line CPU(s) list:                  0,1
Model name:                           AMD EPYC Processor
BIOS Model name:                      NotSpecified  CPU @ 2.0GHz
NUMA node0 CPU(s):                    0,1

               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       1.6Gi       171Mi       6.0Mi       258Mi       263Mi

- GPU: 
- Others:
```

### Current Behavior

`ERROR: ld.so: object '/milvus/lib/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.`

### Expected Behavior

docker compose up launches the container

### Steps To Reproduce

```markdown
Deploy Milvus using the provided docker-compose.yml.
Attempt to start the container.
Observe the container fails with exit code 134 and logs the above error.
```

### Milvus Log
```
root@docker-ce-ubuntu-2gb-ash-1:~# docker inspect 
[
    {
        "Id": "sha256:4683fdeb1c31ef39c80a542a268f6bbe8dfdd1805e630362f6d98bb73de11a50",
        "RepoTags": [
            "milvusdb/milvus:v2.4.17"
        ],
        "RepoDigests": [
            "milvusdb/milvus@sha256:def1f0a3f90cd67273afba833ae68ed5cdadf6bb7a128b694b662323f74940b8"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2024-11-22T11:41:12.232359318Z",
        "DockerVersion": "24.0.5",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/milvus/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LD_LIBRARY_PATH=/milvus/lib::/usr/lib",
                "LD_PRELOAD=/milvus/lib/:/milvus/lib/libjemalloc.so",
                "MALLOC_CONF=background_thread:true"
            ],
            "Cmd": null,
            "Image": "sha256:41136788db4d6b90332900d5b4a934f9f8983c2167d8266ca85bb2c19764ee75",
            "Volumes": null,
            "WorkingDir": "/milvus/",
            "Entrypoint": [
                "/tini",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "22.04"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1664829469,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/15b745a5c0deecf32da0bb3fd3eca9dc06bd66d1b0bfd2c0ef87b3f9a2add0b5/diff:/var/lib/docker/overlay2/958654eac65bbe0d64e4ee459537372250b5b8ce39443fd557e520836d5ed501/diff:/var/lib/docker/overlay2/76ca9924f4f61d739fea0f539ef4cdd4fe74b39b29e7b0afc5a3334c935bb6bf/diff:/var/lib/docker/overlay2/7dc2a362c36815fb2ac618435b5efe6b22c6cf5bf9443ec17d5571e1aece25e7/diff:/var/lib/docker/overlay2/98ed5484c9b5010a060a966fd360f4e21d2bd00171e9ac2eaadf12f4f8805b01/diff",
                "MergedDir": "/var/lib/docker/overlay2/cf42bb2890955af49328a7d5cfe7196438f725b6213a9f08f096d510d5245a08/merged",
                "UpperDir": "/var/lib/docker/overlay2/cf42bb2890955af49328a7d5cfe7196438f725b6213a9f08f096d510d5245a08/diff",
                "WorkDir": "/var/lib/docker/overlay2/cf42bb2890955af49328a7d5cfe7196438f725b6213a9f08f096d510d5245a08/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:0b9c994b0484c0bc61f9de7c28a58745a504704254c5e8ed12349ebee3393a66",
                "sha256:c75ec3f1b42dcac8b1d9cd2e4e5b26eb29414a969ac4866a115212350bddfeb1",
                "sha256:8054a3c041e90a8422307b12c174ac445ea7b035ef08f8de8f0de4ac51d670c8",
                "sha256:6f9cc92b5334d3a11d924a1433b0725cba89a8f47e63f68475beb0a107a56b81",
                "sha256:60f673b3f11d932f93a8477f87214d52bb1aa7af7edf17f445025bab13406942",
                "sha256:e594bf1dbba9fb458d4b0b4dbac86f205866981a2465e9d105cea404cc8bef6a"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

### Anything else?

I expect this has to do with the volume mapping, but I don't see anything inherently wrong with it. 

```
  standalone:
    container_name: milvus-standalone
    networks:
      - milvus_net
    image: milvusdb/milvus:v2.4.17
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /home/<my_user>/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - "etcd"
      - "minio"

```
