### ISSUE TITLE
[Bug]: [benchmark][retrieve] just wrote 1.5G of data to the 16G memory milvus was forbidden to write

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#38706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:sunby-no_unlink-e76862d-20241217 
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc124
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-h4xxv

server:
```
NAME                                                              READY   STATUS                   RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
wt-test-unlink-2-etcd-0                                           1/1     Running                  0                24h     10.104.25.198   4am-node30   <none>           <none>
wt-test-unlink-2-milvus-standalone-7857b5bbb5-thgsb               1/1     Running                  2 (24h ago)      24h     10.104.26.239   4am-node32   <none>           <none>
wt-test-unlink-2-minio-5c95dc8d69-tbs42                           1/1     Running                  0                24h     10.104.25.196   4am-node30   <none>           <none>
```

<img width="1518" alt="截屏2024-12-24 16 54 41" src="https://github.com/user-attachments/assets/f9840ab3-2e6e-41e8-a306-6492b847b734" />

client log:
![image](https://github.com/user-attachments/assets/afc559ae-c120-4d9f-80b6-c9c62c024c79)

### Steps To Reproduce

```markdown
1. create a collection with fields:
   - id: INT64, primary key
   - float_vector: 3dim
   - int64_1: INT64
2. build FLAT index on 'float_vector'
3. insert 3500m data <- inserted 60m data raised error `memory quota exceeded`
```

### Anything else?

server config：
```
extraConfigFiles:
  user.yaml: |+
    dataCoord:
      segment:
        sealProportion: 1
    indexCoord:
      scheduler:
        interval: 1
    queryNode:
      cache:
        warmup: sync
      mmap:
        vectorField: true
        vectorIndex: true
        scalarField: true
        scalarIndex: true
standalone:
  resources:
    limits:
      cpu: '2.0'
      memory: 16Gi
    requests:
      cpu: '1.0'
      memory: 10Gi
  nodeSelector:
    node-role/nvme: 'true'
    kubernetes.io/hostname: 4am-node32
```

client config:
```
{
     "dataset_params": {
          "metric_type": "L2",
          "dim": 3,
          "dataset_name": "local",
          "dataset_size": "3500m",
          "ni_per": 1000000
     },
     "collection_params": {
          "shards_num": 1,
          "other_fields": [
               "int64_1"
          ],
          "collection_name": "scene_int64_1"
     },
     "index_params": {
          "index_type": "FLAT",
          "index_param": {}
     },
     "concurrent_params": {
          "concurrent_number": [
               10,
               100
          ],
          "during_time": "30m",
          "interval": 20
     },
     "concurrent_tasks": [
          {
               "type": "query",
               "weight": 1,
               "params": {
                    "expr": "",
                    "output_fields": [
                         "int64_1"
                    ],
                    "limit": 10,
                    "timeout": 600,
                    "random_data": true,
                    "random_count": 10,
                    "random_range": [
                         0,
                         35000000
                    ],
                    "field_name": "id",
                    "field_type": "int64"
               }
          }
     ]
}
```
