### ISSUE TITLE
[Bug]: [benchmark][retrieve] After releasing the loaded collection, the memory usage of milvus standalone still exceeds 1G

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#39075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250107-3739446a-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc124
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server:
```
NAME                                                              READY   STATUS                   RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
wt-test-array-1-etcd-0                                            1/1     Running                  0               24h     10.104.23.75    4am-node27   <none>           <none>
wt-test-array-1-milvus-standalone-57b9b958cf-pzdll                1/1     Running                  1 (22h ago)     24h     10.104.23.74    4am-node27   <none>           <none>
wt-test-array-1-minio-5b67b979cd-4zl2x                            1/1     Running                  0               24h     10.104.23.76    4am-node27   <none>           <none>
```

test steps:
```
1. deploy a standalone milvus <- memory usage of milvus standalone is 275M
2.creata a collection with fields: 'id'(primary key), 'float_vector'(3dim), 'array_varchar_1'(max_capacity=10)
3. build FLAT index on field 'float_vector'
4. insert 200 million data
5. flush collection
6. rebuild index
7. load collection
8. release collection <- memory usage of milvus standalone still exceeds 1G
```
### step 1
<img width="1611" alt="截屏2025-01-08 15 30 02" src="https://github.com/user-attachments/assets/4c59515f-6c81-499f-b601-710e6d324b71" />

### step 8
<img width="660" alt="截屏2025-01-08 15 30 34" src="https://github.com/user-attachments/assets/7cf7cb1e-eb74-46e6-b13b-832cb9629b96" />
<img width="1600" alt="截屏2025-01-08 15 30 48" src="https://github.com/user-attachments/assets/56190145-b8a5-4652-beb9-2a6b664fa4cd" />
<img width="1913" alt="截屏2025-01-08 15 31 03" src="https://github.com/user-attachments/assets/07808cf6-8403-43ad-8e51-8227b42d4f64" />

### Anything else?

server config:
```
extraConfigFiles:
  user.yaml: |
    dataCoord:
      segment:
        sealProportion: 1
    indexCoord:
      scheduler:
        interval: 1
    queryNode:
      cache:
        warmup: sync
      mmap:
        vectorField: true
        vectorIndex: true
        scalarField: true
        scalarIndex: true
standalone:
  resources:
    limits:
      cpu: '2.0'
      memory: 16Gi
    requests:
      cpu: '1.0'
      memory: 10Gi
  nodeSelector:
    node-role/nvme: 'true'
```

client config:
```
{
     "dataset_params": {
          "metric_type": "L2",
          "dim": 3,
          "dataset_name": "local",
          "dataset_size": "200m",
          "ni_per": 50000,
          "scalars_params": {
               "array_varchar_1": {
                    "params": {
                         "max_length": 100,
                         "max_capacity": 10
                    }
               }
          }
     },
     "collection_params": {
          "shards_num": 1,
          "other_fields": [
               "array_varchar_1"
          ],
          "collection_name": "scene_array_varchar_1"
     },
     "index_params": {
          "index_type": "FLAT",
          "index_param": {}
     },
     "concurrent_params": {
          "concurrent_number": [
               10,
               100
          ],
          "during_time": "30m",
          "interval": 20
     },
     "concurrent_tasks": [
          {
               "type": "query",
               "weight": 1,
               "params": {
                    "expr": "",
                    "output_fields": [
                         "array_varchar_1"
                    ],
                    "limit": 10,
                    "timeout": 600,
                    "random_data": true,
                    "random_count": 10,
                    "random_range": [
                         0,
                         200000000
                    ],
                    "field_name": "id",
                    "field_type": "int64"
               }
          }
     ]
}
```
