### ISSUE TITLE
[Bug]: Milvus WebUI show etcd Unhealthy

### ISSUE THREAD

**Issue by Flamentt** [milvus-io/milvus#39417]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5.3  
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 32 core/128GB
- GPU: 
- Others:
```

### Current Behavior

Hi, I have installed Milvus using docker-compose to a HDD disk and change `port:` to `127.0.0.1:...:...`. Then I run `sudo docker-compose ps` and it show all containers are `healthy` but on Milvus WebUI it show that `etcd` are unhealthy. Is this fine?

I runned some simple python code to create database, collection, insert some data and query and it seem worked fine.

( I restarted `etcd` once after seeing the error on WebUI but it doesn't change the status on WebUI)
<img width="1571" alt="Image" src="https://github.com/user-attachments/assets/5c5e8bb4-dfb0-4d01-a857-35f65aa67d52" />

<img width="1359" alt="Image" src="https://github.com/user-attachments/assets/c095b0bd-7927-4cba-b7fd-c9ba743bf134" />

I also run some other commands to make sure:

```
sudo docker exec -it milvus-etcd etcdctl endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 4.144762ms

sudo docker exec milvus-etcd etcdctl endpoint status
127.0.0.1:2379, 8e9e05c.........., 3.5.16, 74 kB, true, false, 3, 551, 551, 

sudo docker exec milvus-etcd etcdctl member list
8e9e05c.........., started, default, http://localhost:2380, http://127.0.0.1:2379, false
````

Below are my docker compose file:

```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.16
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "127.0.0.1:9001:9001"
      - "127.0.0.1:9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.3
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "127.0.0.1:19530:19530"
      - "127.0.0.1:9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

### Steps To Reproduce

```markdown

```
