### ISSUE TITLE
[Bug]: [benchmark][cluster] DataNode panic `Failed to create consumer by-dev-rootcoord-dml_12, errors = server error: ConsumerBusy: Exclusive consumer is already connected` in concurrent ddl & dql scene

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#39498]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250120-905c3b81-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc124
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-tvshj

server:
```
NAME                                                            READY   STATUS             RESTARTS          AGE     IP              NODE         NOMINATED NODE   READINESS GATES
spring-festival-1-etcd-0                                        1/1     Running            0                 23h     10.104.27.104   4am-node31   <none>           <none>
spring-festival-1-etcd-1                                        1/1     Running            0                 23h     10.104.21.242   4am-node24   <none>           <none>
spring-festival-1-etcd-2                                        1/1     Running            0                 23h     10.104.16.143   4am-node21   <none>           <none>
spring-festival-1-milvus-datanode-66f5dbcc87-hhpwc              1/1     Running            3 (41m ago)       23h     10.104.9.9      4am-node14   <none>           <none>
spring-festival-1-milvus-indexnode-5584579bc-9kq2m              1/1     Running            2 (23h ago)       23h     10.104.9.7      4am-node14   <none>           <none>
spring-festival-1-milvus-indexnode-5584579bc-d4mgd              1/1     Running            2 (23h ago)       23h     10.104.16.139   4am-node21   <none>           <none>
spring-festival-1-milvus-indexnode-5584579bc-h8bbp              1/1     Running            1 (23h ago)       23h     10.104.21.237   4am-node24   <none>           <none>
spring-festival-1-milvus-indexnode-5584579bc-wsq5q              1/1     Running            2 (23h ago)       23h     10.104.33.123   4am-node36   <none>           <none>
spring-festival-1-milvus-mixcoord-694896454f-wjmrc              1/1     Running            2 (23h ago)       23h     10.104.16.137   4am-node21   <none>           <none>
spring-festival-1-milvus-proxy-84944bf5c9-c24h5                 1/1     Running            2 (23h ago)       23h     10.104.9.6      4am-node14   <none>           <none>
spring-festival-1-milvus-querynode-6dfdf5c7b7-2qjnq             1/1     Running            2 (23h ago)       23h     10.104.16.138   4am-node21   <none>           <none>
spring-festival-1-milvus-querynode-6dfdf5c7b7-5gtc5             1/1     Running            1 (23h ago)       23h     10.104.30.23    4am-node38   <none>           <none>
spring-festival-1-milvus-querynode-6dfdf5c7b7-bvtrp             1/1     Running            1 (23h ago)       23h     10.104.32.49    4am-node39   <none>           <none>
spring-festival-1-milvus-querynode-6dfdf5c7b7-pj2mj             1/1     Running            2 (23h ago)       23h     10.104.33.124   4am-node36   <none>           <none>
spring-festival-1-milvus-querynode-6dfdf5c7b7-zgvk2             1/1     Running            1 (23h ago)       23h     10.104.15.123   4am-node20   <none>           <none>
spring-festival-1-pulsarv3-bookie-0                             1/1     Running            0                 23h     10.104.27.108   4am-node31   <none>           <none>
spring-festival-1-pulsarv3-bookie-1                             1/1     Running            0                 23h     10.104.21.243   4am-node24   <none>           <none>
spring-festival-1-pulsarv3-bookie-2                             1/1     Running            0                 23h     10.104.16.144   4am-node21   <none>           <none>
spring-festival-1-pulsarv3-bookie-init-x5fsk                    0/1     Completed          0                 23h     10.104.9.5      4am-node14   <none>           <none>
spring-festival-1-pulsarv3-broker-0                             1/1     Running            0                 23h     10.104.9.8      4am-node14   <none>           <none>
spring-festival-1-pulsarv3-broker-1                             1/1     Running            0                 23h     10.104.13.138   4am-node16   <none>           <none>
spring-festival-1-pulsarv3-proxy-0                              1/1     Running            0                 23h     10.104.9.11     4am-node14   <none>           <none>
spring-festival-1-pulsarv3-proxy-1                              1/1     Running            0                 23h     10.104.13.139   4am-node16   <none>           <none>
spring-festival-1-pulsarv3-pulsar-init-ns2gk                    0/1     Completed          0                 23h     10.104.9.10     4am-node14   <none>           <none>
spring-festival-1-pulsarv3-recovery-0                           1/1     Running            0                 23h     10.104.30.22    4am-node38   <none>           <none>
spring-festival-1-pulsarv3-zookeeper-0                          1/1     Running            0                 23h     10.104.32.51    4am-node39   <none>           <none>
spring-festival-1-pulsarv3-zookeeper-1                          1/1     Running            0                 23h     10.104.27.107   4am-node31   <none>           <none>
spring-festival-1-pulsarv3-zookeeper-2                          1/1     Running            0                 23h     10.104.21.244   4am-node24   <none>           <none>
```

<img width="1289" alt="Image" src="https://github.com/user-attachments/assets/cf31c1c8-a5c6-4a01-9942-796c56015f07" />

<img width="1433" alt="Image" src="https://github.com/user-attachments/assets/65ff0e89-2410-4c8d-b381-03fc2cba87e3" />

client log:
```
[2025-01-21 22:09:13,680 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_13_455456785573251593v3])>, <Time:{'RPC start': '2025-01-21 22:06:00.428681', 'RPC error': '2025-01-21 22:09:13.680876'}> (decorators.py:140)
[2025-01-21 22:10:08,218 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_13_455456785573497613v3])>, <Time:{'RPC start': '2025-01-21 22:06:55.026227', 'RPC error': '2025-01-21 22:10:08.218809'}> (decorators.py:140)
[2025-01-21 22:11:31,628 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_13_455456785573561376v3])>, <Time:{'RPC start': '2025-01-21 22:08:16.843460', 'RPC error': '2025-01-21 22:11:31.628790'}> (decorators.py:140)

....

[2025-01-22 03:05:48,904 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_6_455456785588078413v2])>, <Time:{'RPC start': '2025-01-22 03:02:32.188756', 'RPC error': '2025-01-22 03:05:48.904405'}> (decorators.py:140)
[2025-01-22 03:06:27,363 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_0_455456785588078429v2])>, <Time:{'RPC start': '2025-01-22 03:02:32.205224', 'RPC error': '2025-01-22 03:06:27.363017'}> (decorators.py:140)
[2025-01-22 03:06:40,126 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_11_455456785588084805v5])>, <Time:{'RPC start': '2025-01-22 03:02:53.375657', 'RPC error': '2025-01-22 03:06:40.126715'}> (decorators.py:140)
[2025-01-22 03:06:41,163 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_5_455456785588078440v5])>, <Time:{'RPC start': '2025-01-22 03:02:32.268667', 'RPC error': '2025-01-22 03:06:41.163054'}> (decorators.py:140)
[2025-01-22 03:06:44,065 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_12_455456785588084818v2])>, <Time:{'RPC start': '2025-01-22 03:02:53.521987', 'RPC error': '2025-01-22 03:06:44.065908'}> (decorators.py:140)
[2025-01-22 03:07:19,371 - ERROR - fouram]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: channel not found[channel=by-dev-rootcoord-dml_7_455456785588108799v5])>, <Time:{'RPC start': '2025-01-22 03:04:09.879044', 'RPC error': '2025-01-22 03:07:19.371268'}> (decorators.py:140)
```

### Steps To Reproduce

```markdown
1. create a collection with fields: 'id'(primary key), 'float_vector'(128dim), 'sparse_float_vector', 'int64_1', 'varchar_1', 'array_varchar_1', 'bool_1', dynamic fields
2. build indexes
   - IVF_SQ8: 'float_vector'
   - SPARSE_INVERTED_INDEX: 'sparse_float_vector'
   - STL_SORT: 'int64_1'
   - Trie: 'varchar_1'
   - INVERTED: 'array_varchar_1'
   - BITMAP: 'bool_1'
3. insert 100 million data
4. flush collection
5. rebuild indexes
6. load collection
7. concurrent requests: <- dataNode panic 
   - hybrid_search
   - search
   - query
   - scene_hybrid_search_test: 4 vector fields, 3 scalar fields, dynamic field
      (collection: create->insert->flush->index->load->hybrid_search->drop)
```

### Anything else?

server config:
```
queryNode:
  resources:
    limits:
      cpu: '8'
      memory: 64Gi
    requests:
      cpu: '8'
      memory: 33Gi
  replicas: 5
  nodeSelector:
    node-role/nvme: 'true'
indexNode:
  resources:
    limits:
      cpu: '8.0'
      memory: 16Gi
    requests:
      cpu: '4.0'
      memory: 4Gi
  replicas: 4
dataNode:
  resources:
    limits:
      cpu: '1.0'
      memory: 8Gi
    requests:
      cpu: '1.0'
      memory: 5Gi
minio:
  enabled: false
externalS3:
  enabled: true
  accessKey: miniolru500g
  secretKey: miniolru500g
  bucketName: lru-500g
  host: minio-1.minio
  port: 9000
  rootPath: lru500g
```

client config:
```
dataset_params:
  metric_type: L2
  dim: 128
  dataset_name: sift
  dataset_size: 100m
  ni_per: 2000
  scalars_index:
    int64_1:
      index_type: STL_SORT
    varchar_1:
      index_type: Trie
    array_varchar_1:
      index_type: INVERTED
    bool_1:
      index_type: BITMAP
  vectors_index:
    sparse_float_vector:
      index_type: SPARSE_INVERTED_INDEX
      index_param:
        drop_ratio_build: 0.2
      metric_type: IP
  scalars_params:
    sparse_float_vector:
      other_params:
        dim: 30000
        sparse_range:
        - 100
        - 150
    array_varchar_1:
      params:
        max_length: 128
        max_capacity: 10
      other_params:
        dataset: random_algorithm
        algorithm_params:
          algorithm_name: specify_scope_array
          specify_range:
          - 0
          - 10
          capacity_range:
          - 0
          - 10
common_params:
  data_organization: row_insert
collection_params:
  other_fields:
  - sparse_float_vector
  - int64_1
  - varchar_1
  - array_varchar_1
  - bool_1
  dynamic_fields:
  - json_dynamic
  - int8_dynamic
  - int32_dynamic
  - array_int64_dynamic
  enable_dynamic_field: true
  shards_num: 2
  collection_name: spring_festival_1
index_params:
  index_type: IVF_SQ8
  index_param:
    nlist: 1024
concurrent_params:
  concurrent_number: 20
  during_time: 12d
  interval: 20
concurrent_tasks:
- type: hybrid_search
  weight: 1
  params:
    nq: 1
    top_k: 10
    reqs:
    - search_param:
        nprobe: 16
      anns_field: float_vector
      top_k: 100
      expr: int64_1 % 10 == 6
    - search_param:
        nprobe: 32
      anns_field: float_vector
      top_k: 9
      expr: bool_1 == false
    - search_param:
        drop_ratio_search: 0.2
      anns_field: sparse_float_vector
      top_k: 10
      expr: varchar_1 like '%9'
    - search_param:
        drop_ratio_search: 0.3
      anns_field: sparse_float_vector
      top_k: 11
      expr: int8_dynamic >= 64
    rerank:
      WeightedRanker:
      - 0.85
      - 0.95
      - 0.5
      - 0.6
    output_fields:
    - "*"
    timeout: 1200
    random_data: true
    check_task: check_search_output
- type: search
  weight: 1
  params:
    nq: 10
    top_k: 10
    search_param:
      nprobe: 16
    expr: bool_1 == true || array_contains_any(array_varchar_1, ['0', '5', '7'])
    output_fields:
    - "*"
    timeout: 1200
    random_data: true
    check_task: check_search_output
- type: query
  weight: 1
  params:
    expr: ''
    output_fields:
    - "*"
    limit: 10
    timeout: 1200
    random_data: true
    random_count: 10
    random_range:
    - 0
    - 100000000
    field_name: id
    field_type: int64
- type: scene_hybrid_search_test
  weight: 1
  params:
    nq: 1
    top_k: 1
    reqs:
    - search_param:
        nprobe: 128
      anns_field: float_vector
      top_k: 100
    - search_param:
        nprobe: 32
      anns_field: float_vector_1
      top_k: 10
    - search_param:
        ef: 32
      anns_field: float_vector_2
      top_k: 5
    - search_param:
        search_list: 20
      anns_field: float_vector_3
      top_k: 10
    rerank:
      RRFRanker: []
    timeout: 600
    random_data: true
    dataset: local
    dim: 128
    shards_num: 6
    data_size: 3000
    nb: 3000
    index_type: IVF_SQ8
    index_param:
      nlist: 2048
    metric_type: L2
    output_fields:
    - "*"
    other_fields:
    - float_vector_1
    - float_vector_2
    - float_vector_3
    - int64_1
    - bool_1
    - varchar_1
    dynamic_fields:
    - json_dynamic
    - float_dynamic
    - array_bool_dynamic
    enable_dynamic_field: true
    data_organization: row_insert
    replica_number: 1
    scalars_params:
      float_vector_1:
        params:
          dim: 128
        other_params:
          dataset: sift
      float_vector_2:
        params:
          dim: 128
        other_params:
          dataset: sift
      float_vector_3:
        params:
          dim: 128
        other_params:
          dataset: sift
    scalars_index:
      int64_1: {}
      bool_1:
        index_type: INVERTED
      varchar_1:
        index_type: BITMAP
    vectors_index:
      float_vector_1:
        index_type: IVF_FLAT
        index_param:
          nlist: 1024
        metric_type: L2
      float_vector_2:
        index_type: HNSW
        index_param:
          M: 8
          efConstruction: 200
        metric_type: L2
      float_vector_3:
        index_type: DISKANN
        index_param: {}
        metric_type: IP
    hybrid_search_counts: 10
```
