### ISSUE TITLE
[Bug]: [benchmark][cluster] Serial insert timed out, it seems that dataNode consumption is stuck

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#39666]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.5-20250126-bc91b2a4-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc124
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-xj5sz

server:
```
NAME                                                   READY   STATUS             RESTARTS           AGE    IP              NODE         NOMINATED NODE   READINESS GATES
spring-festival-4-etcd-0                               1/1     Running            0                  10d    10.104.27.249   4am-node31   <none>           <none>
spring-festival-4-etcd-1                               1/1     Running            0                  10d    10.104.17.129   4am-node23   <none>           <none>
spring-festival-4-etcd-2                               1/1     Running            0                  10d    10.104.33.246   4am-node36   <none>           <none>
spring-festival-4-milvus-datanode-5ff77bcf9b-bklhr     1/1     Running            1 (10d ago)        10d    10.104.14.65    4am-node18   <none>           <none>
spring-festival-4-milvus-indexnode-7999b498f9-m7fng    1/1     Running            1 (10d ago)        10d    10.104.6.93     4am-node13   <none>           <none>
spring-festival-4-milvus-indexnode-7999b498f9-tg4qw    1/1     Running            2 (10d ago)        10d    10.104.23.24    4am-node27   <none>           <none>
spring-festival-4-milvus-indexnode-7999b498f9-z8r8w    1/1     Running            2 (10d ago)        10d    10.104.32.55    4am-node39   <none>           <none>
spring-festival-4-milvus-indexnode-7999b498f9-zs4dv    1/1     Running            2 (10d ago)        10d    10.104.16.42    4am-node21   <none>           <none>
spring-festival-4-milvus-mixcoord-cd5549bc7-wgsrt      1/1     Running            1 (10d ago)        10d    10.104.14.64    4am-node18   <none>           <none>
spring-festival-4-milvus-proxy-6b5b6688bf-sprzz        1/1     Running            1 (10d ago)        10d    10.104.14.66    4am-node18   <none>           <none>
spring-festival-4-milvus-querynode-7f9b9c9d69-vb92s    1/1     Running            2 (10d ago)        10d    10.104.30.24    4am-node38   <none>           <none>
spring-festival-4-pulsarv3-bookie-0                    1/1     Running            0                  10d    10.104.27.251   4am-node31   <none>           <none>
spring-festival-4-pulsarv3-bookie-1                    1/1     Running            0                  10d    10.104.17.130   4am-node23   <none>           <none>
spring-festival-4-pulsarv3-bookie-2                    1/1     Running            0                  10d    10.104.25.15    4am-node30   <none>           <none>
spring-festival-4-pulsarv3-bookie-init-8gjr4           0/1     Completed          0                  10d    10.104.6.92     4am-node13   <none>           <none>
spring-festival-4-pulsarv3-broker-0                    1/1     Running            0                  10d    10.104.27.244   4am-node31   <none>           <none>
spring-festival-4-pulsarv3-broker-1                    1/1     Running            0                  10d    10.104.9.10     4am-node14   <none>           <none>
spring-festival-4-pulsarv3-proxy-0                     1/1     Running            0                  10d    10.104.6.94     4am-node13   <none>           <none>
spring-festival-4-pulsarv3-proxy-1                     1/1     Running            0                  10d    10.104.9.11     4am-node14   <none>           <none>
spring-festival-4-pulsarv3-pulsar-init-lgqpt           0/1     Completed          0                  10d    10.104.9.9      4am-node14   <none>           <none>
spring-festival-4-pulsarv3-recovery-0                  1/1     Running            0                  10d    10.104.27.243   4am-node31   <none>           <none>
spring-festival-4-pulsarv3-zookeeper-0                 1/1     Running            0                  10d    10.104.27.250   4am-node31   <none>           <none>
spring-festival-4-pulsarv3-zookeeper-1                 1/1     Running            0                  10d    10.104.17.131   4am-node23   <none>           <none>
spring-festival-4-pulsarv3-zookeeper-2                 1/1     Running            0                  10d    10.104.33.248   4am-node36   <none>           <none>
```

### milvus logs
<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/5fe7bde6-9f0f-4448-851e-8426ecab58bb" />

### proxy pod monitor
<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/821c456f-8d4c-43c6-86d5-bc4a15b52057" />

### dataNode pod monitor
<img width="1916" alt="Image" src="https://github.com/user-attachments/assets/cb767940-439c-41ff-8bfe-bcde95ead10e" />

### dataNode TT lag behind now
<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/a6b23a89-bf70-4d00-941c-c0bdcfaa3339" />

<img width="1912" alt="Image" src="https://github.com/user-attachments/assets/e982c943-cc26-49e1-a543-abfbfc3af550" />

### dataCoord
<img width="1912" alt="Image" src="https://github.com/user-attachments/assets/285fbefb-5461-45ff-abbd-900a1285b98d" />

client logs:
```
[2025-01-26 22:02:00,977 -  INFO - fouram]: [Base] Number of vectors in the collection(spring_festival_4): 11509945 (base.py:535)
[2025-01-26 22:02:01,171 -  INFO - fouram]: [Base] Start inserting, ids: 18410000 - 18419999, data size: 20,000,000 (base.py:366)
[2025-01-26 22:02:03,932 -  INFO - fouram]: [Time] Collection.insert run in 2.7606s (api_request.py:49)
[2025-01-26 22:02:03,934 -  INFO - fouram]: [Base] Number of vectors in the collection(spring_festival_4): 11509945 (base.py:535)
[2025-01-26 22:02:04,128 -  INFO - fouram]: [Base] Start inserting, ids: 18420000 - 18429999, data size: 20,000,000 (base.py:366)
[2025-01-26 22:02:36,571 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=65535, message=message send timeout: TimeoutError)>, <Time:{'RPC start': '2025-01-26 22:02:04.526869', 'RPC error': '2025-01-26 22:02:36.571553'}> (decorators.py:140)
[2025-01-26 22:02:36,573 - ERROR - fouram]: (api_response) : [Collection.insert] <MilvusException: (code=65535, message=message send timeout: TimeoutError)>, [requestId: 2d2e49ac-dc31-11ef-8665-9ee58c5ad356] (api_request.py:57)
[2025-01-26 22:02:36,573 - ERROR - fouram]: [CheckFunc] insert request check failed, response:<MilvusException: (code=65535, message=message send timeout: TimeoutError)> (func_check.py:106)
```

### Steps To Reproduce

```markdown
1. create a collection with fields: 'id'(primary key), 'float_vector'(128dim), 'float_vector_1'(768dim), 'sparse_float_vector', 'bfloat16_vector'(256dim), 'int64_1', 'varchar_1'
2. build indexes
   - HNSW: 'float_vector'
   - DISKANN: 'float_vector_1'
   - SPARSE_INVERTED_INDEX: 'sparse_float_vector'
   - IVF_SQ8: 'bfloat16_vector'
   - INVERTED: 'int64_1'
   - Trie: 'varchar_1'
3. insert 20m data <- insert timeout
```

### Anything else?

server config:
```
extraConfigFiles:
  user.yaml: |+
    indexCoord:
      scheduler:
        interval: 1
    queryNode:
      mmap:
        vectorField: true
        vectorIndex: true
        scalarField: true
        scalarIndex: true
queryNode:
  resources:
    limits:
      cpu: '32'
      memory: 32Gi
    requests:
      cpu: '16'
      memory: 32Gi
  replicas: 1
  nodeSelector:
    node-role/nvme: 'true'
indexNode:
  resources:
    limits:
      cpu: '4.0'
      memory: 16Gi
    requests:
      cpu: '2.0'
      memory: 4Gi
  replicas: 4
dataNode:
  resources:
    limits:
      cpu: '2.0'
      memory: 16Gi
    requests:
      cpu: '2.0'
      memory: 5Gi
minio:
  enabled: false
externalS3:
  enabled: true
  accessKey: minio-4am-stable-user
  secretKey: minio-4am-stable-password
  bucketName: 4am-stable
  host: minio-1.minio
  port: 9000
  rootPath: 4am_stable_cny_scene_4
broker:
  configData:
    defaultRetentionTimeInMinutes: "60"
```

client config:
```
    dataset_params:
      metric_type: L2
      dim: 128
      scalars_index:
        int64_1:
          index_type: INVERTED
        varchar_1:
          index_type: INVERTED
      vectors_index:
        float_vector_1:
          index_type: DISKANN
          index_param: {}
          metric_type: IP
        sparse_float_vector:
          index_type: SPARSE_INVERTED_INDEX
          index_param:
            drop_ratio_build: 0.2
          metric_type: IP
        bfloat16_vector:
          index_type: IVF_SQ8
          index_param:
            nlist: 2048
          metric_type: L2
      scalars_params:
        float_vector_1:
          params:
            dim: 768
          other_params:
            dataset: laion2b_multi
            column_name: float32_vector
        sparse_float_vector:
          other_params:
            dim: 10000
            sparse_range:
            - 1
            - 20
        bfloat16_vector:
          params:
            dim: 256
      dataset_name: sift
      dataset_size: 20m
      ni_per: 10000
    collection_params:
      other_fields:
      - float_vector_1
      - sparse_float_vector
      - bfloat16_vector
      - int64_1
      - varchar_1
      shards_num: 2
      collection_name: spring_festival_4
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200
    concurrent_params:
      concurrent_number: 20
      during_time: 8d
      interval: 20
    concurrent_tasks:
    - type: scene_hybrid_search_test
      weight: 1
      params:
        nq: 2
        top_k: 5
        reqs:
        - search_param:
            nprobe: 128
          anns_field: float_vector
          expr: bool_1 == True
          top_k: 100
        - search_param:
            nprobe: 32
          anns_field: binary_vector_scene_hybrid_search_test_1
          expr: bool_1 != True
          top_k: 10
        - search_param:
            search_list: 30
          anns_field: float16_vector_scene_hybrid_search_test_2
          expr: int64_1 >= 1500
          top_k: 5
        - search_param:
            drop_ratio_search: 0.1
          anns_field: sparse_float_vector_scene_hybrid_search_test_3
          expr: varchar_1 like "1%"
          top_k: 10
        rerank:
          RRFRanker: []
        output_fields:
        - "*"
        timeout: 600
        random_data: true
        dataset: local
        dim: 128
        shards_num: 2
        data_size: 3000
        nb: 3000
        index_type: IVF_SQ8
        index_param:
          nlist: 2048
        metric_type: L2
        other_fields:
        - binary_vector_scene_hybrid_search_test_1
        - float16_vector_scene_hybrid_search_test_2
        - sparse_float_vector_scene_hybrid_search_test_3
        - int64_1
        - bool_1
        - varchar_1
        replica_number: 1
        scalars_params:
          binary_vector_scene_hybrid_search_test_1:
            params:
              dim: 512
            other_params:
              dataset: binary
          float16_vector_scene_hybrid_search_test_2:
            params:
              dim: 64
        scalars_index:
          int64_1: {}
          bool_1:
            index_type: BITMAP
          varchar_1:
            index_type: INVERTED
        vectors_index:
          binary_vector_scene_hybrid_search_test_1:
            index_type: BIN_IVF_FLAT
            index_param:
              nlist: 2048
            metric_type: JACCARD
          float16_vector_scene_hybrid_search_test_2:
            index_type: DISKANN
            index_param: {}
            metric_type: IP
          sparse_float_vector_scene_hybrid_search_test_3:
            index_type: SPARSE_WAND
            index_param:
              drop_ratio_build: 0.2
            metric_type: IP
        hybrid_search_counts: 10
    - type: scene_test
      weight: 1
      params:
        dim: 128
        data_size: 3000
        nb: 3000
        index_type: IVF_SQ8
        index_param:
          nlist: 2048
        metric_type: L2
    - type: scene_test_partition_hybrid_search
      weight: 1
      params:
        nq: 1
        top_k: 1
        reqs:
        - search_param:
            ef: 32
          anns_field: float_vector
          top_k: 10
        - search_param:
            search_list: 30
          anns_field: float_vector_1
          top_k: 10
        - search_param:
            drop_ratio_search: 0.3
          anns_field: sparse_float_vector
          top_k: 30
        - search_param:
            nprobe: 16
          anns_field: bfloat16_vector
          top_k: 400
        rerank:
          RRFRanker: []
        output_fields:
        - "*"
        timeout: 6000
        random_data: true
        hybrid_search_counts: 10
        data_size: 3000
        ni: 3000
    - type: search
      weight: 1
      params:
        nq: 1000
        top_k: 1
        search_param:
          nprobe: 1000
        expr: int64_1 >= 0
        timeout: 6000
        random_data: true
        partition_names:
        - _default
        check_task: check_search_output
        check_items:
          nq: 1000
    - type: hybrid_search
      weight: 1
      params:
        nq: 1
        top_k: 100
        reqs:
        - search_param:
            ef: 32
          anns_field: float_vector
          expr: int64_1 > 100000
          top_k: 10
        - search_param:
            search_list: 30
          anns_field: float_vector_1
          expr: id < 900000
          top_k: 10
        - search_param:
            drop_ratio_search: 0.3
          anns_field: sparse_float_vector
          expr: varchar_1 > "1"
          top_k: 30
        - search_param:
            nprobe: 16
          anns_field: bfloat16_vector
          top_k: 400
        rerank:
          WeightedRanker:
          - 0.85
          - 0.95
          - 0.51
          - 0.32
        output_fields:
        - "*"
        partition_names:
        - _default
        timeout: 6000
        random_data: true
        check_task: check_search_output
        check_items:
          nq: 1
          output_fields:
          - id
          - float_vector
          - float_vector_1
          - sparse_float_vector
          - bfloat16_vector
          - int64_1
          - varchar_1
    - type: query
      weight: 1
      params:
        expr: 'int64_1 > -1 && '
        output_fields:
        - "*"
        partition_names:
        - _default
        limit: 10
        timeout: 6000
        custom_expr: " {0} < id < {0} + 100"
        custom_range:
        - 0
        - 19999900
        check_task: check_query_output
        check_items:
          expect_length: 10
          output_fields:
          - id
          - float_vector
          - float_vector_1
          - sparse_float_vector
          - bfloat16_vector
          - int64_1
          - varchar_1
```
