### ISSUE TITLE
The configurations build_index_threshold is not effective after update config file and restart docker

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4030]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. update `engine:
  build_index_threshold: 2000` in milvus.yaml
2. restart docker and docker logs is:
```
Last commit id: 4c44c03fdeb14f7cbfcfa3ed3b124e32349d712e

Successfully load configuration from /var/lib/milvus/conf/milvus.yaml.
WARNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Running on single mode.
Supported CPU instruction sets: avx2, sse4_2
Nvidia driver version: 450.66
CUDA Driver Version / Runtime Version : 11.0 / 10.1
FAISS hook AVX2
Milvus server started successfully!
```

3. get milvus config:
```
c._cmd("get_milvus_config")
'{"cache.cache_insert_data":"false","cache.cache_size":"5GB","cache.cpu_cache_threshold":"0.700000","cache.insert_buffer_size":"1GB","cache.max_concurrent_insert_request_size":"2GB","cache.preload_collection":"","cluster.enable":"false","cluster.role":"rw","engine.build_index_threshold":"4096","engine.omp_thread_num":"0","engine.search_combine_nq":"64","engine.simd_type":"auto","engine.stat_optimizer_enable":"true","engine.use_blas_threshold":"16385","general.meta_uri":"sqlite://:@:/","general.timezone":"UTC+8","gpu.build_index_devices":"gpu0,","gpu.cache_size":"6GB","gpu.cache_threshold":"0.700000","gpu.enable":"true","gpu.gpu_search_threshold":"1000","gpu.search_devices":"gpu0,","logs.level":"debug","logs.log_rotate_num":"0","logs.log_to_file":"true","logs.log_to_stdout":"false","logs.max_log_file_size":"1GB","logs.path":"/var/lib/milvus/logs","logs.trace.enable":"true","metric.address":"127.0.0.1","metric.enable":"false","metric.port":"9091","network.bind.address":"0.0.0.0","network.bind.port":"19530","network.http.enable":"true","network.http.port":"19121","storage.auto_flush_interval":"1","storage.path":"/var/lib/milvus","system.lock.enable":"true","tracing.json_config_path":"","transcript.enable":"false","transcript.replay":"","version":"0.5","wal.buffer_size":"256MB","wal.enable":"true","wal.path":"/var/lib/milvus/wal","wal.recovery_error_ignore":"false","wal.sync_mode":"false"}'

```
get config file by `client._cmd('get_milvus_config')`

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
  - branch master
  - docker image 0.11.0 gpu

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

#----------------------+------------------------------------------------------------+------------+-----------------+
# Metric Config        | Description                                                | Type       | Default         |
#----------------------+------------------------------------------------------------+------------+-----------------+
# enable               | Enable monitoring function or not.                         | Boolean    | false           |
#----------------------+------------------------------------------------------------+------------+-----------------+
# address              | Pushgateway address                                        | IP         | 127.0.0.1       +
#----------------------+------------------------------------------------------------+------------+-----------------+
# port                 | Pushgateway port, port range (1024, 65535)                 | Integer    | 9091            |
#----------------------+------------------------------------------------------------+------------+-----------------+
metric:
  enable: false
  address: 127.0.0.1
  port: 9091

engine:
  build_index_threshold: 2000
```

**Screenshots**

**Additional context**
