### ISSUE TITLE
[Bug]: Slowdown of vector ingestion between v2.4.14 and v2.5.4

### ISSUE THREAD

**Issue by lowener** [milvus-io/milvus#40310]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz - 80 cores / 100GB RAM
- GPU: V100
- Others:
```

### Current Behavior

I am experiencing a slowdown on the ingestion of vectors when upgrading from Milvus 2.4.14 to 2.5.4.
I am running Milvus cluster with Helm deployments, and the slowdown can be up to 2x slower depending on the configuration. I have found that increasing the `dataNode.resources.limits.cpu` can lead to a bigger difference as well.
The reproducer I am using ingest 50k vectors in a collection.
Ingestion time with `dataNode.resources.limits.cpu=6` (repeated twice):
- With v2.5.4-gpu
  - Ingestion time: 49.60 seconds. (7.88MB/s)
  - Ingestion time: 47.30 seconds. (8.26MB/s)
- With v2.4.14-gpu
  - Ingestion time: 26.91 seconds. (14.52MB/s)
  - Ingestion time: 27.28 seconds. (14.32MB/s)

[reproducer_ingest.py.txt](https://github.com/user-attachments/files/19057540/reproducer_ingest.py.txt)
[chart_reproducer.yml.txt](https://github.com/user-attachments/files/19057539/chart_reproducer.yml.txt)

### Steps To Reproduce

```markdown
1. microk8s helm install --wait milvus-cluster milvus/milvus -f chart_reproducer.yml
2. python reproducer_ingest.py
```

**Comment by xiaofan-luan** [comment]
only 50k vectors?
can you share the code of how you ingest and how you do the measurement?
Could this caused by slow flush?

**Comment by bigsheeper** [comment]
@lowener Milvus 2.5 introduces a new feature that sorts data based on primary keys to accelerate queries. As a result, the import process now includes sorting, making it longer compared to version 2.4. For large-scale data, you can shorten the import duration by increasing the number of DataNodes.

**Comment by lowener** [comment]
I used 50k vectors and only one DataNode for the sake of the reproducer. I didn't include it but here's my usual values:
```yml
image:
  all:
    repository: milvusdb/milvus
    tag: v2.5.5-gpu #  v2.4.14-gpu # v2.5.4-gpu # 
extraConfigFiles:
  user.yaml: |+
    indexNode:
      scheduler:
        buildParallel: 1
    dataCoord:
      segment:
        maxSize: 1024
        sealProportion: 0.90
dataNode:
  replicas: 5
  resources:
    limits:
      cpu: 3
indexNode:
  replicas: 2
  resources:
    limits:
      cpu: 2
    requests:
      nvidia.com/gpu: "1"
    limits:
      nvidia.com/gpu: "1"

queryNode:
  replicas: 1
  resources:
    limits:
      cpu: 2
  resources:
    requests:
      nvidia.com/gpu: "1"
    limits:
      nvidia.com/gpu: "1"
minio:
  zones: 2
  resources:
    limits:
      cpu: 3
      memory: 8Gi
  persistence:
    storageClass: raid-hostpath
    storageClassName: raid-hostpath
etcd:
  persistence:
    storageClass: raid-hostpath
    storageClassName: raid-hostpath
pulsar:
  enabled: false
kafka:
  enabled: true
  global:
    storageClass: raid-hostpath

```
@xiaofan-luan I shared the code on the post. It is `reproducer_ingest.py.txt` just rename the extension to py.
I have found that with a similar number of Datanodes and cpu per Datanode the difference is still important between the two versions.
On larger scale data (1 million vecs, 2048 dim) I can get an ingestion speed of 51MB/s (total ingestion time of 150 seconds) on Milvus 2.4 while Milvus 2.5 gets to 21MB/s (total ingestion time of 367 seconds)
