### ISSUE TITLE
[Bug]: [laion-1b] When upgrading the 2.5 branch image the indexnodes were continuously oomkilled

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#40858]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.5-50241e4cf9-20250321
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
- indexNode: 3*8c16g
```
    dataCoord:
      channel:
        watchTimeoutInterval: 1800
      compaction:
        rpcTimeout: 7200
        timeout: 7200
      enableActiveStandby: true
      enableGarbageCollection: true
      segment:
        expansionRate: 1.15
        maxSize: 4096
        sealProportion: 0.08
```
### client
1. upgrading image to `cardinal-milvus-io-2.5-50241e4cf9-20250321` and the indexnode oomkilled
2. upgrading indexNode's memory to 64g and the indexnode oomkilled
3. updating the config `indexNode/workerSlotUnit` from 16 to 8 -> the indexnode oom
4. upgrading the config `indexNode/workerSlotUnit` from 8 to 4 -> indexnode running

![Image](https://github.com/user-attachments/assets/2a68015f-bbee-4e6f-ab57-e8c7196884da)

![Image](https://github.com/user-attachments/assets/5656a61c-f01f-44ea-9fdd-baea397d2113)

### Steps To Reproduce

```markdown

```

### Milvus Log

pods:
```
laion1b-test-2-milvus-datanode-686cdd8b9b-64jxp                   1/1     Running            0               2d17h   10.104.14.56    4am-node18   <none>           <none>
laion1b-test-2-milvus-indexnode-6795897f96-gr2rp                  1/1     Running            522 (31m ago)   2d15h   10.104.14.85    4am-node18   <none>           <none>
laion1b-test-2-milvus-indexnode-6795897f96-nxmnf                  1/1     Running            520 (34m ago)   2d15h   10.104.25.172   4am-node30   <none>           <none>
laion1b-test-2-milvus-indexnode-6795897f96-twvq4                  1/1     Running            531 (34m ago)   2d15h   10.104.17.178   4am-node23   <none>           <none>
laion1b-test-2-milvus-mixcoord-6d9cdbd488-ct22h                   1/1     Running            0               2d17h   10.104.6.37     4am-node13   <none>           <none>
laion1b-test-2-milvus-proxy-8575f484f4-dk67d                      1/1     Running            0               2d17h   10.104.30.94    4am-node38   <none>           <none>
```
