### ISSUE TITLE
[Bug]: The indexNode and queryNode were OOMKilled when concurrent DML requests were made to the partition-key collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#40891]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5-20250324-b534c9d8-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
```
    indexNode:
      replicas: 2
      resources:
        limits:
          cpu: "4" 
          memory: 16Gi
        requests:
          cpu: "4" 
          memory: 16Gi
    queryNode:
      replicas: 4
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
  config:
    common:
      enabledGrowingSegmentJSONKeyStats: true
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
### client
1. create a collection withfields: int64(pk) + floatVec + json_1
2. create the vector index
3. insert 30m entities -> flush
4. index again -> load
5. concurrent requests: search + upsert + flush
![Image](https://github.com/user-attachments/assets/cd140364-2039-4417-a282-682e599484bc)

### result
[last_terminated_reason](https://grafana-4am.zilliz.cc/explore?panes=%7B%22tzg%22:%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22level-zero-par-key-op-69-1436-milvus-.%2A%5C%22%7D%22,%22range%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221742787130285%22,%22to%22:%221742871912308%22%7D%7D%7D&schemaVersion=1&orgId=1)
1. indexNode `level-zero-par-key-op-69-1436-milvus-indexnode-577fbbf4c5-j4xv5` oomkilled
2. all queryNodes oomkilled

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/3deb9b9a-0b22-4b6d-8a9c-09f254121473?nodeId=goose-level-zero-stable-602123280
```

### Milvus Log

pods:
```
level-zero-par-key-op-69-1436-milvus-datanode-757b8b4b49-lxczp    1/1     Running     0               16h     10.104.23.33    4am-node27   <none>           <none>
level-zero-par-key-op-69-1436-milvus-indexnode-577fbbf4c5-j4xv5   1/1     Running     1 (12h ago)     16h     10.104.16.77    4am-node21   <none>           <none>
level-zero-par-key-op-69-1436-milvus-indexnode-577fbbf4c5-qd8vm   1/1     Running     0               16h     10.104.20.223   4am-node22   <none>           <none>
level-zero-par-key-op-69-1436-milvus-mixcoord-55dddcff49-dkpk5    1/1     Running     0               16h     10.104.21.97    4am-node24   <none>           <none>
level-zero-par-key-op-69-1436-milvus-proxy-545944fd9d-6nw6w       1/1     Running     0               16h     10.104.24.46    4am-node29   <none>           <none>
level-zero-par-key-op-69-1436-milvus-querynode-0-7cc878cbc29z68   1/1     Running     12 (9h ago)     16h     10.104.14.214   4am-node18   <none>           <none>
level-zero-par-key-op-69-1436-milvus-querynode-0-7cc878cbc2g742   1/1     Running     10 (9h ago)     16h     10.104.9.67     4am-node14   <none>           <none>
level-zero-par-key-op-69-1436-milvus-querynode-0-7cc878cbcfxvpn   1/1     Running     10 (9h ago)     16h     10.104.27.27    4am-node31   <none>           <none>
level-zero-par-key-op-69-1436-milvus-querynode-0-7cc878cbcjnkmv   1/1     Running     7 (9h ago)      16h     10.104.6.183    4am-node13   <none>           <none>
```
