### ISSUE TITLE
[Bug]: [streaming] The streamingNode panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#40967]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:  master-20250327-384d39ef-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
```
    streamingNode:
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
  config:
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
### client
1. create a collection with fields: pk + varchar_1 + varchar_2 + array_varchar_1 + json_1 + foat_vector + binary_vector + binary_vector + binary_vector
2. insert 3m -> flush
3. create index -> load
4. concurrent requests: insert + delete + flush + query + search + hybrid_search
5. streaming node panic and restarted:[sn_tcb2h.log](https://github.com/user-attachments/files/19486027/sn_tcb2h.log)![Image](https://github.com/user-attachments/assets/54bba06a-f929-44d5-8d0a-7ecfe9eac712)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/4bf7070b-58b9-4240-b69b-7cbb1a3b9462?nodeId=zong-dn-test-3a-3763909888
```

### Milvus Log

pods:
```
zong-dn-base-op-35-5741-milvus-datanode-7fc96d56c5-xsvrn          1/1     Running                  0               4h40m   10.104.25.111   4am-node30   <none>           <none>
zong-dn-base-op-35-5741-milvus-mixcoord-6ccb7dc6f8-bdnld          1/1     Running                  0               4h40m   10.104.14.62    4am-node18   <none>           <none>
zong-dn-base-op-35-5741-milvus-proxy-58d4f8c877-9qxxj             1/1     Running                  0               4h40m   10.104.19.57    4am-node28   <none>           <none>
zong-dn-base-op-35-5741-milvus-querynode-0-f5fdddc66-265cd        1/1     Running                  0               4h40m   10.104.24.14    4am-node29   <none>           <none>
zong-dn-base-op-35-5741-milvus-querynode-0-f5fdddc66-jgklc        1/1     Running                  0               4h40m   10.104.6.151    4am-node13   <none>           <none>
zong-dn-base-op-35-5741-milvus-querynode-0-f5fdddc66-pxcf6        0/1     Completed                0               4h40m   10.104.33.97    4am-node36   <none>           <none>
zong-dn-base-op-35-5741-milvus-querynode-0-f5fdddc66-s8pfb        1/1     Running                  0               4h40m   10.104.20.108   4am-node22   <none>           <none>
zong-dn-base-op-35-5741-milvus-querynode-0-f5fdddc66-vq76r        1/1     Running                  0               82m     10.104.19.60    4am-node28   <none>           <none>
zong-dn-base-op-35-5741-milvus-streamingnode-74c7f5cc8c-jd94s     1/1     Running                  0               4h40m   10.104.26.68    4am-node32   <none>           <none>
zong-dn-base-op-35-5741-milvus-streamingnode-74c7f5cc8c-tcb2h     1/1     Running                  1 (4h39m ago)   4h40m   10.104.27.68    4am-node31   <none>           <none>
```
