### ISSUE TITLE
[Bug]: When deploying with Helm, the configuration of API key and URL in text embedding function through extraConfigFiles is not taking effect

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#40978]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250327-9676365a-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

helm values
```
cluster:
  enabled: false

log:
  level: debug

image:
  all:
    repository: milvusdb/milvus
    tag: master-latest
    pullPolicy: Always
standalone:
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi
pulsarv3:
  enabled: false

pulsar:
  enabled: false

kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2

etcd:
  replicaCount: 3
  image:
    repository: milvusdb/etcd
    tag: 3.5.5-r2  
minio:
  mode: standalone
pulsar:
  enabled: false

extraConfigFiles:
  user.yaml: |+
    dataCoord:
      compaction:
        indexBasedCompaction: false
    indexCoord:
      scheduler:
        interval: 100
    function:
      textEmbedding:
        siliconflow:
          api_key: "sk-xxx"
          url: "https://api.siliconflow.cn/v1/embeddings"


```

### Expected Behavior

```
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=Missing credentials. Please pass `api_key`, or configure the MILVUSAI_SILICONFLOW_API_KEY environment variable in the Milvus service.)>
 (api_request.py:35)
[2025-03-28 14:06:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=Missing credentials. Please pass `api_key`, or configure the MILVUSAI_SILICONFLOW_API_KEY environment variable in the Milvus service.)> (api_request.py:36)
```

### Steps To Reproduce

```markdown

```

### Milvus Log

[log.log](https://github.com/user-attachments/files/19499766/log.log)

### Anything else?

When deploying Milvus through Helm or operator, if you need to modify the configurations in milvus.yaml, the changes are made in the user.yaml file, and the configurations in user.yaml have higher priority than those in milvus.yaml.

Need to check if the current function configuration reading has this logic implemented
