### ISSUE TITLE
[Bug]: [json-inverted] IndexNode were oomkilled when creating json key index

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41218]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5-20250409-409721d9-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server 
```
    indexNode:
      replicas: 2
      resources:
        limits:
          cpu: "4" 
          memory: 8Gi 
        requests:
          cpu: "2" 
          memory: 4Gi 
  config:
    common:
      **enabledGrowingSegmentJSONKeyStats: true
      enabledJsonKeyStats: true**
    dataCoord:
      enableActiveStandby: true
      **enabledJSONKeyStatsInSort: true**
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
### client
1. create a collection with fields: pk + vector + json_1
2. insert 10m entities, json data example: 
each json object has 100 keys, key_0 - key_99
```
{key_91': '04000', key_0': '04000', ... key_99': '04000'}
```
3. create index and indexNode oom
```
zong-json-perf-op-86-3115-milvus-indexnode-5bbd786f-cw74c         0/1     CrashLoopBackOff   156 (40s ago)     15h     10.104.23.2     4am-node27   <none>           <none>
zong-json-perf-op-86-3115-milvus-indexnode-5bbd786f-lw4kk         0/1     CrashLoopBackOff   156 (4m31s ago)   15h     10.104.18.127   4am-node25   <none>           <none>
```

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/60e69f71-0acc-4012-8671-27a82dc592d0?nodeId=zong-json-key-cron-1744214400-2755496899
```

### Milvus Log

pods:
```
zong-json-perf-op-86-3115-milvus-datanode-d9dc6bfd9-xl9xp         1/1     Running            0                 15h     10.104.16.251   4am-node21   <none>           <none>
zong-json-perf-op-86-3115-milvus-indexnode-5bbd786f-cw74c         0/1     CrashLoopBackOff   156 (40s ago)     15h     10.104.23.2     4am-node27   <none>           <none>
zong-json-perf-op-86-3115-milvus-indexnode-5bbd786f-lw4kk         0/1     CrashLoopBackOff   156 (4m31s ago)   15h     10.104.18.127   4am-node25   <none>           <none>
zong-json-perf-op-86-3115-milvus-mixcoord-644768677c-g8dk9        1/1     Running            0                 15h     10.104.26.89    4am-node32   <none>           <none>
zong-json-perf-op-86-3115-milvus-proxy-f5cc6694f-8dhzk            1/1     Running            0                 15h     10.104.26.90    4am-node32   <none>           <none>
zong-json-perf-op-86-3115-milvus-querynode-0-699468c788-4tt44     1/1     Running            0                 15h     10.104.16.252   4am-node21   <none>           <none>
zong-json-perf-op-86-3115-milvus-querynode-0-699468c788-jfmpp     1/1     Running            0                 15h     10.104.24.97    4am-node29   <none>           <none>
```
