### ISSUE TITLE
[Bug]: minio username and password are hardcoded

### ISSUE THREAD

**Issue by freemankevin** [milvus-io/milvus#41240]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.5.8
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04.5 lts
- CPU/Memory: x86
- GPU: a100
- Others:
```

### Current Behavior

```yaml
      #MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      #MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
```

The minio username and password are hard-coded as: minioadmin
If you change to other usernames and passwords, milvus will not start normally

### Expected Behavior

Supports passing environment variables with the latest minio user password field, and supports modifying the default simple username and password

```yaml
MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
```

### Steps To Reproduce

```markdown
compose files.

  etcd:
    container_name: etcd
    image: "${ETCD_IMAGE}"
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./data/milvus/etcd:/etcd
    restart: always
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - middleware

  minio:
    container_name: minio
    image: "${MINIO_IMAGE}"
    environment:
      #MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      #MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./data/milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - middleware

  milvus:
    container_name: milvus
    image: "${MILVUS_IMAGE}"
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./data/milvus/milvus:/var/lib/milvus
    restart: always
    ports:
      - "${MILVUS_PORT:-19530}:19530"
      - "${MILVUS_API_PORT:-9091}:9091"
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    networks:
      - middleware

  attu:
    container_name: attu
    image: "${ATTU_IMAGE:-zilliz/attu:v2.5.6}"
    ports:
      - "${ATTU_PORT:-3000}:3000"
    environment:
      - MILVUS_URL=milvus:19530
    restart: always
    depends_on:
      milvus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error',   () => process.exit(1));"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - middleware     


.env


# MinIO
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ROOT_USER="admin"
MINIO_ROOT_PASSWORD="Minio@Www.123.com"
MINIO_IMAGE="minio/minio:RELEASE.2023-03-20T20-16-18Z"

# etcd 
ETCD_IMAGE="quay.io/coreos/etcd:v3.5.18"

# Milvus
MILVUS_IMAGE="milvusdb/milvus:v2.5.8"
MILVUS_PORT="19530"
MILVUS_API_PORT="9091"

# Attu
ATTU_IMAGE="zilliz/attu:v2.5.6"
ATTU_PORT="3000"
```

### Milvus Log

[2025/04/11 07:29:32.863 +00:00] [WARN] [grpcclient/client.go:494] ["grpc client is nil, maybe fail to get client in the retry state"] [client_role=datacoord] [error="empty grpc client: find no available datacoord, check datacoord state"] [errorVerbose="empty grpc client: find no available datacoord, check datacoord state\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call.func2\n  | \t/workspace/source/internal/util/grpcclient/client.go:493\n  | github.com/milvus-io/milvus/pkg/v2/util/retry.Handle\n  | \t/workspace/source/pkg/util/retry/retry.go:128\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n  | \t/workspace/source/internal/util/grpcclient/client.go:486\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/workspace/source/internal/util/grpcclient/client.go:573\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/workspace/source/internal/util/grpcclient/client.go:589\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | \t/workspace/source/internal/distributed/datacoord/client/client.go:121\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics\n  | \t/workspace/source/internal/distributed/datacoord/client/client.go:434\n  | github.com/milvus-io/milvus/internal/rootcoord.getDataCoordMetrics\n  | \t/workspace/source/internal/rootcoord/util.go:257\n  | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func2\n  | \t/workspace/source/internal/rootcoord/quota_center.go:446\n  | golang.org/x/sync/errgroup.(*Group).Go.func1\n  | \t/go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) empty grpc client\nWraps: (3) find no available datacoord, check datacoord state\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString"]
[2025/04/11 07:29:32.863 +00:00] [WARN] [grpcclient/client.go:494] ["grpc client is nil, maybe fail to get client in the retry state"] [client_role=querycoord] [error="empty grpc client: find no available querycoord, check querycoord state"] [errorVerbose="empty grpc client: find no available querycoord, check querycoord state\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call.func2\n  | \t/workspace/source/internal/util/grpcclient/client.go:493\n  | github.com/milvus-io/milvus/pkg/v2/util/retry.Handle\n  | \t/workspace/source/pkg/util/retry/retry.go:128\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n  | \t/workspace/source/internal/util/grpcclient/client.go:486\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/workspace/source/internal/util/grpcclient/client.go:573\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/workspace/source/internal/util/grpcclient/client.go:589\n  | github.com/milvus-io/milvus/internal/distributed/querycoord/client.wrapGrpcCall[...]\n  | \t/workspace/source/internal/distributed/querycoord/client/client.go:114\n  | github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetMetrics\n  | \t/workspace/source/internal/distributed/querycoord/client/client.go:286\n  | github.com/milvus-io/milvus/internal/rootcoord.getQueryCoordMetrics\n  | \t/workspace/source/internal/rootcoord/util.go:239\n  | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func1\n  | \t/workspace/source/internal/rootcoord/quota_center.go:401\n  | golang.org/x/sync/errgroup.(*Group).Go.func1\n  | \t/go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) empty grpc client\nWraps: (3) find no available querycoord, check querycoord state\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString"]
[2025/04/11 07:29:32.864 +00:00] [WARN] [grpcclient/client.go:262] ["failed to get client address"] [error="find no available querycoord, check querycoord state"]
[2025/04/11 07:29:32.864 +00:00] [WARN] [grpcclient/client.go:262] ["failed to get client address"] [error="find no available datacoord, check datacoord state"]
[2025/04/11 07:29:32.864 +00:00] [WARN] [grpcclient/client.go:480] ["fail to get grpc client in the retry state"] [client_role=querycoord] [error="find no available querycoord, check querycoord state"]
[2025/04/11 07:29:32.864 +00:00] [WARN] [grpcclient/client.go:480] ["fail to get grpc client in the retry state"] [client_role=datacoord] [error="find no available datacoord, check datacoord state"]
[2025/04/11 07:29:33.264 +00:00] [WARN] [grpcclient/client.go:494] ["grpc client is nil, maybe fail to get client in the retry state"] [client_role=datacoord] [error="empty grpc client: find no available datacoord, check datacoord state"] [errorVerbose="empty grpc client: find no available datacoord, check datacoord state\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call.func2\n  | \t/workspace/source/internal/util/grpcclient/client.go:493\n  | github.com/milvus-io/milvus/pkg/v2/util/retry.Handle\n  | \t/workspace/source/pkg/util/retry/retry.go:128\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n  | \t/workspace/source/internal/util/grpcclient/client.go:486\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/workspace/source/internal/util/grpcclient/client.go:573\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/workspace/source/internal/util/grpcclient/client.go:589\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | \t/workspace/source/internal/distributed/datacoord/client/client.go:121\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics\n  | \t/workspace/source/internal/distributed/datacoord/client/client.go:434\n  | github.com/milvus-io/milvus/internal/rootcoord.getDataCoordMetrics\n  | \t/workspace/source/internal/rootcoord/util.go:257\n  | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func2\n  | \t/workspace/source/internal/rootcoord/quota_center.go:446\n  | golang.org/x/sync/errgroup.(*Group).Go.func1\n  | \t/go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) empty grpc client\nWraps: (3) find no available datacoord, check datacoord state\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString"]
[2025/04/11 07:29:33.264 +00:00] [WARN] [grpcclient/client.go:494] ["grpc client is nil, maybe fail to get client in the retry state"] [client_role=querycoord] [error="empty grpc client: find no available querycoord, check querycoord state"] [errorVerbose="empty grpc client: find no available querycoord, check querycoord state\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call.func2\n  | \t/workspace/source/internal/util/grpcclient/client.go:493\n  | github.com/milvus-io/milvus/pkg/v2/util/retry.Handle\n  | \t/workspace/source/pkg/util/retry/retry.go:128\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n  | \t/workspace/source/internal/util/grpcclient/client.go:486\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/workspace/source/internal/util/grpcclient/client.go:573\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/workspace/source/internal/util/grpcclient/client.go:589\n  | github.com/milvus-io/milvus/internal/distributed/querycoord/client.wrapGrpcCall[...]\n  | \t/workspace/source/internal/distributed/querycoord/client/client.go:114\n  | github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetMetrics\n  | \t/workspace/source/internal/distributed/querycoord/client/client.go:286\n  | github.com/milvus-io/milvus/internal/rootcoord.getQueryCoordMetrics\n  | \t/workspace/source/internal/rootcoord/util.go:239\n  | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func1\n  | \t/workspace/source/internal/rootcoord/quota_center.go:401\n  | golang.org/x/sync/errgroup.(*Group).Go.func1\n  | \t/go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) empty grpc client\nWraps: (3) find no available querycoord, check querycoord state\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString"]
[2025/04/11 07:29:33.266 +00:00] [WARN] [grpcclient/client.go:262] ["failed to get client address"] [error="find no available querycoord, check querycoord state"]
[2025/04/11 07:29:33.266 +00:00] [WARN] [grpcclient/client.go:480] ["fail to get grpc client in the retry state"] [client_role=querycoord] [error="find no available querycoord, check querycoord state"]
[2025/04/11 07:29:33.266 +00:00] [WARN] [grpcclient/client.go:262] ["failed to get client address"] [error="find no available datacoord, check datacoord state"]
[2025/04/11 07:29:33.266 +00:00] [WARN] [grpcclient/client.go:480] ["fail to get grpc client in the retry state"] [client_role=datacoord] [error="find no available datacoord, check datacoord state"]

**Comment by xiaofan-luan** [comment]
> MINIO_ROOT_USER

But did you need to change the username/ paasword for minio server?

**Comment by xiaofan-luan** [comment]
if you just change the user name password here then it is not matched with minio server

**Comment by freemankevin** [comment]
> /assign [@freemankevin](https://github.com/freemankevin)

The minio username and password can be modified, but milvus cannot be started. It seems that milvus only recognizes the default simple username and password, and the fields are still written in the old way.

**Comment by xiaofan-luan** [comment]
> > /assign [@freemankevin](https://github.com/freemankevin)
> 
> The minio username and password can be modified, but milvus cannot be started. It seems that milvus only recognizes the default simple username and password, and the fields are still written in the old way.

you need to modify the username/password  of minio. then setup the password to milvus

**Comment by freemankevin** [comment]
Tried it, seems to be completely ineffective.

**Comment by LoveEachDay** [comment]
@freemankevin You can easily add environment variable into `milvus` service in the docker-compose file. Using the following environment `MINIO_ACCESS_KEY_ID` and `MINIO_SECRET_ACCESS_KEY` for milvus. 
```
  milvus:
    container_name: milvus
    image: "${MILVUS_IMAGE}"
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
     MINIO_ACCESS_KEY_ID: <user>
     MINIO_SECRET_ACCESS_KEY: <pass>
```
Or you change the `milvus.yaml`:
```
minio:
  acccessKeyID: <user>
  secretAccessKey: <pass>
```

**Comment by freemankevin** [comment]
> MINIO_SECRET_ACCESS_KEY: <pass>

This is how it was written. I thought it was like passing environment variables like minio. Now this method is OK. Thanks to the experts. Can this be added to the documentation? Or updated to the docker-compose code. I guess other people will have this doubt too.

**Comment by maxshatskiy** [comment]
> [@freemankevin](https://github.com/freemankevin) You can easily add environment variable into `milvus` service in the docker-compose file. Using the following environment `MINIO_ACCESS_KEY_ID` and `MINIO_SECRET_ACCESS_KEY` for milvus.
> 
> ```
>   milvus:
>     container_name: milvus
>     image: "${MILVUS_IMAGE}"
>     command: ["milvus", "run", "standalone"]
>     security_opt:
>       - seccomp:unconfined
>     environment:
>       ETCD_ENDPOINTS: etcd:2379
>       MINIO_ADDRESS: minio:9000
>      MINIO_ACCESS_KEY_ID: <user>
>      MINIO_SECRET_ACCESS_KEY: <pass>
> ```
> 
> Or you change the `milvus.yaml`:
> 
> ```
> minio:
>   acccessKeyID: <user>
>   secretAccessKey: <pass>
> ```

@LoveEachDay @freemankevin @xiaofan-luan @yanliang567 
I also tried to change Minio password and login when  install using Milvus Operator.
But I am not sure should it be specified in components configuration or in config for minio or in both?? I when I change it ussually Milvus POD does not start.

For example, will the following change Minio password?
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: lulc
  labels:
    app: milvus
spec:
  mode: standalone

  # more about components here https://github.com/zilliztech/milvus-operator/blob/main/docs/CRD/milvus.md
  components:
    # components global configuration
    # cluster components configuration
    standalone:
        image: milvusdb/milvus:v2.5.7
        imagePullPolicy: IfNotPresent
        env:
          **- name: MINIO_ACCESS_KEY_ID**
            valueFrom:
              secretKeyRef:
                name: milvus-db-credentials
                key: accesskey
          **- name: MINIO_SECRET_ACCESS_KEY**
            valueFrom:
              secretKeyRef:
                name: milvus-db-credentials
                key: secretkey

  # override the fields of Milvus Cluster config template
  # complete set of https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml
  config:

    common:
      security:
        authorizationEnabled: true # Enable authorization, otherwise changed password will not take effect

    minio:
      #bucketName: milvus-bucket # Optional, config the bucket name of the bucket milvus will use
      rootPath: files
      useSSL: false
      **accessKeyID: DO I HAVE TO CHANGE IT HERE. AND HOW to use secrets?
      secretAccessKey: DO I HAVE TO CHANGE IT HERE. AND HOW to use secrets?**

  dependencies:
    # for etcd: https://artifacthub.io/packages/helm/bitnami/etcd/6.3.3
    etcd:
      inCluster:
        values:
          replicaCount: 1
          image:
            repository: milvusdb/etcd
            tag: 3.5.18-r1
            pullPolicy: IfNotPresent
    storage:
      type: "MinIO"
      # for MinIO config: https://github.com/zilliztech/milvus-helm/blob/master/charts/minio/values.yaml
      inCluster:
        values:
          mode: standalone
          resources:
            requests:
              memory: 30Gi
          image:
            repository: minio/minio
            tag: RELEASE.2023-03-20T20-16-18Z
            pullPolicy: IfNotPresent
          **existingSecret: "milvus-db-credentials" OR I HAVE TO CHANGE IT HERE**

```
