### ISSUE TITLE
[Bug]: [mixcoord] After merging into mixcoord, dataCoord and queryCoord have no metrics data

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41338]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20250415-a53f3024-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- deploy tool: operator
- deploy config:
```
    mixCoord:
      paused: false
      probes: null
      replicas: 1
      resources:
        limits:
          cpu: "1" 
          memory: 4Gi 
```
[metrics link](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-chaos-clu-qn&var-collection=All&var-app_name=milvus&from=1744697487667&to=1744715297719)
![Image](https://github.com/user-attachments/assets/f6a3e246-85ee-42c1-8d50-1661630b9859)

### Steps To Reproduce

```markdown

```
