### ISSUE TITLE
[Bug]: [json-inverted] The query returns unexpected results when using like `%` to match infix or suffix in the json value

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41386]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5-20250416-a89b611b-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
```
config:
    common:
      enabledGrowingSegmentJSONKeyStats: true
      enabledJsonKeyStats: true
    dataCoord:
      enableActiveStandby: true
      enabledJSONKeyStatsInSort: false
      jsonStatsTriggerCount: 10
      jsonStatsTriggerInterval: 10
```
### client
```
        json_4:
          other_params:
            dataset: random_algorithm
            algorithm_params:
              algorithm_name: mixed_values_json
              json_key: 'text.value'
              json_value_types: ["varchar"]
              specify_range: [0, 100]
              varchar_prefix: "z"
              varchar_filled_length: 100
              max_capacity: 5
```
1. insert 5m entities
    - id: range [0, 5m)
    - json_4: The data inserted into json_4 is of type string. Each value is generated by left-padding numbers in the range [0, 100) with the character 'z' to a total length of 100, and then converting the result into a string.
    for example:
```
c.query('id == 12 ', output_fields=["json_4"])
data: ["{'json_4': {'text': {'value': 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz12'}}, 'id': 12}"]
```
2. flush -> index -> load
3. concurrent upsert + flush + search
   - upsert data from pk 5000000, the json_4 object has 100 keys, each with the same value as pk, but as a string.
   example:
```
data: ["{'json_4': {'key_3': '5000000', 'key_8': '5000000', 'key_5': '5000000', 'extra_80': '5000000', 'key_9': '5000000', 'extra_60': '5000000', 'key_2': '5000000', 'key_0': '5000000', 'key_4': '5000000', 'key_6': '5000000', 'key_7': '5000000', 'key_1': '5000000'}, 'id': 5000000}"]
```

### result
query with like `z1%`, `%z1`, `%z1%`
- `z1%` return 0, expected 0 actual 0
- `%z1` return 0, expected 50000 actual 0
- `%z1%` return 0, expected 550000 actual 0
```
c.query('json_4["text"]["value"] like "z1%"', output_fields=["count(*)"])
data: ["{'count(*)': 0}"]
c.query('json_4["text"]["value"] like "%z1"', output_fields=["count(*)"])
data: ["{'count(*)': 0}"]
c.query('json_4["text"]["value"] like "%z1%"', output_fields=["count(*)"])
data: ["{'count(*)': 0}"]
```

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/dd7b4df8-4dea-41f1-96ae-90db1e7bdcbc?nodeId=zong-json-key-cron-1744819200-2223764376
```

### Milvus Log

pods:
```
zong-json-multi-op-54-6884-milvus-datanode-7558b9d6c-r4m2x        1/1     Running                  0               15h     10.104.17.5     4am-node23   <none>           <none>
zong-json-multi-op-54-6884-milvus-indexnode-dc7696cff-8dhfj       1/1     Running                  0               15h     10.104.21.151   4am-node24   <none>           <none>
zong-json-multi-op-54-6884-milvus-indexnode-dc7696cff-q4r7j       1/1     Running                  0               15h     10.104.27.111   4am-node31   <none>           <none>
zong-json-multi-op-54-6884-milvus-indexnode-dc7696cff-t8wd4       1/1     Running                  0               15h     10.104.25.148   4am-node30   <none>           <none>
zong-json-multi-op-54-6884-milvus-indexnode-dc7696cff-zbd68       1/1     Running                  0               15h     10.104.20.7     4am-node22   <none>           <none>
zong-json-multi-op-54-6884-milvus-mixcoord-66f99776cc-5vnsj       1/1     Running                  0               15h     10.104.24.250   4am-node29   <none>           <none>
zong-json-multi-op-54-6884-milvus-proxy-64fd69f965-qwdst          1/1     Running                  0               15h     10.104.24.251   4am-node29   <none>           <none>
zong-json-multi-op-54-6884-milvus-querynode-0-6f9d45887c-bk2tj    1/1     Running                  0               15h     10.104.21.152   4am-node24   <none>           <none>
zong-json-multi-op-54-6884-milvus-querynode-0-6f9d45887c-fdbhx    1/1     Running                  0               15h     10.104.25.149   4am-node30   <none>           <none>
zong-json-multi-op-54-6884-milvus-querynode-0-6f9d45887c-g8tzd    1/1     Running                  0               15h     10.104.6.199    4am-node13   <none>           <none>
zong-json-multi-op-54-6884-milvus-querynode-0-6f9d45887c-qptl6    1/1     Running                  0               15h     10.104.17.6     4am-node23   <none>           <none>
```
