### ISSUE TITLE
[Bug]: In concurrent upsert and search scene, the search latency of streamingNode is much higher than that of queryNode

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41500]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20250422-110c5aaa-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- resource
```
    streamingNode:
      replicas: 3
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
    queryNode:
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
```
- milvus config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    mixCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        growingMmapEnabled: true
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
```
### client
1. create a collection with fields: pk + 128dim vector + int64_1 (partition-key) + json_1
2. create index for vector `{'index_type': 'HNSW', 'index_param': {'M': 8, 'efConstruction': 200}}` and L2 metrics_type
3. insert 30m entities -> flush -> index again -> load
4. concurrent upsert & search
![Image](https://github.com/user-attachments/assets/51e19a5c-b63c-4033-91ad-39af6035d2d7)

### result
In concurrent upsert and search scene, the search latency of streamingNode is much higher than that of queryNode
[metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=sn-parkey-pulsar-op-4-2888&var-collection=All&var-app_name=milvus&from=1745310313885&to=1745351214037)
- avg latency of each queryNode:
![Image](https://github.com/user-attachments/assets/6653007f-c820-4cda-ad6a-194451bee2fa)
- queryable entitity num
![Image](https://github.com/user-attachments/assets/1c50c4d4-5a68-44de-a7c0-35821a752d76)
- cpu usage
![Image](https://github.com/user-attachments/assets/afa5aa71-6803-48f8-9745-f2fa94f55aa2)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/34ddc189-c319-49d1-8394-1935995fdfd8?nodeId=zong-sn-par-key-b6ldg-452498691
```

### Milvus Log

pods:
```
sn-parkey-pulsar-op-4-2888-etcd-0                                 1/1     Running            0                46h     10.104.34.39    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-etcd-1                                 1/1     Running            0                46h     10.104.27.26    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-etcd-2                                 1/1     Running            0                46h     10.104.24.5     4am-node29   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-datanode-74c7cdb995-bbp8j       1/1     Running            0                46h     10.104.16.143   4am-node21   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-datanode-74c7cdb995-tszkw       1/1     Running            0                46h     10.104.27.57    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-mixcoord-866bc57466-b4249       1/1     Running            0                46h     10.104.27.56    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-proxy-9cd7df5-t9qm6             1/1     Running            0                46h     10.104.16.144   4am-node21   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-querynode-0-67d4c7d68b-fbqmz    1/1     Running            0                46h     10.104.27.59    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-querynode-0-67d4c7d68b-sx7hb    1/1     Running            0                46h     10.104.14.2     4am-node18   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-streamingnode-969ff646f-2gkkv   1/1     Running            0                46h     10.104.24.23    4am-node29   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-streamingnode-969ff646f-h78x4   1/1     Running            0                46h     10.104.16.145   4am-node21   <none>           <none>
sn-parkey-pulsar-op-4-2888-milvus-streamingnode-969ff646f-zskjv   1/1     Running            0                46h     10.104.27.58    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-minio-0                                1/1     Running            0                46h     10.104.18.37    4am-node25   <none>           <none>
sn-parkey-pulsar-op-4-2888-minio-1                                1/1     Running            0                46h     10.104.24.12    4am-node29   <none>           <none>
sn-parkey-pulsar-op-4-2888-minio-2                                1/1     Running            0                46h     10.104.27.43    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-minio-3                                1/1     Running            0                46h     10.104.34.54    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-bookie-0                        1/1     Running            0                46h     10.104.27.42    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-bookie-1                        1/1     Running            0                46h     10.104.18.35    4am-node25   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-bookie-2                        1/1     Running            0                46h     10.104.34.51    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-bookie-init-dn7wg               0/1     Completed          0                46h     10.104.34.37    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-broker-0                        1/1     Running            0                46h     10.104.16.134   4am-node21   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-broker-1                        1/1     Running            0                46h     10.104.24.3     4am-node29   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-proxy-0                         1/1     Running            0                46h     10.104.34.35    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-proxy-1                         1/1     Running            0                46h     10.104.16.135   4am-node21   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-pulsar-init-7m2bv               0/1     Completed          0                46h     10.104.34.36    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-recovery-0                      1/1     Running            0                46h     10.104.27.27    4am-node31   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-zookeeper-0                     1/1     Running            0                46h     10.104.34.49    4am-node37   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-zookeeper-1                     1/1     Running            0                46h     10.104.33.245   4am-node36   <none>           <none>
sn-parkey-pulsar-op-4-2888-pulsar-zookeeper-2                     1/1     Running            0                46h     10.104.27.39    4am-node31   <none>           <none>
```
