### ISSUE TITLE
[Bug]: [streaming] After inserting the data, the index was built and then loaded, and 40712 entities were lost

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41563]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_full-b41ce80-20250427
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): woodpecker   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- streamingNode: 2 * 4c16g
- queryNode: 2 * 4c16g
- msgStreamType: woodpecker
- milvus.yaml config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        growingMmapEnabled: true
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
    streaming:
      walWriteAheadBuffer:
        capacity: 1m
        keepalive: 0.5s
```
### client
1. create a  collection `fouram_XeyLsmPN` with fields: id int64-pk + 128-dim vector + int64_1 partition_key + json_1
2. create vector index : {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}}
3. insert 10,000,000 entities with batch 50000
4. flush -> create same index again
5. loading collection and 40712 entities were lost
![Image](https://github.com/user-attachments/assets/2fb5596e-f12d-431c-a733-7441454da201)
```
c.query('', output_fields=["count(*)"], consistency_level="Strong")
data: ["{'count(*)': 9959288}"]
c.query('5000000 <= id < 5050000', output_fields=["count(*)"], consistency_level="Strong")
data: ["{'count(*)': 9288}"]
```

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/fdd50889-b3ce-476e-85aa-e1f615aa8c42?nodeId=zong-chaos-clu-wp-mix-3
```

### Milvus Log

- client debug log path: /test/fouram/log/2025_04_27/zong-chaos-clu-wp-mix-3-fouramf-client_40527/fouram_log.debug
- pods:
```
zong-chaos-clu-wp-mix-3-etcd-0                                    1/1     Running       0               5h17m   10.104.17.25    4am-node23   <none>           <none>
zong-chaos-clu-wp-mix-3-etcd-1                                    1/1     Running       0               5h17m   10.104.20.177   4am-node22   <none>           <none>
zong-chaos-clu-wp-mix-3-etcd-2                                    1/1     Running       0               5h17m   10.104.18.158   4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-datanode-7d764cc5d8-r8cml          1/1     Running       0               5h15m   10.104.33.43    4am-node36   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-datanode-7d764cc5d8-v74wd          1/1     Running       0               5h15m   10.104.14.131   4am-node18   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-mixcoord-9b655db7f-r69hw           1/1     Running       1 (4h26m ago)   5h15m   10.104.14.130   4am-node18   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-mixcoord-9b655db7f-scq9b           1/1     Running       2 (4h29m ago)   5h15m   10.104.19.31    4am-node28   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-proxy-66d7cc5b6b-s8jjt             1/1     Running       0               5h15m   10.104.18.160   4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-querynode-0-5b54bc44f7-47s9p       1/1     Running       0               5h15m   10.104.15.134   4am-node20   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-querynode-0-5b54bc44f7-pvvml       1/1     Running       0               5h15m   10.104.33.44    4am-node36   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-streamingnode-7f4fcc7494-4nnhj     1/1     Running       0               5h15m   10.104.18.161   4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-3-milvus-streamingnode-7f4fcc7494-xxxm5     1/1     Running       0               5h15m   10.104.19.32    4am-node28   <none>           <none>
zong-chaos-clu-wp-mix-3-minio-0                                   1/1     Running       0               5h17m   10.104.17.26    4am-node23   <none>           <none>
zong-chaos-clu-wp-mix-3-minio-1                                   1/1     Running       0               5h17m   10.104.20.178   4am-node22   <none>           <none>
zong-chaos-clu-wp-mix-3-minio-2                                   1/1     Running       0               5h17m   10.104.18.159   4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-3-minio-3                                   1/1     Running       0               5h17m   10.104.27.163   4am-node31   <none>           <none>
```
