### ISSUE TITLE
[Bug]: [streaming] Inserting data serially into a collection gets stuck, and cp lag continues to grow

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41575]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_full-b41ce80-20250427
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): woodpecker   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- sn: 2 * 4c16g
- qn: 2*4c16g
- config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        growingMmapEnabled: true
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
    streaming:
      walWriteAheadBuffer:
        capacity: 1m
        keepalive: 0.5s
```
### client
1. create a collection `fouram_kEmNapZ1` with fields: pk + vector + int64_1(partition_key) + json_1
```
 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}},
            {'name': 'int64_1', 'description': '', 'type': <DataType.INT64: 5>, 'is_partition_key': True}, {'name': 'json_1', 'description': '', 'type': <DataType.JSON: 23>}],
```
2. release collection
3. create vector index `{'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}}`
4. insert entities with batch 5w, insert hangs with requestId: `fc26f904188a4b50aa76ffe1acbb596b` 
![Image](https://github.com/user-attachments/assets/a0106026-3d69-4e34-8960-1aed408c259f)
![Image](https://github.com/user-attachments/assets/626ce871-3dc1-4afc-ab85-2f6ab8073301)
5. cp lag
![Image](https://github.com/user-attachments/assets/54f14400-8253-4107-8d6c-117f13eeff9c)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/workflows/qa/zong-chaos-clu-wp-mix-4?tab=workflow&nodeId=zong-chaos-clu-wp-mix-4-2852875763&nodePanelView=containers
```

### Milvus Log

pods:
```
zong-chaos-clu-wp-mix-4-etcd-0                                    1/1     Running     0               14h     10.104.24.104   4am-node29   <none>           <none>
zong-chaos-clu-wp-mix-4-etcd-1                                    1/1     Running     0               14h     10.104.21.37    4am-node24   <none>           <none>
zong-chaos-clu-wp-mix-4-etcd-2                                    1/1     Running     0               14h     10.104.30.68    4am-node38   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-datanode-65b47bb974-2stk7          1/1     Running     0               14h     10.104.20.156   4am-node22   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-datanode-65b47bb974-w6tvs          1/1     Running     0               14h     10.104.33.101   4am-node36   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-mixcoord-9dc667749-8xwq9           1/1     Running     2 (13h ago)     14h     10.104.6.99     4am-node13   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-mixcoord-9dc667749-fjvm4           1/1     Running     2 (13h ago)     14h     10.104.14.202   4am-node18   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-proxy-7fd9dbb7d6-nchhn             1/1     Running     0               14h     10.104.34.62    4am-node37   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-querynode-0-6cf9f8f989-kpjmd       1/1     Running     0               14h     10.104.19.98    4am-node28   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-querynode-0-6cf9f8f989-kwj9v       1/1     Running     0               14h     10.104.17.65    4am-node23   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-streamingnode-65bdd96b9b-pq5sg     1/1     Running     0               14h     10.104.16.120   4am-node21   <none>           <none>
zong-chaos-clu-wp-mix-4-milvus-streamingnode-65bdd96b9b-q2cqk     1/1     Running     0               14h     10.104.18.67    4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-4-minio-0                                   1/1     Running     0               14h     10.104.18.61    4am-node25   <none>           <none>
zong-chaos-clu-wp-mix-4-minio-1                                   1/1     Running     0               14h     10.104.24.102   4am-node29   <none>           <none>
zong-chaos-clu-wp-mix-4-minio-2                                   1/1     Running     0               14h     10.104.25.70    4am-node30   <none>           <none>
zong-chaos-clu-wp-mix-4-minio-3                                   1/1     Running     0               14h     10.104.21.35    4am-node24   <none>           <none>
```
