### ISSUE TITLE
[Bug]: [streaming] Query count(*) results in more than expected during chaos kill streamingNode container

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41570]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_full-b41ce80-20250427
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): woodpecker   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- streamingNode: 2 * 4c16g
- queryNode: 2 * 4c16g
- milvus.yaml config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        growingMmapEnabled: true
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
    streaming:
      walWriteAheadBuffer:
        capacity: 1m
        keepalive: 0.5s
```
### client test
1. create collection `fouram_jDzJ1VeB` with fields: pk + vector + int64_1(partition_key)  + json_1
2. create vector index HNSW
3. insert 10m entities -> flush -> index again -> load again
4. concurrent requests: query count(*) + search + upsert + flush + scene_search_test
- upsert: start pk from 0
- scene_search_test: create collection -> index -> load -> insert 1w -> flush-> index -> load -> search -> drop collection
5. apply chaos to kill a streamingNode container randomly every 2 minutes during 10 minutes

### result
During chaos, query count(*) return succ, but the actual count is more than expected 10m
![Image](https://github.com/user-attachments/assets/d6c373f6-969d-4e71-8b35-139790be1e21)

### Expected Behavior

always return 10m count(*)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/60f7c994-12e4-49a2-a476-892c155200b3?nodeId=zong-chaos-clu-wp-sn-3-4263864101
```

### Milvus Log

pods:
```
zong-chaos-clu-wp-sn-3-etcd-0                                     1/1     Running     0               13h     10.104.18.57    4am-node25   <none>           <none>
zong-chaos-clu-wp-sn-3-etcd-1                                     1/1     Running     0               13h     10.104.34.60    4am-node37   <none>           <none>
zong-chaos-clu-wp-sn-3-etcd-2                                     1/1     Running     0               13h     10.104.27.117   4am-node31   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-datanode-5747cd787d-9nmzm           1/1     Running     0               13h     10.104.34.61    4am-node37   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-datanode-5747cd787d-jl529           1/1     Running     0               13h     10.104.6.98     4am-node13   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-mixcoord-7bdb75c595-4ssbv           1/1     Running     0               13h     10.104.18.63    4am-node25   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-mixcoord-7bdb75c595-5kxtc           1/1     Running     0               13h     10.104.20.155   4am-node22   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-proxy-59dcc469fd-kf5kk              1/1     Running     0               13h     10.104.14.200   4am-node18   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-querynode-0-746c9d75fc-488xk        1/1     Running     0               13h     10.104.18.64    4am-node25   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-querynode-0-746c9d75fc-f4j45        1/1     Running     0               13h     10.104.19.97    4am-node28   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-streamingnode-5f8b94c55b-thhvq      1/1     Running     4 (12h ago)     13h     10.104.16.119   4am-node21   <none>           <none>
zong-chaos-clu-wp-sn-3-milvus-streamingnode-5f8b94c55b-zg6kt      1/1     Running     4 (12h ago)     13h     10.104.17.64    4am-node23   <none>           <none>
zong-chaos-clu-wp-sn-3-minio-0                                    1/1     Running     0               13h     10.104.18.58    4am-node25   <none>           <none>
zong-chaos-clu-wp-sn-3-minio-1                                    1/1     Running     0               13h     10.104.30.66    4am-node38   <none>           <none>
zong-chaos-clu-wp-sn-3-minio-2                                    1/1     Running     0               13h     10.104.27.118   4am-node31   <none>           <none>
zong-chaos-clu-wp-sn-3-minio-3                                    1/1     Running     0               13h     10.104.24.100   4am-node29   <none>           <none>
```
