### ISSUE TITLE
[Bug]: [woodpecker] Standalone terminated with log: SIGSEGV: segmentation violation in concurrent DML & DDL scene

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41579]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_full-b41ce80-20250427
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):woodpecker    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- msgStreamType: woodpecker
- standalone: 8c32g
- milvus config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        growingMmapEnabled: true
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
    streaming:
      walWriteAheadBuffer:
        capacity: 1m
        keepalive: 0.5s
    woodpecker:
      storage:
        type: local
```
### client
1. create a collection `fouram_vbQjB24p` with schema: 
```
{'auto_id': False,
 'description': '',
 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}},
            {'name': 'int32_1', 'description': '', 'type': <DataType.INT32: 4>}, {'name': 'float32_1', 'description': '', 'type': <DataType.FLOAT: 10>},
            {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100}},
            {'name': 'array_varchar_1', 'description': '', 'type': <DataType.ARRAY: 22>, 'params': {'max_length': 100, 'max_capacity': 10}, 'element_type': <DataType.VARCHAR: 21>},
            {'name': 'json_1', 'description': '', 'type': <DataType.JSON: 23>}],
 'enable_dynamic_field': False} (base.py:329)
```
2. create vector index `{'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 16, 'efConstruction': 200}}`
3. create scalar index
```
'scalars_index': {'float32_1': {'index_type': 'STL_SORT'},
                          'int32_1': {'index_type': 'BITMAP'},
                          'varchar_1': {'index_type': 'TRIE'},
                          'array_varchar_1': {'index_type': 'INVERTED'}}
```
4. insert 10m entities -> flush -> index again -> load
5. concurrent requests: insert + delete + flush + query + search + scene_search_test
- scene_search_test: create a collection -> insert 5k data -> flush -> vector index -> load -> search many times -> drop collection
![Image](https://github.com/user-attachments/assets/ee5d1395-38c7-4e02-b27e-0e3a59da324c)

### results
standalone terminated with error:
[Loki logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20pod%3D~%5C%22sn-ddl-wp-op-49-9976-milvus-standalone-cbbd5696-tv7rp%5C%22%7D%20%7C%3D%20%5C%22SIGSEGV%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221745739545192%22,%22to%22:%221745765579921%22%7D%7D%7D&schemaVersion=1&orgId=1)
![Image](https://github.com/user-attachments/assets/b6513700-0e4f-40d0-9209-8950e77c24ef)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/2c6c1aae-47b9-4ca6-aacc-505d04febc29?nodeId=zong-sn-scene-ddl-2-1939565451
```

### Milvus Log

pods:
```
sn-ddl-wp-op-49-9976-etcd-0                                       1/1     Running       0              23h     10.104.17.49    4am-node23   <none>           <none>
sn-ddl-wp-op-49-9976-milvus-standalone-cbbd5696-tv7rp             1/1     Running       1 (20h ago)    23h     10.104.14.132   4am-node18   <none>           <none>
sn-ddl-wp-op-49-9976-minio-665d68b6d9-jj8bg                       1/1     Running       0              23h     10.104.17.48    4am-node23   <none>           <none>
```
