### ISSUE TITLE
[Bug]: [woodpecker] The cp lag continues to grow and proxy oomkilled in concurrent DML and DQL scene

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41659]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_fix2-22e2ec9-20250429
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): woodpecker  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- mq: woodpecker
- config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
    streaming:
      walWriteAheadBuffer:
        capacity: 1m
        keepalive: 0.5s
```
### client tests
1. create a collection with schema
```
[2025-04-30 11:34:25,332 -  INFO - fouram]: [Base] Collection schema: 
{'auto_id': False,
 'description': '',
 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False},
 {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}},
            {'name': 'int32_1', 'description': '', 'type': <DataType.INT32: 4>}, {'name': 'float32_1', 'description': '', 'type': <DataType.FLOAT: 10>},
            {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100}},
            {'name': 'varchar_2', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100, 'enable_match': True, 'enable_analyzer': True}},
            {'name': 'array_varchar_1', 'description': '', 'type': <DataType.ARRAY: 22>, 'params': {'max_length': 100, 'max_capacity': 10}, 'element_type': <DataType.VARCHAR: 21>},
            {'name': 'json_1', 'description': '', 'type': <DataType.JSON: 23>}, {'name': 'binary_vector', 'description': '', 'type': <DataType.BINARY_VECTOR: 100>, 'params': {'dim': 128}},
            {'name': 'float16_vector', 'description': '', 'type': <DataType.FLOAT16_VECTOR: 102>, 'params': {'dim': 128}}, {'name': 'bfloat16_vector', 'description': '', 'type': <DataType.BFLOAT16_VECTOR: 103>, 'params': {'dim': 128}}],
 'enable_dynamic_field': False} (base.py:329)
```
2. build index
- float_vector: HNSW
- float16_vector: IVF_SQ8
- bfloat16_vector: IVF_FLAT
- binary_vector: BIN_IVF_FLAT
- float32_1: STL_SORT
- int32_1: BITMAP
- varchar_1: TRIE
- array_varchar_1: INVERTED
3. insert 5m -> flush -> index again -> load
4. concurrent requests: insert + delete + flush + query + search + hybrid_search 
```
    concurrent_params:
      concurrent_number: 30
      during_time: '120h'
      #during_time: '5m'
      interval: 300
    concurrent_tasks:
      - type: insert
        weight: 10
        params:
          nb: 100
          start_id: 5000000
          random_id: true
          random_vector: true
          shuffle_id: true
          timeout: 60
      - type: delete
        weight: 10
        params:
          delete_length: 70
          timeout: 60
      - type: flush
        weight: 1
        params:
          timeout: 120
          check_task: check_ignore_rate_limit
      - type: query
        weight: 9
        params:
          #expr: "TEXT_MATCH(varchar_2, 'ok 0')"
          expr: ''
          output_fields: ["array_varchar_1", "json_1"]
          limit: 20
          random_data: true
          random_count: 100
          random_range: [4000000, 7000000]
          timeout: 120
      - type: search
        weight: 20
        params:
          nq: 100
          top_k: 100
          #expr: 'not exists json_1["id"]'
          random_data: true
          search_param: {}
          timeout: 60
      - type: hybrid_search
        weight: 10
        params:
          nq: 10
          top_k: 10
          random_data: true
          output_fields: [id, binary_vector, float16_vector, bfloat16_vector, float_vector]
          check_task: check_search_output
          check_items:
            output_fields: [id, binary_vector, float16_vector, bfloat16_vector, float_vector]
          rerank:
            WeightedRanker: [0.4, 0.3, 0.3]
          reqs:
            - anns_field: binary_vector
              search_param:
                nprobe: 32
              top_k: 10
              expr: "int32_1 > 3000000"
            - anns_field: float16_vector
              search_param:
                nprobe: 32
              top_k: 5
              expr: "float32_1 < 5000000.1"
            - anns_field: bfloat16_vector
              search_param:
                nprobe: 32
              top_k: 12
```

### results
1. cp lag keeps growing
[metrics of zong-sn-wp-op-13-9508](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-sn-wp-op-13-9508&var-collection=All&var-app_name=milvus&from=1745997698000&to=1746345190000)
![Image](https://github.com/user-attachments/assets/42194951-c79d-431b-9d4e-ea52ce8f6e55)

2. proxy oomkilled multi times
[last terminated reason](https://grafana-4am.zilliz.cc/explore?panes=%7B%22_Hv%22:%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22zong-sn-wp-op-13-9508-milvus-proxy-8f99bc44c-gdxmr%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221745901545605%22,%22to%22:%221746504469548%22%7D%7D%7D&schemaVersion=1&orgId=1)
![Image](https://github.com/user-attachments/assets/958bf8bf-7ea9-4398-b7fb-cc26b6f7499a)

3. The delete request failed, but the number of L0 segments increased; Some segments are still in the growing state after more than 24 hours.
![Image](https://github.com/user-attachments/assets/f4a4fa34-f435-4af6-9406-40e735cfc5f2)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/6f61c1bd-e7e0-492f-bc19-2b203d5df137?nodeId=zong-sn-labor-1a-900339393
```

### Milvus Log

pods:
```
zong-sn-wp-op-13-9508-etcd-0                                    1/1     Running     0               6d14h   10.104.19.202   4am-node28   <none>           <none>
zong-sn-wp-op-13-9508-etcd-1                                    1/1     Running     0               6d14h   10.104.16.116   4am-node21   <none>           <none>
zong-sn-wp-op-13-9508-etcd-2                                    1/1     Running     0               6d14h   10.104.33.24    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-milvus-datanode-74bf859745-778v2          1/1     Running     0               6d14h   10.104.20.215   4am-node22   <none>           <none>
zong-sn-wp-op-13-9508-milvus-datanode-74bf859745-d54fm          1/1     Running     0               6d14h   10.104.34.203   4am-node37   <none>           <none>
zong-sn-wp-op-13-9508-milvus-datanode-74bf859745-k8mzd          1/1     Running     0               6d14h   10.104.17.180   4am-node23   <none>           <none>
zong-sn-wp-op-13-9508-milvus-datanode-74bf859745-qpz5c          1/1     Running     0               6d14h   10.104.33.31    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-milvus-mixcoord-69fcc65b9d-nmkhn          1/1     Running     0               6d14h   10.104.33.30    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-milvus-proxy-8f99bc44c-gdxmr              1/1     Running     4 (3d ago)      6d14h   10.104.34.204   4am-node37   <none>           <none>
zong-sn-wp-op-13-9508-milvus-querynode-0-5647595ccb-2knz9       1/1     Running     0               6d14h   10.104.33.33    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-milvus-querynode-0-5647595ccb-9htgg       1/1     Running     0               6d14h   10.104.17.181   4am-node23   <none>           <none>
zong-sn-wp-op-13-9508-milvus-querynode-0-5647595ccb-w45bq       1/1     Running     0               6d14h   10.104.34.206   4am-node37   <none>           <none>
zong-sn-wp-op-13-9508-milvus-querynode-0-5647595ccb-z9w5m       1/1     Running     0               6d14h   10.104.20.216   4am-node22   <none>           <none>
zong-sn-wp-op-13-9508-milvus-streamingnode-69548c9bdf-dnjvf     1/1     Running     1 (2d22h ago)   6d14h   10.104.34.205   4am-node37   <none>           <none>
zong-sn-wp-op-13-9508-milvus-streamingnode-69548c9bdf-v4l5q     1/1     Running     0               6d14h   10.104.33.32    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-minio-0                                   1/1     Running     0               6d14h   10.104.19.211   4am-node28   <none>           <none>
zong-sn-wp-op-13-9508-minio-1                                   1/1     Running     0               6d14h   10.104.15.57    4am-node20   <none>           <none>
zong-sn-wp-op-13-9508-minio-2                                   1/1     Running     0               6d14h   10.104.33.29    4am-node36   <none>           <none>
zong-sn-wp-op-13-9508-minio-3                                   1/1     Running     0               6d14h   10.104.16.130   4am-node21   <none>           <none>
```
