### ISSUE TITLE
[Bug]: [streaming] The hybrid_search failed: query failed: St12out_of_range :unordered_map::at

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41662]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_fix2-22e2ec9-20250429
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
```
  config:
    common:
      enabledJSONKeyStats: true
    dataCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    mixCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    queryNode:
      mmap:
        scalarField: true
        scalarIndex: true
        vectorField: true
        vectorIndex: true
    rootCoord:
      enableActiveStandby: true
```
### client tests
1. create a collection with schema
```
[2025-04-30 11:34:25,332 -  INFO - fouram]: [Base] Collection schema: 
{'auto_id': False,
 'description': '',
 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False},
 {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}},
            {'name': 'int32_1', 'description': '', 'type': <DataType.INT32: 4>}, {'name': 'float32_1', 'description': '', 'type': <DataType.FLOAT: 10>},
            {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100}},
            {'name': 'varchar_2', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100, 'enable_match': True, 'enable_analyzer': True}},
            {'name': 'array_varchar_1', 'description': '', 'type': <DataType.ARRAY: 22>, 'params': {'max_length': 100, 'max_capacity': 10}, 'element_type': <DataType.VARCHAR: 21>},
            {'name': 'json_1', 'description': '', 'type': <DataType.JSON: 23>}, {'name': 'binary_vector', 'description': '', 'type': <DataType.BINARY_VECTOR: 100>, 'params': {'dim': 128}},
            {'name': 'float16_vector', 'description': '', 'type': <DataType.FLOAT16_VECTOR: 102>, 'params': {'dim': 128}}, {'name': 'bfloat16_vector', 'description': '', 'type': <DataType.BFLOAT16_VECTOR: 103>, 'params': {'dim': 128}}],
 'enable_dynamic_field': False} (base.py:329)
```
2. build index
- float_vector: HNSW
- float16_vector: IVF_SQ8
- bfloat16_vector: IVF_FLAT
- binary_vector: BIN_IVF_FLAT
- float32_1: STL_SORT
- int32_1: BITMAP
- varchar_1: TRIE
- array_varchar_1: INVERTED
3. insert 5m -> flush -> index again -> load
4. concurrent requests: insert + delete + flush + query + search + hybrid_search 
```
    concurrent_params:
      concurrent_number: 30
      during_time: '120h'
      #during_time: '5m'
      interval: 300
    concurrent_tasks:
      - type: insert
        weight: 10
        params:
          nb: 100
          start_id: 5000000
          random_id: true
          random_vector: true
          shuffle_id: true
          timeout: 60
      - type: delete
        weight: 10
        params:
          delete_length: 70
          timeout: 60
      - type: flush
        weight: 1
        params:
          timeout: 120
          check_task: check_ignore_rate_limit
      - type: query
        weight: 9
        params:
          #expr: "TEXT_MATCH(varchar_2, 'ok 0')"
          expr: ''
          output_fields: ["array_varchar_1", "json_1"]
          limit: 20
          random_data: true
          random_count: 100
          random_range: [4000000, 7000000]
          timeout: 120
      - type: search
        weight: 20
        params:
          nq: 100
          top_k: 100
          #expr: 'not exists json_1["id"]'
          random_data: true
          search_param: {}
          timeout: 60
      - type: hybrid_search
        weight: 10
        params:
          nq: 10
          top_k: 10
          random_data: true
          output_fields: [id, binary_vector, float16_vector, bfloat16_vector, float_vector]
          check_task: check_search_output
          check_items:
            output_fields: [id, binary_vector, float16_vector, bfloat16_vector, float_vector]
          rerank:
            WeightedRanker: [0.4, 0.3, 0.3]
          reqs:
            - anns_field: binary_vector
              search_param:
                nprobe: 32
              top_k: 10
              expr: "int32_1 > 3000000"
            - anns_field: float16_vector
              search_param:
                nprobe: 32
              top_k: 5
              expr: "float32_1 < 5000000.1"
            - anns_field: bfloat16_vector
              search_param:
                nprobe: 32
              top_k: 12
```

### results
Some hybrid search failed
```
2025-04-30 14:41:33,122 [ERROR][handler]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to Query on QueryNode 4: worker(12) query failed: St12out_of_range :unordered_map::at)>, <Time:{'RPC start': '2025-04-30 14:41:28.504156', 'RPC error': '2025-04-30 14:41:33.122405'}> (decorators.py:140)
[2025-04-30 14:41:33,124 - ERROR - fouram]: (api_response) : [Collection.hybrid_search] <MilvusException: (code=65535, message=fail to Query on QueryNode 4: worker(12) query failed: St12out_of_range :unordered_map::at)>, [requestId: a77c03df21de4828998f3f18a3b90e84] (api_request.py:58)
```

### Expected Behavior

all hybrid search succ

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/6f61c1bd-e7e0-492f-bc19-2b203d5df137?nodeId=zong-sn-labor-1a-2451211907
```

### Milvus Log

pods:
```
zong-sn-base-op-34-1484-milvus-datanode-6d97c559bb-2fggl        1/1     Running     0              6d18h   10.104.34.210   4am-node37   <none>           <none>
zong-sn-base-op-34-1484-milvus-datanode-6d97c559bb-9n7nd        1/1     Running     0              6d18h   10.104.6.149    4am-node13   <none>           <none>
zong-sn-base-op-34-1484-milvus-datanode-6d97c559bb-dfszh        1/1     Running     0              6d18h   10.104.33.34    4am-node36   <none>           <none>
zong-sn-base-op-34-1484-milvus-datanode-6d97c559bb-nt87w        1/1     Running     0              6d18h   10.104.21.47    4am-node24   <none>           <none>
zong-sn-base-op-34-1484-milvus-mixcoord-6d5c84bdcc-hk74b        1/1     Running     0              6d18h   10.104.17.182   4am-node23   <none>           <none>
zong-sn-base-op-34-1484-milvus-proxy-6478f7f9fb-nns46           1/1     Running     0              6d18h   10.104.17.183   4am-node23   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-8rx4b     0/1     Completed   0              6d18h   10.104.24.35    4am-node29   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-bswj4     1/1     Running     0              4d9h    10.104.6.65     4am-node13   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-d42bq     0/1     Completed   0              4d7h    10.104.34.188   4am-node37   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-dmvtp     0/1     Completed   0              6d18h   10.104.16.133   4am-node21   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-gjwln     0/1     Completed   0              6d18h   10.104.34.211   4am-node37   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-j7s75     0/1     Completed   0              6d18h   10.104.18.229   4am-node25   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-kldtb     1/1     Running     0              29h     10.104.25.81    4am-node30   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-tk5dm     1/1     Running     0              3d5h    10.104.17.234   4am-node23   <none>           <none>
zong-sn-base-op-34-1484-milvus-querynode-0-7cddff8879-wq58m     1/1     Running     0              4d6h    10.104.14.102   4am-node18   <none>           <none>
zong-sn-base-op-34-1484-milvus-streamingnode-5d6856c954-gqvm5   1/1     Running     0              6d18h   10.104.15.58    4am-node20   <none>           <none>
zong-sn-base-op-34-1484-milvus-streamingnode-5d6856c954-qc4rt   1/1     Running     0              6d18h   10.104.20.217   4am-node22   <none>           <none>
```
