### ISSUE TITLE
[Bug]: Standalone was oomkilled due to stats task during concurrent inserts

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#41732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: chyezh-enhance_make_recovery_components_full_debug-5ed1fe0-20250508
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- standalone + rocksmq
```
    standalone:
      replicas: 1
      resources:
        limits:
          cpu: "2" 
          memory: 8Gi
        requests:
          cpu: "2" 
          memory: 8Gi
```
### client
1. create a collection with int64 pk fields and 768dim float32 vector
2. Insert data with batch 100 and concurrency 30
3. standalone oomkilled
```
stand-rocksmq-op-88-1495-etcd-0                                   1/1     Running                  0               22h    10.104.18.98    4am-node25   <none>           <none>
stand-rocksmq-op-88-1495-milvus-standalone-5c447d6d4b-vtkzt       1/1     Running                  3 (18m ago)     22h    10.104.20.96    4am-node22   <none>           <none>
stand-rocksmq-op-88-1495-minio-8687f698b4-r5df9                   1/1     Running                  0               22h    10.104.18.99    4am-node25   <none>           <none>
```

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/47cb4ab6-654b-43f1-bd4e-e5ebd15e426d?nodeId=zong-go-insert-batch100-con30-1-1303559674
```
