### ISSUE TITLE
[Bug]: [benchmark][caching layer] queryNode panic `SIGNO: 11; SIGNAME: Segmentation fault; SI_CODE: 1; SI_ADDR: 0x10` in concurrent DDL scene

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#42014]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250522-78010262-amd64 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.6.0rc125
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-mdqcp

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
caching-layer-scene22-etcd-0                                      1/1     Running     0               134m    10.104.16.124   4am-node21   <none>           <none>
caching-layer-scene22-etcd-1                                      1/1     Running     0               134m    10.104.30.19    4am-node38   <none>           <none>
caching-layer-scene22-etcd-2                                      1/1     Running     0               134m    10.104.20.159   4am-node22   <none>           <none>
caching-layer-scene22-milvus-datanode-77cfc79cd5-9jm7c            1/1     Running     0               134m    10.104.19.241   4am-node28   <none>           <none>
caching-layer-scene22-milvus-datanode-77cfc79cd5-f5hwz            1/1     Running     0               134m    10.104.25.165   4am-node30   <none>           <none>
caching-layer-scene22-milvus-datanode-77cfc79cd5-jdxlp            1/1     Running     0               134m    10.104.26.75    4am-node32   <none>           <none>
caching-layer-scene22-milvus-datanode-77cfc79cd5-vcd26            1/1     Running     0               134m    10.104.32.189   4am-node39   <none>           <none>
caching-layer-scene22-milvus-datanode-77cfc79cd5-wkbfw            1/1     Running     0               134m    10.104.21.32    4am-node24   <none>           <none>
caching-layer-scene22-milvus-mixcoord-5679474ff9-sltgh            1/1     Running     0               134m    10.104.20.152   4am-node22   <none>           <none>
caching-layer-scene22-milvus-proxy-54d66ff74c-thzqs               1/1     Running     0               134m    10.104.24.15    4am-node29   <none>           <none>
caching-layer-scene22-milvus-querynode-54d547c4bb-cjvsb           1/1     Running     22 (31m ago)    134m    10.104.20.153   4am-node22   <none>           <none>
caching-layer-scene22-milvus-streamingnode-697d4676cc-kjbmk       1/1     Running     0               134m    10.104.24.16    4am-node29   <none>           <none>
caching-layer-scene22-minio-0                                     1/1     Running     0               134m    10.104.16.125   4am-node21   <none>           <none>
caching-layer-scene22-minio-1                                     1/1     Running     0               134m    10.104.30.14    4am-node38   <none>           <none>
caching-layer-scene22-minio-2                                     1/1     Running     0               134m    10.104.20.165   4am-node22   <none>           <none>
caching-layer-scene22-minio-3                                     1/1     Running     0               134m    10.104.27.132   4am-node31   <none>           <none>
caching-layer-scene22-pulsarv3-bookie-0                           1/1     Running     0               134m    10.104.30.20    4am-node38   <none>           <none>
caching-layer-scene22-pulsarv3-bookie-1                           1/1     Running     0               134m    10.104.27.133   4am-node31   <none>           <none>
caching-layer-scene22-pulsarv3-bookie-2                           1/1     Running     0               134m    10.104.16.128   4am-node21   <none>           <none>
caching-layer-scene22-pulsarv3-bookie-init-q7c96                  0/1     Completed   0               134m    10.104.16.120   4am-node21   <none>           <none>
caching-layer-scene22-pulsarv3-broker-0                           1/1     Running     0               134m    10.104.30.8     4am-node38   <none>           <none>
caching-layer-scene22-pulsarv3-broker-1                           1/1     Running     0               134m    10.104.16.121   4am-node21   <none>           <none>
caching-layer-scene22-pulsarv3-proxy-0                            1/1     Running     0               134m    10.104.32.192   4am-node39   <none>           <none>
caching-layer-scene22-pulsarv3-proxy-1                            1/1     Running     0               134m    10.104.27.126   4am-node31   <none>           <none>
caching-layer-scene22-pulsarv3-pulsar-init-qw4kq                  0/1     Completed   0               134m    10.104.27.125   4am-node31   <none>           <none>
caching-layer-scene22-pulsarv3-recovery-0                         1/1     Running     1 (133m ago)    134m    10.104.30.7     4am-node38   <none>           <none>
caching-layer-scene22-pulsarv3-zookeeper-0                        1/1     Running     0               134m    10.104.20.164   4am-node22   <none>           <none>
caching-layer-scene22-pulsarv3-zookeeper-1                        1/1     Running     0               134m    10.104.30.22    4am-node38   <none>           <none>
caching-layer-scene22-pulsarv3-zookeeper-2                        1/1     Running     0               134m    10.104.17.200   4am-node23   <none>           <none>
```

![Image](https://github.com/user-attachments/assets/71200b37-c166-4161-9000-8ba4f18bd9c5)

### Steps To Reproduce

```markdown
1. deploy a cluster milvus
2. Create a collection with fields：'id'(pk), 'float_vector'(128dim), 'int64'(enabled partition key = 1024)
3. Build FLAT index on field 'float_vector' INVERTED index on 'id'
4. Insert 10m data
5. Flush collection
6. Rebuild index with the same params
7. Load collection
8. Concurrent requests:
  - scene_search_test: 'int64'(enabled partition key)
    (collection: create->insert->flush->index->load->search->drop)
```

### Anything else?

server config:
```
cluster:
  enabled: true
dataNode:
  enabled: true
  replicas: 5
  resources:
    limits:
      cpu: "8.0"
      memory: 16.0Gi
    requests:
      cpu: "5.0"
      memory: 9.0Gi
etcd:
  metrics:
    enabled: true
    podMonitor:
      enabled: true
extraConfigFiles:
  user.yaml: |-
    queryNode:
      segcore:
        tieredStorage:
          warmup:
            scalarField: async
            scalarIndex: async
            vectorField: async
            vectorIndex: async
image:
  all:
    repository: harbor.milvus.io/milvus/milvus
    tag: master-20250522-78010262-amd64
indexNode:
  enabled: false
kafka: {}
log:
  level: debug
metrics:
  serviceMonitor:
    enabled: true
minio:
  metrics:
    podMonitor:
      enabled: true
pulsarv3:
  broker:
    configData:
      defaultRetentionTimeInMinutes: "720"
queryNode:
  enabled: true
  resources:
    limits:
      cpu: "8.0"
      memory: 16Gi
    requests:
      cpu: "5.0"
      memory: 9Gi
streaming:
  enabled: true
streamingNode:
  resources:
    limits:
      cpu: "8.0"
      memory: 16Gi
    requests:
      cpu: "5.0"
      memory: 9Gi
```

client config:
```
{
     "dataset_params": {
          "metric_type": "L2",
          "dim": 128,
          "dataset_name": "sift",
          "dataset_size": "10m",
          "ni_per": 50000,
          "scalars_params": {
               "int64": {
                    "params": {
                         "is_partition_key": true
                    }
               }
          }
     },
     "collection_params": {
          "shards_num": 16,
          "other_fields": [
               "int64"
          ],
          "num_partitions": 1024
     },
     "index_params": {
          "index_type": "FLAT",
          "index_param": {}
     },
     "concurrent_params": {
          "concurrent_number": 20,
          "during_time": "5h",
          "interval": 20
     },
     "concurrent_tasks": [
          {
               "type": "scene_search_test",
               "weight": 10,
               "params": {
                    "data_size": 30000,
                    "other_fields": [
                         "varchar"
                    ],
                    "index_type": "FLAT",
                    "index_param": {},
                    "scalars_params": {
                         "varchar": {
                              "params": {
                                   "is_partition_key": true
                              }
                         }
                    },
                    "nq": 1,
                    "top_k": 1,
                    "search_param": {
                         "nprobe": 16
                    }
               }
          }
     ]
}
```
