### ISSUE TITLE
[Bug]: [benchmark][standalonr] In the scenario of multiple growing segments, milvus continues to upsert and then OOM

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#42028]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250522-2e353931-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):2.6.0rc125
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-dsr5k

server:
```
NAME                                                              READY   STATUS        RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-dsr5k-66-1332-etcd-0                                      1/1     Running       0               5h32m   10.104.23.114   4am-node27   <none>           <none>
fouramf-dsr5k-66-1332-milvus-standalone-6765559d89-5jm22          1/1     Running       1 (151m ago)    5h32m   10.104.15.175   4am-node20   <none>           <none>
fouramf-dsr5k-66-1332-minio-779d847f94-kzh7h                      1/1     Running       0               5h32m   10.104.23.115   4am-node27   <none>           <none>
```

<img width="1434" alt="Image" src="https://github.com/user-attachments/assets/a5e1bca4-1db9-4ff6-bbdd-f77ec7f09e37" />

<img width="887" alt="Image" src="https://github.com/user-attachments/assets/8a249d77-3be7-406f-9868-1652a25c2248" />

### Steps To Reproduce

```markdown
1. deploy a standalone milvus and reset quotaAndLimits
2. create a collection with fields: 'id', 'float_vector', 'varchar_1': is_partition_key(num_partition=1024)
3. build index HNSW
4. insert 5m data
5. flush collection
6. rebuild index HNSW
7. load colleciton
8. concurrent request: concurrent num=1
   - query: 'count(*)'
   - upsert: id 1 ~ 2000
```

### Anything else?

server config:
```
    standalone:
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 8
          memory: 16Gi
      profiling:
        enabled: true
    extraConfigFiles:
      user.yaml: |+
        quotaAndLimits:
          dml:
            enabled: true
            upsertRate:
              max: 0.5
            insertRate:
              max: 0.5
            deleteRate:
              max: 0.5
          quotaCenterCollectInterval: 1
```

client config:
```
{
     "dataset_params": {
          "dataset_name": "sift",
          "dim": 128,
          "dataset_size": "5m",
          "ni_per": 5000,
          "metric_type": "L2",
          "scalars_params": {
               "varchar_1": {
                    "params": {
                         "is_partition_key": true,
                         "max_length": 100
                    }
               }
          }
     },
     "collection_params": {
          "other_fields": [
               "varchar_1"
          ],
          "shards_num": 16,
          "num_partitions": 1024
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 8,
               "efConstruction": 200
          }
     },
     "concurrent_params": {
          "concurrent_number": 1,
          "during_time": "5h",
          "interval": 20
     },
     "concurrent_tasks": [
          {
               "type": "query",
               "weight": 1,
               "params": {
                    "expr": "",
                    "output_fields": [
                         "count(*)"
                    ],
                    "consistency_level": "Strong",
                    "check_task": "check_query_output_count",
                    "check_items": {
                         "query_count": 5000000
                    }
               }
          },
          {
               "type": "upsert",
               "weight": 1,
               "params": {
                    "nb": 2000,
                    "random_id": false,
                    "start_id": 1
               }
          }
     ]
}
```
