### ISSUE TITLE
[Bug]: [woodpecker] Concurrent inserts are stuck, leading to growing CP lag

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#42049]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20250523-48419da4-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
```
    dataCoord:
      enableActiveStandby: true
      gc: 
        dropTolerance: 1800
        interval: 1800
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
    woodpecker:
      logstore:
        logFileSyncPolicy:
          maxInterval: 200 
      storage:
        type: minio
```
### test
1. create a collection with pk, vector fields
2. insert with batch 100 concurrent [100, 50, 200]
```
root@laion-test-1:~/milvusGoBench# go run main.go -addr cluster-wp-minio-op-51-4141-milvus.qa-milvus:19530 -duration 11m -interval 1m -batch 100 -concurrency "200" --clean
```

### results
[grafana metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=cluster-wp-minio-op-51-4141&var-collection=All&var-app_name=milvus&from=1747968949319&to=1747988457485)
- streamingNode memory usage
![Image](https://github.com/user-attachments/assets/0a7e8321-f671-4900-9549-c963fd4b7b6f)
- inserts get stuck and cp lag
![Image](https://github.com/user-attachments/assets/3862d564-d3d1-4e3b-b09a-dc952f8b9d74)

### Steps To Reproduce

```markdown

```

### Milvus Log

pods:
```
cluster-wp-minio-op-51-4141-milvus-datanode-578dd7c676-rb2vq      1/1     Running     0               5h32m   10.104.18.232   4am-node25   <none>           <none>
cluster-wp-minio-op-51-4141-milvus-mixcoord-84ffc7778-qwt49       1/1     Running     0               5h42m   10.104.16.27    4am-node21   <none>           <none>
cluster-wp-minio-op-51-4141-milvus-proxy-6bb6c5cb9d-d4c85         1/1     Running     0               5h30m   10.104.18.237   4am-node25   <none>           <none>
cluster-wp-minio-op-51-4141-milvus-querynode-0-744dff97cf-nr27c   1/1     Running     0               5h35m   10.104.18.229   4am-node25   <none>           <none>
cluster-wp-minio-op-51-4141-milvus-streamingnode-7654c7545584mm   1/1     Running     0               5h37m   10.104.27.72    4am-node31   <none>           <none>
```
