### ISSUE TITLE
Tried to create index but not effect on milvus 0.10.3 rw node while keeping read on ro node

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4224]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
We built milvus ENV using 1 rw node + 2 ro node. 

Frist , we wrote data through rw node(index = IVFSQ8) , and then read data from 2 ro node  by domain name.
After a few days,  we wrote some data through rw node again while keeping reading from ro node  with qps =200 - 500. 
Then we tried to create index on rw node avoid raw search  but failed,
Because we found there were both index search and raw seach on grafana monitor.  

**Steps/Code to reproduce behavior**
1. keep reading on ro node with qps = 200-500
2. write data through rw node 
3. create index throgh rw node

**Expected behavior**

Keep searching from milvus ro node while  qps = 200, and write data throught rw node and  then create index.
We think creating index should succeed and there is no raw search.

**Method of installation**
- [X] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.5

cluster:
  enable: true
  role: rw

general:
  timezone: UTC+8
  meta_uri: mysql://milvus:XXXXXX@XXXXXXXX:2501/mil                                                                                                             vus_character

network:
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/mulvus/wal

cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: info
  trace.enable: true
  path: /var/log/milvus
  max_log_file_size: 1024MB
  log_rotate_num: 7

metric:
  enable: true
  address: kube-master-hzaz1-hubble.cloud.qiyi.domain
  port: 27243
  cluster_label: milvus_character
  instance_label: rw:10.16.135.92:20000

```

**Screenshots**
![image](https://user-images.githubusercontent.com/17443614/98900062-e9998900-24eb-11eb-94e8-cc70692b0ca0.png)

**Additional context**
