### ISSUE TITLE
request milvus got error: "Encounter exception when describe collection xxx"

### ISSUE THREAD

**Issue by cos120** [milvus-io/milvus#4233]
**Describe the bug**
creating single collection and index without write-ahead-log, copy whole db directory to another milvus and start milvus. 
sometimes we got 
```sh
[ERROR][SERVER][OnExecute][reqsched_thread] [search][0] Error occurred when describing collection xxx: Encounter exception when describe collection:bad parameter or other API misuse: bad parameter or other API misuse 
```
after this error occurs, milvus can't service again.  it occurs seldom.

**Expected behavior**
request successfully

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- host os: CentOS Linux release 7.4.1708 (Core)
- docker container: Ubuntu 18.04.4 LTS
- cpu:  Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
- memory: 6GiB

- Milvus version (master or released version)
0.10.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection: '*'
cluster:
  enable: false
  role: ro
general:
  meta_uri: sqlite://:@:/
  timezone: UTC+8
gpu:
  build_index_devices:
  - gpu0
  cache_size: 4GB
  enable: false
  gpu_search_threshold: 1000
  search_devices:
  - gpu0
logs:
  level: error
  log_rotate_num: 1
  max_log_file_size: 512MB
  path: /var/lib/milvus/logs
  trace.enable: false
metric:
  address: xxx
  enable: true
  port: 21000
network:
  bind.address: 0.0.0.0
  bind.port: 8600
  http.enable: true
  http.port: 8088
storage:
  auto_flush_interval: 0
  path: /var/lib/milvus
version: 0.5
wal:
  buffer_size: 256MB
  enable: false
  path: /var/lib/milvus/wal
  recovery_error_ignore: false
```

**Additional context**
i will test mysql later.
