### ISSUE TITLE
[Bug]: Milvus (v2.5.12 in standalone mode) does not start, the milvus-standalone container terminates with the errors context deadline exceeded, fail to list policy, and status 134. Errors indicate problems connecting to etcd.

### ISSUE THREAD

**Issue by Masalskiy** [milvus-io/milvus#42479]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.5.12
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 8/8
- GPU: -
- Others:
```

### Current Behavior

the problem has been repeated. I was uploading vectors to the database and at some point it stops responding and I can't restart the database. It comes to reading indexes. I see the display in the zilliz/attu interface.
catalog volumes 
first try
![Image](https://github.com/user-attachments/assets/f82dbf4a-96a7-4eed-9b0c-f1297e8d18d8)
second try
![Image](https://github.com/user-attachments/assets/c4aa6516-3de6-43fb-a2fc-70ee276b1ea7)

after the error, I changed docker-compose.yml and added milvus.yaml with changed parameters

```yml
ersion: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=10000
      - ETCD_QUOTA_BACKEND_BYTES=10294967296
      - ETCD_SNAPSHOT_COUNT=60000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
      - ./milvus.yaml:/milvus/configs/milvus.yaml

    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 90s
      timeout: 60s
      retries: 5

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.12
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 60s
      start_period: 290s
      timeout: 20s
      retries: 5
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
I am set parameters. I thought the problem was in the delays and the weak server.  I increased the CPU and RAM. before 2/4 after 8/8

requestTimeout: 120000
requestTimeout: 60000
equestTimeoutMs: 20000
initializeTimeout: 40000
healthCheckTimeout: 7000
channelTaskTimeout: 66000 # 1 minute¶
segmentTaskTimeout: 180000 # 2 minute¶
loadTimeoutSeconds: 1200
checkHealthRPCTimeout: 900000
brokerTimeout: 8000 
aitTimeout: 50000
requestResourceTimeout: 15000
maxRetryTimes: 5
maxEvictPerRetry: 5
maxIdleTime: 2200
quotaAndLimits:¶
enabled: false

What do I have to do to get the database working?

### Expected Behavior

When I do `sudo docker compose up`  then later container `milvus-standalone` don`t   exited with code 134 or code 1, (context deadline exceeded, fail to list policy)
Errors indicate problems with connecting to etcd

### Steps To Reproduce

```markdown
1. fill the database so that the storage volume is about 6gb
2. with base docker-compose config
3. insert data until the DB is disconnected
```

### Milvus Log

[milvus-standalone.log](https://github.com/user-attachments/files/20558622/milvus-standalone.log)

[etcd.log](https://github.com/user-attachments/files/20558670/etcd.log)

### Anything else?

I don't understand how to connect inside the etcd container
