### ISSUE TITLE
collection not exists

### ISSUE THREAD

**Issue by zhangchenglala** [milvus-io/milvus#4254]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I create a collection at the write node, and then I can't get the new collection from the read node. Is there any other way to solve this problem besides restart?

**Steps/Code to reproduce behavior**

**Expected behavior**
Metadata cache time is configurable

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.6

cluster:
  enable: true
  role: rw

general:
  timezone: UTC+8
  meta_uri: mysql://milvus:xxxx@xxxx/milvus_bi

network:
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  path: /var/lib/milvus/wal

cache:
  cache_size: 50GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 6GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: info
  trace.enable: true
  path: /var/log/milvus
  max_log_file_size: 1024MB
  log_rotate_num: 7

metric:
  enable: true
  address: xxxx
  port: 27243

```
