### ISSUE TITLE
[Bug]: [dn&in] The dataNode was oomkilled while bulk_import multi parquet files

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#42608]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus26-20250606-fe00c6e
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
- mq: pulsar
- dataNode:  **1* 4c16g**
- config
```
    common:
      enabledJSONKeyStats: true
    dataCoord:
      compaction:
        clustering:
          autoEnable: true
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    mixCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    queryNode:
      enableSegmentPrune: true
    rootCoord:
      enableActiveStandby: true
    streamingNode:
      walTruncate:
        retentionInterval: 30s 
        sampleInterval: 1m
```

### client
1. upload 16 laion1b_nolang dataset parquet files to minio
- parquet file schema
```
pk: int64
pk_5b: int64
caption: string
NSFW: string
similarity: double
width: int64
height: int64
original_width: int64
original_height: int64
md5: string
float32_vector: list<item: float>
  child 0, item: float
-- schema metadata --
```
![Image](https://github.com/user-attachments/assets/40287163-b5a4-4902-9ae5-81930f899b7e)

2. create collection with milvus collection schem:
```
    fields = [
        FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
        FieldSchema(name="pk_5b", dtype=DataType.INT64, is_clustering_key=True),
        FieldSchema(name="caption", dtype=DataType.VARCHAR, max_length=8192, enable_analyzer=True, enable_match=True),
        FieldSchema(name="NSFW", dtype=DataType.VARCHAR, max_length=8192),
        FieldSchema(name="similarity", dtype=DataType.DOUBLE),
        FieldSchema(name="width", dtype=DataType.INT64, is_partition_key=True),
        FieldSchema(name="height", dtype=DataType.INT64),
        FieldSchema(name="original_width", dtype=DataType.INT64),
        FieldSchema(name="original_height", dtype=DataType.INT64),
        FieldSchema(name="md5", dtype=DataType.VARCHAR, max_length=8192),
        FieldSchema(name="float32_vector", dtype=DataType.FLOAT_VECTOR, dim=VECTOR_DIM),
    ]
```
3. bulk import 16 parquet files
```
 files = []
    for parquet_file in parquet_files:
        files.append([parquet_file])
    resp = bulk_import(
        url=MILVUS_URL,
        collection_name=cname,
        files=files
    )
```

### results
dataNode was oom killed multi times
```
zong-sn-base-op-33-3381-milvus-datanode-758884f444-wff9w          1/1     Running            9 (7m32s ago)   2d15h   10.104.6.25     4am-node13   <none>           <none>
```

### Steps To Reproduce

```markdown

```

### Milvus Log

```
zong-sn-base-op-33-3381-milvus-datanode-758884f444-wff9w          1/1     Running            9 (7m32s ago)   2d15h   10.104.6.25     4am-node13   <none>           <none>
zong-sn-base-op-33-3381-milvus-mixcoord-57cf89c879-ld68n          1/1     Running            0               2d15h   10.104.27.101   4am-node31   <none>           <none>
zong-sn-base-op-33-3381-milvus-proxy-6db976c656-ht9ps             1/1     Running            0               2d15h   10.104.9.88     4am-node14   <none>           <none>
zong-sn-base-op-33-3381-milvus-querynode-0-5b5688668f-7r5tg       1/1     Running            0               2d15h   10.104.30.45    4am-node38   <none>           <none>
zong-sn-base-op-33-3381-milvus-querynode-0-5b5688668f-82qwz       1/1     Running            0               6h28m   10.104.19.199   4am-node28   <none>           <none>
zong-sn-base-op-33-3381-milvus-querynode-0-5b5688668f-8c7w6       1/1     Running            0               2d15h   10.104.13.108   4am-node16   <none>           <none>
zong-sn-base-op-33-3381-milvus-querynode-0-5b5688668f-h9jl4       1/1     Running            0               2d15h   10.104.14.103   4am-node18   <none>           <none>
zong-sn-base-op-33-3381-milvus-querynode-0-5b5688668f-tlfdw       1/1     Running            0               2d15h   10.104.6.26     4am-node13   <none>           <none>
zong-sn-base-op-33-3381-milvus-streamingnode-588fb45678-bfl4s     1/1     Running            0               2d15h   10.104.19.98    4am-node28   <none>           <none>
zong-sn-base-op-33-3381-milvus-streamingnode-588fb45678-nf764     1/1     Running            0               2d15h   10.104.15.160   4am-node20   <none>           <none>
```
