### ISSUE TITLE
Memory usage during searching on sift-1b/ivf_sq8 is more than expected with CPU-version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4499]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
dataset:
```
sift_1b_40000000_128_l2_sq8
```

**Steps/Code to reproduce behavior**
![scrnli_12_23_2020_3-02-42 PM](https://user-images.githubusercontent.com/56623710/102969179-37b09c00-4530-11eb-9622-ca8fe80f9647.png)

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
server config:
```
      milvus:
        db_config.primary_path: /test/milvus/db_data_011/sift_1b_4000000_128_l2_sq8
        cache_config.cpu_cache_capacity: 150GB
        engine_config.use_blas_threshold: 0
        engine_config.gpu_search_threshold: 200
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
        wal_enable: true
      collection_name: sift_1b_4000000_128_l2
      run_count: 2
      top_ks: [1, 10, 100, 1000]
      nqs: [1, 10, 100, 200, 500, 1000]
      search_params:
        -
          nprobe: 8
        -
          nprobe: 32

```
