### ISSUE TITLE
Memory usage during searching is increasing and unstable regardless of cluster config true or false

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4508]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. keep searching 10 hours on collection `sift_1m_2000000_128_l2_2` with  a writable pod (cluster=false), and the memory usage is as follows:
![Screenshot_2020-12-24 kubernetes pod dashboard - Grafana(3)](https://user-images.githubusercontent.com/27288593/103076358-8598d300-4608-11eb-9fc3-e1873d9ff552.png)

2. keep searching 10 hours on collection `sift_1m_2000000_128_l2_2` with  a writable pod  and three read-only pod (cluster=false), and the writable pod memory usage is as follows:
![Screenshot_2020-12-24 kubernetes pod dashboard - Grafana(1)](https://user-images.githubusercontent.com/27288593/103076435-b0832700-4608-11eb-97e0-e4c8862455f5.png)
the read-only pod memory usage is as follows:
![Screenshot_2020-12-24 kubernetes pod dashboard - Grafana(2)](https://user-images.githubusercontent.com/27288593/103076494-cee92280-4608-11eb-9df7-e678292e62e4.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
1. insert one million vectors with 2000000 segment_row_limit
2. build sq8 index with 16384 nlist
3. locust search 10 hours with nq=1, top_k=10, nprobe=16

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
locust_search_performance:
  collections:
    -
      milvus:
        db_config.primary_path: /test/milvus/db_data_011/cluster/sift_1m_2000000_128_l2_2
        suffix_path: true
        cache_config.cpu_cache_capacity: 8GB
        cache_config.insert_buffer_size: 2GB
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 1
        gpu_resource_config.enable: false
        gpu_resource_config.cache_capacity: 4GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
        wal_enable: true
#        cluster: true
#        external_mysql: true
#        readonly:
#          replicas: 3
      collection_name: sift_1m_2000000_128_l2_2
      ni_per: 50000
      build_index: true
      index_type: ivf_sq8
      index_param:
        nlist: 16384
      task:
        connection_num: 2
        clients_num: 100
        hatch_rate: 10
        during_time: 36000
        types:
          -
            type: query
            weight: 1
            params:
              top_k: 10
              nq: 1
              search_param:
                nprobe: 16

```

**Screenshots**

**Additional context**
