### ISSUE TITLE
QPS is not good in Milvus 0.11.0 comparing to the post in offical site

### ISSUE THREAD

**Issue by wineternity** [milvus-io/milvus#4557]
**Please state your issue using the following template and, most importantly, in English.**
user milvus 0.11.0 with default milvus.yaml config. change the cpu.cache_size to 72G 

run the perfomance test with wrk .
the collection is. sift 128. with datasize. 1000000.  index: ivf_pq nlist 512 , m 4 nprobe 1 , topk 10
the QPS is 
![image](https://user-images.githubusercontent.com/1088645/103402080-812f6580-4b86-11eb-8c1b-7fcffcb926a6.png)

the collection is. sift 128. with datasize. 10000000.  index: ivf_pq nlist 512 , m 4 nprobe 1 , topk 10
the QPS is 
![image](https://user-images.githubusercontent.com/1088645/103402140-c18ee380-4b86-11eb-82ea-8678a742e0be.png)

another collection  query 768. datasize. 6000000. index: ivf_pq nlist 512 , m 4 , nprobe 1, topk 10
the QPS is also poor
![image](https://user-images.githubusercontent.com/1088645/103402196-0581e880-4b87-11eb-8975-e01ebf095845.png)

how could you get the qps 2000/s in this test. https://www.milvus.io/cn/docs/benchmarks_azure

And even poor result got in locust test in benchamark with sift_1m dataset. 
![image](https://user-images.githubusercontent.com/1088645/103402217-2ba78880-4b87-11eb-82ea-3b33adc32c8b.png)

```
locust_search_performance:
  collections:
    -
      milvus:
        cache_config.cpu_cache_capacity: 8GB
        cache_config.insert_buffer_size: 2GB
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 1
        gpu_resource_config.enable: false
        gpu_resource_config.cache_capacity: 4GB
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
        wal_enable: true
      collection_name: ${collection}
      ni_per: 50000
      build_index: false
      index_type: ivf_sq8
      index_param:
        nlist: 16384
      task:
        connection_num: 2
        clients_num: 5000
        hatch_rate: 400
        during_time: 10
        types:
          -
            type: query
            weight: 1
            params:
              top_k: 100
              nq: 1
              # filters:
              #   -
              #     range:
              #       int64:
              #         LT: 0
              #         GT: 1000000
              search_param:
                nprobe: 1
```

**What would you like to be added ?**

**Why is this needed ?**
