### ISSUE TITLE
The index building performance of 0.10.6 branch is worse than that of 0.10.5 branch

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4727]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. in the 0.10.6 branch, index building time is longer than 0.10.5 for ivf_flat and ivf_pq
index ivf_pq:
![image](https://user-images.githubusercontent.com/27288593/108465736-8626b080-72bd-11eb-866f-e141fd8fbd86.png)
index ivf_flat:
![image](https://user-images.githubusercontent.com/27288593/108465824-a8203300-72bd-11eb-9a3e-eb5bc664edfd.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
index params for ivf_flat:
```
      collection_name: random_1m_1024_512_l2
      index_type: ivf_flat
      index_param:
        nlist: 16384 
```
index params for ivf_pq:
```
      collection_name: sift_1m_128_128_l2
      index_type: ivf_pq
      index_param:
        nlist: 8092
        m: 32
```
**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.10.6

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
