### ISSUE TITLE
While writing date to RW node, the Cache Usage of  RO node increase quickly

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4794]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
We built Milvus Env with 1rw node and 2ro nodes, they shared data with share filesystem.
We found while we wrote data  to RW node, the Cache Usage of  RO node increase quickly.
please see the following:
1. write data (Client)
![image](https://user-images.githubusercontent.com/17443614/110424195-5eb54d80-80dd-11eb-98ce-37ee9213668f.png)

2. rw node moniter
![image](https://user-images.githubusercontent.com/17443614/110424302-8c9a9200-80dd-11eb-9c15-f0e5d67d806f.png)

3. ro node moniter
![image](https://user-images.githubusercontent.com/17443614/110424367-a63bd980-80dd-11eb-8b7d-24582b9de668.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**

```yaml
version: 0.5

cluster:
enable: true
role: rw

general:
timezone: UTC+8
meta_uri: (省略)

network:
bind.address: 0.0.0.0
bind.port: 19530
http.enable: true
http.port: 19121

storage:
path: /var/lib/milvus
auto_flush_interval: 1

wal:
enable: true
recovery_error_ignore: true
buffer_size: 256MB
path: /var/lib/milvus/wal

cache:
cache_size: 4GB
insert_buffer_size: 1GB
preload_collection:

gpu:
enable: false
cache_size: 1GB
gpu_search_threshold: 1000
search_devices:cartoon
- gpu0
build_index_devices:
- gpu0

logs:
level: info
trace.enable: true
path: /var/log/milvus
max_log_file_size: 1024MB
log_rotate_num: 7

metric:
enable: true
address: kube-master-hzaz1-hubble.cloud.qiyi.domain
port: 27243
cluster_label: milvus_cartoon
instance_label: rw:k8s_cartoon	 	

```

**Screenshots**

**Additional context**
