### ISSUE TITLE
Milvus crashing with `free(): invalid pointer` on inserting vectors

### ISSUE THREAD

**Issue by hartfelt** [milvus-io/milvus#4848]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Inserting a vector into milvus crashes the server with the message `free(): invalid pointer`

**Steps/Code to reproduce behavior**
Here's a minimal sample program, with a similar setup to what I'm trying to do in my actual project:
(The actual vectors would be of length 768, but that doesn't seem to make any difference for the sake of this problem)

```python
from milvus import Milvus, MetricType, IndexType

milvus = Milvus(host="localhost", port=19530)

record = [
	-0.03644951432943344, 0.03700318560004234, -0.05371199920773506, 0.00838780403137207,
	0.02592720091342926, -0.012614944949746132, 0.030186856165528297, -0.003707726253196597,
	-0.022971007972955704, -0.0438711978495121, 0.058944880962371826, -0.03153105452656746,
	-0.0016110327560454607, -0.08753041177988052, 0.04356173798441887, -0.004882387816905975,
	0.09493870288133621, 0.014008271507918835, 0.01241231244057417, 0.00046556926099583507,
	0.002853832906112075, -0.02555236592888832, -0.006986357271671295, 0.018231555819511414,
	0.03665747866034508, -0.2015785425901413, -0.03151408210396767, 0.04647446423768997,
	0.03178019821643829, -0.052712470293045044, -0.043200910091400146, 0.00800394732505083]

collection = 'test_hartfelt_crash'
_, ok = milvus.has_collection(collection)
if ok:
	milvus.drop_collection(collection)

milvus.create_collection({
	"collection_name": collection,
	"dimension": 32,
	"metric_type": MetricType.L2})
milvus.create_index(collection, IndexType.ANNOY, {
	"n_trees": 20,
	"search_k": 60})

# This will crash milvus:
milvus.insert(
	collection_name=collection,
	records=[record],
	ids=[19735])
```

**Expected behavior**
Vector should be inserted, and the server should continue to run

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
Build from source (cpu edition), running both on a production server and my laptop (without docker, in both cases)
Both are running Debian 10, amd64 arch.

- Milvus version (master or released version)
Release v1.0 (but I had the same problem with 0.10.6, though I didn't have time to look closely into it then)

**Configuration file**
Config file from my local machine (with comments stripped):
The config for the production server is identical, except that general.meta_uri is a mysql database, instead of sqlite.

```yaml
version: 0.5

cluster:
  enable: false
  role: rw

general:
  timezone: UTC+0
  meta_uri: sqlite://:@:/

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

fpga:
   enable: false
   search_devices:
     - fpga0

logs:
  level: debug
  trace.enable: true
  path: /var/log/milvus
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091
```

**Additional context**
This is the output when milvus starts:

```
    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/
Welcome to use Milvus!
Milvus Release version: v1.0.0, built at 2021-03-23 12:30.42, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 21ea92ec7e57ab00cca671d74195c4eaa81869a2
Loading configuration from: /etc/milvus.yaml
2021-03-24 13:31:01,039 ERROR [default] [SERVER][GetSysCgroupMemLimit][milvus_server] Failed to read /sys/fs/cgroup/memory/memory.limit_in_bytes, reason: basic_ios::clear: iostream error
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Supported CPU instruction sets: avx2, sse4_2
FAISS hook AVX2
Milvus server started successfully!
```

I notice the failure to read memory.limit_in_bytes, ever though that file exists. The following is from my local machine

```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
```

Is there any other info I can supply?

Thank you in advance!
