### ISSUE TITLE
gpu no usage during index building

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#486]
**Describe the bug**

dataset : sift-1b
index_type: ivf_sq8

```
| 27%   32C    P8     9W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 27%   32C    P8    21W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 27%   32C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:83:00.0 Off |                  N/A |
| 27%   32C    P8     4W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |

```
config settings:
```
root@2e7587acffa7:/opt/milvus# cat conf/server_config.yaml
#  Default values are used when you make no changes to the following parameters.
server_config:
  address: 0.0.0.0                  # milvus server ip address (IPv4)
  port: 19530                       # milvus server port, must in range [1025, 65534]
  deploy_mode: single               # deployment type: single, cluster_readonly, cluster_writable
  time_zone: UTC+8                  # time zone, must be in format: UTC+X

db_config:
  primary_path: /opt/milvus  #  path used to store data and meta
  secondary_path:                   # path used to store data only, split by semicolon

  backend_url: sqlite://:@:/        # URI format: dialect://username:password@host:port/database
                                    # Keep 'dialect://:@:/', and replace other texts with real values
                                    # Replace 'dialect' with 'mysql' or 'sqlite'

  insert_buffer_size: 4             # GB, maximum insert buffer size allowed, must be a positive integer
                                    # sum of insert_buffer_size and cpu_cache_capacity cannot exceed total memory

  preload_table:                    # preload data at startup, '*' means load all tables, empty value means no preload
                                    # you can specify preload tables like this: table1,table2,table3

metric_config:
  enable_monitor: true             # enable monitoring or not, must be a boolean
  collector: prometheus             # prometheus
  prometheus_config:
    port: 8080                      # port prometheus uses to fetch metrics, must in range [1025, 65534]

cache_config:
  cpu_cache_capacity: 160            # GB, size of CPU memory used for cache, must be a positive integer
  cache_insert_data: false          # whether to load inserted data into cache, must be a boolean

engine_config:
  use_blas_threshold: 1100          # if nq <  use_blas_threshold, use SSE, faster with fluctuated response times
                                    # if nq >= use_blas_threshold, use OpenBlas, slower with stable response times
  gpu_search_threshold: 1100        # threshold beyond which the search computation is executed on GPUs only

gpu_resource_config:
  enable: true                     # whether to enable GPU resources
  cache_capacity: 4                 # GB, size of GPU memory per card used for cache, must be a positive integer
  search_resources:                 # define the GPU devices used for search computation, must be in format gpux
    - gpu0
    - gpu1
    - gpu2
    - gpu3
  build_index_resources:            # define the GPU devices used for index building, must be in format gpux
    - gpu0
    - gpu1
    - gpu2
    - gpu3
root@2e7587acffa7:/opt/milvus# 


```

**Steps/Code to reproduce behavior**
use default config (gpu0) to build index,
it can use gpu to build
and then update config, set build_index_resources to gpu0,gpu1,..
start building index with no gpu usage

**Expected behavior**

**Environment details**
0.6.0-GPU-version with internal faiss

**Screenshots**

**Additional context**
