### ISSUE TITLE
No search results when using "term" or "range" in DSL query

### ISSUE THREAD

**Issue by maximilianbiber** [milvus-io/milvus#4907]
**Please state your issue using the following template and, most importantly, in English.**
The search oftentimes does not return any results when using dsl query even though data exists in the search engine for the specified "term" or "range". This is not always the case, but happens **frequently**, which makes the search not usable!
This does neither work using v0.11.0 (Docker/CPU) or v0.11.1 (compiled from source)

**Describe the bug**
Searching without any "term" or "range" filter works fine, i.e. I use a vector from the dataset itself as query vector and get the query vector as result with distance 0.0. But when using the same query vector including one of its "field" as e.g. "term" dsl, the search does not return any results. (this also applies when using a "range" dsl)

The collection contains:
* ~5.5M feature vectors (dim=128) with 13 "fields" (e.g. "A", "B", "C")
* 5 partitions ("_default" + 4 custom partitions), with 2 segments per partition
with the following setup:
```
collection_param = {
   "fields": [
       {"name": "A", "type": DataType.INT64},
       {"name": "B", "type": DataType.INT64},
       {"name": "C", "type": DataType.DOUBLE},
       {"name": "D", "type": DataType.DOUBLE},
       {"name": "E", "type": DataType.DOUBLE},
       {"name": "F", "type": DataType.DOUBLE},
       {"name": "G", "type": DataType.DOUBLE},
       {"name": "H", "type": DataType.DOUBLE},
       {"name": "I", "type": DataType.INT64},
       {"name": "J", "type": DataType.INT32},
       {"name": "K", "type": DataType.INT32},
       {"name": "L", "type": DataType.INT32},
       {"name": "M", "type": DataType.INT32},
       {"name": "feature", "type": DataType.FLOAT_VECTOR, "params": {"dim": 128}}
   ],
   "segment_row_limit": 1000000,
   "auto_id": False
}
```
* Used HNSW Index (with {"M": 16, "efConstruction": 512})

**Steps/Code to reproduce behavior**
Working example **without** a "term" dsl:
```
_HOST = 'host' # used host not shown here
_PORT = 'port' # used port not shown here
client = Milvus(_HOST, _PORT, handler="GRPC")

# get query feature vector from search collection itself (by ID) # used collection_name not shown here
query_entity = client.get_entity_by_id(collection_name=collection_name, ids=[6767089394630100520])
query_vector = []
for query in query_entity:
    query_vector.append(query.get("feature"))  # "feature" is the used vector "field"; dim=128

# Define DSL --> WITHOUT "term" filter
search_dsl = {
    "bool": {
        "must":[
#             {
#                 "term": {"A": [int(6767089391172383232)]}
#             },
            {
                "vector": {
                   "feature": {"topk": 10, "query": query_vector[:1], "metric_type": "L2", "params": {"ef": 512}}
                }
            }
        ]
    }
}

# Search
results = client.search(
    collection_name=collection_name,
    partition_tags=[],
    dsl=search_dsl,
    fields=["A", "B", "C"]
)

for entities in results:
    print(f"Found {len(entities)} results!")
    for i, topk in enumerate(entities):
        print(f"Result #{i+1}")
        print(f"ID: {topk.id}")
        print(f"Distance: {topk.distance}")
        print(f"A: {topk.entity.get('A')}")
        print(f"B: {topk.entity.get('B')}")
        print(f"C: {topk.entity.get('C')}\n")
```
**Output**: finds the query vector itself with correct ID and Distance
```
Found 10 results!
Result #1
ID: 6767089394630100520
Distance: 0.0
A: 6767089391172383232
B: 1613336858
C: 4775.0498046875

Result #2
.....
```
--> **BUG HERE**
Not working example: same as above but **with** a "term" dsl:
Here I use field "A" as "term" filter from the "Result 1" above and same query vector
```
_HOST = 'host' # used host not shown here
_PORT = 'port' # used port not shown here
client = Milvus(_HOST, _PORT, handler="GRPC")

# get query feature vector from search collection itself (by ID)
query_entity = client.get_entity_by_id(collection_name=collection_name, ids=[6767089394630100520])
query_vector = []
for query in query_entity:
    query_vector.append(query.get("feature"))  # "feature" is the used vector "field"; dim=128

# Define DSL --> WITH "term" filter
search_dsl = {
    "bool": {
        "must":[
            {
                "term": {"A": [int(6767089391172383232)]}
            },
            {
                "vector": {
                   "feature": {"topk": 10, "query": query_vector[:1], "metric_type": "L2", "params": {"ef": 512}}
                }
            }
        ]
    }
}

# Search
results = client.search(
    collection_name=collection_name,
    partition_tags=[],
    dsl=search_dsl,
    fields=["A", "B", "C"]
)

for entities in results:
    print(f"Found {len(entities)} results!")
    for i, topk in enumerate(entities):
        print(f"Result #{i+1}")
        print(f"ID: {topk.id}")
        print(f"Distance: {topk.distance}")
        print(f"A: {topk.entity.get('A')}")
        print(f"B: {topk.entity.get('B')}")
        print(f"C: {topk.entity.get('C')}\n")
```
**Output**: Does not find query vector itself!
```
Found 0 results!
```

**Expected behavior**
Get search results when using a dsl query with "term" or "range" filter where data exists in the search engine

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
  * Ubuntu 20.04.1
  * CPU
  * Memory: 500G

- Milvus version (master or released version)
  - v0.11.0 (Docker/cpu)
  - v0.11.1 (Build from source) (or "experimental.1")

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.6

cluster:
  enable: false
  role: rw

general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/

network:
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  path: /var/lib/milvus/wal

cache:
  cache_size: 50GB
  insert_buffer_size: 15GB
  preload_collection: "*"
  max_concurrent_insert_request_size: 15GB

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

```

**Questions**
Is this a known issue?

When will the new version v1.0.0 support scalar field filtering? This is a critical feature for our use-case
