### ISSUE TITLE
Data files are not cleaned up after merge

### ISSUE THREAD

**Issue by rky0930** [milvus-io/milvus#4956]
**Describe the bug**
After the segments are merged, the remaining files are not cleanup and remain. 
Soft delete is executed, but hard delete is not.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
After all entities are inserted, and only the merged segments remain.
The files created in the process of merge are deleted in the background, saving file system capacity

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- mishards (cpu: '2', memory: 2Gi)
- readonly (cpu: '4', memory: 8Gi)
- writable (cpu: '8', memory: 10Gi)
- EFS, RDS

- Milvus version (master or released version)
milvusdb/milvus:1.0.0-cpu-d030521-1ea92e

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.5 
 
cluster:
  enable: true
  role: rw

general:
  timezone: UTC+8

 network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

 storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

 wal:
  enable: false
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/db/wal

cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0


metric:
  enable: false
  address: 127.0.0.1
  port: 9091
```

**Screenshots**
**Data file list**
```
[root@milvus-writable-7c45b78c4c-gns8j 1618801438425356000]# du -h -d1 | sort -nr
940M    ./1618803778475847000
936M    ./1618805063272023000
851M    ./1618803673238671000
781M    ./1618804918745904000
693M    ./1618804808892122000
654M    ./1618803479024943000
583M    ./1618804685540457000
578M    ./1618803385962883000
538M    ./1618805856154113000
494M    ./1618803290403082000
489M    ./1618804591810154000
459M    ./1618805753445001000
...
3.8M    ./1618804793053724000
3.8M    ./1618804313904597000
3.8M    ./1618804224919654000
3.6M    ./1618805613666656000
3.6M    ./1618805029226228000
3.6M    ./1618803273841237000
3.4M    ./1618805524339384000
3.2M    ./1618805654958242000
3.1M    ./1618805650981601000
3.0M    ./1618803284849659000
1.2G    ./1618804042744790000
1.1G    ./1618805257613027000
```
```
[root@milvus-writable-7c45b78c4c-gns8j 1618801438425356000]# du -h -d1 | wc
    651    1302   17360
```

**Stats result**
```
Status(code=0, message='Success')
{   'partitions': [   {'row_count': 0, 'segments': None, 'tag': '_default'},
                      {   'row_count': 501998,
                          'segments': [   {   'data_size': 1252737912,
                                              'index_name': 'IDMAP',
                                              'name': '1618804042744790000',
                                              'row_count': 203631},
                                          {   'data_size': 1138150760,
                                              'index_name': 'IDMAP',
                                              'name': '1618805257613027000',
                                              'row_count': 185005},
                                          {   'data_size': 561148528,
                                              'index_name': 'IDMAP',
                                              'name': '1618805856154113000',
                                              'row_count': 91214},
                                          {   'data_size': 97816800,
                                              'index_name': 'IDMAP',
                                              'name': '1618805925330843000',
                                              'row_count': 15900},
                                          {   'data_size': 38437696,
                                              'index_name': 'IDMAP',
                                              'name': '1618805937842108000',
                                              'row_count': 6248}],
                          'tag': '2021-01'}],
    'row_count': 501998}
```
