### ISSUE TITLE
Writable and readOnly pod cannot access same PVC

### ISSUE THREAD

**Issue by apurvamishra20** [milvus-io/milvus#5073]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
While running milvus with mishards and GPU enable, the created readOnly and writeable milvus po cannot access same PVC with access mode ReadOnlyMany

**Steps/Code to reproduce behavior**
Deploy Milvus with cluster.enable: true, persistence.enabled: true and gpu.enabled: true. 
The readOnly pod didn't start with the following error:

attachdetach-controller  AttachVolume.Attach failed for volume "pvc-XXXXXX : googleapi: Error 400: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE - The disk resource 'projects/projectnamezones/us-west1-a/disks/gke  -****-pvc-XXXXXXX' is already being used by 'projects/projectname/zones/us-west1-a/instances/gke-gpu-**********

**Expected behavior**
Pod should be started successfully

**Method of installation**

- [x] Docker/gpu

**Environment details**
- GKE, GKE persistance disk

- Milvus version (master or released version)
0.10.2

**Configuration file**

```yaml
mishards_config.yaml:

FROM_EXAMPLE='true'
SQLALCHEMY_DATABASE_URI=mysql://root:milvusroot@namespace-mysql:3306/milvus

DEBUG=true
SERVER_PORT=19530
WOSERVER=tcp://milvus-writable:19530
DISCOVERY_PLUGIN_PATH=static
DISCOVERY_STATIC_HOSTS=milvus-writable,milvus-readonly
DISCOVERY_STATIC_PORT=19530

TRACER_CLASS_NAME=jaeger
TRACING_SERVICE_NAME=mishards-demo
TRACING_REPORTING_HOST=jaeger
TRACING_REPORTING_PORT=5775

readonly_server_config.yaml:
version: 0.5 
cluster:
  enable: true
  role: ro
general:
  timezone: UTC+8
  meta_uri: mysql://root:milvusroot@namespace-mysql:3306/milvus
network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: false
  http.port: 19121
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: false
  recovery_error_ignore: true
  buffer_size: 256MB
  path: /var/lib/milvus/db/wal
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:
gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
 logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

server_config.yaml:
version: 0.5 
cluster:
  enable: true
  role: rw
general:
  timezone: UTC+8
  meta_uri: mysql://root:milvusroot@namespace-mysql:3306/milvus
network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/db/wal
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: true
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
 
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
metric:
  enable: false
  address: 127.0.0.1
  port: 9091
```

**Additional context**
All pods are running on GPU whereas readonly.gpu.enabled=false
