### ISSUE TITLE
Accuracy decreased

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5227]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
standalone version.
```
sift_128_euclidean, index_type: IVF_SQ8, metric_type: L2
index: {'nlist': 1024}
search: {'nprobe': [1,2,...,128,512]}
```
```
W
benchmark-test-95kzg-3855789697: 2021-05-14 08:10:59,155 - milvus_benchmark.client:236 - INFO - Building index start, collection_nam
e: sift_128_euclidean, index_type: IVF_SQ8, metric_type: L2
benchmark-test-95kzg-3855789697: 2021-05-14 08:10:59,155 - milvus_benchmark.client:238 - INFO - {'nlist': 1024}
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:35,975 - milvus_benchmark.client:49 - DEBUG - Milvus create_index run in 36.82s
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:35,979 - milvus_benchmark.client:251 - INFO - None
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:35,979 - milvus_benchmark.runners.accuracy:244 - INFO - {'index_type': 'flat', 'me
tric_type': None, 'index_param': None}
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:35,979 - milvus_benchmark.runners.accuracy:245 - INFO - Start load collection: sif
t_128_euclidean
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:35,981 - milvus_benchmark.client:49 - DEBUG - Milvus release_collection run in 0.0
s
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:40,018 - milvus_benchmark.client:49 - DEBUG - Milvus load_collection run in 4.04s
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:40,018 - milvus_benchmark.runners.accuracy:248 - INFO - End load collection: sift_
128_euclidean
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:40,167 - milvus_benchmark.main:89 - INFO - Start run case
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:41,653 - milvus_benchmark.client:49 - DEBUG - Milvus query run in 1.49s
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:42,326 - milvus_benchmark.main:99 - INFO - {'acc': 0.009}
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:42,327 - milvus_benchmark.main:106 - DEBUG - {'type': 'ann_accuracy', 'value': {'a
cc': 0.009}}
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:43,914 - milvus_benchmark.client:49 - DEBUG - Milvus query run in 1.59s
benchmark-test-95kzg-3855789697: 2021-05-14 08:11:44,578 - milvus_benchmark.main:99 - INFO - {'acc': 0.013}
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
`zilliztech/milvus_benchmark`
branch: argo
yaml: 
```
ann_accuracy:
  collections:
    -
      milvus:
        cache_config.cpu_cache_capacity: 16GB
        engine_config.use_blas_threshold: 1100
      server:
        cpus: 12
      source_file: /test/milvus/ann_hdf5/sift-128-euclidean.hdf5
      collection_name: sift_128_euclidean
      index_types: ['flat']
      index_params:
        nlist: [1024]
      top_ks: [10]
      nqs: [10000]
      search_params:
        nprobe: [1]
```
