### ISSUE TITLE
Building index is too slow on CPU

### ISSUE THREAD

**Issue by sweshixing** [milvus-io/milvus#5299]
**Describe the bug**
I'm building about 110 million vectors whose dimension is 256.And in milvus, the data was splited to many 2GB files, but it was too slow while building IVFSQ8 index.

As this [ #2293](https://github.com/milvus-io/milvus/issues/2293#issuecomment-626562637) you replied `build index for an 1GB file could cost about 5~10 minute in a 12 cores machine.` But my machine has 40 cores, it cost about 1 hour for a 2GB file , it was slower than you mentioned. 

So why  my building index in CPU is so slow?

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
> OS: Ubuntu 18.04
> CPU:  Intel(R) Xeon(R) Silver 4210R CPU
> GPU: RTX3090(cannot use)
> Memory: 384GB

- Milvus version (master or released version)
milvus-cpu 1.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
cache:
  cache_size: 60
  insert_buffer_size: 1
  preload_collection:

gpu:
  enable: false
  cache_size: 8
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu1
    - gpu2
    
fpga:
   enable: false
   search_devices:
     - fpga0
```

**Screenshots**
The recent debug log file :
![debug_log](https://user-images.githubusercontent.com/24455669/118780444-a36c1a80-b8be-11eb-9003-cf16827e003f.png)

The recent info log file:
![info_log](https://user-images.githubusercontent.com/24455669/118780401-97805880-b8be-11eb-8017-964f1c4a1b6a.png)

The recent warning log file:
![warning_log](https://user-images.githubusercontent.com/24455669/118780519-b5e65400-b8be-11eb-9be7-e94f22b8ed6f.png)

**Additional context**
