### ISSUE TITLE
Index file is not loaded in memory

### ISSUE THREAD

**Issue by sweshixing** [milvus-io/milvus#5308]
**Describe the bug**
After building IVF_SQ8 index, I started to call search() in python. Logically, the Index file would be loaded in memory for cpu cache, but my milvus-server only toke 2.2GB memory. It seemed like that there was no index file in cache, and my cpu.cache_size is 60GB which is bigger than the amount of the index files' size.Because of not loading index file to memory, it was so slow to search vector.

How could this happened? Why the index files were not loaded in memory？

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
> OS: Ubuntu 18.04
> CPU: Intel(R) Xeon(R) Silver 4210R CPU
> GPU: RTX3090(cannot use)
> Memory: 384GB

- Milvus version (master or released version)
milvus-cpu 1.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
cache:
  cache_size: 60
  insert_buffer_size: 1
  preload_collection:

gpu:
  enable: false
  cache_size: 8
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu1
    - gpu2
    
fpga:
   enable: false
   search_devices:
     - fpga0
```
