### ISSUE TITLE
Search with s3 storage backend got invalid vector id.

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus#5390]
**Describe the bug**
Search with s3 storage backend got invalid vector id.

**Steps/Code to reproduce behavior**
Compiling with S3 support, and using the official example.py and check the final returned vector ids.

**Expected behavior**
We want to see:
``` plain
Query result is correct
[
 [ (id:0, distance:0.0) ]
 [ (id:1, distance:0.0) ]
 [ (id:2, distance:0.0) ]
        ......
            ......
]

```

but finally got a result like:

```
Query result is correct
[
 [ (id:80000, distance:0.0) ]
 [ (id:0, distance:0.0) ]
 [ (id:1, distance:0.0) ]
        ......
            ......
]
```

The id:80000 is not valid, as we only have ids(0..9999).

**Method of installation**
- [x] Docker/cpu
- [x] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
N/A

- Milvus version (master or released version)
1.1 branch

**Configuration file**
default config with s3 extra configuration:
``` yaml
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
  s3_enabled: true
  s3_address: 192.168.18.161
  s3_port: 7480
  s3_access_key: ********
  s3_secret_key: ***************************
  s3_bucket: milvus

```

**Screenshots**
N/A

**Additional context**
After checking the implementation of `S3IOReader`. in the `read` function, it does not update the `_pos` after the read. IMO, it should keep the original behavior as DiskIOReader does.
I'll raise PR for it.
