### ISSUE TITLE
Memory usage keeps going up when deploy standalone mode on k8s

### ISSUE THREAD

**Issue by zwd1208** [milvus-io/milvus#5463]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I deploy a standalone milvus2.0 instance on k8s and I'm just testing the prometheus metrics. No any test case are run, but
I've observed that memory usage keeps going up.

**Steps/Code to reproduce behavior**
helm install -n test --set image.all.repository=registry.zilliz.com/milvus/milvus --set image.all.tag=master-latest --set minio.persistence.enabled=false  --set etcd.persistence.enabled=false testbyzwd .

**Expected behavior**
Memory can be freed normally

**Method of installation**
- [*] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- K8S Node 16c64G Centos7

- Milvus version (master or released version)
master

**Configuration file**
milvus.yaml

```yaml
nodeID: # will be deprecated after v0.2
  proxyIDList: [0]
  queryNodeIDList: [1]
  dataNodeIDList: [2]

etcd:
  address: testbyzwd-etcd
  port: 2379
  rootPath: by-dev
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
  segFlushMetaSubPath: writer/segment
  ddlFlushMetaSubPath: writer/ddl
  writeNodeSegKvSubPath: writer/segment # GOOSE TODO: remove this
  writeNodeDDLKvSubPath: writer/ddl # GOOSE TODO: remove this
  segThreshold: 10000

minio:
  address: testbyzwd-minio
  port: 2379
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: "a-bucket"

pulsar:
  address: testbyzwd-milvus-ha-pulsar
  port: 6650
  authentication: false
  user: user-default
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.ipevRNuRP6HflG8cFKnmUPtypruRC4fb1DWtoLL62SY

master:
  address: localhost
  port: 53100

proxyService:
  address: localhost
  port: 21122

proxyNode:
  port: 19530

queryService:
  address: localhost
  port: 19531

queryNode:
  gracefulTime: 5000 #ms
  port: 21123

indexService:
  address: localhost
  port: 31000

indexNode:
  port: 21121

dataService:
  address: localhost
  port: 13333

dataNode:
  port: 21124

log:
  level: debug
  file:
    rootPath: ""
    maxSize: 300
    maxAge: 10
    maxBackups: 20
  dev: true
  format: text
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15153901/119802642-4a7d3180-bf11-11eb-9af7-272b31b8680d.png)
