### ISSUE TITLE
DropIndex/DropCollection blocked when milvus is indexing the collection on the backgroud

### ISSUE THREAD

**Issue by hawkphantomnet** [milvus-io/milvus#5530]
**Please state your issue using the following template and, most importantly, in English.**
DropIndex/DropCollection blocked when milvus is indexing the collection on the backgroud.

**Describe the bug**
We created a collection and create index(IVF_PQ) before inserting data.
When we have inserted 800w+ 1024-dim vectors, we try to dropCollection.
The dropCollection request get hanged, and from the debug log we can see milvus keep indexing the colleciton we want to delete.
So does dropIndex request.

**Steps/Code to reproduce behavior**
Act like the description above.

**Expected behavior**
We want milvus stop indexing and drop the collection.

**Method of installation**
Docker/cpu

**Environment details**
- OS: CentOS Linux release 7.8.2003 (Core)
  CPU: kubernetes pod with 16 Cores CPU
  Memory: kubernetes pod with 120G Memory

- Milvus version (master or released version)
milvus:0.10.4-cpu-d120220-e72454

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.5

network: 
  bind.address: 0.0.0.0
  bind.port: 19000
  http.enable: true
  http.port: 19121

cluster:
  enable: true
  role: rw

general:
  timezone: UTC+8
  meta_uri: mysql://xxx@xxxx:3306/xxx

storage:
  path: /var/milvus
  auto_flush_interval: 1

cache:
  cache_size: 100GB
  insert_buffer_size: 1GB

engine_config:
  use_blas_threshold: 800
  gpu_search_threshold: 1000

wal:
  enable: false
  path: /data/wal

logs:
  path: /data/logs
```

**Screenshots**

**Additional context**
