### ISSUE TITLE
Server has been stopped building index and trying upload collections to cache over and over

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus#5701]
I have one Milvus-write server 1.1.0

Few collections and few partitions inside each collections.
Total amount of data: ~250M vectors

My server is building index for last couple of hours (probably day+) and it ate the all available cpu's. But now it stoped trying to build index and start trying upload data to cache over and over. (cpu usage is 0+ and memory usage is weird (attached)).
In the server logs I saw that its trying to upload collections to memory and when it try to eat more then I have in cache configuration it's bump back to 16GiB ~ and trying to eat all memory again. 

Information from MySQL:
- row count for type 1: 2 177 590
- row count for type 2: 55 354 046
- row count for type 3: 163 894 614

As I understand type 1 is a raw data. Type 2 data that should be "in progress" right now. Type 3 is a finished (with index) data.

Question:
1. Is it right about types? 
2. How can I ask milvus to continue build index? Or it's try to eat memory like a step between?

**Environment details**
- Node deployed under k8s with your helm chart
- Requested resources: 64 CPU and 32G memory
- Limits: 78 CPU and 36G memory

- Milvus version (master or released version)
1.1.0 cpu image from helm

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
version: 0.5 

cluster:
  enable: false
  role: rw

general:
  timezone: UTC+8
  meta_uri: *********secured**********

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: false
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/db/wal

cache:
  cache_size: 26GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

```

**Screenshots**
CPU:
<img width="766" alt="cpu" src="https://user-images.githubusercontent.com/3996622/121377793-50303980-c94b-11eb-8de5-97811be4386a.png">

MEMORY:
<img width="757" alt="memory" src="https://user-images.githubusercontent.com/3996622/121377799-51616680-c94b-11eb-9886-58a756ac940f.png">
