### ISSUE TITLE
Proxy state is abnormal

### ISSUE THREAD

**Issue by xuqinkun** [milvus-io/milvus#6332]
I build milvus from source code which is latest version, and start it through following commands:
nohup /home/std/xqk/code/v2/milvus/bin/milvus run rootcoord > ~/rootcoord.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run datacoord > ~/datacoord.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run datanode > ~/datanode.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run querycoord > ~/querycoord.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run querynode > ~/querynode1.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run indexcoord > ~/indexcoord.log 2>&1 &
nohup /home/std/xqk/code/v2/milvus/bin/milvus run indexnode > ~/indexnode.log 2>&1 &

But the log of proxy shows that the state is abnormal

![image](https://user-images.githubusercontent.com/19572081/124694619-3cf59700-df14-11eb-9a21-297efcc6aa0a.png)

When I try to connect milvus by pymilvus_orm, I got an error "server is not healthy, please try again later".
![image](https://user-images.githubusercontent.com/19572081/124694782-8645e680-df14-11eb-892d-b5377cd6d78b.png)

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
v2.0.0-rc1

**Configuration file**
```yaml
etcd:
  endpoints:
    - localhost:2379
  rootPath: by-dev
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
  segmentBinlogSubPath: datacoord/binlog/segment  # Full Path = rootPath/metaSubPath/segmentBinlogSubPath
  collectionBinlogSubPath: datacoord/binlog/collection # Full Path = rootPath/metaSubPath/collectionBinglogSubPath
  flushStreamPosSubPath: datacoord/flushstream # Full path = rootPath/metaSubPath/flushStreamPosSubPath
  statsStreamPosSubPath: datacoord/statsstream # Full path = rootPath/metaSubPath/statsStreamPosSubPath

minio:
  address: localhost
  port: 9000
  accessKeyID: xqk
  secretAccessKey: xqk111000
  useSSL: false
  bucketName: "a-bucket"

pulsar:
  address: localhost
  port: 6650
  maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes

rocksmq:
  path: /var/lib/milvus/rdb_data

rootCoord:
  address: localhost
  port: 53100

proxy:
  port: 19530

queryCoord:
  address: localhost
  port: 19531

queryNode:
  gracefulTime: 1000 # ms, for search
  port: 21123

indexCoord:
  address: localhost
  port: 31000

indexNode:
  port: 21121

dataCoord:
  address: localhost
  port: 13333

dataNode:
  port: 21124

log:
  level: debug # info, warn, error, panic, fatal
  file:
    rootPath: "" # default to stdout, stderr
    maxSize: 300 # MB
    maxAge: 10 # day
    maxBackups: 20
  format: text # text/json
```
The all config files are not changed.
