### ISSUE TITLE
Scaling nodes causes issues

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#6355]
**Describe the bug**
When manually adding an index/query/data node to an established AWS cluster, sometimes all subsequent tasks are sent to one node. 

**Steps/Code to reproduce behavior**
Manually launching a new node then applying this ansible script to it:
```yaml
- name: Scale Index
  hosts: index_ips_public
  remote_user: ec2-user
  become: true
  vars:
    etcd_ip: "{{groups['etcd_ips_private'][0]}}"
    minio_ip: "{{groups['minio_ips_private'][0]}}"
    pulsar_ip: "{{groups['pulsar_ips_private'][0]}}"
    indexcoord_ip: "{{groups['index_coordinator_ips_private'][0]}}"


  tags:
    - scale_index

  tasks:
  - name: Install docker
    ansible.builtin.yum:
      name: docker
      state: present
  - name: Run docker
    ansible.builtin.service:
      name: docker
      state: started

  - name: Install or upgrade docker-compose
    get_url: 
      url : "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
      force: yes
  - name: Create symbolic link for docker-compose
    file:
      src: "/usr/local/bin/docker-compose"
      dest: "/usr/bin/docker-compose"
      state: link

  - name: Copy index config
    ansible.builtin.template:
      src: ./yaml_files/indexnode.j2
      dest: /home/ec2-user/docker-compose.yml
      owner: ec2-user
      group: wheel
      mode: '0644'

  - name: Run index node
    shell: docker-compose up -d
    args:
      chdir: /home/ec2-user/
```

**Expected behavior**
Add a new node, all nodes get used. 

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
-AWS EC2

- Milvus 2.0

**Screenshots**
This screenshot shows what happens after a new index node is added and a call for a new index is run:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/81822489/124842020-7bef1100-df43-11eb-9cb1-79060506ebfa.png">

This shows a similar situation but the lead up was a bit different. In this case 3 index nodes were running, one was stopped, then resumed while another node was added and then create index was called:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/81822489/124842042-89a49680-df43-11eb-856d-4bee5a5646cc.png">

**Additional context**
