### ISSUE TITLE
Milvusdm crashed when export collection data

### ISSUE THREAD

**Issue by eeezae** [milvus-io/milvus#6582]
#### Describe the bug:

Test export collection feature data with 10,000 pictures succeed but failed on exporting the collection with 300,000+ pictures.

![image](https://user-images.githubusercontent.com/34007837/125890102-0b6191e6-de7a-4a05-a340-9a38b8437698.png)

![image](https://user-images.githubusercontent.com/34007837/125890118-b873db8d-80e4-4773-9358-8a905c596783.png)

#### Expected behavior:

Export the specified collection data to file.

#### Environment:
- Milvus version(1.0): 
- SDK version(pymilvus v1.0, pymiluvsdm v1.0):
- OS(CentOS el7): 
- CPU/Memory: 4 Core  8g
- GPU: None
- Others: 

#### Configuration file:

M2H.yaml: 
```
M2H:
  milvus_version: 1.0
  source_milvus_path: '/home/root/milvus'
  mysql_parameter:
  source_collection:
    style_collection:
  data_dir: '/home/data'
```
