### ISSUE TITLE
The skip ci conditions lack restrictions on files

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6882]
#### Steps/Code to reproduce:
in  .github/mergify.yml
```
  - name: Test passed for title skip ci
    conditions:
      - base=master
      - title~=\[skip ci\]
    actions:
      label:
        add:
          - ci-passed
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
