### ISSUE TITLE
server is not healthy if external etcd and minio configured

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7221]
#### Steps/Code to reproduce:
1. deploy Milvus with cluster mode with externalS3 and externalEtcd configured
2. trying to connect to Milvus

#### Expected result:
successfully connect to Milvus

#### Actual results:
Exception: server is not healthy, please try again later
checking the proxy log: 
[2021/08/22 04:11:23.517 +00:00] [DEBUG] [service.go:235] [proxy] ["state of proxy"=Initializing]

[proxy.ext.log](https://github.com/milvus-io/milvus/files/7026597/proxy.ext.log)
[querycoord.ext.log](https://github.com/milvus-io/milvus/files/7026598/querycoord.ext.log)
[rootcoord.ext.log](https://github.com/milvus-io/milvus/files/7026599/rootcoord.ext.log)
[datacoord.ext.log](https://github.com/milvus-io/milvus/files/7026600/datacoord.ext.log)
[etcd.ext.data.log](https://github.com/milvus-io/milvus/files/7026601/etcd.ext.data.log)
[etcd.ext.log](https://github.com/milvus-io/milvus/files/7026602/etcd.ext.log)
[indexcoord.ext.log](https://github.com/milvus-io/milvus/files/7026603/indexcoord.ext.log)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master-20210820-bf2c427
- Deployment mode(standalone or cluster): cluster

#### Configuration file:
```
###################################
# External S3
# - these configs are only used when `externalS3.enabled` is true
###################################
externalS3:
  enabled: true
  host: external-minio.chaos-testing.svc.cluster.local
  port: 2379
  accessKey: minioadmin
  secretKey: minioadmin
  useSSL: false
  bucketName: ""

###################################
# External etcd
# - these configs are only used when `externalEtcd.enabled` is true
###################################
externalEtcd:
  enabled: true
  ## the endpoints of the external etcd
  ##
  endpoints:
    - external-etcd.chaos-testing.svc.cluster.local:2379
```

**Comment by thecooltechguy** [comment]
I'm also facing this issue, but I'm not using an external etcd.

**Comment by thecooltechguy** [comment]
Actually, I was able to fix my issue. It was due to insufficient AWS S3 IAM policy permissions that did not give read/write access to the bucket.

**Comment by yanliang567** [comment]
but i use a standalone minio and configure the secrets in the yaml. Also would proxy check the healthy of minio before being healthy itself?

**Comment by xiaocai2333** [comment]
I guess the port of minio is wrong, try port: 9000?

**Comment by yanliang567** [comment]
still fails after using port 9000
```
###################################
# External S3
# - these configs are only used when `externalS3.enabled` is true
###################################
externalS3:
  enabled: true
  host: external-minio.chaos-testing.svc.cluster.local
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  useSSL: false
  bucketName: ""
```

**Comment by yanliang567** [comment]
shall set a bucket name for  external S3 and port 9000
```
###################################
# External S3
# - these configs are only used when `externalS3.enabled` is true
###################################
externalS3:
  enabled: true
  host: external-minio.chaos-testing.svc.cluster.local
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  useSSL: false
  bucketName: "abucket"

###################################
# External etcd
# - these configs are only used when `externalEtcd.enabled` is true
###################################
externalEtcd:
  enabled: true
  ## the endpoints of the external etcd
  ##
  endpoints:
    - external-etcd.chaos-testing.svc.cluster.local:2379
```
