### ISSUE TITLE
Hangs on getting collection entities after NetworkChaos (partition) deleted

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#8069]
#### Steps/Code to reproduce:
1. deploy a cluster milvus by helm accroding to the doc in milvus website (include port-forward)
2. run `hello_milvus.py`
3. inject network chaos (partition) for proxy pod
It means proxy pod can't communicate with other pods during injecting
4. run `hello_milvus.py`
5. delete network chaos 
6. run `hello_milvus.py`
#### Expected result:
step 2 success
step 4 fail
step 6 success
After deleting chaos,milvus is supposed to works well.
#### Actual results:
step 2 success
step 4 fail
step 6 fail
After deleting chaos, run `hello_milvus.py`, the result is output hangs on `Get collection entities...`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):RC6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):RC6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
NetworkChaos yaml content
```
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: test-partition
  namespace: default
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/instance: chaos-milvus
      app.kubernetes.io/name: milvus
  mode: all
  action: partition
  duration: 5m
  direction: both
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app.kubernetes.io/instance: chaos-milvus
        app.kubernetes.io/name: milvus
        component: proxy
    mode: one

```
[k8s_logs.zip](https://github.com/milvus-io/milvus/files/7176183/k8s_logs.zip)
