### ISSUE TITLE
Flush does not get a response when multi milvus share the same pulsar cluster

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#8691]
#### Steps/Code to reproduce:
1. Deploy external distributed etcd, minio and Pulsar
```
external-etcd-0                                    1/1     Running     0          3d22h
external-etcd-1                                    1/1     Running     0          3d22h
external-etcd-2                                    1/1     Running     0          3d22h
external-minio-0                                   1/1     Running     0          3d22h
external-minio-1                                   1/1     Running     0          3d22h
external-minio-2                                   1/1     Running     0          3d22h
external-minio-3                                   1/1     Running     0          3d22h
external-pulsar-autorecovery-84fc5fc58b-r66l5      1/1     Running     0          3d22h
external-pulsar-bastion-5569f656fc-c48wq           1/1     Running     0          3d22h
external-pulsar-bookkeeper-0                       1/1     Running     0          3d22h
external-pulsar-bookkeeper-1                       1/1     Running     0          3d22h
external-pulsar-broker-66cd976fd8-wl987            1/1     Running     0          3d22h
external-pulsar-proxy-64b86d775-2qxwx              2/2     Running     0          3d22h
external-pulsar-zookeeper-0                        1/1     Running     0          3d22h
external-pulsar-zookeeper-1                        1/1     Running     0          3d22h
external-pulsar-zookeeper-2                        1/1     Running     0          3d22h
external-pulsar-zookeeper-metadata-xmpdj           0/1     Completed   0          3d22h
```
2. Deploy `milvus-one` with `etcd.rootPath=by-dev-a`, `minio.bucketName=a-bucket`, `chanNamePrefix.cluster=by-dev-a`
```
helm install --values values_external.yaml --set image.all.repository=milvusdb/milvus-dev --set image.all.tag=master-20210927-77a773d --set cluster.enabled=true --set metadata.rootPath="by-dev-a" --set externalS3.bucketName="a-bucket" --set msgChannel.chanNamePrefix.cluster="by-dev-a" --set service.type=LoadBalancer milvus-one .
```
3. Deploy `milvus-two` with `etcd.rootPath=by-dev-b`, `minio.bucketName=b-bucket`, `chanNamePrefix.cluster=by-dev-b`
```
helm install --values values_external.yaml --set image.all.repository=milvusdb/milvus-dev --set image.all.tag=master-20210927-77a773d --set cluster.enabled=true --set metadata.rootPath="by-dev-b" --set externalS3.bucketName="b-bucket" --set msgChannel.chanNamePrefix.cluster="by-dev-b" --set service.type=LoadBalancer milvus-two .
```
4. Run test_e2e.py on milvus-one and milvus-two

#### Expected result:
All steps in test_e2e.py (create collection, insert, flush, search, create index, search, query) run successfully.

#### Actual results:
1. e2e-test passed on milvus-one
2. milvus-two insert successfully and flush get no response.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  master-20210927-77a773d
- Deployment mode(standalone or cluster):
  cluster milvus with external cluster etcd, minio and Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc7.dev13
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Configuration file:
values_external.yaml
```
minio:
  enabled: false

etcd:
  enabled: false

pulsar:
  enabled: false

externalS3:
  enabled: true
  host: external-minio
  port: 9000
  accessKey: minio-admin
  secretKey: minio-admin
  useSSL: false
  bucketName: "a-bucket"

externalEtcd:
  enabled: true
  ## the endpoints of the external etcd
  ##
  endpoints:
    - external-etcd:2379

externalPulsar:
  enabled: true
  host: external-pulsar-proxy
  port: 6650
```

#### Additional context:
Milvus logs: 
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7235156/milvus_logs.tar.gz)
