### ISSUE TITLE
[Bug]: [benchmark][cluster][performance] recall value is different when the same data size 、index and search params

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#9658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`diff recall with same data size and same index and search params`

test yaml:
server: server-cluster-3rd-8c16m
client: client-acc-sift-hnsw-perf

redash: 2.0_rc7_acc_hnsw_group_by_ef

![image](https://user-images.githubusercontent.com/26307815/136777446-4b5c5f96-964c-4fa1-8a0c-12abf8e50790.png)

### Expected Behavior

recall value is the same when the same data size 、index and search params

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Anything else?
client-acc-sift-hnsw-perf：
```
ann_accuracy:
      collections:
        -
          milvus:
            cache_config.cpu_cache_capacity: 16GB
            engine_config.use_blas_threshold: 1100
          source_file: /test/milvus/ann_hdf5/sift-128-euclidean.hdf5
          collection_name: sift_128_euclidean
          index_types: ['hnsw']
          index_params:
            M: [16]
            efConstruction: [500]
          top_ks: [10]
          nqs: [1, 100, 1000, 2000, 5000, 10000]
          search_params:
            ef: [16, 32, 64, 128, 256, 512]
```
